### ISSUE TITLE
opening a skill window while a different one is open causes a lua error

### ISSUE THREAD

**Issue by Kherae** [Auctionator/Auctionator#1001]
## Brief Description of Bug
activating a profession to open its skill window while another profession skill window is open causes a lua error.

## Steps to Reproduce
press K. click profession 1 to open its window. click profession 2 to open its window.

## Loaded Addons
auctionator, addon control panel

## Back Trace (LUA Error Output)
Message: Usage: local numReagents = C_TradeSkillUI.GetRecipeNumReagents(recipeSpellID [, recipeLevel])
Time: Thu Feb 18 15:24:58 2021
Count: 5
Stack: Usage: local numReagents = C_TradeSkillUI.GetRecipeNumReagents(recipeSpellID [, recipeLevel])
[string "=[C]"]: in function `GetRecipeNumReagents'
[string "@Interface\AddOns\Auctionator\Source\ReagentSearch\Main.lua"]:22: in function `GetSkillReagentsTotal'
[string "@Interface\AddOns\Auctionator\Source\ReagentSearch\Mixins\Button.lua"]:31: in function `UpdateTotal'
[string "@Interface\AddOns\Auctionator\Source\ReagentSearch\Mixins\Button.lua"]:15: in function <...s\Auctionator\Source\ReagentSearch\Mixins\Button.lua:14>
[string "=[C]"]: in function `SetSelectedRecipeLevel'
[string "@Interface\AddOns\Blizzard_TradeSkillUI\Blizzard_TradeSkillDetails.lua"]:90: in function `SetSelectedRecipeID'
[string "@Interface\AddOns\Blizzard_TradeSkillUI\Blizzard_TradeSkillUI.lua"]:157: in function <...dOns\Blizzard_TradeSkillUI\Blizzard_TradeSkillUI.lua:156>
[string "=[C]"]: in function `OnRecipeChanged'
[string "@Interface\AddOns\Blizzard_TradeSkillUI\Blizzard_TradeSkillUI.lua"]:24: in function `recipeChangedCallback'
[string "@Interface\AddOns\Blizzard_TradeSkillUI\Blizzard_TradeSkillRecipeList.lua"]:494: in function `SetSelectedRecipeID'
[string "@Interface\AddOns\Blizzard_TradeSkillUI\Blizzard_TradeSkillRecipeList.lua"]:82: in function `OnDataSourceChanging'
[string "@Interface\AddOns\Blizzard_TradeSkillUI\Blizzard_TradeSkillUI.lua"]:46: in function <...dOns\Blizzard_TradeSkillUI\Blizzard_TradeSkillUI.lua:42>

Locals: (*temporary) = "Usage: local numReagents = C_TradeSkillUI.GetRecipeNumReagents(recipeSpellID [, recipeLevel])"

**Comment by Kherae** [comment]
additional information through debugging: 
/source/ReagentSearch/main.lua@18, recipeIndex variable is sometimes assigned nil, which is why the error occurs. fallback code should be inserted immediately after that point: `if not recipeIndex  then return 0 end`

**Comment by plusmouse** [comment]
Thanks for the report. Just released 9.0.6.1 which will fix the issue.
