### ISSUE TITLE
icone in professions window over lap the to craft prise

### ISSUE THREAD

**Issue by Alfbnielens** [Auctionator/Auctionator#1002]
![move icon](https://user-images.githubusercontent.com/79406273/108625922-c4eb7080-744d-11eb-84bf-5caf7e5547f4.png)

hej 

as seen on the picure is overlaping i am useing https://www.curseforge.com/wow/addons/cloudy-trade-skill 

if i turen cloudy-trade-skill  off the it is working as it shout

**Comment by plusmouse** [comment]
This is now fixed in alpha 521 (if you need help downloading it message back):
![image](https://user-images.githubusercontent.com/60280559/108626410-e47f9a80-7447-11eb-89b7-aa7f161e3877.png)

**Comment by plusmouse** [comment]
If curseforge hasn't updated the alphas to 521 by the time you read this, you can get the alpha from https://github.com/Auctionator/Auctionator/releases/download/521-alpha/Auctionator-alpha-521.zip instead.

**Comment by Alfbnielens** [comment]
wow thx for the fast fix working like a charem 

good day to you =)
