### ISSUE TITLE
Price history in tooltips.

### ISSUE THREAD

**Issue by Tarkumi** [Auctionator/Auctionator#1007]
Could you implement a feature to show the item price history in the tooltip on a keypress? Like Ctrl or Alt.

**Comment by plusmouse** [comment]
Something like:
![image](https://user-images.githubusercontent.com/60280559/108986406-fcdef780-7689-11eb-948a-87c35491edb3.png)

**Comment by Tarkumi** [comment]
Exactly, that would be great!

**Comment by plusmouse** [comment]
While we can implement the feature, this is sufficiently invasive that it will need to be disabled by default (the price history is a pretty big thing to add to a tooltip, even with a modifier key), and adding a feature that needs to be hidden in that way is undesirable.

**Comment by plusmouse** [comment]
Its possible to hook into Auctionator to add it yourself though:
```lua
hooksecurefunc(Auctionator.Tooltip, "ShowTipWithPricingDBKey", function(tooltipFrame, dbKeys)
  if IsAltKeyDown() then
    for index, entry in ipairs(Auctionator.Database:GetPriceHistory(dbKeys[1])) do
      tooltipFrame:AddDoubleLine(entry.date, WHITE_FONT_COLOR:WrapTextInColorCode(Auctionator.Utilities.CreateMoneyString(entry.minSeen)))
    end
  end
  tooltipFrame:Show()
end)
```
