### ISSUE TITLE
Delete shopping list dropdownmenu error

### ISSUE THREAD

**Issue by ceylina** [Auctionator/Auctionator#101]
Please include as much of the following information as possible to help me fix the bug:
## Brief Description of Bug

Make sure to not have the AH open when trying to reproduce this. I opened the auctionator settings through interface options

After creating a new shopping list and clicking accept the following error appears

This may or may not be a valid error but leaving it here for research purposes
## Back Trace (LUA Error Output)

FrameXML\UIDropDownMenu.lua:682: attempt to index local 'frame' (a nil value)
FrameXML\UIDropDownMenu.lua:682: in function `UIDropDownMenu_SetSelectedValue'
Auctionator\AuctionatorShop.lua:578: in function <Auctionator\AuctionatorShop.lua:569>
Auctionator\AuctionatorShop.lua:599: in function`OnAccept'
FrameXML\StaticPopup.lua:4256: in function `StaticPopup_OnClick'
[string "_:OnClick"]:1: in function <[string "_:OnClick"]:1>

Locals:
frame = nil
value = 3
useValue = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = "attempt to index local 'frame' (a nil value)"

To reporduce:

Only have auctionator loaded
reload UI (/reload)
Open interface options (DO NOT open AH)
Select Auctionator in Addons and click to Shopping Lists
Click New
Type a name click accept.

**Comment by ceylina** [comment]
New button and rename button no longer error but pressing delete on a shopping list without he AH open at least once will throw and error

Renaming a shopping list while that list is selected in the dropdown list will not rename the list. You must pulldown the dropdown menu again to refresh.

**Comment by ceylina** [comment]
Event triggers of note:

AUCTION_HOUSE_CLOSED - "Fires when the player ends interaction with an auction house"

AUCTION_HOUSE_SHOW - "Fires when the player begins interaction with an auction house"

**Comment by ShaunDreclin** [comment]
This should be re-opened, I'm getting the same error when I try to delete a shopping list from interface options.

```
Message: Interface\FrameXML\UIDropDownMenu.lua:857: attempt to index local 'frame' (a nil value)
Time: Mon Nov 19 00:46:38 2018
Count: 1
Stack: Interface\FrameXML\UIDropDownMenu.lua:857: attempt to index local 'frame' (a nil value)
Interface\FrameXML\UIDropDownMenu.lua:857: in function `UIDropDownMenu_SetSelectedValue'
Interface\AddOns\Auctionator\AuctionatorShop.lua:777: in function `Atr_ShpList_SetToRecents'
Interface\AddOns\Auctionator\AuctionatorConfig.lua:1121: in function `OnAccept'
Interface\FrameXML\StaticPopup.lua:4973: in function `StaticPopup_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals: frame = nil
value = 1
useValue = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'frame' (a nil value)"
```
