### ISSUE TITLE
Use pet level for finding prices (like iLvl for equipment)

### ISSUE THREAD

**Issue by DaBear78** [Auctionator/Auctionator#1014]
The feature for also comparing the itemlevel to find a price for an item to sell is great. Can this also be done for pet levels? Because I don't want to sell my lvl 25 pet for the same price as everybody else sells their lvl 1 pets for ;)

**Comment by plusmouse** [comment]
It technically can be done, but would complicate the code that searches for items (gear has a simple way to make the search work, adding in pet levels is more complicated). Closing as unlikely to implement.
