### ISSUE TITLE
Quantité par defaut

### ISSUE THREAD

**Issue by ossana33** [Auctionator/Auctionator#1016]
Il serait pratique de pouvoir régler la quantité à mettre en vente par catégorie (Conteneurs, consommables, fournitures d'artisanat, amélioration d'objets, etc...)

Avez-vous prévu de faire cela dans une prochaine mise à jour ?

Merci

**Comment by plusmouse** [comment]
This issue has been closed because there are new per-category quantity options in the latest alpha (555) available from https://github.com/Auctionator/Auctionator/releases/tag/555-alpha

**Comment by ossana33** [comment]
Merci
 Merci 
Merci !!! 

Big Kiss 😉

Provenance : Courrier pour Windows 10

De : plusmouse
Envoyé le :mercredi 17 mars 2021 17:29
À : Auctionator/Auctionator
Cc : ossana33; Author
Objet :Re: [Auctionator/Auctionator] Quantité par defaut (#1016)

This issue has been closed because there are new per-category quantity options in the latest alpha (555) available from https://github.com/Auctionator/Auctionator/releases/tag/555-alpha
