### ISSUE TITLE
Error when using the Selling tab

### ISSUE THREAD

**Issue by Alinnia** [Auctionator/Auctionator#1017]
## Brief Description of Bug
Get this error when using the Selling tab.

## Steps to Reproduce
Get the error sometimes.

## Back Trace (LUA Error Output)
60x ...lizzard_AuctionHouseUI\Blizzard_AuctionHouseUtil.lua:321: attempt to compare number with nil
[string "@Blizzard_AuctionHouseUI\Blizzard_AuctionHouseUtil.lua"]:321: in function `AddSellersToTooltip'
[string "@Blizzard_AuctionHouseUI\Blizzard_AuctionHouseUtil.lua"]:335: in function `AddAuctionHouseTooltipInfo'
[string "@Blizzard_AuctionHouseUI\Blizzard_AuctionHouseUtil.lua"]:540: in function <...lizzard_AuctionHouseUI\Blizzard_AuctionHouseUtil.lua:512>
[string "=[C]"]: in function `SetAuctionHouseTooltip'
[string "@Blizzard_AuctionHouseUI\Blizzard_AuctionHouseUtil.lua"]:563: in function `LineOnEnterCallback'
[string "@Auctionator\Source\Tabs\ResultsListing\Mixins\SellSearchRow.lua"]:14: in function `OnEnter'
[string "@Auctionator\Source\Components\ResultsListing\Mixins\AuctionatorCell.lua"]:10: in function <...Components\ResultsListing\Mixins\AuctionatorCell.lua:8>

Locals:
tooltip = GameTooltip {
 BottomLeftCorner = <unnamed> {
 }
 SetQuestLogRewardSpell = <function> defined @TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:419
 SetText = <function> defined =[C]:-1
 OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:195
 GetBackdropColor = <function> defined @SharedXML\Backdrop.lua:433
 SetHyperlink = <function> defined @TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:419
 RightEdge = <unnamed> {
 }
 SetVoidWithdrawalItem = <function> defined =[C]:-1
 SetSocketGem = <function> defined =[C]:-1
 ClearBackdrop = <function> defined @SharedXML\Backdrop.lua:325
 Show = <function> defined =[C]:-1
 SetPetAction = <function> defined @TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:419
 SetLootItem = <function> defined @TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:419
 numMoneyFrames = 2
 SetRecipeReagentItem = <function> defined @TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:419
 SetBuybackItem = <function> defined @TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:419
 SetWeeklyReward = <function> defined =[C]:-1
 SetMerchantItem = <function> defined @TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:419
 SetupTextureCoordinates = <function> defined @SharedXML\Backdrop.lua:257
 BottomOverlay = <unnamed> {
 }
 SetTalent = <function> defined @TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:419
 LibExtraTipRight = <table> {
 }
 backdropInfo = <table> {
 }
 GetEdgeSize = <function> defined @SharedXML\Backdrop.lua:231
 SetInventoryItem = <function> defined @TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:419
 TopEdge = <unnamed> {
 }
 SetLootRollItem = <function> defined @TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:419
 SetBagItem = <function> defined @TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:419
 comparing = false
 BottomRightCorner = <unnamed> {
 }
 SetBackdropColor = <function> defined @SharedXML\Backdrop.lua:442
 LeftEdge = <unnamed> {
 }
 waitingForData = false
 SetUnitBuff = <function> defined =[C]:-1
 SetQuestRewardSpell = <function> defined @TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:419
 SetShapeshift = <function> defined @TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:419
 SetHeirloomByItemID = <function> defined =[C]:-1
 textLeft1Font = "GameTooltipHeaderText"
 SetTrainerService = <function> defined @TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:419
 SetVoidDepositItem = <function> defined =[C]:-1
 SetCurrencyToken = <function> defined @TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:419
 SetGuildBankItem = <function> defined @TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:419
 updateTooltipTimer = 0.137000
 SetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:465
 SetVoidItem = <function> defined =[C]:-1
 Hide = <function> defined =[C]:-1
 SetExistingSocketGem = <function> defined =[C]:-1
 HasBackdropInfo = <function> defined @SharedXML\Backdrop.lua:321
 template = "Transparent"
 textRight2Font = "GameTooltipText"
 ApplyBackdrop = <function> defined @SharedXML\Backdrop.lua:337
 SetBackdrop = <function> defined @SharedXML\Backdrop.lua:372
 TopOverlay = <unnamed> {
 }
 GetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:452
 GetBackdrop = <function> defined @SharedXML\Backdrop.lua:390
 SetUnitDebuff = <function> defined =[C]:-1
 SetItemByID = <function> defined =[C]:-1
 SetQuestItem = <function> defined @TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:419
 customBackdropAlpha = 0.800000
 SetBorderBlendMode = <function> defined @SharedXML\Backdrop.lua:309
 SetToyByItemID = <function> defined =[C]:-1
 itemCleared = true
 StatusBar = GameT

**Comment by plusmouse** [comment]
Found out what was causing it (minor API change), pushed a fix which should in alpha 550 shortly
