### ISSUE TITLE
Selling panel: do not switch current item when item is sold

### ISSUE THREAD

**Issue by cyberalien** [Auctionator/Auctionator#1019]
**Is your feature request related to a problem? Please describe.**
Currently when any item is sold and selling panel is active, add-on switches to item that has been sold. This is annoying because it often happens when I'm posting another item and possibly canceling undercut items of that another item.

Example: I have currently selected "Enchant Ring - Tenet of Haste", about to put 2 more items and cancel undercut. Then someone buys auction for "Enchant Ring - Tenet of Versatility". Auctionator immediately switches to versatility enchant in selling tab, preventing me from canceling undercuts for haste enchant.

**Describe the solution you'd like**
I'd like Auctionator to not automatically change selected item or at least have an option to disable it.

**Comment by plusmouse** [comment]
It shouldn't be doing that. Do you have any other auction house add-ons installed?

**Comment by plusmouse** [comment]
Update: Managed to replicate the issue, looking into solutions.

**Comment by plusmouse** [comment]
Updated update: Seems to be erratic, doesn't happen every time an auction sells.

**Comment by plusmouse** [comment]
Fixed in alpha 553

**Comment by cyberalien** [comment]
Thank you.

Tried code from this repo, bug is sort of fixed. Now it no longer switches to another item, but it still refreshes currently selected item and something bugs out because after that I cannot cancel auction for currently selected item.

Example: I'm about to cancel enchant from selling tab of add-on, someone buys my bag. Panel refreshes. After that right clicking on enchant in auctions list (trying to cancel it) doesn't do anything.

**Comment by cyberalien** [comment]
Actually, I was wrong. It does cancel auction, just doesn't update auctions list. Probably a different unrelated bug.

**Comment by plusmouse** [comment]
The bug was related (caused by the code changes to fix this bug). Find the fix in the latest alpha (554)

**Comment by cyberalien** [comment]
Thank you! Now it works perfectly.
