### ISSUE TITLE
Tooltips flooded for grouped battle pets

### ISSUE THREAD

**Issue by Voxxel** [Auctionator/Auctionator#1020]
**Is your feature request related to a problem? Please describe.**
Ex. I'm always frustrated when [I see the battle pets' tooltips are really messed up if used with tooltip addons. See screenshot: 

![WoWScrnShot_032321_081921](https://user-images.githubusercontent.com/3882152/112110004-95e22f00-8bb2-11eb-9912-26708cb61e6b.jpg)

I know it's not an Auctionator issue and that's why I write this ticket to the Feature Request. This is printed by stock WoW UI, I found it in the global strings:
```
AUCTION_HOUSE_BUCKET_VARIATION_PET_TOOLTIP
Pets in this group may vary in stats, level, and quality. Check the auction's tooltip before buying.
```
This text is added to every pet tooltips listed in any group, like stock UI's Favorites or Auctionator's custom lists.]

**Describe the solution you'd like**
It would be very nice if you could add a checkbox to turn off this annoying text on the tooltips.

I was unable to find any settings in the game to eliminate it and I don't understand lua language to write a script for it.

**Comment by plusmouse** [comment]
It looks like the addon you use to display the pet sources is causing an issue. Using an addon that doesn't have that issue like https://www.curseforge.com/wow/addons/battle-pet-tooltip-plus would resolve the issue.
![image](https://user-images.githubusercontent.com/60280559/112111989-d8a10880-8bac-11eb-921e-f74d9cb04ca5.png)

**Comment by Voxxel** [comment]
Very good, thank you for the suggestion!
