### ISSUE TITLE
Translation issue

### ISSUE THREAD

**Issue by DreamOfHero** [Auctionator/Auctionator#1021]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

_Please include a brief description of the bug, including what you were doing, and when it occurred._

## Steps to Reproduce

_Include the steps I would need to follow to reproduce the bug._

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

When an Italian Player sell things on the Auction House, for each thing, Auctionator write in the chat:

[thing] Acquistato a [money]

but "Acquistato a" in Italian mean "Purchased for", but the player is selling and not buying things.
the correct version of that sentence is " messo all'asta per ".
I already changed my itIT.lua file.

**Comment by plusmouse** [comment]
I've updated the translation, it will go out in the next release. Translations are kept track of on Curseforge, which (providing you have a curseforge account) you can edit.

https://www.curseforge.com/wow/addons/auctionator/localization/languages/95/phrases#293470
