### ISSUE TITLE
Selling tab: option to offer to post "Max number minus xx"

### ISSUE THREAD

**Issue by Bubalazzy** [Auctionator/Auctionator#1023]
**Is your feature request related to a problem? Please describe.**
Selling items that I normally keep in my bags, like healing potions, glider kits, etc, often leaves me with none in my bags and I have to produce some more or run to the back to pick a stack. And often enough I totally forget to restock.

**Describe the solution you'd like**
Would be nice to have an option to post "Max number minus ##" by default, or max# minus 1 stack, or as it was in the pre-8.3 Auctionator: offer "max# of full stacks" (that perfectly worked to post, say all 23 stacks of potions, while leaving some for yourself)

**Comment by GandelXIV** [comment]
Could you be more specific?
