### ISSUE TITLE
Shopping tab: more advanced marker for "Owned" column

### ISSUE THREAD

**Issue by Bubalazzy** [Auctionator/Auctionator#1024]
**Is your feature request related to a problem? Please describe.**
There not much space for all the columns in Shopping tab. While I want to see all, it leaves too short space for the names. Leading to something like this:
[Enchant Chest - Etern...
[Enchant Chest - Etern...
[Enchant Chest - Etern...
And I have to mouseover every line to see the name.

**Describe the solution you'd like**
It would be nice to make some of the columns more narrow.
For example: 
The "yes" in the **"owned" column** can be changed to simple * (asterisk) and the title to O? :). 
The **"Available" column** to "Avail" and all numbers to short 4-digits format, like: 9999 then 999k then 999m. Seeing there is available 243255 or 243k is more or less the same. 

**Second thing is:** is it possible to make the marker even more intelligent? Like to scan for undercuts and show * (asterisk) for owned-undercutted or say + (plus) for not-undercutted

**Comment by plusmouse** [comment]
1. Abbreviating terms sometimes causes issues with translation - as not always every language has something short enough to fit in the column. More complete names simplify explaining what a given feature does.
2. That isn't possible without doing additional searches in the background - which will take longer.
