### ISSUE TITLE
Can't see sellable item list on the sell tab

### ISSUE THREAD

**Issue by TzachDana** [Auctionator/Auctionator#1025]
I've just recently download the addon, however when I'm on the sell tab the visual item list isn't showing.. 
I've made sure the option is turned on and reloaded and also disabled any other AH addon installed.
Is there any other known addon compatibility issue or is it something else I'm missing?

**Comment by plusmouse** [comment]
Can you provide a screenshot? Just paste the image into the email/issue comment box.

**Comment by TzachDana** [comment]
![WoWScrnShot_042021_211010](https://user-images.githubusercontent.com/48175414/115444274-04032b80-a21d-11eb-9412-79c296495b8c.jpg)

**Comment by plusmouse** [comment]
Auctionator creates its own tab, called "Selling" - you need to use that tab instead.

**Comment by TzachDana** [comment]
> Auctionator creates its own tab, called "Selling" - you need to use that tab instead.

Well I'm officially an idiot... thanks for the help :)
