### ISSUE TITLE
Shopping Tab: Be able to create a list with deals

### ISSUE THREAD

**Issue by stamicvs** [Auctionator/Auctionator#1026]
Hi plusmouse and team,

thank you very much for you efforts on the addon.
As I am now more and more using it I wanted to ask for a feature, I hope this has not been requested before:

I am currently scanning the auction house every day to  build up a price history database for me. I really  like the view of the price development for single items I am interested in. Now I would like to do more with this historic data. Currently in the shopping tab I created a shopping list for example for all items which I need to create my Legendaries. As I open the List all items are shown and I can click on every item for check the price on the item and its history.

Is there any chance to implement a feature that I can create a shopping list with certain filters and define that it only shows items with good deals, which would mean a percentage undercut in comparison to the historic prices?
So in the configuration of the shopping list I would be able to set a number where items appear in shopping list only if theri price is lower than this percentage compared to the cheapest historic price.
The other alternative instead of the value field would be a checkbox to only show the item if the price is lower than any of the historic scanned prices for the item.

This would be great for looking for good deals on specific items and not having to compare the complete autionhouse for deals.

Bests,
Stamic

**Comment by plusmouse** [comment]
There are price filters inside the shopping list for a specific price.
![image](https://user-images.githubusercontent.com/60280559/119182280-9e4bce80-ba6a-11eb-93aa-ebc758c75b20.png)

I have had a few users setup a sniping view, but even the ones with custom code set the price to watch out for manually.

Determining what is or isn't a good deal is subjective and we tend to avoid providing analytical price information.

Using the cheapest historical price would be mean that the deal would only appear once, as after its appeared it is now the cheapest historic price.

**Comment by plusmouse** [comment]
Adding sniping based on historical prices is outside the scope of the core Auctionator addon, and there's been no further responses. Closing.
