### ISSUE TITLE
Automatically select current item instead of next item.

### ISSUE THREAD

**Issue by SiderealDay** [Auctionator/Auctionator#1028]
**Is your feature request related to a problem? Please describe.**
It is not really a problem but quite an inconvenience.

**Describe the solution you'd like**
At the moment, when I am trying to sell stacks of an item in smaller increments, I have to continuously select the same item to try and sell in stacks of 5 or 10.

In addition to the existing "Automatically select next item" option, I would like to see an option to "Automatically reselect current item" that would continue to select the current item when I am selling it in smaller stacks. And when that item is completely sold, only then would it continue to select the next item.

**Comment by dandepeched** [comment]
+1, this is quite annoying when you want to sell items in specific stacks. At least there should be an option in settings to select expected behavior

**Comment by plusmouse** [comment]
Why are you selling items in small stacks? The auction house (from 8.3 onwards) now lets users purchase part of a stack that's been posted, so posting 50 ore will let a buyer buy just 5 (or 1, 2, 3, ...).

**Comment by dandepeched** [comment]
Cool, didn't know about that! 
But I still observe an issue with the armor of the same name (which cannot be stacked) being skipped to next item.

**Comment by plusmouse** [comment]
If you set the quantity in the settings for `Selling: Gear/Pets` to 0 it will post them all in one go (with the ability to purchase just one).

**Comment by dandepeched** [comment]
That may work, will try it, thanks!

**Comment by SiderealDay** [comment]
Ok thank you!  I did not know that as I have been away from the game for years :)
