### ISSUE TITLE
Sell different quantities per different stack limits.

### ISSUE THREAD

**Issue by SiderealDay** [Auctionator/Auctionator#1029]
**Is your feature request related to a problem? Please describe.**
It is not really a problem but quite an inconvenience.

**Describe the solution you'd like**
At the moment, I can assign a single default quantity for sales. But items come in different stack limits: some have a stack size limit of 200, 20, 10 and 5.
It would be nice to assign different quantities that depends on different stack size limit; maybe at least two options, one for size 20 and another for size 200, as those are the most common in my experience.
For example, I would like to sell a quantity of 25 if that item in question has a stack limit of 200, but a quantity of 5 if the item has a stack limit of 20.

**Comment by plusmouse** [comment]
In the alpha builds there's an extending quantity settings per-category that should let you configure it how you want it:
![image](https://user-images.githubusercontent.com/60280559/119181582-afe0a680-ba69-11eb-9adb-53070e3ff7ba.png)

Does that do what you wanted?

**Comment by plusmouse** [comment]
Closing, the feature appears to do what was requested and is now available in the normal Auctionator releases.

**Comment by SiderealDay** [comment]
Thank you, I will test this :)
