### ISSUE TITLE
Compare auction prices between realms where I performed scan

### ISSUE THREAD

**Issue by dandepeched** [Auctionator/Auctionator#1030]
**Is your feature request related to a problem? Please describe.**
I have characters on few realms and I want to know where is the highest price for a particular pet. Also it is useful to compare prices for some account-wide items like mounts and toys.

**Describe the solution you'd like**
I want to be able to compare auction prices between realms where I performed scan

**Describe alternatives you've considered**
This feature will be very useful for battle pets, that can be transferred between realms via caging. And it will help to buy account-wide items at the lowest price.

**Additional context**
Implementation can contain a tooltip where current realm price is compared to max price on all scanned realms.

**Comment by plusmouse** [comment]
What kind of UI did you have in mind to see this information? I've mocked up what it could look like if the realm "Twisting Nether" has a better price:
![image](https://user-images.githubusercontent.com/60280559/120846247-bf7fe500-c569-11eb-87ed-b97a4dbf9785.png)

**Comment by dandepeched** [comment]
This looks great. Probably "on" can be removed to save space. If there are more than one additional realms they may be sorted by price, but that's optional.
By the way, such tooltip also makes sense for transmog items. As I have 2 druids on different realms (and also rogue) I may buy some leather items or weapons to add to the collection.
Another type that came into my mind is quest items like "Battered Hilt" that leads to account-wide achievement.
So I suggest to have some setting on item types that you can turn on. Pets may be 'on' by default.

**Comment by plusmouse** [comment]
Having a tooltip item that needs to be on on certain items and off on others is more complicated than I'd like to add to Auctionator, and unless a user is specifically looking at cross realm purchases it is of limited use.
