### ISSUE TITLE
Vendor price for Legendary items

### ISSUE THREAD

**Issue by dale206Git** [Auctionator/Auctionator#1031]
**Is your feature request related to a problem? Please describe.**
The tooltip displays a vendor price for legendary items that cannot be sold to any vendor.

**Describe the solution you'd like**
Do not display a vendor price for legendary items.

**Describe alternatives you've considered**
Display "Cannot be sold to a vendor" or something to that effect, possibly in red.

**Additional context**
I experienced this issue with Legion legendary items. I purchased one trusting that I could sell it to a vendor for 49 gold, as in the tooltip, but then realized the information was not reliable.

**Comment by plusmouse** [comment]
Can I have a screenshot of the item?

**Comment by dale206Git** [comment]
...sure!

**Comment by dale206Git** [comment]
![juna](https://user-images.githubusercontent.com/84369924/118608416-f7410b80-b7b9-11eb-85cb-6295d16a472b.png)

**Comment by plusmouse** [comment]
I've put a fix in alpha 557, available [here](https://github.com/Auctionator/Auctionator/releases/tag/557-alpha) or on curseforge

**Comment by dale206Git** [comment]
...great! I no longer see the vendor price for that item. Maybe you'd be interested to know that before to open this issue I found two forum threads that described the same issue (I could post the links).
