### ISSUE TITLE
WoW Default Item Price

### ISSUE THREAD

**Issue by TheOtherMadPenguin** [Auctionator/Auctionator#1032]
I'm always frustrated when I go to sell an object; the default price is usually wrong.

I Wish for a configuration option on the selling items and selling gear/pets pages to set the starting price. 
<e.g.>
Set Default Price to _____ times <buttons>Vendor/Deposit</buttons> price
<checkbox>Or lowest price of this item at this item level, whichever is lower</checkbox>
</e.g.>
Resume with current text for undercutting by % or fixed amount.

**Comment by plusmouse** [comment]
Closing as unlikely to implement. Historically Auctionator has avoided setting arbitary prices for items when there's a price already set. In the event that no price is stored for an item the gear vendor price multiplier can be used:
![image](https://user-images.githubusercontent.com/60280559/128244184-f88245d9-12dd-4bce-92c9-7e7eb4276b7b.png)
