### ISSUE TITLE
"Uncollected" and "Usable" filters on shopping lists

### ISSUE THREAD

**Issue by designadrug** [Auctionator/Auctionator#1033]
Would love to have the "Uncollected" and "Usable" filters available on shopping lists.

**Comment by plusmouse** [comment]
Is this for transmog searches? Have you tried Collectionator https://www.curseforge.com/wow/addons/collectionator/ (made by me).

**Comment by designadrug** [comment]
I'll check it out. Sorry for the redundancy.

**Comment by designadrug** [comment]
Yeah like that. Except it would remember my settings :)

**Comment by plusmouse** [comment]
Adding tmog search tools to Auctionator is unlikely to happen on the basis that Collectionator exists.
