### ISSUE TITLE
Auctionator not showing up in Game, Cant see The Tabs in the auction house. Yes I Can see it is installed and working in the Addons Tab

### ISSUE THREAD

**Issue by jorelvcam** [Auctionator/Auctionator#1034]
It was working before TBC and many have said that they can see everything and it is working for me but I have loaded it and it does not work in game for me.

**Comment by rodier** [comment]
Same here. Not sure why.
I tried disabled all addons and it was same.

**Comment by jorelvcam** [comment]
Hey I figured something out look up auctionator burning crusade edition
that worked for me

**Comment by plusmouse** [comment]
This issue appears to be resolved. Closing.
