### ISSUE TITLE
Show Bid price?

### ISSUE THREAD

**Issue by sauljaffe** [Auctionator/Auctionator#1035]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

If "Show bid price option when listing an item" is supposed to provide the ability to set a bid price, rather than a sell price on the "Selling" tab or "Sell" tab, it's not working.

## Steps to Reproduce

Turn on the option. Reload. Go to the appropriate tab.

## Loaded Addons

Too many to list here unless a way is provided to get a snapshot of all of them at once. Having to type each one in individually is difficult and painful due to physical disabilities.

## Back Trace (LUA Error Output)

None.

**Comment by plusmouse** [comment]
It adds a bid field to the "Selling" tab:
![image](https://user-images.githubusercontent.com/60280559/120078901-7e8b5a80-c0a9-11eb-8f61-febfafca5f3a.png)

Is this not appearing for you?
