### ISSUE TITLE
Full Scan

### ISSUE THREAD

**Issue by CueyLaO** [Auctionator/Auctionator#1044]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

_Please include a brief description of the bug, including what you were doing, and when it occurred._

## Steps to Reproduce

_Include the steps I would need to follow to reproduce the bug._

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by plusmouse** [comment]
You haven't provided any information for me to figure out what precisely is broken (just "Full Scan" - which doesn't help me).

What is wrong/broken and what error messages have been displayed? You'll need !BugGrabber and BugSack to get the error messages.

**Comment by CueyLaO** [comment]
remove this please. I didn't mean to post till I got the report for it.
