### ISSUE TITLE
Typo or Translation Error in Last Scan popup for Classic TBC

### ISSUE THREAD

**Issue by CPrince211** [Auctionator/Auctionator#1045]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

"at" is instead "alle" when describing Last Scan

## Steps to Reproduce

When Full Scan popup is opened

## Loaded Addons

AtlasLootClassic
Attune
Auctionator
Bagnon
Better Vendor Price
BugSack
ClassicCodex
Consequence - Flightmaster
Deadly Boss Mods (DBM)
Details! Damage Meter
Details! Damage Meter (classic)
Dominos
HealBarsClassic
Leatrix Maps (Burning Crusade Classic)
Leatrix Plus (Burning Crusade Classic)
LFG Group Bulletin Board TBC
LunaUnitFrames
MBB - Classic
Message Barker
MrBigglesworthDeath
Musician
Musician List
Noteworthy II
Nova World Buffs
Owospeak
Pawn
PlayerMadeQuests (PMQ)
project-403048
RaidSummon
ThreatClassic2
Total RP 3
TotemTimers Classic
Twitch Emotes v2
WeakAuras
WIM (WoW Instant Messenger) v3

## Back Trace (LUA Error Output)

You have no bugs, yay!

**Comment by plusmouse** [comment]
I've added a new fixed version to curseforge https://www.curseforge.com/wow/addons/auctionator/files/3365195
