### ISSUE TITLE
15 mins between scans regardless of setting

### ISSUE THREAD

**Issue by Culmar** [Auctionator/Auctionator#1046]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

_Please include a brief description of the bug, including what you were doing, and when it occurred._

When I scan the World of Warcraft auction house in Auctionator, I can't do another scan for 15 minutes, no matter what I set the interval to in the addon's basic options.  I have bank toons on Rexxar Horde and Rexxar Alliance, also Hyjal Horde.

## Steps to Reproduce

_Include the steps I would need to follow to reproduce the bug._

Scan the AH, then try again.

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._

Altoholic (except DataStore Auctions component), Auctionator, MapCoords, Postal, SellJunk

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

I'm not getting an error message.

**Comment by plusmouse** [comment]
The 15 minute limit is normal (Blizzard enforced).

You can do a slower scan that isn't subject to that limit by Ctrl+Clicking the scan button.

The autoscan interval only permits a scan when Blizzard does (at the 15 minute mark), so it isn't possible to make that work with a smaller value.
