### ISSUE TITLE
Scann doesn't start 

### ISSUE THREAD

**Issue by Chrysiana** [Auctionator/Auctionator#1047]
When I start the full scann nothing happens at all. This has been happening since 9.1 came out. I am using the newest update.

**Comment by plusmouse** [comment]
Can you provide a screenshot? Do you have BugSack/BugGrabber installed and are they showing any errors?

**Comment by Chrysiana** [comment]
Hi no bugsack/bugGrabber installed 
I just can't make it do more than 10% - The few times it goes through it scanns in maybe 2 min but now nothing happens
![full scann](https://user-images.githubusercontent.com/80256306/126222974-5adce2a7-50f2-46ef-b27c-fd40f29b11a4.png)

**Comment by plusmouse** [comment]
What realm are you on? EU/US? - If you're in the EU I'll be able to do a scan on your realm to check.

Can you install BugSack and BugGrabber and report if any errors show up?

Also, can you try with just Auctionator enabled (to eliminate the possibility that another addon is interfering)?

Being stuck on 10% usually means (if there's no bugs) that the server hasn't responded to the scan request yet. It should always respond though.

**Comment by plusmouse** [comment]
Running it with BugSack/BugGrabber active is ok - I don't expect them to interfere.

**Comment by Chrysiana** [comment]
It sometimes works on Ragnaros EU, on Argent Dawn EU I can leave the computer for up to 15 min and nothing happens.

**Comment by plusmouse** [comment]
I've tried scanning on Ragnaros and Argent Dawn, both work for me. I'll try again at peak times just in case though.

I'm going to need you to install BugSack and BugGrabber, and report any errors they tell you about when the scan happens.

If they don't report an error, can you please try doing the scan with just Auctionator enabled and report what happens.

**Comment by Chrysiana** [comment]
I got the addons BugSack and BugGrabber. Nothing comes out for the Auctioneer addon. So i tried with only Auctionator enabled and that worked. Guess it's an old addon that blocked it. 

Sorry!
