### ISSUE TITLE
ShoppingLists error message upon login

### ISSUE THREAD

**Issue by Wisdawn** [Auctionator/Auctionator#1048]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

The error message showed up immediately after my character appeared in the world.

## Steps to Reproduce

Just start the game and log in a character.

## Loaded Addons

CTATracker: enabled
FactionAddict: enabled
Ace3: enabled
QuestPlates: enabled
VanasKoS: enabled
SmexyMats: enabled
Oilvl: enabled
TitanQuests: enabled
TomCats: enabled
Coordinates: enabled
CQuestCounter: enabled
HandyNotes_BattleForAzerothTreasures: enabled
GarrisonMissionManager: enabled
ChampionCommander: enabled
War Mode Tracker: enabled
EquipSee: enabled
AutoRepair: enabled
Bartender4: enabled
Overachiever: enabled
Overachiever_Cache: enabled
Overachiever_Tabs: enabled
Overachiever_Trade: enabled
RareScanner: enabled
DBM-Interrupts: enabled
RealmHopAssist: enabled
ACU: enabled
WorldQuestsList: enabled
MuteSoundFile: enabled
MuteSoundFile_Options: enabled
Rematch: enabled
WeakAuras: enabled
WeakAurasModelPaths: enabled
WeakAurasOptions: enabled
WeakAurasTemplates: enabled
WeakAurasCompanion: enabled
SharedMedia: enabled
Paste: enabled
CopyPasta: enabled
Explorer: enabled
Grail: enabled
Grail-NPCs-_retail_: enabled
Grail-NPCs-_retail_-enUS: enabled
Grail-Quests-_retail_: enabled
Grail-Quests-_retail_-enUS: enabled
Grail-Reputations-_retail_: enabled
Grail-Achievements: enabled
Grail-Rewards: enabled
Grail-When: enabled
TitanGathered2: enabled
WeakAurasArchive: enabled
Wholly: enabled
DBM-CastleNathria: enabled
DBM-Party-Shadowlands: enabled
DBM-SanctumOfDomination: enabled
DBM-Shadowlands: enabled
Plater: enabled
Scrap_Config: enabled
CallToArms: enabled
D4KiR Healer Protection: enabled
MythicDungeonTools: enabled
AAP-Core: enabled
AAP-EasternKingdoms: enabled
AAP-Shadowlands: enabled
SimpleRaidTargetIcons: enabled
MarkingBarLives: enabled
MaxDps_DeathKnight: enabled
MaxDps_Mage: enabled
MaxDps_Monk: enabled
MaxDps_Paladin: enabled
MaxDps_Priest: enabled
MaxDps_Rogue: enabled
MaxDps_Warrior: enabled
DynamicCam: enabled
MinimalArchaeology: enabled
ElvUI: enabled
ElvUI_OptionsUI: enabled
DBM-Archaeology: enabled
ConRO_Shaman: enabled
Collectionator: enabled
Collectionator-data: enabled
MuffinArchaeologyUI: enabled
SpeedyAutoLoot: enabled
ConRO_Warlock: enabled
Rarity: enabled
Rarity_Options: enabled
MazeHelper: enabled
BattlePetBreedID: enabled
PetTracker: enabled
PetTracker_Battle: enabled
PetTracker_Config: enabled
PetTracker_Journal: enabled
PokemonTrainer: enabled
PokemonTrainer_Loader: enabled
InstanceAchievementTracker: enabled
MyChatAlert: enabled
HandyNotes_Universal_Explorer: enabled
UltraSquirt: enabled
CovenantMissionHelper: enabled
BtWQuests: enabled
BtWQuestsShadowlands: enabled
Ailo: enabled
InstanceAutoMarker: enabled
Details_Covenants: enabled
HandyNotes_ShadowlandsTreasures: enabled
LibQTip-1.0: enabled
MythicPlusTimer: enabled
OmniCD: enabled

## Back Trace (LUA Error Output)

Message: ...ace\AddOns\Auctionator\Source\ShoppingLists\Main.lua:34: bad argument #1 to 'ipairs' (table expected, got nil)
Time: Wed Jul 21 16:45:14 2021
Count: 1
Stack: ...ace\AddOns\Auctionator\Source\ShoppingLists\Main.lua:34: bad argument #1 to 'ipairs' (table expected, got nil)
[string "=[C]"]: ?
[string "=[C]"]: in function `ipairs'
[string "@Interface\AddOns\Auctionator\Source\ShoppingLists\Main.lua"]:34: in function `ListIndex'
[string "@Interface\AddOns\Auctionator\Source\Config\Mixins\Shopping.lua"]:28: in function <...AddOns\Auctionator\Source\Config\Mixins\Shopping.lua:22>
[string "=[C]"]: in function `Show'
[string "@Interface\FrameXML\UIParent.lua"]:2928: in function `SetUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2734: in function `ShowUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2641: in function <Interface\FrameXML\UIParent.lua:2637>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface\FrameXML\UIParent.lua"]:3492: in function <Interface\FrameXML\UIParent.lua:3471>
[string "=[C]"]: ?
[string "=[C]"]: in function `ShowUIPanel'
[string "@Interface\AddOns\Oilvl\Oilvl.lua"]:5437: in function `?'
[string "@Interface\AddOns\Oilvl\Oilvl.lua"]:5584: in function <Interface\AddOns\Oilvl\Oilvl.lua:5583>

Locals:

**Comment by plusmouse** [comment]
Had a look. It looks like this is caused by another addon triggering Auctionator's code before Auctionator has finished loading.

Does this happen every time you login and does it happen when only Auctionator is enabled?

**Comment by plusmouse** [comment]
Going to close this issue due to no response (if there is a response I'll reopen it).
