### ISSUE TITLE
Multiple LUA Errors with  9.1.5.1 release causing Add-on to not fuction

### ISSUE THREAD

**Issue by mdon3153** [Auctionator/Auctionator#1056]
Please include as much of the following information as possible to help me fix the bug:

Getting 19 LUA errors when logging into any character.  Going to the Auction House shows none of the tabs for Auctionator

_Please include a brief description of the bug, including what you were doing, and when it occurred._

Logged into any character.  Pulling up the Action House shows none of the Auctionator tabs.

_Include the steps I would need to follow to reproduce the bug._

Login and go to any Auction House

_Include a list of addons you were running at the time this bug occurred._

Disabled all addons except Auctionator and error still occurs and Auctionator tabs do not show up on Auction House.
[AuctionatorLUAWarnings.txt](https://github.com/Auctionator/Auctionator/files/7103158/AuctionatorLUAWarnings.txt)

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by plusmouse** [comment]
Can you try reinstalling Auctionator (I think the download or the install was corrupted)?

**Comment by mdon3153** [comment]
that fixed the issue.  I removed and reinstalled it and it's working fine now.

**Comment by plusmouse** [comment]
Great
