### ISSUE TITLE
Fix battle pet level in undercut scan

### ISSUE THREAD

**Issue by robertvasile** [Auctionator/Auctionator#1057]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

Battle pets level should be a filter in undercut scan. atm. lvl 25 battle pets are reported as undercut by level 1s

## Steps to Reproduce

post auction and ask another account to undercut

**Comment by plusmouse** [comment]
Which tab are you looking in, Cancelling or Selling (both have undercut checks)?

**Comment by plusmouse** [comment]
Closing as request for clarification received no response.
