### ISSUE TITLE
Disproportioned selling frame when “Show bid price option” is enabled

### ISSUE THREAD

**Issue by tflo** [Auctionator/Auctionator#1060]
Please see screenshot. Only happens with Bid Price Option enabled.

![WoWScrnShot_091521_112846](https://user-images.githubusercontent.com/1410282/133410142-5ce0ab4f-1482-41c5-8300-74ec54068039.jpg)

Seen since 9.1.5.1-8-g1183c2e. Also happens with all other add-ons unloaded.

**Comment by plusmouse** [comment]
Fixed in 9.1.5.1-9-g80d0b6d (it'll be available on curseforge shortly)

**Comment by tflo** [comment]
Seems fine now. Thanks for the quick fix!
