### ISSUE TITLE
zhCN Missing localization 

### ISSUE THREAD

**Issue by nanjuekaien1** [Auctionator/Auctionator#1066]
Curseforge could not register an account, thank you for your help 

L["NEW_SHOPPING_LIST"] = "+ 新购物清单"
L["NO_LIST"] = "没有清单"
L["PROFIT_COLON"] = "利润:"
L["REAGENT_SEARCH"] = "材料搜索" 
L["RENAME_LIST_CONFIRM"] = "输入'%s'的新名称:"
L["SAVE_THIS_LIST_AS"] = "将此清单另存为..."
L["SEARCH_ALL"] = "搜寻全部"
L["SELECT_SHOPPING_LIST"] = "选择购物清单..." 
L["SHOPPING_LIST"] = "购买清单" 
L["SORT"] = "排序"
L["SPLASH_9105_DESCRIPTION"] = "添加了一种新的购物清单搜索方法，可以在14秒内扫描和过滤数千件商品的价格（在全负载的大服大约为42秒）--以前这可能需要20分钟！当与金币价格过滤器结合使用时，这对于阻击完美交易非常宝贵。"
L["SPLASH_9105_FEATURES_1"] = "搜索超过50件商品时，购物清单搜索速度非常快"
L["SPLASH_9105_FEATURES_2"] = "添加一个按钮，可将 \"购物\" 选项卡中的历史价格对话框移动到结果列表的右侧(右键单击任务物品可查看历史价格)。"
L["SPLASH_9105_FEATURES_3"] = "当拍卖行开启时，可以选择在制造窗口内显示利润而不是显示制造成本。"
L["SPLASH_9105_FEATURES_HEADER"] = "最近的功能"
L["X_PRICE_HISTORY"] = "%s 价格记录"

**Comment by plusmouse** [comment]
I've added the translations to curseforge. Thankyou.

**Comment by plusmouse** [comment]
I've added those too. Thanks a lot 😃 
![image](https://user-images.githubusercontent.com/60280559/134120660-b252a026-1afa-4ed3-927d-3ac29e4b1a1c.png)

**Comment by nanjuekaien1** [comment]
Thank you 
However, I found a place that could not be localized
![本地化](https://user-images.githubusercontent.com/2303601/134142874-f77731d5-3bd9-44bf-9e9d-3553378b2678.png)

**Comment by plusmouse** [comment]
Fixed. It should be localised in the next alpha release, available here while waiting for Curseforge to approve it.
[Auctionator-9.1.5.1-17-g0d149d6.zip](https://github.com/Auctionator/Auctionator/files/7201895/Auctionator-9.1.5.1-17-g0d149d6.zip)
.

**Comment by nanjuekaien1** [comment]
Thanks, it's perfect

**Comment by nanjuekaien1** [comment]
L["LIST_EXTENDED_SEARCH_HEADER"] = "扩展的搜索选项"

**Comment by plusmouse** [comment]
Added to Curseforge.

**Comment by nanjuekaien1** [comment]
L["CONFIG_SHOPPING_LIST_MISSING_TERMS"] = "显示购物清单中没有结果的物品。"
L["CONFIG_SHOPPING_LIST_MISSING_TERMS_TOOLTIP_HEADER"] = "没有结果的搜索"
L["CONFIG_SHOPPING_LIST_MISSING_TERMS_TOOLTIP_TEXT"] = "当搜索没有结果时，一个为零的可用物品将添加到结果中显示。"


https://github.com/Auctionator/Auctionator/blob/master/Source/Tabs/ShoppingLists/Mixins/Item.lua#L87
Can it be localized ？
No item info was specified=" 未指定物品信息"

**Comment by plusmouse** [comment]
Added the new translations and localised that text.

**Comment by nanjuekaien1** [comment]
L["NO_ITEM_INFO_SPECIFIED"] = "没有指定物品信息。"

**Comment by nanjuekaien1** [comment]
L["SPLASH_9106_DESCRIPTION"] = "重新设计购物清单中的新快速搜索框和搜索历史记录。"
L["SPLASH_9106_FEATURES_1"] = "“购物”标签中的搜索框和最近的搜索面板。"
L["SPLASH_9106_FEATURES_2"] = "按照字母顺序对购物清单进行排序的按钮。"
L["SPLASH_9106_FEATURES_3"] = "在购物清单的结果中显示未找到的搜索词。"
L["SPLASH_9106_FEATURES_HEADER"] = "新增功能"

**Comment by nanjuekaien1** [comment]
L["CONFIG_SELLING_TBC_SHOW_ALL_RESULTS"] = "包括不需要在结果中获得最低价格的拍卖"
  L["CONFIG_SELLING_TBC_SHOW_ALL_RESULTS_TOOLTIP_HEADER"] = "显示所有 结果"
  L["CONFIG_SELLING_TBC_SHOW_ALL_RESULTS_TOOLTIP_TEXT"] = "启用此设置会导致搜索结果的所有页面并列出所有找到的拍卖，即使只需要第一页来确定最低价格。"

**Comment by nanjuekaien1** [comment]
L["YOU_COLUMN"] = "你?"

**Comment by plusmouse** [comment]
Thanks. Added it.

**Comment by nanjuekaien1** [comment]
L["COPY_NO_LIST_SELECTED"] = "无法复制物品。未选择购物清单"
  L["COPY_ITEM_ADDED"] = "已将 %s 复制到 %s"
  L["COPY_TO_LIST"] = "将物品复制到购物清单中"

**Comment by plusmouse** [comment]
Added them. 👍

**Comment by nanjuekaien1** [comment]
L["MULTIPLE_STACKS_AUCTION_INFO"] = "%s %s，总共 %s"

**Comment by nanjuekaien1** [comment]
L["SPLASH_9108_FEATURES_9"] = "可以取消自己的拍卖，无论是在购买界面内还是在带有压价扫描的专用标签上。"

**Comment by nanjuekaien1** [comment]
L["CHAIN_BUY"] = "连续购买"
L["CHAIN_BUY_TOOLTIP_HEADER"] = "连续多次购买"
L["CHAIN_BUY_TOOLTIP_TEXT"] = "以当前价格和堆栈数量完成购买后，选择下一个价格和堆栈数量"

**Comment by nanjuekaien1** [comment]
L["CONFIG_RESET_STACK_SIZE_MEMORY"] =  "重置堆栈数量"

**Comment by nanjuekaien1** [comment]
L["BRACKETS_X_EACH"] = "(每个 %s)"

**Comment by nanjuekaien1** [comment]
L["YOU"] = "你"

**Comment by nanjuekaien1** [comment]
Thank you，
Forgot to submit recently

**Comment by nanjuekaien1** [comment]
L["TOTAL_PENDING"] = "(%s 待处理)"
L["ANY_UPPER"] = "任何"

**Comment by plusmouse** [comment]
All done 😄 
![image](https://user-images.githubusercontent.com/60280559/162900418-5716caa9-c0a5-47ce-8e73-9db4f69fa97a.png)

**Comment by plusmouse** [comment]
Added those.

**Comment by nanjuekaien1** [comment]
L[" CONFIRM_POST_LOW_PRICE"] = "%s 的价格有点低。你确定要以这个价格发布吗？"

**Comment by nanjuekaien1** [comment]
L["CANCEL_SEARCH"] = "取消搜索"

**Comment by nanjuekaien1** [comment]
L["UNDERCUT_BID"] = "竞价"

**Comment by nanjuekaien1** [comment]
L["LOAD_ALL"] = "全部加载"

**Comment by nanjuekaien1** [comment]
L["LOAD_MORE_RESULTS"] = "载入更多结果"
L["LOAD_HIGHER_PRICES"] = "载入更高价格"

**Comment by nanjuekaien1** [comment]
L["SPLASH_9225_ALL_VERSIONS_1"] = "在计算制作成本时使用看到的供应商价格。"
L["SPLASH_9225_ALL_VERSIONS_2"] = "右键点击取消标签中的任何拍卖来搜索竞争拍卖。"
L["SPLASH_9225_ALL_VERSIONS_3"] = "购买搜索的品质过滤器。"
L["SPLASH_9225_ALL_VERSIONS_4"] = "按住 \"Shift\"键点击任何栏的标题来重置排序。"
L["SPLASH_9225_ALL_VERSIONS_5"] = "当发布低于供应商价格的物品时,销售标签页会发布警告。"
L["SPLASH_9225_ALL_VERSIONS_HEADER"] = "所有版本的最新功能。"
L["SPLASH_9225_CLASSIC_1"] = "现在在销售或购物时从拍卖行载入的页面更少，从而节省了在繁忙服务器的时间。"
L["SPLASH_9225_CLASSIC_2"] = "右键点击背包中物品的选项是一种将其选择为销售标签页的方式。"
L["SPLASH_9225_CLASSIC_3"] = "销售和购买时拍卖可选\"卖家\" (右键点击标题以启用)。"
L["SPLASH_9225_CLASSIC_4"] = "当你在AH时，暴雪附魔图纸会显示制作成本。"
L["SPLASH_9225_CLASSIC_5"] = "在购买物品栏中点击该物品的图标，可以在原版的AH中查看它。"
L["SPLASH_9225_CLASSIC_HEADER"] = "经典版的最新功能。"
L["SPLASH_9225_DESCRIPTION"] = "许多改进,包括在繁忙的经典服务器的销售和购物变得更快。"
L["SPLASH_9225_RETAIL_1"] = "与列出的其他商品相比,以异常低的价格发布商品时,销售标签页会发出警告。"
L["SPLASH_9225_RETAIL_HEADER"] = "正式服版本的最新功能。"

**Comment by plusmouse** [comment]
All added. Thanks.

**Comment by nanjuekaien1** [comment]
There is an error:
The price of the supplier on the tooltip shows the price of recycling, not the price of the item sold by the supplier.

**Comment by plusmouse** [comment]
It is meant to show the recycling price though?

**Comment by plusmouse** [comment]
If that isn't what is wrong
![image](https://user-images.githubusercontent.com/60280559/183248773-4c217b26-2501-4e2e-a7bf-27c731426478.png)
can you screenshot an affected item's tooltip.

**Comment by nanjuekaien1** [comment]
![拍卖行2-1](https://user-images.githubusercontent.com/2303601/183249476-9f9300c1-c111-417c-8c94-7a3023186399.png)

**Comment by nanjuekaien1** [comment]
Oribos NPC：
![拍卖行3-2](https://user-images.githubusercontent.com/2303601/183249636-d35add13-d9bf-41a1-a594-3b30d409da03.png)
Covenant Sanctum NPC：
![拍卖行3-3](https://user-images.githubusercontent.com/2303601/183249648-f7cfaff7-2bc4-4404-ad68-5eac8f124e55.png)

**Comment by nanjuekaien1** [comment]
Show some impact on manufacturing cost prices

**Comment by plusmouse** [comment]
It doesn't affect the Crafting cost information, as that uses the vendor's purchase price instead of the recycling price
![image](https://user-images.githubusercontent.com/60280559/183249924-e65dee97-80c2-4ebc-8534-59b61944786e.png)

The thread has a recycling price of 2.25g
![image](https://user-images.githubusercontent.com/60280559/183249948-34a59f87-6916-422f-a22e-e62984a29246.png)
But the crafting cost uses the purchase cost of 9g to calculate the crafting cost.

**Comment by nanjuekaien1** [comment]
I get it, thank

**Comment by nanjuekaien1** [comment]
L["CONFIG_SHOPPING_ALWAYS_LOAD_MORE"] = "总是加载所有可用的结果。"
L["CONFIG_SHOPPING_ALWAYS_LOAD_MORE_TOOLTIP_HEADER"] = "总是加载更多。"
L["CONFIG_SHOPPING_ALWAYS_LOAD_MORE_TOOLTIP_TEXT"] = "虽然仍然获得准确的最低价格，但会跳过某些页面以加快购物搜索速度。这可以防止任何页面被跳过并确保显示所有可能的结果。"

**Comment by nanjuekaien1** [comment]
L["CURRENT_PRICES"] = "当前价格"

**Comment by nanjuekaien1** [comment]
L["FULL_SCAN_FAILED_REPLICATE"] = "完整扫描 (重复模式) 失败，没有完成。"
L["FULL_SCAN_FAILED_SUMMARY"] = "完整扫描 (摘要模式) 失败，没有完成。"
L["STARTING_FULL_SCAN_REPLICATE"] = "开始完整扫描 (重复模式)。"
L["STARTING_FULL_SCAN_SUMMARY"] = "开始完整扫描 (摘要模式)。"

**Comment by nanjuekaien1** [comment]
L["CONFIG_SAVE_LAST_DURATION_AS_DEFAULT"] = "将上次使用的拍卖持续时间保存为预设值"
L["CONFIG_SAVE_LAST_DURATION_AS_DEFAULT_TOOLTIP_HEADER"] = "将上次使用的时间覆盖预设持续时间"
L["CONFIG_SAVE_LAST_DURATION_AS_DEFAULT_TOOLTIP_TEXT"] = "将上次使用的时间覆盖预设持续时间"

**Comment by plusmouse** [comment]
Added 👍

**Comment by nanjuekaien1** [comment]
L["OPEN_IN_SHOPPING_TAB"] = "在购物标签页中打开"

**Comment by nanjuekaien1** [comment]
L["CONFIRM_POST_PRICE_DROP"] = "%s 的单价大幅降价。你确定要按这价格发布吗？"

**Comment by nanjuekaien1** [comment]
L["IS_TOP_COLUMN"] = "顶部?"

**Comment by nanjuekaien1** [comment]
L["CONFIG_SELLING_ALL_ITEMS_CATEGORY"] = "销售: 全部物品"
Thanks

**Comment by nanjuekaien1** [comment]
L["TRANSLATORS_TURKISH_INFO"] = "土耳其语 (单独提供)"
L["CONFIG_SELLING_SPLIT_PANELS"] = "在当前价格和历史价格之间显示分离面板视图"
L["CONFIG_SELLING_SPLIT_PANELS_TOOLTIP_HEADER"] = "分离面板视图"
L["CONFIG_SELLING_SPLIT_PANELS_TOOLTIP_TEXT"] = "通常，历史价格位于“销售”选项标签的标签上，这使得当前价格始终可见，但历史价格显示在它们下方的面板内。"

**Comment by nanjuekaien1** [comment]
L["POST_ATTEMPT_FAILED"] = "你最后一次发布没有成功。请再试一次。"

**Comment by nanjuekaien1** [comment]
L["POST_ATTEMPT_FAILED"] = "你最后一次拍卖没有发布成功。请再试一次。"
L["CONFIG_SELLING_GREY_POST_BUTTON"] = "拍卖发布失败时灰色（禁用）开始拍卖按键"
L["CONFIG_SELLING_GREY_POST_BUTTON_TOOLTIP_HEADER"] = "灰色拍卖按键"
L["CONFIG_SELLING_GREY_POST_BUTTON_TOOLTIP_TEXT"] = "当拍卖可能失败时，拍卖按键将变灰（禁用）。关闭此选项以避免等待按键启用，以便您可以尝试更快地发布。"

**Comment by nanjuekaien1** [comment]
L["CONFIG_PROSPECT_TOOLTIP"] = "在工具提示中显示来自珠宝加工矿石的潜在价值"
L["PROSPECT_TOOLTIP_TOOLTIP_HEADER"] = "潜在客户工具提示信息"
L["PROSPECT_TOOLTIP_TOOLTIP_TEXT"] = "鼠标悬停时在工具提示中显示珠宝加工勘探估计价值。"

**Comment by nanjuekaien1** [comment]
L["PROSPECT"] = "选矿"
L["PROSPECT_TOOLTIP_TOOLTIP_TEXT"] = "鼠标悬停时在工具提示中显示珠宝加工选矿估计价值。

**Comment by nanjuekaien1** [comment]
L["SHOPPING_TAB_HEADER_2"] = "拍卖小帮手 - 购物"

**Comment by nanjuekaien1** [comment]
L["SHOPPING_TAB"] = "购物"

**Comment by nanjuekaien1** [comment]
Modify the error before：
L["BUG_REPORT"] = "反馈 Bug"
L["BUG_TOOLTIP_HEADER"] = "在 Github 反馈 Bug"
L["BUG_TOOLTIP_TEXT"] = "如果你在使用拍卖小帮手时发生错误，请到 Github 反馈。请提供足够的细节以便让我们能够重现出相同的 Bug! 使用错误收集插件 !BugGrabber 和 BugSack，并附上所提供的详细错误讯息也能够帮助我们修复错误。"
L["CONFIG_DEBUG"] = "输出出错讯息"
L["CONFIG_DEBUG_TOOLTIP_HEADER"] = "拍卖小帮手出错"
L["CONFIG_DEBUG_TOOLTIP_TEXT"] = "仅供维护人员使用，将出错信息输出到聊天视窗。"
L["SPLASH_830_BUGS_2"] = "反馈问题请到 Github %s"
L["SPLASH_830_BUGS_3"] = "我们大部分都在 Discord 活动，所以请不要在 curseforge 或 Auctionator 讨论区反馈问题。"
L["SPLASH_830_BUGS_HEADER"] = "社群和问题反馈"

**Comment by plusmouse** [comment]
Done

**Comment by nanjuekaien1** [comment]
L["CRAFTING_INFO"] = "制造成本"
L["CONFIG_CRAFTING_INFO_SHOW"] = "在制造窗口中显示制造成本"
L["CONFIG_CRAFTING_INFO_SHOW_TOOLTIP_HEADER"] = "制造窗口额外信息"
L["CONFIG_CRAFTING_INFO_SHOW_TOOLTIP_TEXT"] = "制造窗口中显示制造物品的成本，禁用此选项后将不再显示制造成本。"

**Comment by nanjuekaien1** [comment]
L["CONFIG_MILL_TOOLTIP"] = "在铭文的工具提示中显示草药的研磨价值"
L["MILL_TOOLTIP_TOOLTIP_HEADER"] = "研磨提示信息"
L["MILL_TOOLTIP_TOOLTIP_TEXT"] = "鼠标停留时在工具提示上显示铭文研磨的估价值。"
L["MILL"] = "研磨"

**Comment by nanjuekaien1** [comment]
L["CONFIRM_X_TOTAL_PRICE_X"] = "确认 %s, 总价 %s"

**Comment by nanjuekaien1** [comment]
L["NO_LONGER_AVAILABLE"] = "不再可用"

**Comment by nanjuekaien1** [comment]
L["CONFIG_CRAFTING_INFO_SHOW_COST"] = "显示拍卖行和供应商的药剂成本"
L["CONFIG_CRAFTING_INFO_SHOW_COST_TOOLTIP_HEADER"] = "制作信息显示费用"
L["CONFIG_CRAFTING_INFO_SHOW_COST_TOOLTIP_TEXT"] = "启用此选项在查看时查看特定配方的成本。"
L["CONFIG_CRAFTING_INFO_SHOW_PROFIT"] = "显示拍卖行和供应商的药剂在制作中的利润"
L["CONFIG_CRAFTING_INFO_SHOW_PROFIT_TOOLTIP_HEADER"] = "制作信息显示利润"
L["CONFIG_CRAFTING_INFO_SHOW_PROFIT_TOOLTIP_TEXT"] = "启用此选项在查看特定配方时查看制作特定配方的利润。"

**Comment by nanjuekaien1** [comment]
L["CONFIG_CRAFTING_INFO_SHOW_COST"] = "显示拍卖行和商人配方的材料成本"
L["CONFIG_CRAFTING_INFO_SHOW_COST_TOOLTIP_HEADER"] = "制作信息显示成本"
L["CONFIG_CRAFTING_INFO_SHOW_COST_TOOLTIP_TEXT"] = "启用此选项在查看特定配方时显示制作成本。"
L["CONFIG_CRAFTING_INFO_SHOW_PROFIT"] = "显示拍卖行和商人配方的材料利润"
L["CONFIG_CRAFTING_INFO_SHOW_PROFIT_TOOLTIP_TEXT"] = "启用此选项在查看特定配方时显示制作利润。"

**Comment by nanjuekaien1** [comment]
L["TRANSLATORS_ROMANIAN_INFO"] = "罗马尼亚语 (单独提供)"

**Comment by nanjuekaien1** [comment]
L["EXTENDED_SEARCH_ACTIVE_TEXT"] = "%扩展搜索启用%"
L["PRICE_HISTORY"] = "历史价格记录"

**Comment by nanjuekaien1** [comment]
L["SPLASH_100015_ALL_VERSIONS_1"] = "在“购物”标签页中搜索时自动完成搜索词。"
L["SPLASH_100015_ALL_VERSIONS_2"] = "搜索后可立即在“购物”标签页中编辑快速搜索词。"
L["SPLASH_100015_ALL_VERSIONS_3"] = "在“销售”标签页中保留上次选择的有效时限的选项"
L["SPLASH_100015_ALL_VERSIONS_4"] = "制作成本和利润可以同时显示在制作窗口中"
L["SPLASH_100015_ALL_VERSIONS_5"] = "滚动区域已经重新设计过，更加平滑。"
L["SPLASH_100015_ALL_VERSIONS_6"] = "WOW的一般错误修复和兼容性更改。"
L["SPLASH_100015_ALL_VERSIONS_HEADER"] = "所有版本的最新功能。"
L["SPLASH_100015_CLASSIC_1"] = "警告当发布有大额削价(50%或更多)的警告以减少错误。"
L["SPLASH_100015_CLASSIC_2"] = "新的可选“最高？”在“购物”标签页的列表中查看您的拍卖是否是商品的最高价。"
L["SPLASH_100015_CLASSIC_3"] = "矿石选矿的估价值作为可选工具提示"
L["SPLASH_100015_CLASSIC_4"] = "研磨草药的估价值作为可选工具提示"
L["SPLASH_100015_CLASSIC_5"] = "在物品的价格历史窗口中将“历史记录”显示为额外选项"
L["SPLASH_100015_CLASSIC_6"] = "在“销售”标签也中删除了发布物品后的额外扫描。"
L["SPLASH_100015_CLASSIC_7"] = "防止发布按钮变灰/禁用的选项，並允许尝试立即发布，失败时免费重试。"
L["SPLASH_100015_CLASSIC_HEADER"] = "经典版的最新功能"
L["SPLASH_100015_DESCRIPTION"] = "许多的改进，包括与巨龙时代的兼容性。"
L["SPLASH_100015_RETAIL_1"] = "根据所选物品和品质更新制作成本和利润"
L["SPLASH_100015_RETAIL_2"] = "销售标签页有一个扩展窗口，可在单独的标签页中提供的历史价格记录，也可选择恢复到分离窗口。"
L["SPLASH_100015_RETAIL_HEADER"] = "正式版的最新功能

**Comment by plusmouse** [comment]
Added

**Comment by nanjuekaien1** [comment]
I went online and found that you are going to publish a new version, I'm afraid you will publish it.

**Comment by plusmouse** [comment]
I'm confused. It's in an alpha at the moment, so most users won't see the untranslated text?

**Comment by plusmouse** [comment]
The translations are pulled in automatically when I do the next build

**Comment by nanjuekaien1** [comment]
Thanks！

**Comment by nanjuekaien1** [comment]
L["SPLASH_100015_RETAIL_3"] = "列出在制作订单时显示拍卖行的材料价值。"
L["REAGENTS_VALUE_COLON"] = "材料价值:"

**Comment by nanjuekaien1** [comment]
L["SPLASH_100015_RETAIL_3"] = "列出在制造订单时显示拍卖行的材料价值。"

**Comment by nanjuekaien1** [comment]
L["TIER"] = "品质"

**Comment by nanjuekaien1** [comment]
L["CONTINUE"] = "继续"

**Comment by nanjuekaien1** [comment]
L["STOP_LOADING_NOW"] = "立即停止加载"
L["CONFIG_SELLING_CONFIRM_LOW_PRICE_TOOLTIP_TEXT_2"] = "新增一个确认对话框，该对话框以异常低的价格发布商品时会出现。"

**Comment by nanjuekaien1** [comment]
I register the Curseforge account, and I will submit the localized document directly in Curseforge in the future.
Today I submitted the zhCN document of Journalator.
