### ISSUE TITLE
Shopping list not working after 10/5/21 patch

### ISSUE THREAD

**Issue by phage-cell** [Auctionator/Auctionator#1067]
The shopping list scan is stuck on 'fetching item info...' and is unable to complete. Logging in and out doesn't change anything but restarting the client sometimes works. This has been occuring all morning long since the update.

**Comment by plusmouse** [comment]
Can you install BugSack and BugGrabber and tell me if they report an error when trying to scan?
Which version of Auctionator are you using (alpha or normal)?

**Comment by plusmouse** [comment]
Also, have you tried having just Auctionator enabled? Testing on my computer the searches function fine.
![image](https://user-images.githubusercontent.com/60280559/136067240-d14d3b9b-9f56-4e4c-9e0f-ac1cd2f456a2.png)

**Comment by phage-cell** [comment]
It was related to the server's performance. It had corrected itself after a couple of hours.
