### ISSUE TITLE
when going to scan for full scan

### ISSUE THREAD

**Issue by Sal-inja** [Auctionator/Auctionator#1084]
So when you go to the auctionator tab and hit scan this error happens:

Message: ...Ons\Auctionator\Source_TBC\FullScan\Mixins\Frame.lua:49: attempt to perform arithmetic on field 'TimeOfLastGetAllScan' (a nil value)
Time: Fri Oct 29 17:54:13 2021
Count: 2
Stack: ...Ons\Auctionator\Source_TBC\FullScan\Mixins\Frame.lua:49: attempt to perform arithmetic on field 'TimeOfLastGetAllScan' (a nil value)
[string "@Interface\AddOns\Auctionator\Source_TBC\FullScan\Mixins\Frame.lua"]:49: in function `NextScanMessage'
[string "@Interface\AddOns\Auctionator\Source_TBC\FullScan\Mixins\Frame.lua"]:39: in function `InitiateScan'
[string "@Interface\AddOns\Auctionator\Source_TBC\Tabs\Auctionator\Mixins\ScanButton.lua"]:4: in function <...or\Source_TBC\Tabs\Auctionator\Mixins\ScanButton.lua:3>

Locals: self = AuctionatorFullScanFrame {
 0 = <userdata>
 CanInitiate = <function> defined @Interface\AddOns\Auctionator\Source_TBC\FullScan\Mixins\Frame.lua:43
 OnLoad = <function> defined @Interface\AddOns\Auctionator\Source_TBC\FullScan\Mixins\Frame.lua:8
 NextScanMessage = <function> defined @Interface\AddOns\Auctionator\Source_TBC\FullScan\Mixins\Frame.lua:48
 ResetData = <function> defined @Interface\AddOns\Auctionator\Source_TBC\FullScan\Mixins\Frame.lua:14
 OnEvent = <function> defined @Interface\AddOns\Auctionator\Source_TBC\FullScan\Mixins\Frame.lua:151
 RegisterForEvents = <function> defined @Interface\AddOns\Auctionator\Source_TBC\FullScan\Mixins\Frame.lua:56
 state = <table> {
 }
 EndProcessing = <function> defined @Interface\AddOns\Auctionator\Source_TBC\FullScan\Mixins\Frame.lua:204
 CacheScanData = <function> defined @Interface\AddOns\Auctionator\Source_TBC\FullScan\Mixins\Frame.lua:68
 InitiateScan = <function> defined @Interface\AddOns\Auctionator\Source_TBC\FullScan\Mixins\Frame.lua:19
 ProcessBatch = <function> defined @Interface\AddOns\Auctionator\Source_TBC\FullScan\Mixins\Frame.lua:82
 UnregisterForEvents = <function> defined @Interface\AddOns\Auctionator\Source_TBC\FullScan\Mixins\Frame.lua:62
}
(*temporary) = 1635555253
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on field 'TimeOfLastGetAllScan' (a nil value)"

I have reloaded the UI and also done a clean install of the mod with and fresh restart of he game. So I haven't been able to get the scan working.

**Comment by plusmouse** [comment]
It should be fixed in the latest alpha 9.1.8.1-5-gd983650-bcc (downloadable from curseforge or here
[Auctionator-9.1.8.1-5-gd983650-bcc.zip](https://github.com/Auctionator/Auctionator/files/7445908/Auctionator-9.1.8.1-5-gd983650-bcc.zip)
