### ISSUE TITLE
Items Per Stack text overflows and cuts off on Shopping tab.

### ISSUE THREAD

**Issue by Mayron** [Auctionator/Auctionator#1086]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

It's a visual bug that sort of sounds like a feature request, but I would like to be able to read the full stack text:

![image](https://user-images.githubusercontent.com/5854995/139807824-8c787099-bd12-4f5b-9931-63e1316124d0.png)

I really need to read the "25 stacks o..." part because this is some crucial detail that I rely on. I have to actually buy the item to know what the item's per stack was, or make a guess based on the stack price. Not great if I only need X number of items while crafting!

Just an idea; maybe do something with the owner column? The "No"/"Yes" values take up a lot of space. Maybe you could have a small icon next to the item row or a small label such as "(you)"? I can't remember how the latest version of Auctionator handled this but I thought knowing what I owned was clearer. Seeing a lot of "No" values can create some background noise because I just care about my items (e.g., I just care about the "Yes" values and seeing nothing is the same as seeing a "No").

I don't think any other info is necessary but if it is then please let me know, thanks!

**Comment by plusmouse** [comment]
Are you on the latest version, I tweaked t he column sizes slightly:
