### ISSUE TITLE
Craft price calculation

### ISSUE THREAD

**Issue by Thavion** [Auctionator/Auctionator#1087]
While checking AUC for craft materials using a button from craft window(Alchemy) vials also taken from AUC and their price added to final craft result. I suppose that craft mats which are always available from vendors by fixed price should be excluded from AUC search and added with real price, not auc scams.

**Comment by Thavion** [comment]
Visited vendors many times, crafted a lot of bottles but still it takes price from AUC. Will take a closer look and might make some screenshots.

**Comment by plusmouse** [comment]
Can you specify which recipes aren't working (so I can test them)? Also are you on retail or TBC?

**Comment by Thavion** [comment]
![изображение](https://user-images.githubusercontent.com/93672387/140164548-601f8db8-72a9-4b68-bd35-580a702bc4bd.png)

Just as an example a Haste Potion recipe. Imbued Vial price taken from auc. 
Vendor sells 5x Imbued Vial for 1g50s and here we see one vial calculated with price 1g50s53c

**Comment by Thavion** [comment]
> 
> 
> Can you specify which recipes aren't working (so I can test them)? Also are you on retail or TBC?

TBC

**Comment by Thavion** [comment]
![изображение](https://user-images.githubusercontent.com/93672387/140165603-9e6bb2bc-7c65-463f-9f12-db5a683f2c7d.png)
Just to add more examples: Mad Alchemist's Potion. As you can see a Crystal Vial is also calculated from auc price of 39s0c for a single item which is not reasonable when you can buy those from vendor 5x vials for 22s50c which is 04s50c per item.

**Comment by plusmouse** [comment]
In the last case the price is derived from the vial (4s50c) and the other reagent (48s0c), and 2*48s + 4s50c = 1g0s50c, which is what it displays?

**Comment by plusmouse** [comment]
For the "Haste Potion" it looks like the numbers are a bit wrong, as it should do
2 * 6.3 + 3.1 + 0.045 = 15g74s50c
But the price its showing is 16.60, which doesn't line up with the AH vial price, as with the AH vial price the calculation would be:
2 * 6.3 + 3.1 + 1.5013 = 17g20s31c

**Comment by plusmouse** [comment]
The price shown in the AH search results _isn't_ always what is used for the calculations, it uses the vendor price internally.

**Comment by Thavion** [comment]
> 
> 
> For the "Haste Potion" it looks like the numbers are a bit wrong, as it should do 2 * 6.3 + 3.1 + 0.045 = 15g74s50c But the price its showing is 16g6s, which doesn't line up with the AH vial price, as with the AH vial price the calculation would be: 2 * 6.3 + 3.1 + 1.5013 = 17g20s31c

Price of 16g6s also does not lines up with 15g74s50c which is calculated. I'll take a look on a lower tier recipes as well but a bit later and will report if any issues'll occure. 
Anyway thank you for a swift response. Highfive!

**Comment by plusmouse** [comment]
Update, I was using the wrong vendor price for the "Haste Potion", which is why the numbers were a bit off, the new calculation is, for buying the vials at 1g80s for 5, or 36s each:
2 * 6g30s + 3g10s +  36s = 16g6s

**Comment by Thavion** [comment]
> 
> 
> Update, I was using the wrong vendor price for the "Haste Potion", which is why the numbers were a bit off, the new calculation is, for buying the vials at 1g80s for 5, or 36s each: 2 * 6g30s + 3g10s + 36s = 16g6s

Price may vary depending on reputation to the vendor's facton. Might be a solution to add a fixed value of Exalted and forget about such an issue forever )

**Comment by plusmouse** [comment]
OK. I've added a fix that will set it to use the minimum seen vendor price in the calculation. It will go out in the next release, but in the interim you can download the latest alpha (which will be available in a moment)

**Comment by plusmouse** [comment]
[Auctionator-9.1.10-1-gcf47869-bcc.zip](https://github.com/Auctionator/Auctionator/files/7469977/Auctionator-9.1.10-1-gcf47869-bcc.zip)
