### ISSUE TITLE
Option to convert Recent Searches into a Shopping List

### ISSUE THREAD

**Issue by b-morgan** [Auctionator/Auctionator#1091]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'd like an option to create a shopping list from the list of recent searches.

**Describe alternatives you've considered**
I've already typed the names of the items once, I'd prefer not to have to do it again to create a new shopping list.

**Comment by plusmouse** [comment]
Are you looking to convert the entire recent searches list (up to 30 items) or a select few? ie. Are you after a button to do everything, or are you looking for a new button for each recent search (alongside the delete button) to add the search to a list?

**Comment by b-morgan** [comment]
I'd be happy with either option. 

It is easier to delete the items I don't want than it is to retype the ones I do want.

**Comment by b-morgan** [comment]
Since there is already room for two buttons on each item, it would seem like that would be the best option. I find the UI changes are usually the hardest part.

**Comment by plusmouse** [comment]
Got a design for the buttons:
![image](https://user-images.githubusercontent.com/60280559/141438197-b2be611a-cd69-482e-a02f-15d41da7dc6e.png)

- [ ] Prevent button being visible/clickable when no shopping list is select or show appropriate error message
- [ ] Give visual feedback that the button was clicked (to avoid people repeatedly clicking it thinking it did nothing)

**Comment by plusmouse** [comment]
Find this in the latest alpha `9.1.12-1-g43ff39e`
