### ISSUE TITLE
Filter junk listing when updating database

### ISSUE THREAD

**Issue by Debuggernaut** [Auctionator/Auctionator#1096]
Hey team, there's a bad apple on my server who runs a bot 24/7 that continuously reposts single stacks of commodity items for insanely low prices in order to trick people into undercutting him, and then he immediately buys out the underpriced stuff

example:
![image](https://user-images.githubusercontent.com/20571604/141658248-c5421ec9-edeb-480f-8c6e-ac65ddd827a5.png)

I poked around in Auctionator trying to find a good way to make it easy to avoid getting ensnared by this dude, but unfortunately it looks like my local auctionator DB is getting filled with bad data from seeing this guy's bad listings, so Auctionator.Database.GetFirstPrice() will always return the lowest price, which is always the bot's evil trick listing.

Could someone point me toward where the database gets updated from a new AH scan?  Maybe I can patch my local copy to just drop the first entry if it's a high-volume commodity and way underpriced.

**Comment by plusmouse** [comment]
You're looking for [this line](https://github.com/Auctionator/Auctionator/blob/127de5e149e84eb44b590dd72a8b3260d6aa8235/Source_Mainline/Tabs/Selling/Mixins/SaleItem.lua#L386) (the AH scan price is used when no current prices are found, which is why its a different line)

1. Would a seller blacklist help to remove these entries?
2. What formula would you use to determine if the first entry is underpriced?

**Comment by Debuggernaut** [comment]
Thanks man!

Let me play with it a little

I don't think a blacklist would help, since the guy's bot gets banned every 2-3 days, and he switches his bot to a new account

I'll probably try to do something like this:

When I'm updating the database, I'll:
- check to see if there's more of 10,000 of an item listed total
- calculate the average price of the cheapest 10% of the items up for sale 
- throw out anything priced less than 70% of that average for the purpose of deciding what the lowest price is on an item

Ideally it'd be nice if I could just run my own bot to counter his, but I don't want to get banned, haha.

**Comment by plusmouse** [comment]
This issue has been resolved. Closing.
