### ISSUE TITLE
Allow parallel filter check and receipt of browse scan result additional pages using CachingSearchProvider

### ISSUE THREAD

**Issue by Valkylbank** [Auctionator/Auctionator#1097]
**Is your feature request related to a problem? Please describe.**

When using the caching search provided for shopping scans (with 50+ items in the shopping list), at some point the AH throttle is reached due to the budget on AH actions, and the WoW client and Auctionator addon receives an additional page of 500 items every few seconds.  The received items are not processed for checking against filters until the entire browse scan is complete, which can take several minutes on a large server.  The delay can potentially lead to items being bought by other players before the scan can complete.

**Describe the solution you'd like**

Add scanning of each page of browse results either at a game state where AH throttle is reached, or by some configuration option to always process results per page (when browse query new results received), rather than to wait for the entire AH scan to finish.  This will require a change to the order of processing in the search code to allow for parallel events of receiving new AH data and scanning the cache.

**Comment by plusmouse** [comment]
As stated this would require changes to the search code, disrupting the current abstractions that keep the components separate, as such we're unlikely to implement this.
