### ISSUE TITLE
SoM: Selling: Training Sword shows as none available when there are other listings

### ISSUE THREAD

**Issue by jalongino3** [Auctionator/Auctionator#1098]
Both the Search and Shopping tabs correctly showed 5 "Training Sword of the Tiger" items. However the Selling tab showed nothing. Refresh didn't help.  This is in WoW SoM.

## Loaded Addons
Altoholic, Bagnon, DataStore, GatherMate 2, Healbot, Questie, Scrap, Titan Panel Classic.

## Back Trace (LUA Error Output)

No LUA error message.

**Comment by plusmouse** [comment]
Can I get a screenshot of the item's tooltip when inside your bag?

**Comment by jalongino3** [comment]
Unfortunately, I've already put it on auction. But here is a snapshot of it
on the auction house. Hope that helps.

--Jim

**Comment by jalongino3** [comment]
If the previous snapshot doesn't help, let me know and I'll cancel the
auction if I can.

--Jim

**Comment by plusmouse** [comment]
Closing this issue.

Had someone try to replicate the issue with a training sword, but the issue didn't reoccur. I'm unsure why it glitched in this particular case. If it happens again please report it again, but there isn't anything I can do to fix the issue at the moment.
