### ISSUE TITLE
Keybind ALL THE THINGS!

### ISSUE THREAD

**Issue by fooshards** [Auctionator/Auctionator#1101]
**Is your feature request related to a problem? Please describe.**
I like to use both hands when playing

**Describe the solution you'd like**
I would like the buttons in Auctionator to either 1)  Have specific assignable keybinds for each    or  2)  Have a global "skip confirmation" modifier, like to hold shift while leftclicking the button, or a middleclick instead of leftclick.  etc

The usability problem I experience is this:   I click the Shopping tab.   I need to buy like 200 linen cloth.  The UI organizes this list and I do in fact love it.   

https://imgur.com/a/zaMHLi6

However, consider that I want to buy a pantsload of linen.  My literal process is:

1) Mouseover to top of list
2) Click to select row
3) mouseover to buy button
4) Click, spawning the buy Atr_Buy_Confirm_Frame
5) mouseover to buy stack button
6) click, wait for update  (to be very clear, this wait for update is legit and I am not complaining about this speed)
7) spam click repeat step 6  until "none left" is shown
8) mouseover to close
9) click close to despawn the buy stack/close screen

repeat by like 50 times, in order to get the cheapest 200 linen

All the while, my left hand is sitting idly by

I would ask for a better process, either one of two:

1)  Mouseover to top of list
2) Hold $MODIFIER_KEY with left hand
3) click to select row with right hand
4) wait for update, as the addon places an order to buyout one stack of whatever i have selected

OR:

1) Mouseover to top of list
2) Click to select row
3) Press $HOTKEY_1 to invoke the buy button and spawn the buy stack/close screen
4) Press $HOTKEY_2 to invoke the Atr_Buy_Confirm_OK button and wait for update

**Describe alternatives you've considered**
Keybinds are unavailable, although realistically the "bypass confirm" toggle is a real winner IMO

**Additional context**
Both of my hands are functional!  My free hand typed up this issue report faster than my mousing hand took to buy 200 linen (minor hyperbole, or is it?)

**Comment by fooshards** [comment]
Oh another rambling thought too would be to make it so the "ESCAPE" button does not nuke the whole auction UI, and instead would simply close the Atr_Buy_Confirm_Frame

**Comment by plusmouse** [comment]
I've added a new option to the buy dialog that should help https://github.com/Auctionator/Auctionator/issues/1107#issuecomment-1004915168

Comment here to indicate if that is enough to close the issue or if we still need to add a keybinding.

**Comment by plusmouse** [comment]
Closing this issue as fixed - the new "Chain buy" element of the buy dialog solves this usecase.
