### ISSUE TITLE
Make sorting by name optional

### ISSUE THREAD

**Issue by dale206Git** [Auctionator/Auctionator#1103]
**Is your feature request related to a problem? Please describe.**
All my shopping lists are carefully sorted by gem color and the automatic sorting by name makes them very confusing and difficult to read.

**Describe the solution you'd like**
Make sorting by name optional, or offer different sorting options including custom and/or off/no sort.

**Describe alternatives you've considered**
For now, I switched back to version 9.1.4 (see screenshot)

**Additional context**

![Untitled-1](https://user-images.githubusercontent.com/84369924/144192685-5049464c-d7b8-4b3b-87a9-a4ee4a58098d.png)

**Comment by plusmouse** [comment]
I think what happened is you accidentally clicked the "Sort" button - they aren't sorted by default?
![image](https://user-images.githubusercontent.com/60280559/144207247-92f9f243-2a26-47d9-bf0e-0c6af522da8a.png)

**Comment by dale206Git** [comment]
Yes, the shopping list on the left side (as shown in your screenshot) is not automatically sorted, that remains as it is (and you can move items up or down, which is very useful) but I think the search results on the right side are automatically sorted?
________________________________

**Comment by plusmouse** [comment]
They are only sorted if you've clicked the header to sort them by name. A `/reload` will clear the sorting.
Not sorted:
![image](https://user-images.githubusercontent.com/60280559/144208640-48e021e3-983e-4412-9a7f-f9ccac460069.png)
Sorted:
![image](https://user-images.githubusercontent.com/60280559/144208715-c3e85389-fa5d-4ecf-b146-e130b1a7bb09.png)

**Comment by dale206Git** [comment]
Ok, sorry, I will try the latest version again.

**Comment by dale206Git** [comment]
Can I delete this thread or only close it? Where can I ask a question about sorting shopping lists? Thanks.

**Comment by plusmouse** [comment]
You can only close the thread. The discord is probably the best place for that, or you can open a new issue.
