### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by dale206Git** [Auctionator/Auctionator#1104]
Thank you for this great addon. I am trying to find answers to the following questions...

In the Shopping tab, after clicking on a header to sort the search results, is there a way to go back to the unsorted results (shopping list order) without logging out?

Is there a way to rearrange shopping lists without using the export/import feature?

In the Selling tab, under each category, in which order are the items to sell listed and can that be changed?

**Comment by plusmouse** [comment]
Using `/reload` to reload the UI will reset the search headers, there isn't another way to go back to unsorted results.

You can click-and-drag an item in the shopping list to change its position.

In the Selling tab the sort is based on the item ID, not the name or anything player facing, there isn't currently a way to change that. Adding an item to your favourites (right-click and "Add Favourite") will create a new entry for the item at the top of your bag.
![image](https://user-images.githubusercontent.com/60280559/144647264-8b5cf167-97dd-4a90-9641-a2605ed824a1.png)

**Comment by dale206Git** [comment]
Thanks! Yes, I click-and-drag items in a shopping list all the time, but I was wondering if there's a way to rearrange the shopping lists as they appear in the drop-down list. The only way I found so far is to export them all, rearrange the lines in a text file, and then import them back... However, I guess this question does not apply to the latest version where I remember they were automatically arranged in alphabetical order...

**Comment by plusmouse** [comment]
Yeah. The alphabetical sorting was a user request to help finding a shopping list.

Adding a UI to reorder the dropdown entries is unlikely - especially now its automatically sorted.

**Comment by dale206Git** [comment]
Yes, I was expecting to be able to drag and drop shopping lists, but then again not from a dropdown list, that wouldn't feel right. Maybe you could consider moving the shopping lists to a different type of control where they can be easily rearranged. Ideally, one should see a two-level hierarchy, shopping lists names and shopping list items, and be able to rearrange both (not only the items). For now, there are easy workarounds though (prefix shopping list names with some characters to force a custom order, same as with Windows folder names, for the versions with alphabetical sorting, or my export/import trick for previous versions).

**Comment by dale206Git** [comment]
Just found 9.0.0.4 on my laptop and it keeps my custom sort order for items in the Selling tab, as well as the shopping lists in the dropdown, so I'll use that for now...
