### ISSUE TITLE
Incorrect default stack count for selling items 

### ISSUE THREAD

**Issue by kenthklui** [Auctionator/Auctionator#1105]
## Brief Description of Bug

When using a default maximum stack size of 0, the AH selling interface is filling an incorrect stack count.

## Steps to Reproduce

1. Use a default stack size setting of "0 stack of 1" - ie. maximum number of stacks of 1.
2. Have multiple stacks of an item, ie. 2 stacks of 20 Arcane Dust, total 40.
3. Go to "selling" tab.
4. Either drag-and-drop a stack of items into the selling slot, or alt-left-click stack of items from bag. ie. Select 1 of the 2 stacks of 20 Arcane Dust for selling.

**Expected result:**
Selling tab should default to maximum stacks of 1 Arcane Dust each, ie. "40 stacks of 1".

Alternatively, I think 20 stacks of 1 is also acceptable, as it is what was dragged and dropped into the selling tab. Perhaps this should be another feature?

**Observed result:**
Selling tab defaults to a maximum stack number equal to the "number of maximum stacks" in your bag. In this case, it will default to "2 stacks of 1", because the player has 40 Arcane Dust in their bags, which can fill 2 full stacks of 20.

If the player happens to have between 60-79 Arcane Dust in bag, it will default to "3 stacks of 1", because the player is holding 3 full stacks of 20. This occurs regardless of how many stacks the Arcane Dust has been split into, within the bag.

## Loaded Addons

I have reproduced this bug with all other addons disabled, only running the Auctionator addon.

## Back Trace (LUA Error Output)

No LUA errors occurred.

**Comment by kenthklui** [comment]
I can't really make a video, and I know a screenshot doesn't really prove or show the bug, but I hope this helps explain the issue:
![image](https://user-images.githubusercontent.com/1038272/144760853-cc406704-8de1-4a5b-a391-086dafdec396.png)
You can see that the user has 70 Arcane Dust, but the stack number is defaulting to 3 instead of 70 or 20.

**Comment by plusmouse** [comment]
An alpha version will be on Curseforge shortly with a fix for this issue. The sceenshot helped 😃 . In the interim you can download this version
[Vanilla.zip](https://github.com/Auctionator/Auctionator/files/7656699/Auctionator-9.1.12-7-g2c6bbfb-classic.zip)
[TBC.zip](https://github.com/Auctionator/Auctionator/files/7656701/Auctionator-9.1.12-7-g2c6bbfb-bcc.zip)

**Comment by kenthklui** [comment]
Thanks for the quick response!
