### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by muRmot** [Auctionator/Auctionator#1106]
Want to offer a feature. 
Shift+click in the "Selling" on the Trade Goods = Lead to one click putting item on AH (without moving mouse so far to button "Post").

**Comment by muRmot** [comment]
Do not know how to add label yet.

**Comment by muRmot** [comment]
No one watchin this section?

**Comment by plusmouse** [comment]
Posting an item is at least 2 actions, the first one being a search for the current prices.

You can post without moving your mouse by pressing the "Space" key on your keyboard after the item is selected?

**Comment by muRmot** [comment]
> Posting an item is at least 2 actions, the first one being a search for the current prices.
> 
> You can post without moving your mouse by pressing the "Space" key on your keyboard after the item is selected?

ty, solved, didn't know
