### ISSUE TITLE
TBC Suggestion: Faster to rapid buy

### ISSUE THREAD

**Issue by dennisdahlc** [Auctionator/Auctionator#1107]
Hello and thank you for a great addon.

When buying a stack of items, would it be possible to close the modal if no more stacks are available? If this is not wanted as default, I would settle for an options. But it would help me immensely when buying a lot of different stacks of items in larger quantities

**Comment by plusmouse** [comment]
The latest alpha has a new option that should do what you want:
![image](https://user-images.githubusercontent.com/60280559/148084063-0ac81b39-3000-48bb-8f34-a41c47b1302a.png)
[Download it here or on curseforge](https://github.com/Auctionator/Auctionator/files/7808651/Auctionator-9.1.12-11-g647a081-bcc.zip)
