### ISSUE TITLE
Shift + Click not linking to chat window from shopping tab (TBC Classic)

### ISSUE THREAD

**Issue by cogara** [Auctionator/Auctionator#1108]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

Previously, I could shift+click from shopping tab to link into chat. Since the UI was updated, it seems to no longer work. (TBC Classic)

## Steps to Reproduce

Open shopping tab. search for item. shift+click the item, listing, or any part of the AH does not link to chat. Tried history/current tabs as well.

## Loaded Addons

Adibags
Atlas
Attune
Auctionator
Details
ElvUI
Grid2
TSM
Itemrack
Leatrix (+ maps)
Neatplates
OPieRing
Weakauras
DBM
Questie

## Back Trace (LUA Error Output)

no error, just doesn't link to chat

**Comment by plusmouse** [comment]
Are you referring to Shift+Clicking here?
![image](https://user-images.githubusercontent.com/60280559/147145344-dfb3d9b8-fd16-4a16-a231-d47ba719d75e.png)

**Comment by plusmouse** [comment]
(I can make it Shift+Click, but need to double check that that is what you intended)

**Comment by cogara** [comment]
there, or in my UI it has the item above that, as well, that used to work. I'll try get a SS

**Comment by cogara** [comment]
![image](https://user-images.githubusercontent.com/18064694/147196189-1784e2db-d938-461f-9491-16cb4abf3a54.png)
clicking into the item, it shows all the listings. on the top is the icon of the item. That's where I used to be able to shift+click

![image](https://user-images.githubusercontent.com/18064694/147196233-5bed785d-f72e-49fa-b958-37e8631feaf5.png)
and here on the selling, this icon works to link to chat. It seems just the shopping tab doesn't allow it.

**Comment by plusmouse** [comment]
Fixed. Will be available as an alpha from curseforge shortly, or you can download it [here](https://github.com/Auctionator/Auctionator/files/7768425/default.zip)

**Comment by cogara** [comment]
oh, sweet. thanks.
