### ISSUE TITLE
Items disappear

### ISSUE THREAD

**Issue by Mome25** [Auctionator/Auctionator#1111]
Hello everyone,
I'm playing WoW classic on Ironfoe, using auctionator. First thing: when I put an item on the square to sell it, before choosing the price and click ok, I did a full scan and the item just disappeared: it wasn't in my bank, my mail or between the auctions. It was a receipe and I didn't learn it.
Then, I had some items on the AH, I didn't sell them but still they disappeared and they are nowhere to be found, after that the time to sell them expired.

**Comment by plusmouse** [comment]
Hi. I'm sorry about the missing items. I have previously had a user report mail being delayed, and the item arriving eventually.

Which items were they specifically so I can test on my computer?

**Comment by plusmouse** [comment]
Do you know what Blizzard meant by "burnchange"?

**Comment by Mome25** [comment]
I asked them. Waiting for their answer

**Comment by Mome25** [comment]
Ok, everything is solved now, no problems :) Thank you!

**Comment by plusmouse** [comment]
Awesome
