### ISSUE TITLE
Shift-click + mouse clicking, does not paste clicked item 

### ISSUE THREAD

**Issue by seskobrodo** [Auctionator/Auctionator#1112]
I've used auctionator classic fixed for 2 years in tbc+vanilla, but in SoM it has errors, so I downloaded the
auctionator that works in SoM. When doing the two things I always do to save time, it appears to not function.
So I have to manually write the product I am looking for, especially in enchanting or leather-working tab, when you need materials.

**Comment by plusmouse** [comment]
Which two things are they? Using Shift+Click to search for an item when the Shopping tab is open works, and when the AH is open a search button appears in the crafting panel to search for all the reagents:
![image](https://user-images.githubusercontent.com/60280559/149084612-7886b41f-92e5-450f-9483-2af45636cc69.png)

**Comment by seskobrodo** [comment]
I actually dont have that search button there, but the issue is if you were to shift+mouse1 click the "bolt of linen cloth" image, it doesnt paste it directly in to the search area

**Comment by plusmouse** [comment]
It does for me. Can I get a screenshot of how you're trying to do it?

**Comment by seskobrodo** [comment]
![Capture](https://user-images.githubusercontent.com/75147266/149085680-e6841bcf-cf22-4539-93c7-dd19c45e8897.PNG)

**Comment by seskobrodo** [comment]
so 1) mouse over Strange Dust 2) hold shift 3) click mouse1 4) nothing happens

**Comment by plusmouse** [comment]
1. Have you restarted WoW since installing the new version of Auctionator?
2. It looks like a bug is preventing the Shift+Click from working, if restarting the client doesn't fix the issue, can you installing BugGrabber (retail version works) + BugSack and tell me what error they report?

**Comment by seskobrodo** [comment]
yeah, give me a minute or two

**Comment by seskobrodo** [comment]
I installed them, tried again, but didnt get any notification from bugsack that I can see

**Comment by plusmouse** [comment]
OK. I think the bug is a Blizzard change - I tried disabling Auctionator and it _still_ wouldn't let the Shift+Click shortcut work (I setup a SoM character with enchanting to test). I'll do some digging to try and find a workaround.

Oddly, Shift+Click on the dust adds a link to chat and shift+clicking an item in your bag searches for it.

**Comment by seskobrodo** [comment]
nice, hopefully you find a solution for it! 👍 

yeah it definitely seems to be a SoM thing, I've never had this issue in classic tbc/retail before

**Comment by plusmouse** [comment]
I've added a fix for this to the newest alpha
[Auctionator-9.2.18-5-ga98fca4-classic.zip](https://github.com/Auctionator/Auctionator/files/8838553/Auctionator-9.2.18-5-ga98fca4-classic.zip)
