### ISSUE TITLE
Suggestion: show the price per piece when chain buying

### ISSUE THREAD

**Issue by dennisdahlc** [Auctionator/Auctionator#1113]
![image](https://user-images.githubusercontent.com/17319141/149186451-e13dce77-f2e3-4670-8f24-52be2511eb46.png)

I love the new chain buy feature.
I have a small request though.
Would it be possible to show the individuel price when chain buying?
It's not possible to see whether you could be getting scammed and suddenly buying the items at overprice.

**Comment by plusmouse** [comment]
Something like this?
![image](https://user-images.githubusercontent.com/60280559/149190127-3bc4211d-5062-4e1f-929f-b35035e96fd2.png)

**Comment by dennisdahlc** [comment]
That would be incredible <3

**Comment by plusmouse** [comment]
This feature can now be found in the newest alpha (available from Curseforge shortly)
[Auctionator-9.1.13-2-ga0cf3ac-bcc.zip](https://github.com/Auctionator/Auctionator/files/7856576/Auctionator-9.1.13-2-ga0cf3ac-bcc.zip)
