### ISSUE TITLE
Stack sizes keep changing instead of using max

### ISSUE THREAD

**Issue by Jokaleth** [Auctionator/Auctionator#1116]
In the "Selling: All Items" settings I have the Default Stack Sizes both set to Max: 0, however when I actually go to sell items instead of choosing the max stack size (usually 20) it keeps choosing random different numbers instead, For example I had 132 Knothide Leather in my inventory, and instead of trying to sell them in stacks of 20 it changed to selling in stacks of 13.

**Comment by plusmouse** [comment]
I've released a fixed version (9.1.14). It'll take a few moments to be on Curseforge.
You can download it here in the interim: [Auctionator-9.1.14-bcc.zip](https://github.com/Auctionator/Auctionator/files/7883069/Auctionator-9.1.14-bcc.zip)
You'll need to click this button just the once to fix the issue permanently after installing the update:
![image](https://user-images.githubusercontent.com/60280559/149799874-c88aab71-4cd9-4899-ad68-6ab7e1bbbb5e.png)
