### ISSUE TITLE
[suggestion & bug] Shopping List sorting

### ISSUE THREAD

**Issue by tflo** [Auctionator/Auctionator#1118]
Auctionator 9.1.14, release; WoW Retail, Shadowlands

***

One of the great features of Auctionator is that it allows me to build my Shopping Lists in a customized order and having the results being displayed in exactly that order.

But – unless I’m blind — it seems that once having sorted the results by one of the table headers, there is no way back to my default order, except reloading the UI.

I suggest to add something like (for example) alt-clicking one of the headers to reset the results sorting to the items order.

***

BTW, when I click the ‘Owned?’ column header of any Shopping List, I can reliably produce a nil:

```bash
1x ...\Source_Mainline\Tabs\DataProviders\ShoppingList.lua:91: attempt to call field '?' (a nil value)
[string "@Auctionator\Source_Mainline\Tabs\DataProviders\ShoppingList.lua"]:91: in function `Sort'
[string "@Auctionator\Source\Components\ResultsListing\Mixins\ResultsListing.lua"]:141: in function `sortFunction'
[string "@Auctionator\Source\Components\ResultsListing\Mixins\AuctionatorStringColumnHeader.lua"]:21: in function `DoSort'
[string "@Auctionator\Source\Components\ResultsListing\Mixins\AuctionatorStringColumnHeader.lua"]:38: in function <...ultsListing\Mixins\AuctionatorStringColumnHeader.lua:36>
```

***

Thank you for developing Auctionator.

– Tom

**Comment by plusmouse** [comment]
I've fixed the "Is Owned" sorting error.

I'll keep this issue open for the sort resetting though.

**Comment by plusmouse** [comment]
Fixed. Find it in the latest alpha, available in a few minutes from Curseforge
[Auctionator-9.2.13-4-gea104e4.zip](https://github.com/Auctionator/Auctionator/files/8546733/Auctionator-9.2.13-4-gea104e4.zip)
.

**Comment by plusmouse** [comment]
Its been setup to use [Shift] + Click on a column header to reset the sorting.

**Comment by tflo** [comment]
Wow, great, thank you a thousand times!
