### ISSUE TITLE
Unable to scan auction items in TBC and error reported

### ISSUE THREAD

**Issue by xuhua0508** [Auctionator/Auctionator#1121]
Using the 9.1.16-BCC version

## Brief Description of Bug

In the TBC game, when I click Sell and select an item, the item is not scanned and a LUA error appears.

## Steps to Reproduce

在TBC游戏中，当我点击销售，选择物品时，不会扫描商品,也无法显示同一物品的所有拍卖价格，并且会出现一个LUA错误。  

## Loaded Addons

I disabled all the plugins, and restarting the game also failed.

## Back Trace (LUA Error Output)

Message: ...ns\Auctionator\Source\Utilities\DelimitThousands.lua:6: bad argument #1 to 'gsub' (string expected, got table)
Time: Thu Feb 10 14:23:20 2022
Count: 1
Stack: ...ns\Auctionator\Source\Utilities\DelimitThousands.lua:6: bad argument #1 to 'gsub' (string expected, got table)
[string "=[C]"]: in function `gsub'
[string "@Interface\AddOns\Auctionator\Source\Utilities\DelimitThousands.lua"]:6: in function `DelimitThousands'
[string "@Interface\AddOns\Auctionator\Source\Tabs\DataProviders\HistoricalPrice.lua"]:50: in function `SetItem'
[string "@Interface\AddOns\Auctionator\Source_TBC\Tabs\DataProviders\BuyingHistoricalPrice.lua"]:5: in function `callback'
[string "@Interface\AddOns\Auctionator\Source\Utilities\DBKeyFromLink.lua"]:44: in function `DBKeyFromLink'
[string "@Interface\AddOns\Auctionator\Source_TBC\Tabs\DataProviders\BuyingHistoricalPrice.lua"]:4: in function `SetItemLink'
[string "@Interface\AddOns\Auctionator\Source_TBC\Tabs\Buying\Mixins\Main.lua"]:203: in function `ReceiveEvent'
[string "@Interface\AddOns\Auctionator\Source\Utilities\EventBusMixin.lua"]:77: in function `Fire'
[string "@Interface\AddOns\Auctionator\Source_TBC\Tabs\Selling\Mixins\SaleItem.lua"]:235: in function `SellItemClick'
[string "@Interface\AddOns\Auctionator\Source_TBC\Tabs\Selling\Mixins\SaleItem.lua"]:142: in function <...tionator\Source_TBC\Tabs\Selling\Mixins\SaleItem.lua:139>

Locals: (*temporary) = <table> {
}
(*temporary) = "([^%d]*%d+)(%d%d%d)"
(*temporary) = "%1,%2"
(*temporary) = "string expected, got table"

**Comment by plusmouse** [comment]
Back up your shopping lists (using the "Export" button), close WoW, and then backup and delete your `[WoW Directory]\_classic_\WTF\Account\[Some numbers]\SavedVariables\Auctionator.lua` file. It looks like it might be corrupted. That should fix the error.

**Comment by xuhua0508** [comment]
> 备份您的购物清单（使用“导出”按钮），关闭 WoW，然后备份并删除您的`[WoW Directory]\_classic_\WTF\Account\[Some numbers]\SavedVariables\Auctionator.lua`文件。看起来它可能已损坏。那应该可以解决错误。

Why is that? Is there any way to avoid it? Is there a plug-in conflict lookup table?

**Comment by xuhua0508** [comment]
The solution found temporarily is to delete the entire WTF folder of TBC; But it clears all Settings.

**Comment by plusmouse** [comment]
Can you send me your Auctionator.lua file so I can inspect it and figure out what exactly went wrong?

**Comment by plusmouse** [comment]
There isn't a way to figure out which plugins conflict without turning them on/off one by one

**Comment by xuhua0508** [comment]
[Auctionator.zip](https://github.com/Auctionator/Auctionator/files/8039194/Auctionator.zip)
Lua and Auctionator.lua.bak are all compressed and uploaded; Thank you for your trouble.

> 如果不逐个打开/关闭它们，就无法确定哪些插件冲突



> 你能把你的 Auctionator.lua 文件发给我，这样我就可以检查它并找出到底出了什么问题？

**Comment by plusmouse** [comment]
Thanks a lot for the files, they helped me find the bug. I've released a fixed alpha version of Auctionator, available [here](https://github.com/Auctionator/Auctionator/files/8039403/Auctionator-9.1.16-2-g9ce7621-bcc.zip)
or on Curseforge/Wago in 5-10 minutes

**Comment by plusmouse** [comment]
You'll need to use a new `Auctionator.lua` saved variable file though (just deleting the old one should work)

**Comment by xuhua0508** [comment]
> 非常感谢这些文件，他们帮助我找到了错误。我已经发布了 Auctionator 的固定 alpha 版本，可[在此处](https://github.com/Auctionator/Auctionator/files/8039403/Auctionator-9.1.16-2-g9ce7621-bcc.zip) 或在 5-10 分钟内访问 Curseforge/Wago



> You'll need to use a new `Auctionator.lua` saved variable file though (just deleting the old one should work)



Thank you very much for your help. I will use it for a period of time and then give feedback.
