### ISSUE TITLE
Buying not chossing the next lowest stack price with chain buy

### ISSUE THREAD

**Issue by silkanwow** [Auctionator/Auctionator#1122]
Please include as much of the following information as possible to help me fix the bug:

I was on AH in SW, buying Arcane Powder. Saw that there was a few stacks avalible at a low cost. Looked away for a brief second and when i looked back I had just bought one Powder for 3400 gold. The Auction listings looked excatly as they look in the screenshot. I posted one for the same price so that you can see excatly what my screen looked like. 

I was saving up for the swift flying mount. GG Auctionator. Countless grinding hours gone in a swift moment.

![image](https://user-images.githubusercontent.com/100447974/155810895-5720fde4-734f-4316-854c-59bbac057d5a.png)

**Comment by plusmouse** [comment]
I'm really sorry about that.

Did it show the correct price in the buy-confirm popup? I've tried using Chain Buy and can't replicate the behaviour.

**Comment by plusmouse** [comment]
I've added a new warning that interrupts purchases when the price jumps up a lot, which should resolve this issue.
![image](https://user-images.githubusercontent.com/60280559/156591793-a56a7cfe-b3ad-4c4c-acbe-5a714245f36d.png)
Closing (if that doesn't help reply here and I can reopen the issue)
