### ISSUE TITLE
Right click on other listings does not adjust your price

### ISSUE THREAD

**Issue by addonaddict** [Auctionator/Auctionator#1123]
Please include as much of the following information as possible to help me fix the bug:

Clicking on other prices in the list when selling does not adjust your price to match (or undercut)
This used to work before

![image](https://user-images.githubusercontent.com/73442541/156199193-a14ecb06-8f85-47d4-8ab5-90a3c38b1c51.png)

No bugsack errors or anything

**Comment by plusmouse** [comment]
Disable the right-click to cancel shortcut and that will make it work again:
![image](https://user-images.githubusercontent.com/60280559/156200116-da7eb133-892b-4c49-8370-12f89ee05156.png)

It defaults to right-click to cancel.

**Comment by addonaddict** [comment]
Awesome thanks! Didnt even realize this
