### ISSUE TITLE
Feature request: Keep item selected after post if item count greater than Selling Quantities setting

### ISSUE THREAD

**Issue by dracosveen** [Auctionator/Auctionator#1126]
**Is your feature request related to a problem? Please describe.**
If you have 500 of an item and your Selling Quantity is set to 20, then when you click post, you have to select the item again to to sell the next 20.  Alternatively, if you have the Select Next Item setting set, then you cycle through items until there is only one item left but then have to select it after each post.  Since there is no auto-post feature (blizzard changed post to need a physical action), having the option to be able to have the same item selected again as described above would greater enhance the selling experience.

**Describe the solution you'd like**
* Add an option in settings to allow for the same item to be set after clicking POST if the item's stack amount is greater than the Selling: Quantities setting for the item.
* So I have 500 leather.  Selling:Quantities:Consumables is set to 20.  I select leather and click post.  Leather remains as the selected item.

**Describe alternatives you've considered**
I have tried implementing an auto-post feature.  Obviously this doesn't work due to Blizzard requiring a physical action to trigger the POST action.  The next best solution is the one I have proposed above.  I have implemented locally so I know that it can work however I did not do a pull request because I can see that you have an established naming convention and my understanding of LUA is not that good, so it is better that it is implemented by you.

**Comment by plusmouse** [comment]
Stack sizes are irrelevant in Shadowlands.  A player can purchase any amount from any amount posted. For example if you post 200, a player can then buy just 5 of them. Unless you're trying to do something different?

**Comment by dracosveen** [comment]
Well then I must profusely apologize for wasting your time. I have only just returned to wow. Last time I played was Pandaria or before Legion. Didn’t realise that this was not a thing anymore. Thank you for replying.
