### ISSUE TITLE
Bug on Apparences

### ISSUE THREAD

**Issue by Machou** [Auctionator/Auctionator#1128]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

Date: 2022-03-20 10:34:49
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\CollectionShop\CollectionShop.lua line 960:
   bad argument #1 to 'GetCategoryInfo' (Usage: local name, isWeapon, canHaveIllusions, canMainHand, canOffHand = C_TransmogCollection.GetCategoryInfo(category))
Debug:
   [string "=[C]"]: GetCategoryInfo()
   [string "@CollectionShop\CollectionShop.lua"]:960:
      CollectionShop\CollectionShop.lua:921
   [string "@CollectionShop\CollectionShop.lua"]:967: SetMode()
   [string "@CollectionShop\CollectionShop.lua"]:3381:
      CollectionShop\CollectionShop.lua:3380
Locals:
(*temporary) = 30

## Steps to Reproduce

When i go to Auction for Appereance.

## Loaded Addons

AddOns:
  Swatter, v9.1.BETA.5.3 (OneMawTime)
  Auctionator, v9.2.3
  AzeritePowerWeights, v9.2.0
  BadBoy, vv9.1.0
  ClassicQuestLog, v2.0.8
  CollectionShop, v4.04
  GTFO, v4.66.4
  HandyNotes, vv1.6.5
  HandyNotesArgus, vv0.34
  HandyNotesAzerothsTopTunes, vv1.3.1
  HandyNotesBattleForAzeroth, v9
  HandyNotesBattleForAzerothTreasures, vv20
  HandyNotesBrokenShore, vv1.47
  HandyNotesDraenor, v2.4
  HandyNotesDraenorTreasures, v1.21
  HandyNotesEliteBattlePets, v1
  HandyNotesHallowsEnd, vv1.5.1
  HandyNotesKosumoth, v1
  HandyNotesLegionInstanceWorldQuests, vv1.31
  HandyNotesLegionTreasures, vv24
  HandyNotesLongForgottenHippogryph, v1
  HandyNotesLostAndFound, vv16
  HandyNotesOribos, vv16
  HandynotesPandaria, v1.5.1
  HandyNotesShadowlands, v46
  HandyNotesShadowlandsTreasures, vv56
  HandyNotesStygia, vv90200.0
  HandyNotesSuramarShalAranTelemancy, vv1.39
  HandyNotesSuramarTelemancy, vv9
  HandyNotesTimelessIsleRareElites, v2.32
  HandyNotesTimelessTreasures, v1.1.0
  HandyNotesTravelGuide, vv2.7.0
  HandyNotesTreasureHunter, vv25
  HandyNotesVisionsOfNZoth, v42
  HandyNotesWitheredArmyTraining, v1
  InterruptNoSpam, v1.8.5
  NugComboBar, v9.2.0
  Pawn, v2.5.34
  Prat30, v3.9.1
  Prat30Libraries, v
  RareScanner, v9.2.0.4
  Rarity, v1.0 (r715-release-4)
  RarityOptions, v
  Recount, vv9.2.0a
  Rematch, v4.11.20
  TargetPercent, vv9.2.0
  TomTom, vv3.0.6
  TrollTheBones, v9.2.0 build 1
  WeakAuras, v3.7.13
  WorldQuestTracker, v
  BlizRuntimeLib_frFR v9.2.0.90200 <none>
  (ck=5d7)

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by plusmouse** [comment]
We don't make collectionshop, so I can't help you with that specific error. However you probably meant to install Collectionator - which we do support - for it's transmog feature https://www.curseforge.com/wow/addons/collectionator/files which will do what you're looking for

**Comment by Machou** [comment]
Ah, I'm sorry, I'm back to WoW, I'm a bit lost with all the changes :)

Great addon anyway, much better than the other one; thanks :)
