### ISSUE TITLE
[Selling Tab] Cancel Auction. No longer updates selling tab ui. Upon last auction cancelled, lua error.

### ISSUE THREAD

**Issue by Xian55** [Auctionator/Auctionator#1129]
## Brief Description of Bug

Cancelling auctions in the `Selling` tab no longer update the posted stack count. When the last stack is getting cancelled a lua error shows up.

## Steps to Reproduce

tbc version: 
```
Dump: value=GetBuildInfo() 
[1]="2.5.3", 
[2]="42598", 
[3]="Mar  3 2022", 
[4]=20503
```

[video](https://user-images.githubusercontent.com/367101/159356733-db48a2d0-359e-465f-9ea8-2bf73e912a77.mp4)

1. Using default settings
1. Post a few stacks of an item in auction.
1. `Alt + Left` click on the item in the inventory, to show the `Selling` tab
1. Select the related stack of auction
1. Start pressing the `Cancel Auction` button => As a result the `Available` row not getting updated.
1. When the last auction getting cancelled, lua eror shows up

## Loaded Addons

* `Auctionator` version `9.2.3-bcc` from https://addons.wago.io/addons/auctionator
* ElvUI
* BankItems Classic

## Back Trace (LUA Error Output)

```
Message: ...s\Auctionator\Source_TBC\Tabs\Buying\Mixins\Main.lua:118: attempt to index field 'selectedAuctionData' (a nil value)
Time: Mon Mar 21 21:08:53 2022
Count: 1
Stack: ...s\Auctionator\Source_TBC\Tabs\Buying\Mixins\Main.lua:118: attempt to index field 'selectedAuctionData' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\Auctionator\Source_TBC\Tabs\Buying\Mixins\Main.lua"]:118: in function `LoadForCancelling'
[string "@Interface\AddOns\Auctionator\Source_TBC\Tabs\Buying\Mixins\Main.lua"]:150: in function `CancelFocussed'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals: 
```

**Comment by plusmouse** [comment]
Sorry about the issue. I've fixed it in the latest alpha (available from Curseforge in a few minutes). Can you test it, and after you've checked its working I'll make it a full release.

**Comment by plusmouse** [comment]
This is the alpha file
[Auctionator-9.2.3-2-g4d72022-bcc.zip](https://github.com/Auctionator/Auctionator/files/8319077/Auctionator-9.2.3-2-g4d72022-bcc.zip)

**Comment by Xian55** [comment]
Hi, thanks for the quick reply.

With [Auctionator-9.2.3-2-g4d72022-bcc.zip](https://github.com/Auctionator/Auctionator/files/8319077/Auctionator-9.2.3-2-g4d72022-bcc.zip)
the supplied fix, it seems to be working again.
![image](https://user-images.githubusercontent.com/367101/159359265-35819ea5-08d0-4491-95b0-510ed8868de2.png)

**Comment by Machou** [comment]
@Xian55 how did do enable stack ?

**Comment by Xian55** [comment]
Hello there, i'm unable to figure out what are you asking about. Would you elaborate more about it?

**Comment by Machou** [comment]
> Hello there, i'm unable to figure out what are you asking about. Would you elaborate more about it?

When I go to the auction house, I can only sell my items by pile, not 1 by 1, so if I have 100 items, I have to sell them 1 by 1, it gets boring very fast :P

Like here:

[https://i.ibb.co/JvnNm9r/159359265-35819ea5-08d0-4491-95b0-510ed8868de2.png]

**Comment by Xian55** [comment]
I'm playing the Burning Crusade Classic version of the game. Its a basic feature of the addon.

Be sure to use the latest version. https://github.com/Auctionator/Auctionator/releases

**Comment by Machou** [comment]
Of course i have the latest. :) but i play on WoW  Normal, this is a screen of my interface :

[Image](https://i.ibb.co/KNjtBkg/Wo-WScrn-Shot-032222-050719.jpg)

**Comment by plusmouse** [comment]
The retail version of the addon doesn't have multiple stacks because they no longer matter in retail wow, you can post 200 ore and another player is allowed to buy 5 of them, even though they were posted in a 200.

If you have any further issues please open a new issue rather than reusing an existing one.
