### ISSUE TITLE
Error when i kill Rare ZM

### ISSUE THREAD

**Issue by Mithras2801** [Auctionator/Auctionator#1131]
Message: ...ace\AddOns\Auctionator\Source\ShoppingLists\Main.lua:34: bad argument #1 to 'ipairs' (table expected, got nil)
Time: Wed Mar 23 11:20:43 2022
Count: 1
Stack: ...ace\AddOns\Auctionator\Source\ShoppingLists\Main.lua:34: bad argument #1 to 'ipairs' (table expected, got nil)
[string "=[C]"]: in function `Show'
[string "@Interface\FrameXML\UIParent.lua"]:3017: in function `SetUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2823: in function `ShowUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2730: in function <Interface\FrameXML\UIParent.lua:2726>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface\FrameXML\UIParent.lua"]:3582: in function <Interface\FrameXML\UIParent.lua:3561>
[string "=[C]"]: in function `ShowUIPanel'
[string "@Interface\AddOns\Oilvl\Oilvl.lua"]:5601: in function `?'
[string "@Interface\AddOns\Oilvl\Oilvl.lua"]:5748: in function <Interface\AddOns\Oilvl\Oilvl.lua:5747>

Locals: (*temporary) = InterfaceOptionsFrame {
 0 = <userdata>
 numTabs = 2
 Header = <unnamed> {
 }
 Border = <unnamed> {
 }
 selectedTab = 1
}
(*temporary) = <function> defined =[C]:-1

**Comment by plusmouse** [comment]
What screen were you trying to view?
