### ISSUE TITLE
as long as you open the friendly nameplate, there will be an error

### ISSUE THREAD

**Issue by yourapple** [Auctionator/Auctionator#1136]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

in the dungeon, as long as you open the friendly nameplate, there will be an error

## Steps to Reproduce

in the dungeon,As long as you open the friendly nameplate, and then there will always be errors.
Outside the dungeon is ok

## Loaded Addons
BugSack
Auctionator

## Back Trace (LUA Error Output)

59x FrameXML\CompactUnitFrame.lua:1122: Attempt to access forbidden object from code tainted by an AddOn
[string "=[C]"]: in function `Hide'
[string "@FrameXML\CompactUnitFrame.lua"]:1122: in function `CompactUnitFrame_UpdateClassificationIndicator'
[string "@FrameXML\CompactUnitFrame.lua"]:1380: in function `CompactUnitFrame_UpdateAuras'
[string "@FrameXML\CompactUnitFrame.lua"]:96: in function <FrameXML\CompactUnitFrame.lua:45>

Locals:
(*temporary) = <unnamed> {
 0 = <userdata>
}

**Comment by plusmouse** [comment]
Can you post a screenshot of the nameplate? Is it a specific nameplate or does any one trigger this?

**Comment by yourapple** [comment]
![1](https://user-images.githubusercontent.com/32905192/160276134-3155780f-e064-4079-b5d9-16a1e4227482.png)
![2](https://user-images.githubusercontent.com/32905192/160276137-a9afaea7-6a31-4e79-935f-0cc1879a37ea.png)
![3](https://user-images.githubusercontent.com/32905192/160276141-7da36a1d-80cf-4c0f-8450-471f5e04b0b5.png)
![4](https://user-images.githubusercontent.com/32905192/160276150-0821f0a7-ff70-452e-a2bf-79326d5936df.png)
![5](https://user-images.githubusercontent.com/32905192/160276155-d68c5ca3-3e62-4146-a1d6-35386d95f260.png)
![6](https://user-images.githubusercontent.com/32905192/160276160-9cef2925-4e40-4044-937f-b957cdc5b02c.png)
![7](https://user-images.githubusercontent.com/32905192/160276168-0cbdd1d2-09ca-4a9f-9da1-9ec3901e03c6.png)

As long as Auctionator is disabled, everything should be fine. Or turn off friendly Nameplate

**Comment by plusmouse** [comment]
Can you try updating to the newest release 9.2.6 https://www.curseforge.com/wow/addons/auctionator/files/3718004 it includes a fix for this issue.

**Comment by yourapple** [comment]
Yes! No more error messages. Thank you so much.

**Comment by plusmouse** [comment]
As the fix broke something else I've released a new fix. Can you confirm that it works for you?
[Auctionator-9.2.9.zip](https://github.com/Auctionator/Auctionator/files/8360152/Auctionator-9.2.9.zip)

**Comment by plusmouse** [comment]
I've tested the fix with a party and friendly nameplates, no issues. Closing (not fix? comment and I'll reopen it)
