### ISSUE TITLE
Armor Item Class menu wrong

### ISSUE THREAD

**Issue by mbattersby** [Auctionator/Auctionator#1137]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

Wrong third level menu on Extended Search Item Class when second level selection is Armor.

The menu needs to be different per second-level. Not all of the options are the same. It should match what the Blizzard AH UI presents. As far as I can see there is currently no way to select a cloak, neck or ring item, and there's a confusing and unnecessary third level for Shields (which Blizzard groups under Miscellaneous).

The sort order is strange on the second level menu too.

![image](https://user-images.githubusercontent.com/1300207/160302138-1e6b4bee-e328-4871-b693-9e245bb0f289.png)

## Steps to Reproduce

Shopping Tab -> Extended Search -> Use the menus.

## Loaded Addons

N/A

## Back Trace (LUA Error Output)

N/A

**Comment by mbattersby** [comment]
I am fairly sure you can use the `AuctionCategories` global ones the (retail) AH is loaded.

**Comment by mbattersby** [comment]
```
local function printCategory(t, indent)
   indent = indent or ''
   print(indent .. t.name)
   for _, s in ipairs(t.subCategories or {}) do
      printCategory(s, indent .. '  ')
   end
end

for _,t in ipairs(AuctionCategories) do
   printCategory(t)
end
```

**Comment by plusmouse** [comment]
It looks like there's an equivalent table in TBC `AuctionCategories`, and your print code works with that too.

- [ ] Implement compatibility function to translate from current category strings into new strings (Retail and TBC)
- [ ] Implement FilterKeySelector with new categories
- [ ] Decide whether to store category filters as numerical values or to stick to the string values.

**Comment by plusmouse** [comment]
Find the fix/feature in the latest alpha.
