### ISSUE TITLE
Bug from actionator versus 20220401

### ISSUE THREAD

**Issue by Dedalios** [Auctionator/Auctionator#1143]
[bug.txt](https://github.com/Auctionator/Auctionator/files/8399865/bug.txt)

**Comment by plusmouse** [comment]
You didn't include any information about what the bug is. Please open a new report with the info included.

**Comment by Dedalios** [comment]
> You didn't include any information about what the bug is. Please open a new report with the info included.

[bug2.txt](https://github.com/Auctionator/Auctionator/files/8399870/bug2.txt)

**Comment by Dedalios** [comment]
[bug3.txt](https://github.com/Auctionator/Auctionator/files/8399873/bug3.txt)

**Comment by Dedalios** [comment]
[bug3.txt](https://github.com/Auctionator/Auctionator/files/8399876/bug3.txt)

**Comment by Dedalios** [comment]
[bug4.txt](https://github.com/Auctionator/Auctionator/files/8399878/bug4.txt)

**Comment by Dedalios** [comment]
[bug5.txt](https://github.com/Auctionator/Auctionator/files/8399880/bug5.txt)

**Comment by Dedalios** [comment]
[bug6.txt](https://github.com/Auctionator/Auctionator/files/8399881/bug6.txt)

**Comment by Dedalios** [comment]
Just repport when open the game

**Comment by plusmouse** [comment]
Thanks. Just going to test 9.2.11 now.

**Comment by plusmouse** [comment]
Could you try reinstalling Auctionator?

**Comment by plusmouse** [comment]
It looks like your install is corrupted somehow, and multiple addons are broken. This doesn't appear to be a bug with Auctionator.
