### ISSUE TITLE
how can I get the function "seller names" in the version 9.2.6?

### ISSUE THREAD

**Issue by LasombraK** [Auctionator/Auctionator#1147]
boss
please tell me, how can I get "seller name" when I sell something? 
this function could be used in version 9.2.6, it's good one!
but it is not shown in the newest version.
so how can I get it or how can I setting to show the names?
Thank you for reading!

**Comment by plusmouse** [comment]
Right click the column header and tick sellers in the drop down that appears

**Comment by LasombraK** [comment]
> Right click the column header and tick sellers in the drop down that appears

get it!
Thank you very much!
