### ISSUE TITLE
LUA error when buying stacks of things

### ISSUE THREAD

**Issue by flound1129** [Auctionator/Auctionator#1151]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug
When I shift-click to buy more than the default number of an item from a vendor, I sometimes get this lua error

```
Message: [ADDON_ACTION_FORBIDDEN] AddOn 'Auctionator' tried to call the protected function 'RunBinding()'.
Time: Sat Apr 30 13:06:42 2022
Count: 1
Stack: [ADDON_ACTION_FORBIDDEN] AddOn 'Auctionator' tried to call the protected function 'RunBinding()'.
[string "=[C]"]: in function `Hide'
[string "@Interface\FrameXML\StackSplitFrame.lua"]:235: in function `StackSplitOkayButton_OnClick'
[string "@Interface\FrameXML\StackSplitFrame.lua"]:165: in function <Interface\FrameXML\StackSplitFrame.lua:141>

Locals: <none>
```

_Please include a brief description of the bug, including what you were doing, and when it occurred._

## Steps to Reproduce
Go to a vendor
Shift-click on an item
Enter a number of stacks/items to purchase
Hit enter

## Loaded Addons
Auctionator
BankItems
CursorTrail
DBM-Brawlers
DBM-CastleNathria
DBM-Core
DBM-DMF
DBM-GUI
DBM-Party-Shadowlands
DBM-SanctumOfDomination
DBM-Sepulcher
DBM-Shadowlands
DBM-StatusBarTimers
DBM-VPVEM
DBM-WorldEvents
Decursive
Details
Details_DataStorage
Details_EncounterDetails
Details_RaidCheck
Details_Streamer
Details_TinyThreat
Details_Vanguard
ExRT
GarrisonMissionManager
HandyNotes
HandyNotes_Shadowlands
Journalator
Journalator.old
MRT
Minimap_Alert
PersonalLootHelper
PetTracker
PetTracker_Battle
PetTracker_Config
PetTracker_Journal
RareScanner
Rarity
Rarity_Options
Rematch
Simulationcraft
TomTom
VenturePlan
VenturePlanSoDMissions
WeakAuras
WeakAurasArchive
WeakAurasModelPaths
WeakAurasOptions
WeakAurasTemplates

## Back Trace (LUA Error Output)

see above.  Thanks for all of your hard work on this addon!

**Comment by plusmouse** [comment]
Can you run `/console taintLog 1` when you start playing and then trigger the error again. Then upload your `C:\Program Files (x86)\World of Warcraft\_retail_\Logs\taint.log` file to here.

Just using Shift-Click and Enter isn't enough to trigger the error - it doesn't appear on my machine.

Oddly you seem to have Journalator.old loaded, is there a reason for that (it might be containing code that causes this bug)?

**Comment by flound1129** [comment]
got rid of journalator.old, but this has been happening to me for a long time.

```
$ cat taint.log
4/30 22:41:46.164  Interface\FrameXML\StackSplitFrame.lua:194
4/30 22:41:46.164  An action was blocked because of taint from Auctionator - RunBinding()
4/30 22:41:46.164      Interface\FrameXML\StackSplitFrame.lua:196
4/30 22:41:46.164      StackSplitFrame:Hide()
4/30 22:41:46.164      Interface\FrameXML\StackSplitFrame.lua:235 StackSplitOkayButton_OnClick()
4/30 22:41:46.164      Interface\FrameXML\StackSplitFrame.lua:165

```

**Comment by plusmouse** [comment]
I've got it to trigger on my computer.

Steps to reproduce:
1. Shift-Click to select a different stack/item count at a vendor.
2. Hold down "c" and press [Enter], continuing to hold down "c" (or use a keyboard shortcut bound to something of your choosing).

This version of Auctionator should have the bug fixed. Can you check too?
[Auctionator-9.2.14-1-g9468ada.zip](https://github.com/Auctionator/Auctionator/files/8598456/Auctionator-9.2.14-1-g9468ada.zip)

**Comment by flound1129** [comment]
Looks like it's fixed!  Thank you!
