### ISSUE TITLE
Favorites saying None Available

### ISSUE THREAD

**Issue by incith** [Auctionator/Auctionator#1153]
**Is your feature request related to a problem? Please describe.**
Only first favorite is showing as available

**Describe the solution you'd like**
All my favorites are currently available on the AH, it just says "None Available" beside all but 1 tho

![wow-ah-err](https://user-images.githubusercontent.com/5614781/166151572-8e20b152-fdda-4fef-8366-39e3ef14ea1c.png)

**Comment by plusmouse** [comment]
That's a bug with the Blizzard auction house. You need to favourite the items again to get it to work.

**Comment by incith** [comment]
Thanks!
