### ISSUE TITLE
Shift+click trying to split the stack

### ISSUE THREAD

**Issue by Mard35** [Auctionator/Auctionator#1155]
After last update when i'm searching on auction via Shift+click on item in my bags with opened auction window it's trying to split the stack of that item. Why did you do that? I have to to cancel splitting every new search!

**Comment by plusmouse** [comment]
A fix will be available on Curseforge in a few minute
[Auctionator-9.2.15-2-g458a55f-bcc.zip](https://github.com/Auctionator/Auctionator/files/8618765/Auctionator-9.2.15-2-g458a55f-bcc.zip)
s
