### ISSUE TITLE
TBC auction scanning bug

### ISSUE THREAD

**Issue by xuhua0508** [Auctionator/Auctionator#1156]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

TBC has been stuck in the words "scan page 2" since it is used in the latest version of sales. See the figure for details

## Loaded Addons

List of plug-ins that were running when the error occurred_ See Figure

## Back Trace (LUA Error Output)

！ Buggrabber and bugsack plug-ins do not report errors

![Snipaste_2022-05-05_11-42-46](https://user-images.githubusercontent.com/50047726/166861129-1b5c999f-7553-4bc7-b003-c04fd2d66998.png)
![Snipaste_2022-05-05_11-46-00](https://user-images.githubusercontent.com/50047726/166861150-54a733a5-20a4-4d0c-8efe-c4833a00c7db.png)
![Snipaste_2022-05-05_11-44-58](https://user-images.githubusercontent.com/50047726/166861152-94baa307-690f-4c41-b9e9-3adbb8cadc4b.png)
![Snipaste_2022-05-05_11-44-45](https://user-images.githubusercontent.com/50047726/166861154-83813d1a-39d2-4347-ab2c-0ae6e2538d82.png)

**Comment by xuhua0508** [comment]
Suggestion: when scanning the auction items on the shelf, can you add a prompt for scanning the remaining time or scanning the overall progress bar?

**Comment by plusmouse** [comment]
Can you try scanning for an item with just Auctionator enabled to see if the issue is still happening?

Running a scan on my computer gets past page 2:
![image](https://user-images.githubusercontent.com/60280559/166976380-e1bf2406-226f-42b9-80f2-158806350899.png)

**Comment by xuhua0508** [comment]
> 您可以尝试在启用 Auctionator 的情况下扫描一个项目，看看问题是否仍然存在？
> 
> 在我的计算机上运行扫描会超过第 2 页： ![图片](https://user-images.githubusercontent.com/60280559/166976380-e1bf2406-226f-42b9-80f2-158806350899.png)

解决方式是关掉拍卖行，重新打开几次才正常。

**Comment by plusmouse** [comment]
Do you see an "Internal Auction Error" red message text appear at the top centre of your screen when the search stops working?

**Comment by xuhua0508** [comment]
There are no errors in the game when this issue occurs, and there is no internal auction error as you said. &nbsp;This problem is so frequent that the auction house can only be restored to its original state by reopening it. &nbsp;In addition, I found that the first time I opened the auction house purchase list and entered the item name to search, it would also get stuck. &nbsp;in the words "Scan page 2".

发自我的iPhone


------------------ Original ------------------
From: plusmouse ***@***.***&gt;
Date: Sat,May 7,2022 0:18 AM
To: Auctionator/Auctionator ***@***.***&gt;
Cc: xuhua0508 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [Auctionator/Auctionator] TBC auction scanning bug (Issue #1156)





 
Do you see an "Internal Auction Error" red message text appear at the top centre of your screen when the search stops working?

**Comment by xuhua0508** [comment]
There is a bug in the bugsack:

1x ...ddOns\Auctionator\Source\Utilities\DBKeyFromLink.lua:38: attempt to concatenate upvalue 'basicKey' (a nil value) [string ***@***.***\Source\Utilities\DBKeyFromLink.lua"]:38: in function <...ddOns\Auctionator\Source\Utilities\DBKeyFromLink.lua:34&gt; [string "=[C]"]: in function `xpcall' [string ***@***.***\ObjectAPI\Item.lua"]:298: in function `FireCallbacks' [string ***@***.***\ObjectAPI\Item.lua"]:260: in function <FrameXML\ObjectAPI\Item.lua:256&gt; [string "=[C]"]: ? [string "=[C]"]: in function `RequestLoadItemDataByID' [string ***@***.***\ObjectAPI\Item.lua"]:274: in function `AddCallback' [string ***@***.***\ObjectAPI\Item.lua"]:238: in function `ContinueOnItemLoad' [string ***@***.***\Source\Utilities\DBKeyFromLink.lua"]:34: in function `DBKeyFromLink' [string ***@***.***\Source\Tooltips\Main.lua"]:15: in function `ShowTipWithPricing' [string ***@***.***\Source\Tooltips\Hooks.lua"]:286: in function <Auctionator\Source\Tooltips\Hooks.lua:285&gt; [string "=[C]"]: ? [string ***@***.***\LibTSM\Service\ItemTooltipClasses\Wrapper.lua"]:107: in function <...Master\LibTSM\Service\ItemTooltipClasses\Wrapper.lua:105&gt; [string "=[C]"]: ? [string "=[C]"]: in function `SetHyperlink' [string ***@***.***\module\misc.lua"]:157: in function <alaChat\module\misc.lua:153&gt;




发自我的iPhone


------------------ Original ------------------
From: plusmouse ***@***.***&gt;
Date: Sat,May 7,2022 0:18 AM
To: Auctionator/Auctionator ***@***.***&gt;
Cc: xuhua0508 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [Auctionator/Auctionator] TBC auction scanning bug (Issue #1156)





 
Do you see an "Internal Auction Error" red message text appear at the top centre of your screen when the search stops working?

**Comment by plusmouse** [comment]
That looks like a quirk in an item link filter affecting Auctionator.

Can you please try the scan with just Auctionator enabled and report whether it works?

**Comment by plusmouse** [comment]
OK. This particular error is unrelated to the scan failing, and is caused by another addon putting modified item links in the chat.

**Comment by plusmouse** [comment]
The error in [this comment](https://github.com/Auctionator/Auctionator/issues/1156#issuecomment-1121147352) has been fixed.


The latest alpha (and preview release 9.2.25) has an enhancement to the search functionality that will get the lowest prices much sooner, and hopefully this will resolve the issue of it getting stuck on later pages, as those pages will now be skipped.
![Load All Button](https://user-images.githubusercontent.com/60280559/182871386-93a1b0a3-0f3c-47bf-ab0e-8005569850dc.gif)
