### ISSUE TITLE
Font Improvements

### ISSUE THREAD

**Issue by btnmasher** [Auctionator/Auctionator#1160]
**Is your feature request related to a problem? Please describe.**
I recently updated Auctionator, and am faced with this new fangled UI. It's okay, not my favorite (I really liked the simplicity of the old version), but what is most upsetting to my enjoyment of the use of this tool is the complete wild west of font selections within the UI.

**Describe the solution you'd like**
I would like all of the fonts of Auctionator to honor the interface default font, or be individually configurable.

**Describe alternatives you've considered**
Reinstalling the older version of Auctionator and never updating again.

**Additional context**
![uoLEkoA0WW](https://user-images.githubusercontent.com/67168637/169632819-ba15d8da-337b-49ef-a8ae-917e556a799c.png)

**Comment by plusmouse** [comment]
I've altered the fonts, it should appear OK now. Can you confirm this before I push this to a normal release?

[Auctionator-9.1.19-3-g3a1d79d-bcc.zip](https://github.com/Auctionator/Auctionator/files/9003468/Auctionator-9.1.19-3-g3a1d79d-bcc.zip)

**Comment by btnmasher** [comment]
Looking great!
