### ISSUE TITLE
Back Button

### ISSUE THREAD

**Issue by tflo** [Auctionator/Auctionator#1165]
We got keybinds like these:

![WoWScrnShot_060122_170709 copy](https://user-images.githubusercontent.com/1410282/171438361-e0965f51-0fbd-41ff-9ed8-0a0dcec87b71.jpg)

What happens is that often I catch myself having advanced too fast. For example, skipped an auction, then, a fraction of a second later, decided to post it.

In this situation, a Back key would be really handy: Just going back to the previously selected item. In my setup (see screenshot, it would be ‘S’ obviously.)

Thanks for considering.

– Tom

**Comment by plusmouse** [comment]
Adding in going back would complicate the code for the Selling tab for a minor change. So not going to add this.

**Comment by plusmouse** [comment]
Is this still something you want?
![image](https://github.com/Auctionator/Auctionator/assets/60280559/a241632c-8cb1-4e50-9314-0e2611a98b29)

I've made a version that works:
[Auctionator-10.1.8-4-g53c2dba.zip](https://github.com/Auctionator/Auctionator/files/11821950/Auctionator-10.1.8-4-g53c2dba.zip)

**Comment by tflo** [comment]
> Is this still something you want?

Sure :)

Thank you!

**Comment by plusmouse** [comment]
Great. It will be in the next alpha release or you can use the version above

**Comment by tflo** [comment]
Just tried 10.1.8-4-g53c2dba. Works great, even with favorites! Thank you again!

**Comment by tflo** [comment]
Getting this error with 10.1.8-10-g83587bc:

<details>
<summary><code>1x ...tor/Source_Mainline/Tabs/Selling/Mixins/SaleItem.lua:106: bad argument #1 to 'LockItem' (Usage: C_Item.LockItem(itemLocation))</code></summary>

```text
1x ...tor/Source_Mainline/Tabs/Selling/Mixins/SaleItem.lua:106: bad argument #1 to 'LockItem' (Usage: C_Item.LockItem(itemLocation))
[string "=[C]"]: in function `LockItem'
[string "@Auctionator/Source_Mainline/Tabs/Selling/Mixins/SaleItem.lua"]:106: in function `LockItem'
[string "@Auctionator/Source_Mainline/Tabs/Selling/Mixins/SaleItem.lua"]:173: in function `ReceiveEvent'
[string "@Auctionator/Source/Utilities/EventBusMixin.lua"]:77: in function `Fire'
[string "@Auctionator/Source_Mainline/Tabs/Selling/Mixins/SaleItem.lua"]:720: in function `PrevItem'
[string "*SaleItem.xml:119_OnClick"]:1: in function <[string "*SaleItem.xml:119_OnClick"]:1>

Locals:
(*temporary) = <table> {
 Clear = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:29
 IsEquipmentSlot = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:56
 IsEqualToBagAndSlot = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:72
 SetBagAndSlot = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:35
 IsBagAndSlot = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:60
 SetEquipmentSlot = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:46
 slotIndex = 14
 HasAnyLocation = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:64
 bagID = 0
 GetEquipmentSlot = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:52
 IsEqualToEquipmentSlot = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:80
 GetBagAndSlot = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:42
 IsValid = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:68
 IsEqualTo = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:88
}

```
</details>

This gets thrown when I use the back button _after posting an item_. The item is highlighted in the selector but the data isn't filled into the main fields (item count is >= 1, no favorite item). This remains like that until I mouse-click any item in the selector, then it gets "repaired".

Does not happen when I navigate through the items back and forth without posting.

**Comment by plusmouse** [comment]
Fixed in the latest alpha (available from Curseforge or Wago shortly)
[Auctionator-10.1.8-11-g5a2c3a4.zip](https://github.com/Auctionator/Auctionator/files/11859160/Auctionator-10.1.8-11-g5a2c3a4.zip)
