### ISSUE TITLE
Full Scan not working on AH (Alliance - Benediction)

### ISSUE THREAD

**Issue by lumiecat** [Auctionator/Auctionator#1166]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

Full Scan is not working, stops at 10%. Also takes a long time when selling items 

## Steps to Reproduce

Go to AH and start a Full Scan 

## Loaded Addons

AtlasLootClassic, Auctionator, Bagnon, DBM, Details!, GatherMate, Guidelime, Pawn, Questie, Raid Rebuff, RareScanner

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by plusmouse** [comment]
That is usually a result of being on a busy realm.

Stopping at 10% means that despite Auctionator starting the scan, no results were sent back from the server

**Comment by jake-c** [comment]
so what's the fix? Don't be on a busy realm?

**Comment by plusmouse** [comment]
There isn't a fix unfortunately - its on Blizzard's end.

**Comment by plusmouse** [comment]
Selling items should be faster in the latest alpha. As the full scan issue isn't fixable closing the issue (try doing it with just Auctionator enabled, that should work though).
![Load All Button](https://user-images.githubusercontent.com/60280559/182868990-ee3493dd-9f76-402f-9d14-53e919f5eea3.gif)

**Comment by Otsoko** [comment]
> There isn't a fix unfortunately - its on Blizzard's end.

If no results were sent back from the server, meaning that a full scan was not performed, don't apply the 15 min cooldown so we can hit the button again.

**Comment by plusmouse** [comment]
On classic Blizzard supplies an interface that specifies whether a full scan is possible. If a scan is possible before the 15 minute timer elapses the button will work to scan (it ignores the timer in that case). Restarting the WoW client resets the scan status on classic.
