### ISSUE TITLE
Sell Tab Causes Game to Crash Everytime

### ISSUE THREAD

**Issue by Tehdanzig** [Auctionator/Auctionator#1167]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug
Whenever I click on the sell tab and then select the item "lucy" a battle pet  i wish to sell my game hard crashes.
_Please include a brief description of the bug, including what you were doing, and when it occurred._
Whenever I click on the sell tab and then select the item "lucy" a battle pet  i wish to sell my game hard crashes.
## Steps to Reproduce

_Include the steps I would need to follow to reproduce the bug._
So i was able to replicate this crash 5 times. Then i decided to try it with a different item. As soon as i did it with another item it no longer is crashing. So I am not sure how to get it to happen for you.
## Loaded Addons
Big wigs
zperl
DBM
Healbot
pawn
platter
maze helper
Mythic io raider
weak auras 
tom tom
_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._
Neither of the bug addons got anything because the game just crashed when i reloaded it showed no bugs present.

**Comment by plusmouse** [comment]
I've purchased a Lucy pet, and replicated the crash - it doesn't even require the AH to be open. Just trying to pick up the Lucy pet with the cursor triggers it (right-clicking doesn't)

However, this is not an Auctionator bug as it still happens when Auctionator is disabled, so this is not something I can fix.

**Comment by plusmouse** [comment]
You can still post the item, right-clicking the item when the AH is open will work to put it up for selling, or using the integrated bag view in the Selling tab will work too.
