### ISSUE TITLE
Fallback selling price based on vendor sell price (5x for weapons and armor, 4x for reagents)

### ISSUE THREAD

**Issue by JackTrapper** [Auctionator/Auctionator#1168]
Many times the random green, randomly assigned stats, will have no presence (or history) in the auction house.

It's time's like that when i would use the **Vendor Sell Price** as a guide to how valuable an item is (or should be).

So i finally tested it. I found as many different examples of things you can buy from a vendor:

- reagents
- weapons
- armor
- plate armor
- cloth armor
- gray armor
- white armor
- gray armor

And there are consistent ratios between the **vendor sell price** and what it would cost to buy from a vendor:

**Buying Markups**

| Item type | Markup |
|-------------|------------|
| Weapons | 5x |
| Armor | 5x |
| Reagents | 4x |

It would be nice to have a feature where these *"baseline"* prices serve as a good fallback in case there are no other auctions to compare against.

Also, in classic, i don't **want** to gouge people. We're all in it together. I'll sell it to you for a fair price; not the price the market will bear.

So now every time i auction i:

- put the item up
- hover over to look at the vendor sell price
- type that into Windows Calculator, multiply by 5
- type that into the sell amount

Lua would be very good at calculating `x * 5`

------------

> And, of course, this is purely a suggestion. Great addon, love it, awesome forever, you make people's lives better. But i don't want it to be a slog; another *"oh god what do these people want just leave me alone!"*

**Comment by plusmouse** [comment]
Adding in multiple options would be a bit much, but I'm happy to add in just one vendor price multiplier - retail Auctionator has something similar for gear.
![image](https://user-images.githubusercontent.com/60280559/175008440-a15a6d04-7d12-4e02-99ca-434683eaaf24.png)

This would be optional, to avoid accidental posting (for when selling tmog at higher prices and to avoid feeling ripped off if posted too low and sniped).

The retail version only uses the vendor price multiplier when there's no price, and this would be the same, just covering more items beyond gear.

**Comment by plusmouse** [comment]
No response. Closing.
