### ISSUE TITLE
Incorrect Disenchanting Results

### ISSUE THREAD

**Issue by IHexYou** [Auctionator/Auctionator#1169]
Hi. 
When i mouseover the item i want to disenchant it shows the possible disenchant for different expansions instead of the current one. 
Like yesterday, i went to disenchant an item for shadowlands my priest made and it showed it would possibly result is Ethereal shard instead of the shadowlands result.

**Comment by plusmouse** [comment]
Auctionator doesn't show disenchant results, so this is likely another addon that has the results set wrong:
![image](https://user-images.githubusercontent.com/60280559/175003441-4f09c3a8-5f5e-4189-bfdf-cafa2aad9d30.png)

**Comment by IHexYou** [comment]
Ah, okay. Thank you :D
