### ISSUE TITLE
Undercut function not undercutting

### ISSUE THREAD

**Issue by Gandramir** [Auctionator/Auctionator#1170]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

_Please include a brief description of the bug, including what you were doing, and when it occurred._

**_It occurs every time an item is in the selling menu on the AH window.  The undercut percentage is set to 2% on my Auctionator settings, but the calculation is as if it's not finding the percent difference at all between the lowest posted price and the percent I wish to undercut._** 

## Steps to Reproduce

_Include the steps I would need to follow to reproduce the bug._

**_Select Item from Selling menu or from bag to the Sell menu with undercut value set and see that there is no undercutting of the price._**

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._

**_I cannot find a written bug as if the calculations were wrong and something was in error, but I have screenshots provided that explain it to a tee._**

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

![Screenshot_4](https://user-images.githubusercontent.com/47938447/176836949-947e56d9-e996-44ee-9ea0-064d6e983f34.png)
![Screenshot_3](https://user-images.githubusercontent.com/47938447/176836952-48bcf1ef-0d0c-4118-aac8-933ff44ef992.png)

**Comment by plusmouse** [comment]
Gear has a separate undercut setting, go to "Selling: Gear/Pets" to set the undercut

**Comment by Gandramir** [comment]
> Gear has a separate undercut setting, go to "Selling: Gear/Pets" to set the undercut

Ah ok awesome, thank you for the heads up, I feel dumb now XD.
