### ISSUE TITLE
Lua Error during login

### ISSUE THREAD

**Issue by kayaaydinalpay** [Auctionator/Auctionator#1171]
Im getting the following Lua error during login. But it doesnt seem to be affecting any of the Auctionator's operations. GetAll function, price history etc all seems to be working perfectly. 
On a second glance, it looks like TSM trying to reach Auctionator's database but fails. I use Auctionator prices for TSM's crafting costs and although it mostly works fine; on some items some mid tier crafted items have no craft cost value. I guess this is the reason why

Date: 2022-07-01 14:47:50
ID: 1
Error occured in: Global
Count: 1
Message: ...AddOns\Auctionator\Source\API\v1\GetAuctionPrice.lua line 32:
   attempt to index field 'Database' (a nil value)
Debug:
   [string "=[C]"]: ?
   [string "@Auctionator\Source\API\v1\GetAuctionPrice.lua"]:32:
      ...AddOns\Auctionator\Source\API\v1\GetAuctionPrice.lua:14
   [string "=(tail call)"]: ?
   [string "@TradeSkillMaster\LibTSM\Service\CustomPrice.lua"]:379: GetItemPrice()
   [string "@TradeSkillMaster\LibTSM\Service\CustomPrice.lua"]:641: _priceHelper()
   [string "TSMCustomPrice: min(atrvalue, crafting, vendorbuy)"]:17: func()
   [string "@TradeSkillMaster\LibTSM\Service\CustomPrice.lua"]:669: proxy()
   [string "@TradeSkillMaster\LibTSM\Service\CustomPrice.lua"]:345: GetValue()
   [string "@TradeSkillMaster\Core\Service\Crafting\Cost.lua"]:59: GetMatCost()
   [string "@TradeSkillMaster\Core\Service\Crafting\Cost.lua"]:283:
      ...dOns\TradeSkillMaster\Core\Service\Crafting\Cost.lua:236
   [string "=(tail call)"]: ?
   [string "@TradeSkillMaster\Core\Service\Crafting\Cost.lua"]:94: GetCostsByCraftString()
   [string "@TradeSkillMaster\Core\Service\Crafting\Core.lua"]:280: GetMostProfitableCraftStringByItem()
   [string "@TradeSkillMaster\Core\Service\Crafting\Gathering.lua"]:265: UpdateDB()
   [string "@TradeSkillMaster\Core\Service\Crafting\Gathering.lua"]:196: OnQueuedCraftsUpdated()
   [string "@TradeSkillMaster\Core\Service\Crafting\Gathering.lua"]:55: OnEnable()
   [string "@TradeSkillMaster\Core\Lib\Addon.lua"]:64: DoEnable()
   [string "@TradeSkillMaster\Core\Lib\Addon.lua"]:123:
      TradeSkillMaster\Core\Lib\Addon.lua:111

[aucluaerror.txt](https://github.com/Auctionator/Auctionator/files/9028624/aucluaerror.txt)

**Comment by plusmouse** [comment]
Can you try this build and report if it has the error or not?
[Auctionator-9.2.20-1-g70ff05c-bcc.zip](https://github.com/Auctionator/Auctionator/files/9028856/Auctionator-9.2.20-1-g70ff05c-bcc.zip)

**Comment by kayaaydinalpay** [comment]
yep, this build seems to be fine. No more lua errors during login and all my crafts in TSM are rightly calculated with Auctionator prices
