### ISSUE TITLE
[Feature request] Ignore selected items while undercut cancelling.

### ISSUE THREAD

**Issue by zeenk** [Auctionator/Auctionator#1172]
**Is your feature request related to a problem? Please describe.**
Not really a problem, just more of a QoL feature to save some deposit gold while posting and if you see someone has listed same item for a big discount and you don't want to match that low price, so when you undercut scan you don't keep cancel it while cancelling other items with the cancel button.

**Describe the solution you'd like**
Adding some sort of setting to "ignore and skip" this item while using the cancel undercut button until the auction timer is over.

**Additional context**
Having a setting here when you are posting the item and show some sort of indicator in the cancelling tab that shows that the item is being ignored and skipped while undercut scanning and using the cancel button so you don't have to manually cancel all the undercuts and can just spam the button instead for the other items.

(This is just an example, was thinking this could be a nice feature for items with higher deposit cost or if you just don't want to match a big undercut but want to leave the auction up for normal price in case the low one sells within the 48hrs.)
![2022-07-02_00-53-00](https://user-images.githubusercontent.com/68170439/176975826-0cfa49ea-bd48-418a-bebb-594011e9d02f.png)

![2022-07-02_01-56-22](https://user-images.githubusercontent.com/68170439/176978672-197cb047-8317-4fff-ad1a-d8b00ddd3ee7.png)

**Comment by plusmouse** [comment]
This won't be added.
1. Adding more options to an already complex tab will distract from posting.
2. At the moment the selling and cancelling tabs don't have much state to keep track of (just the current item), trying to keep track of whether this is the auction you wanted skipped would add an entanglement between the tabs' code.
