### ISSUE TITLE
TBC: Ethereum Prison Key bug (probably other keyring items too)

### ISSUE THREAD

**Issue by anzz1** [Auctionator/Auctionator#1174]
## Brief Description of Bug

LUA error for GetInventoryItemDurability and cannot post Ethereum Prison key on Selling tab.
Error happens when trying to drag the item from keyring, if drag to normal bag first and then post, it works fine.
As keyring is a "special" bag, it's very likely that GetInventoryItemDurability cannot be called on items in your keyring bag.

Client version 2.5.4.44400 (TBC-Classic)

## Steps to Reproduce

Try to put [Ethereum Prison Key](https://tbc.wowhead.com/item=29460/ethereum-prison-key) (itemID 29460) from Keyring to the sell slot in "Selling" tab. Normal bags works fine, bug happens only on keyring.

![image](https://user-images.githubusercontent.com/13628128/179316371-3e097897-48fb-4750-b747-3af42a021b4b.png)

## Back Trace (LUA Error Output)
```
Message: ...or\Source_Classic\Utilities\ItemInfoFromLocation.lua:16: Usage: GetInventoryItemDurability(slot)
Time: Sat Jul 16 00:51:19 2022
Count: 1
Stack: ...or\Source_Classic\Utilities\ItemInfoFromLocation.lua:16: Usage: GetInventoryItemDurability(slot)
[string "=[C]"]: in function `GetInventoryItemDurability'
[string "@Interface\AddOns\Auctionator\Source_Classic\Utilities\ItemInfoFromLocation.lua"]:16: in function `ItemInfoFromLocation'
[string "@Interface\AddOns\Auctionator\Source_Classic\Tabs\Selling\Mixins\BagItemSelected.lua"]:18: in function `ProcessCursor'
[string "@Interface\AddOns\Auctionator\Source_Classic\Tabs\Selling\Mixins\BagItemSelected.lua"]:4: in function <...urce_Classic\Tabs\Selling\Mixins\BagItemSelected.lua:3>
```

**Comment by plusmouse** [comment]
This appears to be the result of a Blizzard bug. I've tested with an Ethereum Prison Key, and it won't give the item link (and hence the details Auctionator uses for selling and to tell it not to use the durability check), when the item is on the cursor.

However it does work if I add the key to the bag view in Auctionator.

Try using this alpha [Auctionator-9.2.21-2-ga25a648-bcc.zip](https://github.com/Auctionator/Auctionator/files/9125385/Auctionator-9.2.21-2-ga25a648-bcc.zip) - it will add the key to the bag view letting you put it up for the sale

![image](https://user-images.githubusercontent.com/60280559/179346151-0fa16dff-dbed-4368-8fe9-e6f413cb9b0a.png)

**Comment by plusmouse** [comment]
Update: I've added a fix for picking up with your cursor and placing it in your bag in the latest alpha
[Auctionator-9.2.21-4-g080983e-bcc.zip](https://github.com/Auctionator/Auctionator/files/9125634/Auctionator-9.2.21-4-g080983e-bcc.zip)
Can you test it?

**Comment by anzz1** [comment]
That seems to have corrected it ! Tested with Relic Coffer Key, no more bug.
