### ISSUE TITLE
Another lua error with latest alpha patch

### ISSUE THREAD

**Issue by zeenk** [Auctionator/Auctionator#1176]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

I clicked on my Veiled augment runes in my bag to post on AH and got the lua error(s)

## Steps to Reproduce

Haven't found a way to reproduce the bug, it worked like it's supposed to second time I tried it.

## Back Trace (LUA Error Output)
Message: ...tor\Source_Mainline\Tabs\Selling\Mixins\SaleItem.lua:12: attempt to perform arithmetic on local 'normalizedPrice' (a nil value)
Time: Mon Jul 25 06:07:28 2022
Count: 4
Stack: ...tor\Source_Mainline\Tabs\Selling\Mixins\SaleItem.lua:12: attempt to perform arithmetic on local 'normalizedPrice' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\Auctionator\Source_Mainline\Tabs\Selling\Mixins\SaleItem.lua"]:12: in function <...tor\Source_Mainline\Tabs\Selling\Mixins\SaleItem.lua:8>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Auctionator\Source_Mainline\Tabs\Selling\Mixins\SaleItem.lua"]:132: in function <...tor\Source_Mainline\Tabs\Selling\Mixins\SaleItem.lua:106>

Locals: 

Message: ...tor\Source_Mainline\Tabs\Selling\Mixins\SaleItem.lua:12: attempt to perform arithmetic on local 'normalizedPrice' (a nil value)
Time: Mon Jul 25 06:07:28 2022
Count: 1
Stack: ...tor\Source_Mainline\Tabs\Selling\Mixins\SaleItem.lua:12: attempt to perform arithmetic on local 'normalizedPrice' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\Auctionator\Source_Mainline\Tabs\Selling\Mixins\SaleItem.lua"]:12: in function <...tor\Source_Mainline\Tabs\Selling\Mixins\SaleItem.lua:8>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Auctionator\Source_Mainline\Tabs\Selling\Mixins\SaleItem.lua"]:521: in function `GetPostButtonState'
[string "@Interface\AddOns\Auctionator\Source_Mainline\Tabs\Selling\Mixins\SaleItem.lua"]:561: in function `UpdatePostButtonState'
[string "@Interface\AddOns\Auctionator\Source_Mainline\Tabs\Selling\Mixins\SaleItem.lua"]:173: in function `ReceiveEvent'
[string "@Interface\AddOns\Auctionator\Source\Utilities\EventBusMixin.lua"]:77: in function `Fire'
[string "@Interface\AddOns\Auctionator\Source_Mainline\AH\Mixins\Throttling.lua"]:42: in function <...Auctionator\Source_Mainline\AH\Mixins\Throttling.lua:24>

Locals: 

Also noticed that the left side panel with all the items is missing (re-open ah again fixed it back to normal)🤔 
![2022-07-25_06-09-47](https://user-images.githubusercontent.com/68170439/180697661-81a4077a-2960-402b-87a8-c5fb4ebe3ba8.png)

**Comment by plusmouse** [comment]
Thanks for the report. Fixed in the latest alpha (available shortly from Curseforge/Wago)
