### ISSUE TITLE
Undercut scan should perhaps use full scan

### ISSUE THREAD

**Issue by archfrog** [Auctionator/Auctionator#1177]
**Is your feature request related to a problem? Please describe.**
An undercut scan takes 15 to 20 seconds, a full AH scan takes two seconds.

**Describe the solution you'd like**
I'd like the undercut scan to either reuse a recent full scan or make a full scan prior to doing the undercut examination.

**Describe alternatives you've considered**
I am on a low population server (about 4K AH items), not sure how my suggestion would work out on a high population server with hundreds of thousands of AH listings.  But I seem to recall that full AH scans are generally very fast.

**Additional context**
None.

**Comment by plusmouse** [comment]
Set up a version where when you do a full scan it will use those results to update the Cancelling tab as to which items have been undercut. This way the original undercut scan is still available, and you get the fast results from your full scan.

[Auctionator-9.2.26-4-g40a2f4c.zip](https://github.com/Auctionator/Auctionator/files/9289351/Auctionator-9.2.26-4-g40a2f4c.zip)
![Auctionator full scan for cancel scan](https://user-images.githubusercontent.com/60280559/183620191-ed82b618-1c25-496a-815d-4441c7d812c0.gif)

**Comment by plusmouse** [comment]
Can you let me know how it goes?

**Comment by archfrog** [comment]
Yes, I'm downloading it now and will test it tonight.  Then I'll provide feedback and status.  Thanks a lot for this change!

**Comment by archfrog** [comment]
I've tried it and it seems to work very well :-)  I'll be keeping your Github version until the time it is officially released.

Thanks again!

**Comment by plusmouse** [comment]
After assessing the feature it sufficiently complicated to be awkward to maintain, so its not going to get added to the main build of Auctionator.
