### ISSUE TITLE
"Load more results" feature

### ISSUE THREAD

**Issue by FuriousZahn** [Auctionator/Auctionator#1179]
Hi,
This new "Load more results" feature is making me considering other addon alternatives. 
So if I search Pyretone it ends up with only 2 results: Pyrestone and Potent Pyrestone. Need to press load more to get the rest of the 6 results missing. 
If I go into Pyrestone, then I'm happy with the results as there are plenty, but in the tier before it's quite annoying. 

Missed already some items in the past because sometimes I forget the button and just think it's not available in the Auction House.

**Comment by plusmouse** [comment]
The feature was added because loading all the pages get take a while on a busy realm.

Would adding an option to disable the "Load more results" button and always load everything help?

**Comment by FuriousZahn** [comment]
My server has over 8k people and never felt the need for the "Load more results", to be honest. Maybe on the mega servers it's necessary.
If not possible to customise even further the feature, then an option to toggle it would definitely be very welcomed.

**Comment by plusmouse** [comment]
This option is available in the latest alpha, and will go out with the next normal release
[Auctionator-9.2.25-2-gf33f9e6-bcc.zip](https://github.com/Auctionator/Auctionator/files/9275553/Auctionator-9.2.25-2-gf33f9e6-bcc.zip)
[Auctionator-9.2.25-2-gf33f9e6-classic.zip](https://github.com/Auctionator/Auctionator/files/9275554/Auctionator-9.2.25-2-gf33f9e6-classic.zip)
![image](https://user-images.githubusercontent.com/60280559/183261319-84ee087a-e64b-42db-81a5-acadf59276c3.png)

**Comment by FuriousZahn** [comment]
Wow! This was much faster than I anticipated. Thanks a lot!
