### ISSUE TITLE
Ability to disable the trunacted search results.

### ISSUE THREAD

**Issue by btnmasher** [Auctionator/Auctionator#1180]
**Is your feature request related to a problem? Please describe.**

The change to truncating the search results and forcing one to click the load more results button is unwelcome without the ability to disable this functionality.

**Describe the solution you'd like**

I would like for an option to toggle disable the partial scan mode. Let us decide if things take too long, not you.

**Describe alternatives you've considered**

I have considered just accepting the Repeated Stress Injuries from having to click twice in two different parts of the screen every time I want to search for something. And being confused every time I search something and wondering how there's so few of them before realizing that this thing was added unbeknownst to me and I'm not losing my mind.

**Additional context**

![gTjM7YFNLT](https://user-images.githubusercontent.com/67168637/183312728-e16aea3a-3c78-4d83-9e97-8a007dcfb290.png)

**Comment by plusmouse** [comment]
Added an option to disable them. While Curseforge is processing the new release you can download it here:
[Auctionator-9.2.26-bcc.zip](https://github.com/Auctionator/Auctionator/files/9277980/Auctionator-9.2.26-bcc.zip)
![image](https://user-images.githubusercontent.com/60280559/183320723-5557240b-2f28-45b4-8ef0-d5ac1b6108a4.png)
