### ISSUE TITLE
Unable to update addon from Github using cursebreaker or similar tool

### ISSUE THREAD

**Issue by rgk85** [Auctionator/Auctionator#1182]
I'm using [CurseBreaker](https://github.com/AcidWeb/CurseBreaker) to manage all my addons, up until recently I have not had any issues updating Auctionator directly from GitHub, but now I'm getting errors.

![Screenshot 2022-08-15 090345](https://user-images.githubusercontent.com/40987871/184590931-1a19650b-365e-49b1-b69b-ed645d7e7ec2.png)

Did you remove the posibility of updating your addon using any other tool than CurseForge?

**Comment by plusmouse** [comment]
It isn't only Curseforge. Auctionator is available from both [Curseforge](https://www.curseforge.com/wow/addons/auctionator) and [Wago](https://addons.wago.io/addons/auctionator). Wago has integrations with WoWUp and Cursebreaker.

**Comment by rgk85** [comment]
That's a shame, limiting the addon to 2 addon client only :/
