### ISSUE TITLE
Full Scan doesn't work after new update

### ISSUE THREAD

**Issue by cck23** [Auctionator/Auctionator#1183]
Please include as much of the following information as possible to help me fix the bug:

Auctionator was working fine yesterday in terms of full scan. Today, after the scheduled maintanence. The full scan is stopping at 10% and says "Full Scan Failed to Complete. A full scan may be started in...."

I have updated to the latest version which looks like it was updated 2 days ago. However, WoW still thinks the add on is out of date.

_Please include a brief description of the bug, including what you were doing, and when it occurred._

Attempting to run a full scan at the AH - Darksorrow and also on Hellscream

_Include the steps I would need to follow to reproduce the bug._

1 - Go to the AH and start a full scan, observe that the progress stops at 10% and there is a message in the chat window as above.

_Include a list of addons you were running at the time this bug occurred._

I only have Auctionator and Journaltor installed

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by plusmouse** [comment]
Hi. I've just pushed an update to resolve the issue - the default scan mode is now too slow on the merged auction houses so I swapped to a different scan mode.

Available on Curseforge (https://www.curseforge.com/wow/addons/auctionator/files/3938739) and Wago now.

Can you respond whether this resolves the problem?

**Comment by cck23** [comment]
Hello, I did have the alternate scan set up (which worked before). I then disabled the alternate method and restarted WoW. When I scan, it does work but the chat message still says it's using the alternate scan even though it's switch off in the addon's settings. It works, but were you expecting that message to say that it's using the alternate method?

**Comment by plusmouse** [comment]
That's normal, I pushed out the release in a hurry and didn't have time to change the message

**Comment by cck23** [comment]
OKay, thanks

**Comment by plusmouse** [comment]
It will be fixed in a later release.

**Comment by cck23** [comment]
Excellent

**Comment by plusmouse** [comment]
Just pushed a release with the fixed wording. Closing this issue as complete.
[Auctionator-9.2.29.zip](https://github.com/Auctionator/Auctionator/files/9359119/Auctionator-9.2.29.zip)
