### ISSUE TITLE
Safety feature for undercutting

### ISSUE THREAD

**Issue by jashakettel** [Auctionator/Auctionator#1185]
A few days ago i wanted to sell 4x spellcloth. Rather then entering at the stack field, I ended up entering 4g/item (the market value was 15g) and posted the auction. To my surprise a bot INSTANTLY bought the cloth off the auction house..

Is there a way to implement a safety feature for this? Maybe a undercut % and when you manage to enter under it, a little warning before posting the items?

Of course I could be more cautious and this is the 1st time this happend in 3 years, but maybe I'm not the only one who managed to fail this way 

thanks!

**Comment by plusmouse** [comment]
There's already a post warning when posting really low on retail for Auctionator. I'm happy to add in one for classic too, but need example listing screenshots and what price would be considered too low.

**Comment by plusmouse** [comment]
Something like 
![image](https://user-images.githubusercontent.com/60280559/187026700-53f4cd14-5431-4826-8146-968b5304725e.png)
and 5s

Having the comparison for a few items would be ideal, that way I can ensure the formula used to detect abnormally low prices is general enough to be useful

**Comment by jashakettel** [comment]
![Screenshot 2022-08-27 124630](https://user-images.githubusercontent.com/111365117/187026794-ff34a639-b2ea-4858-86de-5b8833dafd88.png)

Something like this..the addon uses real time data anyways? So it scans the current price and undercuts it. Maybe something like a configurable % value of the current price, when undercut you receive a warning?
E.g. 50%, when I enter a price lower than 50% (~11g) I get a warning

**Comment by plusmouse** [comment]
I'd prefer to have a default % tuned to the values people post at as what counts as too low will probably vary for high or low value items, and I can code in scaling so that it selects the appropriate % for the right value. Making it an opt-in feature will likely make it only be found after a user has made a mistake, or they opt-out because the % is too sensitive.

Retail looks like this when posting a price that look low:
![image](https://user-images.githubusercontent.com/60280559/187027023-9b258917-159e-47cc-b0f1-8e4bae593238.png)

**Comment by plusmouse** [comment]
(current Auctionator for classic looks like this when selling, so any dialog/confirmation added would only apply to this classic UI)
![image](https://user-images.githubusercontent.com/60280559/187027175-b17db009-1df6-4166-816b-62bdae185843.png)

**Comment by jashakettel** [comment]
looking good!
cant wait :)

**Comment by jashakettel** [comment]
omg thank you for the pictures...I was a little confused, bc your version looked so different from mine! 
I have been using "Auctionator fix for classic" for over 2 years, I think there wasnt a classic version of Auctionator back then^^
and the current version does have a feature 
"confirm posting items at an unusual low price"

I feel so dumb now xD

**Comment by plusmouse** [comment]
That particular feature only covers posting below vendor price in the classic version. The retail version uses a formula to guess when its too low. This build includes the low price check of 50% below
[Auctionator-9.2.30-2-g03ab30d-bcc.zip](https://github.com/Auctionator/Auctionator/files/9450928/Auctionator-9.2.30-2-g03ab30d-bcc.zip)
![image](https://user-images.githubusercontent.com/60280559/187382666-d031faf4-71ad-42fd-88db-0434952972ab.png)

**Comment by plusmouse** [comment]
Available in the latest alpha, available on Curseforge and Wago once the files have finished processing.
![image](https://user-images.githubusercontent.com/60280559/187406718-d459ba9e-f590-4155-b5bd-df6619dd56c3.png)
