### ISSUE TITLE
Scanning is too slow

### ISSUE THREAD

**Issue by Higr25** [Auctionator/Auctionator#1187]
Just updated from TBC to WOTLK version and scanning seems about 5x slower than before. It's both full scan and 'small' scan when placing items to sell.

**Comment by plusmouse** [comment]
It's a Blizzard issue - nothing in Auctionator has changed between the TBC and WOTLK versions.

**Comment by sjanssen15** [comment]
Yesterday I had the same issue, but as of today it's snappy again so I'm not sure if something changed serverside. Issue for me is resolved.

**Comment by plusmouse** [comment]
This is a result of the WoW servers, can't fix so closing.
