### ISSUE TITLE
Current price + reaml history / your history

### ISSUE THREAD

**Issue by Dhisanas** [Auctionator/Auctionator#1188]
**Is your feature request related to a problem? Please describe.**
The "Selling" tab In the latest releases of retail due to the updtades to the auction house and therefore updates to the auctionator UI have been changed to have the below tabs for active sellings, history and your history, all into different tabs while the older version used to have a single tab for selling and in the same page below the option to select realm history or your history allowing to check current prices compared to your history (for example) without changing page each time, if you have to post 100+ items at the time it can be a bit unnerving tbh or maybe it's just me..

**Describe the solution you'd like**
revert back the ui to an alternative such a version like 9.2.21 to keep all in 1 page

**Describe alternatives you've considered**
can just the Ui be changed to have all in 1 page but keep on using the updated addon, is there something i can do to do so without making you change the whole addon?

**Additional context**
Keep up the good work and thanks for whatever you can do to help :)

![9 2 21 example](https://user-images.githubusercontent.com/112558441/187685396-c6cc8e57-848a-43e8-87dd-5fc926201aac.png)

![9 2 31 example](https://user-images.githubusercontent.com/112558441/187685421-8cb48b82-6fb6-43a8-afd5-a9bbdf1ebdc1.png)

**Comment by plusmouse** [comment]
Available as an options in the latest alpha
[Auctionator-9.2.31-2-gd65cbda.zip](https://github.com/Auctionator/Auctionator/files/9470299/Auctionator-9.2.31-2-gd65cbda.zip)
![image](https://user-images.githubusercontent.com/60280559/187928208-c913d1ca-4010-45a0-83dd-a00a201fcf9c.png)

**Comment by Dhisanas** [comment]
Great job man :D
