### ISSUE TITLE
Some cut gems failing to display in search results

### ISSUE THREAD

**Issue by Ranadicus** [Auctionator/Auctionator#1189]
Some, but not all, of the cut gems aren't being displayed in the search results.

For example, when searching "Talasite" only the basic uncut Talasite will appear in the results. All of the cut Talasite, such as Dazzling Talasite, must be searched either by explicit name or prefix (e.g. Dazzling) to be located. However, searching "Star of Elune" will show the Sparkling Star of Elune in addition to the uncut Star of Elune, but only those two results. All other cut Star of Elune are missing and must be searched using other parameters to be seen.

I've been able to reproduce this issue with no addons other than Auctionator loaded

This issue has persisted for some time, since before the pre patch update

**Comment by plusmouse** [comment]
There will be a "Load more results" button at the bottom of the search results:
![image](https://user-images.githubusercontent.com/60280559/187861349-5e1a1fdf-a724-4a10-8c1a-f1696f6e3b9b.png)
If you want Auctionator to always load all available results turn this option on:
![image](https://user-images.githubusercontent.com/60280559/187861476-a83645bb-91a2-43d8-a85c-f77258470063.png)

**Comment by Ranadicus** [comment]
Interesting, I guess it didn't occur to me that I would need to load more results when there are only like 5 to begin with. Thanks
