### ISSUE TITLE
Buy popup closes as soon as buy is clicked

### ISSUE THREAD

**Issue by ceylina** [Auctionator/Auctionator#119]
In 4.0.1 after I've scanned a shopping list of pattern, plans and schematics in the "Buy" tab and click "Buy" on an item, the new box shortly pops up where you can buy the item and then it vanish again making it impossible to buy any items.

**Comment by ceylina** [comment]
This requires a revert and conclusion on what  these arguments take as values.

Aucitonatorbuy.lua

Line 158 must be reset to

QueryAuctionItems( queryString, nil, nil, gAtr_Buy_CurPage, nil, nil, false, false, nil )

AuctionatorScanFull.lua

line 93

QueryAuctionItems( "", nil, nil, 0, nil, nil, true, false, nil )

line 143

QueryAuctionItems( "", nil, nil, gSlowScanPage, nil, nil, false, false, nil )


this should be the last time I recommend touching these.

**Comment by jrob8577** [comment]
Fixed.  :)
