### ISSUE TITLE
Wrath Classic Enchanting Search

### ISSUE THREAD

**Issue by b-morgan** [Auctionator/Auctionator#1190]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

The Search button in the Enchanting adds the enchant name to the shopping list. If it added "Scroll of "..enchant name then the results might be better.
 
## Steps to Reproduce

1. Open the AH
2. Open Enchanting (now a Tradeskill instead of a Craft)
3. Select an Enchant
4. Click on "Search"

## Loaded Addons

N/A

## Back Trace (LUA Error Output)

N/A

**Comment by plusmouse** [comment]
Changed the search method for enchant scrolls to use a non-exact search so that it will catch them. Reagents and products of other professions still use an exact search (this is the same fix that was applied to retail)
