### ISSUE TITLE
Just updated to latest version, there is nothing there...........

### ISSUE THREAD

**Issue by Ifartstarz** [Auctionator/Auctionator#1191]
![WoWScrnShot_090222_164002](https://user-images.githubusercontent.com/112528341/188246726-30765953-e104-4239-9fd1-b05754e3eeba.jpg)
![WoWScrnShot_090222_163927](https://user-images.githubusercontent.com/112528341/188246736-8564521c-23c0-4e31-b36c-e97205fb4946.jpg)
Litterally nothing under options, no features whatsoever, its dead

**Comment by AnbuFozzy** [comment]
Same here! Re-installed, deleted and installed again... nothing. Folder isn't blocked.

**Comment by plusmouse** [comment]
Can you install BugSack and BugGrabber and report if they show any errors?

**Comment by bigdaveor** [comment]
same problem:


10x SharedXML\Mixin.lua:28: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: in function `pairs'
[string "@SharedXML\Mixin.lua"]:28: in function <SharedXML\Mixin.lua:25>
[string "=(tail call)"]: ?
[string "@Auctionator\Source\Components\ResultsListing\Mixins\AuctionatorStringColumnHeader.lua"]:1: in main chunk

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

**Comment by plusmouse** [comment]
@bigdaveor Are there any other errors in your BugSack? That looks like a corrupted install.

**Comment by Ifartstarz** [comment]
> @bigdaveor Are there any other errors in your BugSack? That looks like a corrupted install.

Downloaded current version right from curseforge, installed as always, Broken still

**Comment by plusmouse** [comment]
> Downloaded current version right from curseforge, installed as always, Broken still
Again, can you install BugSack and BugGrabber and report if they show any errors?

**Comment by jtravers** [comment]
Apologies if posting incorrectly.
I enjoy the addon so I downloaded buggrabber and bugsack.

Issue:
Auctionator tabs are missing when visiting the ingame auctionhouse. No tabs.

Interface settings:
I am "loading "out of date addons" and only have auctionator, buggrabber, and bugsack, enabled.

Error:
--------
1x ...tor\Source_Mainline\Components\Mixins\MoneyInput.lua:32: attempt to call method 'GetAmount' (a nil value)
[string "@Auctionator\Source_Mainline\Components\Mixins\MoneyInput.lua"]:32: in function `GetAmount'
[string "@Auctionator\Source_Mainline\Config\Mixins\SellingAllItems.lua"]:56: in function <...or\Source_Mainline\Config\Mixins\SellingAllItems.lua:45>
[string "=[C]"]: in function `Hide'
[string "@FrameXML\InterfaceOptionsFrame.lua"]:201: in function `InterfaceOptionsFrame_Show'
[string "@FrameXML\InterfaceOptionsFrame.lua"]:243: in function <FrameXML\InterfaceOptionsFrame.lua:223>

Locals:
self = <unnamed> {
 0 = <userdata>
 OnLeave = <function> defined @Auctionator\Source\Components\Mixins\Tooltip.lua:16
 GetAmount = <function> defined @Auctionator\Source_Mainline\Components\Mixins\MoneyInput.lua:31
 OnLoad = <function> defined @Auctionator\Source_Mainline\Components\Mixins\MoneyInput.lua:3
 SetAmount = <function> defined @Auctionator\Source_Mainline\Components\Mixins\MoneyInput.lua:21
 Label = <unnamed> {
 }
 tooltipText = "The undercut value that will be used to calculate the sell price."
 MoneyInput = <unnamed> {
 }
 labelText = "Undercut"
 Clear = <function> defined @Auctionator\Source_Mainline\Components\Mixins\MoneyInput.lua:27
 OnEnter = <function> defined @Auctionator\Source\Components\Mixins\Tooltip.lua:3
 tooltipTitleText = "Undercut Value"
}
(*temporary) = nil
(*temporary) = <unnamed> {
 0 = <userdata>
 hideCopper = true
}
(*temporary) = "attempt to call method 'GetAmount' (a nil value)"

**Comment by plusmouse** [comment]
@jtravers It looks like you've installed the retail version of Auctionator by mistake. You want https://www.curseforge.com/wow/addons/auctionator/files/3967813

**Comment by jtravers** [comment]
> @jtravers It looks like you've installed the retail version of Auctionator by mistake. You want https://www.curseforge.com/wow/addons/auctionator/files/3967813

Well, Thank you! hah

**Comment by plusmouse** [comment]
Closing this as it appears to be the retail version installed by mistake error.
