### ISSUE TITLE
"No Items Found"

### ISSUE THREAD

**Issue by SadboiYami** [Auctionator/Auctionator#1192]
Please include as much of the following information as possible to help me fix the bug:

I keep getting the message "Full Scan (Summary Mode) Failed to complete." And that's the ONLY thing that i can find thats different. But i've tried EVERYTHING. No matter what I do, search, filter, change settings, full scans, anything, NOT A SINGLE ITEM SHOWS UP. It looks like its loading forever i let it sit multiple different times for over 10 minutes and nothing. If you ever click the Search button directly, again no matter how you do it, all it does is bring up the message "No Items Found". I've reloaded my UI, I've gone thru all the settings and even tried the slower scan option even tho im not on a busy server, and still NOTHING works. 

_Please include a brief description of the bug, including what you were doing, and when it occurred._

All I did was open up the Auction House. I didn't do anything special. I've never once messed with any of the settings or anything ever. I was just trying to buy a gem and when i opened it nothing would load ANYWHERE, NOTHING LOADS. No items of any kinds, no sections, not the WoW UI or the TSM UI, nothing you type or search, not a single thing loads. You either get a spinning circle that never stops or the message "No Items Found". I've taken down all the other addons i had running 1 by 1 until all that remained was Auctionator and it still doesnt work. 

_Include the steps I would need to follow to reproduce the bug._

As I said, JUST OPEN THE AUCTION HOUSE. NOTHING WORKS. ALL I DID WAS OPEN IT AT AN AUCTION NPC AS USUAL. I tried the long neck mount, i tried an actual stormwind auction house, nothing. 

_Include a list of addons you were running at the time this bug occurred._

Auctioneer and all the things that come with it, TSM, Pawn, WorthIt and i think thats it.

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by plusmouse** [comment]
Does the % counter in the Auctionator tab increase beyond 10% when the scan is running?
![image](https://user-images.githubusercontent.com/60280559/188258447-0a3449c8-897e-4823-ae07-f06e091d0e56.png)
Also, can you install BugSack and BugGrabber and report if they show any error when you attempt to search or scan?

**Comment by plusmouse** [comment]
No response. Closing.

**Comment by SadboiYami** [comment]
The reason i didn't respond is because I'm getting literally hundreds of zperl bug reports a day while playing dungeons/raids/pvp of every kind, nearly every npc interaction, auction house, the list goes on. The number just yesterday hit 400 and I decided it's a lot less time consuming and better to just wait until the addon as a whole is updated since it seems like thats probably the reason all this is happening.

**Comment by SadboiYami** [comment]
After a few reloads and completely logging out and closing for a couple minutes then starting everything up again, it all went back to normal. Thank you for trying <3
