### ISSUE TITLE
Internal Auction House Error When Posting Many Stacks At Once

### ISSUE THREAD

**Issue by Verlash** [Auctionator/Auctionator#1193]
I honestly don't think this is a "bug" in the addon per se, but more of an oversight.
I am playing the Wrath pre-patch and I've come across an issue with this addon.
When posting several stacks at once, the addon does the posting too quickly.
For example, I tried to post 50 stacks of 1 item (sometimes posting in stacks of 1 will allow posting with 0 deposit).
It got through posting about half the stacks when I got an Internal auction house error and then the Auctionator window got stuck in an infinite loading loop, I had to close the window and talk to the auctioneer again. I tried posting the rest of the 25 or so stacks of 1 and that time it only got through about 10 of them before I got the error again.

I think when posting more than 1 stack there needs to be a pause in the code between postings, to avoid this error. How long the pause needs to be, I don't know.

**Comment by plusmouse** [comment]
The Blizzard API sets the delay - all Auctionator does is press the metaphorical "Go start posting 50 stacks" button. So there's no control over the delay for Auctionator to exert.
