### ISSUE TITLE
Major Problem with non-cancellable scanning

### ISSUE THREAD

**Issue by yyaux** [Auctionator/Auctionator#1195]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

1. Scanning for an item or a shopping list
2. Press on results of any item
3. Try to buy an item

Problem: You cant buy it as auctionator constantly starts scanning over again (taking 4-5 min every time). After scanning is over you try to purchase the item, auctionator starts scanning for 5 min again. 

Auctionator must add a function to prevent this from happening. Scanning must be cancellable. This bug only appears in the new version, it never happened in Classic Vanilla.

**Comment by plusmouse** [comment]
Can you screenshot the affected views? This is how the buy process appears on my realm:
![buying copper ore](https://user-images.githubusercontent.com/60280559/188313688-b75830cf-e786-477f-b9f8-2b140fb15354.gif)

Scans shouldn't exceed 20s, even on a full pop megaserver.

Make sure this option is off:
![image](https://user-images.githubusercontent.com/60280559/188313630-bf9e1b12-ee2a-4c51-b3af-7b3c8bc426ed.png)

**Comment by yyaux** [comment]
I'm playing on a fresh realm so the ah is extremely flooded (e.g. 50 pages of copper ore) with new auctions coming in every few seconds.  This problem occurs then.

**Comment by plusmouse** [comment]
Does the list of available copper auctions change drastically (just the first page) every few seconds?
Can you screenshot 2 views, one on initial scan, and one after trying to purchase an item - I can't login to a fresh realm that is that busy (login queue)?

**Comment by plusmouse** [comment]
No response. Closing.
