### ISSUE TITLE
Slow Post Selling

### ISSUE THREAD

**Issue by avarath2022** [Auctionator/Auctionator#1196]
Since latest WOTLK update there is a good 6-10sec delay when I sell.  Post button will grey out for a time.  Just started. Reinstalled the addon and deleted settings.

**Comment by plusmouse** [comment]
Auctionator for Wrath Classic greys out the post button while waiting for when it is sure a post will succeed and then the post button will ungrey. Normally this would be an insignificant amount of time, but with the pre-patch and increased load on the servers the delay has become very noticeable. There isn't a good solution.

**Comment by JasonGoemaat** [comment]
I wonder why that is, the default blizzard sell works instantly every time

**Comment by nanjuekaien1** [comment]
Wrath
Indeed, Blizzard's sell interface  can be published directly
Publishing on Chinese servers now requires a 30-second wait

**Comment by plusmouse** [comment]
Got a solution, don't grey out the post button and let the user quickly retry if the post fails. Available in the latest alpha 
[Auctionator-9.2.36-1-g1a13343-wrath.zip](https://github.com/Auctionator/Auctionator/files/9543350/Auctionator-9.2.36-1-g1a13343-wrath.zip)
