### ISSUE TITLE
Add option to stop automatic "refresh" after posting something in the selling tab

### ISSUE THREAD

**Issue by StefGraf** [Auctionator/Auctionator#1197]
With the way you have to wait 30 seconds anytime you scan anything it would be most welcome to stop automatically refreshing the list of items after you post something. I really don't care to see how my item I posted looks next to the 20 other ones. I would rather use that time to refresh the list with the next item I want to sell.

**Describe the solution you'd like**
An option to enable/disable refreshing the list of items in the selling tab after you post something. When disabled, the list of items does not get refreshed automatically after posting. Optionally, the item you post just could get added as a "fake" item in the current list of items shown. But this is more of a "nice to have" thing, the important part is to not auto-refresh anymore.

**Describe alternatives you've considered**
We used to be able to "interrupt" this scan by clicking the next item to sell. But now, it throttles the refresh triggered by the next item and you have to wait for the timeout before it starts searching for the new item that got dropped into the selling box. So if you can restore the old behavior of the "new" item interrupting the refresh scan of the item you posted then that could work too but I doubt the current Auction House API would let you implement this correctly.

**Comment by mattdept** [comment]
I came here to leave this exact piece of feedback. Disabling this additional scan will certainly reduce the AH load described here:
https://github.com/Auctionator/Auctionator/issues/1196#issuecomment-1236399751

...by reducing the total number of queries sent to the AH. Disabling this additional (and largely unnecessary) post-selling scan would be a win-win.

**Comment by craigdbarber** [comment]
Additional motivation for disabling this feature is that often the extra scan gets stalled requiring a /reload of the UI to fix.

**Comment by plusmouse** [comment]
Fixed in the latest alpha
[Auctionator-9.2.36-6-g13be93f-wrath.zip](https://github.com/Auctionator/Auctionator/files/9551266/Auctionator-9.2.36-6-g13be93f-wrath.zip)

![scanless post update](https://user-images.githubusercontent.com/60280559/189741516-6fa6da14-a25c-449a-a7d4-fa67da1ecdf3.gif)

**Comment by StefGraf** [comment]
I tested it quickly with the alpha and can confirm the problem seems to be fixed.
