### ISSUE TITLE
You're going too fast?

### ISSUE THREAD

**Issue by Bitskob** [Auctionator/Auctionator#1198]
Please include as much of the following information as possible to help me fix the bug:

## Are you on the retail or the classic version of WoW?
retail
## Is this a bug or a feature request?
bug
# Bug:
## Brief Description of Bug

I get a message on the auctionator 'sell' tab the says "You're doing that too fast." for several (20-30) seconds before it allows the creation of an auction. This is an annoyance.
_Please include a brief description of the bug, including what you were doing, and when it occurred._

## Steps to Reproduce
Open the sall tab and immediately create an auction. I right-click on the item to do this.
_Include the steps I would need to follow to reproduce the bug._
same
## Loaded Addons
auctionator and several others
_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

# Feature Request:
## Is your feature request related to a problem? Please describe
Describe the problem you are experiencing.

## Describe the solution you'd like
Have the window be as responsive as it once was (a couple of weeks ago)

**Comment by plusmouse** [comment]
This isn't something that can be fixed by Auctionator, its a Blizzard problem.
