### ISSUE TITLE
search and post button is delayed to be active ( red ) if ( always load all available  results) isn't checked 

### ISSUE THREAD

**Issue by dare2010** [Auctionator/Auctionator#1199]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug
search and post button is delayed to be active ( red ) if ( always load all available  results) isn't checked 
_Please include a brief description of the bug, including what you were doing, and when it occurred._

## Steps to Reproduce

_Include the steps I would need to follow to reproduce the bug._
just uncheck " always load all available  results " then open AH , have a look at search button which will take like 15 sec to be active , same for post button when creating auctions
## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._
i'v disabled them all , only auctionator wroking alone in an the space xD
## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by plusmouse** [comment]
The search takes quite a bit longer when "Always load all available results" is checked, because it goes through every page.

Testing on my realm, when "Always load all available results" is unticked start-to-ready-to-post take 0.47s, and when it is ticked, 11.28s - which renders no speed benefit when posting.

**Comment by TheClarkster** [comment]
I can confirm this bug.  "Always load" is turned off, in all sections of the options.

When trying to sell, it instantly loads the first page, stops searching, and then takes exactly 10 seconds for the Post button to become active.

I tried turning "always load all available results" on and then back off, but the bug remains.

Is it some sort of throttling on Faerlina maybe?

**Comment by plusmouse** [comment]
Its definitely throttling.

Auctionator for Wrath Classic greys out the post button while waiting for when it is sure a post will succeed and then the post button will ungrey. Normally this would be an insignificant amount of time, but with the pre-patch and increased load on the servers the delay has become very noticeable. There isn't a good solution.

**Comment by plusmouse** [comment]
Got a solution, don't grey out the post button and let the user quickly retry if the post fails. Available in the latest alpha 
[Auctionator-9.2.36-1-g1a13343-wrath.zip](https://github.com/Auctionator/Auctionator/files/9543350/Auctionator-9.2.36-1-g1a13343-wrath.zip)
