### ISSUE TITLE
Post-sale autoscans interfere with posting new auctions

### ISSUE THREAD

**Issue by LavingRunatic** [Auctionator/Auctionator#1200]
Every time an auction sells, Auctionator is rescanning the AH, and it's interfering with posting new auctions (even when set to slow scan). For example, when I've posted a stack of gems/chants/food/etc, then attempt to post a few rings, there are constant interruptions as the gems/etc sell. The price on the rings reset with every gem sale, so attempting to type in a price fails because the autoscan occurring after the other sales overwrites and/or slaps extra digits onto the price you're trying to type in. You're basically stuck until faster-selling items are no longer posted/selling.

In the same manner, it's tough and/or impossible to post the auction, even when the price is fine. Even if you manage to set a price you like, the autoscans that occur after every sale also interfere with simply posting new auctions. Every time something sells, the ensuing autoscan greys-out the "Post" button. You have to try catching it in that brief moment between sales to even be able to post.  Again, when you have faster selling items up like gems/chants, this makes it nearly impossible to post other auctions. Slow scan setting helps a little, but only a little.

It really shouldn't be autoscanning/interfering with a completely unrelated auction every time a different one sells, effectively preventing me from typing in a price/posting. It's excruciating to work with given how fast some items sell now on the world market.

**Comment by plusmouse** [comment]
I've found the bug causing the extra scans and fixed it in the latest alpha (available from Curseforge and Wago shortly)
[Auctionator-9.2.35-2-g77bf5cd.zip](https://github.com/Auctionator/Auctionator/files/9500122/Auctionator-9.2.35-2-g77bf5cd.zip)

**Comment by LavingRunatic** [comment]
What took u so long? lol

Seriously amazing, thank you!
