### ISSUE TITLE
Request: Implement type-ahead look-up for the search box in the Shopping tab

### ISSUE THREAD

**Issue by almx** [Auctionator/Auctionator#1202]
Problem: In the "old look" version of Auctionator, the addon kept a history of searches and matched previous searches as you typed. For example, if I had previously searched for "dreamfoil", I could type "dream" and it'd suggest "dreamfoil", allowing for quick executions of previous searches.

Suggested solution: Implement type-ahead look-up for the search box in the Shopping tab

**Comment by plusmouse** [comment]
Available in the latest alpha (from Curseforge and Wago shortly)
[Auctionator-9.2.41-5-gc4adac2-wrath.zip](https://github.com/Auctionator/Auctionator/files/9718122/Auctionator-9.2.41-5-gc4adac2-wrath.zip)
