### ISSUE TITLE
When trying to post

### ISSUE THREAD

**Issue by cryptoris** [Auctionator/Auctionator#1203]
Please include as much of the following information as possible to help me fix the bug:

## Is this a bug or a feature request? i dont know if its a bug .. maybe a feature request?

# Bug: when  posting on the auction house to sell the post button is greyed out for way too long. 
## Brief Description of Bug

_Please include a brief description of the bug, including what you were doing, and when it occurred._

## Steps to Reproduce

_Include the steps I would need to follow to reproduce the bug._

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

# Feature Request:
## Is your feature request related to a problem? Please describe
Describe the problem you are experiencing.

**Comment by plusmouse** [comment]
The post button is greyed out to avoid an Internal Auction Error caused by posting before the WoW client is ready.

Auctionator for Wrath Classic greys out the post button while waiting for when it is sure a post will succeed and then the post button will ungrey. Normally this would be an insignificant amount of time, but with the pre-patch and increased load on the servers the delay has become very noticeable. There isn't a good solution.

**Comment by Geesu** [comment]
The problem is if you do "20 stacks of 1" the wow lua method `PostAuction` will fail with `Internal Auction Error`, I wonder if it would be better to move the logic of splitting the stacks into the addon? And add a delay?

I just wish we knew what the rate limit was.

**Comment by plusmouse** [comment]
@Geesu That would require a click per stack batch the addon manually schedules.

However, there is an alternative, offering the option to try again with the stacks that haven't been successfully posted.

[Auctionator-9.2.36-6-g90e7b60-wrath.zip](https://github.com/Auctionator/Auctionator/files/9543230/Auctionator-9.2.36-6-g90e7b60-wrath.zip)

This version incorporates letting you post while the post button would have been greyed _and_ loads the item back up (without another search) ready to try again if the post fails, deducting any stacks that succeeded from the next attempt.

I'd appreciate any feedback you have if you test this version.

**Comment by plusmouse** [comment]
Got a solution, don't grey out the post button and let the user quickly retry if the post fails. Available in the latest alpha 
[Auctionator-9.2.36-1-g1a13343-wrath.zip](https://github.com/Auctionator/Auctionator/files/9543350/Auctionator-9.2.36-1-g1a13343-wrath.zip)

**Comment by Geesu** [comment]
> @Geesu That would require a click per stack batch the addon manually schedules.
> 
> However, there is an alternative, offering the option to try again with the stacks that haven't been successfully posted.
> 
> [Auctionator-9.2.36-6-g90e7b60-wrath.zip](https://github.com/Auctionator/Auctionator/files/9543230/Auctionator-9.2.36-6-g90e7b60-wrath.zip)
> 
> This version incorporates letting you post while the post button would have been greyed _and_ loads the item back up (without another search) ready to try again if the post fails, deducting any stacks that succeeded from the next attempt.
> 
> I'd appreciate any feedback you have if you test this version.

The difference in this build is amazing! Thanks so much. The "may fail" is so helpful.

Will try the latest one you posted now!

**Comment by Geesu** [comment]
I did notice if I change the stack price, post it (maybe 1 of the 2 stacks goes through), and it "reloads" the previous details it won't save the stack price I typed in. Rather, it will show the price from the scan.

**Comment by plusmouse** [comment]
Fixed [Auctionator-9.2.36-4-g1803c9c-wrath.zip](https://github.com/Auctionator/Auctionator/files/9548656/Auctionator-9.2.36-4-g1803c9c-wrath.zip)
