### ISSUE TITLE
Quantity 0 (auto-max) isn't working in latest version

### ISSUE THREAD

**Issue by raysmith59** [Auctionator/Auctionator#1205]
When listing armour that I have multiples of it was only listing 1 at a time, I went into settings and noticed that weapons and armour had reverted to 1 where I'd had 0 before, I changed the settings to 0 but it's still only posting 1.  Tried relogging and existing the game without any change.

**Comment by plusmouse** [comment]
Which item specifically (I've tested a blacksmith's hammer and it works)?

**Comment by raysmith59** [comment]
I didn't have weapon multiples but it happened a bunch of times with armour.  Might be tied to that iLvl option I had enabled, I'll test that out tomorrow when I relist, but the Max button was available and worked when I clicked it even when it wasn't happening automatically.

**Comment by plusmouse** [comment]
Likely the same as the #1207 and this issue is for the Blizzard UI, not Auctionator's. Closing.
