### ISSUE TITLE
Non functional, had to disable

### ISSUE THREAD

**Issue by Friendlyhealer** [Auctionator/Auctionator#1206]
Please include as much of the following information as possible to help me fix the bug:
The auctionator addon just isnt working. 
## Brief Description of Bug
Tries to scan, takes 5 minutes to scan 5 pages, then when you go to buy, times out. 
_Please include a brief description of the bug, including what you were doing, and when it occurred._
I was trying to use auctionator addon to list auctions. 
## Steps to Reproduce
Benediction, Faerlina, Grobbulus, try to use the addon. 
_Include the steps I would need to follow to reproduce the bug._
See above.

**Comment by plusmouse** [comment]
Which version of Auctionator are you using?

**Comment by Friendlyhealer** [comment]
most recent classic wotlk update

**Comment by Friendlyhealer** [comment]
the only way I can actually post auctions efficiently is to disable the addon

**Comment by plusmouse** [comment]
It should only scan 1 page per-item on the latest version https://www.curseforge.com/wow/addons/auctionator/files/3973626 (as that's all that's needed for an addon to get the lowest price)

**Comment by Friendlyhealer** [comment]
yea sometimes though when you try and post it just doesnt post or times out, takes multiple times to try and post sometimes for auctions, when it goes through it lists them quickly just extremely slow

**Comment by plusmouse** [comment]
There isn't any fix for slow actions, as that's a result of the Blizzard servers being overloaded. Closing as can't fix.
