### ISSUE TITLE
Not all auctions are undercutting properly

### ISSUE THREAD

**Issue by raysmith59** [Auctionator/Auctionator#1207]
This may have happened other times but I'm only sure it's happening right now.

I have Buyout Mode enabled (checked).  I put up an auction for an item that had other listings.  There were 6 items up at the same price, 4 of which had bid prices showing.  The sort was by Buyout Price.  The 1st and 6th results were the two that didn't have buyout prices, the 4 between did.  There were two other listings below that at higher prices, Auctionator auto-selected the next listing after the top 6 for pricing purposes so it was recommending a price higher (by about 800g) than the lowest listings.  Not sure how to explain it, I'm guessing it's something to do with the mix of bid and non-bid listings for the 6 identically priced items that's causing Auctionator to skip those and move to the next listing to determine a recommended price.  Tried reversing the sort to the highest price is at the top and it's still selecting the same listing to determine pricing (now 2nd on the list instead of 7th).

**Comment by raysmith59** [comment]
Might be related to iLvl not being ignored, just had another scenario where there were 3 existing listings, one with a bid price, but it's telling me there aren't any available at my item level so it isn't recommending a price.  I'm pretty much just posting for tmog purposes so iLvl isn't a factor for me but if that's new functionality I'd like a way to disable it somehow, not seeing that ability currently.

**Comment by plusmouse** [comment]
Its this option:
![image](https://user-images.githubusercontent.com/60280559/189492830-5f036908-a97c-4278-a09a-8a2f166b2d0e.png)

**Comment by raysmith59** [comment]
Oops.  Will test that, ignore all this for now.

**Comment by raysmith59** [comment]
I disabled the option and tested a few more items, this one also isn't recommending a price due to item level.
![image](https://user-images.githubusercontent.com/2917594/189493187-78176781-1bdf-49b5-acc5-9825448388d3.png)

**Comment by raysmith59** [comment]
![image](https://user-images.githubusercontent.com/2917594/189493216-c16630a1-e9f6-4458-9c29-df268e1ec712.png)

**Comment by raysmith59** [comment]
But here's one that worked properly... maybe different behaviour for green vs blue vs purple?
![image](https://user-images.githubusercontent.com/2917594/189493293-6d8945bf-7eeb-46a1-91ef-b192449101db.png)

**Comment by raysmith59** [comment]
I've done most of my auctions but I still have 2 greens that are both working correctly and 2 blues that aren't so it might be an issue with quality.  I'll see if I can come up with more data tomorrow when I do my relists.

**Comment by plusmouse** [comment]
The Auctionator settings don't affect the Sell tab, only the Selling tab. The behaviour you are seeing in the Sell tab is Blizzard behaviour.

**Comment by plusmouse** [comment]
You will want to use this tab
![image](https://user-images.githubusercontent.com/60280559/189493386-41c9ebbf-db0b-43ed-9a20-4d5bf9660966.png)

**Comment by plusmouse** [comment]
There is an option to make right-click select the item for the Selling tab under "Selling: Shortcuts"

**Comment by raysmith59** [comment]
I've always just right-clicked to list items, something has changed recently and I assumed it was the UI change mentioned in the release notes.  I'll do some more testing.

**Comment by plusmouse** [comment]
From the screenshots the undercutting issues were with the Blizzard UI, and not Auctionator's. Closing.
