### ISSUE TITLE
Showing hidden items in a extra tab under sell.

### ISSUE THREAD

**Issue by Rubyurek** [Auctionator/Auctionator#1208]
**Is your feature request related to a problem? Please describe.**
Showing hidden items in a extra tab under sell.

**Describe the solution you'd like**
It should be possible to show hidden items in an extra tab under sell.

**Comment by plusmouse** [comment]
What do you need that feature for? Hidden items are presumed to be unwanted for selling.

**Comment by Rubyurek** [comment]
Problem is that sometimes the items are worth gold again and you have to take it out of the hidden mode to sell it. This is quite troublesome.

**Comment by ImJayc2** [comment]
It would be more useful to be able to unhide a selected item, rather then the current unhide all. I have items that are hidden accidentally (thanks to the cat walking across keyboard while I'm in AH) but don't want to unhide all

**Comment by plusmouse** [comment]
You can unhide a specific item by selecting it for the Selling tab.
1. By your normal bag, pick up and drop the item in the Selling tab slot, or use the Alt+Click shortcut to select it
2. Right click the item as shown in the Selling icon slot and click the "Unhide" button, that will only unhide the specific item.

**Comment by plusmouse** [comment]
This has a workaround, and adding a hidden item tab would defeat the point of hiding them in the first place.
