### ISSUE TITLE
[Feature Request] Login message

### ISSUE THREAD

**Issue by Stanzilla** [Auctionator/Auctionator#121]
Please add an option to disable the message on login that reminds about the FAQ.

**Comment by jrob8577** [comment]
Thanks for the request!

Note to self (and if you want to comment out this line until I can get the option built in): this is printed at Auctionator.lua:899:
```lua
zc.msg_anm ("Read the FAQ at |cFF4499FF http://auctionatoraddon.com/faq")
```

**Comment by jrob8577** [comment]
I'm just going to disable this message; seems pointless.  I suspect people will just go to curse anyways with a question?
