### ISSUE TITLE
[Request] Option to limit saved history prices.

### ISSUE THREAD

**Issue by zeenk** [Auctionator/Auctionator#1210]
**Is your feature request related to a problem? Please describe.**
File size sometimes gets too large for me and the addon resets to default settings same as my old issue, #1163 

**Describe the solution you'd like**
An option to limit how many history prices gets saved, like only save last 3 days maybe, could this help to stop this from happening? rather than having to use a fresh backup lua file every time this happens. I like this history pricing feature so don't want to disable it completely :/

**Additional context**

*Old screenshot, but same error*
![170888662-a8efbffd-a591-4d8c-b98f-84ee9b11bf5b](https://user-images.githubusercontent.com/68170439/190529523-1a7232e5-9734-486e-9cc6-2e29788535e8.png)

**Comment by plusmouse** [comment]
You can limit price histories to 3 days by using this command: ```
/atr c price_history_days 1
```

**Comment by zeenk** [comment]
Thanks! I will try this out and report back in a few weeks to see if it helped, closing this for now.

**Comment by zeenk** [comment]
Hmm, I think this command might be a bit buggy? I just canceled it for the first time today since I added the command and it's showing a bunch of very old listing i'm assuming? in my "your history tab" the realm history tab did get wiped tho so that one seem to work at least.

![2022-09-16_23-49-20](https://user-images.githubusercontent.com/68170439/190801179-eced26c8-3e3e-4052-ae64-52c2aed319a7.png)

**Comment by plusmouse** [comment]
You can use

```
/atr c auctions_history_length 3
```

to limit it to 3 days

**Comment by zeenk** [comment]
Thanks! 👍

**Comment by zeenk** [comment]
Has been almost a month now and have not ran into this issue again since I started using these 2 commands 👍 

```
/atr c price_history_days 3
/atr c auctions_history_length 3
```

If anyone else runs into this issue I had, use these ^
