### ISSUE TITLE
item not appearing on search

### ISSUE THREAD

**Issue by amey1956** [Auctionator/Auctionator#1212]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug
when searching for knothide leather it only will find knothide leather scraps, there is no other listing including knothide - regular or heavy version

_Please include a brief description of the bug, including what you were doing, and when it occurred._

## Steps to Reproduce

_Include the steps I would need to follow to reproduce the bug._

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by plusmouse** [comment]
There is a load more results button at the bottom of the results view and a always load all results option in the shopping section of the options

**Comment by plusmouse** [comment]
No response. Closing.
