### ISSUE TITLE
Option to abort multiple page scans in the Selling tab

### ISSUE THREAD

**Issue by phaiz** [Auctionator/Auctionator#1213]
Please include as much of the following information as possible to help me fix the bug:

## Are you on the retail or the classic version of WoW?
Wrath
## Is this a bug or a feature request?
Feature request
# Bug:
## Brief Description of Bug

_Please include a brief description of the bug, including what you were doing, and when it occurred._

## Steps to Reproduce

_Include the steps I would need to follow to reproduce the bug._

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

# Feature Request:
## Is your feature request related to a problem? Please describe
Describe the problem you are experiencing.
When using the Selling tab, the initial scan displays what I assume to be the first couple of pages for an item. Using the 'Load higher prices' button forces it to scan for every single listing without a way to stop the scan. This can lead to having to wait for it to scan many more listings than desired.
## Describe the solution you'd like
A button to stop the scan where it is.

**Comment by plusmouse** [comment]
Available in the latest alpha (on Curseforge once it finishes processing)
[Auctionator-10.0.27-2-g88827d4-wrath.zip](https://github.com/Auctionator/Auctionator/files/10300398/Auctionator-10.0.27-2-g88827d4-wrath.zip)
