### ISSUE TITLE
SetGuildBankItem hook locks up client

### ISSUE THREAD

**Issue by madcowfred** [Auctionator/Auctionator#1214]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

Auctionator hooks `GameTooltip.SetGuildBankItem` to provide auction information. It unconditionally adds text to the tooltip each time this is called, which works _very poorly_ when another addon uses this function to scan the entire guild bank - the WoW client locks up entirely and needs to be killed.

## Steps to Reproduce

1. Put a bunch (I had 50 or so, probably varies based on screen resolution/scale) of battle pets in a guild bank tab.
2. Install/activate the WoWthing Collector addon.
3. Open the guild bank.
4. Kill WoW after a bit as it's now unresponsive.

## Loaded Addons

- Auctionator
- WoWthing Collector

## Back Trace (LUA Error Output)

None as the client explodes.

**Comment by plusmouse** [comment]
This isn't an Auctionator bug - when scanning tooltips an addon should always use a custom tooltip so its results are unaffected by addon hooks. See https://wowpedia.fandom.com/wiki/UIOBJECT_GameTooltip for details on how to do that.
