### ISSUE TITLE
Add filter to ignore sellers

### ISSUE THREAD

**Issue by savelichev** [Auctionator/Auctionator#1219]
Some of the players constantly adds crazy price on their lot for fishing inattentive people, but this lots included into calculation of the goods market price.
E.g.: market price of the reagent is 20 gold, but someone can add price 2500 gold, so market price is (20+2500)/2.
It will be a great advantage to add black list for sellers while scanning data.

**Comment by plusmouse** [comment]
Auctionator doesn't have a market price, only a minimum price seen, so it won't be skewed?

**Comment by savelichev** [comment]
sorry missed addon, Auctionator works good))
