### ISSUE TITLE
All Auctionator Tabs missing

### ISSUE THREAD

**Issue by cdin0303** [Auctionator/Auctionator#1220]
When I load the Auctionator I don't have any of the Auctionator tabs.

If I type /Auctionator in the chat window I do get a list of possible commands. I've tried resetting the config, and reloading the addon on but everything I can think of doesn't cause the tabs to appear. I've also tried disabling all other addons and they don't appear.

Any idea what is causing this and how to fix it?

**Comment by plusmouse** [comment]
Try installing this file specifically https://www.curseforge.com/wow/addons/auctionator/files/4009628 - some of the download links on Curseforge are misleading and give the retail file when you're trying to download for wrath.

**Comment by cdin0303** [comment]
> Try installing this file specifically https://www.curseforge.com/wow/addons/auctionator/files/4009628 - some of the download links on Curseforge are misleading and give the retail file when you're trying to download for wrath.

Excellent. That worked. Thanks for the help.
