### ISSUE TITLE
Exact search on linking

### ISSUE THREAD

**Issue by MorbidMind** [Auctionator/Auctionator#1222]
I think it would be useful to default to exact search when triggering the search through linking the item (shift+click).

I think this is expected by users to find the item they linked instead of everything containing that name.

It is especially useful on classic as the AH is slower and often requires lengthy search to actually find that e.g. uncut gem, vs. quickly showing the cheapest item containing that name.

**Comment by plusmouse** [comment]
Find this in the next alpha 
[Auctionator-9.2.40-5-g7576797-wrath.zip](https://github.com/Auctionator/Auctionator/files/9692160/Auctionator-9.2.40-5-g7576797-wrath.zip)

**Comment by MorbidMind** [comment]
Works perfectly. Thank you!
