### ISSUE TITLE
Searching for items, frequently does not find item.

### ISSUE THREAD

**Issue by jeffhennen** [Auctionator/Auctionator#1223]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

When using the shopping tab, frequently does not find for example "Cobalt" or many others, it will not find the "Cobalt Ore" ore "Cobalt Bar". This happens very frequently for most things you can search.

## Steps to Reproduce

Shopping Tab, Search "Cobalt"

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._

Only Auctionator is  installed and running. I had disabled all other addons.

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by plusmouse** [comment]
There is a "Load more results" button at the bottom of the search results, and under Shopping in the settings there's a "Always load all available results" option to make that the default.
