### ISSUE TITLE
Function Search() error - breaks in-game LFG function

### ISSUE THREAD

**Issue by thehallowedfire** [Auctionator/Auctionator#1224]
## Brief Description of Bug
Made full AH scan and after some time (like 30-60 mins) tried to make a group through LFG function. Listed a group and got an error.
With this error LFG tool breaks and doesn't allow to see any groups listed (It infinitely searchs for a groups).
![image](https://user-images.githubusercontent.com/112851853/194276883-d02e5c8b-a474-4d6b-9f9f-e04069622759.png)

## Steps to Reproduce

Not sure what steps exactly but I did full scan and have changed zone and completed a few quests after that. Then have listed in LFG tool and got error. Usually /reload helps to get rid of error and make LFG tool work properly.

## Loaded Addons

![image](https://user-images.githubusercontent.com/112851853/194277410-5aa782b2-0a37-46ab-817f-0458fd4a68f6.png)
![image](https://user-images.githubusercontent.com/112851853/194277470-769ce4bd-5401-483a-8e05-9671c2429de5.png)
![image](https://user-images.githubusercontent.com/112851853/194277516-0a6c8a21-37c3-40cb-8824-2fd97ffc0129.png)
![image](https://user-images.githubusercontent.com/112851853/194277557-68aee2ff-223b-4426-aee6-f9504c188f63.png)
![image](https://user-images.githubusercontent.com/112851853/194277599-5313d25c-50d6-49cf-8e62-58d8def627d6.png)
![image](https://user-images.githubusercontent.com/112851853/194277636-da54d2de-e86d-4402-b771-1c93ee8e01e6.png)
![image](https://user-images.githubusercontent.com/112851853/194277689-2b276d6a-7a7b-41b6-a4fb-a34da087f889.png)
![image](https://user-images.githubusercontent.com/112851853/194277723-f0ee4dea-997b-4f35-a8fa-e187cd567168.png)

## Back Trace (LUA Error Output)

```
3x [ADDON_ACTION_BLOCKED] Модификация 'Auctionator' пыталась вызвать защищенную функцию 'Search()'.
[string "@!BugGrabber\BugGrabber.lua"]:480: in function <!BugGrabber\BugGrabber.lua:480>
[string "=[C]"]: in function `Search'
[string "@Blizzard_LookingForGroupUI\Blizzard_LFGBrowse.lua"]:225: in function `LFGBrowse_DoSearch'
[string "@Blizzard_LookingForGroupUI\Blizzard_LFGBrowse.lua"]:178: in function `SearchActiveEntry'
[string "@Blizzard_LookingForGroupUI\Blizzard_LFGParentFrame.lua"]:92: in function `LFGParentFrame_SearchActiveEntry'
[string "@Blizzard_LookingForGroupUI\Blizzard_LFGListing.lua"]:67: in function <...s\Blizzard_LookingForGroupUI\Blizzard_LFGListing.lua:49>
```

**Comment by plusmouse** [comment]
1. Has this happened more than once?
2. Did the `/reload` fix the search error this time around?

**Comment by thehallowedfire** [comment]
Yes, it happens frequently. Reload helps every time

**Comment by plusmouse** [comment]
Can you try this build and report if it still happens?

[Auctionator-9.2.41-6-gdab8932-wrath.zip](https://github.com/Auctionator/Auctionator/files/9736910/Auctionator-9.2.41-6-gdab8932-wrath.zip)

**Comment by thehallowedfire** [comment]
Made a full scan and have listed a group into LFG tool. No errors by now.

**Comment by plusmouse** [comment]
I'll call this fixed now. If it breaks again comment here and I'll reopen the issue.
