### ISSUE TITLE
Smart Buy Function

### ISSUE THREAD

**Issue by Nihlo** [Auctionator/Auctionator#1225]
I really love the addon and think it's one of the best. Thanks.

What I'm missing most is a smart buy function like some other auction addons have. It works that way:

The addon checks what is the cheapest way to buy the item your are looking for in a given quantity. 
Like so:  You'd like to buy 7 manapots and enter that number. Now the addon checks if the cheapest way 
is to buy 7x1 pot or 1x5 + 2x1 or even buy 10 cause it's cheaper than buying 7. The addon now shows you
the resulst with number of auctions which are needed to get your wanted amount and you have to click buy 
multiple times for multiple auctions obvs.

I used this addon last year which got that feature:
https://www.curseforge.com/wow/addons/auctipus
but sadly it doesn't work anymore and is in general a little bit too simple. 

Thanks in advanced
Nihlo

**Comment by plusmouse** [comment]
This would add an additional button to an already full view, and require additional explanation as to why a user might want to use it. So not going to add it.
