### ISSUE TITLE
entire addon does not load

### ISSUE THREAD

**Issue by Grizzlemonk** [Auctionator/Auctionator#1227]
Please include as much of the following information as possible to help me fix the bug:

## Auctionator does not seem to load at all. When I open the auction house, I do not have any of the tabs. Opening the game provides the following bug along with 28 'null' errors.

_Please include a brief description of the bug, including what you were doing, and when it occurred._

## I start the game and the addon does not work.

_Include the steps I would need to follow to reproduce the bug._

## I'm not sure, it just happens as soon as I start the game.

_Include a list of addons you were running at the time this bug occurred._

## 
Atlas
AtlasLoot Classic
Bagnon
Bartender4
BetterVendorPrice
BugGrabber
BugSack
Details!
Gatherlite
Pawn
Plater
Questie
Scrap
Sexymap
Slidebar
Stubby
WeakAuras
DeadlyBossMods

_You can get this through the use of !BugGrabber and BugSack addons._

Bug text follows

4x ...tor\Source_Mainline\Components\Mixins\MoneyInput.lua:32: attempt to call method 'GetAmount' (a nil value)
[string "@Auctionator\Source_Mainline\Components\Mixins\MoneyInput.lua"]:32: in function `GetAmount'
[string "@Auctionator\Source_Mainline\Config\Mixins\SellingAllItems.lua"]:56: in function <...or\Source_Mainline\Config\Mixins\SellingAllItems.lua:45>
[string "=[C]"]: in function `Hide'
[string "@FrameXML\InterfaceOptionsFrame.lua"]:201: in function `InterfaceOptionsFrame_Show'
[string "@FrameXML\InterfaceOptionsFrame.lua"]:261: in function <FrameXML\InterfaceOptionsFrame.lua:247>
[string "=[C]"]: in function `Click'
[string "@Interface_Wrath\FrameXML\UIParent.lua"]:3561: in function `ToggleGameMenu'
[string "TOGGLEGAMEMENU"]:1: in function <[string "TOGGLEGAMEMENU"]:1>

Locals:
self = <unnamed> {
 0 = <userdata>
 OnLeave = <function> defined @Auctionator\Source\Components\Mixins\Tooltip.lua:16
 GetAmount = <function> defined @Auctionator\Source_Mainline\Components\Mixins\MoneyInput.lua:31
 OnLoad = <function> defined @Auctionator\Source_Mainline\Components\Mixins\MoneyInput.lua:3
 SetAmount = <function> defined @Auctionator\Source_Mainline\Components\Mixins\MoneyInput.lua:21
 Label = <unnamed> {
 }
 tooltipText = "The undercut value that will be used to calculate the sell price."
 MoneyInput = <unnamed> {
 }
 labelText = "Undercut"
 Clear = <function> defined @Auctionator\Source_Mainline\Components\Mixins\MoneyInput.lua:27
 OnEnter = <function> defined @Auctionator\Source\Components\Mixins\Tooltip.lua:3
 tooltipTitleText = "Undercut Value"
}
(*temporary) = nil
(*temporary) = <unnamed> {
 0 = <userdata>
 hideCopper = true
}
(*temporary) = "attempt to call method 'GetAmount' (a nil value)"

**Comment by plusmouse** [comment]
Can you try installing this file specifically (Curseforge often makes the download buttons misleading so the wrong version gets downloaded)
[Auctionator-9.2.42-wrath.zip](https://github.com/Auctionator/Auctionator/files/9740856/Auctionator-9.2.42-wrath.zip)

**Comment by plusmouse** [comment]
No response. Closing.
