### ISSUE TITLE
Shopping Tab > Clicking buy on missing item automatically initiates re-scan

### ISSUE THREAD

**Issue by craigdbarber** [Auctionator/Auctionator#1229]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

When using the shopping tab, after the initial scan when you go to buy the item, if the item is missing it automatically initiates a re-scan for the item, which is very time consuming. In previous versions it would simply disable the item from the listing and allow you to buy the next item in the list without a re-scan.

## Steps to Reproduce

Go to shopping tab, search for a high volume item to buy, (uncut gems are a good option), wait some time for the initial results to be purchased, then attempt to buy them. Notice the triggering a re-scan for the item.

**Comment by plusmouse** [comment]
Do you have this option disabled?
![image](https://user-images.githubusercontent.com/60280559/195394955-eb99bd68-8a3d-4637-8659-18b7e66ec13e.png)

**Comment by craigdbarber** [comment]
Yes this option is disabled.

**Comment by plusmouse** [comment]
When it does the rescan does it just scan the first page, or does it go through all of them?

**Comment by craigdbarber** [comment]
It scans multiple pages.

**Comment by qq20004604** [comment]
反馈类似问题，
游戏版本：wlk
插件版本：不确定，但推测是最新版本

当我在一个人数较少，且拍卖行物品数量较少的服务器时使用，一切正常，或者说，没有明显察觉到异常情况
当我来到一个人数较多，拍卖行物品数量非常多的服务器时，遇见问题，按顺序描述我遇见的问题：
1. 我搜索了一个物品；
2. 该物品的在售数量非常多；
3. 我选择了一个最低价格或者较低价格物品，点击购买按钮；
4. 弹窗出现，但是购买按钮是灰色，且不能点击；
5. 需要等待较长的时间，才能点击弹窗里的购买按钮

**Comment by plusmouse** [comment]
I've put a fix in the next release that will prevent it from scanning more than 1 page on the refresh.
