### ISSUE TITLE
Strict find

### ISSUE THREAD

**Issue by ZzOneDay** [Auctionator/Auctionator#1230]
**Is your feature request related to a problem? Please describe.**
If i want to find/buy Sun Crystal, addon finds gem creted by profession. I try to get 'Sun Crystal' but find 'critital sun crystal'

**Describe the solution you'd like**
If i have some checkbox for 'strict finding'

**Describe alternatives you've considered**
If i put in field [Sun crystal] it will use strick find. 

**Additional context**
From time to time, i copy reg from profession, and it will be copy as [item], i have to remove '[' and ']' from field for finding

**Comment by plusmouse** [comment]
You can do an exact/strict search/find by surrounding the search term with `"`, so `"Sun Crystal"` will only find the raw crystal.
