### ISSUE TITLE
SOLID GOLD COIN

### ISSUE THREAD

**Issue by annoyed12345** [Auctionator/Auctionator#1231]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

_Please include a brief description of the bug, including what you were doing, and when it occurred._

## Steps to Reproduce

_Include the steps I would need to follow to reproduce the bug._

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by annoyed12345** [comment]
Solid Gold COin item not able to post- super annoying

**Comment by plusmouse** [comment]
You can't auction that item. If the default AH UI lets you list it report back.
