### ISSUE TITLE
To Craft Value in Profession Menu

### ISSUE THREAD

**Issue by Adiaz0611** [Auctionator/Auctionator#1234]
Not really a bug or a problem, but the cost to craft price overlaps with the time left on CD for crafts such as Titansteal Bars. 
Would it be possible to shift the cost to craft up or down do that is it not overlapping with the time left on cool down
Thank you.

**Comment by plusmouse** [comment]
Fixed in the latest release (pending processing by Curseforge)
[Auctionator-9.2.46-wrath.zip](https://github.com/Auctionator/Auctionator/files/9795155/Auctionator-9.2.46-wrath.zip)
