### ISSUE TITLE
Curseforge falsely complains that the addon was modified

### ISSUE THREAD

**Issue by LupeChristoph** [Auctionator/Auctionator#1236]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug
Curseforge displays a "Modified" action even thogh the most recent version of Auctionator is installed unmodified.

## Steps to Reproduce

1) install Curseforge
2) select World of Warcraft
3) let it scan your addons
4) check Auctionator.

## Loaded Addons

Irrelevant, this does not require using World of Warcraft.

## Back Trace (LUA Error Output)

Irrelevant, this does not require using World of Warcraft.

#### Possible Cause

Possibly Curseforge is confused by the varying version numbers in the *.toc files. I have opened a ticket with Curseforge for this and they asked me to notify you.

**Comment by plusmouse** [comment]
This is not an Auctionator bug - Curseforge should support _any_ version numbers that the addon has, and the addon's version numbers are of a common format for a lot of WoW addons. Besides if it was the version numbers it would glitch on everyone's Curseforge installations, and it doesn't.
![image](https://user-images.githubusercontent.com/60280559/196938845-0f0219b3-3c54-4be3-8d19-9394e3e5bf22.png)
![image](https://user-images.githubusercontent.com/60280559/196938898-21e59f96-3613-49ba-b7c0-fa23bdb22260.png)
