### ISSUE TITLE
block action

### ISSUE THREAD

**Issue by Alca01** [Auctionator/Auctionator#1237]
taint.log

10/21 18:28:37.001  An action was blocked in combat because of taint from Auctionator - CompactRaidFrame1:Show()
10/21 18:28:37.001      Interface\FrameXML\CompactUnitFrame.lua:378 CompactUnitFrame_UpdateVisible()
10/21 18:28:37.001      Interface\FrameXML\CompactUnitFrame.lua:309 CompactUnitFrame_UpdateAll()
10/21 18:28:37.001      Interface\FrameXML\CompactUnitFrame.lua:48

sry... not classic.... aucionar on sh.land
 Interface: 90207
 Version: 9.2.47

**Comment by plusmouse** [comment]
Which version of Auctionator were you running?

**Comment by plusmouse** [comment]
Can you try this build of Auctionator and report if it fixes the problem?
[Auctionator-9.2.47-6-gca65b37.zip](https://github.com/Auctionator/Auctionator/files/9847094/Auctionator-9.2.47-6-gca65b37.zip)

**Comment by plusmouse** [comment]
No response. Closing.
