### ISSUE TITLE
Action blocked

### ISSUE THREAD

**Issue by Fluke667** [Auctionator/Auctionator#1240]
10/23 12:51:01.368  An action was blocked in combat because of taint from Auctionator - CompactRaidFrame4:Show()
10/23 12:51:01.368      Interface\FrameXML\CompactUnitFrame.lua:378 CompactUnitFrame_UpdateVisible()
10/23 12:51:01.368      Interface\FrameXML\CompactUnitFrame.lua:309 CompactUnitFrame_UpdateAll()
10/23 12:51:01.368      Interface\FrameXML\CompactUnitFrame.lua:116
10/23 12:56:11.742  Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:135 CompactRaidFrameContainer_ReadyToUpdate()
10/23 12:56:11.742  An action was blocked in combat because of taint from Auctionator - CompactRaidFrame2:ClearAllPoints()
10/23 12:56:11.742      Interface\FrameXML\FlowContainer.lua:157 FlowContainer_DoLayout()
10/23 12:56:11.742      Interface\FrameXML\FlowContainer.lua:17 FlowContainer_ResumeUpdates()
10/23 12:56:11.742      Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:185 CompactRaidFrameContainer_LayoutFrames()
10/23 12:56:11.742      Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:130 CompactRaidFrameContainer_TryUpdate()
10/23 12:56:11.742      Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:57 CompactRaidFrameContainer_OnEvent()
10/23 12:56:11.742      CompactRaidFrameContainer:OnEvent()
10/23 12:56:11.742  Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:135 CompactRaidFrameContainer_ReadyToUpdate()
10/23 12:56:11.742  An action was blocked in combat because of taint from Auctionator - CompactRaidFrame2:SetPoint()
10/23 12:56:11.742      Interface\FrameXML\FlowContainer.lua:161 FlowContainer_DoLayout()
10/23 12:56:11.742      Interface\FrameXML\FlowContainer.lua:17 FlowContainer_ResumeUpdates()
10/23 12:56:11.742      Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:185 CompactRaidFrameContainer_LayoutFrames()
10/23 12:56:11.742      Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:130 CompactRaidFrameContainer_TryUpdate()
10/23 12:56:11.742      Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:57 CompactRaidFrameContainer_OnEvent()
10/23 12:56:11.742      CompactRaidFrameContainer:OnEvent()
10/23 12:56:11.742  Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:135 CompactRaidFrameContainer_ReadyToUpdate()
10/23 12:56:11.742  An action was blocked in combat because of taint from Auctionator - CompactRaidFrame3:ClearAllPoints()
10/23 12:56:11.742      Interface\FrameXML\FlowContainer.lua:157 FlowContainer_DoLayout()
10/23 12:56:11.742      Interface\FrameXML\FlowContainer.lua:17 FlowContainer_ResumeUpdates()
10/23 12:56:11.742      Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:185 CompactRaidFrameContainer_LayoutFrames()
10/23 12:56:11.742      Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:130 CompactRaidFrameContainer_TryUpdate()
10/23 12:56:11.742      Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:57 CompactRaidFrameContainer_OnEvent()
10/23 12:56:11.742      CompactRaidFrameContainer:OnEvent()
10/23 12:56:11.742  Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:135 CompactRaidFrameContainer_ReadyToUpdate()
10/23 12:56:11.742  An action was blocked in combat because of taint from Auctionator - CompactRaidFrame3:SetPoint()
10/23 12:56:11.742      Interface\FrameXML\FlowContainer.lua:161 FlowContainer_DoLayout()
10/23 12:56:11.742      Interface\FrameXML\FlowContainer.lua:17 FlowContainer_ResumeUpdates()
10/23 12:56:11.742      Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:185 CompactRaidFrameContainer_LayoutFrames()
10/23 12:56:11.742      Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:130 CompactRaidFrameContainer_TryUpdate()
10/23 12:56:11.742      Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:57 CompactRaidFrameContainer_OnEvent()
10/23 12:56:11.742      CompactRaidFrameContainer:OnEvent()

Im using Auctionator 9.2.47 on wow Retail

**Comment by Fluke667** [comment]
Wrong Label

**Comment by plusmouse** [comment]
1. Did the error stop anything in your UI from working?
2. What version of Auctionator are you running?

**Comment by Fluke667** [comment]
> 1. Did the error stop anything in your UI from working?
> 
>     2. What version of Auctionator are you running?

No did not stop Working.
Im using Auctionator 9.2.47 on wow Retail

**Comment by Fluke667** [comment]
From Bugsack:

23225x FrameXML\CompactUnitFrame.lua:1122: Attempt to access forbidden object from code tainted by an AddOn
[string "=[C]"]: in function `Hide'
[string "@FrameXML\CompactUnitFrame.lua"]:1122: in function `CompactUnitFrame_UpdateClassificationIndicator'
[string "@FrameXML\CompactUnitFrame.lua"]:1380: in function `CompactUnitFrame_UpdateAuras'
[string "@FrameXML\CompactUnitFrame.lua"]:96: in function <FrameXML\CompactUnitFrame.lua:45>

Locals:
Skipped (In Encounter)



Had this Error 23225 times (!!!)

**Comment by Fluke667** [comment]
Played 1x Mists of Tirna Scithe on Normal for Leveling and now Error is at 24401 times.

1176 Errors in that Dungeon

**Comment by plusmouse** [comment]
Can you try disabling Auctionator when you run another dungeon?

**Comment by plusmouse** [comment]
Just run Mists of Tirna Scythe, no errors :|

**Comment by plusmouse** [comment]
Can you run `/console taintLog 1` and reproduce the error? Then upload the taintlog found in `[WoW Directory]\_retail_\Logs\taint.log` to https://pastebin.com/ and link it here. That should help me figure out where the error is.

**Comment by Fluke667** [comment]
https://pastebin.com/vkDw2Atv

**Comment by plusmouse** [comment]
Thanks. Can you run `/console taintLog 2` and post that log too after getting an error?

**Comment by Fluke667** [comment]
25MB Log File
[taint.zip](https://github.com/Auctionator/Auctionator/files/9846871/taint.zip)

**Comment by plusmouse** [comment]
Thanks. I'm not sure exactly what it causing the error, but if its OK with you, would like you to try a few different builds of Auctionator to test what might have caused it.

[Option 1: Auctionator-9.2.47-5-gb2a54aa.zip](https://github.com/Auctionator/Auctionator/files/9846938/Auctionator-9.2.47-5-gb2a54aa.zip)
[Option 2: Auctionator-9.2.47-8-ga70dea7.zip](https://github.com/Auctionator/Auctionator/files/9846943/Auctionator-9.2.47-8-ga70dea7.zip)

You can swap back to `/console taintLog 1` as it doesn't look like `taintLog 2` is going to pinpoint the problem. Also, disable Collectionator while doing the tests, as Option 2 will break the current version of Collectionator.

**Comment by Fluke667** [comment]
No Error with Option 1

and now i try Option 2

**Comment by Fluke667** [comment]
Same Error with Option 2

**Comment by plusmouse** [comment]
That's good. I now have a possible fix for the error 😄 (the change I made for option 1)

**Comment by Fluke667** [comment]
Can i stay at Option1?

**Comment by plusmouse** [comment]
Yes.
