### ISSUE TITLE
'Auctionator' tried to call the protected function CompactRaidFrameManagerContainerResizeFrame

### ISSUE THREAD

**Issue by Tiiara** [Auctionator/Auctionator#1241]
## Version used
Auctionator-9.2.47-5-gb2a54aa.zip

## Brief Description of Bug
Bug apperead simply while in combat or starting combat

## Steps to Reproduce
login and start a fight

## Loaded Addons
kinda big list ... might have to disable a few to see if it's just auctioneers fault

## Back Trace (LUA Error Output)
12x [ADDON_ACTION_BLOCKED] AddOn 'Auctionator' tried to call the protected function 'CompactRaidFrameManagerContainerResizeFrame:Hide()'.
[string "@!BugGrabber\BugGrabber.lua"]:480: in function <!BugGrabber\BugGrabber.lua:480>
[string "=[C]"]: in function 'Hide'
[string "@Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameManager.lua"]:574: in function 'CompactRaidFrameManager_LockContainer'
[string "@Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameManager.lua"]:567: in function 'CompactRaidFrameManager_UpdateContainerLockVisibility'
[string "@Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameManager.lua"]:56: in function <...mpactRaidFrames\Blizzard_CompactRaidFrameManager.lua:49>

Locals:
Skipped (In Encounter)

**Comment by plusmouse** [comment]
It probably isn't Auctionator. I've tried running a few dungeons with raid frames enabled and haven't hit any errors. Can you try disabling Auctionator and reporting if the error still happens in your next dungeon/raid?

**Comment by Tiiara** [comment]
It did not happen in a dungeon / raid. I was just doing worldquests in a normal group. 
Also, I use an interface addon (pitbull) and the standard blizzard raidframe is disabled.

**Comment by plusmouse** [comment]
Tried using Pitbull and Auctionator in a world quest - no error.

Can you run `/console taintLog 1` and reproduce the error? Then upload the taintlog found in `[WoW Directory]\_retail_\Logs\taint.log` to https://pastebin.com/ and link it here. That should help me figure out where the error is.

**Comment by Tiiara** [comment]
Just got another error. 

1x [ADDON_ACTION_BLOCKED] AddOn 'Auctionator' tried to call the protected function 'CompactRaidFrame2:ClearAllPoints()'.
[string "@!BugGrabber\BugGrabber.lua"]:480: in function <!BugGrabber\BugGrabber.lua:480>
[string "=[C]"]: in function `ClearAllPoints'
[string "@FrameXML\FlowContainer.lua"]:157: in function `FlowContainer_DoLayout'
[string "@FrameXML\FlowContainer.lua"]:17: in function `FlowContainer_ResumeUpdates'
[string "@Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:185: in function 'CompactRaidFrameContainer_LayoutFrames'
[string "@Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:130: in function 'CompactRaidFrameContainer_TryUpdate'
[string "@Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:57: in function 'CompactRaidFrameContainer_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

**Comment by Tiiara** [comment]
Here's the taint.log

https://pastebin.com/GSifsq04

**Comment by plusmouse** [comment]
Thanks. Can you run `/console taintLog 2` and post that log too after getting an error (it should be a lot larger)?

**Comment by Tiiara** [comment]
_You have exceeded the maximum size of 512 kilobytes per Paste ..._ 

Maybe this works?
https://cdn.discordapp.com/attachments/401746874089996310/1033753895102590997/taint.log

**Comment by plusmouse** [comment]
That works. Thanks 😄 Just looking into it.

**Comment by plusmouse** [comment]
I'm not sure exactly what is causing the error, but if its OK with you, would like you to try a few different builds of Auctionator to test what might have caused it.

[Option 1: Auctionator-9.2.47-5-gb2a54aa.zip](https://github.com/Auctionator/Auctionator/files/9846938/Auctionator-9.2.47-5-gb2a54aa.zip)
[Option 2: Auctionator-9.2.47-8-ga70dea7.zip](https://github.com/Auctionator/Auctionator/files/9846943/Auctionator-9.2.47-8-ga70dea7.zip)

You can swap back to `/console taintLog 1` as it doesn't look like `taintLog 2` is going to pinpoint the problem.

**Comment by Tiiara** [comment]
I was using Auctionator-9.2.47-5-gb2a54aa.zip up until now.
I'll try Auctionator-9.2.47-8-ga70dea7.zip next. Thank you.

**Comment by plusmouse** [comment]
The Option 1 is a modified version of `Auctionator-9.2.47-5-gb2a54aa.zip` - it includes a change that has worked for another user (so if Option 2 errors can you try the modified version in Option 1)
