### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SegoItCh** [Auctionator/Auctionator#1242]
1x ...\Auctionator\Source\Tabs\Auctionator\Mixins\Main.lua:15: attempt to call field 'OpenToCategory' (a nil value)
[string "@Auctionator\Source\Tabs\Auctionator\Mixins\Main.lua"]:15: in function `OpenOptions'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals:
self = AuctionatorConfigFrame {
 0 = <userdata>
 AuthorHeading = <unnamed> {
 }
 deDE = <unnamed> {
 }
 koKR = <unnamed> {
 }
 zhCN = <unnamed> {
 }
 ScanButton = <unnamed> {
 }
 VersionHeading = <unnamed> {
 }
 OptionsButton = <unnamed> {
 }
 DiscordLink = <unnamed> {
 }
 OpenOptions = <function> defined @Auctionator\Source\Tabs\Auctionator\Mixins\Main.lua:13
 tkTK = <unnamed> {
 }
 EngageHeading = <unnamed> {
 }
 ptBR = <unnamed> {
 }
 ruRU = <unnamed> {
 }
 OnLoad = <function> defined @Auctionator\Source\Tabs\Auctionator\Mixins\Main.lua:3
 itIT = <unnamed> {
 }
 Author = <unnamed> {
 }
 frFR = <unnamed> {
 }
 Contributors = <unnamed> {
 }
 esMX = <unnamed> {
 }
 ContributorsHeading = <unnamed> {
 }
 Version = <unnamed> {
 }
 esES = <unnamed> {
 }
 zhTW = <unnamed> {
 }
 TranslatorsHeading = <unnamed> {
 }
 BugReportLink = <unnamed> {
 }
 Bg = <unnamed> {
 }
}
(*temporary) = nil
(*temporary) = "Auctionator"
(*temporary) = "attempt to call field 'OpenToCategory' (a nil value)"

**Comment by plusmouse** [comment]
I put a fix in the next release
