### ISSUE TITLE
Post button stays greyed out, can't post auction. I talk to the auctioneer in undercity, auctionator opens, i go to selling, click my 102 bolts of mage weave, and the 5 stacks load and then the post button just never ungreys.

### ISSUE THREAD

**Issue by AW415T4D** [Auctionator/Auctionator#1243]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

_Please include a brief description of the bug, including what you were doing, and when it occurred._

## Steps to Reproduce

_Include the steps I would need to follow to reproduce the bug._

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by plusmouse** [comment]
Do you have enough gold to pay the deposit?

**Comment by plusmouse** [comment]
No response. Closing.
