### ISSUE TITLE
Auctionator will not load

### ISSUE THREAD

**Issue by Mecharossilla** [Auctionator/Auctionator#1244]
Please include as much of the following information as possible to help me fix the bug:

Auctionator doesn't load, playing WotLK.  

_Please include a brief description of the bug, including what you were doing, and when it occurred._

I get the following 6 Lua errors when I start the game:
Message: Error loading Interface\AddOns\Auctionator\Source\Dialogs.lua
Time: Tue Oct 25 18:23:19 2022
Count: 4

Message: Couldn't open Interface\AddOns\Auctionator\Source\Mixins\Manifest.xml
Time: Tue Oct 25 18:23:19 2022
Count: 4

Message: Couldn't open Interface\AddOns\Auctionator\Source\Templates.xml
Time: Tue Oct 25 18:23:19 2022
Count: 4

Message: Couldn't open Interface\AddOns\Auctionator\Source\Frames\Manifest.xml
Time: Tue Oct 25 18:23:19 2022
Count: 4

Message: Couldn't open Interface\AddOns\Auctionator\Source_Classic\Mixins\Manifest.xml
Time: Tue Oct 25 18:23:19 2022
Count: 4

Message: Couldn't open Interface\AddOns\Auctionator\Source_Classic\Frames\Manifest.xml
Time: Tue Oct 25 18:23:19 2022
Count: 4

As far as I can see in the folder structure, none of these files it's looking for exist.   I've tried downloading the classic, wrath, and retail versions and none work for me.  I've also cleared my cache.

## Loaded Addons

None, turned off all my other addons and it still doesn't work

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by plusmouse** [comment]
This is a Blizzard bug. Usually resolved by deleting and recreating your Interface folder that holds your addons.

**Comment by Mecharossilla** [comment]
Deleting and rebuilding the addon folder did not do it.  I'll look into other solutions and report back.

**Comment by Mecharossilla** [comment]
I deleted and rebuilt the Cache, WTF and AddOns folders and did a repair on the wow client and I'm still getting the same errors.

**Comment by Mecharossilla** [comment]
This is the ONLY addon that does this.  Whether I have any other addons in the folder or not.

**Comment by plusmouse** [comment]
@Mecharossilla Have you tried downloading Auctionator again, as the errors look like a corrupted download?

@KalmiaKamui Did you download the Wrath edition, as the prominent Curseforge download buttons can send you to the retail version https://www.curseforge.com/wow/addons/auctionator/files/4153626

**Comment by Mecharossilla** [comment]
Just downloaded the newest WOTLK version today and I'm still getting similar errors.

6x Couldn't open Auctionator\Source\v1\Manifest.xml
6x Couldn't open Auctionator\Source_Classic\v1\Manifest.xml
8x Error loading Auctionator\Source\Internal.lua

**Comment by plusmouse** [comment]
One user said that reinstalling wow fixed the issue for them, but I don't know why it did.

There's something broken, as the files the client is falling to load are stored at different locations than the errors state and there isn't be any code in the add-on to load them at the wrong place.

Can you screenshot the contents of the Auctionator/Source/Manifest.xml file?

**Comment by Mecharossilla** [comment]
<Ui xmlns="http://www.blizzard.com/wow/ui/">
  <Script file="Internal.lua" />

  <Include file="v1\Manifest.xml" />
</Ui>

**Comment by Mecharossilla** [comment]
"
<Ui xmlns="http://www.blizzard.com/wow/ui/">
  <Script file="Internal.lua" />

  <Include file="v1\Manifest.xml" />
</Ui>
"

**Comment by Mecharossilla** [comment]
...<Ui xmlns="http://www.blizzard.com/wow/ui/">
... <Script file="Internal.lua" />
...
...  <Include file="v1\Manifest.xml" />
...</Ui>

**Comment by Mecharossilla** [comment]
Post keeps leaving out part of the code...  but ya, I'm just using the default unzipper on my computer

**Comment by plusmouse** [comment]
How did you unzip the downloaded Auctionator file? It looks like the extraction went wrong and put files in the wrong place.

**Comment by Mecharossilla** [comment]
< Ui xmlns="http://www.blizzard.com/wow/ui/">
  < Script file="Internal.lua" />

  < Include file="v1\Manifest.xml" />
< /Ui>

**Comment by plusmouse** [comment]
The file at Auctionator/Source/Manifest.xml should look like this
```xml
<!-- Source directory manifest -->
<Ui xmlns="http://www.blizzard.com/wow/ui/">
  <Script file="Objects.lua" />
  <Script file="Locales\Main.lua" />
  <Include file="Constants\Manifest.xml" />

  <Include file="AH\Manifest.xml"/>

  <Include file="Components\Manifest.xml" />

  <Include file="Search\Manifest.xml" />

  <Include file="Utilities\Manifest.xml" />

  <Include file="Tooltips\Manifest.xml"/>

  <Include file="Variables\Manifest.xml" />
  <Include file="Database\Manifest.xml"/>

  <Include file="SlashCmd\Manifest.xml" />

  <Include file="Shopping\Manifest.xml" />
  <Include file="Config\Manifest.xml" />
  <Include file="Selling\Manifest.xml"/>
  <Include file="PostingHistory\Manifest.xml"/>

  <Include file="Cancelling\Manifest.xml"/>
  <Include file="CraftingInfo\Manifest.xml" />

  <Include file="Tabs\Manifest.xml" />
  <Include file="API\Manifest.xml" />

  <Include file="SplashScreen\Manifest.xml" />

  <Include file="Initialize\Manifest.xml" />
</Ui>
```

**Comment by Mecharossilla** [comment]
I guess maybe I don't extract them correctly.  I download them, open the compressed folder, cut the contents out and paste to the addon folder.   It's always worked for all the other addons.

**Comment by plusmouse** [comment]
Try copying rather than cut, it should work. Or drag-and-drop to the right place.

I don't know why its glitched with the Auctionator zip, as it uses a common build system that a lot of other addons use too.

**Comment by plusmouse** [comment]
You could try checking that particular file is right inside the zip?

**Comment by Mecharossilla** [comment]
So I used the Extract dialog and properly extracted instead of cut/paste.  That looks like it solved the problem, manifest file looks like yours and it loaded up in game.   Thanks for the help,  it's a great addon and I've been annoyed not to have it the last month.

**Comment by plusmouse** [comment]
I'm glad its fixed now. I now have a solution for the next user who reports that issue. You're not the first unfortunately, but at least that explains why redownloading the zip appeared to work in some cases, the user coincidentally used a different extraction method on the second/third time round.
