### ISSUE TITLE
A couple of QOL things.

### ISSUE THREAD

**Issue by lindenkron** [Auctionator/Auctionator#1246]
**Character specific options saving**
For example having the "Default shopping list" that opens be set per character, and not per account. I want enchanting to be main on my enchanter, not on my jewelcrafter. Changing it every time is cumbersome.

**Add item to shopping list**
There used to be a button (Fairly sure) that would add currently searched item to the current shopping list. This was a _lot_ easier and more intuitive than having to click "add item" to then type in the name that you already have open and searched.

**Remember previous extended search**
There's currently no way to search for your extended search easily refreshing it over and over. You have to type in the search parameters every time, a bit cumbersome. 

**Fix 'item level' searching**
Appears to be broken at the moment. Searching for 2-20 item level **quality** 'uncommon', yields 0 items. Even though there is plenty items. Doing the same using **Level** instead of **Item Level** works just fine.

Thanks for this addon. While it's hard to work around Blizzard sometimes, it's impressive how nice this addon makes classic AH.

**Comment by plusmouse** [comment]
1. **Character specific options saving**
You can do this, but it makes _every_ option specific to the current character:
![image](https://user-images.githubusercontent.com/60280559/198114174-20b640e1-7291-4c7b-8b11-8219eea8d299.png)
Probably not ideal though.

2. **Remember previous extended search**
All searches appear in the Recents list so you can click any one to redo it, that will include any extended search options. Added persisting the search in the search text box for editing later to my todo list.

3. **Add item to shopping list**
You can Shift+Click the Add Item button to add the current item in the search box to your shopping list, or use the copy icon in the recents list to copy to the currently active list.
![image](https://user-images.githubusercontent.com/60280559/198111966-5bd456ad-804c-400d-a5d2-b54a2b9b28d2.png)

4. **Fix 'item level' searching**
It isn't possible to do the 1 page query and always get item level results. The alternative is keeping the query going until a match is found, which could take a while - in the end I settled for the newest versions having this result if the search has more pages that might contain a wanted result, and a button to keep going:
![image](https://user-images.githubusercontent.com/60280559/198113897-abad73b3-09f7-46d6-b4c3-561bd04f5fc6.png)

---

I'd anticipate that the code resulting from both 2 and 3 would let me set it up so clicking the Add Item button puts the full search in the "Add Item" dialog, removing the usage of a Shift+Click

---

Thoughts?

**Comment by lindenkron** [comment]
1. Ah I see, this seems a little UX counter intuitive to me. It feels like this box should be checked by default. But it's hard for me to speak for other users. Good to know it's there though, checked it now.

2. I see. I rarely use the `Recent Searches` tab, so I was not aware of this. Good to know you're planning on persistence later, I think that's what'll come most natural to people. Perhaps keep last search in the searches 'Input field' (similar to how it shows it in the Recent Searches) so people can just press 'Search' button again - and it will search same again?

3. Same as above, I'm rarely on the `Recent Searches` tab, so I was not aware of this copy paste function. I was more expecting the "Add item" button to add the current specific search. Perhaps with a cogwheel next to it (Like the search cog wheel) that  would open the advanced item add feature. It would make sense since they both open the exact same menu UI.
![image](https://user-images.githubusercontent.com/6466136/198125932-baae6875-505d-4da5-bcc9-96534d7f2b0d.png)

4. That's unfortunate. I understand there's a lot of limitations imposed by Blizzard and it's not always easy to get solutions that are suitable. Not much I can say on that.

**Comment by lindenkron** [comment]
Also, holding shift does not provide the tooltips (I believe are from Auctionator as well) for disenchant materials inside of the auction house.

**In bags**
![image](https://user-images.githubusercontent.com/6466136/198227146-6220987b-d534-4582-a496-bfa9b907de39.png)


**In AH:**
![image](https://user-images.githubusercontent.com/6466136/198227073-a29cf98d-d802-4dab-9716-2c64d36233e5.png)

**Comment by plusmouse** [comment]
That's a quirk of the tooltip, if you start with Shift down before mousing over it it will show the disenchant materials.

Would you prefer the materials to be shown by default? I've already written an option for that, but haven't released it due to not being able to find a user that wants it and wants to test it.
![image](https://user-images.githubusercontent.com/60280559/198253992-3df527cb-f623-4c09-aced-cd0e8e5344a0.png)

**Comment by lindenkron** [comment]
It appears you're right.  Not sure I'd want it on at all times since it does take up some space for the break down. And other addons like RatingBuster doesn't allow your (very handy btw!) shift modifier.

Perhaps an option to always have it shown in AH to bypass the quirk? Or perhaps have that as default to bypass that. Not sure. I tested it, and it did indeed show the disenchant mats upon holding shift _prior_ to hovering over the item. Thanks.

**Comment by lindenkron** [comment]
Another small QOL thing that'd be nice. `Load more results` doesn't take `Extended search options` searches into consideration.

So if you search `Elemental` and `Common`, it'll show the cheapest common `elemental` available. If you still don't see them and press `Load More` it will load *everything*, uncommon, rare, epic - you name it. I don't see a way to load more items within your extended search parameter currently?

**Comment by plusmouse** [comment]
It does take it into consideration, but after testing it seems the Blizzard search APIs ignore the quality filter, which is what you're seeing:
![image](https://user-images.githubusercontent.com/60280559/198265968-a93069cb-f4f5-499d-ad71-113c1e9d65f7.png)

**Comment by plusmouse** [comment]
I've altered the Auctionator search code to double check the quality after the results arrive, so it won't show the other qualities when you specify one now (available from Curseforge when it finishes processing, or linked here)
[Auctionator-10.0.1-1-gb74c732-wrath.zip](https://github.com/Auctionator/Auctionator/files/9878700/Auctionator-10.0.1-1-gb74c732-wrath.zip)

**Comment by lindenkron** [comment]
Not sure if it changes anything, sorry for not being specific enough, but this was the "elemental" type of search I was referring to:
![image](https://user-images.githubusercontent.com/6466136/198272590-c2b31ea8-1225-480a-9d46-238d91f5afce.png)

And pressing `Load More` yields this:
![image](https://user-images.githubusercontent.com/6466136/198272704-af419836-d837-400d-bd1d-7783d62b001d.png)

I'll give the new version a test.

**Comment by lindenkron** [comment]
Thoughts on items being added to a list, being added to the top and not the bottom of a list? Would this be counter intuitive to people? I often find myself that adding an item, especially to a list that has a scroll bar (so it gets added at the bottom out of sight) can be disorientating and confusing since you just added something and expect to see it appear.

**Comment by plusmouse** [comment]
Its always been at the bottom. However I could probably change it so that it scrolls to the bottom of the list to show the new one?

**Comment by lindenkron** [comment]
I suppose that is a fair middle ground. Is there a way in the wow UI to have it scrolling while holding an item at the top of a list? I find myself dragging things from bottom to top (to have enchanting mats in order of their skill level) and losing where I dropped it off - because you have to drag drop scroll drag drop scroll to move things up.

Again, just minor QOL things :)

Thanks for the back and forth on this, appreciated.

**Comment by lindenkron** [comment]
I don't know if this is a addon thing, or where it gets the information from but this is incorrect:
![image](https://user-images.githubusercontent.com/6466136/198300732-00e12d03-f319-493b-b11d-f442a56e63ad.png)
![image](https://user-images.githubusercontent.com/6466136/198300785-d7d9c014-b404-43c5-9448-495dee91a8e3.png)

**Comment by lindenkron** [comment]
Don't think this is intended. Using the version you uploaded above.
![image](https://user-images.githubusercontent.com/6466136/198325943-6934cfd2-184e-4f90-80e6-eddaa04aed18.png)

**Comment by plusmouse** [comment]
1. The enchant data comes from a 2015/16 resource that no longer exists and computing new data (because of all the ilvl cutoffs) is difficult - but I'll add reviewing that to my todo list.
2. The search result is a side effect of making sure the "Load more results" button is enabled when no results were found on the first page.

**Comment by plusmouse** [comment]
Updates: In the latest alpha (available on Curseforge shortly) the list will now scroll to the bottom to show your new item.

**Comment by plusmouse** [comment]
Latest alpha has the remembering your last extended search so you can edit it. This completes the issue.
[Auctionator-10.0.8-7-g693b7c7-wrath.zip](https://github.com/Auctionator/Auctionator/files/9997490/Auctionator-10.0.8-7-g693b7c7-wrath.zip)

![image](https://user-images.githubusercontent.com/60280559/201528046-1642bf3a-49ed-4f5f-9e0b-461af7f47187.png)
![image](https://user-images.githubusercontent.com/60280559/201528057-31b2bacc-aca3-4129-b942-f62af37bf7dc.png)
