### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by nanjuekaien1** [Auctionator/Auctionator#1248]
...ns/Auctionator/Source_Mainline/CraftingInfo/Main.lua:64: attempt to index local 'recipeInfo' (a nil value)
Count: 3

Call Stack:
[string "=[C]"]: ?
[string "@Interface/AddOns/Auctionator/Source_Mainline/CraftingInfo/Main.lua"]:64: in function `GetSkillReagentsTotal'
[string "@Interface/AddOns/Auctionator/Source/CraftingInfo/Main.lua"]:25: in function <...face/AddOns/Auctionator/Source/CraftingInfo/Main.lua:24>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Auctionator/Source_Mainline/CraftingInfo/Mixins/Frame.lua"]:59: in function `UpdateTotal'
[string "@Interface/AddOns/Auctionator/Source_Mainline/CraftingInfo/Mixins/Frame.lua"]:13: in function <...onator/Source_Mainline/CraftingInfo/Mixins/Frame.lua:10>
[string "=[C]"]: in function `Init'
[string "@Interface/AddOns/Blizzard_Professions/Blizzard_ProfessionsCrafting.lua"]:621: in function `Init'
[string "@Interface/AddOns/Blizzard_Professions/Blizzard_ProfessionsCrafting.lua"]:213: in function <...lizzard_Professions/Blizzard_ProfessionsCrafting.lua:212>
[string "=[C]"]: ?
[string "@Interface/SharedXML/CallbackRegistry.lua"]:143: in function <Interface/SharedXML/CallbackRegistry.lua:142>
[string "=[C]"]: ?
[string "@Interface/SharedXML/CallbackRegistry.lua"]:146: in function `TriggerEvent'
[string "@Interface/AddOns/Blizzard_Professions/Blizzard_ProfessionsFrame.lua"]:112: in function `SetProfessionInfo'
[string "@Interface/AddOns/Blizzard_Professions/Blizzard_ProfessionsFrame.lua"]:80: in function <...s/Blizzard_Professions/Blizzard_ProfessionsFrame.lua:52>

**Comment by nanjuekaien1** [comment]
Odd? This error does not occur when changing the number

**Comment by plusmouse** [comment]
Added a fix into the next release
