### ISSUE TITLE
Region-wide commodities - consolidate history?

### ISSUE THREAD

**Issue by Veyska** [Auctionator/Auctionator#1249]
**Is your feature request related to a problem? Please describe.**
No problems per se, but it'd be nice to "share" pricing history for commodities across realms rather than doubling up on the data.

**Describe the solution you'd like**
Have commodities pricing history not be realm-specific in the addon, so scanning Random Ore on one server and then on a second the next day would show both values on both servers.

**Describe alternatives you've considered**
No real alternatives because it's a minor QoL upgrade not anything major.  If implementing it is too tricky to implement then no change from live.

**Comment by plusmouse** [comment]
Making this change would introduce unwanted complexity when converting between classic and retail versions of Auctionator. As such its not likely to be done anytime soon.
