### ISSUE TITLE
Issue on shopping lists and "search for all items" - sub for colons overwrites names with colons

### ISSUE THREAD

**Issue by ceylina** [Auctionator/Auctionator#125]
4.0.4

http://mods.curse.com/addons/wow/auctionator?comment=6034

> Since yesterday my search for profession plans, patterns and designs have been broken. It just return the searches in white text and with 0 instantly (doesnt even do the search).

![search_16](https://cloud.githubusercontent.com/assets/9342192/17047326/57c2a2be-4fa2-11e6-9c53-69104a381ef9.png)

**Comment by ceylina** [comment]
I put together a simple test shopping list with 

Design
Pattern
Plans

and this was the "search for all items" result. Not sure why the actual search names I chose return as "none available". Could it be this issue reported is that they manually search these items in a shopping list and doing a search for all items will return the actual name as none available before posting the search results?

This is the screen shot of my results

![wowscrnshot_072216_002431](https://cloud.githubusercontent.com/assets/9342192/17047356/bd8830d2-4fa2-11e6-9aa7-d5f156528281.jpg)

**Comment by jrob8577** [comment]
I think the shopping list works like the tradeskill search - the name of the list is included in the search, but I can look to confirm.  In the original image, it looks like our migration overwrote the user's colons to semicolons.  :P

**Comment by ceylina** [comment]
Yup, looks like the colon check also can overwrite shopping lists with only item names that contain colons but aren't advanced search strings. oops :O

**Comment by jrob8577** [comment]
Too excited about closing things, there's an additional issue here around searching for Design, Pattern, and Plans in above screenshot.

**Comment by ceylina** [comment]
I retested with latest test code and it works. Removed my initial comment in here
