### ISSUE TITLE
Alt-clicking to post an auction works only when combined bags is disabled. 

### ISSUE THREAD

**Issue by Kream** [Auctionator/Auctionator#1251]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

I used to be able to alt-click on an item to post it . Alt-clicking to post an auction still works, but only when combined bags is disabled. 

## Steps to Reproduce

Enable combined bags
Interact with an auctioneer
Alt-click an item in your inventory 

## Loaded Addons

Tested with zero addons other than Auctionator. 

## Back Trace (LUA Error Output)

No error seen. Fails silently.

**Comment by plusmouse** [comment]
Can you try this build?
[Auctionator-10.0.3-3-g828341d.zip](https://github.com/Auctionator/Auctionator/files/9895958/Auctionator-10.0.3-3-g828341d.zip)

**Comment by Kream** [comment]
Works!

**Comment by plusmouse** [comment]
Ok. I'll close this issue as completed. The fix is in the current alpha and will go in the next normal release.
