### ISSUE TITLE
When I click on an item from the bag I get this error message

### ISSUE THREAD

**Issue by Rubyurek** [Auctionator/Auctionator#1253]
Please include as much of the following information as possible to help me fix the bug:

When I click on an item from the bag I get this error message

## Loaded Addons

Auctionator
BtwLoadouts
Buggrabber
Bugsack
DeModal
Details!
Immersion
Krowi's achievement Filter
Leatrix Maps
Leatrix Plus
LFGSpamFilter
LS: Toasts
OmniCC
Simulationcraft
TL:DR Missions
WeakAuras

## Back Trace (LUA Error Output)

1x [ADDON_ACTION_FORBIDDEN] AddOn 'Auctionator' hat versucht die geschützte Funktion 'UNKNOWN()' aufzurufen.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: ?
[string "=[C]"]: in function `UseContainerItem'
[string "@Interface/FrameXML/ContainerFrame.lua"]:1384: in function <Interface/FrameXML/ContainerFrame.lua:1294>
[string "=[C]"]: in function `ContainerFrameItemButton_OnClick'
[string "@Interface/FrameXML/ContainerFrame.lua"]:1435: in function <Interface/FrameXML/ContainerFrame.lua:1423>

**Comment by plusmouse** [comment]
Fixed in the latest alpha 
[Auctionator-10.0.3-10-g6dec85e.zip](https://github.com/Auctionator/Auctionator/files/9908150/Auctionator-10.0.3-10-g6dec85e.zip)
