### ISSUE TITLE
Right click on item to open selling tab bug

### ISSUE THREAD

**Issue by zeenk** [Auctionator/Auctionator#1254]
Noticed this bug when I was relisting some auctions, if you have bagnon disabled it doesn't open the selling tab when you right click an item in ur bag even if u have it enabled to do so, it goes to default sell tab instead, it works however if u have bagnon enabled.

Bagnon disabled:

https://user-images.githubusercontent.com/68170439/199098407-3ad26c73-8ba8-4350-ae11-72464969cbbd.mp4

Bagnon enabled:

https://user-images.githubusercontent.com/68170439/199098455-04996b3f-366a-4036-92e8-5af3b4564c59.mp4

**Comment by zeenk** [comment]
Hmm, odd. I tried the same thing on another character with disabling Bagnon and it was working fine on that char, so not sure what caused this 😕

**Comment by plusmouse** [comment]
Can you think of any settings that might be different between them affecting the bag?

**Comment by plusmouse** [comment]
I've had another user have the shortcut inexplicably not work, as it hasn't broken for me its hard to test and fix (at least until I find the combination of stuff that breaks it)

**Comment by zeenk** [comment]
I tried it on same character again as the videos above, and now it's working with bagnon disabled wtf .. I didn't change anything 🤔 just a relog

**Comment by zeenk** [comment]
![2022-10-31_21-20-45](https://user-images.githubusercontent.com/68170439/199102836-2fe8458d-c9fa-480f-994e-635bfa32739b.jpg)

I also got it on this next character which also had bagnon disabled when I logged in, after I enabled bagnon it went back to normal again.

**Comment by plusmouse** [comment]
There's definitely something weird with the bags - been having a taint issue with them today.

**Comment by plusmouse** [comment]
Replicated the bug on my device and found a fix. Available in the latest alpha (and will go out in the next normal release) 
[Auctionator-10.0.3-11-g0ecf0c7.zip](https://github.com/Auctionator/Auctionator/files/9908921/Auctionator-10.0.3-11-g0ecf0c7.zip)
