### ISSUE TITLE
Conflict with GW2 UI - unable to post auctions

### ISSUE THREAD

**Issue by idominic18** [Auctionator/Auctionator#1255]
23x ...r/Source_Mainline/Utilities/ItemInfoFromLocation.lua:10: attempt to index local 'itemInfo' (a number value)
[string "@Interface/AddOns/Auctionator/Source_Mainline/Utilities/ItemInfoFromLocation.lua"]:10: in function `ItemInfoFromLocation'
[string "@Interface/AddOns/Auctionator/Source/Tabs/DataProviders/Bag.lua"]:67: in function `LoadBagData'
[string "@Interface/AddOns/Auctionator/Source/Tabs/DataProviders/Bag.lua"]:13: in function `Reload'
[string "@Interface/AddOns/Auctionator/Source/Tabs/DataProviders/Bag.lua"]:33: in function <...AddOns/Auctionator/Source/Tabs/DataProviders/Bag.lua:29>
[string "=[C]"]: in function `Show'
[string "@Interface/AddOns/Blizzard_AuctionHouseUI/Blizzard_AuctionHouseFrame.lua"]:611: in function <...izzard_AuctionHouseUI/Blizzard_AuctionHouseFrame.lua:571>
[string "=[C]"]: in function `?'
[string "@Interface/SharedXML/FunctionUtil.lua"]:15: in function `CallMethodOnNearestAncestor'
[string "@Interface/AddOns/Blizzard_AuctionHouseUI/Blizzard_AuctionHouseTab.lua"]:24: in function <...Blizzard_AuctionHouseUI/Blizzard_AuctionHouseTab.lua:23>

Locals:
location = <table> {
 Clear = <function> defined @Interface/FrameXML/ObjectAPI/ItemLocation.lua:29
 IsEquipmentSlot = <function> defined @Interface/FrameXML/ObjectAPI/ItemLocation.lua:56
 IsEqualToBagAndSlot = <function> defined @Interface/FrameXML/ObjectAPI/ItemLocation.lua:72
 SetBagAndSlot = <function> defined @Interface/FrameXML/ObjectAPI/ItemLocation.lua:35
 IsBagAndSlot = <function> defined @Interface/FrameXML/ObjectAPI/ItemLocation.lua:60
 SetEquipmentSlot = <function> defined @Interface/FrameXML/ObjectAPI/ItemLocation.lua:46
 slotIndex = 1
 HasAnyLocation = <function> defined @Interface/FrameXML/ObjectAPI/ItemLocation.lua:64
 bagID = 0
 GetEquipmentSlot = <function> defined @Interface/FrameXML/ObjectAPI/ItemLocation.lua:52
 IsEqualToEquipmentSlot = <function> defined @Interface/FrameXML/ObjectAPI/ItemLocation.lua:80
 GetBagAndSlot = <function> defined @Interface/FrameXML/ObjectAPI/ItemLocation.lua:42
 IsValid = <function> defined @Interface/FrameXML/ObjectAPI/ItemLocation.lua:68
 IsEqualTo = <function> defined @Interface/FrameXML/ObjectAPI/ItemLocation.lua:88
}
itemKey = <table> {
 itemLevel = 1
 itemSuffix = 0
 itemID = 6948
 battlePetSpeciesID = 0
}
itemType = 1
icon = nil
itemCount = nil
quality = nil
itemLink = nil
_ = nil
itemInfo = 134414
(*temporary) = 0
(*temporary) = 1
(*temporary) = 134414
(*temporary) = 1
(*temporary) = false
(*temporary) = 1
(*temporary) = false
(*temporary) = false
(*temporary) = "|cffffffff|Hitem:6948::::::::60:72:::::::::|h[Hearthstone]|h|r"
(*temporary) = false
(*temporary) = "attempt to index local 'itemInfo' (a number value)"

**Comment by plusmouse** [comment]
I've tested GW2 (beta). This is a bug with GW2, as it adds its own function for the API `C_Container.GetItemInfo` - which pretends to be the Blizzard function while returning different results to the real `C_Container.GetItemInfo` on the Dragonflight beta. Auctionator checks for the function's existence and if it exists tries to use it with the correct return values. You'll need to contact the developers of GW2 to fix this.

For reference, this is what the function _should_ do:
![image](https://user-images.githubusercontent.com/60280559/199429554-44306256-2b4c-414c-8e69-06335899c9a2.png)
