### ISSUE TITLE
Number display on history of items broken

### ISSUE THREAD

**Issue by Quantifyblue** [Auctionator/Auctionator#1256]
Please include as much of the following information as possible to help me fix the bug:

**Any item searched has their price history numbers garbled.**

_Please include a brief description of the bug, including what you were doing, and when it occurred._

**View the price history of any item searched on the AH.**

_Include the steps I would need to follow to reproduce the bug._

**Search any item and then switch to the history tab.**

## Loaded Addons

**Advanced Interface options
AtlastLootClassic
ClassicCastBars
ClassicSpellActivations
Details! Dmg Meter
GTFO
ItemRack
Leatrix Maps
Leatrix Plus
LoseControl
NamePlatesThreat
Nova Instance Tracker 
OmniCC
Questie
SafeQueue
SpellNotifications
TacoTip
TomTom
tullaRange
Deadly Moss Mods
Bagnon**

## Back Trace (LUA Error Output)

**No Errors**

Screenshot:
![WoWScrnShot_110222_082403](https://user-images.githubusercontent.com/117281176/199490450-6a45da10-8929-47ad-92f8-11b06107c144.jpg)

**Comment by plusmouse** [comment]
Which version of Auctionator are you on?

**Comment by Quantifyblue** [comment]
10.0.0.4 
The latest one available on curse. Problem began this morning after update

**Comment by plusmouse** [comment]
Can you try this alpha build - it contains a fix for the problem:
[Auctionator-10.0.4-1-g75b65ae-wrath.zip](https://github.com/Auctionator/Auctionator/files/9920701/Auctionator-10.0.4-1-g75b65ae-wrath.zip)

**Comment by Quantifyblue** [comment]
Yes! All fixed, thank you very much. Your addon has great functionality - I can recommend it to anyone.
