### ISSUE TITLE
Undercut Scan shows no items

### ISSUE THREAD

**Issue by Tryko1** [Auctionator/Auctionator#1259]
Please include as much of the following information as possible to help me fix the bug:

Undercut scan startet and let all postet items disapear. Need to Reload UI. Happens since last update.

https://gyazo.com/7be4425e9077aeef96c7232aa6d072b9

_Please include a brief description of the bug, including what you were doing, and when it occurred._

## Steps to Reproduce

Happens sometimes, while scan active and start scrolling. Not on every scan.

!BugGrabber
Altoholic
Altoholic_Achievements
Altoholic_Agenda
Altoholic_Characters
Altoholic_Grids
Altoholic_Guild
Altoholic_Search
Altoholic_Summary
AtlasLootClassic
AtlasLootClassic_Collections
AtlasLootClassic_Crafting
AtlasLootClassic_Data
AtlasLootClassic_DungeonsAndRaids
AtlasLootClassic_Factions
AtlasLootClassic_Options
AtlasLootClassic_PvP
Auctionator
BigDebuffs
BigWigs
BigWigs_AhnQirajRuins
BigWigs_AhnQirajTemple
BigWigs_BlackTemple
BigWigs_BlackwingLair
BigWigs_Core
BigWigs_Hyjal
BigWigs_Karazhan
BigWigs_MoltenCore
BigWigs_Options
BigWigs_Outland
BigWigs_Plugins
BigWigs_Serpentshrine
BigWigs_Sunwell
BigWigs_TempestKeep
BigWigs_World
BigWigs_WrathOfTheLichKing
BigWigs_ZulAman
BigWigs_ZulGurub
BugSack
Capping
Capping_Options
DataStore
DataStore_Achievements
DataStore_Agenda
DataStore_Auctions
DataStore_Characters
DataStore_Containers
DataStore_Crafts
DataStore_Inventory
DataStore_Mails
DataStore_Quests
DataStore_Reputations
DataStore_Spells
DataStore_Talents
Details
Details_DataStorage
Details_EncounterDetails
Details_RaidCheck
Details_Streamer
Details_TinyThreat
Details_Vanguard
Doom_CooldownPulse
ElvUI
ElvUI_OptionsUI
ExRT
FarmHud
FarmHud_QuestArrow
FarmHud_TrailPath
1FasterLooting
Gladdy
GladiatorlosSA2
LittleWigs
LittleWigs_BattleForAzeroth
LittleWigs_BurningCrusade
LittleWigs_Cataclysm
LittleWigs_Classic
LittleWigs_Legion
LittleWigs_MistsOfPandaria
LittleWigs_WarlordsOfDraenor
LittleWigs_WrathOfTheLichKing
LoseControl
MikScrollingBattleText
MRT
MSBTOptions
OmniBar
OmniCD
Pawn
Plater
Questie
RaidRoll
RareScanner
RXPGuides
sArena
SharedMedia
SharedMedia_MyMedia
Skillet-Classic
WeakAuras
WeakAurasArchive
WeakAurasModelPaths
WeakAurasOptions
WeakAurasTemplates
WhatsTraining

_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

2x ...s\ResultsListing\Mixins\CancellingListResultsRow.lua:44: attempt to index field 'rowData' (a nil value)
[string "@Auctionator\Source_Classic\Tabs\ResultsListing\Mixins\CancellingListResultsRow.lua"]:44: in function `ApplyFade'
[string "@Auctionator\Source_Classic\Tabs\ResultsListing\Mixins\CancellingListResultsRow.lua"]:38: in function `Populate'
[string "@Auctionator\Source\Components\ResultsListing\Mixins\ResultsListing.lua"]:15: in function <...\Components\ResultsListing\Mixins\ResultsListing.lua:14>
[string "@SharedXML\Scroll\ScrollBoxListView.lua"]:288: in function `frameFactory'
[string "@SharedXML\Scroll\ScrollBoxListView.lua"]:217: in function `AcquireInternal'
[string "@SharedXML\Scroll\ScrollBoxListView.lua"]:250: in function `AcquireRange'
[string "@SharedXML\Scroll\ScrollBoxListView.lua"]:503: in function `Rebuild'
[string "@SharedXML\Scroll\ScrollBoxListView.lua"]:562: in function `ValidateDataRange'
[string "@SharedXML\Scroll\ScrollBox.lua"]:613: in function `Update'
[string "@SharedXML\Scroll\ScrollBox.lua"]:219: in function `SetScrollPercentageInternal'
[string "@SharedXML\Scroll\ScrollBox.lua"]:211: in function `SetScrollPercentage'
[string "@SharedXML\Scroll\ScrollController.lua"]:70: in function `ScrollInDirection'
[string "@SharedXML\Scroll\ScrollBox.lua"]:185: in function `ScrollInDirection'
[string "@SharedXML\Scroll\ScrollController.lua"]:61: in function <SharedXML\Scroll\ScrollController.lua:59>

Locals:
self = <unnamed> {
 NormalTexture = <unnamed> {
 }
 OnEnter = <function> defined @Auctionator\Source_Classic\Tabs\ResultsListing\Mixins\CancellingListResultsRow.lua:25
 HighlightTexture = <unnamed> {
 }
 ElementDataMatches = <function> defined @SharedXML\Scroll\ScrollBoxListView.lua:6
 cells = <table> {
 }
 SetOrderIndex = <function> defined @SharedXML\Scroll\ScrollBoxListView.lua:15
 OnClick = <function> defined @Auctionator\Source_Classic\Tabs\ResultsListing\Mixins\CancellingListResultsRow.lua:3
 GetElementData = <function> defined @SharedXML\Scroll\ScrollBoxListView.lua:2
 ApplyHighlight = <function> defined @Auctionator\Source_Classic\Tabs\ResultsListing\Mixins\CancellingListResultsRow.lua:51
 dataIndex = 22
 Populate = <function> defined @Auctionator\Source_Classic\Tabs\ResultsListing\Mixins\CancellingListResultsRow.lua:35
 OnLeave = <function> defined @Auctionator\Source_Classic\Tabs\ResultsListing\Mixins\CancellingListResultsRow.lua:31
 GetOrderIndex = <function> defined @SharedXML\Scroll\ScrollBoxListView.lua:11
 SelectedHighlight = <unnamed> {
 }
 0 = <userdata>
 ApplyFade = <function> defined @Auctionator\Source_Classic\Tabs\ResultsListing\Mixins\CancellingListResultsRow.lua:42
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'rowData' (a nil value)"

**Comment by plusmouse** [comment]
Fixed in the latest alpha (available from Curseforge shortly)

[Auctionator-10.0.5-7-g34ee2c5-wrath.zip](https://github.com/Auctionator/Auctionator/files/9926515/Auctionator-10.0.5-7-g34ee2c5-wrath.zip)

**Comment by plusmouse** [comment]
Fixed in the newest alpha
[Auctionator-10.0.5-8-g452e3db-wrath.zip](https://github.com/Auctionator/Auctionator/files/9926561/Auctionator-10.0.5-8-g452e3db-wrath.zip)

**Comment by Tryko1** [comment]
Solved, can't reproduce. Perfect.
