### ISSUE TITLE
Show split panel view between current prices and historical prices.

### ISSUE THREAD

**Issue by Tacailfe** [Auctionator/Auctionator#1260]
split panel option on selling tab is not functioning.

**Comment by plusmouse** [comment]
Did you reload after changing the option?
![image](https://user-images.githubusercontent.com/60280559/199833416-664661cd-0a57-4a64-9961-360b1db6fc24.png)

**Comment by Tacailfe** [comment]
i did not. and after doing so all is good....thanks.

**Comment by plusmouse** [comment]
Great
