### ISSUE TITLE
Add 'cost to post' under 'crafting cost' and 'profit' in crafting window.

### ISSUE THREAD

**Issue by Hedjman** [Auctionator/Auctionator#1261]
**Is your feature request related to a problem? Please describe.**
I've noticed that if the profit is a few gold, and I'm looking to make some, I don't easily know the listing cost of the item. Sometimes it can take a few listing before an item has lost all its profit to that cost.

**Describe the solution you'd like**
I would like another line added under Profit in the crafting window that simply lists the cost of listing a single item on the auction house.

**Comment by plusmouse** [comment]
The deposit value isn't accessible for addons when the Auction House is closed or when the item is not currently selected for posting. Its not possible, and the formula for the deposit calculation based on the vendor price isn't known.
