### ISSUE TITLE
shopping scam

### ISSUE THREAD

**Issue by joni132** [Auctionator/Auctionator#1262]
Please include as much of the following information as possible to help me fix the bug:

i was shopping enchanting mats for lowest prices and  i paid 4k gold extra for some item which i was not shown
_Please include a brief description of the bug, including what you were doing, and when it occurred._

## Steps to Reproduce

_Include the steps I would need to follow to reproduce the bug._

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by plusmouse** [comment]
1. Was this with the Auctionator Shopping/Selling interface?
2. Did Auctionator report the price paid accurately? (after purchase)
3. Which item specifically was it?
4. Did you use the Chain Buy feature?
5. And if you do use the chain buy feature did the warning appear about a price spike?

**Comment by joni132** [comment]
yes auctionator 
price was chain buy 
it was enchanting mats which are alot of at low price i used the chain buy  anyway ggs

**Comment by plusmouse** [comment]
Is there anything that would have helped avoid the issue?

**Comment by plusmouse** [comment]
No response. Closing.
