### ISSUE TITLE
Shopping: Shortcut not working

### ISSUE THREAD

**Issue by godnoble** [Auctionator/Auctionator#1263]
## Brief Description of Bug

Holding Alt and left-clicking an item in my back while the AH is open does nothing.

## Steps to Reproduce

Go to Auction House, hold Alt, left click something auctionable.

## Loaded Addons

AdonFactory, AllTheThings, Altoholic, Auctionator, Bartender4, Battle Pet Battle UI Tweaks, BeStride, CandyButckets, ChampionCommander, Cross RP, DataStore, Decursive, Details!, DropTheCheapestThing, Elkano's BuffBars, Emote Splitter, GarrisonCommander, HandyNotes, Listener, Master Plan, Mik's Scrolling Battle Text, MinimapButtonBag, MogIt, Mythic Dungeon Tools, Ny's To Do List, OrderHallCommander, PetTracker, Postal, Protoform Synthesis Field Journal, Rematch, Sick of Clicking Dailies, Simulationcraft, TomTom, Tongues, Total RP 3, Venture Plan, War Plan, WeakAuras, Deadly Boss Mods

## Back Trace (LUA Error Output)

I do not have this.

**Comment by plusmouse** [comment]
Try disabling to MogIt and try again

**Comment by godnoble** [comment]
Thanks so much!
