### ISSUE TITLE
Feature Request: Green text in cancelling tab if active bid & a cancel warning.

### ISSUE THREAD

**Issue by zeenk** [Auctionator/Auctionator#1268]
Just a minor detail suggestion, could we possibly get a green color on auctions that have an active bid on the item like the default auctions tab has? Just to make it easier to spot auctions with active bids so you don't accidentally click on one while cancelling other auctions that are about to expire soon that has not been undercut yet. I know the addon ignores it when you cancel scan but it would help to see it better :)
![2022-11-09_21-17-21](https://user-images.githubusercontent.com/68170439/200933969-1c531c8e-db3e-492c-a375-a87afeb8262f.png)
![2022-11-09_21-16-42](https://user-images.githubusercontent.com/68170439/200933981-821aa898-4a96-4f93-b9c9-2bb485686519.png)

Also, could this default ah feature be added to Auctionator (maybe as an option) for items that has bids so if u accidentally clicked on a bid item it doesn't auto cancel and you lose a bunch of extra gold.

![2022-11-09_21-18-06](https://user-images.githubusercontent.com/68170439/200935164-4cfccd1d-830f-43e7-a198-bfd481f0c501.png)

**Comment by plusmouse** [comment]
I've added a warning dialog to avoid accidentally cancelling auctions with bids on them. Find it in the newest alpha (after it finishes building and processing)
