### ISSUE TITLE
Checking for Undercuts Error

### ISSUE THREAD

**Issue by matilley** [Auctionator/Auctionator#127]
## Brief Description of Bug

Strange output to chat window when checking for undercuts:

 <Auctionator> Error: scn.itemQuality == nil, scn.itemName:  Archer's Crossbow of the Bandit
 <Auctionator> Error: scn.itemQuality == nil, scn.itemName:  Boblet's Bouncing Hauberk
 <Auctionator> Error: scn.itemQuality == nil, scn.itemName:  Chunk o' Basilisk
 <Auctionator> Error: scn.itemQuality == nil, scn.itemName:  Coldsinger Amulet of the Aurora
 <Auctionator> Error: scn.itemQuality == nil, scn.itemName:  Darkmoon Firewater
 <Auctionator> Error: scn.itemQuality == nil, scn.itemName:  Diamond Hammer
 <Auctionator> Error: scn.itemQuality == nil, scn.itemName:  Dreamsinger Legguards
 <Auctionator> Error: scn.itemQuality == nil, scn.itemName:  Elegant Dress
 <Auctionator> Error: scn.itemQuality == nil, scn.itemName:  Gaarn's Leggings of Infestation
 <Auctionator> Error: scn.itemQuality == nil, scn.itemName:  Galardell Shoulderpads of the Invoker
 <Auctionator> Error: scn.itemQuality == nil, scn.itemName:  Holy Diadem
 <Auctionator> Error: scn.itemQuality == nil, scn.itemName:  Longclaw Gun of the Feverflare
 <Auctionator> Error: scn.itemQuality == nil, scn.itemName:  Necropolis Breastplate of the Seer
 <Auctionator> Error: scn.itemQuality == nil, scn.itemName:  Prismatic Scale
 <Auctionator> Error: scn.itemQuality == nil, scn.itemName:  Spring Rabbit's Foot
 <Auctionator> Error: scn.itemQuality == nil, scn.itemName:  Steppe Legguards of the Undertow
 <Auctionator> Error: scn.itemQuality == nil, scn.itemName:  Unknown Archaeologist's Hammer
 <Auctionator> Error: scn.itemQuality == nil, scn.itemName:  Whisper Shoulders of the Monkey

_Please include a brief description of the bug, including what you were doing, and when it occurred._

Just after full scan, hit 'check for undercuts'.

_Include a list of addons you were running at the time this bug occurred._

_NPCScan
Auctionator
CT_Core
CT_Library
CT_MailMod
Fishing Buddy
Gathermate2
Gathermate2Data
Master Plan
Master Plan A
Skada
WoWDBProfiler
Wowhead Looter
AddOnSkins
ElvUI Config
ElvUI
ElvUI Shadow & Light
Deadly Boss Mods (All)

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by ceylina** [comment]
Looks like you have debug enabled in the basic options settings. Make sure that is unchecked - "Enable debug mode". Simply uncheck that if checked.

**Comment by matilley** [comment]
A good guess: It is unchecked, and errors still occurring.

**Comment by ceylina** [comment]
Had a chance to look into this today. Looks like if there is a section of the scan code that is outputting that if the item's quality (such as uncommon, rare, etc) is not returned. I will raise this and see what we can do.

**Comment by jrob8577** [comment]
Thanks @ceylina and @matilley - this is older output code, I'll replace it with the new Debug messaging.
