### ISSUE TITLE
Automatic pricing for the item

### ISSUE THREAD

**Issue by RayabDeveloper27** [Auctionator/Auctionator#1270]
In crowded servers like Gehennas, the number of players who put an item in the AH is very high.
This is if automatic pricing takes place according to the price of each item and Cooper reduces the price of the previous one.
The problem is that after a very short period of time, the price of the item is very low, and this is a very serious problem.
If you just display the price of each item and according to a calculation, subtract the price based on the total Stack and minus one Cooper, this problem will be solved.
In general, remove item-based pricing altogether and let stack-based pricing be calculated.

**Comment by plusmouse** [comment]
Switching to stack based pricing would only slow down the price decreases, rather than eliminate them?

**Comment by RayabDeveloper27** [comment]
Switching to stack-based pricing would only slow down the price decreases, rather than eliminate them.


Look at some items in AH, For example, an Item "Unit Price" is 1g 49s 86c, Then a stack of that item is 29g 97s 20c.
Now the next player puts a new item there and your addons set the price like this:
"Unit Price": 1g 49s 85c
"Stack Price": 1g 49s 65c

This is not good for busy realms, Why is 20c reduced when can reduce only 1c and order that by "Stack Price"?
I/we just want to sell our items ASAP.

I have seen many times that in our server, an item has decreased in price by more than 2 gold after 1 hour, without anyone changing the price manually, and this was only because of AddOns.

**Comment by RayabDeveloper27** [comment]
I'm just saying change the auto pricing like this.
If someone wants to manually change the price in any way, there is no problem.
But most players only change the price automatically and this process causes the price to drop in the fastest time.

**Comment by plusmouse** [comment]
The change would confuse users when their unit price _looks_ like its not undercutting the competition, and the expected behaviour is to undercut on the unit price (and has been for a long time).
