### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Imna1975** [Auctionator/Auctionator#1271]
3x ...Auctionator/Source_Mainline/Selling/UniqueBagKey.lua:2: attempt to concatenate field 'quality' (a nil value)
[string "@Interface/AddOns/Auctionator/Source_Mainline/Selling/UniqueBagKey.lua"]:2: in function <...Auctionator/Source_Mainline/Selling/UniqueBagKey.lua:1>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Auctionator/Source/Tabs/DataProviders/Bag.lua"]:68: in function `LoadBagData'
[string "@Interface/AddOns/Auctionator/Source/Tabs/DataProviders/Bag.lua"]:13: in function `Reload'
[string "@Interface/AddOns/Auctionator/Source/Tabs/DataProviders/Bag.lua"]:33: in function <...AddOns/Auctionator/Source/Tabs/DataProviders/Bag.lua:29>
[string "=[C]"]: in function `Show'
[string "@Interface/AddOns/Auctionator/Libs_Mainline/LibAHTab/LibAHTab.lua"]:97: in function `SetSelected'
[string "@Interface/AddOns/Auctionator/Libs_Mainline/LibAHTab/LibAHTab.lua"]:67: in function <...dOns/Auctionator/Libs_Mainline/LibAHTab/LibAHTab.lua:66>

Locals:
entry = <table> {
 itemKey = <table> {
 }
 itemType = 0
 auctionable = false
 classId = 7
 count = 54
 location = <table> {
 }
 itemLink = "|cffffffff|Hitem:172231::::::::22:262:::::::::|h[]|h|r"
 iconTexture = 3528446
}
(*temporary) = "172231 0 0 0"
(*temporary) = " "
(*temporary) = nil
(*temporary) = " "
(*temporary) = "0"
(*temporary) = " "
(*temporary) = "attempt to concatenate field 'quality' (a nil value)"

**Comment by plusmouse** [comment]
Fixed in the latest alpha
[Auctionator-10.0.10-2-gadd9fd8.zip](https://github.com/Auctionator/Auctionator/files/10020767/Auctionator-10.0.10-2-gadd9fd8.zip)
