### ISSUE TITLE
"Auctionator attempted to call a protected function (Search())" according to swatter, this causes Groupfinder to hang.

### ISSUE THREAD

**Issue by sedfvrzg** [Auctionator/Auctionator#1279]
Date: 2022-11-25 00:11:30
ID: 2
Error occured in: AddOn: Auctionator
Count: 1
Message: Warning: AddOn Auctionator attempted to call a protected function (Search()) which may require interaction.
Debug:
   [string "=[C]"]: Search()
   [string "@Blizzard_LookingForGroupUI\Blizzard_LFGBrowse.lua"]:225: LFGBrowse_DoSearch()
   [string "@Blizzard_LookingForGroupUI\Blizzard_LFGBrowse.lua"]:178: SearchActiveEntry()
   [string "@Blizzard_LookingForGroupUI\Blizzard_LFGParentFrame.lua"]:92: LFGParentFrame_SearchActiveEntry()
   [string "@Blizzard_LookingForGroupUI\Blizzard_LFGListing.lua"]:67:
      ...s\Blizzard_LookingForGroupUI\Blizzard_LFGListing.lua:49
Locals:
None
AddOns:
  Swatter, v2.5.6773 (SwimmingSeadragon)
  AtlasLootClassic, vv3.0.7
  AtlasLootClassicData, vv3.0.7
  AtlasLootClassicDungeonsAndRaids, vv3.0.7
  Auctionator, v10.0.14
  BagBrother, v
  Bagnon, v10.0.3
  Bistooltip, v6.8
  DBMChamberOfAspects, v0812bef
  DBMCore, v5b00279
  DBMStatusBarTimers, v5b00279
  DBMVPVEM, v0dab85c
  Details, v#Details.DF.Wrath.10259.146
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  FarmHud, v9.0.9-release
  FarmHudQuestArrow, v9.0.9-release
  FarmHudTrailPath, v9.0.9-release
  GatherMate2, v1.46.3-classic
  ItemRack, v
  LootReserve, v2022-10-10-2
  MinimapButtonButton, v1.8.2
  NPCTime, v1.0.8
  Plater, vPlater-v537.1-Wrath
  Questie, v7.4.5
  RareScanner, v3.4.0.2
  RXPGuides, vv4.3.19
  SilverDragon, vv30400.1
  SilverDragonBurningCrusade, vv30400.1
  SilverDragonClassic, vv30400.1
  SilverDragonWrath, vv30400.1
  SpeedyAutoLoot, v2.1.6
  TacoTip, v0.2.7
  WeakAuras, v5.2.0
  WowSimsExporter, v2.3
  BlizRuntimeLib_enUS v3.4.0.30400 <none>
  (ck=41f)

**Comment by plusmouse** [comment]
Has this happened often?

If this is easily repeatable can do run `/console taintLog 1` and then `/reload` and trigger the bug. Then close WoW and post the `[Wow Directory]/_classic_/Logs/taint.log` file here.
