### ISSUE TITLE
Better placing elements at sell page

### ISSUE THREAD

**Issue by esvarc** [Auctionator/Auctionator#128]
I'm reopening old issue. After migration there is same problem as in pre 7.0.3 version. See attached pictures and patch file.

![auctionator-with-overlaping-frame](https://cloud.githubusercontent.com/assets/6427670/17076688/f3e432c2-50b8-11e6-83fc-577fdbce54db.jpg)

![auctionator-elements-ok](https://cloud.githubusercontent.com/assets/6427670/17076686/e980b1fc-50b8-11e6-84a2-620d0d4e52c1.jpg)

[sell-diff.txt](https://github.com/Auctionator/Auctionator/files/379429/sell-diff.txt)

**Comment by ceylina** [comment]
Thank you for re-reporting this. I've proposed a change to better align that button

**Comment by ceylina** [comment]
sell.xml

line 375

change *x and y coordinates) to

`           <Anchors><Anchor point="TOPLEFT"><Offset><AbsDimension x="5" y="-153"/></Offset></Anchor></Anchors>`

**Comment by jrob8577** [comment]
This is actually an issue with another addon?  @esvarc Can I get a list of the addons you're running along with Auctionator when this occurs?  I suspect an Auctionator skin that someone else maintains is doing this, and would like to narrow it down and reach out to them to have them udpate.
