### ISSUE TITLE
Allow Auctionator to shop for items on the Tradeskillmaster Gathering "Buy from AH" section.

### ISSUE THREAD

**Issue by Kream** [Auctionator/Auctionator#1280]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I love using Auctionator but Tradeskillmaster's recipe / crafting stuff is invaluable. The shopping functionality in TSM is so slow and broken it makes me want to pull my hair out. I'd like a function in Auctionator that generates a shopping list from the Tradeskillmaster Gathering "Buy from AH" section so I can efficiently purchase the items I need.

**Describe alternatives you've considered**
Quitting wow. In all seriousness, this would just be awesome.

**Comment by plusmouse** [comment]
This would be best as a separate addon that does a search in Auctionator by scanning the TSM stuff.
