### ISSUE TITLE
AddOn 'Auctionator' tried to call the protected function 'UNKNOWN()'

### ISSUE THREAD

**Issue by kev22257** [Auctionator/Auctionator#1281]
Please include as much of the following information as possible to help me fix the bug:

## Are you on the retail or the classic version of WoW?
Retail

## Is this a bug or a feature request?
Bug

# Bug:
## Brief Description of Bug
This happens frequently when I use items in my bags.  Reloading the UI allows using the same item, so I'm not sure exactly what re-creates the issue.

## Back Trace (LUA Error Output)
5x [ADDON_ACTION_FORBIDDEN] AddOn 'Auctionator' tried to call the protected function 'UNKNOWN()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: ?
[string "=[C]"]: in function `UseContainerItem'
[string "@FrameXML/ContainerFrame.lua"]:1409: in function <FrameXML/ContainerFrame.lua:1318>
[string "=[C]"]: in function `ContainerFrameItemButton_OnClick'
[string "@FrameXML/ContainerFrame.lua"]:1461: in function <FrameXML/ContainerFrame.lua:1448>

**Comment by plusmouse** [comment]
Great. If it comes back I'll reopen the issue.
