### ISSUE TITLE
Show profits for enchantments

### ISSUE THREAD

**Issue by sadamczyk** [Auctionator/Auctionator#1284]
**Is your feature request related to a problem? Please describe.**
Currently profits for enchants aren't shown in the profession window.

There is a few problems here:
1. You can't sell the enchant directly (unless you trade with a player manually), but only the item "Scroll of *currently selected enchant*", meaning Auctionator would have to look for the current price of that scroll instead.
2. The vellums also have a cost to them, so that would also have to be added to the shown cost of production, and afterwards be subtracted from the profits. Problem: Which vellum do you use for the cost calculation? This isn't an issue for the max level recipes, since for those you can only use the [Armor Vellum III] / [Weapon Vellum III], but the enchants from older expansions can be put on any of the available vellums.

**Describe the solution you'd like**
1. Show the profit of enchants by using the current sell price of "Scroll of *currently selected enchant*".
The subtracted cost needs to factor in the vellum cost picked in 2.
2. Add 2 options (in the options?) to select which weapon/armor vellums you want to add for the cost calculation.
Both of these should list all the available vellums, and the option *"None"*, if you want to know the cost without the vellums.

**Describe alternatives you've considered**
Since people might want to still manually sell enchants by trading with players directly, you maybe want to show both the cost as it is now without the vellum, and then *additionally* the cost of creating the enchant + the vellum.
Another row could be added between the current cost and the profit, named "Cost (Scroll)" or something like that, which shows the cost of all the enchanting materials + the cost of the vellum picked in 2.
I feel like this solution just bloats the profession window though, and by adding a *"None"* option for the vellums, you still can get the same result.
But maybe it would actually be cleaner (code-wise) to have 2 separate costs listed, so there is no need to add additional edge cases for the existing cost calculation. Not sure about that.

**Comment by plusmouse** [comment]
1. Finding the scroll on the AH isn't a problem
2. Finding the matching vellum is a problem as I'm not sure how to compute what vellum a particular enchant should appear on, and keeping a list that isn't automatically generated would be awkward.

**Comment by tschirky** [comment]
This feature would indeed be great. Since computing the required vellum, one could simply exclude the vellum from the profit calculation and indicate: profit - <vellum price>

**Comment by plusmouse** [comment]
How would you determine the required vellum to exclude?

**Comment by sadamczyk** [comment]
1. Which "level" of vellum should be used? I, II or III (and further in retail?)

    Enchants are technically spells and have a level (listed on wowhead f.e.).
All the WOTLK enchants are level 60, TBC enchants are 35 and Classic enchants have no level listed (so let's say 0).
The description of the enchants also says "Requires a level 60 or higher item." for WOTLK, 35 for TBC and nothing for Classic enchants, so this seems to match.
[WOTLK example](https://www.wowhead.com/wotlk/spell=59621/enchant-weapon-berserking)
[TBC example](https://www.wowhead.com/wotlk/spell=44383/enchant-shield-resilience)
[Classic example](https://www.wowhead.com/wotlk/spell=20025/enchant-chest-greater-stats)

    If I look at the vellums they are item level 65, 40 and 1 respectively:
[WOTLK example](https://www.wowhead.com/wotlk/item=39350/weapon-vellum-ii)
[TBC example](https://www.wowhead.com/wotlk/item=43146/weapon-vellum-iii)
[Classic example](https://www.wowhead.com/wotlk/item=39349/weapon-vellum)

    So I guess the rule could just be that the item level of the vellum has to be higher than the spell level of the enchantment.
I'm unfamiliar with the WOW API and could only find the spell levels listed [in a database](https://wow.tools/dbc/?dbc=spelllevels&build=3.4.1.47720#page=1&search=44383), but no way to get that info in the actual API, but maybe I just didn't look in the right place.
(The lack of good official documentation for this is actually surprising.)

2. Do we have to use an Armor or a Weapon Vellum?

    The `SpellEquippedItems` table seems to map which spells work on which item types.
    Here are the results for the enchants I linked above:
[WOTLK example](https://wow.tools/dbc/?dbc=spellequippeditems&build=3.4.1.47720#page=1&colFilter[1]=20025)
[TBC example](https://wow.tools/dbc/?dbc=spellequippeditems&build=3.4.1.47720#page=1&colFilter[1]=44383)
[Classic example](https://wow.tools/dbc/?dbc=spellequippeditems&build=3.4.1.47720#page=1&colFilter[1]=59621)
`GetItemInfo()` [[ref]](https://wowpedia.fandom.com/wiki/ItemType) returns the `ClassId` 2 for weapons, so use Weapon Vellums for those, and the `ClassId` 4 for armor, so use Armor Vellums for those.

3. Go through all the actually usable vellums now, and pick the cheapest option for the profit calculation?

**Comment by plusmouse** [comment]
Thanks for the information, I've used it to add in a profit line for enchants, taking the vellum into account:
![image](https://user-images.githubusercontent.com/60280559/228351372-8bca4627-43b5-4001-a548-289238109c97.png)
I haven't been able to test higher level enchants, but the code should work for them. Find this in the latest alpha (available shortly from Curseforge or Wago)
[Auctionator-10.0.42-9-g2db1ad9-wrath.zip](https://github.com/Auctionator/Auctionator/files/11093642/Auctionator-10.0.42-9-g2db1ad9-wrath.zip)

Can you let me know if it works with the higher level enchants (35 or above)?

**Comment by sadamczyk** [comment]
I'm glad my research helped you find a solution! :) Thanks for your work!
Unfortunately my subscription recently ran out, and I won't be renewing it any time soon, so I can't test it.
Hopefully somebody else can try it out though.
