### ISSUE TITLE
Game is unplayable due to Auctionator and new profession UI. 

### ISSUE THREAD

**Issue by DCCXVIII** [Auctionator/Auctionator#1286]
Game FPS goes down to single digits when this addon is enabled and when you open the new profession UI. Disabling this addon resolves the issue. Enchanting is of particular concern. You will get 3 FPS with this addon.

**Comment by plusmouse** [comment]
Can you try with just Auctionator enabled?

For the profession UI its unlikely to be Auctionator tanking the frame rate - there may be another addon that's rapidly switching recipes triggering multiple computations for the profession UI.

**Comment by plusmouse** [comment]
No response. Closing.
