### ISSUE TITLE
same item with different levels or stats has different vendor prices

### ISSUE THREAD

**Issue by R-Adrian** [Auctionator/Auctionator#1289]
This is not exactly an error with Auctionator but more of a side-effect of how Blizzard is setting the sell-to-vendor prices in the last few years... it happened in Shadowlands too, but the recent launch of Dragonflight makes it even more annoying..

## Brief Description of Bug

The same item with different levels or stats has different sell-to-vendor prices and the base item without any random stats has a much lower sell-to-vendor price than an actual item with stats.

When the checkbox to use item level and title is not selected in Auctionator options, as a result of this vendor price variation, the Auction House is now flooded with tons of items posted by careless people at below sell-to-vendor prices because they think they are undercutting someone else and are still making a profit, but instead are just throwing revenue away and flooding the Auction House database servers in the process.
(and the default setting of that checkbox is to not be selected, from what i remember)

## Steps to Reproduce

try listing an item level 302 random Dragonflight green item in the Auction House. Auctionator will try to undercut the LOWEST price possible while ignoring item level variations.

## Loaded Addons
not relevant

## Back Trace (LUA Error Output)
This is not a LUA error, but a logical error when appraising prices and the sell-to-vendor lower price limits.

## proposed solution
When calculating the sell-to-vendor low price limits use the full item level and title and ignore the checkbox for this in the Auctionator options.

## Example:
this ilvl 302 item below appears posted just above the sell-to-vendor price, right?...
Wrong. it actually is posted way below the sell-to-vendor price.

![image](https://user-images.githubusercontent.com/16319504/205462241-d040ecb0-915f-4c9f-a42b-ba472eccf4fb.png)

if you look at the actual item with stats, it becomes obvious that it was posted in the Auction House by an addon that was only considering the vendor price of the base item alone, without any modifiers.

![image](https://user-images.githubusercontent.com/16319504/205462314-99663b74-dba7-44f1-9e44-d87f98b3b62e.png)

**Comment by plusmouse** [comment]
It does target the lowest price _but_ it also warns you when you attempt to post that that price is below vendor price:
![image](https://user-images.githubusercontent.com/60280559/205462791-893b9a79-cd01-4ad0-b385-8593c79f026e.png)

A user has to confirm they really want to post at that price.

**Comment by plusmouse** [comment]
If the dialog isn't appearing that's a bug, but otherwise the behaviour is expected.

**Comment by R-Adrian** [comment]
just tested it, that warning does appear.

then the server i'm playing of must be full of clueless people... i've been buying tons of such random stuff in AH lately and then dumping them to a vendor, to the point i'm getting exasperated.

Blizzard should just make the AH goblins automatically vendor all items posted at below-vendor prices... this would automatically clean up the AH server databases of such items.
