### ISSUE TITLE
New Lua Error with latest update 12/8/2022

### ISSUE THREAD

**Issue by Kaenna52** [Auctionator/Auctionator#1297]
**Please include as much of the following information as possible to help me fix the bug:**
## When I open my professions window I get a Lua Error, the same error happened with Enchanting and Cooking.  I disabled every one of my addons and tried only running Auctionator and still received the same error.  In addition, the crafting cost is no longer showing up in my profession window.
___________________________________________________________________________________________________________________________________
_The Error:_
Message: ...ionator/Source_Mainline/CraftingInfo/Professions.lua:94: attempt to index local 'operationInfo' (a nil value)
Time: Thu Dec  8 03:28:47 2022
Count: 2
Stack: ...ionator/Source_Mainline/CraftingInfo/Professions.lua:94: attempt to index local 'operationInfo' (a nil value)
[string "@Interface/AddOns/Auctionator/Source_Mainline/CraftingInfo/Professions.lua"]:94: in function <...ionator/Source_Mainline/CraftingInfo/Professions.lua:82>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Auctionator/Source_Mainline/CraftingInfo/Professions.lua"]:168: in function `GetInfoText'
[string "@Interface/AddOns/Auctionator/Source_Mainline/CraftingInfo/Mixins/Professions.lua"]:79: in function `UpdateTotal'
[string "@Interface/AddOns/Auctionator/Source_Mainline/CraftingInfo/Mixins/Professions.lua"]:13: in function <.../Source_Mainline/CraftingInfo/Mixins/Professions.lua:10>
[string "=[C]"]: in function `Init'
[string "@Interface/AddOns/Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeSchematicForm.lua"]:189: in function <...emplates/Blizzard_ProfessionsRecipeSchematicForm.lua:183>
[string "=[C]"]: in function `Show'
[string "@Interface/FrameXML/UIParent.lua"]:2853: in function `SetUIPanel'
[string "@Interface/FrameXML/UIParent.lua"]:2696: in function `ShowUIPanel'
[string "@Interface/FrameXML/UIParent.lua"]:2561: in function <Interface/FrameXML/UIParent.lua:2557>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/FrameXML/UIParent.lua"]:3159: in function `ShowUIPanel'
[string "@Interface/FrameXML/UIParent.lua"]:2002: in function <Interface/FrameXML/UIParent.lua:1362>
[string "=[C]"]: in function `UseAction'
[string "@Interface/FrameXML/SecureTemplates.lua"]:364: in function `handler'
[string "@Interface/FrameXML/SecureTemplates.lua"]:690: in function <Interface/FrameXML/SecureTemplates.lua:672>
[string "@Interface/FrameXML/SecureTemplates.lua"]:704: in function <Interface/FrameXML/SecureTemplates.lua:697>
[string "@Interface/FrameXML/SecureTemplates.lua"]:746: in function `SecureActionButton_OnClick'
[string "@Interface/FrameXML/ActionButton.lua"]:1175: in function <Interface/FrameXML/ActionButton.lua:1145>
[string "=[C]"]: ?

Locals: schematicForm = Frame {
 0 = <userdata>
 elapsed = 0.684000
 OnHyperlinkLeave = <function> defined @Interface/AddOns/Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeSchematicForm.lua:1234
 postInit = <function> defined @Interface/AddOns/Blizzard_Professions/Blizzard_ProfessionsCrafting.lua:117
 Stars = Frame {
 }
 GetRecipeInfo = <function> defined @Interface/AddOns/Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeSchematicForm.lua:1191
 UpdateRecraftSlot = <function> defined @Interface/AddOns/Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeSchematicForm.lua:1155
 enchantSlot = Frame {
 }
 extraSlotFrames = <table> {
 }
 OnShow = <function> defined @Interface/AddOns/Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeSchematicForm.lua:183
 currentRecipeInfo = <table> {
 }
 OnHyperlinkEnter = <function> defined @Interface/AddOns/Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeSchematicForm.lua:1222
 recipeSchematic = <table> {
 }
 OptionalReagents = Frame {
 }
 selectedRecipeLevels = <table> {
 }
 GetSlots = <function> defined @Interface/AddOns/Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeSchematicForm.lua:1206
 UpdateDetailsStats = <function> defined @Interface/AddOns/Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeSchematicForm.lua:1167
 GetCallbacksByEvent = <function> defined @Interface/SharedXML/CallbackRegistry.lua:54
 UnregisterEvents = <function> defined @Interface/SharedXML/CallbackRegistry.lua:165
 RecipeLevelBar = StatusBar {
 }
 loader = <table> {
 }
 GetCurrentRecipeLevel = <function> defined @Interface/AddOns/Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeSchematicForm.lua:1218
 NineSlice = Frame {
 }
 OnLoad = <function> defined @Interface/AddOns/Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeSche
____________________________________________________________________________________________________________________________________

_Please include a brief description of the bug, including what you were doing, and when it occurred._
## I ran a scan of the AH, then opened my profession window to craft

_Include the steps I would need to follow to reproduce the bug._
## I received the error for the first time after going to the AH, posting a few items, running a cancel undercut, and canceling undercut items. Then I ran collected my items from the mail, went back to the AH, and ran a full scan. I then opened my profession window (Enchanting) to see what I needed to craft... This is when I received this error. 

_Include a list of addons you were running at the time this bug occurred._
## Error occurred while running all of my addons, and after disabling them all and running Auctionator on its own

_You can get this through the use of !BugGrabber and BugSack addons._
with these addons installed, the error doesn't show, but the crafting cost does not show up in the profession window still.  The items in my bag do seem to have the correct AH price in the tooltips. 
![Auctionator_LuaError_12-8-2022](https://user-images.githubusercontent.com/116967878/206412460-d0cd30c1-729e-4162-8ec0-06ae2dde06a3.JPG)
![craftingcostmissing](https://user-images.githubusercontent.com/116967878/206413241-a5f7985d-6d2a-42af-9fbb-a8c9812ad9e9.JPG)

**Comment by plusmouse** [comment]
Now fixed in the latest alpha. Can you try it and verify that it is fixed for you too:
[Auctionator-10.0.23-2-ga7d2093.zip](https://github.com/Auctionator/Auctionator/files/10184275/Auctionator-10.0.23-2-ga7d2093.zip)
