### ISSUE TITLE
New errors for auctionator 10.0.25 (wasn't there yesterday)

### ISSUE THREAD

**Issue by nToxik** [Auctionator/Auctionator#1299]
Just logged into WOW retail and receive this error in bugrabber/bugsack. These errors were not there yesterday.

1x Auctionator/Source_Mainline/AH/Initialize.lua:7: CreateFrame(): Couldn't find inherited node "AuctionatorAHThrottlingFrameTemplate"
[string "=[C]"]: in function `CreateFrame'
[string "@Auctionator/Source_Mainline/AH/Initialize.lua"]:7: in function `Initialize'
[string "@Auctionator/Source_Mainline/Initialize/Main.lua"]:37: in function `AuctionHouseShown'
[string "@Auctionator/Source_Mainline/Initialize/Main.lua"]:20: in function <...dOns/Auctionator/Source_Mainline/Initialize/Main.lua:12>

Locals:
(*temporary) = "FRAME"
(*temporary) = "AuctionatorAHThrottlingFrame"
(*temporary) = AuctionHouseFrame {
 0 = <userdata>
 GetBidStatus = <function> defined @Blizzard_AuctionHouseUI/Blizzard_AuctionHouseFrame.lua:932
 ItemSellList = Frame {
 }
 GetBackdropColor = <function> defined @SharedXML/Backdrop.lua:390
 AuctionsTab = AuctionHouseFrameAuctionsTab {
 }
 GetTitleText = <function> defined @SharedXML/PortraitFrame.lua:28
 SetDisplayMode = <function> defined @Blizzard_AuctionHouseUI/Blizzard_AuctionHouseFrame.lua:571
 SelectBrowseResult = <function> defined @Blizzard_AuctionHouseUI/Blizzard_AuctionHouseFrame.lua:717
 UpdateTitle = <function> defined @Blizzard_AuctionHouseUI/Blizzard_AuctionHouseFrame.lua:670
 TitleContainer = Frame {
 }
 ClearBackdrop = <function> defined @SharedXML/Backdrop.lua:282
 GetBrowseResultsFrame = <function> defined @Blizzard_AuctionHouseUI/Blizzard_AuctionHouseFrame.lua:687
 GetMaxPriceWidth = <function> defined @Blizzard_AuctionHouseUI/Blizzard_AuctionHouseFrame.lua:922
 SetPostItem = <function> defined @Blizzard_AuctionHouseUI/Blizzard_AuctionHouseFrame.lua:638
 CommoditiesSellFrame = Frame {
 }
 maxBuyoutPriceWidth = <table> {
 }
 UnregisterEvents = <function> defined @SharedXML/CallbackRegistry.lua:165
 SetPortraitAtlasRaw = <function> defined @SharedXML/PortraitFrame.lua:83
 GetCategorySearchContext = <function> defined @Blizzard_AuctionHouseUI/Blizzard_AuctionHouseFrame.lua:711
 WoWTokenResults = Frame {
 }
 SetTitleFormatted = <function> defined @SharedXML/PortraitFrame.lua:40
 NineSlice = Frame {
 }
 BuyDialog = Frame {
 }
 TopEdge = Texture {
 }
 Event = <table> {
 }
 MoneyFrameBorder = Frame {
 }
 SetBackdropColor = <function> defined @SharedXML/Backdrop.lua:399
 LeftEdge = Texture {
 }
 StartCommoditiesPurchase = <function> defined @Blizzard_AuctionHouseUI/Blizzard_AuctionHouseFrame.lua:878
 StartItemBuyout = <function> defined @Blizzard_AuctionHouseUI/Blizzard_AuctionHouseFrame.lua:893
 SetPortraitShown = <function> defined @SharedXML/PortraitFrame.lua:91
 activeSearches = <table> {
 }
 QueryItem = <function> defined @Blizzard_AuctionHouseUI/Blizzard_AuctionHouseFrame.lua:771
 SellTab = AuctionHouseFrameSellTab {
 }
 SetDialogOverlayShown = <function> defined @Blizzard_AuctionHouseUI/Blizzard_AuctionHouseFrame.lua:944
 callbackTables = <table> {
 }
 RefreshSearchResults = <function> defined @Blizzard_AuctionHouseUI/Blizzard_AuctionHouseFrame.lua:862
 RegisterCallback = <function> defined @SharedXML/CallbackRegistry.lua:75
 ClearMaxWidthCaches = <function> defined @Blizzard_AuctionHouseUI/Blizzard_AuctionHouseFrame.lua:505
 UnregisterCallback = <function> defined @SharedXML/CallbackRegistry.lua:150
 RegisterCallbackWithHandle = <function> defined @SharedXML/CallbackRegistry.lua:119
 SetBorderBlendMode = <function> defined @SharedXML/Backdrop.lua:266
 maxUnitPriceWidth = <table> {
 }
 SetBorder = <function> defined @SharedXML/PortraitFrame.lua:62
 HasRegistrantsForEvent = <function> defined @SharedXML/CallbackRegistry.lua:59
 OnBackdropSizeChanged = <function> defined @SharedXML/Backdrop.lua:182
 GetPortrait = <function> defined @SharedXML/PortraitFrame.lua:58
 GetDisplayMode = <function> defined @Blizzard_AuctionHouseUI/Blizzard_AuctionHouseFrame.lua:629
 GetMaxBuyoutWidth = <function> defined @Blizzard_AuctionHouseUI/Blizzard_AuctionHouseFrame.lua:361
 SetupPieceVisuals = <function> defined @SharedXML/Backdrop.lua:246
 selectedTab = 1
 GetMaxUnitPriceWidth = <function> defined @Blizzard_AuctionHouseUI/Blizzard_AuctionHouseFrame.lua:361
 CommoditiesBuyFrame = Frame {
 }
 SendBrowseQuery = <function> defined @Blizzar

1x ...ceAuctionator/Source_Mainline/Core/Mixin.lua:20: attempt to call method 'IsAutoscanReady' (a nil value)
[string "@Auctionator/Source_Mainline/Core/Mixin.lua"]:20: in function <...ceAuctionator/Source_Mainline/Core/Mixin.lua:3>
[string "@Auctionator/Source_Mainline/Core/Mixin.lua"]:111: in function <...ceAuctionator/Source_Mainline/Core/Mixin.lua:108>
[string "=[C]"]: in function `CreateFrame'
[string "@Auctionator/Source_Mainline/Initialize/Main.lua"]:40: in function `AuctionHouseShown'
[string "@Auctionator/Source_Mainline/Initialize/Main.lua"]:20: in function <...dOns/Auctionator/Source_Mainline/Initialize/Main.lua:12>

Locals:
frame = AuctionatorIncrementalScanFrame {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = AuctionatorIncrementalScanFrame {
 0 = <userdata>
}
(*temporary) = "attempt to call method 'IsAutoscanReady' (a nil value)"

**Comment by plusmouse** [comment]
Can you try downloading Auctionator again - it looks like the .zip you installed was corrupted.

**Comment by Hammerpass** [comment]
cant disenchant items

**Comment by plusmouse** [comment]
@Hammerpass Can you open a new issue and include the error message you've seen in it.

**Comment by nToxik** [comment]
Yes deleting and downloading a new copy fixed my issue. Thanks.
