### ISSUE TITLE
Error when opening jewelcrafting and choosing an item to recraft

### ISSUE THREAD

**Issue by Caerdon** [Auctionator/Auctionator#1301]
## Brief Description of Bug

When attempting to recraft an item (specifically jewelcrafting in my case), I get multiple LUA errors after I've chosen an item to recraft and start selecting various options on that screen (embellishments, etc).

## Steps to Reproduce

1. Open jewelcrafting
2. Choose Recraft Equipment
3. Click the big + and choose an item that can be recrafted.

## Loaded Addons

I disabled all other addons other than Auctionator.

## Back Trace (LUA Error Output)

`Message: ...ns/Auctionator/Source_Mainline/CraftingInfo/Main.lua:39: attempt to index local 'slotAllocations' (a nil value)
Time: Sat Dec 10 21:48:02 2022
Count: 1
Stack: ...ns/Auctionator/Source_Mainline/CraftingInfo/Main.lua:39: attempt to index local 'slotAllocations' (a nil value)
[string "@Interface/AddOns/Auctionator/Source_Mainline/CraftingInfo/Main.lua"]:39: in function <...ns/Auctionator/Source_Mainline/CraftingInfo/Main.lua:33>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Auctionator/Source_Mainline/CraftingInfo/Professions.lua"]:156: in function <...ionator/Source_Mainline/CraftingInfo/Professions.lua:155>
[string "@Interface/AddOns/Auctionator/Source_Mainline/CraftingInfo/Professions.lua"]:180: in function `GetInfoText'
[string "@Interface/AddOns/Auctionator/Source_Mainline/CraftingInfo/Mixins/Professions.lua"]:79: in function `UpdateTotal'
[string "@Interface/AddOns/Auctionator/Source_Mainline/CraftingInfo/Mixins/Professions.lua"]:13: in function <.../Source_Mainline/CraftingInfo/Mixins/Professions.lua:10>
[string "=[C]"]: in function `Init'
[string "@Interface/AddOns/Blizzard_Professions/Blizzard_ProfessionsCrafting.lua"]:273: in function `SelectRecipe'
[string "@Interface/AddOns/Blizzard_Professions/Blizzard_ProfessionsCrafting.lua"]:582: in function `Init'
[string "@Interface/AddOns/Blizzard_Professions/Blizzard_ProfessionsFrame.lua"]:98: in function <...s/Blizzard_Professions/Blizzard_ProfessionsFrame.lua:59>
[string "=[C]"]: in function `OpenRecipe'
[string "@Interface/AddOns/Blizzard_ProfessionsTemplates/Blizzard_Professions.lua"]:295: in function `TransitionToRecraft'
[string "@Interface/AddOns/Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeSchematicForm.lua"]:669: in function <...emplates/Blizzard_ProfessionsRecipeSchematicForm.lua:668>
[string "=[C]"]: ?
[string "@Interface/SharedXML/CallbackRegistry.lua"]:143: in function <Interface/SharedXML/CallbackRegistry.lua:142>
[string "=[C]"]: ?
[string "@Interface/SharedXML/CallbackRegistry.lua"]:146: in function `TriggerEvent'
[string "@Interface/AddOns/Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeFlyout.lua"]:83: in function <...ssionsTemplates/Blizzard_ProfessionsRecipeFlyout.lua:81>

Locals: recipeSchematic = <table> {
 outputItemID = 201759
 hasCraftingOperationInfo = true
 quantityMax = 1
 quantityMin = 1
 recipeID = 394621
 recipeType = 1
 name = "Torc of Passed Time"
 hasGatheringOperationInfo = false
 reagentSlotSchematics = <table> {
 }
 isRecraft = false
 icon = 0
}
transaction = <table> {
 SanitizeRecraftAllocation = <function> defined @Interface/AddOns/Blizzard_ProfessionsTemplates/Blizzard_ProfessionsTransaction.lua:346
 GetRecraftAllocation = <function> defined @Interface/AddOns/Blizzard_ProfessionsTemplates/Blizzard_ProfessionsTransaction.lua:498
 AccumulateAllocations = <function> defined @Interface/AddOns/Blizzard_ProfessionsTemplates/Blizzard_ProfessionsTransaction.lua:191
 ClearRecraftAllocation = <function> defined @Interface/AddOns/Blizzard_ProfessionsTemplates/Blizzard_ProfessionsTransaction.lua:460
 SetRecraftAllocation = <function> defined @Interface/AddOns/Blizzard_ProfessionsTemplates/Blizzard_ProfessionsTransaction.lua:465
 HasAllocatedReagentRequirements = <function> defined @Interface/AddOns/Blizzard_ProfessionsTemplates/Blizzard_ProfessionsTransaction.lua:550
 IsRecraft = <function> defined @Interface/AddOns/Blizzard_ProfessionsTemplates/Blizzard_ProfessionsTransaction.lua:456
 SetRecraftAllocationOrderID = <function> defined @Interface/AddOns/Blizzard_ProfessionsTemplates/Blizzard_ProfessionsTransaction.lua:474
 GenerateExpectedItemModifications = <function> defined @Interface/AddOns/Blizzard_ProfessionsTemplates/Blizzard_ProfessionsTransaction.lua:250
 GetAllocations = <function> defined @Interface/AddOns/Blizzard_ProfessionsTemplates/Blizzard_ProfessionsTransaction.lua:168
 OnChanged = <function> defined @Interface/AddOns/Blizzard_ProfessionsTemplates/Blizzard_ProfessionsTransaction.lua:230
 GetRecip`

**Comment by plusmouse** [comment]
Is selecting a finishing/modification reagent required to trigger the error, or will it happen without doing that?
![image](https://user-images.githubusercontent.com/60280559/206891892-b9ff3ec3-85b9-49bb-9efb-d95245b7eca3.png)

Also, were all the errors identical?

**Comment by plusmouse** [comment]
While I wasn't able to replicate the error I've added some code that should prevent it anyway in the latest alpha (available here or from Curseforge shortly):
[Auctionator-10.0.25-1-g7bc43ff.zip](https://github.com/Auctionator/Auctionator/files/10201685/Auctionator-10.0.25-1-g7bc43ff.zip)

Can you test the alpha and report if the error is gone?

**Comment by Caerdon** [comment]
It happened as soon as I entered the recrafting interface, but the alpha appears to have fixed it - thanks!
