### ISSUE TITLE
Please add a Crafted Quality option to the Extended Search Options

### ISSUE THREAD

**Issue by jonjbm** [Auctionator/Auctionator#1302]
I'm referring to the new quality tiers they have added to various crafted items (bronze, silver, gold, etc.). It would be very helpful in my shopping lists if I could set a certain item in a list to only search for a specific quality tier of that item. Would really help to declutter my shopping lists.

**Comment by plusmouse** [comment]
Is this for the reagents, or is it necessary to cover the crafted items too?
![image](https://user-images.githubusercontent.com/60280559/207317834-da8e8b8c-9b91-4940-9725-9f7060fe53e5.png)
![image](https://user-images.githubusercontent.com/60280559/207317886-d4aa6d09-338f-4adb-a214-2daa407825a3.png)
![image](https://user-images.githubusercontent.com/60280559/207317931-26a3ed26-1df1-468a-a02f-17b60efdae44.png)

**Comment by jonjbm** [comment]
> Is this for the reagents, or is it necessary to cover the crafted items too?

I'd really like it for both if possible. I've been using shopping lists pretty heavily lately for crafted jewelcrafting items (as well as jewelcrafting reagents).

Thank you!

**Comment by plusmouse** [comment]
Can give an example of a crafted JC item, some of them count as reagents even if they're craft results.

**Comment by plusmouse** [comment]
This build will do this correctly, and the emeralds are crafted JC items, but code-wise count as reagents 😄 
![image](https://user-images.githubusercontent.com/60280559/207411931-421e946e-69c1-4708-b88b-cdbd3cec7507.png)

[Auctionator-10.0.26.zip](https://github.com/Auctionator/Auctionator/files/10220934/Auctionator-10.0.26.zip)

**Comment by jonjbm** [comment]
Lately I've been using a shopping list a lot with blue crafted gems, such as:

https://www.wowhead.com/item=192919/crafty-alexstraszite

**Comment by plusmouse** [comment]
That should work fine with the build linked

**Comment by plusmouse** [comment]
Basically everything except gear should work.

**Comment by jonjbm** [comment]
Cool. Thanks so much! :)
