### ISSUE TITLE
Items dissapear on selling and not appear in the Auction

### ISSUE THREAD

**Issue by io-sar** [Auctionator/Auctionator#1303]
## Brief Description of Bug

Every item that I tried to sell today (14/12/2022 CET, 00:00 AM) When I pressed sell they removed from my bag but didnt reach the auction house (cant be seen in the auction)

## Steps to Reproduce

Any item sold from the Reagent bag (not sure if it matters)

## Loaded Addons

Auctionator, Coordinates, Details!, Pawn, Rarescanner, DBM

**Comment by io-sar** [comment]
Hi, when I added the items from the blizzard ui it worked. Later I recieved gold from the sell so it seems the auctionator wasnt showing the items :/

**Comment by plusmouse** [comment]
Due to not being able to replicate the bug, and the user finding a resolution, closing this.
