### ISSUE TITLE
Split the option for item level and item name sell price calculation

### ISSUE THREAD

**Issue by cremor** [Auctionator/Auctionator#1305]
**Is your feature request related to a problem? Please describe.**
When I try to sell profession equipment I want the default price to match the price of existing auctions with the same item level. But if I want to sell low level green items I do not want to only see existing auctions with the exact same item name.

**Describe the solution you'd like**
I'd like the option to be split in two, so that I can match the price by item level, but not by item name.

**Comment by raysmith59** [comment]
+1... not to hijack but I'd also like to see an equipped level option as well - the level 60 green gear sells for significantly more than the higher level gear but they aren't all the same iLvl, of a small handful of items I have there are a mix of 200 and 202 items.

**Comment by ThistleProse** [comment]
Hey! I dropped by to make a similar request!

Searching for items to sell, it would be really nice if we could enable/disable the variations of the same option. Eg,

"... of the Flashfire" and "... of the Quickblade" -- they might both be listed, but won't show up in the Selling tab, unless _your_ item being listed is also Flashfire or Quickblade, which can cause some interesting results when looking at buying them lol.

**Comment by plusmouse** [comment]
Hi. Looking at this request, would these options be sufficient?
- Item level with the same item id
- Item id only (so any ilvl and suffix)
- Item name and level (exactly the same as what you are posting)
- Item name only (so not ilvl specific)

**Comment by plusmouse** [comment]
Available in the latest alpha (from Curseforge or Wago shortly or from here)
[Auctionator-10.0.45-4-gc632c5e.zip](https://github.com/Auctionator/Auctionator/files/11359174/Auctionator-10.0.45-4-gc632c5e.zip)
The options are as described in the previous comment:
![image](https://user-images.githubusercontent.com/60280559/235302665-16a2f3af-74fd-4131-9813-d025464bdac3.png)

**Comment by plusmouse** [comment]
Update: Bugfix for the release in the previous comment
[Auctionator-10.0.45-5-g910b6b0.zip](https://github.com/Auctionator/Auctionator/files/11359189/Auctionator-10.0.45-5-g910b6b0.zip)
