### ISSUE TITLE
Attempt to index field 'Database' (a nil value)

### ISSUE THREAD

**Issue by Grizz2202** [Auctionator/Auctionator#1308]
I've been getting this error for a pretty long time now, you can see i have 1,016 of these errors since the last time I cleared my bugsack. I get this on every toon every time I log in.

Please tell me how to fix this or if there's something I'm doing wrong, this is killing me:

1016x ...nterface\AddOns\Auctionator\Source\Tooltips\Main.lua:37: attempt to index field 'Database' (a nil value)
[string "@Interface\AddOns\Auctionator\Source\Tooltips\Main.lua"]:37: in function `ShowTipWithPricingDBKey'
[string "@Interface\AddOns\Auctionator\Source\Tooltips\Main.lua"]:17: in function `callback'
[string "@Interface\AddOns\Auctionator\Source\Utilities\DBKeyFromLink.lua"]:52: in function `DBKeyFromLink'
[string "@Interface\AddOns\Auctionator\Source\Tooltips\Main.lua"]:15: in function `ShowTipWithPricing'
[string "@Interface\AddOns\Auctionator\Source\Tooltips\Hooks.lua"]:293: in function <...terface\AddOns\Auctionator\Source\Tooltips\Hooks.lua:292>
[string "=[C]"]: in function `SetHyperlink'
[string "@Interface\AddOns\StealYourCarbon\WaterUpgrader.lua"]:13: in main chunk

**Comment by plusmouse** [comment]
Fixed in the latest alpha (available from Curseforge when it finishes processing), or from:
[Auctionator-10.0.26-5-g21d9644-wrath.zip](https://github.com/Auctionator/Auctionator/files/10262727/Auctionator-10.0.26-5-g21d9644-wrath.zip)
