### ISSUE TITLE
Stack Price toggle button in "Cancelling" tab

### ISSUE THREAD

**Issue by aucqa** [Auctionator/Auctionator#1309]
I often use this tab to check my auction summary and I think having the option to view the stack price (if applicable to the listing) on top of the unit price would be a nice QoL feature. Screenshot attached. Thank you!

![auctionator](https://user-images.githubusercontent.com/121124999/208738111-f2da9d05-72d8-4f6b-a328-669bd0e57530.png)

**Comment by plusmouse** [comment]
![image](https://user-images.githubusercontent.com/60280559/208755135-d5d81d6c-53c6-402f-9888-47c8bde37bc6.png)
This will be in the next alpha release on Curseforge (once it finishes processing) as an optional column
