### ISSUE TITLE
Crafter order NPC Bug

### ISSUE THREAD

**Issue by Rubyurek** [Auctionator/Auctionator#1311]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

_Please include a brief description of the bug, including what you were doing, and when it occurred._

## Steps to Reproduce

_Include the steps I would need to follow to reproduce the bug._

I pressed on the craft order NPC and then this error message appeared.

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._
WeakAurasCompanion: enabled
WeakAurasArchive: enabled
Auctionator: enabled
BetterAddonList: enabled
BtWLoadouts: enabled
DeModal: disabled
Details: enabled
Details_EncounterDetails: enabled
Details_RaidCheck: enabled
Details_DataStorage: enabled
Details_Streamer: disabled
Details_TinyThreat: enabled
Details_Vanguard: enabled
Immersion: enabled
Leatrix_Maps: enabled
Leatrix_Plus: enabled
LFGSpamFilter: disabled
OmniCC: enabled
OmniCC_Config: enabled
Simulationcraft: enabled
WeakAuras: enabled
WeakAurasModelPaths: enabled
WeakAurasOptions: enabled
WeakAurasTemplates: enabled
!KalielsTracker: enabled
Krowi_AchievementFilter: enabled
TLDRMissions: disabled
BlizzMove: enabled
BlizzMove_Debug: disabled
Blizzard_ObjectiveTracker: enabled
Blizzard_CompactRaidFrames: enabled
ls_Toasts: enabled
!BugGrabber: enabled
BugSack: enabled
Bagnon: disabled
Bagnon_Config: disabled
Bagnon_GuildBank: disabled
Bagnon_VoidStorage: disabled
BagBrother: disabled
ExtendedSets: disabled
Blizzard_CombatText: enabled
BetterWardrobe: disabled
BetterWardrobe_SourceData: disabled
Details_Compare2: enabled
Masque: disabled
RemoveExtraActionButtonTexture: enabled
BtWQuests: enabled
BtWQuestsDragonflight: enabled
HandyNotes: enabled
HandyNotes_Dragonflight: enabled
HandyNotes_Valdrakken: enabled
EditModeExpanded: disabled
LiteBag: enabled
RareScanner: enabled
BetterWorldQuests: enabled
AngrierWorldQuests: enabled
Dominos_Cast: disabled
AlignmentGrid: disabled
Dominos: enabled
Dominos_Config: enabled
Dominos_Encounter: disabled
Dominos_Progress: enabled
Dominos_Roll: enabled
Masque_Dominos: disabled
InstanceAchievementTracker: disabled
PremadeGroupsFilter: enabled
WagoAppCompanion: enabled
GladiusEx: enabled
DragonridingJournal: enabled
ShadowedUF_Options: enabled
ShadowedUnitFrames: enabled

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._
1x ...ator/Source_Mainline/CraftingInfo/CustomerOrders.lua:11: attempt to index global 'ProfessionsCustomerOrdersFrame' (a nil value)
[string "@Auctionator/Source_Mainline/CraftingInfo/CustomerOrders.lua"]:11: in function `InitializeCustomerOrdersFrame'
[string "@Auctionator/Source_Mainline/Initialize/Main.lua"]:22: in function <...dOns/Auctionator/Source_Mainline/Initialize/Main.lua:12>

Locals:
(*temporary) = <function> defined =[C]:-1
(*temporary) = "BUTTON"
(*temporary) = "AuctionatorTradeSkillSearch"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'ProfessionsCustomerOrdersFrame' (a nil value)"
addedFunctionality = true

**Comment by plusmouse** [comment]
Fixed in 10.0.27 (available from Curseforge/Wago when it finishes processing)
[Auctionator-10.0.27.zip](https://github.com/Auctionator/Auctionator/files/10287976/Auctionator-10.0.27.zip)
