### ISSUE TITLE
In crafting UI, use lowest price to calculate crafting cost, not lowest quality

### ISSUE THREAD

**Issue by kevininderhees** [Auctionator/Auctionator#1312]
**Is your feature request related to a problem? Please describe.**
For some reagents like runed writhebark, the lowest quality is more expensive than higher qualities.  This inflates the cost displayed on the crafting screen.

**Describe the solution you'd like**
When we don't have an explicit quality selected for a reagent, use the cheapest available quality rather than the lowest quality when calculating price.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by plusmouse** [comment]
Fixed in the latest alpha
[Auctionator-10.0.27-1-gc70262c.zip](https://github.com/Auctionator/Auctionator/files/10298877/Auctionator-10.0.27-1-gc70262c.zip)
