### ISSUE TITLE
Post button takes a long time to become available

### ISSUE THREAD

**Issue by MarshallBuhl** [Auctionator/Auctionator#1314]
Please include as much of the following information as possible to help me fix the bug:

For my first auction (of the day?), the Post button doesn't become available for about 15-20 seconds.  Additional auctions do not have this problem.

_Please include a brief description of the bug, including what you were doing, and when it occurred._

First auction of the day, click on an item to auction, enter a price, then wait for the Post button to activate.

_Include the steps I would need to follow to reproduce the bug._

(see above)

_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

It does not generate an error.  It's just painfully slow.

**Comment by MarshallBuhl** [comment]
This does not happen if a different toon creates an auction on a different realm soon after creating auctions on the first realm.

**Comment by plusmouse** [comment]
Is this a new issue, or has it been a problem for a while?

**Comment by MarshallBuhl** [comment]
It's been bothering me for a couple weeks.

**Comment by MarshallBuhl** [comment]
Another data point: While I'm waiting for the Post button to light up so I can post and auction, I notice that it flashes *very* briefly in a non-periodic (random) fashion before it turns a solid red.

**Comment by plusmouse** [comment]
Does this affect commodities or items specifically? And is it on items that you already have some posted?

**Comment by MarshallBuhl** [comment]
It doesn't seem to affect anything other than it taking 15-20 seconds to post the first auction of the day instead of it being virtually instantaneous as it was in the past.  It happens to different toons on different realms.  But, it affects only one per day.

As for whether it happens for a new item for me to auction or one that is a repeat auction, I don't know.  I do know it happens if it's a repeat.  I will try to auction something for the first time to test this.  But, I seriously doubt that's the issue.

**Comment by plusmouse** [comment]
Also, does the buy listing continue to load or reload while you're waiting?

**Comment by plusmouse** [comment]
Try this build, it has a change that may help
[Auctionator-10.0.28-1-g4f65e84.zip](https://github.com/Auctionator/Auctionator/files/10325045/Auctionator-10.0.28-1-g4f65e84.zip)

**Comment by MarshallBuhl** [comment]
I don't know about buy listings as I haven't bought anything in a long time. 

I'll try the suggested version.

**Comment by MarshallBuhl** [comment]
Auctionator-10.0.28-1-g4f65e84.zip didn't fix it.

**Comment by plusmouse** [comment]
Ok. Can you try disabling this shortcut temporarily and report if it fixes the 15s lag
![image](https://user-images.githubusercontent.com/60280559/210138982-74c1fbb8-d243-4e77-a1c0-e55590f2817e.png)

**Comment by MarshallBuhl** [comment]
Which of the three am I supposed to disable? The location of the selection box makes it look like you are disabling the second, but I wanted to make sure.

I just now tried it and the Post button was lit immediately.  I don't know what that has to do with cancelling auctions, but it works for me.  Thanks!

**Comment by MarshallBuhl** [comment]
Bummer.  I noticed an alt had an item to auction, so I sent it to my main auction toon and I got the 15-second delay even though I had submitted a handful of auctions just a few minutes before.

I've never noticed this happen after the first sell of the day--even when I did it with a toon on a different server realm.

**Comment by plusmouse** [comment]
Just to clarify, this delay happened even with the setting changed?

**Comment by MarshallBuhl** [comment]
Yes.  It still happens.

However!  I noticed that just as the button became active, I got the following messages in my chat window:

> Auctionator: Starting a full scan (summary mode).
> Auctionator: Finished processing 18088 items.

So, since this started fairly recently, it appears that something about the scanning process is slower than it used to be and it's not done before I start selling.

**Comment by plusmouse** [comment]
It seems you have the autoscan option enabled, so it runs a full scan when you open the AH, delaying posting as it can't post while a scan is ongoing.

The scan is ~12s at the best of times, so a 15s delay while you wait for it to finish isn't unexpected.

I'd suggest turning the autoscan off so you can post immediately.
