### ISSUE TITLE
Canceling Undercuts constantly fail. 

### ISSUE THREAD

**Issue by AHFarmer123** [Auctionator/Auctionator#1316]
Please include as much of the following information as possible to help me fix the bug:
While canceling undercuts it constantly says internal auction failure. Its very slow and aggravating. Can we not create a bulk undercut cancel option that runs VS clicking the button 9 million times? 
## Brief Description of Bug
Constant failure when trying to cancel undercuts or canceling posted auctions.  
_Please include a brief description of the bug, including what you were doing, and when it occurred._
Failure to cancel auctions while canceling multiple auctions. 
## Steps to Reproduce
Post a bunch of auctions and try to cancel. 
_Include the steps I would need to follow to reproduce the bug._
Post 20+ of the same item or multiple deferent items and try to cancel.
## Loaded Addons
Auctionator and Bagnon
_Include a list of addons you were running at the time this bug occurred._
Auctionator and bagnon
## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by plusmouse** [comment]
A bulk cancel button isn't possible due to Blizzard restrictions on what addons can do.

**Comment by plusmouse** [comment]
The internal auction errors are a Blizzard problem, and there isn't anything Auctionator can do to mitigate them
