### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Luierror** [Auctionator/Auctionator#1317]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

_Please include a brief description of the bug, including what you were doing, and when it occurred._

## Steps to Reproduce

_Include the steps I would need to follow to reproduce the bug._

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by Luierror** [comment]
Currently this applies the Hat of Wintry Doom aswell as Deep Frozen Cord. Could possible apply to other items aswell.

**Comment by plusmouse** [comment]
Is this issue still relevant, or should I close it?
