### ISSUE TITLE
Feature Request: clicking item icon in Selling tab should take you to Buy tab for this specific item

### ISSUE THREAD

**Issue by Rezy942** [Auctionator/Auctionator#1319]
**Is your feature request related to a problem? Please describe.**
A lot of the time I find myself wanting to purchase an item when i'm putting up my items for sale. Currently, I find myself having to switch to buy the item, and entering the name manually. This can be quite tedious, and can be easily resolved by adding a shortcut.

**Describe the solution you'd like**
Left clicking on large item icon, should take user to buy tab, with name already entered in the field, and if possible automatically entered search. Currently, left click on icon = refresh search in Selling tab, which could be rebound to right click, as im sure most people arent using this, or are just clicking on the smaller icons instead.
![image](https://user-images.githubusercontent.com/122007087/211144731-bb61bfde-ca22-43e0-9cbe-643a98d62a07.png)
End result after clicking the icon:
![image](https://user-images.githubusercontent.com/122007087/211144763-f96692e9-6a4c-4d25-8369-cc1b59c72c43.png)

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by plusmouse** [comment]
You can alt+left click on a selling tab result to buy he

**Comment by Rezy942** [comment]
Yes I use that too, but the problem is it is all dependant on the quantity of top-most price.
I want to buy specific amount of gliders in this example, but here is what I get instead:
![image](https://user-images.githubusercontent.com/122007087/211145021-c60379f0-4db8-4c57-a022-9e879faf9afe.png)

**Comment by Rezy942** [comment]
Hello, are you considering this at all? (i'm aware you are very busy with various addons!!)
I feel this would be a massive QoL (at least for me) as switching tabs and re-entering the full name of item just to buy a specific amount is quite slow and annoying!
As i mentioned above - current right click feature works, but it doesnt allow to buy a specific amount. Only everything.

Technically, you could expand that tooltip and let user write how many pcs they want, which will recalculate price for that, and let user buy it. But i feel it would add more risk to user to mis-click and buy everything instead. So best is just a simple re-direct to buy tab.

Thank you so much...

**Comment by plusmouse** [comment]
Its on my list of things to review. Haven't decide whether to accept/reject so haven't closed the issue.

**Comment by plusmouse** [comment]
Assessment: Yes I'll add it, but with one extra click (on the result found in the Shopping tab)
 
![selling tab click to buy](https://user-images.githubusercontent.com/60280559/219732806-b09723fc-3185-4deb-8b83-06613594faef.gif)

**Comment by Rezy942** [comment]
Thank you so much! Even like this its miles ahead of having to manually type-out each item!!!
