### ISSUE TITLE
[Feature Req] Quantity of Item

### ISSUE THREAD

**Issue by Manta7388** [Auctionator/Auctionator#132]
Hi, your AddOn is wonderful.

I changed from AuctionLite (because it didnt work anymore) and used lovely the quantity function. 

Example: I want to buy 200 pieces of a Herb, then the AddOn marks the Auctions (cheapest) and i can click on buy, until i reach 200 pieces. 

I don't find the option in this AddOn, but i think it will help make it easier to use (to prevent calculate, how much i bought in the last few auctions).

**Comment by jrob8577** [comment]
Hi @Manta7388, thanks for the kind words!  

If you go to the Buy tab, and search for an item, then click on one of the results, you will see a window with a Buy button.  As long as additional items remain at that price, this window will stay open and allow you to continue purchasing, and show you the number you have purchased at that price.

Is this the functionality you are looking for?

**Comment by Manta7388** [comment]
if i bought over one of the result i get only the number of purchases of this result. If i want more as the result give me like 1000 pieces. and we have result like 1 with 15 pieces, 3 with 40...

**Comment by jrob8577** [comment]
If I am understanding correctly, you are requesting that the Buy pop up dialog continues to allow you to buy so long as results remain, even if those results are at a different price (i.e. a different row in the results listing).

Flagged as enhancement, we will investigate as time allows.

**Comment by Gorthezar** [comment]
I wanted to add to this slightly if I can to help you better understand what he is asking for as it is also a feature I would LOVE to see added as I also used Auctionlite and it was very helpful. The way the auction search worked with Auctionlite is you could search for a item and also add a number to it so say I was looking for 26 titanium ore like in the picture attached and you are then able to keep clicking the approve button to buy the cheapest listed auctions  until you have bought the amount you were looking for at which point the approve button goes away and you have finished buying however many of said item you wanted to buy.
![fac271b6c65a5b8614ce521aa88bdf20](https://cloud.githubusercontent.com/assets/20695078/17200507/d9c3747c-543a-11e6-8b2f-bdb702a92bcd.jpg)

**Comment by jrob8577** [comment]
Thanks for the clarification, @Gorthezar!

**Comment by Gorthezar** [comment]
No problem. any kind of ETA on this? I know it probably isn't a high priority at the moment.
