### ISSUE TITLE
Feature Request: per-item customizable notes in shopping list

### ISSUE THREAD

**Issue by Rezy942** [Auctionator/Auctionator#1320]
**Is your feature request related to a problem? Please describe.**
I like to use shopping list not only as a quick price-check, but also as a "shopping list" for certain items like battle pet crafts.
For example, to craft this pet I need 3 different items "A" "B" and "C".
I can add A B C to the shopping list, BUT i have no way to make a note on how many items I need to BUY for my craft.
My solution right now is to have excel list with my go-to crafted items. Otherwise I just cant remember without going to NPC or looking up wowhead.

**Describe the solution you'd like**
Allow us to set a custom note (or a dedicated item quantity field, which is still just a note) inside "edit shopping list item" menu.
Rough example:
![image](https://user-images.githubusercontent.com/122007087/211345451-16e98fd8-4ee3-44ca-9f75-700f75c82e0e.png)
To view note, user can hover over each item, and the tooltip will expand lower to show the note. If no note set, the tooltip remains unchanged.

Im not sure how many people are like me, but this would be a huge QoL change for mass production without using TSM or the likes.
Thank you, as always

**Comment by plusmouse** [comment]
This would only really be useful in conjunction with a feature that applies the quantity to the buy screen, or at least makes it visible. Auctionator doesn't have a buy screen to put the information onto (it uses the Blizzard ones as they're good enough)

**Comment by Rezy942** [comment]
You dont need any of that just to add a simple note function... literally a string of text when hovering over a shopping list item.....
What use is a shopping list when you need a spreadsheet to track how much you need to buy. ITEM + QTY is literally what s hopping list is.
Feels like you're just denying every request to avoid extra work, so you prefer leaving half-working features.
Anyway. I appreciate auctionator as it is, i wont hold my breath on anyone improving upon it so i'll just live with it.
