### ISSUE TITLE
Hide the Unhide all option. Pun not intended.

### ISSUE THREAD

**Issue by UnoneTV** [Auctionator/Auctionator#1321]
I once pressed it, then, months later, pressed it again. Each time, hundred of items were unhidden, and I needed to start over, hiding them, one by one. And EACH TIME that Unhide All option was literally 0.1 inch from the Hide one...

I need to consciously avoid pressing it, EACH TIME. It's literally 1 button to ruin all efforts of all time, of hiding items. And it's next to regularly pressed button. When I was never going to use it, there is no way to need to unhide every item, only some that are now optional for trading, it's a rare occasion even for 1 item. This mistake is so huge, that makes it look like mockery.

Hide the Unhide all option. Make it an option, in Addon Options. And make it call the "Are you sure?" tab, because it's that dangerous of an effort waster.

Alternative, just put it somewhere even deeper in Options. In Advanced.

Total: a harmful button, assuming the placement of it and its' functions.

**Comment by plusmouse** [comment]
Changed it in the latest alpha to ask for confirmation after hitting the unhide all button:
![image](https://user-images.githubusercontent.com/60280559/219744687-41c95689-98c3-4862-b5ba-99da76c5928e.png)
