### ISSUE TITLE
German localization issue

### ISSUE THREAD

**Issue by NVO88** [Auctionator/Auctionator#1323]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

selling "Rolle der Armschienenverzauberung - Außergewöhnliche Intelligenz"
"Rolle der Handschuhverzauberung - Außergewöhnliche Zaubermacht" will not work, as it does not find the correct items

searching for the item without "" (which are done automatically) will work
searching only for "Außergewöhnliche" will work
## Steps to Reproduce

search for "Rolle der Armschienenverzauberung - Außergewöhnliche Intelligenz"
"Rolle der Handschuhverzauberung - Außergewöhnliche Zaubermacht"

## Loaded Addons
alot
but the issue will occur aswell when you didnt load any other addons
i can upload a list if needed

## Back Trace (LUA Error Output)
no error, just not listing the items

<img width="1168" alt="image" src="https://user-images.githubusercontent.com/82704214/212840496-09587350-fab2-40b8-8a71-40aabc0918f2.png">
<img width="746" alt="image" src="https://user-images.githubusercontent.com/82704214/212840529-7dae7a05-345a-4f20-9b79-f98c261a4bc3.png">
<img width="790" alt="image" src="https://user-images.githubusercontent.com/82704214/212840604-125b230b-4d5a-4214-b8d1-b6a4916ab287.png">
<img width="796" alt="image" src="https://user-images.githubusercontent.com/82704214/212840846-27bb00ae-5adc-407f-b7e1-345bc12b7988.png">

**Comment by plusmouse** [comment]
No response. Closing.
