### ISSUE TITLE
Feature Request: Show # of items in bags when buying in "Buy" tab

### ISSUE THREAD

**Issue by Rezy942** [Auctionator/Auctionator#1324]
**Is your feature request related to a problem? Please describe.**
Right now, when buying up many different reagents, you have to manually check your bags to see how much you have, and how much you still need to buy. 1 item at a time. Super annoying as AH goblin / profession junkie, especially this expac.

**Describe the solution you'd like**
A simple counter in the item buy menu that shows total quantity of specific item you have in your bags, next to "Quantity" field for buying. This will make it easier to buy the difference, especially if you have full, messy bags!!

**Describe alternatives you've considered**
n/a

**Additional context**
![image](https://user-images.githubusercontent.com/122007087/212865263-568e98fc-e82b-4907-942c-321d793758d7.png)

**Comment by plusmouse** [comment]
Not going to add this - altering the Blizzard buy screens isn't something that will happen. If you need to check the count I'd suggest installing bagsync so it appears on the item's tooltip.

**Comment by Rezy942** [comment]
Unfortunate. Thank you for addon suggestion. Will look into it!
