### ISSUE TITLE
error

### ISSUE THREAD

**Issue by nanjuekaien1** [Auctionator/Auctionator#1327]
Version: 10.0.32
Interface: 30401

The search function of the shopping bar is invalid.
Info's historical records are invalid.

**Comment by plusmouse** [comment]
Can you screenshot the broken results/records and what they should be?

**Comment by nanjuekaien1** [comment]
CreateFrame: Unknown frame type 'AuctionatorBuyAuctionsResultsRowTemplate'
Count: 1

Call Stack:
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `CreateFrame'
[string "@SharedXML\Pools.lua"]:117: in function `creationFunc'
[string "@SharedXML\Pools.lua"]:50: in function `Acquire'
[string "@SharedXML\Scroll\ScrollBoxListView.lua"]:54: in function `factory'
[string "@SharedXML\Scroll\ScrollBoxListView.lua"]:287: in function `frameFactory'
[string "@SharedXML\Scroll\ScrollBoxListView.lua"]:217: in function `AcquireInternal'
[string "@SharedXML\Scroll\ScrollBoxListView.lua"]:250: in function `AcquireRange'
[string "@SharedXML\Scroll\ScrollBoxListView.lua"]:503: in function `Rebuild'
[string "@SharedXML\Scroll\ScrollBoxListView.lua"]:562: in function `ValidateDataRange'
[string "@SharedXML\Scroll\ScrollBox.lua"]:613: in function `Update'
...
[string "@SharedXML\CallbackRegistry.lua"]:118: in function <SharedXML\CallbackRegistry.lua:117>
[string "=[C]"]: ?
[string "@SharedXML\CallbackRegistry.lua"]:121: in function `TriggerEvent'
[string "@SharedXML\Scroll\ScrollBoxListView.lua"]:195: in function `SignalDataChangeEvent'
[string "@SharedXML\Scroll\ScrollBoxListView.lua"]:175: in function `SetDataProvider'
[string "@SharedXML\Scroll\ScrollBox.lua"]:563: in function `SetDataProvider'
[string "@AddOns\Auctionator\Source\Components\ResultsListing\Mixins\ResultsListing.lua"]:135: in function `UpdateTable'
[string "@AddOns\Auctionator\Source\Components\ResultsListing\Mixins\ResultsListing.lua"]:39: in function `onUpdate'
[string "@AddOns\Auctionator\Source\Components\DataProviders\DataProvider.lua"]:207: in function `CheckForEntriesToProcess'
[string "@AddOns\Auctionator\Source\Components\DataProviders\DataProvider.lua"]:26: in function <...tor\Source\Components\DataProviders\DataProvider.lua:24>

--------------------------------
CreateFrame: Unknown frame type 'AuctionatorShoppingResultsRowTemplate'
Count: 1

Call Stack:
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `CreateFrame'
[string "@SharedXML\Pools.lua"]:117: in function `creationFunc'
[string "@SharedXML\Pools.lua"]:50: in function `Acquire'
[string "@SharedXML\Scroll\ScrollBoxListView.lua"]:54: in function `factory'
[string "@SharedXML\Scroll\ScrollBoxListView.lua"]:287: in function `frameFactory'
[string "@SharedXML\Scroll\ScrollBoxListView.lua"]:217: in function `AcquireInternal'
[string "@SharedXML\Scroll\ScrollBoxListView.lua"]:250: in function `AcquireRange'
[string "@SharedXML\Scroll\ScrollBoxListView.lua"]:503: in function `Rebuild'
[string "@SharedXML\Scroll\ScrollBoxListView.lua"]:562: in function `ValidateDataRange'
[string "@SharedXML\Scroll\ScrollBox.lua"]:613: in function `Update'
...
[string "@SharedXML\CallbackRegistry.lua"]:118: in function <SharedXML\CallbackRegistry.lua:117>
[string "=[C]"]: ?
[string "@SharedXML\CallbackRegistry.lua"]:121: in function `TriggerEvent'
[string "@SharedXML\Scroll\ScrollBoxListView.lua"]:195: in function `SignalDataChangeEvent'
[string "@SharedXML\Scroll\ScrollBoxListView.lua"]:175: in function `SetDataProvider'
[string "@SharedXML\Scroll\ScrollBox.lua"]:563: in function `SetDataProvider'
[string "@AddOns\Auctionator\Source\Components\ResultsListing\Mixins\ResultsListing.lua"]:135: in function `UpdateTable'
[string "@AddOns\Auctionator\Source\Components\ResultsListing\Mixins\ResultsListing.lua"]:39: in function `onUpdate'
[string "@AddOns\Auctionator\Source\Components\DataProviders\DataProvider.lua"]:207: in function `CheckForEntriesToProcess'
[string "@AddOns\Auctionator\Source\Components\DataProviders\DataProvider.lua"]:26: in function <...tor\Source\Components\DataProviders\DataProvider.lua:24>

**Comment by nanjuekaien1** [comment]
3.4.0.47659

**Comment by nanjuekaien1** [comment]
Chinese server needs to use version 10.0.29, right?

**Comment by plusmouse** [comment]
10.0.31 should work too, but yeah, it needs an older version (as the newest version is for WoW 3.4.1)

**Comment by nanjuekaien1** [comment]
Just remembered, you updated today, the Chinese server did not update 3.4.1
my fault.
Sorry
