### ISSUE TITLE
Is this price really "a bit low?"

### ISSUE THREAD

**Issue by MarshallBuhl** [Auctionator/Auctionator#1328]
Please include as much of the following information as possible to help me fix the bug:

I don't know if it's a bug or a feature.  I'm trying to sell 16 jewels that vendor for 25s.  There are already 37 of them for sale for 9g. There's also one for sale for 416,000g!  When I propose selling them for 8g, I'm told the price is a bit low,  I probably couldn't sell them for more than 9g.  Is that one 416,000g auction affecting what Auctionator thinks is reasonable?  How do you make that computation?

Thanks, again, for such a great addon!

## Steps to Reproduce

N/A

## Loaded Addons

N/A

## Back Trace (LUA Error Output)

N/A

**Comment by plusmouse** [comment]
Its an unavoidable consequence of the low pricing check - it uses the auctions already on sale. This is for simplicity and to avoid historical data being skewed. It should be infrequent that it triggers though.
