### ISSUE TITLE
Net profit for selling

### ISSUE THREAD

**Issue by MarshallBuhl** [Auctionator/Auctionator#1329]
**Is your feature request related to a problem? Please describe.**

I currently have to use my aging noggin to determine how much profit I will make from a sale.  That's a problem!  :-)

**Describe the solution you'd like**

In the upper-right corner of the Selling window are the Deposit and Total Price.  What is most important to me would be just Gross Sale and Net Profit.  I don't really see a need for displaying the Deposit.  My suggested Gross Sale would be what is now called Total Price and my Net Profit would be Gross Sale minus the total Deposit and minus the vendor price.  You could probably eliminate the warning about being able to vendor the item(s) for more than you would make on the auction.

**Describe alternatives you've considered**

Leave the Deposit amount.
Keep the warning if people really want it.
Maybe even eliminate the Gross Sale.  All I really care about is how much profit I will make.

**Additional context**

N/A

**Comment by plusmouse** [comment]
The price would require additional explanation to most users as to why the amount they put in doesn't match the total. So not going to change it.
