### ISSUE TITLE
Feature Request: pre-configured per-expansion shopping lists (with community's help?)

### ISSUE THREAD

**Issue by Rezy942** [Auctionator/Auctionator#1330]
**Is your feature request related to a problem? Please describe.**
Would be great to have some pre-configured shopping lists available for user to opt-into in settings.
For example:

DF - Fishes:
** - fish A
** - fish B
and so on

It could be a checkbox in settings that would add or remove it from your shopping lists.
Right now, user would have to either add it all manually, or search online for a list. (im not sure where to search myself)

It would be sorted by expansions (work can start from latest expac, then go down to previous ones over time)
Perhaps we can use the community to help out with this and provide these lists?
I envision it being sorted by expansion first, then profession type.
Could also include other things like a full list of AH-bought mounts, high value battle pets, etc.

Just something to think about i guess :)

**Comment by plusmouse** [comment]
It isn't practical to create a large set of lists, and there will always be more items that could go in a list.

Using Wowhead's search tool and then exporting the item IDs to put in Auctionator is a good solution to the search problem though, as it offers just about any filtering you could want:
![image](https://user-images.githubusercontent.com/60280559/221880376-2954cce1-218c-428d-8180-944bf573ea36.png)

For example <https://www.wowhead.com/items/trade-goods/type:8?filter=166:217:69;10:1:1;0:0:0> the exported IDs are
```
200061, 200074, 197755, 199344, 197745, 197754, 194970, 197741, 194967, 194730, 194969, 194966, 194968
```
And then importing it into Auctionator and saving it with the name "Fish"
![image](https://user-images.githubusercontent.com/60280559/221881640-59bff13c-cce0-404e-81b2-5ddb5459b8fd.png)

There are a couple of items that aren't fish, but they're easy enough to remove when the list has been imported.

**Comment by Rezy942** [comment]
Wow didnt know I could do that. Thank you so much. :)
