### ISSUE TITLE
January 21 can't post auctions of multiple items.

### ISSUE THREAD

**Issue by Karnadas** [Auctionator/Auctionator#1333]
Please include as much of the following information as possible to help me fix the bug:

## Is this a bug or a feature request? Bug??

# Bug:
## Brief Description of Bug

_Please include a brief description of the bug, including what you were doing, and when it occurred._ Went to Orgrimmar auction house, tried to sell an item in stacks (Linen Cloth, Mutton Chop), it said max stacks and max size were both 0. Adding numbers in there greyed out the create auction button but leaving them blank posted one stack of one item instead of x stacks of y items.

ALSO on the legacy-wow page for this addon, clicking the download button downloads a zip file named Auctionator, but the contents are AtlasQuest.

## Steps to Reproduce

_Include the steps I would need to follow to reproduce the bug._

## Loaded Addons
 
_Include a list of addons you were running at the time this bug occurred._ Mapster, Pallypower Classic, Pawn, Questie, Slidebar.

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._ 

# Feature Request:
## Is your feature request related to a problem? Please describe
Describe the problem you are experiencing.

**Comment by plusmouse** [comment]
The latest version of Auctionator is available from https://addons.wago.io/addons/auctionator and https://www.curseforge.com/wow/addons/auctionator - any other source is unofficial and unsupported.
