### ISSUE TITLE
Price to craft for enchanting is always wrong

### ISSUE THREAD

**Issue by Tirkoue** [Auctionator/Auctionator#1334]
Please include as much of the following information as possible to help me fix the bug:

## Are you on the retail or the classic version of WoW?
Retail
## Is this a bug or a feature request?
Bug
# Bug:
## Brief Description of Bug

![image](https://user-images.githubusercontent.com/38634339/214116629-604dc2d9-1f38-47d5-890b-df82322a19bc.png)
Price to craft is obviously wrong I need to 3 dusts at 1g39 the dust cost should be over 3g not 60 copper

## Steps to Reproduce

Be enchanter, scan the AH or refresh prices, enchanting craft costs are always wrong._

## Loaded Addons

All addons removed only Auctionator is running.

**Comment by plusmouse** [comment]
Thanks for the report. Run this command to resolve the issue (resets the database that had the bad prices), and update to 10.0.35 when it releases to prevent this happening again
```
/run AUCTIONATOR_VENDOR_PRICE_CACHE = nil; Auctionator.Variables.InitializeVendorPriceCache()
```

**Comment by Tirkoue** [comment]
@plusmouse how did you know it was tournament realm? you are the best :)

**Comment by plusmouse** [comment]
Discovered that it was the strange vendor prices that affected the crafting cost when working with another user, and they remembered that the last time there had been a vendor with the reagents for the recipes was on a tournament realm.
