### ISSUE TITLE
tooltip lines

### ISSUE THREAD

**Issue by drsleo** [Auctionator/Auctionator#1336]
before AH price and vendor price was shown in the bottom last line of the tooltip, and now it is appearing in the middle of the tooltip, Is there any way to fix this, is it a bug or intentional?

**Comment by plusmouse** [comment]
That's a necessary change to prevent the prices not always showing if the item isn't in the game's item cache. Moving the order was an unintended side-effect of the fix.

There isn't a simple way to fix this.
