### ISSUE TITLE
Bug (or maybe feature request?): Alt + Right clicking item in "Selling" tab price update warning

### ISSUE THREAD

**Issue by Rezy942** [Auctionator/Auctionator#1337]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

With Dragonflight, i've seen a massive rise in AH automation bots posting items for 1 silver in low quantities to try and snipe people who arent paying attention. Now, blizzard by default warns users when price has changed. Auctionator currently in Alt + right click does not have that function, so what happens, is a user might be trying to quickly buy a low priced item he thinks costs 1 silver, but in reality the tooltip pops up for the lowest available price (which is usually regular price, because bots take 1s items off instantly).

## Steps to Reproduce

You can reproduce only if you have AH bots on your realm quickly putting low priced items on and off AH.
See screenshot example, what you see is me clicking on what i think is 14 silver item. But a pop up opens as 2g 45s.
![image](https://user-images.githubusercontent.com/122007087/214307786-342950fc-8e08-4aaf-8894-e14d7053ef27.png)

## Solution

Two ways i can think of:
1.  Do a price scan for that specific item when alt + right clicking. If item isnt available anymore for that price, the right click fails, or an error pops up. (preferably that you dont need to interact with, simply a popup that auto closes in a few seconds max)
2. If tooltip price doesnt match item price shown in the list, list will refresh and pop up will remain as it is. Except the list will now update. This option still has a chance someone might buy without paying attention to the tooltip.
3. Lastly you could combat the bots by adding a keybind option (something like ctrl + alt + right click) to buy the item but without price confirmation. IMPORTANT -> the keybind would fail if the price does not match what is shown. This would speed it up and allow users to snipe the bots back, as right now the confirmation tooltip is slowing it down enough for bot to remove his items. Just a possibility, might be stupid idea.

## Loaded Addons

n/a

## Back Trace (LUA Error Output)

n/a

**Comment by Rezy942** [comment]
Update: this problem is actually bigger than i thought. Auctionator does not properly update or warn user if the price changed.
Sometimes i get tooltip that shows low price, click buy, and then the actual price was the normal price.
It seems the bots are taking advantage of auctionator users doing this.

I hope you can find a fix for this soon, this is pretty bad :(

**Comment by plusmouse** [comment]
There isn't a fix, so I've removed the feature.

**Comment by Rezy942** [comment]
Thats unfortunate!! Its a great feature.
Any chance you can reconsider adding a link to Buy tab for the specific item "scalebelly mackerel' as example in screenshot?
Preferably by clicking the icon -> directs you to buy tab -> item name already pre-entered in search (and possibly the search function already initiated)
This would still allow somewhat-easy buying, but through blizzard default UI.

There is currently a disconnect between posting and buying the item that i would love to be solved :)
Thank you

**Comment by Rezy942** [comment]
Indeed. I would give up 1000 auctionator features to get this. I am AH goblin and it's really frustrating to not have this :( I hope the addon dev reconsiders :)
