### ISSUE TITLE
LUA Error when tracking recipe on Place Crafting Order window

### ISSUE THREAD

**Issue by fearkite** [Auctionator/Auctionator#1338]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

LUA error

## Steps to Reproduce

Track recipe on Place Crafting Order window

## Loaded Addons

NA~

## Back Trace (LUA Error Output)

Message: Usage: local recipeIDs = C_TradeSkillUI.GetRecipesTracked(isRecraft)
Time: Wed Jan 25 12:22:35 2023
Count: 1
Stack: Usage: local recipeIDs = C_TradeSkillUI.GetRecipesTracked(isRecraft)
[string "=[C]"]: in function `GetRecipesTracked'
[string "@Interface/AddOns/Auctionator/Source_Mainline/CraftingInfo/Mixins/ObjectiveTracker.lua"]:35: in function `IsAnythingTracked'
[string "@Interface/AddOns/Auctionator/Source_Mainline/CraftingInfo/Mixins/ObjectiveTracker.lua"]:24: in function `ShowIfRelevant'
[string "@Interface/AddOns/Auctionator/Source_Mainline/CraftingInfo/Mixins/ObjectiveTracker.lua"]:44: in function <...ce_Mainline/CraftingInfo/Mixins/ObjectiveTracker.lua:42>
[string "=[C]"]: in function `SetRecipeTracked'
[string "@Interface/AddOns/Blizzard_ProfessionsCustomerOrders/Blizzard_ProfessionsCustomerOrdersForm.lua"]:181: in function <...merOrders/Blizzard_ProfessionsCustomerOrdersForm.lua:179>

Locals: (*temporary) = "Usage: local recipeIDs = C_TradeSkillUI.GetRecipesTracked(isRecraft)"

**Comment by sehra** [comment]
```lua
Message: Usage: local recipeIDs = C_TradeSkillUI.GetRecipesTracked(isRecraft)
Time: Wed Jan 25 11:16:20 2023
Count: 5
Stack: Usage: local recipeIDs = C_TradeSkillUI.GetRecipesTracked(isRecraft)
[string "=[C]"]: ?
[string "=[C]"]: in function `GetRecipesTracked'
[string "@Interface/AddOns/Auctionator/Source_Mainline/CraftingInfo/Mixins/ObjectiveTracker.lua"]:35: in function `IsAnythingTracked'
[string "@Interface/AddOns/Auctionator/Source_Mainline/CraftingInfo/Mixins/ObjectiveTracker.lua"]:24: in function `ShowIfRelevant'
[string "@Interface/AddOns/Auctionator/Source_Mainline/CraftingInfo/Mixins/ObjectiveTracker.lua"]:44: in function <...ce_Mainline/CraftingInfo/Mixins/ObjectiveTracker.lua:42>

Locals:
```

**Comment by Rezy942** [comment]
Yep same. Tracking into shopping list is currently not working :(

19x Usage: local recipeIDs = C_TradeSkillUI.GetRecipesTracked(isRecraft)
[string "=[C]"]: in function `GetRecipesTracked'
[string "@Auctionator/Source_Mainline/CraftingInfo/Mixins/ObjectiveTracker.lua"]:35: in function `IsAnythingTracked'
[string "@Auctionator/Source_Mainline/CraftingInfo/Mixins/ObjectiveTracker.lua"]:24: in function `ShowIfRelevant'
[string "@Auctionator/Source_Mainline/CraftingInfo/Mixins/ObjectiveTracker.lua"]:44: in function <...ce_Mainline/CraftingInfo/Mixins/ObjectiveTracker.lua:42>
[string "=[C]"]: in function `SetRecipeTracked'
[string "@Blizzard_ProfessionsCustomerOrders/Blizzard_ProfessionsCustomerOrdersForm.lua"]:181: in function <...merOrders/Blizzard_ProfessionsCustomerOrdersForm.lua:179>

Locals:
(*temporary) = "Usage: local recipeIDs = C_TradeSkillUI.GetRecipesTracked(isRecraft)"

**Comment by plusmouse** [comment]
I've pushed a fixed version of Auctionator, which will be available from Curseforge and Wago when the build finishes.
