### ISSUE TITLE
single items vs stacks - fix included (by ceylina)

### ISSUE THREAD

**Issue by airleagach** [Auctionator/Auctionator#134]
when putting up a single item for sale in auctionator it works fine but for some reason when putting up stacks of items the big red CREATE AUCTIONS button and the per item buttons are overlaid. i'm submitting a screenshot so you can see what i'm talking about
![auc overlaid](https://cloud.githubusercontent.com/assets/20618975/17081112/49b3c2e8-5119-11e6-89c9-049a99f02429.jpg)

**Comment by airleagach** [comment]
again i have the newest version picked up from curse

**Comment by ceylina** [comment]
Oh that's not good. We'll do some more fine tuning of the layout. Thanks for pointing that out. :D

**Comment by ceylina** [comment]
Alignment adjustment in sell.xml.

Starting at line 235

`            <FontString name="Atr_StackPriceText" inherits="GameFontHighlightSmall" text="Buyout Price">
              <Anchors><Anchor point="TOPLEFT"><Offset><AbsDimension x="10" y="-72"/></Offset></Anchor></Anchors>
            </FontString>

            <FontString name="Atr_ItemPriceText" inherits="GameFontHighlightSmall" text="Item Price">
              <Anchors><Anchor point="TOPLEFT"><Offset><AbsDimension x="10" y="-118"/></Offset></Anchor></Anchors>
            </FontString>`

**Comment by ceylina** [comment]
Secondary option: revert back Button name="Atr_CreateAuctionButton" position.

sell.xml

line 376
change back to

                <Anchor point="TOPLEFT"><Offset><AbsDimension x="3" y="-170"/></Offset></Anchor>
