### ISSUE TITLE
Classic Era Bug when clicking "Selling" Button

### ISSUE THREAD

**Issue by maximus210793** [Auctionator/Auctionator#1341]
Hi,
I am playing WoW Classic Era.
When I click the auction house tab "Selling" I get the following error message:

---

27x ...or\Source_Classic\Utilities\ItemInfoFromLocation.lua:10: attempt to index local 'itemInfo' (a number value)
[string "@Interface\AddOns\Auctionator\Source_Classic\Utilities\ItemInfoFromLocation.lua"]:10: in function `ItemInfoFromLocation'
[string "@Interface\AddOns\Auctionator\Source\Tabs\DataProviders\Bag.lua"]:67: in function `LoadBagData'
[string "@Interface\AddOns\Auctionator\Source\Tabs\DataProviders\Bag.lua"]:13: in function `Reload'
[string "@Interface\AddOns\Auctionator\Source\Tabs\DataProviders\Bag.lua"]:33: in function <...AddOns\Auctionator\Source\Tabs\DataProviders\Bag.lua:29>
[string "=[C]"]: in function `Show'
[string "@Interface\AddOns\Auctionator\Source_Classic\Tabs\Mixins\TabButton.lua"]:34: in function `Selected'
[string "@Interface\AddOns\Auctionator\Source_Classic\Tabs\Mixins\TabContainer.lua"]:73: in function <...tionator\Source_Classic\Tabs\Mixins\TabContainer.lua:66>
[string "=[C]"]: in function `AuctionFrameTab_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals:
location = <table> {
 Clear = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:21
 IsEquipmentSlot = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:48
 IsEqualToBagAndSlot = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:60
 SetBagAndSlot = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:27
 IsBagAndSlot = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:52
 SetEquipmentSlot = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:38
 HasAnyLocation = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:56
 slotIndex = 1
 GetEquipmentSlot = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:44
 IsEqualToEquipmentSlot = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:68
 bagID = 0
 GetBagAndSlot = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:34
 IsEqualTo = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:76
}
icon = nil
itemCount = nil
quality = nil
itemLink = nil
_ = nil
currentDurability = nil
maxDurability = nil
itemInfo = 134497
(*temporary) = 0
(*temporary) = 1
(*temporary) = 134497
(*temporary) = 1
(*temporary) = false
(*temporary) = 3
(*temporary) = false
(*temporary) = false
(*temporary) = "|cff0070dd|Hitem:19260::::::::59:::::::::|h[Three of Warlords]|h|r"
(*temporary) = false
(*temporary) = "attempt to index local 'itemInfo' (a number value)"

---

Any Idea what I can do?
Thanks in advance!

**Comment by plusmouse** [comment]
Is this error still happening? It looks like a Blizzard API is returning no results when previously it could be expected to.

**Comment by lvangh** [comment]
Same error for me on Era  -- happened with .39 and .40

**Comment by plusmouse** [comment]
I'm going to close this issue as it isn't an Auctionator bug.

**Comment by lvangh** [comment]
Found the offending add-on - it's RCLootCouncil Classic 0.18.3
