### ISSUE TITLE
Suggestion / UI Improvement feedback

### ISSUE THREAD

**Issue by Rezy942** [Auctionator/Auctionator#1342]
Hello, thank you for all the great work you're doing!

I would like to see "Full Scan" button relocated to the first Buy tab.
Auto-scan on higher pop realms usually means you cant post auctions that well due to the long delay/lag until scan is finished.
So that means anytime i want to scan, i need to navigate another tab to click the button, then go back to previous tab I was at to buy items while the scan is on-going.

My preferred resolution:
1. Move just the scan button or COPY it to the first tab, perhaps here?:
![image](https://user-images.githubusercontent.com/122007087/215346482-91a308d9-79b7-41f0-b758-bb57fef8a930.png)

Alternatively, add another <optional> but slightly slower scan method that will not lag the item posting as much on higher pop realms. Usual item posting interaction is 20-60 seconds - perhaps slow it down to account for that? It would be optional toggle in settings.
This way users can set it to auto scan without expecting to afk in AH window until its done :)

Heck if its even possible, maybe let users choose 1-100% how fast the scan goes, so they can adjust it for their realm size.
Maybe not possible, i am no coder... just an idea :)

Lastly, a bit unrelated but "Auctionator" tab can probably be moved over to addon settings as front page, unless more visibility is the reason for it being there? It's taking an extra tab for no other reason than that, (from what I can see.)

Thank you for considering and i'll understand if this is not something you're interested in :)

**Comment by plusmouse** [comment]
The alternative "slower" method can take up to 30 minutes at peak times, so it isn't used in Auctionator. With the current method there isn't a way to slow down or restart the scan partway through.

Not going to add buttons to tabs other than the Auctionator tabs, so keeping it in a different tab is going to stay.

You can increase the scan interval for the auto scan, but if its getting in the way I'd suggest turning the autoscan off and doing a scan after you've finished posting.
