### ISSUE TITLE
Addon doesn't even show up when I go to AH

### ISSUE THREAD

**Issue by ZacAttac21** [Auctionator/Auctionator#1343]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

When I go to the AH, there's nothing but the default AH page.
![WoWScrnShot_020123_192248](https://user-images.githubusercontent.com/124221258/216208195-0dedbfbf-ec99-450a-b6ee-759c10762f7c.jpg)

## Loaded Addons

Atlas, Atlasloot, Auctionator, Questie, Tacotip, Weakauras, DBM

**Comment by plusmouse** [comment]
This usually happens when the retail version of Auctionator is installed on Wrath. Try using this file specifically https://www.curseforge.com/wow/addons/auctionator/files/4369240

**Comment by plusmouse** [comment]
Try extracting the files from the zip using this button - for some reason in some cases doing it by drop-and-drop or copy-and-paste glitches.
![image](https://user-images.githubusercontent.com/60280559/216315669-7bc9b06b-8b29-4adb-80d3-51c064bd6c7f.png)

**Comment by Milda47** [comment]
> Try extracting the files from the zip using this button - for some reason in some cases doing it by drop-and-drop or copy-and-paste glitches. ![image](https://user-images.githubusercontent.com/60280559/216315669-7bc9b06b-8b29-4adb-80d3-51c064bd6c7f.png)

Still the same. But what I realized is that in the addon section auctionator shows as out of date version for some reason. Maybe thats the issue but I have no idea why it shows up. 
![image](https://user-images.githubusercontent.com/124261399/216317519-e73fd4c3-37fc-412a-86d2-2a177664c48a.png)

**Comment by plusmouse** [comment]
Can you screenshot the contents of your Interface/AddOns/Auctionator folder?

**Comment by Milda47** [comment]
> Can you screenshot the contents of your Interface/AddOns/Auctionator folder?

![image](https://user-images.githubusercontent.com/124261399/216319008-12dadea4-0ec1-43b9-93f8-6f6d2a3da49e.png)
here you go

**Comment by plusmouse** [comment]
Those files are for the retail version of Auctionator. Make sure the .zip you've got contains `-wrath` in its name.

**Comment by Milda47** [comment]
> Those files are for the retail version of Auctionator. Make sure the .zip you've got contains `-wrath` in its name.

Aaaaa it is working. Thank you so much. I downloaded wrath version but it seems the retail folders were not replaced with copy and paste but with extract all it is working. :)

**Comment by ZacAttac21** [comment]
> This usually happens when the retail version of Auctionator is installed on Wrath. Try using this file specifically https://www.curseforge.com/wow/addons/auctionator/files/4369240

I was wondering if that might be the problem. Thanks!
