### ISSUE TITLE
Feature Request: disable opening bags when visiting auction house

### ISSUE THREAD

**Issue by Rezy942** [Auctionator/Auctionator#1344]
I could not find this option anywhere - is it possible to add this as a toggle in addon settings?
Auctionator does great in its UI so that bags are no longer needed (as much).
I would prefer to not auto-open them when visiting AH.
Currently everytime i open AH i have to manually close, especially annoying with other windows to the side that you need to view.

Thank you

**Comment by plusmouse** [comment]
This isn't possible, as it would break the bag items causing issues with using them later on. https://github.com/Stanzilla/WoWUIBugs/issues/310
