### ISSUE TITLE
mousing over "tracked" recipes in the quest log throws lua error

### ISSUE THREAD

**Issue by ScottIngram** [Auctionator/Auctionator#1345]
## Brief Description of Bug

mousing over a "tracked" recipes in the quest log throws lua error

## Steps to Reproduce

choose a crafting recipe from your journal -- mine was [Dragon Isles Tailoring: Dragoncloth Tailoring Vestments]
click "track recipe"
mouse over its listing in the quest log
enjoy lua vomit

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

Message: Usage: local info = C_TradeSkillUI.GetCraftingOperationInfo(recipeID, craftingReagents [, allocationItemGUID])
Time: Sun Feb  5 10:50:20 2023
Count: 2
Stack: Usage: local info = C_TradeSkillUI.GetCraftingOperationInfo(recipeID, craftingReagents [, allocationItemGUID])
[string "=[C]"]: in function `GetCraftingOperationInfo'
[string "@Interface/AddOns/Auctionator/Source_Mainline/CraftingInfo/Main.lua"]:79: in function `GetOutputItemLink'
[string "@Interface/AddOns/Auctionator/Source/Tooltips/Hooks.lua"]:77: in function `handler'
[string "@Interface/AddOns/Auctionator/Source/Tooltips/Hooks.lua"]:288: in function <...terface/AddOns/Auctionator/Source/Tooltips/Hooks.lua:281>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:60: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:55>
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:80: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:76>
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:116: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:106>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:141: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:134>
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:278: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:236>
[string "=[C]"]: in function `securecallfunction'
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:233: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:232>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/!KalielsTracker/KalielsTracker.lua"]:994: in function `OnBlockHeaderEnter'
[string "@Interface/AddOns/!KalielsTracker/KalielsTracker.lua"]:1094: in function <Interface/AddOns/!KalielsTracker/KalielsTracker.lua:1093>

Locals: (*temporary) = "Usage: local info = C_TradeSkillUI.GetCraftingOperationInfo(recipeID, craftingReagents [, allocationItemGUID])"

**Comment by plusmouse** [comment]
Fixed in the latest alpha available here, and from Wago/Curseforge when it finishes processing:
[Auctionator-10.0.36-6-gc0dee79.zip](https://github.com/Auctionator/Auctionator/files/10611937/Auctionator-10.0.36-6-gc0dee79.zip)
