### ISSUE TITLE
Cosmetic indicator when buying

### ISSUE THREAD

**Issue by MarshallBuhl** [Auctionator/Auctionator#1346]
**Is your feature request related to a problem? Please describe.**
Not really.  I guess the problem is that I bought some cosmetic items thinking they were actual gear so I could disenchant them.  I can hover over the item to see if it's a fake, but it just slows the process down.

**Describe the solution you'd like**
When you look for weapons/armor, the search feature also lists cosmetic items.  I don't know if it's possible, but it would be great if there's a way to not include cosmetic items in the search results.

**Describe alternatives you've considered**
Maybe add something like "-C" to the end of the name to flag is as being fake gear.

**Additional context**
n/a

**Comment by plusmouse** [comment]
An indicator or change the filters isn't needed, and the simplest solution is to use a shopping list with the Plate, Leather, Mail and Cloth categories explicitly stated, as Cosmetic is a separate group
![image](https://user-images.githubusercontent.com/60280559/224828403-9c13aa0e-2d1a-4cba-b70d-bbe3a07130e5.png)
![image](https://user-images.githubusercontent.com/60280559/224828517-bd9f8853-8bd9-4754-bd74-ae067943c9c9.png)

**Comment by MarshallBuhl** [comment]
Thanks.  I'll investigate it.
