### ISSUE TITLE
Auction House Messages in Chat

### ISSUE THREAD

**Issue by Ssesmar** [Auctionator/Auctionator#1347]
Hello, I wanted to ask if it is possible to get chat messages about sold auctions no matter where you are? 
Since I have the Blizzard error of not getting any more auction messages in the chat as soon as I close the auction house window and Blizzard itself doesn't know how to help. 
But now I've seen as a test, TSM adds such a message in the chat again, but I'm personally not a fan of TSM because I've been using Auctionator for years

Here are a few links in German and English that have the same problems as me
[https://eu.forums.blizzard.com/en/wow/t/not-getting-the-auction-sold-message-in-chat-anymore/352569](url)
[https://eu.forums.blizzard.com/en/wow/t/still-cant-see-buyer-has-been-found-messages-its-been-over-half-year-now-with-no-response/404538](url)
[https://eu.forums.blizzard.com/de/wow/t/auktionshaus-chat/191818](url)
[https://eu.forums.blizzard.com/de/wow/t/auktionshauschat-problem/224834](url)

**Comment by plusmouse** [comment]
This is very much something Blizzard should fix. Not going to add it to Auctionator, but, I've put the fix in a separate mini-addon.

Download it from here for now 
[RestoreAuctionSoldNotification-1.0.zip](https://github.com/Auctionator/Auctionator/files/10676064/RestoreAuctionSoldNotification-1.0.zip)

You will be able to find it at https://addons.wago.io/addons/restore-auction-sold-notification and https://www.curseforge.com/wow/addons/restore-auction-sold-notification when the sites approve the addon creation.

**Comment by Ssesmar** [comment]
ty now i got the notifications back , works great
