### ISSUE TITLE
selling-tab is missing alt-right-click to buy

### ISSUE THREAD

**Issue by paul-tergeist** [Auctionator/Auctionator#1348]
Please include as much of the following information as possible to help me fix the bug:

In older versions it was possible to buy by holding alt and clicking (I think it was right clicking)  to buy items from other people.
Since the last update that does not work anymore. (no error message)

**Comment by AngeloRiega** [comment]
Same problem here, it was very helpful

**Comment by plusmouse** [comment]
I've restored the purchase shortcut, available in 10.0.38 (from Curseforge/Wago when it finishes processing, or below)

[Auctionator-10.0.38.zip](https://github.com/Auctionator/Auctionator/files/10695223/Auctionator-10.0.38.zip)
