### ISSUE TITLE
Profit on crafting incorrect

### ISSUE THREAD

**Issue by dilvishdamned** [Auctionator/Auctionator#1350]
You can clearly see highest sell price is 1500g, but Auctionator is stating the profit is 2,236g 90s

![image](https://user-images.githubusercontent.com/60253285/218193410-0fdb7bc7-10c9-4531-b2f6-9221300764b9.png)

**Comment by plusmouse** [comment]
Can you screenshot the tooltip for the crafting result?

![image](https://user-images.githubusercontent.com/60280559/218194612-282f1bde-5188-46e0-9d1e-87276924bd86.png)

Using Windows + Shift + S will let you screenshot part of your screen.

**Comment by dilvishdamned** [comment]
![shhiii](https://user-images.githubusercontent.com/60253285/218195406-442b6501-d1aa-4262-80a9-47a3b75a75bb.png)

**Comment by plusmouse** [comment]
I think what has happened is that the last 337 visible on the AH was at approx 2,658g and that leftover price is being used in the profit calculation

**Comment by dilvishdamned** [comment]
weird, but that could make sense.  Thank you for prompt replies!

**Comment by Crafter90** [comment]
I think there is still an issue with the profit calculation. 

For example, in the cooking profession, the cost to craft an item is 1.315 gold per item. The going price is 1.75 which is a profit of 0.435, yet Auctionator displays a profit of 1.39 gold per item.

If im reading it wrong, please correct me

Attached are the 
![Cooking profit](https://user-images.githubusercontent.com/125540294/219291677-8815a9fd-4274-4137-9de3-aaf463265d52.PNG)
files
![cooking auction price](https://user-images.githubusercontent.com/125540294/219291684-5d51e49b-23e1-4482-86ec-d409d0db23b3.PNG)

**Comment by plusmouse** [comment]
@Crafter90   The profit and to craft values apply to the entire crafting operation, including all 4 result items. So its not a surprise that the profit is 4 times the per-item profit (after the 5% ah cut is removed).

**Comment by Crafter90** [comment]
ah ok that makes sense. thank you

**Comment by plusmouse** [comment]
This is a known behaviour, and expected, so closing the issue
