### ISSUE TITLE
Filter by expansion in buying tab

### ISSUE THREAD

**Issue by gouges2** [Auctionator/Auctionator#1351]
Please include as much of the following information as possible to help me fix the bug:

## Is this a bug or a feature request?  Feature

# Bug:
## Brief Description of Bug

_Please include a brief description of the bug, including what you were doing, and when it occurred._

## Steps to Reproduce

_Include the steps I would need to follow to reproduce the bug._

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

# Feature Request:
## Is your feature request related to a problem? Please describe
Describe the problem you are experiencing.  No problem just nice to have.

## Describe the solution you'd like
Ability to filter by expansion in buying tab.

## Describe alternatives you've considered
A clear and concise description of any alternative solutions or features you've considered. None

**Comment by plusmouse** [comment]
Auctionator doesn't edit the "Buying" tab, so the option won't be added to that. This issue is similar to #1293 - which refers to the Shopping tab, which is managed by Auctionator, any updates to include an expansion filter will be tracked there.
