### ISSUE TITLE
Show value of item on Auction House in Crafting View

### ISSUE THREAD

**Issue by theoriginalmre** [Auctionator/Auctionator#1352]
In the Crafting View, rather than having to mouse-over the item to see the Auction House value, please can you implement it on the crafting view alongside the "To craft" and "Profit" values. 

If possible, it would be preferable to have it show on the left-side pane next on the same line as the craftable item, so that we don't need to keep clicking individual lines just to see the value.

**Comment by plusmouse** [comment]
There's other addons that do this for the crafting view. Auctionator isn't going to add to the lists, as those can be awkward to add details too, making it glitchy.
