### ISSUE TITLE
internal auction error

### ISSUE THREAD

**Issue by WTBpvpbalance** [Auctionator/Auctionator#1354]
Please include as much of the following information as possible to help me fix the bug:

## Steps to Reproduce
click the cancel undercuts button on a stack of individually listed items of the same kind - it will work on solo items but when it gets to a stack of an item that is individually listed it will give the internal auction error either randomly or repeatedly but if you keep spamming it it will eventually work - also got this bug while trying to list items for sale. happens when i try to list a stack of items for sale individually. it will eventually do it but it gives error a few pieces in so have to keep spamming it

## Loaded Addons
have been using the same addons on sales alt together for a long time so i doubt it is being caused by other addons - but i have these enabled - Atlasloot, Bartender4, Chatcopypaste, Postal, Spy, Bagnon

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by plusmouse** [comment]
This is a Blizzard issue and there isn't anything Auctionator can do to mitigate it
