### ISSUE TITLE
Feature request: hotkey to post/scan

### ISSUE THREAD

**Issue by joshuaboele** [Auctionator/Auctionator#1356]
**Is your feature request related to a problem? Please describe.**

When posting large amount of auctions that get undercut quite often, it's a PITA to manually click it. 

**Describe the solution you'd like**

I would love to see something similar to TSM's keybind post/cancel. Like shift + scrollUp or something.

**Describe alternatives you've considered**

I only use TSM for this, but it's a bloated AddOn and has a lot of taint issues which is why I would love to go back to auctionator.

**Comment by plusmouse** [comment]
Already in Auctionator. You can use [Space] to post when on the Selling tab, and [Space] to cancel when on the Cancelling tab after an undercut scan.

**Comment by plusmouse** [comment]
You can pick different keyboard/mouse shortcuts in the settings
