### ISSUE TITLE
If the itemis stacked still goes to the next

### ISSUE THREAD

**Issue by Machou** [Auctionator/Auctionator#1358]
Hello,

I don't know if it's a bug, but when I sell, if item I sell is in a pile, it still goes to the next one.

I don't know if it's recurrent, but before, you could split a pile, which was much better, now I have to go over the item again.

So, with 2 items it's not a big deal, but when I have 100 items, it starts to become a problem.

Maybe can you add a split option, or other ?

Regards

**Comment by plusmouse** [comment]
You don't need to split stacks on retail - a player can buy any portion of a stack you post.
