### ISSUE TITLE
Feature Request: set auction duration based on item type

### ISSUE THREAD

**Issue by Rezy942** [Auctionator/Auctionator#1359]
Hello,

A really big annoyance I have is with auction timers.
Currently I see only one toggle for ALL item types:
![image](https://user-images.githubusercontent.com/122007087/221181906-04983bb0-1f48-4f63-adda-233be9edf7a7.png)

What I would like is a toggle by item type. Mainly to set armor/weapons/transmog/pets to 48 hours as they take FOREVER  to sell!!!
Currently I am forced to set everything to 24 hours because 48 hrs on regular items gets pretty expensive + they sell very fast...
I know I can manually set duration to 48 hours as i post, but that gets annoying very fast.

Is this at all possible?
Preferably BY ITEM TYPE toggle, but most important for me is gear (incl. transmog items) + battle pets.

Thank you

**Comment by plusmouse** [comment]
Auctionator used to split the settings between gear/pets vs commodities, but the feature had so little use that there were no complaints when it was removed.

**Comment by plusmouse** [comment]
Not going to do this as it would complicate the settings, and previously having separate settings resulted in users getting confused when they change the duration in one place and it doesn't appear to work.

**Comment by Rezy942** [comment]
Not sure what kind of people you got opinions from but it was super useful back in the days. Anyways, not a big loss.
