### ISSUE TITLE
Problem when selling recipes

### ISSUE THREAD

**Issue by jrob8577** [Auctionator/Auctionator#136]
## Brief Description of Bug

I'm having an issue with trying to list and sell recipes, I'm not sure if it's an Auctionator problem or not.

When going to sell a recipe it doesn't bring up any other listings of that same item and you have to search outside of the Auctionator sell tab to see prices/other listings.

It seems to be having a problem with the colon on recipes as it's only copying the first part of the name of each recipe item.

It only puts in Plans or Pattern and nothing else instead of the full name like Pattern: Shiny Cloak of Shiny Shine for example.

## Steps to Reproduce

_Include the steps I would need to follow to reproduce the bug._

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by jrob8577** [comment]
Copied from [curse comment](http://mods.curse.com/addons/wow/auctionator?comment=6070)

**Comment by ceylina** [comment]
Can't reproduce. Tried with a recipe, plan, and a pattern I had in my inventory and all we able to be put up for sale, had pricing data, and I was able to type the name in the buy tab and pull up to buy them.

Most likely there is a semi colon in the name, they are not running 4.0.5, or they have a shopping list that needs editing to change the semi colons to colons.

**Comment by jrob8577** [comment]
Thanks for investigating, closing.
