### ISSUE TITLE
Bug/feature request: Kaliel's tracker - tracking recipe to post shopping list unavailable

### ISSUE THREAD

**Issue by Rezy942** [Auctionator/Auctionator#1362]
Can we get the button support in Kaliels tracker please?
Thank you!
![image](https://user-images.githubusercontent.com/122007087/222937528-4d4b93b0-e7e2-485a-9169-1c19d4cc1a92.png)
This is for retail - sorry

**Comment by plusmouse** [comment]
That's an issue for Kaliel's tracker not Auctionator. Auctionator is designed to work with the default UI and to not conflict with other UIs.
