### ISSUE TITLE
Feature Request: tally up all the materials when tracking recipes

### ISSUE THREAD

**Issue by Rezy942** [Auctionator/Auctionator#1363]
Hello,

The button to add tracked recipes into shopping list is fantastic!
One major problem im sure most users are having is tallying up all the materials required
Say I add 10 different recipes to the tracker - I then have to manually look through the list and count total of each material i need
This takes SO long and just plain sucks!

Is there any chance at all that you can incorporate some kind of feature to combat this?
Ideally if i track 10 different recipes - there will be some place that spits out total quantity required for each item.

Thank you..

**Comment by plusmouse** [comment]
This would be better as a separate crafting focussed addon, so not going to add it to Auctionator

**Comment by Rezy942** [comment]
Too bad. This feature is insanely bad for tracking multiple recipes with many different items.
Hopefully someone comes up with a solution. 
I love auctionator but anything shopping list related is awful, im sorry. Just constructive criticism.
Majority of users just dont go on github to write it out, they just deal with it.
