### ISSUE TITLE
Feature Request: Add actual price on craft items separate line not when hit cursor and add more items to scanning

### ISSUE THREAD

**Issue by HASHMAX** [Auctionator/Auctionator#1364]
Hello!

**First:**
Add please to scanning system and leveling items for cancel auction this items cuz when i pressed scan then addon not showed lower price yellow marker on this positions.

https://i.postimg.cc/qpFZkfR9/2023-03-10-09-46-09.png
https://i.postimg.cc/TfC445X2/2023-03-10-09-46-52.png
https://i.postimg.cc/ZJnMtYT8/2023-03-10-09-47-22.png

https://www.wowhead.com/item=9424/ginn-su-sword
https://www.wowhead.com/item=177809/lithe-rapier
https://www.wowhead.com/item=177808/reinforced-rapier
https://www.wowhead.com/item=170119/slithershell-warglaive
https://www.wowhead.com/item=25147/skystrider-katana
https://www.wowhead.com/item=94213/bloodtusk-shoulderpads

And even when someone bets at the same price as yours.

and check please this items for scanning

https://www.wowhead.com/item=8190/hanzo-sword
https://www.wowhead.com/item=9393/beacon-of-hope
https://www.wowhead.com/item=2801/blade-of-hanna

there is no way to check, but in my opinion they also did not show a price reduction (maybe cuz alot of ilvl types)

**Second:**
Move or create line with actual price under crafting item cuz it is extremely inconvenient to point cursor at item all time to see current price, especially when you switch quickly between 4-5 items

https://i.postimg.cc/pWCfL8Cp/2023-03-10-09-57-25.png

_I have been waiting for a long time for you to make these changes, but I had to go to you myself and ask! thanks for your hard work!_

_THANKS!_

**Comment by HASHMAX** [comment]
Updated list of items that do not show a price reduction

**Comment by plusmouse** [comment]
Can you screenshot the buy listing for an item that isn't showing as undercut?

**Comment by HASHMAX** [comment]
> Can you screenshot the buy listing for an item that isn't showing as undercut?

Updated list of items again, please check.

I know that this is still stretching from Legion addon, with me and adds more items with no scan.

And ill show u screenshots about 2 items cuz all auction was canceled today, another i can show u some later if u need. but i hope u trust me and check code for this items and solve the problem like this.

https://www.wowhead.com/item=25147/skystrider-katana
https://i.postimg.cc/4JYPzpkq/2023-03-12-10-21-15.png
https://i.postimg.cc/Zb3LQZqL/2023-03-12-10-21-49.png

https://www.wowhead.com/item=94213/bloodtusk-shoulderpads
https://i.postimg.cc/dJHnk4XG/2023-03-12-10-22-48.png
https://i.postimg.cc/dqgBnDJ1/2023-03-12-10-23-25.png

**Comment by plusmouse** [comment]
I can see why it isn't doing the price check you are looking for - the scan doesn't compare to other items that are the same but with a different item level.

This pre-release build will do the scan the way you're looking for for any items with an ilvl of less than 168
[Auctionator-10.0.40-1-g1d1faf6.zip](https://github.com/Auctionator/Auctionator/files/10950807/Auctionator-10.0.40-1-g1d1faf6.zip)

**Comment by HASHMAX** [comment]
> I can see why it isn't doing the price check you are looking for - the scan doesn't compare to other items that are the same but with a different item level.
> 
> This pre-release build will do the scan the way you're looking for for any items with an ilvl of less than 168 [Auctionator-10.0.40-1-g1d1faf6.zip](https://github.com/Auctionator/Auctionator/files/10950807/Auctionator-10.0.40-1-g1d1faf6.zip)

THANKS!!! i all works!

except, need to wait some time for:
https://www.wowhead.com/item=177809/lithe-rapier
https://www.wowhead.com/item=177808/reinforced-rapier

and check.

**Comment by HASHMAX** [comment]
https://www.wowhead.com/item=177809/lithe-rapier
https://www.wowhead.com/item=177808/reinforced-rapier

Not work scan

https://i.postimg.cc/9c0kYC0n/2023-03-13-10-24-44.png
https://i.postimg.cc/c1d9gNPT/2023-03-13-10-27-34.png

I thought it was strange why up to ilvl 168, you cant immediately raise the ceiling to the maximum? what would it look for up to 405 or 424? to avoid some innovations from Blizzard?

reinforced-rapier and lithe-rapier has 170 ilvl

cuz rapiers checked scan for a decrease, it turned out not to work, please put ceiling much higher, suddenly other scaled things from the old world will appear that will be 180 ilvl, such as from time travel

**Comment by plusmouse** [comment]
Added the undercut scan change as an option. To get the behaviour you want untick this box:
![image](https://user-images.githubusercontent.com/60280559/225848852-d6042b75-2cfb-40b8-b43c-0fcad661ca86.png)

Available in the alphas from Curseforge/Wago shortly or from here [Auctionator-10.0.40-9-g8b06108.zip](https://github.com/Auctionator/Auctionator/files/10999174/Auctionator-10.0.40-9-g8b06108.zip)

**Comment by plusmouse** [comment]
The craft line will be tracked in #1352

**Comment by HASHMAX** [comment]
> Added the undercut scan change as an option. To get the behaviour you want untick this box: ![image](https://user-images.githubusercontent.com/60280559/225848852-d6042b75-2cfb-40b8-b43c-0fcad661ca86.png)
> 
> Available in the alphas from Curseforge/Wago shortly or from here [Auctionator-10.0.40-9-g8b06108.zip](https://github.com/Auctionator/Auctionator/files/10999174/Auctionator-10.0.40-9-g8b06108.zip)

Not work, i just tested on https://www.wowhead.com/item=2801/blade-of-hanna

Check
https://i.postimg.cc/y6sg5tJW/2023-03-17-18-44-51.png
https://i.postimg.cc/6wXvy2Hw/2023-03-17-18-45-31.png

**Comment by plusmouse** [comment]
This isn't something that can be reliably tracked. If you want to make sure your gear comes first no matter a user's setup you'll need to undercut the competition rather than just match them.

**Comment by plusmouse** [comment]
Although I can look at showing an undercut highlight when the others match your price if that's better?

**Comment by HASHMAX** [comment]
> Although I can look at showing an undercut highlight when the others match your price if that's better?

Your tracking technology about fact that price of lot was interrupted or set same initially worked properly until the levels of things appeared, I see no problem just registering this in your addon, and doing it as it was and what would ANY thing of a similar name or another ilvl was displayed in cancel window and highlighted in yellow, I didnt quite understand what you wrote, even translator used, dont understand anyway.

Perhaps you didnt understand me, pay attention to screenshot, the hannahs blade is not highlighted in yellow, and addon does not report that someone put this item at a price lower or same.

I do not want to undermine any competition, I want to systematically set price a little lower, as it has always been.

**Comment by HASHMAX** [comment]
Thank you for your efforts anyway! but it doesnt work as it should. In general, you understand problem, addon does not show a price reduction as before for some equipment.

I dont worry about it anymore.

**Comment by plusmouse** [comment]
Does the feature added help at all?

**Comment by HASHMAX** [comment]
> Does the feature added help at all?

I dont know what function exactly, it helped on many items up to level 168 when it was fixed for first time,

https://www.wowhead.com/item=8190/hanzo-sword
https://www.wowhead.com/item=9393/beacon-of-hope

Worked before last fix, now i dont know.

**Comment by HASHMAX** [comment]
I dont know what you did, but an update was released on course, and everything returned as it was, scanning does not work again, addon works as it was before my appeal, as I understand it all innovations were removed, list of things that I indicated again stopped showing a price reduction
