### ISSUE TITLE
Feature Request: Add-move line option % or FIXED price to sell window from addon settings

### ISSUE THREAD

**Issue by HASHMAX** [Auctionator/Auctionator#1366]
Hello again!

I, as someone who trades a lot, both stones and things, would like to see a fixed price setting or a percentage reduction right in sell window, because I start sell weapons, books, then I start trading stones and putting up 2 pieces with a decrease of 5-6 silver, and it is most profitable to reduce weapons by 1% and more, depending on valuable.

In this regard, it is extremely inconvenient to run all the time in the settings, I endured this for a long time, now I have come to you with requests!

https://i.postimg.cc/592g9tWq/2023-03-12-22-07-08.jpg

Have a chance get this cool feature?

**Comment by plusmouse** [comment]
Not going to add new UI for changing undercut settings on the fly. You can use
```
/atr config undercut_percentage 2
``` to change the undercut percentage to 2% without opening settings though

**Comment by HASHMAX** [comment]
> Not going to add new UI for changing undercut settings on the fly. You can use
> 
> ```
> /atr config undercut_percentage 2
> ``` to change the undercut percentage to 2% without opening settings though
> ```

I dont understand refusal, but ok, I understand you, functionality and simplicity are not relevant, its better to click 100 times and go to settings.

Thanks!
