### ISSUE TITLE
Can't list items with bid only price in selling tab

### ISSUE THREAD

**Issue by zeenk** [Auctionator/Auctionator#1369]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

Not sure if this is a bug or intended but you can't post items with only bid price (button greyed out until u also put a buyout price)
Have to swap to default sell tab if you want to do that otherwise.

![2023-03-15_07-12-31](https://user-images.githubusercontent.com/68170439/225223139-5e56d70c-3004-4b70-b87e-f8c056a0d093.png)

**Comment by plusmouse** [comment]
Fixed in the latest alpha (available shortly).
