### ISSUE TITLE
my auctionator doesnt work anymore

### ISSUE THREAD

**Issue by Gandalf710** [Auctionator/Auctionator#137]
Interface\AddOns\Auctionator\AuctionatorLocalize.lua:324: attempt to call global 'GetAuctionItemClasses' (a nil value)
------------
VERS:3.2.6   MEM: 18468 KB   DB:35962   SE:0  SL:2  FSCHUNK:<nil>  DBVERS:4
------------
REALMS: , The Forgotten Coast_Horde (10077), Fizzcrank_Alliance (0), Dalaran_Horde (0), Dalaran_Alliance (35962)
------------
STACK: GetAuctionItemClasses > Atr_GetAuctionClasses > Atr_ItemType2AuctionClass > Atr_IsWeaponType > Atr_CalcDisenchantPrice > Atr_STWP_GetPrices > Atr_ShowTipWithPricing > SetBagItem > ContainerFrameItemButton_OnEnter
------------
ADDONS: , Auctionator

**Comment by ceylina** [comment]
You need to update to at lease version 4.0.5 as the version you have is not compatible with the pre patch in game.

http://wow.curseforge.com/addons/auctionator/files/
