### ISSUE TITLE
LUA errors for Abominable Stitching

### ISSUE THREAD

**Issue by hollo6** [Auctionator/Auctionator#1370]
## Brief Description of Bug
Getting LUA errors on a lot of recipes when selected in Abominable Stitching.
Not doing anything, just opening the interface and selecting something, e.g. Bindings of Wellbeing, Bonesewn Fleshroc, etc.
From clicking around the recipes, it seems the ones containing Superior Parts produce the error.

## Steps to Reproduce
1. Go to the Stitchyard.
2. Open Abominable Stitching interface.
3. Select Bindings of Wellbeing recipe.

## Loaded Addons
(only the ones that might be remotely relevant)
Advanced Interface Options
ArkInventory
CraftSim
RECraft

## Back Trace (LUA Error Output)
15x Auctionator/Source/API/Internal.lua:2: Contact the maintainer of Reagent Search to resolve this problem. Details: Usage Auctionator.API.v1.GetVendorPriceByItemID(string, number)
[string "=[C]"]: in function `error'
[string "@Auctionator/Source/API/Internal.lua"]:2: in function `ComposeError'
[string "@Auctionator/Source/API/v1/GetVendorPrice.lua"]:5: in function `GetVendorPriceByItemID'
[string "@Auctionator/Source_Mainline/CraftingInfo/Main.lua"]:3: in function <...ns/Auctionator/Source_Mainline/CraftingInfo/Main.lua:2>
[string "@Auctionator/Source_Mainline/CraftingInfo/Main.lua"]:17: in function <...ns/Auctionator/Source_Mainline/CraftingInfo/Main.lua:14>
[string "@Auctionator/Source_Mainline/CraftingInfo/Main.lua"]:60: in function <...ns/Auctionator/Source_Mainline/CraftingInfo/Main.lua:44>
[string "=(tail call)"]: ?
[string "@Auctionator/Source_Mainline/CraftingInfo/Professions.lua"]:174: in function <...ionator/Source_Mainline/CraftingInfo/Professions.lua:173>
[string "@Auctionator/Source_Mainline/CraftingInfo/Professions.lua"]:198: in function `GetInfoText'
[string "@Auctionator/Source_Mainline/CraftingInfo/Mixins/Professions.lua"]:79: in function `UpdateTotal'
[string "@Auctionator/Source_Mainline/CraftingInfo/Mixins/Professions.lua"]:13: in function <.../Source_Mainline/CraftingInfo/Mixins/Professions.lua:10>
[string "=[C]"]: in function `Init'
...
[string "@SharedXML/CallbackRegistry.lua"]:146: in function `TriggerEvent'
[string "@Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeList.lua"]:125: in function <...fessionsTemplates/Blizzard_ProfessionsRecipeList.lua:112>
[string "=[C]"]: ?
[string "@SharedXML/CallbackRegistry.lua"]:143: in function <SharedXML/CallbackRegistry.lua:142>
[string "=[C]"]: ?
[string "@SharedXML/CallbackRegistry.lua"]:146: in function `TriggerEvent'
[string "@SharedXML/Scroll/ScrollUtil.lua"]:383: in function `SetElementDataSelected_Internal'
[string "@SharedXML/Scroll/ScrollUtil.lua"]:348: in function `SelectElementData'
[string "@SharedXML/Scroll/ScrollUtil.lua"]:388: in function `Select'
[string "@Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeList.lua"]:58: in function <...fessionsTemplates/Blizzard_ProfessionsRecipeList.lua:46>

Locals:
(*temporary) = "Contact the maintainer of Reagent Search to resolve this problem. Details: Usage Auctionator.API.v1.GetVendorPriceByItemID(string, number)"

**Comment by plusmouse** [comment]
I've put a fix into the next alpha
