### ISSUE TITLE
Sort button causing nil error.

### ISSUE THREAD

**Issue by cgsub** [Auctionator/Auctionator#1371]
In retail version.

Shopping list sort button was causing a nil error.

I could make it work by edit line 76 in Source\Shopping\Mixins\List.lua 
 --table.sort(self.selectedList.items, function(a, b)
 table.sort(self.data.items, function(a, b)

**Comment by plusmouse** [comment]
The latest alphas already have that fix applied, and I've added the fix into the next release 10.0.44 - available from Curseforge or Wago shortly.
