### ISSUE TITLE
Search button in crafting window to also return the price of disenchanting materials

### ISSUE THREAD

**Issue by dimkasta** [Auctionator/Auctionator#1372]
**Is your feature request related to a problem? Please describe.**

I often look for flipping opportunities. But I cannot easily know the current prices or the precise mats that an item disenchants into. I have to craft at least one and disenchant it, and then manually check current prices.

**Describe the solution you'd like**
The addon already knows the disenchanting materials since it shows the prices to disenchant an item on the tooltip. 
It would be a nice addition to use the search button on the crafting window to also get current prices of disenchanting materials along with crafting materials.

**Describe alternatives you've considered**
I am looking for a flipping addon with little luck so far

**Comment by plusmouse** [comment]
Have you tried enabling the disenchant tooltip information?
![image](https://user-images.githubusercontent.com/60280559/229311212-3aff3eb1-37dc-415a-9345-fadabb3d5f00.png)
![image](https://user-images.githubusercontent.com/60280559/229311247-d7820de8-8896-4fd3-92f4-402e7a6be296.png)

**Comment by plusmouse** [comment]
(misread your question)
Where would the disenchant materials search button be placed?

**Comment by dimkasta** [comment]
No need for a new button. The existing search button on the crafting window works nicely. We would just extend the results to include the enchanting materials on top of crafting mats and item itself

![snip](https://user-images.githubusercontent.com/1822122/229355064-11763c87-8235-418a-bed9-26cbf269b23c.jpg)

**Comment by plusmouse** [comment]
![image](https://user-images.githubusercontent.com/60280559/229355501-be71602b-61a7-419a-964b-b854cd16ea7a.png)

So on this particular item you'd also get in the search results:
* Strange Dust
* Lesser Astral Essence
* Small Glimmering Shard

And then you would have an updated disenchant value? What does seeing them in the search give that a full scan won't?

**Comment by dimkasta** [comment]
I just discovered the full scan button and thankfully it goes fast, so this fixes part of it. 

But I also do not see the possible disenchanting mats. Is there an option for that? Because I could not find one, and I have all the d/e tooltip options enabled

![snip2](https://user-images.githubusercontent.com/1822122/229356613-1b7cc6cc-57a4-4d2d-a2b0-e8b21745d889.jpg)

**Comment by plusmouse** [comment]
Hold down Shift before you move your mouse to trigger the tooltip, then it will show the breakdown.

**Comment by dimkasta** [comment]
Ah nice! thanks

**Comment by plusmouse** [comment]
Going to close this issue as resolved. If it isn't comment here and I'll reopen it.
