### ISSUE TITLE
"Automatically select the next item in your bag" skipping partial/remaining stacks.

### ISSUE THREAD

**Issue by Bogdanov89** [Auctionator/Auctionator#1373]
**Is your feature request related to a problem? Please describe.**
The option "Automatically select the next item in your bag" is skipping partial stacks.
For example if i have 33 linen cloth and i tell the addon to sell 20 linen cloth after that it will move to the next item in my bags (for example Turtle Meat), instead of still staying on the remaining 13 linen cloth (so that i can easily sell that as well without having to manually click on the remaining linen cloth in the UI).

**Describe the solution you'd like**
It would be great if there was an additional option to have the addon stay on these partial stacks before selecting the next item in your bags.

**Describe alternatives you've considered**
Manually adjusting the stack size for every item that is sold is very tiresome, especially for players that frankly do not like hassling with the AH but still have to due to costs.
I would love a new option to instruct the addon to sell ALL of the items stacks in as large stacks as possible (for example it would sell 33 linen cloth with a single button click by putting an auction of 20 linen cloth and an auction of 13 linen cloth.

**Comment by plusmouse** [comment]
This build
[Auctionator-10.0.44-7-g2c3ccad-wrath.zip](https://github.com/Auctionator/Auctionator/files/11183816/Auctionator-10.0.44-7-g2c3ccad-wrath.zip)
when this option is turned on:
![image](https://user-images.githubusercontent.com/60280559/230736079-667e4761-5b34-4389-bdd3-8130bbd0b236.png)
Will let you post the remaining partial stack in one extra click after posting the full stacks (Blizzard limitations prevent this all being done in one click)
