### ISSUE TITLE
Option to sell ALL the stacks of an item with a single button click.

### ISSUE THREAD

**Issue by Bogdanov89** [Auctionator/Auctionator#1374]
**Is your feature request related to a problem? Please describe.**
When i have an item such as 51 silk cloth, without doing a manual setup of stack sizes it takes multiple interactions/clicks to sell all of those items, since they are in uneven stacks (20 20 11 silk cloth stacks). 

**Describe the solution you'd like**
It would be great if we had an option to tell the addon to sell ALL the items of a certain type (example Silk cloth) with a single button click, regardless of how many cloth we have, in as large stacks as possible (to not clutter the AH with small stacks).

**Describe alternatives you've considered**
Manually adjusting the stack size for every stackable item that is sold is very tiresome, especially for players that frankly do not like hassling with the AH but still have to due to costs.
I would love a new option to instruct the addon to sell ALL of the items stacks in as large stacks as possible (for example it would sell 33 linen cloth with a single button click by putting an auction of 20 linen cloth and an auction of 13 linen cloth.

**Comment by plusmouse** [comment]
It isn't possible do it in one button press (Blizzard limitations). See #1373 for a new build to do it in 2 clicks though.
