### ISSUE TITLE
Show price range for Reagent Values in custom order window

### ISSUE THREAD

**Issue by d-schmidt** [Auctionator/Auctionator#1376]
**Is your feature request related to a problem? Please describe.**
The "Reagents Value" in the Custom Order window has no information about reagent quality. When you don't select a quality (because you don't have the mats), it shows "something".

**Describe the solution you'd like**
With prices between quality rangeing wildly I would like to see the range of the value.
i.e. T2 50g, T1 100g, T3 200g. So we can see a Reagents value: 50g-200g instead of 100g I guess we get now.

**Describe alternatives you've considered**
Alternativly I would accept a "Cheapest Reagents Value:" where it just takes the cheapest, not the lowest quality.

**Additional context**
This might already be the cheapest but it doesn't seem like it.

CalculateCraftCost says "Calculate using the lowest quality for remaining mandatatory reagents". Lowest quality is now often way more expensive than T2 or T3.

**Comment by plusmouse** [comment]
The comment is wrong 😂 
```lua
total = total + GetByMinCostOption(reagentSlotSchematic.reagents, reagentSlotSchematic.quantityRequired - selected)
```
The code uses `GetByMinCostOption` to get the lowest priced quality reagent rather than the lowest quality.

**Comment by plusmouse** [comment]
Adding in a price in brackets is going to be confusing. How about this instead?

![image](https://user-images.githubusercontent.com/60280559/236929312-49cc20b2-cbc6-4bd7-8c8e-bc0c4f845962.png)

**Comment by plusmouse** [comment]
Find this in the latest alpha (available shortly from Curseforge and Wago when it finishes processing)

**Comment by d-schmidt** [comment]
I like it. I just tried to avoid text even tho it is much clearer.

**Comment by d-schmidt** [comment]
@plusmouse can you also call this new function in the order window? My implementation did this for  in the `CustomerOrders.lua`

**Comment by plusmouse** [comment]
Done. Find it the latest alpha after it finishes processing
![image](https://github.com/Auctionator/Auctionator/assets/60280559/b6af2920-8182-4040-9edf-45bda295dc7a)
