### ISSUE TITLE
When adding new items It is showing out of stock in "My Favourite"

### ISSUE THREAD

**Issue by KillJoy88** [Auctionator/Auctionator#1378]
Please include as much of the following information as possible to help me fix the bug:

## Are you on the retail or the classic version of WoW?
Retail

## Is this a bug or a feature request?
Bug

# Bug:
## Brief Description of Bug
When adding new items It is showing out of stock in "My Favourite". But when you click on it, you can see that it is selling

I just add an item to favourite, and it is showing out of stock. Other items are ok, which I added before. I think it occur about a month ago or more. As you can see image 3 have the qty for those favourite items. But when I add them they are not showing on the favourite list on image 2
![1](https://user-images.githubusercontent.com/131289381/233147946-442b1b22-ff58-49ef-a5e5-c64aaf75ec92.jpg)
![2](https://user-images.githubusercontent.com/131289381/233148330-9606b4ba-effa-4d8b-82a9-da6d118f01cb.jpg)
![3](https://user-images.githubusercontent.com/131289381/233148339-8f5a512d-f4ea-414b-8c53-61e0db41a806.jpg)

## Steps to Reproduce

Add an item from search to the "star" main favourite list and it's out of stock always.

## Loaded Addons

Atlas
AtlasLoot
Bagnon
BankStack
DBM
Details
EPGP
OmniCC
Mapster
Quartz3
SellJunk
TomTom
 

## Back Trace (LUA Error Output)
You have no errors with those addons

# Feature Request:
## Is your feature request related to a problem? Please describe
Describe the problem you are experiencing.

## Describe the solution you'd like
The item should go to My Favourite and I can see the stock available on the auction

## Describe alternatives you've considered
No alternatives

**Comment by plusmouse** [comment]
This is an issue with the Blizzard UI rather than Auctionator. Blizzard sometimes updates the internal labels for items which breaks the favourites.
