### ISSUE TITLE
Feature Request: Delete historic scan data

### ISSUE THREAD

**Issue by Rezy942** [Auctionator/Auctionator#1379]
Hello,

Im not sure if this feature is already available (without going into your folder and start deleting certain files)
I want to delete all scan data that exists WITHOUT deleting any settings. Absolutely nothing gets deleted EXCEPT price history.

Is that already possible?
If not, is it possible to add this as a button? Maybe close to "scan" button in AH?

Thanks

**Comment by Rezy942** [comment]
Thank you!
Would you consider adding this as a button somewhere in the UI or options?
Macro works but its always nice to not have to google for a solution.

**Comment by plusmouse** [comment]
I'm unlikely to add a button for that - as resetting the database doesn't make sense - usually the price history is wanted

**Comment by Rezy942** [comment]
Understandable.
To be honest your use case and the tiny minority of users commenting on addon authors pages do not represent the reality. It represents your opinion.
There are many times I needed that, but i resorted to resetting the settings entirely instead. 
I will continue to look up this thread in the future to dig up the macro. Thank you for the help.
