### ISSUE TITLE
Tooltip not working

### ISSUE THREAD

**Issue by eric13durham** [Auctionator/Auctionator#1382]
Please include as much of the following information as possible to help me fix the bug:

Tooltip not working showing prices.  Win11 Latest updates with patches.  Options are selected for it to show.  I did multiple full scans.

_Please include a brief description of the bug, including what you were doing, and when it occurred._

always

_Include the steps I would need to follow to reproduce the bug._

none

_Include a list of addons you were running at the time this bug occurred._

even when i uninstall or disable all other addons, the tooltip still does not work.

_You can get this through the use of !BugGrabber and BugSack addons._
![WoWScrnShot_050223_182751](https://user-images.githubusercontent.com/132408369/235800613-0580301f-2ab0-4b31-9d75-a9a9fd31fb00.jpg)

**Comment by eric13durham** [comment]
Tooltip not working with 10.1 patch.. I have the latest Auctionator update. No other addons. (yes it is enabled in options.)
![WoWScrnShot_050223_182751](https://user-images.githubusercontent.com/132408369/235799918-f184c9db-58c4-4a0b-90c1-c44c43e5be1e.jpg)

**Comment by plusmouse** [comment]
I've pushed a fixed version to Curseforge and Wago, which will be available as 10.1.1 when it finishes processing.

**Comment by eric13durham** [comment]
cheers and thanks.
