### ISSUE TITLE
Incorrect error message when trying to sell a damaged item

### ISSUE THREAD

**Issue by gitthrill** [Auctionator/Auctionator#1383]
I'm playing on Classic Era. I have a "Raider Shortsword of Strength" in my bags and was going to Auction it via the Selling tab of Auctionator. It wasn't available in the item list pane, so I dragged it from my bags. I received the error "You cannot sell a soulbound item.". I thought that was odd because the item is still BoE (in fact I was using my lvl1 bank alt who could not equip this level11 sword anyway). Its durability was 38/50 and damaged items cannot be listed, so I thought the error message was incorrect. When I switched to the Auctions tab (non Auctionator) the error message was "You must repair that item before you auction it." which seemed to make a lot more sense.

This is probably easily reproducible on your own with a damaged item/weapon and the fix appears to be to adjust what error message is sent when a broken item is moved into the Selling window.

Thanks.

**Comment by plusmouse** [comment]
Fixed in the latest alphas, available from Curseforge or Wago shortly.
