### ISSUE TITLE
Shopping List Saving

### ISSUE THREAD

**Issue by kbachnik** [Auctionator/Auctionator#1385]
Hi, ran into a problem. When I import New Shopping List and save it, it gets deleted on re-entry. Even when I just reload the interface it gets deleted. No matter how many new imported or just new sheets I create they all get deleted

**Comment by plusmouse** [comment]
Can you install BugSack and BugGrabber and report any errors they show when the list is created, and when you reload?

**Comment by kbachnik** [comment]
So I've created list "10.1 BOE+Recepies"

![1](https://github.com/Auctionator/Auctionator/assets/36343167/5bf3e243-746b-4f13-9336-4404ce0a1cbb)

Than i use /reloadui

![2](https://github.com/Auctionator/Auctionator/assets/36343167/1959f4d0-a37c-4fea-83cd-8542c848a5c2)
![3](https://github.com/Auctionator/Auctionator/assets/36343167/3f5552bc-8777-42a0-9ad7-a053349fddf4)
![4](https://github.com/Auctionator/Auctionator/assets/36343167/39a03945-53de-48b8-a92f-181f34a1d105)

**Comment by plusmouse** [comment]
Thanks for the bug report. I've found the error, its now fixed in the latest alpha, available here, or from Curseforge/Wago when it finishes processing:
[Auctionator-10.1.1-6-g20d3fe0.zip](https://github.com/Auctionator/Auctionator/files/11471398/Auctionator-10.1.1-6-g20d3fe0.zip)
