### ISSUE TITLE
[Enhancement] Additional Undercut Scan information

### ISSUE THREAD

**Issue by b-morgan** [Auctionator/Auctionator#1387]
**Is your feature request related to a problem? Please describe.**
When I do an Undercut Scan, "Undercut? Yes" doesn't tell me enough.

**Describe the solution you'd like**
Instead of "Yes", display the new lowest price. Bonus points if you can display how many auctions are lower. i.e "2g7s3c (7)".

**Comment by plusmouse** [comment]
Right click the column header and enable the "Undercut Price" column
![image](https://github.com/Auctionator/Auctionator/assets/60280559/412688ee-69f0-441f-b8d2-359dff47d86c)

![image](https://github.com/Auctionator/Auctionator/assets/60280559/672ec9c0-a63c-43a0-b05d-030313a7de5c)

![image](https://github.com/Auctionator/Auctionator/assets/60280559/f0500efd-7f56-4245-8d52-57432888c234)

Available from Curseforge/Wago as an alpha after the build finishes processing.
[Auctionator-10.1.2-2-g028f2ed.zip](https://github.com/Auctionator/Auctionator/files/11502622/Auctionator-10.1.2-2-g028f2ed.zip)
[Auctionator-10.1.2-2-g028f2ed-classic.zip](https://github.com/Auctionator/Auctionator/files/11502623/Auctionator-10.1.2-2-g028f2ed-classic.zip)
[Auctionator-10.1.2-2-g028f2ed-wrath.zip](https://github.com/Auctionator/Auctionator/files/11502625/Auctionator-10.1.2-2-g028f2ed-wrath.zip)
