### ISSUE TITLE
Lua error on login with Auctionator 10.1.2-2-g028f2ed

### ISSUE THREAD

**Issue by b-morgan** [Auctionator/Auctionator#1388]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

Lua error on login with version 10.1.2-2-g028f2ed

## Steps to Reproduce

Login. Low level characters in Orgrimmar didn't tickle this bug but my level 60 DK in The Seer's Library on the Scryer's Tier did.

## Loaded Addons

Lots. I'll figure out how to automagically generate this list if it is really needed.

## Back Trace (LUA Error Output)

24x ...Ons/Auctionator/Source/Config/Mixins/PanelConfig.lua:22: attempt to call field 'GetCategory' (a nil value)
[string "@Auctionator/Source/Config/Mixins/PanelConfig.lua"]:22: in function `SetupPanel'
[string "@Auctionator/Source_Classic/Config/Mixins/BasicOptions.lua"]:9: in function <...onator/Source_Classic/Config/Mixins/BasicOptions.lua:3>
[string "=[C]"]: ?
[string "=[C]"]: in function `CreateFrame'
[string "@Auctionator/Source/Config/InitializeFrames.lua"]:3: in function `InternalInitializeFrames'
[string "@Auctionator/Source_Classic/Config/InitializeFrames.lua"]:2: in function `InitializeFrames'
[string "@Auctionator/Source/Variables/Main.lua"]:9: in function `Initialize'
[string "@Auctionator/Source/Initialize/Main.lua"]:30: in function `AddonDataLoaded'
[string "@Auctionator/Source/Initialize/Main.lua"]:20: in function <Auctionator/Source/Initialize/Main.lua:17>

Locals:
self = AuctionatorConfigBasicOptionsFrame {
 0 = <userdata>
 cancel = <function> defined @Auctionator/Source/Config/Mixins/PanelConfig.lua:4
 ShowCraftingCost = Frame {
 }
 parent = "Auctionator"
 Save = <function> defined @Auctionator/Source_Classic/Config/Mixins/BasicOptions.lua:19
 ShowCraftingProfit = Frame {
 }
 OnDefault = <function> defined @Auctionator/Source/Config/Mixins/PanelConfig.lua:13
 SetupPanel = <function> defined @Auctionator/Source/Config/Mixins/PanelConfig.lua:3
 DefaultTab = Frame {
 }
 OnShow = <function> defined @Auctionator/Source_Classic/Config/Mixins/BasicOptions.lua:12
 CraftingInfoHeading = Frame {
 }
 OnRefresh = <function> defined @Auctionator/Source/Config/Mixins/PanelConfig.lua:14
 TitleArea = Frame {
 }
 Cancel = <function> defined @Auctionator/Source_Classic/Config/Mixins/BasicOptions.lua:28
 name = "Basic Options"
 okay = <function> defined @Auctionator/Source/Config/Mixins/PanelConfig.lua:8
 ShowCraftingInfo = Frame {
 }
 OnCommit = <function> defined @Auctionator/Source/Config/Mixins/PanelConfig.lua:8
 OnLoad = <function> defined @Auctionator/Source_Classic/Config/Mixins/BasicOptions.lua:3
 DefaultTabHeading = Frame {
 }
}
(*temporary) = nil
(*temporary) = "Auctionator"
(*temporary) = "attempt to call field 'GetCategory' (a nil value)"

**Comment by b-morgan** [comment]
List of Addons (enabled == loaded) [AddOns.txt](https://github.com/Auctionator/Auctionator/files/11503380/AddOns.txt)

**Comment by plusmouse** [comment]
This is caused by another addon creating a global `Settings` object. Added a temporary fix.

**Comment by b-morgan** [comment]
That other addon would be [Profession Master - Guild Trade Skills](https://www.curseforge.com/wow/addons/profession-master).
