### ISSUE TITLE
Message as soon as I log in to WoW

### ISSUE THREAD

**Issue by Leverarch** [Auctionator/Auctionator#139]
Interface\AddOns\Auctionator\AuctionatorLocalize.lua:306: attempt to call global 'GetAuctionItemClasses' (a nil value)
------------
VERS:3.2.3   MEM:  2609 KB   DB:5073   SE:0  SL:2  FSCHUNK:<nil>  DBVERS:4
------------
REALMS: , Hellfire_Alliance (5073), Hellfire_Horde (0)
------------
STACK: GetAuctionItemClasses > Atr_GetAuctionClasses > Atr_ItemType2AuctionClass > Atr_IsWeaponType > Atr_CalcDisenchantPrice > Atr_STWP_GetPrices > Atr_ShowTipWithPricing > SetInventoryItem > BagSlotButton_OnEnter
------------
ADDONS: , Auctionator, BagBrother, Bagnon, Bartender4, Coordinates, GTFO, MikScrollingBattleText, Quartz, Recount, TidyPlates, VuhDo, WeakAuras, DBM

**Comment by jrob8577** [comment]
You are using an outdate version of Auctionator. Please update to a 7.0.3 patch compatible version (the current version is 4.0.5).
