### ISSUE TITLE
Shopping list no longer highlight the searched item

### ISSUE THREAD

**Issue by sehra** [Auctionator/Auctionator#1392]
**Is your feature request related to a problem? Please describe.**
When using a shopping list and clicking a row to search for, the row is no longer highlighted. Only the shopping list name is highlighted.

**Describe the solution you'd like**
I would like the row highlight back.

**Describe alternatives you've considered**
Different color of the text or an icon would also work.

**Additional context**
![image](https://github.com/Auctionator/Auctionator/assets/1662735/0889aa4d-dbd4-4b6b-b574-fd2721689d66)

**Comment by plusmouse** [comment]
I've added a fix into the latest alpha (available from Curseforge or Wago shortly)
