### ISSUE TITLE
Using shopping list, selecting an item to buy, and then hitting back causes the default list to re-scan - instead of returning to previous shopping list results.

### ISSUE THREAD

**Issue by fatmagic** [Auctionator/Auctionator#1393]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

This is a new bug with new shopping list revamp. It's more a QoL issue than a bug I guess. So I have a default shopping list that auto-searches when I open "Shopping" - which I want to happen. But when I select any non-default list, let it run... then select an item to purchase, and then hit "Back" - it returns to the Shopping tab and begins running the Default shopping list, which I don't want to happen. I want to return to the list of items I was trying to shop for in my non-default list.

Sorry this is hard to explain! I'll put a video in the "Steps to Reproduce" section.

## Steps to Reproduce

https://www.youtube.com/watch?v=uoNdnXWG50k

- The first list that is loading, and I cancel, is the default search list ("Craft Shuffle")
- Then I select the non-default list I want to use ("Clasps")
- I select an item to purchase (...pretend I purchase an item!)
- And then I click back.
- It then starts the load the default list again ("Craft Shuffle"), instead of returning to the previously selected list ("Clasps") with existing results.
- So then I have to select the list I want again, and wait for the search to finish.
- In the previous version before the Shopping List update, it didn't do this. It would just show the previous results and let me jump from item to item that I wanted to purchase quickly.

I hope this makes sense!

**Comment by plusmouse** [comment]
Fixed in the latest alpha. Available from Curseforge or Wago shortly, or from here:
[Auctionator-10.1.3-3-gb8a1f49.zip](https://github.com/Auctionator/Auctionator/files/11581081/Auctionator-10.1.3-3-gb8a1f49.zip)

**Comment by fatmagic** [comment]
You're the best plusmouse! TY!
