### ISSUE TITLE
Updated yesterday (as of making this) and get this Lua Error when i open the Auction house.

### ISSUE THREAD

**Issue by Denaloiv** [Auctionator/Auctionator#1396]
Message: ...Ons\Auctionator\Source\Tabs\Shopping\Mixins\Main.lua:92: Attempt to register unknown event "PLAYER_INTERACTION_MANAGER_FRAME_HIDE"
Time: Fri Jun  2 00:44:30 2023
Count: 1
Stack: ...Ons\Auctionator\Source\Tabs\Shopping\Mixins\Main.lua:92: Attempt to register unknown event "PLAYER_INTERACTION_MANAGER_FRAME_HIDE"
[string "@Interface\AddOns\Auctionator\Source_Classic\Tabs\Mixins\TabButton.lua"]:12: in function `Initialize'
[string "@Interface\AddOns\Auctionator\Source_Classic\Tabs\Mixins\TabContainer.lua"]:19: in function <...tionator\Source_Classic\Tabs\Mixins\TabContainer.lua:7>
[string "@Interface\AddOns\Auctionator\Source_Classic\Tabs\Mixins\TabContainer.lua"]:40: in function <...tionator\Source_Classic\Tabs\Mixins\TabContainer.lua:25>
[string "=[C]"]: in function `CreateFrame'
[string "@Interface\AddOns\Auctionator\Source_Classic\Core\Mixin.lua"]:5: in function <...ace\AddOns\Auctionator\Source_Classic\Core\Mixin.lua:3>
[string "@Interface\AddOns\Auctionator\Source_Classic\Core\Mixin.lua"]:94: in function <...ace\AddOns\Auctionator\Source_Classic\Core\Mixin.lua:90>
[string "=[C]"]: in function `CreateFrame'
[string "@Interface\AddOns\Auctionator\Source_Classic\Initialize\Main.lua"]:37: in function `AuctionHouseShown'
[string "@Interface\AddOns\Auctionator\Source_Classic\Initialize\Main.lua"]:18: in function <...ddOns\Auctionator\Source_Classic\Initialize\Main.lua:16>

Locals: self = AuctionFrameTab4 {
 0 = <userdata>
 displayMode = <table> {
 }
 wrapperFrame = <unnamed> {
 }
 Initialize = <function> defined @Interface\AddOns\Auctionator\Source_Classic\Tabs\Mixins\TabButton.lua:3
 selectedTextY = 4
 Selected = <function> defined @Interface\AddOns\Auctionator\Source_Classic\Tabs\Mixins\TabButton.lua:30
 ahTitle = "Auctionator - Shopping"
 DeselectTab = <function> defined @Interface\AddOns\Auctionator\Source_Classic\Tabs\Mixins\TabButton.lua:45
}
name = "Shopping"
tabTemplate = "AuctionatorShoppingTabClassicFrameTemplate"
tabHeader = "Auctionator - Shopping"
displayMode = <table> {
 1 = "AuctionatorShoppingFrame"
}

As for other adons i am using,
Details damage meter
Rare scanner
Big wigs
atlas classic
atlas loot 
 classic aura duration
classic cast bars
decursive
gathermate 2
gathermate 2 Data
omnicc
questie
Target health
titan panel
Littlewigs

**Comment by plusmouse** [comment]
Fixed in the latest alphas for classic era:
[Auctionator-10.1.4-4-g325f27d-classic.zip](https://github.com/Auctionator/Auctionator/files/11632471/Auctionator-10.1.4-4-g325f27d-classic.zip)
Can you verify that the fix works?
