### ISSUE TITLE
Item buttons improperly sized on Selling tab

### ISSUE THREAD

**Issue by Germbread** [Auctionator/Auctionator#1402]
After updaing Auctionator from version 10.0.40, I noticed the buttons displaying sellable items on the Selling tab are slightly enlarged, causing them to overlap the category headers and cut off item buttons on the right edge of the 'inventory' panel.

I've tested with all other addons disabled, and temporarily rolled back to 10.0.40 to make sure it wasn't some sort of conflict.

- Still occurs with other addons disabled
- Displays properly with the older version regardless of other addons

![auctionator2](https://github.com/Auctionator/Auctionator/assets/137974299/444d276c-2e8b-4951-8085-c56038396e15)

(after some extra testing, it appears the issue is present beginning with version 10.0.45)

**Comment by plusmouse** [comment]
Thanks for the bug report, I've identified a fix and added it to the latest alpha. Can you check that its fixed for you too?
[Auctionator-10.1.8-14-gfc7f7e8-classic.zip](https://github.com/Auctionator/Auctionator/files/11891113/Auctionator-10.1.8-14-gfc7f7e8-classic.zip)
