### ISSUE TITLE
 items in the backpack do not display auction prices in default settings

### ISSUE THREAD

**Issue by lssdo12** [Auctionator/Auctionator#1408]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

In default settings, items in the backpack do not display auction prices. Even if I disable all other plugins and did multiple full scans. I can obtain the auction price of items in my backpack by displaying the auction mouse prompt in the plugin settings, but it will display the total price instead of the unit price. I like to display the unit price

## Steps to Reproduce

Uninstall and install the auctionator plugin again, disable all other plugins, full scan.

## Loaded Addons

none

## Back Trace (LUA Error Output)

BugGrabber does not display any error messages

![image](https://github.com/Auctionator/Auctionator/assets/59727014/2b7e598d-475b-4422-a119-b2e4ab8f17f1)

**Comment by plusmouse** [comment]
That's weird. This option
![image](https://github.com/Auctionator/Auctionator/assets/60280559/95cf1ad2-d7af-4980-b807-921b7312571a)
Will set it to show the unit price by default, but it looks like you already have this option applied.

**Comment by lssdo12** [comment]
> That's weird. This option ![image](https://user-images.githubusercontent.com/60280559/251940188-95cf1ad2-d7af-4980-b807-921b7312571a.png) Will set it to show the unit price by default, but it looks like you already have this option applied.

Thank you for your reply. I have currently resolved this issue. It seems that some options were accidentally unchecked due to porting the plugin from another computer. I use curseforge to manage my plugins, and I found that when I delete and reinstall plugins, curseforge will retain the previous settings. The solution is to right-click the plugin in curseforge and select "Delete Settings (Saved Variables)"
