### ISSUE TITLE
Window with items for Sell Dissapear ?

### ISSUE THREAD

**Issue by Mordrux** [Auctionator/Auctionator#1409]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

_Please include a brief description of the bug, including what you were doing, and when it occurred._

## Steps to Reproduce

_Include the steps I would need to follow to reproduce the bug._

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by Mordrux** [comment]
Where did the window with things from the section for sale go? now I have to move the items directly from the backpack to the window for sale, before it was inside the auction.

**Comment by plusmouse** [comment]
Make sure this option is turned on:
![image](https://github.com/Auctionator/Auctionator/assets/60280559/06e17c5f-54c1-4c51-a69d-50f65b60183a)

**Comment by Mordrux** [comment]
> Make sure this option is turned on: ![image](https://user-images.githubusercontent.com/60280559/252146874-06e17c5f-54c1-4c51-a69d-50f65b60183a.png)

Thanks, Work .. some update reset this :D

**Comment by sandervspl** [comment]
This option keeps getting toggled off for me every time I log in to my character. I'll see if I can find a reproduction.

**Comment by rgeraads** [comment]
It disappeared for me as well. When I toggle that option and do a reload it shows like this.
![image](https://github.com/Auctionator/Auctionator/assets/6044164/b84bfc35-d8f2-4879-9ec5-2ffd0174a809)
