### ISSUE TITLE
Cancelling only if Pet level is the same

### ISSUE THREAD

**Issue by deus81** [Auctionator/Auctionator#1413]
In "Options" -> "Auctionator" -> "Cancelling" you have the Option to only cancel an auction if the gear item level is the same. Could you implement the same for Battlepet level? All my Battlepet lvl 25 get canncelled because the lvl 1 of the same pet are much lower in buyout price.

**Comment by plusmouse** [comment]
Find this in the latest alpha
[Auctionator-10.1.14-1-ge772b68.zip](https://github.com/Auctionator/Auctionator/files/12159921/Auctionator-10.1.14-1-ge772b68.zip)

Change the item matching settings in the Selling: All Items section to choose how undercuts are checked for.
