### ISSUE TITLE
Purchasing Missing Battle Pets

### ISSUE THREAD

**Issue by Unplayed** [Auctionator/Auctionator#1419]
Purchasing Missing Battle Pets: please add an option in the saved search "missing only".

**Comment by plusmouse** [comment]
Have you tried Collectionator? It provides a better UI for catching up on items you haven't collected.
![image](https://github.com/Auctionator/Auctionator/assets/60280559/9174ec09-c378-4c85-8541-4b5522df1d6e)

**Comment by Unplayed** [comment]
Tried, but very long time ago. I prefer to use as few addons as possible, this (rumored) can improve the stability of the game. And I really like to shop through the Auctionator.

**Comment by plusmouse** [comment]
The feature isn't going to be added to Auctionator. Collectionator remains a great option, and is designed to work with Auctionator. Collectionator has been updated since you last tried it, so it may do just what you want now.
