### ISSUE TITLE
Selling tab not showing bags (wotlk)

### ISSUE THREAD

**Issue by Kyung783** [Auctionator/Auctionator#1421]
![auct1](https://github.com/Auctionator/Auctionator/assets/105098239/4ef965d9-1314-4a98-9b40-78d02f73d758)

what happened here? used to show all the bags on the left separated by categories

**Comment by plusmouse** [comment]
Can you check whether this option is on?
![image](https://github.com/Auctionator/Auctionator/assets/60280559/fb6c921c-90bd-4a42-86bb-6a2c149b821d)

**Comment by Kyung783** [comment]
ok i fixed it thanks, but size at 30; was 10 after enabling it again

**Comment by plusmouse** [comment]
I've pushed a new version of Auctionator to Curseforge that should prevent this happening again.
[Auctionator-10.1.16-wrath.zip](https://github.com/Auctionator/Auctionator/files/12305256/Auctionator-10.1.16-wrath.zip)

**Comment by MelchiorGaspar** [comment]
I was having this issue too lol..  thx for the fix @plusmouse 
I noticed that when I started up the game this morning it was missing..
I checked the Auctionator settings and found it had been switched off some how..

This also randomly happens to me with the Blizzard settings for [scrolling combat text] which will some times switch itself off.

hope my input helps a bit.
