### ISSUE TITLE
Unable to scan auctionhouse

### ISSUE THREAD

**Issue by Raven1711** [Auctionator/Auctionator#1424]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug
unable to scan auction house

_Please include a brief description of the bug, including what you were doing, and when it occurred._
1) i redownloaded auctionator fresh
2) went to the auction house
3) attempted to scan
4) nothing happens

## Steps to Reproduce
1) i redownloaded auctionator fresh
2) went to the auction house
3) attempted to scan
4) nothing happens

_Include the steps I would need to follow to reproduce the bug._
1) i redownloaded auctionator fresh
2) went to the auction house
3) attempted to scan
4) nothing happens

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._
isolated the issue by disabling all addons except auctionator. the issue persisted

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._
no error occured

**Comment by plusmouse** [comment]
Which version of Auctionator did you install? If you installed the ClassicFix fork that isn't supported and you'll need to download a classic (or wrath) version from this page instead https://www.curseforge.com/wow/addons/auctionator/files

![image](https://github.com/Auctionator/Auctionator/assets/60280559/303cf31b-f07a-46d0-bdca-6aaa1a4aaa10)

Do you have BugSack and BugGrabber installed?

**Comment by Raven1711** [comment]
I don’t habe buggrubber installed, I will attempt the fix you meantioned.
If I don’t reply again after this email consider it fixed!
Ps: I did have the fix installed
