### ISSUE TITLE
Selling tab: Max button should always be disabled for zero-quantity favorites

### ISSUE THREAD

**Issue by tflo** [Auctionator/Auctionator#1426]
<details>
<summary><code>SaleItem.lua:154: Usage: local listCount = C_AuctionHouse.GetAvailablePostCount(item)</code></summary>

```text
1x ...tor/Source_Mainline/Tabs/Selling/Mixins/SaleItem.lua:154: Usage: local listCount = C_AuctionHouse.GetAvailablePostCount(item)
[string "=[C]"]: in function `GetAvailablePostCount'
[string "@Auctionator/Source_Mainline/Tabs/Selling/Mixins/SaleItem.lua"]:154: in function `GetPostLimit'
[string "@Auctionator/Source_Mainline/Tabs/Selling/Mixins/SaleItem.lua"]:157: in function `SetMax'
[string "*SaleItem.xml:65_OnClick"]:1: in function <[string "*SaleItem.xml:65_OnClick"]:1>

Locals:
(*temporary) = nil

```
</details>

I can get this error in the Selling tab when I accidentally click the Max button on a favorite where I do not currently have the item in my bags.

This is possible because if you select a max-able item (i.e. you have several in your bags) _and then_ select a favorite where you don't have any in your bags, the Max button doesn't get disabled.

(For items where I have exactly one in my bags, the Max button seems to be reliably disabled, no matter what was previously selected.)

**Comment by plusmouse** [comment]
Fixed in the latest alpha (available shortly)
