### ISSUE TITLE
Not showing Results under the Selling Tab

### ISSUE THREAD

**Issue by TryAndErrorBen** [Auctionator/Auctionator#1431]
I have the issue that i cannot see the Items, which other players are selling in the "Selling Tab of the Auctionator" This is mainly happen for Green Items. You can see the issues detailed on the following  screenshot.
WoW Tab shows 2 Sellers and the Autctionator Tab none
![2023-09-19_07h24_15](https://github.com/Auctionator/Auctionator/assets/26752258/26eec54a-b531-4b1d-b93f-a611466128bd)
![2023-09-19_07h24_38](https://github.com/Auctionator/Auctionator/assets/26752258/530ed781-5411-4eeb-b638-0e6bdd18700e)

**Comment by plusmouse** [comment]
This can be fixed by going to the Auctionator settings and looking at the Selling: All Items category:
![image](https://github.com/Auctionator/Auctionator/assets/60280559/839cec4e-9043-4940-ab89-f7683dbc3aa8)
Change the item price matching to what displays the results you want

**Comment by plusmouse** [comment]
Did the above comment resolve your problem?
