### ISSUE TITLE
"make more gold vendoring" math seems wrong..

### ISSUE THREAD

**Issue by jeske** [Auctionator/Auctionator#1433]
I am receiving the "you can make more gold selling this to a vendor" dialog in situations where it does not seem correct. 

My suspicion, is that Auctionator is subtracting the deposit from the price to estimate profit, but this is wrong. The only "loss" of the auction house is the "5% successful auction cut" (for the standard auction house, 10% for the cross-faction AH). The deposit is just money "held" by the AH during a listing. It is never lost.

Here is an exammple:

Lesser Moonstone vendors for 6s. I am listing it for 7s66c, which will net 7s2c.  THen why does it give me the dialog?

![image](https://github.com/Auctionator/Auctionator/assets/15093/78fb4654-3938-4c1a-a5d8-5563a3b3e676)

![image](https://github.com/Auctionator/Auctionator/assets/15093/5f395621-2098-4570-8325-f06bb9160c5b)

**Comment by plusmouse** [comment]
I've now changed the calculation to ignore the deposit when calculating profitability. Available in the next alpha build
