### ISSUE TITLE
"Full scan in progress" chat spam

### ISSUE THREAD

**Issue by tflo** [Auctionator/Auctionator#1435]
Why do I get sometimes this and sometimes not?:

![WoWScrnShot_092723_174957](https://github.com/Auctionator/Auctionator/assets/1410282/04c582cd-66da-41ce-bd6c-fe41261f2ac4)

Those "Full scan in progress" messages are filling several dozens of chat window heights (thousands of printed lines probably)

**Comment by plusmouse** [comment]
That would be a bug. Mostly likely cause is something is hooked to the full scan button and keeps doing a click.

**Comment by tflo** [comment]
I never click the "full scan button", and currently I don't even know where that button is, or how to make it appear. I have set a scan interval in the Auctionator prefs (every 6h or so).

**Comment by tflo** [comment]
The only auction-related addon I'm using, besides Blizz, is TSM. No Auctioneer or so.

Some minor ones: AuctionSellers, AuctionPetlevels

**Comment by plusmouse** [comment]
Found the bug. Just devising a fix.

**Comment by tflo** [comment]
Oh, great :)

**Comment by plusmouse** [comment]
[Auctionator-10.1.22-2-g80073c5.zip](https://github.com/Auctionator/Auctionator/files/12741472/Auctionator-10.1.22-2-g80073c5.zip)

^^ that should resolve the issue

**Comment by tflo** [comment]
Thanks! Will report back in case I get the thing again.
