### ISSUE TITLE
Search button blocking 'to craft' info in profession window

### ISSUE THREAD

**Issue by zx122003** [Auctionator/Auctionator#1436]
When having the Auction House window open together with the profession window, the search button is really wide and covers the 'to craft' cost. I can't see a way to either turn the search button off or move it out of the way.

![auctionator](https://github.com/Auctionator/Auctionator/assets/140452970/7729686a-fe94-49f7-a440-f9086c17faf5)

**Comment by plusmouse** [comment]
This is an issue with CraftSim, not Auctionator - it alters the search button to be in that position.

**Comment by zx122003** [comment]
Do you know how if there's a solution though? If it is CraftSim it doesn't have much options to change anything.

**Comment by plusmouse** [comment]
You can turn CraftSim off?

**Comment by zx122003** [comment]
I guess I will have to. I'd have preferred if it was possible to use both simultaneously without having to turn them off and on again when needed.

**Comment by plusmouse** [comment]
This very much an issue with CraftSim modifying the UI components of Auctionator. You could try reporting the issue to its developer?

![image](https://github.com/Auctionator/Auctionator/assets/60280559/b50582ed-f041-4e50-b9e0-bf61d2ced50a)

**Comment by zx122003** [comment]
Yes, I'll do. I thought because it's the Auctionator's button it was an issue with Auctionator.
