### ISSUE TITLE
Pet stats no longer parsed and hence no breed display via BattlePetBreedId (Selling tooltip)

### ISSUE THREAD

**Issue by tflo** [Auctionator/Auctionator#1438]
10.1.23-18-g02fdd4d

When/before posting a pet, the stats are no longer correctly parsed in the item tooltip in the Selling tab, hence the breed info via [BattlePetBreedId](https://www.curseforge.com/wow/addons/battle_pet_breedid) is missing:

<img width="346" alt="WoWScrnShot_100223_114631" src="https://github.com/Auctionator/Auctionator/assets/1410282/14913c7f-58bb-4a73-b44c-0ac4ae332460">

In the screenshot, you see that power and speed stats are missing, and BattlePetBreedId can no longer compute the correct breed.

Whereas in the tooltip of the _posted_ pet, the stats (and BPBI's output) are there:
<img width="743" alt="WoWScrnShot_100223_114639" src="https://github.com/Auctionator/Auctionator/assets/1410282/743716d6-c27f-4569-ad91-4ca21eec6e23">

**Comment by plusmouse** [comment]
I've added a fix into the next alpha, available shortly.

**Comment by tflo** [comment]
Great! Thanks so much for your speedy fixes!

**Comment by tflo** [comment]
I meant "really, really speedy fixes" :)
