### ISSUE TITLE
Post button active/inactive switching

### ISSUE THREAD

**Issue by hollo6** [Auctionator/Auctionator#1440]
## Brief Description of Bug
In version 10.1.24-3-ga40e2a1, when posting items, the Post button goes inactive and then back to active after the scan results yielded, making it unusable for an extra ~3 seconds.
Rolled back to 10.1.23-20-g62372b9 and confirmed the problem is not present here.

## Steps to Reproduce
1. Open Selling tab
2. Click on any bag item in the list to sell
3. Wait for the scan to complete
4. Observe Post button going inactive (greyed out, unusable) then back to active (usable again)

## Loaded Addons
(not full list, removed some that's obviously irrelevant)
Advanced Interface Options
ArkInventory
Auctionator
BigWigs
BugGrabber
BugSack
BuyEmAll
Can I Mog It?
Details
Dominos
Elkano's BuffBars
Genie
Kaliel's Tracker
LittleWigs
Macro Toolkit
Mapster
Mik's Scrolling Battle Text
MoveAny
NeatPlates
No Mats' No Make
NugComboBar
OmniCC
Pawn
Postal
Prat
Rarity
SavedInstances
SellJunk
SexyMap
Shadowed Unit Frames
SilverDragon
TipTac
Titan Panel
TradeSkillMaster
Venture Plan
WeakAuras
XLoot

## Back Trace (LUA Error Output)
There is no LUA error.

**Comment by plusmouse** [comment]
The post button has always greyed out when the prices are loading though.

This build changes what might have altered the behaviour for you
[Auctionator-10.1.27-1-g4774119.zip](https://github.com/Auctionator/Auctionator/files/12892253/Auctionator-10.1.27-1-g4774119.zip)

**Comment by hollo6** [comment]
Yes of course it's inactive while the scan is running, my problem was it became inactive again AFTER they were loaded.
But this build indeed fixed it, seems fine again now!
Thank you for the quick solution!

**Comment by plusmouse** [comment]
Added the fix to the latest alpha, so going to close the issue.
