### ISSUE TITLE
Item price automatically selected not working

### ISSUE THREAD

**Issue by Dhisanas** [Auctionator/Auctionator#1441]
Please include as much of the following information as possible to help me fix the bug:
Auctionator option - selling: all items tab - choose how the item price is automatically selected:
various option doesn't seem to impact on the selection of the price

_Please include a brief description of the bug, including what you were doing, and when it occurred._
Let's say i was selling profession equipment, regardless of the option above mentioned selected it shows the various range of itemlevels from those items and select the lowest itemlevel price even tho i'm trying to sell the max itemlevel one

_Include the steps I would need to follow to reproduce the bug._
Seems to be working properly with battlepet but doesn't with boe and such

_Include a list of addons you were running at the time this bug occurred._
tried with no addons but auctionator buggrabber and bugsack and it still does it

_You can get this through the use of !BugGrabber and BugSack addons._
no bugs on those

**Comment by plusmouse** [comment]
I've put a fix in 10.1.27 which will be available from Curseforge shortly
