### ISSUE TITLE
Selling tab bag items sorting changed

### ISSUE THREAD

**Issue by hollo6** [Auctionator/Auctionator#1442]
## Brief Description of Bug
Sometime in the last ~2 weeks (don't know in which version exactly, but I can track it down if needed), the sorting of items changed in the Selling tab.
For example, these items: Blossom Burst, Glory Burst, Marrow Burst and Torch Burst were neatly grouped together somewhere at the beginning of the list, and now they are all over the place, so I'm guessing the sorting included the profession before this change and now it's alphabetical.
Is it possible to have the old sorting method back?

## Steps to Reproduce
1. Open Selling tab
2. Observe changed order of items

## Loaded Addons
N/A

## Back Trace (LUA Error Output)
There is no LUA error.

**Comment by LuumaLuuma** [comment]
Hi! I'm having this same issue for all crafted gear (I think they may be sorted by stat combos, but I'm not positive). Are you still experiencing this?

**Comment by hollo6** [comment]
Yes, it's still like this :(

**Comment by plusmouse** [comment]
I've reverted the sorting change (mostly, not exactly the same, but it should keep the grouping you saw before). It will be available on the next alpha release - just waiting for CF and Github to finish processing the build.
