### ISSUE TITLE
Bug with item real level in auctionator selling tab

### ISSUE THREAD

**Issue by Dunette57** [Auctionator/Auctionator#1443]
Hello,
Since the next upgrade of auctionator, the item level which can be seen in selling tab is not correct.

Example: The item I want to sell is level 79 (exact on the top) but the item level and caracteristics I can see with the mouse on the item is 183.

I post a screen to show: 
![WoWScrnShot_101423_130719](https://github.com/Auctionator/Auctionator/assets/147919548/35787161-e5a5-4a24-9dbb-a522d9d910ef)

**Comment by plusmouse** [comment]
Thanks for the report. I've added a fix to 10.1.28 which will be available from Curseforge shortly

**Comment by Dunette57** [comment]
thank ypu very much for been so quick !!!!

**Comment by Dunette57** [comment]
Sorry to comme back again but with the mornig patch, the bug has came back ...
