### ISSUE TITLE
Dragonflight profession tools using not the correct item level when listing

### ISSUE THREAD

**Issue by xxjonoxx** [Auctionator/Auctionator#1444]
Hi there, before the current release on retail, when I would list an profession tool item, such as Draconium Fisherfriend or the like, it would use the appropriate item level to set the listing price, and to check for undercuts. For example if the tool was 346 item level, when listing it would check for other 346s and choose that price to list it. However, in the latest release, it check for just the item name and not the item level. So if a 332 item has a lower price, it will undercut that one in the selling window. This affects the price for the items as auto listing it will list it at a lower value than it is worth.

Can it please be fixed to be like it was previous to the current release so 346 item level tools only check the price of other same item level items and set the price/cancel auction only on that item level?

**Comment by plusmouse** [comment]
There was a build where this broke, but it should be fine on the latest release

**Comment by plusmouse** [comment]
If it still isn't working its likely you just need to change the settings for item matching:
![image](https://github.com/Auctionator/Auctionator/assets/60280559/de0f6298-8671-4238-be9c-5fffd485b7b5)
found in:
![image](https://github.com/Auctionator/Auctionator/assets/60280559/f70b8c98-74e2-4115-8faa-75e70e1e3e0e)
