### ISSUE TITLE
[Feature request] Attempt to remove suffixes from armor/weapon names

### ISSUE THREAD

**Issue by althras** [Auctionator/Auctionator#145]
It could be quite simple - if the name of an armor or weapon item is in the structure of XXX of XXX, remove everything after the "of". Can make it a quick checkbox toggle or something. This will be very useful thanks to the transmog selling we're doing these days. It's a simple way to keep up with the more complicated transmog grouping of other addons.

**Comment by ceylina** [comment]
This has been brought up through out the past and the short answer is it is not something Auctionator can do.

On the buy tab, you are always able to remove anything in the search edit box past "of the" to browse for all items similar. On the sell tab, you want an exact match. Pricing data needs to be as agnostic as possible to get accurate results so manipulating that could potentially skew accurate results.
