### ISSUE TITLE
Crafted necks listing in weird stacks

### ISSUE THREAD

**Issue by paradisewoods** [Auctionator/Auctionator#1450]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug
--The PvP green crafted necklaces and the 319 blue necklaces are shown in two different stacks, despite being made by the same character and being the same ilvl

## Steps to Reproduce
Have several crafted necklaces in your bag, at least 40 just to be safe

## Loaded Addons
Around 50.
bigwigs, arkinventory, betterwardrobe, cinema canceller, deja character stats, titan panel, vuhdo, shadowed unit frames, weakauras, advanced interface options, masque, bartender... a *lot*. this happened when no other addons are enabled, though.

## Back Trace (LUA Error Output)
I'm not sure there is one?

Here's what it looks like
![auctionatorbug](https://github.com/Auctionator/Auctionator/assets/47625206/18fadffd-1c45-4ec0-bb7e-b498c2e561a8)

**Comment by plusmouse** [comment]
Can you screenshot the tooltip of the items?

**Comment by plusmouse** [comment]
This may be fixed in 10.1.32, can you test it?

[Auctionator-10.1.32.zip](https://github.com/Auctionator/Auctionator/files/13063322/Auctionator-10.1.32.zip)

**Comment by paradisewoods** [comment]
I uninstalled and even cleared saved variables, before installing the version you linked, but I'm still getting the issue. Here's what the tool tips look like when I mouse over each stack;
![sidebyside](https://github.com/Auctionator/Auctionator/assets/47625206/7e5ad575-0a76-413d-ac81-4e1a982dab8e)

**Comment by paradisewoods** [comment]
I deleted the addon and the saved variables, then installed with the link you provided. Unfortunate I'm still getting this problem. Here are the tooltips for each stack (the right stack, then the left);

![Uploading sidebyside.jpg…]()

**Comment by paradisewoods** [comment]
I deleted the addon and the saved variables, then installed with the link you provided. Unfortunate I'm still getting this problem. Here are the tooltips for each stack (the right stack, then the left);

![sidebyside](https://github.com/Auctionator/Auctionator/assets/47625206/dbc32dab-072b-4b59-b4ca-dbe732df00be)

**Comment by paradisewoods** [comment]
This has now spread to rings. I included tooltip screenshots, if this helps at all.

![sidebyside002](https://github.com/Auctionator/Auctionator/assets/47625206/b6fa5acf-10f0-41b0-a155-7f0fcd036813)

**Comment by plusmouse** [comment]
Sorry about the delay. This build should group them how they used to be:

[Auctionator-10.2.7-2-gd45eda3.zip](https://github.com/Auctionator/Auctionator/files/13696243/Auctionator-10.2.7-2-gd45eda3.zip)

**Comment by plusmouse** [comment]
Added the change to the normal releases now. Closing this issue as complete
