### ISSUE TITLE
Option to unhide single item is gone

### ISSUE THREAD

**Issue by bunghead** [Auctionator/Auctionator#1451]
## Brief Description of Bug

Right-click on a hidden item doesn't produce a menu to unhide it anymore.

## Steps to Reproduce

Click "Hide" on an item in the Selling tab. Drag the item from the bag into the Selling tab. Right-click the item's icon in the Selling tab. Option to "unhide" should show up, but doesn't.

Retail, v10.1.34

**Comment by plusmouse** [comment]
Find this feature restored in the latest alpha (available from Curseforge and Wago shortly)
