### ISSUE TITLE
Something happened making selling tab items are super small 

### ISSUE THREAD

**Issue by arkenbane** [Auctionator/Auctionator#1452]
I run two accounts with the same add-ons. Only my main account is experiencing this shrinkage issue of the seller's tab. It's really hard to see whats what.
Here's two pics of my accounts. One is the norm and the other is the hard-to-see icons.
![PXL_20231107_175005525](https://github.com/Auctionator/Auctionator/assets/34673068/6b5d7ea0-64e7-4d9b-b72c-933039ca3e34)
![PXL_20231107_180717077](https://github.com/Auctionator/Auctionator/assets/34673068/651913d3-a9b2-49f7-836f-51c7577325cc)

Is there something I can do to make the icons of items large again?

**Comment by plusmouse** [comment]
This will be caused by the icon size setting being too small:
![image](https://github.com/Auctionator/Auctionator/assets/60280559/7a9a6132-583b-42d9-b8d8-43f1e4527afc)

Change it to 35 for the default size on classic.

**Comment by arkenbane** [comment]
found it, thank you.
