### ISSUE TITLE
Restore support for GetAuctionBuyout

### ISSUE THREAD

**Issue by kemayo** [Auctionator/Auctionator#1454]
Before the big post-8.3 rewrite, Auctionator supported the user-invented [GetAuctionBuyout API](https://warcraft.wiki.gg/wiki/GetAuctionBuyout). This was convenient for other addons that wanted to ask about buyout prices, because they didn't need to care about what auction addons the user had installed. Sadly, this was removed in 1da253f1e164a61fa84bce96685b633e6b8fa823. (There was also GetSellValue, but that's not needed any more in retail.)

**Describe the solution you'd like**
Add the following somewhere appropriate in Auctionator:

```lua
local origGetAuctionBuyout = GetAuctionBuyout
function GetAuctionBuyout (item)
    local value
    if type(item) == "string" then
        value = Auctionator.API.v1.GetAuctionPriceByItemLink("GetAuctionBuyout", item)
    else
        value = Auctionator.API.v1.GetAuctionPriceByItemID("GetAuctionBuyout", item)
    end
    if origGetAuctionBuyout and not value then
        value = origGetAuctionBuyout(item)
    end
    return value
end
```
(Or more-directly call the internals, I guess.)

**Comment by plusmouse** [comment]
Going to reject this feature request.

This is an API that is likely to break after disuse and a lack of testing - it has taken 3 _years_ for someone to ask for it.
