### ISSUE TITLE
unkown Value for dragonflight D/E information

### ISSUE THREAD

**Issue by WhyDaRumGone** [Auctionator/Auctionator#1461]
When looking at the tooltip for dragonflight items it comes up with "unkown" as the Value for dienchanting.

I have no bug and this is the only auction addon.

**Comment by plusmouse** [comment]
Similar to the other issue, the data hasn't been compiled for the drop rates for items' disenchants in DF, which is made more complicated by all the modifiers DF crafting has that affect the drops (including things like specialisation points)

**Comment by WhyDaRumGone** [comment]
Again that sucks. I've been using rough estimates myself depending on the gear type and iLvL but I haven't tried any crafted gear.
Thanks for the feedback :-)
