### ISSUE TITLE
"Selling" tab has incorrect item prices, as if it cannot see most recent posts on the AH

### ISSUE THREAD

**Issue by ThralShaman** [Auctionator/Auctionator#1465]
When I open the Seasonal server on the 1.15 Classic client and use the auction house with your 10.2.2-classic or 10.2.3-classic versions of Auctionator I notice that in the Selling tab the suggested sell prices are based on incorrect or outdated AH values. 

Open interaction with Auctioneer, navigate to Sell tab, click on an item in the left area, take note of the suggested items currently on the AH, and their prices. From there I can click the Browse tab and see the actual items on the AH, which have more items, or lower prices. 
Below is an example where the Selling tab indicates no current auctions, but the Browse tab does.
![image](https://github.com/Auctionator/Auctionator/assets/153546239/608855c8-d073-4148-a572-46b5e058c877)
![image](https://github.com/Auctionator/Auctionator/assets/153546239/913206b6-56cd-418c-afcf-2ee78ff75f42)

Below is an example where the Selling tab shows inaccurate current prices compared to the Browse tab.
![image](https://github.com/Auctionator/Auctionator/assets/153546239/da1180b8-dcff-41b8-95ad-50b0aa2286da)
![image](https://github.com/Auctionator/Auctionator/assets/153546239/f29ad4c4-4bb3-4030-a950-8ae46906db11)

## Loaded Addons

![image](https://github.com/Auctionator/Auctionator/assets/153546239/e42fe35d-512f-4144-a06b-c9ff0117678c)

## Back Trace (LUA Error Output)

No error message.

I have attempted to:

1. Run Full Scan with the addon, still the same results.
2. Deleted and reinstalled the addon, same.
3. Tried 10.2.2 instead of the current 10.2.3 version of the addon, same.

What's confusing is that it happens for some items, not for all. I assume this means that the addon isn't keeping up with the AH items, but then that doesn't align with the first example where there are 4 items by 4 different sellers, so those must have been on the AH when I began to interact, or clicked the item (not sure when the addon scans). 

Would really appreciate any help or workaround on this, I love the efficiency of posting items quickly with this AWESOME addon :)

**Comment by plusmouse** [comment]
Can you search for the items in the Shopping tab and screenshot the shopping results?

**Comment by ThralShaman** [comment]
![image](https://github.com/Auctionator/Auctionator/assets/153546239/e52b161d-1cbb-4e96-a587-1e05e24a85c5)
![image](https://github.com/Auctionator/Auctionator/assets/153546239/7b3fa703-306d-4c2d-82ce-4ece103673f6)

**Comment by ThralShaman** [comment]
![image](https://github.com/Auctionator/Auctionator/assets/153546239/695b1509-c931-4ae5-990c-d3fc95352988)

**Comment by ThralShaman** [comment]
Shopping tab seems accurate

**Comment by plusmouse** [comment]
Ok. That narrows down the source of the problem. It looks like the code that tries to match the item you're selling to similar items with the same stats has broken and is now too specific.

Is there anything unusual about the item tooltips (those on the Shopping or Browse tabs)? Something SoD specific?

**Comment by ThralShaman** [comment]
![image](https://github.com/Auctionator/Auctionator/assets/153546239/3313efe8-22e4-42c9-a980-c86c22cfd820)
![image](https://github.com/Auctionator/Auctionator/assets/153546239/482f476d-f8e0-4c3c-b47d-efa7f6d5fe05)
![image](https://github.com/Auctionator/Auctionator/assets/153546239/19ef5388-3ca2-419a-9939-9ee6d41bff7e)
It all seems the same to me. I'm unaware of anything specific to SoD that would impact either the weapon or cloak items/slots. There are no enchants or anything else that would adjust tooltip.

**Comment by ThralShaman** [comment]
OH! I'm overlooking that my item somehow has 4 stam 4 strength... haha weird.

**Comment by ThralShaman** [comment]
AHA... it all makes sense now. 
![image](https://github.com/Auctionator/Auctionator/assets/153546239/5517b35e-aba3-45f3-9300-7bffc4f5e85f)
![image](https://github.com/Auctionator/Auctionator/assets/153546239/1c5b9428-67c4-420d-8000-ea6e1bb18955)
![image](https://github.com/Auctionator/Auctionator/assets/153546239/df9f9d0d-12e1-457d-8ae4-6e789d1a8611)

**Comment by plusmouse** [comment]
I suspect the increased shadow spell damage on the cloak and the increased stamina on the mallet are SoD specific, as this bug hasn't come up before.

Potentially need to add a way to see similar items in the Selling tab so that when this happens a price of some sort is generated.

**Comment by ThralShaman** [comment]
This cape can be within range of 3-4 shadow dmg
https://www.wowhead.com/classic/item=14161/pagan-cape
![image](https://github.com/Auctionator/Auctionator/assets/153546239/49151545-4751-47bd-a7dc-0e2ca5963422)

**Comment by ThralShaman** [comment]
I think this is the case for any item with the "of..." affix.

**Comment by plusmouse** [comment]
Ok. So it its just a fluke the issue hasn't cropped up before.

**Comment by ThralShaman** [comment]
Or players just haven't noticed the minor difference. In the case of hardcore min/max people will consider a higher value on items that have procced the absolute highest possible value, but again this is a small fringe case because most players are not going to consider a green item as their BIS.

**Comment by ThralShaman** [comment]
However, this would be the case with things like engineering goggles, or other crafted gear that has random affix.

**Comment by ThralShaman** [comment]
https://www.wowhead.com/classic/item=10504/green-lens
one example.

**Comment by plusmouse** [comment]
Ok. Looks like I need to add a way to see stat variants on the Selling tab for gear.

**Comment by plusmouse** [comment]
I've added a fix for this to the latest alpha releases, can you test if and verify it is working correctly?

[Auctionator-10.2.5-1-g8dc47dc-classic.zip](https://github.com/Auctionator/Auctionator/files/13671416/Auctionator-10.2.5-1-g8dc47dc-classic.zip)
