### ISSUE TITLE
Medicine Staff of the Eagle Bugged

### ISSUE THREAD

**Issue by CombatActionDad** [Auctionator/Auctionator#1466]
Please include as much of the following information as possible to help me fix the bug:

**Comment by plusmouse** [comment]
Is this in the price tooltip? In the Selling tab when posting?

Can you post a screenshot of the view that shows the wrong price and a screenshot of the results for the correct price.

**Comment by MrRogers-25** [comment]
I see the issue but I'm not sure I'm familiar enough with the codebase to resolve it.

Items such Medicine Staff of the Eagle, Medicine Staff of the Bear, Medicine Staff of the... all have the same item id. I'm wondering if `DBKeyFromLink` file is trying to handle this.  It looks like `dbKeys` are created based off the `itemId` found in the `itemLink` unless the item is gear. If the item is gear it grabs the item level and appends that onto the item id to create a dbkey such as `g:9797:28`. However, that's not enough to differentiate between these items. I believe if the suffix id, which can be pulled from the item link, was also included in the dbkey then this issue would be resolved.

**Comment by plusmouse** [comment]
Using the suffix id will mean that any stat variations will have their own unique prices, even those with the same full name.

This was tried on the Selling tab until recently when it was found to be hiding auctions and giving a misleading sense of the value of the item.

**Comment by MrRogers-25** [comment]
Ah, that would be annoying. Another potential option is using regex to find and append the suffix onto the `dbkey` in certain situations? Maybe you could create a dictionary that contains suffix’s and check against that if the item is gear. I know that’s not desirable, but it could work. I’m really not familiar with this stuff (Auctionator/wow-api) so I’m really spitballing here. I just happened to notice the same issue with “Ivycloth Pants of the…” yesterday only to come here and find someone with the same problem. 

What would be the downsides of using the name as the `dbkey`? Things I can think of:
* Table will grow in size
* Potentially renaming of new items (I know there was a typo on an item at the beginning of sod)

**Comment by plusmouse** [comment]
I've added a potential fix for this issue into the latest alphas

[(classic era/sod/hc) Auctionator-10.2.9-1-gbcb015f-classic.zip](https://github.com/Auctionator/Auctionator/files/13744632/Auctionator-10.2.9-1-gbcb015f-classic.zip)

[(wrath) Auctionator-10.2.9-1-gbcb015f-wrath.zip](https://github.com/Auctionator/Auctionator/files/13744633/Auctionator-10.2.9-1-gbcb015f-wrath.zip)

It combines the item level of the item with its name as the database key.

**Comment by plusmouse** [comment]
Closing this as fixed.
