### ISSUE TITLE
Shopping Deadly Blunderbuss, buy action placed a bid on 1 piece of Medium Leather

### ISSUE THREAD

**Issue by xoryth** [Auctionator/Auctionator#1467]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

When using the Shopping Tab for the item "Deadly Blunderbuss", the lowest cost item was 28s 93c. Clicked "Buy" button, then "Buy stack of 1". The action lagged the game intensely for about 30 seconds and then said "Bid Accepted". When I looked, it had not purchased a buyout for a Deadly Blunderbuss, but had instead placed a bid for 1 piece of Medium Leather for 28s 93c

## Steps to Reproduce

Shopping, Deadly Blunderbuss, Buy, Buy 1 stack, game lags and then you have a bid for medium leather at a way too inflated price.

## Loaded Addons

Bagnon
Scrap
DBM
Atlas
Auctionator
Bartender4
Capping
ClassicCastbars
Details!
Extended Character Stats
GTFO
LFG Bulletin Board
Mana Timer Classic
MobInfo2
OmniBar
OmniCC
OmniCD
Plater
Questie
RareScanner
TomTom
Vendor Price
Wow-Pro

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

No LUA Error addon installed...

**Comment by plusmouse** [comment]
Did the leather appear in the shopping results before you focused on the blunderbuss?

**Comment by xoryth** [comment]
> Did the leather appear in the shopping results before you focused on the blunderbuss?

Nope, only the Deadly Blunderbuss was showing.

**Comment by plusmouse** [comment]
What version of Auctionator are you on? (You can see this in the Auctionator tab at the ah)

**Comment by xoryth** [comment]
> What version of Auctionator are you on? (You can see this in the Auctionator tab at the ah)

10.2.6-classic

**Comment by xoryth** [comment]
![Auctionator 1](https://github.com/Auctionator/Auctionator/assets/153991016/aed0e235-ce18-43bb-a943-789c5dd614d8)
![Auctionator 2](https://github.com/Auctionator/Auctionator/assets/153991016/b14154a5-6942-4e7a-a5ba-9f1125ed14c9)
![Auctionator 3](https://github.com/Auctionator/Auctionator/assets/153991016/fbfd1f47-fd14-42bd-b20f-7c28a9cd2498)

**Comment by plusmouse** [comment]
The screenshots are helpful. Thanks.

When you have your mouse over the row for the item's stack in the shopping tab does a tooltip appear showing the blunderbuss?

**Comment by xoryth** [comment]
> does

It showed the Deadly Blunderbuss, nothing else. There were no signs that this was going to be a piece of Medium Leather, and a bid instead of a buy at that…

**Comment by plusmouse** [comment]
That should let me narrow down whether there's a bug in Auctionator's search or if it's issue is derived from the freeze

**Comment by xoryth** [comment]
![Auctionator 4](https://github.com/Auctionator/Auctionator/assets/153991016/1812c511-bed1-4359-b16a-bc46dedef316)

**Comment by xoryth** [comment]
Looks like someone is price fixing these now lol.

**Comment by plusmouse** [comment]
The freeze for 30s is what will have created the wrong purchase, but I'm unsure as to what could have made the frame rate drop for so long. The Auctionator code is configured to check that the purchase matches the visual on screen.

This suggests something shifted in the background to swap the item between mouse down and mouse up, presumably the freeze is so that there was time to load the new different item's auctions.

Should the search be broken and querying the wrong item viewing the Browse tab would have shown the wrong item.

**Comment by plusmouse** [comment]
I think this must have been a Blizzard bug, as it only occurred during December 2023, and haven't had any further reports.
