### ISSUE TITLE
Item level column

### ISSUE THREAD

**Issue by Arkewas** [Auctionator/Auctionator#1468]
Hello,

I suggest to add a Item level column when searching for items. This way it could be possible to sort items not only by price and name but also by  Item level, like the default WoW UI.

Thanks

**Comment by plusmouse** [comment]
Find this as an optional column in the latest alpha release https://legacy.curseforge.com/wow/addons/auctionator/files/4992058

**Comment by Arkewas** [comment]
> Find this as an optional column in the latest alpha release https://legacy.curseforge.com/wow/addons/auctionator/files/4992058

I really appreciate it, thank you very much.
Regards
