### ISSUE TITLE
Shopping Extended Search Options Save selected filters as List or search String

### ISSUE THREAD

**Issue by sdykae** [Auctionator/Auctionator#1470]
**Is your feature request related to a problem? Please describe.**
Describe the problem you are experiencing.

- There is no option to save the configuration of the filters as search option for custom searches
- ![image](https://github.com/Auctionator/Auctionator/assets/50224521/74b08778-f0c3-4f18-bf27-ad565597ee48)

**Describe the solution you'd like**

- Extended Search Options could be saved as a custom filter or search string to use the auctionator lists for items that are not known by the user but still could be found when filtering by categories

**Describe alternatives you've considered**

- Implementing a filter like shopping lists

**Additional context**

**Comment by plusmouse** [comment]
You can add an extended search term that is currently searched for to the current shopping list by clicking the "Add to list" button

**Comment by sdykae** [comment]
> You can add an extended search term that is currently searched for to the current shopping list by clicking the "Add to list" button

Ya but that only adds a string to the search, but the search options can return multiple items that could or could not be in the results

This feature is looking to use the filters of the advanced search as presets or saved searches to search for example, without knowing the item name, by expansion or lvl in a way we don't need to add those filters manually every time

**Comment by plusmouse** [comment]
That is exactly what adding the extended search term via add to list does. Can you screenshot your shopping list after using the Add to List button with an extended search active?
