### ISSUE TITLE
Separate the "refresh" button from the "buy" button

### ISSUE THREAD

**Issue by Apoxiosis** [Auctionator/Auctionator#1471]
Probably the most petty of complaints, but the refresh button is entirely too close to the buy button. I end up accidentally clicking it all the time, and as there is no way i'm aware of to cancel a scan, I have to close the window and search the auction again or wait for the addon to scan 153 pages of light leather

**Comment by plusmouse** [comment]
Added a cancel button for the loading to the UI, which should resolve this issue
