### ISSUE TITLE
Vendor Sell price Bug

### ISSUE THREAD

**Issue by frankdadad** [Auctionator/Auctionator#1472]
The vendor sell price seems to be off on WoW SoD.

**Comment by plusmouse** [comment]
Does this apply to gear and does the gear the price applies to need repairing?

**Comment by cherry-wave** [comment]
https://www.wowhead.com/classic/item=210781/phoenix-bindings sell price is 24s81c but addon tooltip says its 40s

**Comment by plusmouse** [comment]
This issue should be fixed now (was a Blizzard data bug)
