### ISSUE TITLE
Selling an item scans every page every time: Takes "forever"

### ISSUE THREAD

**Issue by helelena67** [Auctionator/Auctionator#1474]
Please include as much of the following information as possible to help me fix the bug:

## Are you on the retail or the classic version of WoW?
Classic WotLK

## Is this a bug or a feature request?
Bug

# Bug:
## Brief Description of Bug
When selling items the scanning goes on "forever".
Since before christmas (I think) this started to happen. 

## Steps to Reproduce

I go to AH
Make a full scan
Switch to sell tab
Select an item I want to sell
Getting "Fetching item info..." and "Scanning page xxx" for 5-10 minutes PER ITEM I want to sell.
If I actually wait all this time, then I get the normal behaviour for the rest of the sell process 
Auctionator does not find any current or historical prices, but I do get a suggested price from somewhere

This happens for each new item I never sold before. If I try to sell someting I have put up before then it works with normal quickness

I have tried to rename the folders and files for Auctionator - to the best of my knowledge which those are - and reinstalled the addon, since I though maybe my files got corrupted, but it didn't help
Auctionator have gotten updates at least twice since this problem started and every time I hope it will be fixed, but it hasn't been fixed yet.

## Loaded Addons
I have not other addson loaded on this toon since it is my bank and AH alt

**Comment by plusmouse** [comment]
Can you check whether this option is enabled/disabled for you?
![image](https://github.com/Auctionator/Auctionator/assets/60280559/63f0d358-8e30-45bb-a1ef-2f1c540e33bc)

**Comment by helelena67** [comment]
Nope it's not:

![image](https://github.com/Auctionator/Auctionator/assets/80787859/cba82107-4a46-4dbe-9eae-78f0524bd76a)

**Comment by helelena67** [comment]
Also, I installed Buggrabber and BugSack but BugSack says I have no bugs  - so whatever this is (if it is a bug or just SBS), it is not catched by the grabber...

**Comment by plusmouse** [comment]
Can you post some example items that were affected?

**Comment by helelena67** [comment]
https://www.wowhead.com/wotlk/item=25314/ceremonial-hammer  of the Eagle
![image](https://github.com/Auctionator/Auctionator/assets/80787859/d0d09ef2-62b3-44e7-9dee-a6e8a6610339)

**Comment by helelena67** [comment]
https://www.wowhead.com/wotlk/item=15151/ghostwalker-legguards

![image](https://github.com/Auctionator/Auctionator/assets/80787859/6680749e-8791-4182-91bd-6c00f19de693)

**Comment by plusmouse** [comment]
Hi. Sorry for the long delay, but I've replicated and fixed the issue now. Can you test this build, which is the latest alpha? The fix will be in the regular releases in the next few days.

[Auctionator-10.2.13-1-g753320b-wrath.zip](https://github.com/Auctionator/Auctionator/files/14000900/Auctionator-10.2.13-1-g753320b-wrath.zip)

**Comment by helelena67** [comment]
Seem to be working now - Thanks!

**Comment by plusmouse** [comment]
Great
