### ISSUE TITLE
Add fixAH module from Auctioneer to fix pre 8.3 paging issue

### ISSUE THREAD

**Issue by dhaern** [Auctionator/Auctionator#1477]
**Is your feature request related to a problem? Please describe.**
Before 8.3 AH have a paging issue where AH stop working while viewing items in "Browse" frame and/or after buying items.

**Describe the solution you'd like**
Auctioneer added a workaround to fix that and this is working good but many people dont like that addon and prefer other AH addons.

Here is the module description from Auctioneer:

```
## Title: Auc:Util:FixAH
## Notes: Works around a paging issue when viewing items in the Auction House "browse" frame.  Simply forces all new searches to show the results beginning on the first page.
```

**Describe alternatives you've considered**
I wonder if you can add a similar workaround to Auctionator Classic to fix that paging issue.

**Additional context**
Here you can find the source for the module Auc-Util-FixAH from Auctioneer Suite addon for Classic:

[https://gitlab.com/norganna-wow/auctioneer/auc-util-fixah/-/tree/master](https://gitlab.com/norganna-wow/auctioneer/auc-util-fixah/-/tree/master)

You can find a more updated version downloading latest Auctioneer Suite from Curseforge:

[https://www.curseforge.com/wow/addons/auctioneer/files](https://www.curseforge.com/wow/addons/auctioneer/files)

**Comment by plusmouse** [comment]
This shouldn't be an issue with Auctionator, as it always only scans the first page. So there's no need to reset the page counter - which is what happens in the fix.

What are you looking for in the Browse tab that means you can't use the Shopping tab, which would sidestep this potential issue entirely?
