### ISSUE TITLE
Seeing 2 different UIs between different machines

### ISSUE THREAD

**Issue by bkuhl** [Auctionator/Auctionator#1478]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

I see 2 different screens between a laptop and Desktop and I'd like to understand what's different here because I prefer the functionality of one over the other.  

What I currently see (notice the tabs):

<img width="598" alt="Screenshot 2024-01-09 at 6 16 21 PM" src="https://github.com/Auctionator/Auctionator/assets/524933/972153f2-4d50-4722-8f18-e6a7ff1ebdb7">

<img width="932" alt="Screenshot 2024-01-09 at 6 19 10 PM" src="https://github.com/Auctionator/Auctionator/assets/524933/f0449f7e-6260-43c6-94c9-b574138709ae">

What I want to see (and see on my desktop machine):

<img width="482" alt="Screenshot 2024-01-09 at 7 48 48 PM" src="https://github.com/Auctionator/Auctionator/assets/524933/a48cb59f-2c54-4797-9990-3fffc07846ba">

<img width="718" alt="Screenshot 2024-01-09 at 6 22 08 PM" src="https://github.com/Auctionator/Auctionator/assets/524933/c977b345-b586-4b38-aad1-50de52e85b33">

These 2 sets of tabs are very different and they even operate quite differently.  Can you provide any guidance on what might be driving this difference and what I can do to ensure consistency?

## Steps to Reproduce

I'm actually not sure... I sync'd the mod through Curseforge and it showed up looking differently on my Laptop.

## Loaded Addons

<img width="569" alt="Screenshot 2024-01-09 at 6 24 40 PM" src="https://github.com/Auctionator/Auctionator/assets/524933/c8959090-f93e-4fcb-b1da-dd706a9e8a1a">

<img width="525" alt="Screenshot 2024-01-09 at 6 24 53 PM" src="https://github.com/Auctionator/Auctionator/assets/524933/b1bdb5e7-7029-4771-b34f-7fe0c3851350">

<img width="527" alt="Screenshot 2024-01-09 at 6 25 01 PM" src="https://github.com/Auctionator/Auctionator/assets/524933/e2646e48-e17d-47de-98e8-ac5f58241f54">

<img width="528" alt="Screenshot 2024-01-09 at 6 25 09 PM" src="https://github.com/Auctionator/Auctionator/assets/524933/9d41e609-46c9-4bc1-89e5-5de31fe10f08">

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by plusmouse** [comment]
You've installed the classicfix variant of Auctionator on your laptop and the regular classic version on your desktop. Removing then reinstalling Auctionator on your laptop should resolve the issue

**Comment by bkuhl** [comment]
🤦 I could've sworn I tried that... this time after removing it the Curse client said Auctionator might've been corrupt, I'm guessing something the fix addon did.  Reinstalling it worked.  Thank you
