### ISSUE TITLE
Shopping scan continues in background when user clicks item in ResultsListing

### ISSUE THREAD

**Issue by jtrent614** [Auctionator/Auctionator#1479]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

When on the 'Shopping' tab, starting a search of a shopping list continues item by item, showing results in the ResultsListing/ShoppingResults frame.  Clicking a row hides the ResultsListing and shows the AuctionatorShoppingFrame (AuctionatorBuyFrameTemplateForShopping) frame for the individual item's detail, however if the search was not finished, it continues on in the background and causes issues with the Buy frame when the search finishes.
  
## Steps to Reproduce

1. Start a shopping list search
2. Immediately click the first result to be taken to that item's Buy list
3. Wait for search to finish and notice the screen refreshes, sometimes emptying the table completely, especially if you're trying to purchase an item as the search finishes

**Comment by plusmouse** [comment]
Thanks for the bug report. Resolved. Added a fix for both retail and wrath/sod to the latest alphas
