### ISSUE TITLE
Button overlapping (german locales)

### ISSUE THREAD

**Issue by flow0284** [Auctionator/Auctionator#1481]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

Playing with german client (ingame language german) in buyingtab the export-button overlaps with the result list.
![grafik](https://github.com/Auctionator/Auctionator/assets/27314841/dad1b6b9-3eef-49ca-beea-51920a292e43)
![grafik](https://github.com/Auctionator/Auctionator/assets/27314841/6afa5215-a9b7-4116-a1af-d19ce7a5331f)

## Steps to Reproduce

Set game language to german
Open AH
Switch to Buy-Tab

## Loaded Addons

ElvUI
ElvUI - Shadow and Light

## Back Trace (LUA Error Output)

N/A

**Comment by plusmouse** [comment]
Fixed in the latest alphas:
![image](https://github.com/Auctionator/Auctionator/assets/60280559/3a6466b4-5c37-4fa4-a9aa-19c098443d1c)
