### ISSUE TITLE
Wrong Item Listed Through Selling Tab With Two Items of Same Prefix

### ISSUE THREAD

**Issue by Abavao** [Auctionator/Auctionator#1482]
## Brief Description of Bug

I had multiple items with the following names, Grunts Pauldrons of the Bear - Grunts Pauldrons of the Tiger
I had a few of each of these

When I selected the of the Bear pauldrons, it properly scanned for of the Bear and filled in the proper price. Then, when I created the listing, it instead posted the more expensive of the Tiger version. The bear version is about 60silver, the Tiger version the 9gold.

After posting, I immediately had received the message that the of the Tiger versions had sold, even though I selected the Bear versions, because of the massive price difference.

I double checked the chat logs, and it had even stated Auctionator: auction created for the of the Bear version. Then, it immediately said Auction sold for of the tiger. The bear version never left my inventory, but the incorrect tiger did.

It is also worth noting I never got the popup that typically displays saying "A large price drop has been detected" when listing something significantly lower than the other listings.

## Steps to Reproduce

- Obtain a few Grunts Pauldrons of the Bear and Grunts Pauldrons of the Tiger
- Go into the Selling tab and select the of the Bear version
- The price will properly pull and populate for the of the Bear listing
- Create the listing but watch as it instead lists the other version of the shoulders, the of the Tiger ones

## Loaded Addons

AtlasLootClassic, Auctionator, Bagnon, ClassicAuraDurations, DBM, Details, LFGBulletinBoard, OmniCC, Plater, Questie, Ranker, Scrap , TSM, VendorPrice, WeakAuras

## Back Trace (LUA Error Output)

No LUA error was given since no error was displayed

**Comment by plusmouse** [comment]
There was a similar potential Blizzard bug with purchasing in December 2023, so this might be an extension of that. I've tested listing with multiple items with the same name but different suffixes and couldn't replicate the issue.
