### ISSUE TITLE
Pets in favorite group, or loaded from favorite, do not show the actual breed in tooltip

### ISSUE THREAD

**Issue by tflo** [Auctionator/Auctionator#1483]
#### Example:

Option "Always show favorite group items, including when not in bag" is enabled.

1. Add a level-1 P/S Iron Starlette to favorites (Selling tab).
2. Have only a level-1 P/B Iron Starlette in the bags.

The quantity indicator of the fav icon in the Selling tab now shows "1" and it lets me load (select) the pet by clicking the fav icon. Both tooltips, the one from the favorite icon and the bigger icon after clicking the favorite show the pet as P/S, which is not the breed of the actual pet in bags (but the breed of the saved favorite):

<details>
<summary>Tooltip from fav in fav group (bad)</summary>
<img width="407" alt="fav from slot - wrong-fs8" src="https://github.com/Auctionator/Auctionator/assets/1410282/712048f7-a665-4911-a6c5-7e2bfa4f5717">
</details>
<details>
<summary>Tooltip from fav loaded into main icon field for posting (bad)</summary>
<img width="284" alt="fav - wrong-fs8" src="https://github.com/Auctionator/Auctionator/assets/1410282/809941e5-f965-40b4-8538-093f0edf5d61">
</details>

The tooltip of the regular (non-fav) icon in the Selling tab shows the breed correctly:

<details>
<summary>Tooltip from "real" item (good)</summary>
<img width="290" alt="slot - correct-fs8" src="https://github.com/Auctionator/Auctionator/assets/1410282/68d38312-f9ca-42c6-bd64-20a1f2288832">
</details>

If one is not aware of this behavior, then posting from the fav icon will lead to posting the wrong variant. This might seem trivial with the example pet, but there are [pets](https://undermine.exchange/#eu-draenor/search/Gilnean%20Raven) where the breed makes a difference of several 100k gold.

To avoid errors, you must be aware of the issue and strictly only ever post from the "real" (in-bag) icon in the Selling tab, or from the bags directly.

### Thinkable solutions:

- Make the favs **strictly breed-specific** (they are already level-specific): 
  - Counter shows "1" only if there really is one of that breed in the bags, and clicking the fav _does not_ load a fictive variant for posting.
- Make the favs **completely breed-agnostic** (but not level-agnostic!): 
  - If I have one P/B and one P/S (of the same level) in my bags, the counter should show "2".
  - The tooltip breed info of the fav icon should either be undefined (showing "??" if this is technically feasible, no idea), or should show just the breed of _any_ of the variants actually present in the bags.
  - After loading (clicking) the fav for posting, the main icon (of the loaded pet) should show the _actual breed of the loaded variant_ that is going to be posted.[^1]

I tend to prefer solution 2 (breed-agnostic), as it can save quite some space in the fav compartment. And if the tooltip _of the loaded pet_ icon is correct, then it is possible to reliably post the correct variant.

[^1]: If I remember correctly, this was the case with some previous version of Auctionator (like some months ago). But not 100% sure, memory may fail.

**Comment by plusmouse** [comment]
Fixed in the latest alphas (available from Curseforge/Wago shortly)

**Comment by plusmouse** [comment]
Fixed in the latest alphas (available from CF and Wago when they finish processing)

**Comment by tflo** [comment]
Thanks for the fix, seems fine now.

BTW, also thanks for showing the pet level above the icon now!

Now it would be absolutely great (godlike) to have the breed shown there as well:

<img width="302" alt="Screenshot of Affinity Photo 2 at Feb 24, 2024 at 13_47_04-fs8" src="https://github.com/Auctionator/Auctionator/assets/1410282/10c07455-f278-41b1-b4b2-664021148c53">

But nah, we don't want to exaggerate, Auctionator is already good enough 🤐
