### ISSUE TITLE
Pricing Error #Bug

### ISSUE THREAD

**Issue by Vexbane** [Auctionator/Auctionator#1485]
Classic SoD

#Bug

[Phoenix Bindings] show the wrong vendor price.... I have tried lots of other addons that also show the wrong vendor price for these, not sure why.... many of them specifically made for vendor pricing... However, Leatrix Plus addon is the only one that shows the correct vendor price.... Any idea what is causing this?

For reference.  The wrong vendor price that is showing with Better Vendor Price= 40silver.  Leatrix price (correct vendor price) = 24 silver 81 copper

Just for troubleshooting / testing purposes, All other addons were off when testing Better Vendor Price.  Subsequently, when testing just Leatrix Plus, all other addons were off.  If I tried to have both Leatrix and Better Vendor Price enabled by themselves with no other addons, Better Vendor Price overrides Leatrix Price line, giving me the wrong info.

Edit:  (new info) Even with only using Leatrix Plus Addon, the wrong price 40silver (real price is 24s 81c) would come back.  So removed all addons from the actual c:\wow \ addon folder location and temp moved the WTF folder out to have things be 'default' then restarted PC and found that when going to vendor, as soon as you open vendor window and mouse over the item, it still shows the incorrect vendor price.  So, Blizzard's fault?  If so, Leatrix Plus addon must somehow get the data for vendor prices different than how auctioneer, auctionator and other vendor price addons, in order to "temporarily" (until breaks again) show the correct pricing.

**Comment by Vexbane** [comment]
added update to OP "edit"

**Comment by plusmouse** [comment]
How have you confirmed the sell price to be 24s81c?

**Comment by Vexbane** [comment]
> How have you confirmed the sell price to be 24s81c?

by seeing my gold/silver before and after selling it.  the reason why i noticed was because in auctioneer, the search by 'vendor' price option, i bought a lot of these out but was not making profit like it was showing I would, so I thoroughly tested all the above

**Comment by Vexbane** [comment]
![wowprice](https://github.com/Auctionator/Auctionator/assets/46516092/e3acda7c-cad4-4d49-827a-a63d32a8ea81)

reply from another forum

**Comment by plusmouse** [comment]
As this is a Blizzard issue not going to add a fix to Auctionator.
