### ISSUE TITLE
Cant shift click enchanting mats

### ISSUE THREAD

**Issue by Secretsquirrel73** [Auctionator/Auctionator#1486]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

_Please include a brief description of the bug, including what you were doing, and when it occurred._
Every profession window you can shift click the required mats icon at the bottom and it will search for the mat you shift clicked, enchanting profession does not have this option. 

## Steps to Reproduce
Open auction>Open Enchanting>Select a recipe> Shift click 
_Include the steps I would need to follow to reproduce the bug._
Open auction>Open Enchanting>Select a recipe> Shift click material needed> Does not search regardless as its profession based. 
## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._
Did it with just the addon itself
## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._
No error, just not included like every other mat is.

**Comment by plusmouse** [comment]
Is this on Era/HC/SoD or Wrath?

**Comment by Secretsquirrel73** [comment]
Oh this is on SoD I am sorry.

**Comment by plusmouse** [comment]
Now fixed in the latest alpha:
[Auctionator-10.2.24-2-g63c0756-classic.zip](https://github.com/Auctionator/Auctionator/files/14302599/Auctionator-10.2.24-2-g63c0756-classic.zip)

**Comment by Secretsquirrel73** [comment]
absolutely SIIIIIICK
