### ISSUE TITLE
Stopped working: "Select the last item selected for posting when opening the Selling tab"

### ISSUE THREAD

**Issue by tflo** [Auctionator/Auctionator#1487]
Somewhere in last few weeks (or months?), the "Select the last item selected for posting when opening the Selling tab" option stopped working for me, i.e. when I reopen Auctionator - and even when I just switch tabs - nothing is selected in the Selling tab, even though the last item selected is still there.

![Screenshot of Wow at Feb 27, 2024 at 01_58_08](https://github.com/Auctionator/Auctionator/assets/1410282/e6a36f75-64f3-43d3-bb4f-5167d72d45b9)

**Comment by zeenk** [comment]
It broke with this build https://www.curseforge.com/wow/addons/auctionator/files/5100004

**Comment by plusmouse** [comment]
Fixed in the latest alpha. Available from Curseforge/Wago shortly.
