### ISSUE TITLE
Show Average price in tooltip, combine among chars

### ISSUE THREAD

**Issue by cars11** [Auctionator/Auctionator#1488]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
My bankchar visits the auction house a lot more often than my main. I love having a tooltip showing me the acutionhouse price on any item anywhere in the world.
But this price is often outdated if I'm not on my bankchar. Can the prices from scans not be combined? So the latest one is used regardless of character?
And even better, another price with the average would be great in the tooltip

**Comment by plusmouse** [comment]
The latest price from your bank character should be shared between characters.

For average tooltips you use 
```
/atr config auction_mean_tooltips true
```
to turn them on
And 
```
/atr config auction_meant_days_limit 12
```
 to set the days to 12, for example
(limited  to 21)
