### ISSUE TITLE
Options Saved Variables Account or Server Wide

### ISSUE THREAD

**Issue by Jayshua83** [Auctionator/Auctionator#149]
Could we get Auctionator Options Saved Variable Profiles to be able to be created? I'd like the same options across all toons!

**Comment by ceylina** [comment]
Should be able to look into this and see if we can work something up. A feature like this might not make it for when Legion launches as we are focusing on stabilizing the current state of Auctionator.

**Comment by ceylina** [comment]
90% of the addon is server wide minus the tooltip settings and those are pretty trivial.  I believe, to have scans per character would create unnecessary overhead, as a server's data is relevant to every character on the server and the way this addon handles it now seems the most efficient method.
