### ISSUE TITLE
need a button in the Selling tab to mark item as junk for later selling to a vendor instead of listing in AH

### ISSUE THREAD

**Issue by R-Adrian** [Auctionator/Auctionator#1493]
**Describe the solution you'd like**
If it is possible, some integration with the Scrap junk seller addon would be needed
https://github.com/Jaliborc/Scrap
https://www.curseforge.com/wow/addons/scrap

reason: Need a button in the "Selling" tab to mark the current item being considered for posting in AH as scrap/junk, so that the Scrap (junk seller) addon can recognize it as something to be sold at the next vendor visit.

**Describe alternatives you've considered**
after visiting the AH and deciding not to list some items, except just manually reviewing leftover items in bags... there is no real alternative that i could find.
I currenty have so many junk items (green/blue/purple quality) in bags that i literally gave up even manually reviewing them.

**Comment by plusmouse** [comment]
Not going to add an integration with Scrap. Possible alternative is searching for BoE&gear items in your bags and vendoring those. https://www.curseforge.com/wow/addons/baganator has a search box which will support that query and a one-click button to vendor everything matching the query.
