### ISSUE TITLE
Searching, buying, posting freezes the game for a few seconds

### ISSUE THREAD

**Issue by paulmm2125** [Auctionator/Auctionator#1497]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

Searching, buying, posting freezes the game for a few seconds (feels like 5-10 s). Specifically happens when searching and then clicking to expand the item availability by price triggers this issue. Then buying the item triggers the issue when the data is being refreshed. Posting items to sell also triggers this freeze.

## Steps to Reproduce

Specifically happens when searching and then clicking to expand the item availability by price triggers this issue. Then buying the item triggers the issue when the data is being refreshed. Posting items to sell also triggers this freeze.

## Loaded Addons

AchievementsReminder: enabled
AllTheThings: enabled
Auctionator: enabled
BagBrother: enabled
Bagnon: enabled
Bagnon_Config: enabled
Bagnon_GuildBank: enabled
Bagnon_VoidStorage: enabled
BattlePetBreedID: enabled
Battle Pet Daily Tamer: enabled
Details: enabled
Details_Compare2: enabled
Details_EncounterDetails: enabled
Details_RaidCheck: enabled
Details_DataStorage: enabled
Details_Streamer: enabled
Details_TinyThreat: enabled
Details_Vanguard: enabled
EnhancedRaidFrames: enabled
GladiusEx: enabled
GSE: enabled
GSE3-Elfyau_Paladin: enabled
GSE_GUI: enabled
GSE_LDB: enabled
HandyNotes: disabled
HandyNotes_Argus: enabled
HandyNotes_BrokenShore: enabled
HandyNotes_LegionClassOrderHalls: enabled
Handynotes_Pandaria: enabled
HandyNotes_BattleForAzeroth: enabled
HandyNotes_BattleForAzerothTreasures: enabled
HandyNotes_Draenor: enabled
HandyNotes_Dragonflight: enabled
HandyNotes_DragonflightTreasures: enabled
HandyNotes_DungeonLocations: disabled
HandyNotes_LegionTreasures: enabled
HandyNotes_LongForgottenHippogryph: enabled
HandyNotes_MistsOfPandariaTreasures: enabled
HandyNotes_MoleMachine: disabled
HandyNotes_Oribos: enabled
HandyNotes_ScourgeInvasionShadowlands: disabled
HandyNotes_Shadowlands: enabled
HandyNotes_SuramarTelemancy: enabled
HandyNotes_Valdrakken: enabled
HandyNotes_TreasureHunter: enabled
HandyNotes_WellRead: enabled
HandyNotes_WitheredArmyTraining: enabled
HandyNotes_DragonGlyphs: enabled
HandyNotes_Lorewalkers: enabled
HandyNotes_PandariaTreasures: enabled
Leatrix_Plus: enabled
HandyNotes_NetherwingEggs: enabled
Overachiever: disabled
Overachiever_Cache: disabled
Overachiever_Tabs: disabled
Overachiever_Trade: disabled
Pawn: enabled
PetBattleMaster: enabled
PetTracker: enabled
PetTracker_Battle: enabled
PetTracker_Config: enabled
PetTracker_Journal: enabled
RaidAchievement: enabled
RaidAchievement_LegionHeroics: enabled
RaidAchievement_LegionRaids: enabled
RaiderIO_DB_US_M: enabled
RaiderIO_DB_EU_M: disabled
RaiderIO_DB_KR_M: disabled
RaiderIO_DB_TW_M: disabled
RaiderIO: enabled
RaiderIO_DB_US_R: enabled
RaiderIO_DB_EU_R: disabled
RaiderIO_DB_KR_R: disabled
RaiderIO_DB_TW_R: disabled
RaiderIO_DB_US_F: enabled
RaiderIO_DB_EU_F: disabled
RaiderIO_DB_KR_F: disabled
RaiderIO_DB_TW_F: disabled
RareScanner: enabled
Scrap: enabled
Scrap_Merchant: enabled
Scrap_Config: enabled
TomCats: enabled
TomTom: enabled
TradeSkillMaster: enabled
WeakAuras: disabled
WeakAurasArchive: enabled
WeakAurasModelPaths: enabled
WeakAurasOptions: enabled
WeakAurasTemplates: enabled
WorldQuestTracker: enabled
WorldQuestsList: enabled
WQAchievements: enabled
Blizzard_ObjectiveTracker: enabled
Blizzard_CompactRaidFrames: enabled
WeakAurasCompanion: enabled
TomCats-ArathiHighlandsRares: disabled
TomCats-DarkshoreRares: disabled
TomCats-Mechagon: disabled
TomCats-Nazjatar: disabled
TomCats-Nzoth: disabled
TomCats-WarfrontsCommandCenter: disabled
TomCats-Complete: disabled
TomCats-ChildrensWeek: disabled
TomCats-HallowsEnd: disabled
TomCats-LoveIsInTheAir: disabled
TomCats-LunarFestival: disabled
TomCats-Noblegarden: disabled
HealBot: disabled
WowheadQuickLink: enabled
Blizzard_CombatText: enabled
TidyPlates_ThreatPlates: disabled
Plater: enabled

## Back Trace (LUA Error Output)

N/A

**Comment by plusmouse** [comment]
This is not happening for me. So likely another addon is interfering. Can you try with just Auctionator enabled and check if it still happens?

**Comment by paulmm2125** [comment]
Seems like the issue is caused by the BagAppraiser addon when using Auctionator data to update item values.
