### ISSUE TITLE
previously available functionality has been removed

### ISSUE THREAD

**Issue by reussered** [Auctionator/Auctionator#1498]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

_Please include a brief description of the bug, including what you were doing, and when it occurred._

## Steps to Reproduce

_Include the steps I would need to follow to reproduce the bug._

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by reussered** [comment]
In the version of Baginator available before this release, I was able to set up my bags for auction with a single button click (shift left-click on the transfer button). This function collected a single sample of every available item (up to a full stack) in my bag. This function is essential for using the auction house because otherwise duplicate stacks would prevent me from carrying all of the items I have to sell. Doing this by hand takes at least an hour.

This functionality was working perfectly.  Please put it back, or explain where it has been moved to.

**Comment by plusmouse** [comment]
I won't be including highly specialised functionality in the addons (which this was, as per my determination), as it complicates existing code that has to accommodate it, and I'm then expected to keep the feature compatible with the latest versions of WoW (classic or retail), which is an unwanted maintenance burden.
