### ISSUE TITLE
Option to disable chat output when posting an auction.

### ISSUE THREAD

**Issue by Luke1410** [Auctionator/Auctionator#1500]
At the moment Auctionator seems to put a chat output when posting an auction in the chat window:

![image](https://github.com/Auctionator/Auctionator/assets/15809174/74590b25-4d60-4824-9389-9e5eaadd6363)

It would be handy, if there was an option to disable the output (the line: "Auctionator: [itemlink]....".

**Comment by plusmouse** [comment]
The option exists:
![image](https://github.com/Auctionator/Auctionator/assets/60280559/f31a9591-f7e8-432a-8ed6-c800ee77a4b2)

**Comment by Luke1410** [comment]
ouch, thx... not sure how I overlooked that one.
