### ISSUE TITLE
Full Scan Shows Unique items, not total auctions

### ISSUE THREAD

**Issue by kdtresh** [Auctionator/Auctionator#1503]
## Brief Description of Bug

Full scan seems to be missing a large number of auctions. This has been observed in both SoD and [now] Cata classic.

## Steps to Reproduce

1. Open AH and go to Auctionator tab.
2. Click the "Full Scan" button and wait for it to complete.
3. Observe the number of items processed in the chat window.

## Loaded Addons

  Swatter, v3.4.6977 (SwimmingSeadragon)
  ArkInventory, v31027
  ArkInventoryRules, v31027
  ArkInventorySearch, v31027
  Atlas, vv1.52.08
  AtlasBurningCrusade, vv1.52.03
  AtlasClassicWoW, vv1.52.05
  AtlasDungeonLocs, vv1.52.04
  AtlasWrathoftheLichKing, vv1.52.03
  AtlasLootClassic, vv1.1.1
  AtlasLootClassicData, vv1.1.1
  AtlasLootClassicDungeonsAndRaids, vv1.1.1
  AucAdvanced, v3.4.6952 (SwimmingSeadragon)
  AucFilterBasic, v3.4.6941 (SwimmingSeadragon)
  AucStatHistogram, v3.4.6928 (SwimmingSeadragon)
  AucStatiLevel, v3.4.6913 (SwimmingSeadragon)
  AucStatPurchased, v3.4.6910 (SwimmingSeadragon)
  AucStatSimple, v3.4.6911 (SwimmingSeadragon)
  AucStatStdDev, v3.4.6912 (SwimmingSeadragon)
  AucUtilFixAH, v3.4.6914 (SwimmingSeadragon)
  Auctionator, v10.2.36
  BeanCounter, v3.4.6983 (SwimmingSeadragon)
  DBMCore, v10.2.37
  DBMStatusBarTimers, v10.2.37
  DBMVPVEM, v4a10f12
  Enchantrix, v3.4.6979 (SwimmingSeadragon)
  EnchantrixBarker, v3.4.6917 (SwimmingSeadragon)
  GatherMate2, v1.47.4-classic
  GatherMate2GasClouds, v2.3
  HandyNotes, vv1.6.19
  Informant, v3.4.6980 (SwimmingSeadragon)
  ItemRack, v4.00
  Questie, v10.0.2
  Recount, vv3.4.3c
  SlideBar, v3.4.6919 (SwimmingSeadragon)
  Stubby, v3.4.6920 (SwimmingSeadragon)
  TitanClassic, v1.5.12.30403
  TitanClassicAmmo, v1.5.12.30403
  TitanClassicBag, v1.5.12.30403
  TitanClassicClock, v1.5.12.30403
  TitanClassicGold, v1.5.12.30403
  TitanClassicLocation, v1.5.12.30403
  TitanClassicLootType, v1.5.12.30403
  TitanClassicPerformance, v1.5.12.30403
  TitanClassicRegen, v1.5.12.30403
  TitanClassicRepair, v1.5.12.30403
  TitanClassicVolume, v1.5.12.30403
  TitanClassicXP, v1.5.12.30403
  TitanSocial, v3.4.0
  TradeSkillMaster, vv4.13.24
  BlizRuntimeLib v4.4.0.54500(US) <enUS>
  (ck=6e8)

## Back Trace (LUA Error Output)

No LUA error occurred.

## Notes

I am unsure how to get a verifiable "actual" number of auctions, I just know that on the Pagle server of WotLK classic the number of auctions was typically over 120,000. Auctioneer was also choking on it at times (I think the highest number on a successful scan was in the 140k range, failed scans typically reported 110-120k with 20k-ish unresolved). Also, on Wild Growth SoD server it was consistently around 40-50k auctions, with Auctioneer rarely having issue. On both servers, Auctionator seems to return something in the ~22k items range, which does not seem correct. Auctioneer is currently borked on Cata classic, so all I have to go on is regular scans up until a couple days ago and SoD, where it still seems to be functional, and Auctionator seems to be capping in the low 20k range when many more auctions exist.

Interestingly, the number of unresolved/missed items for Auctioneer on LK seems to be in the same range as the number of items processed by Auctionator in all cases. I can get more data if it is needed.

**Comment by plusmouse** [comment]
The 20k refers to the number of different types of _items_ on the AH.

**Comment by kdtresh** [comment]
Is there any indication of how many auctions where scanned/processed?

Thanks for your quick response!

**Comment by plusmouse** [comment]
Not currently. You can run `/dump GetNumAuctionItems("list")` immediately after a full scan to see how many auctions Auctionator had to look at though.

**Comment by kdtresh** [comment]
Just scanned and ran that command, result was:
Dump: value=GetNumAuctionItems("list")
[1]=0,
[2]=0

For reference, the "Full Scan" button also triggered an Auctioneer scan.

Chat frame output:

Auctionator: Finished processing 10299 items.

Auctioneer finished scanning 51514 auctions over 20Secs
48146 items in DB at start (48146 matched query), 51514 at end
20112 unchanged items
4833 updated items
6469 new items
4310 items removed
20100 filtered items
1651 filtered items removed

**Comment by plusmouse** [comment]
Go to line 213 in `Auctionator/Source_Classic/FullScan/Main.lua` and add `print("auctions", #rawFullScanData)` This will print the number of auctions that Auctionator found item data for.

**Comment by kdtresh** [comment]
I put it on line 217 (with blank before and after) but the file is actually Source_Classic\FullScan\Mixins\Frame.lua, for reference.

Another full scan yielded:
Auctionator: Finished processing 10411 items.
auctions 53025
Auctioneer finished scanning 53026 auctions over 18Secs
51514 items in DB at start (51514 matched query); 53026 at end

That definitely indicates it's getting them all, is there any way to push that type of output into the default (or at least as an option)? The number of auctions seems more useful than the number of items, at least to me, and it seems like a fairly trivial change to implement (we just did it, minus the UI integration, in less than a minute).

Thanks again for the quick response.

**Comment by plusmouse** [comment]
There's no plans to change the output.
