### ISSUE TITLE
Addon not found

### ISSUE THREAD

**Issue by Jingliu90** [Auctionator/Auctionator#1504]
Hi, i have the Auctionator installed and used it before cataclysm, but now it doesn't appear in the ingame addon list anymore. even after deleting and reinstalling

**Comment by Kelryth** [comment]
Just update Auctionator_Wrath.toc add 40400 to ## Interface, save as Auctionator_Cata.toc and it should work. I also upped the ## version from 10.2.36 to 10.2.37 but i'm not sure that is necessary. I've briefly tested it and it seems to work now.

**Comment by plusmouse** [comment]
This issue is resolved by updating to the Cataclysm version of Auctionator. Available in your add-on manager (which will need updating) or from Curseforge
