### ISSUE TITLE
Addon does not appear in the list of addons... had to change a file name to get it to show up.

### ISSUE THREAD

**Issue by d-wow-guy** [Auctionator/Auctionator#1505]
Please include as much of the following information as possible to help me fix the bug:

## Are you on the retail or the classic version of WoW?

Classic - Cata

## Is this a bug or a feature request?
# Bug:
## Brief Description of Bug
addon doesn't appear in the list of addons.  Others are there just fine.  Have "load out of date addons" selected.

## Steps to Reproduce

download addon using WowUp.io.

## Back Trace (LUA Error Output)

no output because it doesn't load

## Additional context

I navigated to the AddOns folder to look at the files.  After many attempts to clear the folder, even only having auctionator as the only addon it would not work.  It would not show in the AddOns window.

Looking at the files I noticed that the folder name is Auctionator, and the main file in the directory was Auctionator_Wrath.toc.  This looks wrong.  When I change the name of this file to Auctionator.toc everything works just fine.  Not sure if something went wrong with the decompressing or what.

I use WowUp.io app to manage my addons.

After a bit more snooping I downloaded directly from the curseforge website and there were 2 .toc files.  One was _wrath.toc and the other _cata.toc.  The _cata.toc was missing and I don't understand how the game decides which to use, maybe based on the client.  But it seems that there is something with the package distribution.

**Comment by plusmouse** [comment]
This is an issue with wowup.io downloading the wrong version of Auctionator for Cataclysm

**Comment by d-wow-guy** [comment]
Yeah seeing that now.  I didn't realize how many different versions you guys were keeping up with.  It looks like they are still pointing to the wrath download so I put it to them.  Thanks.
