### ISSUE TITLE
Auctionator not showing up

### ISSUE THREAD

**Issue by PBCjimbo** [Auctionator/Auctionator#1506]
Please include as much of the following information as possible to help me fix the bug:

My Auctionator add-on stopped showing up when pre-patch update released. I assumed it had to do with the large update. Now the add-on has been updated and my friends are using it but it still doesn't show up on my add-on list or change anything in my game. I have tried deleting and reinstalling it several times, as well as closing and relaunching World of Warcraft.

## Loaded Addons

Ace3, AtlasLootClassic, Attune, Auctionator, Bagnon, Core Loot Manager, Deadly Boss Mods, Decursive, Details! , Gargul, GatherMate 2 Classic, GTFO, Guild Roster Manager, Loon Best in Slot, MapCoords, Method Raid Tools, Mount Journal Enhanced, Neat Minimap, PallyPower, Pawn, Questie, RareScanner, SharedMedia, Speedy AutoLoot, TacoTip, ThreatClassic2, VuhDo, WeakAuras

![Screenshot (7)](https://github.com/Auctionator/Auctionator/assets/168888322/9af00dcc-8e4f-4bf9-978c-8b234f5b5ea2)
![Screenshot (3)](https://github.com/Auctionator/Auctionator/assets/168888322/8b3804eb-63c2-4fa6-b831-c3a343c704bb)
![Screenshot (4)](https://github.com/Auctionator/Auctionator/assets/168888322/8ea4d89a-8c3f-4b2c-ad21-5e01fa45b540)
![Screenshot (5)](https://github.com/Auctionator/Auctionator/assets/168888322/21afdade-7e24-4686-8ad7-221a3afde784)
![Screenshot (6)](https://github.com/Auctionator/Auctionator/assets/168888322/3f6188c6-3739-4478-b687-2d1e58ef79a1)

**Comment by plusmouse** [comment]
Hi. Your version of Curseforge is out of date and installing the Wrath edition of Auctionator. Either update your version of the Curseforge app, or install the zip found at https://www.curseforge.com/wow/addons/auctionator/files/5312618
