### ISSUE TITLE
Items not showing up on Search

### ISSUE THREAD

**Issue by ksjdgb** [Auctionator/Auctionator#1507]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

No items comes up when searching (tried multiple that I know are on AH). No items comes up when adding an item from my bag in the selling tab, so can't see how many of that item and to what prices is on the AH at the moment. I'm playing SoD and noticed this in Tanaris, have not tried any other AH. 

## Steps to Reproduce

Search for an item on AH or add an item on the selling tab.

## Loaded Addons

Questie, Deadly boss mode, mage book tracker, baganator, enhanced-world-map-for-wow-classic, syndicator.

## Back Trace (LUA Error Output)

Don't have this sorry

**Comment by plusmouse** [comment]
Can to specify a few items that you know should be there?
