### ISSUE TITLE
Custom Groups not found in release 10.2.40

### ISSUE THREAD

**Issue by reussered** [Auctionator/Auctionator#1508]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

_Please include a brief description of the bug, including what you were doing, and when it occurred._

## Steps to Reproduce

_Include the steps I would need to follow to reproduce the bug._

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by reussered** [comment]
I used this feature extensively. I have signed up to support the program at the 5/month level. Will it become available at the 10/month level? This feature has been in Auctionator for at least 3 months and has been working very well without any issues at all.  I am more than glad to up my support to 10/month to have access to this feature again.

**Comment by plusmouse** [comment]
There are no plans to readd the custom groups feature.
