### ISSUE TITLE
Post and Skip do not work in version 10.2.40

### ISSUE THREAD

**Issue by reussered** [Auctionator/Auctionator#1509]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

_Please include a brief description of the bug, including what you were doing, and when it occurred._

## Steps to Reproduce

_Include the steps I would need to follow to reproduce the bug._

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by reussered** [comment]
Just select an item from the list and hit Post.  The auction is posted properly, but the selection isn't moved to the next item.  Similarly, when I hit the Skip function, nothing happens.  The keys that are bound to those functions are also not working.  This is the way it works when the program is first brought up.  It is possible that there are some set of options I have selected that is causing this problem, but looking at them I can't see anything that would cause it, except the option to move to the next item which is enabled.

**Comment by plusmouse** [comment]
I can't replicate this issue on Cataclysm classic, on retail or on era.

Both the autoselect next item and the skip buttons work as expected.

**Comment by reussered** [comment]
Are you using the same version?  I am using the one posted by Curseforge (10.2.40). Did I get the wrong version because I am reporting exactly what I am seeing?  Is there some setting that would give me this result?

**Comment by plusmouse** [comment]
I've tested with the Curseforge version - no issues. Can you try with a clean saved variables file (close WoW, delete `[WoW Directory]/_classic_/WTF/Account/[some numbers]/SavedVariables/Auctionator.lua` and reopen WoW and try again?

**Comment by reussered** [comment]
Deleting all of the saved variables worked.  I now have the basic functionality back.
