### ISSUE TITLE
Vanishing Powder not listed

### ISSUE THREAD

**Issue by reussered** [Auctionator/Auctionator#1510]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

_Please include a brief description of the bug, including what you were doing, and when it occurred._

## Steps to Reproduce

_Include the steps I would need to follow to reproduce the bug._

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by reussered** [comment]
This is a new item in this release.  There isn't a section its under.  It can be auctioned through the AH, but not through the auctionator.

**Comment by reussered** [comment]
version 10.2.40

**Comment by plusmouse** [comment]
Fixed in the latest alpha (available shortly)
