### ISSUE TITLE
Add Favorites doesn't work in 10.2.40

### ISSUE THREAD

**Issue by reussered** [Auctionator/Auctionator#1511]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

_Please include a brief description of the bug, including what you were doing, and when it occurred._

## Steps to Reproduce

_Include the steps I would need to follow to reproduce the bug._

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by reussered** [comment]
The Add Favorites function which was the old feature before Custom Group's was added doesn't work.

**Comment by reussered** [comment]
As far as I can tell, the only thing that works in this version is the Post function which does post an auction.  But even Post is also broken because it doesn't go to the next item.  This is a selling window bug.

**Comment by reussered** [comment]
I am using game version 4.4.0 (cataclysm classic)

**Comment by plusmouse** [comment]
Follow the instructions in https://github.com/Auctionator/Auctionator/issues/1509#issuecomment-2117006777

**Comment by reussered** [comment]
I deleted all of the SavedVariables files, and everything now works including Add to Favorites in the drop down menu  The Custom Groups feature still needs to be included.  When do you expect to have that back in some version.  It was working perfectly well for me and I miss it terribly.  I can't imagine that anyone was complaining about it, but I can only go by the bug reports I see.  Was there a problem with Cataclysm that prevented this feature from being included?
