### ISSUE TITLE
lua error in Constants.lua:66

### ISSUE THREAD

**Issue by fireymerlin** [Auctionator/Auctionator#1513]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

3x Auctionator/Source_Classic/Prospect/Constants.lua:66: '}' expected (to close '{' at line 1) near 'JASPER'

version:  10.2.41-1.
Error is not present in 10.2.41

**Comment by plusmouse** [comment]
Fixed in the next alpha (pending CF approval)
