### ISSUE TITLE
Search doesn't show all results

### ISSUE THREAD

**Issue by LukeSR** [Auctionator/Auctionator#1515]
Please include as much of the following information as possible to help me fix the bug:

If I search for something like 'volatile' (without ' and empty filter), I would expect to get everything that starts with volatile (e. g. volatile fire, volatile earth, volatile air etc.)
But instead I get only Volatile Life, Volatile Rum and Volatile Healing Potion and available column '?'
(I checked, the other items are available on the auction house)

If I search for 'volatile f' I get volatile fire as expected but also with the question mark under available.

![image](https://github.com/Auctionator/Auctionator/assets/52469961/bebd8f8b-6e85-45e4-b7e2-7a171dfc0e67)

![image](https://github.com/Auctionator/Auctionator/assets/52469961/b6db6541-11c1-489b-9c56-a1c3a3ddf088)

## Steps to Reproduce

Searching for something with multiple expected search results e. g. volatile. 
Standart configuration and no search filter activated.

## Loaded Addons

All Addons were deactivated, I manually removed the Auctionator Addon and reinstalled it already.
TSM is installed but was also deactivated.

**Comment by plusmouse** [comment]
Click the "Load more results" button at the bottom of the search results pane.

**Comment by LukeSR** [comment]
Damn, my fault then 😣
