### ISSUE TITLE
auctionator wanting to sell equipped items

### ISSUE THREAD

**Issue by amey1956** [Auctionator/Auctionator#1517]
Please include as much of the following information as possible to help me fix the bug:
on my bank rogue, the selling tab is listing everything she is wearing as for sale: haliscan set, antique cufflinks, gold band. i don't think this is intended behavior 

## Brief Description of Bug

_Please include a brief description of the bug, including what you were doing, and when it occurred._

## Steps to Reproduce

_Include the steps I would need to follow to reproduce the bug._

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by amey1956** [comment]
![bankroguegear2](https://github.com/Auctionator/Auctionator/assets/29166161/555f00c4-e206-4ae2-98a2-6990bae290d3)
![ahlist banker](https://github.com/Auctionator/Auctionator/assets/29166161/448055ff-3515-4006-b6c0-d6750b456c34)

**Comment by plusmouse** [comment]
Thanks for the bug report. I've pushed a fix into the next release of Auctionator, 10.2.45.
