### ISSUE TITLE
he dont run full scan

### ISSUE THREAD

**Issue by cyxallina** [Auctionator/Auctionator#1520]
Please include as much of the following information as possible to help me fix the bug:
many days now we try many ppl doing full scan but he dont work it, is cata classic

## Brief Description of Bug

_Please include a brief description of the bug, including what you were doing, and when it occurred._

## Steps to Reproduce

_Include the steps I would need to follow to reproduce the bug._

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by plusmouse** [comment]
Unfortunately due to an undocumented change Blizzard introduced with Cata full scans on busy realms can take a while. They will complete, eventually.

**Comment by cyxallina** [comment]
i doing it but i w8 24hour and no complete u mean need w8 more? srsly? i mean for no working

**Comment by plusmouse** [comment]
Try doing it with just Auctionator enabled.
