### ISSUE TITLE
Cata Classic - MoneyFrame.lua:579

### ISSUE THREAD

**Issue by evilgodly** [Auctionator/Auctionator#1522]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

Mouse over error

## Steps to Reproduce

I get this error in Cata Classic mainly when i am at the AH and mousing over items or mainly the cost of the item. I was able to disable this add-on and the error goes away. 

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

473x ...ceBlizzard_MoneyFrame/Classic/MoneyFrame.lua:579: attempt to index global 'self' (a nil value)
[string "@Blizzard_MoneyFrame/Classic/MoneyFrame.lua"]:579: in function `MoneyFrame_AccumulateAlignmentWidths'
[string "@Blizzard_GameTooltip/Classic/GameTooltip.lua"]:333: in function `SetTooltipMoney'
[string "@Blizzard_AuctionUI/Classic/Blizzard_AuctionUI.lua"]:2070: in function <...ns/Blizzard_AuctionUI/Classic/Blizzard_AuctionUI.lua:2049>
[string "@Blizzard_AuctionUI/Classic/Blizzard_AuctionUI.lua"]:2152: in function `AuctionFrameItem_OnEnter'
[string "*Blizzard_AuctionUITemplates.xml:375_OnEnter"]:2: in function <[string "*Blizzard_AuctionUITemplates.xml:375_OnEnte..."]:1>

Locals:
frameName = "GameTooltipMoneyFrame1"
widths = <table> {
}
frame = GameTooltipMoneyFrame1 {
 GoldButton = GameTooltipMoneyFrame1GoldButton {
 }
 vadjust = 0
 trialErrorButton = GameTooltipMoneyFrame1TrialErrorButton {
 }
 CopperButton = GameTooltipMoneyFrame1CopperButton {
 }
 moneyType = "AUCTION_TOOLTIP"
 0 = <userdata>
 info = <table> {
 }
 small = 1
 staticMoney = 6001
 SilverButton = GameTooltipMoneyFrame1SilverButton {
 }
 moneyWidth = 76.222225
}
info = <table> {
 showSmallerCoins = "Backpack"
 align = 1
 fixedWidth = 1
 UpdateFunc = <function> defined @Blizzard_MoneyFrame/Classic/MoneyFrame.lua:51
 collapse = 1
}
prefixFrame = GameTooltipMoneyFrame1PrefixText {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = "PrefixText"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'self' (a nil value)"

**Comment by plusmouse** [comment]
This error isn't related to Auctionator - I've had this reported before and been able to reliably replicate it without Auctionator enabled. It still happens with no addons, and is a Blizzard bug.

**Comment by evilgodly** [comment]
ah thank you for the response.
