### ISSUE TITLE
Annoying persistent LUA errors 

### ISSUE THREAD

**Issue by Ooshga** [Auctionator/Auctionator#1523]
I am unsure whether this is new, applicable to only me, or is entirely my fault. I have asked around and it appears no one has this issue from my friends group apart from me, so it maybe something my end. I wont deny that.

I repeatedly have this LUA error pop up whilst using the Auction House in Cataclysm classic. All I have to do to repeat it is simply hover over an item. Not all items do this, but a lot of them do. This particular error was popping up because I was hovering over Frostweave cloth. Strangely, it didn't do it for the bolts of frostweave, just the raw material. While it does not interfere with the addon at all, all seemingly works as intended, at least I have not noticed any breaking errors, it is very irritating and had not gone away since the start of  Cata. I have left it till now, due to me just thinking it'll go away on its own due to Cata being new. 
Its not new anymore, and I seem to be the only 1 suffering.  

Message: ...ce/AddOns/Blizzard_MoneyFrame/Classic/MoneyFrame.lua:579: attempt to index global 'self' (a nil value)
Time: Sun Jun 16 09:43:32 2024
Count: 16
Stack: ...ce/AddOns/Blizzard_MoneyFrame/Classic/MoneyFrame.lua:579: attempt to index global 'self' (a nil value)
[string "@Interface/AddOns/Blizzard_MoneyFrame/Classic/MoneyFrame.lua"]:579: in function `MoneyFrame_AccumulateAlignmentWidths'
[string "@Interface/AddOns/Blizzard_GameTooltip/Classic/GameTooltip.lua"]:333: in function `SetTooltipMoney'
[string "@Interface/AddOns/Blizzard_AuctionUI/Classic/Blizzard_AuctionUI.lua"]:2070: in function <...ns/Blizzard_AuctionUI/Classic/Blizzard_AuctionUI.lua:2049>
[string "@Interface/AddOns/Blizzard_AuctionUI/Classic/Blizzard_AuctionUI.lua"]:2121: in function <...ns/Blizzard_AuctionUI/Classic/Blizzard_AuctionUI.lua:2115>

Locals: frameName = "GameTooltipMoneyFrame1"
widths = <table> {
}
frame = GameTooltipMoneyFrame1 {
 small = 1
 GoldButton = GameTooltipMoneyFrame1GoldButton {
 }
 vadjust = 0
 trialErrorButton = GameTooltipMoneyFrame1TrialErrorButton {
 }
 CopperButton = GameTooltipMoneyFrame1CopperButton {
 }
 moneyType = "AUCTION_TOOLTIP"
 info = <table> {
 }
 0 = <userdata>
 staticMoney = 243827
 SilverButton = GameTooltipMoneyFrame1SilverButton {
 }
 moneyWidth = 113.407404
}
info = <table> {
 showSmallerCoins = "Backpack"
 align = 1
 fixedWidth = 1
 UpdateFunc = <function> defined @Interface/AddOns/Blizzard_MoneyFrame/Classic/MoneyFrame.lua:51
 collapse = 1
}
prefixFrame = GameTooltipMoneyFrame1PrefixText {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = "PrefixText"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'self' (a nil value)"

Any help on this annoying issue would be welcome. If its just me being a ignorant buffoon, I am happy to take the ego hit to get rid of it. I also apologize if this has a simple fix that was linked somewhere else and just not noticed.

**Comment by plusmouse** [comment]
This particular issue is a Blizzard bug - they made a typo in their lua code and haven't fixed it.

**Comment by Ooshga** [comment]
> This particular issue is a Blizzard bug - they made a typo in their lua code and haven't fixed it.

Small indy group..... amarite?
Ok, well..... thanks. Explains things and I'm happy it isnt exactly something my end. Curious as to why only I seem to be suffering. Unless others are and are being less whiny about it.

**Comment by plusmouse** [comment]
Well, someone reported it earlier this morning... And last month, and the month before that.

**Comment by Ooshga** [comment]
> Well, someone reported it earlier this morning... And last month, and the month before that.

Its true what they say then. Misery loves company, because now I feel a lot better. Thanks a bunch for your prompt replies. It is appreciated.
