### ISSUE TITLE
Lua error MoneyFrame.lua

### ISSUE THREAD

**Issue by weitrem** [Auctionator/Auctionator#1525]
Please include as much of the following information as possible to help me fix the bug:

463x ...ceBlizzard_MoneyFrame/Classic/MoneyFrame.lua:579: attempt to index global 'self' (a nil value)
[string "@Blizzard_MoneyFrame/Classic/MoneyFrame.lua"]:579: in function `MoneyFrame_AccumulateAlignmentWidths'
[string "@Blizzard_GameTooltip/Classic/GameTooltip.lua"]:333: in function `SetTooltipMoney'
[string "@Blizzard_AuctionUI/Classic/Blizzard_AuctionUI.lua"]:2070: in function <...ns/Blizzard_AuctionUI/Classic/Blizzard_AuctionUI.lua:2049>
[string "@Blizzard_AuctionUI/Classic/Blizzard_AuctionUI.lua"]:2152: in function `AuctionFrameItem_OnEnter'
[string "*Blizzard_AuctionUITemplates.xml:375_OnEnter"]:2: in function <[string "*Blizzard_AuctionUITemplates.xml:375_OnEnte..."]:1>

Locals:
frameName = "GameTooltipMoneyFrame1"
widths = <table> {
}
frame = GameTooltipMoneyFrame1 {
 0 = <userdata>
 small = 1
 staticMoney = 236
 trialErrorButton = GameTooltipMoneyFrame1TrialErrorButton {
 }
 moneyWidth = 74.769955
 moneyType = "AUCTION_TOOLTIP"
 info = <table> {
 }
 GoldButton = GameTooltipMoneyFrame1GoldButton {
 }
 vadjust = 0
 SilverButton = GameTooltipMoneyFrame1SilverButton {
 }
 CopperButton = GameTooltipMoneyFrame1CopperButton {
 }
}
info = <table> {
 showSmallerCoins = "Backpack"
 align = 1
 fixedWidth = 1
 UpdateFunc = <function> defined @Blizzard_MoneyFrame/Classic/MoneyFrame.lua:51
 collapse = 1
}
prefixFrame = GameTooltipMoneyFrame1PrefixText {
 0 = <userdata>
 fontStyle = "OUTLINE"
 font = "Fonts\FRIZQT__.TTF"
 fontSize = 15
}
(*temporary) = nil
(*temporary) = "PrefixText"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'self' (a nil value)"

_Please include a brief description of the bug, including what you were doing, and when it occurred._

Checking posted auctions

_Include the steps I would need to follow to reproduce the bug._

1. Post something on AH
2. Open Auctions page and mouse over the item

_Include a list of addons you were running at the time this bug occurred._

Auctionator
BugGrabber
BugSack
Simple Addon Manager

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by plusmouse** [comment]
This is a Blizzard error, and nothing to do with Auctionator. See #1522
