### ISSUE TITLE
could u please update for WLK at China Service

### ISSUE THREAD

**Issue by Anveena** [Auctionator/Auctionator#1527]
I'm sure that i had install the latest version(10.2.38-wrath) by curseforge,and i could see some options in menu,but when i open auction,there is no tags from Auctionator,so sad.

**Comment by semye** [comment]
下载老版本10.2.32可以正常使用

**Comment by AngryEagle91** [comment]
10.2.36也可以用，版本比较新点

**Comment by jyz0501** [comment]
10.2.38 测试可用

**Comment by plusmouse** [comment]
I can't access China's WLK so won't be supplying support. Your best best is to step back versions until you find one that works.

**Comment by plusmouse** [comment]
Minor update, with the latest Wrath update the APIs are in line with what I _can_ support, so v269 will support it.
