### ISSUE TITLE
MoneyFrame.lua:579 Error

### ISSUE THREAD

**Issue by evilgodly** [Auctionator/Auctionator#1528]
I am not sure if this is a Auctinator addon issue or not but i think it is. I am getting this in the Dwarf AH in SW on my 85 Frost NE DK. If not caused by this addon, any possible direction who might be the issue?

1043x ...ceBlizzard_MoneyFrame/Classic/MoneyFrame.lua:579: attempt to index global 'self' (a nil value)
[string "@Blizzard_MoneyFrame/Classic/MoneyFrame.lua"]:579: in function `MoneyFrame_AccumulateAlignmentWidths'
[string "@Blizzard_GameTooltip/Classic/GameTooltip.lua"]:333: in function `SetTooltipMoney'
[string "@Blizzard_AuctionUI/Classic/Blizzard_AuctionUI.lua"]:2070: in function <...ns/Blizzard_AuctionUI/Classic/Blizzard_AuctionUI.lua:2049>
[string "@Blizzard_AuctionUI/Classic/Blizzard_AuctionUI.lua"]:2152: in function `AuctionFrameItem_OnEnter'
[string "*Blizzard_AuctionUITemplates.xml:375_OnEnter"]:2: in function <[string "*Blizzard_AuctionUITemplates.xml:375_OnEnte..."]:1>

Locals:
frameName = "GameTooltipMoneyFrame1"
widths = <table> {
}
frame = GameTooltipMoneyFrame1 {
 GoldButton = GameTooltipMoneyFrame1GoldButton {
 }
 vadjust = 0
 trialErrorButton = GameTooltipMoneyFrame1TrialErrorButton {
 }
 CopperButton = GameTooltipMoneyFrame1CopperButton {
 }
 moneyType = "AUCTION_TOOLTIP"
 0 = <userdata>
 info = <table> {
 }
 small = 1
 staticMoney = 6001
 SilverButton = GameTooltipMoneyFrame1SilverButton {
 }
 moneyWidth = 76.222225
}
info = <table> {
 showSmallerCoins = "Backpack"
 align = 1
 fixedWidth = 1
 UpdateFunc = <function> defined @Blizzard_MoneyFrame/Classic/MoneyFrame.lua:51
 collapse = 1
}
prefixFrame = GameTooltipMoneyFrame1PrefixText {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = "PrefixText"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'self' (a nil value)"

**Comment by plusmouse** [comment]
Its a Blizzard bug, and commenting about it on the Blizzard WoW forums is pretty much the only thing you can do about it.
