### ISSUE TITLE
Relic Coffer Key

### ISSUE THREAD

**Issue by romadurr** [Auctionator/Auctionator#1535]
Please include as much of the following information as possible to help me fix the bug:

Relic Coffer Key item is not showing in Selling tab at auction house. Tried to reload, did not help. 

_Please include a brief description of the bug, including what you were doing, and when it occurred._

Need to have that item in the bag, try to sell it.

_Include the steps I would need to follow to reproduce the bug._

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by plusmouse** [comment]
I've added a fix into the latest alpha, available shortly.
