### ISSUE TITLE
[retail prepatch]

### ISSUE THREAD

**Issue by Demonbrent** [Auctionator/Auctionator#1537]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

**_1.    _Please include a brief description of the bug, including what you were doing, and when it occurred._**

## Steps to Reproduce

its crashing my whole game with a weird type of error i havent seen before but it happens within 10 seconds of opening auction vendor 100% of the time have tested with addon turned off and its fine. i saw there was an update on it recent so i just put it back on to check but still crashed my game. i have even tried removing and reinstalling the addon incase there was some kinda of weird corruption somewhere between going into prepatch but that also didnt work.

**_2.    _Include the steps I would need to follow to reproduce the bug.__**
-----------------------------------------------------------------------------------------------------------------------
## Loaded Addons
1. open auction vendor 2. move mouse into auction window 3. game crashes

## Loaded Addons
im running minimal addons currently 
bigwig, littlewig, omnicc, plater, details, bigdebuffs, click links, dbm, nameplate sct

----------------------------------------------------------------------------------------------------------------------
**_3.    _Include a list of addons you were running at the time this bug occurred.__**

## Back Trace (LUA Error Output)

all the addons above, no LUA error
![Screenshot_6](https://github.com/user-attachments/assets/2160b034-feb8-4b0f-9793-55123ecf3711)

**Comment by plusmouse** [comment]
Do you have auto scan on?

**Comment by Demonbrent** [comment]
yeah i think so come to think of it only turned that on the other day right before i started having the issue

**Comment by Demonbrent** [comment]
yep that seems to have fixed it.

**Comment by plusmouse** [comment]
If it crashes in the full scan make sure the slow full scan option in the advanced settings is disabled. 

Going to close this issue as resolved

**Comment by Demonbrent** [comment]
thank you will do
