### ISSUE TITLE
JC - Placing Auctions issue

### ISSUE THREAD

**Issue by Medysis** [Auctionator/Auctionator#1540]
Trying to sell jewel crafting items, Cata Classic ones, and the addon is not recognizing each type individually, but rather will randomly choose from the ones I have and post them at the price I put. 

Example, 

I have 5 necklaces in my bag that I would like to sell. 2x Alicite Pendant of the Bear and 2x Alicite Pendant of the Whale and 1x Alicite Pendant of the Soldier. I want to put the 2x Bear for 25g. Instead, the addon takes 2x from any of the Alicite Pendants and places them at 25g each. 

To fix this, I have to change the quantity to 1x Bear, and do it twice. This tends to be long when you have over 50 to AH.

<3 Thank you!

**Comment by plusmouse** [comment]
This is because of the Blizzard API underlying the posting multiple auctions at once.
