### ISSUE TITLE
Feature request: Support info requests by whisper

### ISSUE THREAD

**Issue by marcodifresco** [Auctionator/Auctionator#1543]
I have been out of WoW for a long time so I don't know if it has been discussed and denied before.

I remember the other mob that I used years ago (Auctioneer) had a nice feature where people can whisper you with ?[item_link] and the mod would answer them with the suggested bid/buyout price, number of times seen in the AH, and other info.

Is it possible

**Comment by plusmouse** [comment]
No plans to add this.
