### ISSUE TITLE
Reagent search broken

### ISSUE THREAD

**Issue by hollo6** [Auctionator/Auctionator#1544]
## Brief Description of Bug
Reagent search is not working, triggers the LUA error below.
Issue is present in versions 11.0.0-1 and 11.0.0-2. Working in 11.0.0.

## Steps to Reproduce
Open AH and any recipe in a profession window and click Search.

## Loaded Addons
Not relevant. Rolled back to 11.0.0 and this one is still working.

## Back Trace (LUA Error Output)

4x ...ionator/Source_Mainline/CraftingInfo/Professions.lua:38: Usage: Item:CreateFromItemLink(itemLinkString)
[string "=[C]"]: in function `error'
[string "@Blizzard_ObjectAPI/Mainline/Item.lua"]:33: in function `CreateFromItemLink'
[string "@Auctionator/Source_Mainline/CraftingInfo/Professions.lua"]:38: in function `DoTradeSkillReagentsSearch'
[string "@Auctionator/Source_Mainline/CraftingInfo/Mixins/Professions.lua"]:117: in function `SearchButtonClicked'
[string "*Professions.xml:20_OnClick"]:1: in function <[string "*Professions.xml:20_OnClick"]:1>

Locals:
(*temporary) = "Usage: Item:CreateFromItemLink(itemLinkString)"

**Comment by plusmouse** [comment]
Which recipe are you testing this on?

**Comment by plusmouse** [comment]
Nevermind that question, got it replicated now

**Comment by plusmouse** [comment]
Added a fix into the next alpha. Thanks for the bug report.
