### ISSUE TITLE
Remove item price

### ISSUE THREAD

**Issue by my92925** [Auctionator/Auctionator#1545]
**Is your feature request related to a problem? Please describe.**
when I enable vendor price, it will be duplicated with the default price

**Describe the solution you'd like**
add an option that removes the default Blizzard sell price string from the item tooltip

**Comment by LadyEclipse** [comment]
Now how do those of us who want the item price see it? Suddenly most of the items in my bag (which I just searched the AH for) say "unknown" for the item price, even though the "show price in tooltip" is selected under options.

**Comment by plusmouse** [comment]
No plans to hide the vendor price (blocked action issues)

@LadyEclipse Sorry about that. I've just pushed a fix which be available from Curseforge momentarily.

**Comment by zeenk** [comment]
@my92925 you can try this addon to hide it https://www.curseforge.com/wow/addons/remove-sell-price-ng
