### ISSUE TITLE
Auctionator locks up WoW after a scan

### ISSUE THREAD

**Issue by rodalpho** [Auctionator/Auctionator#1549]
After scanning the AH Auctionator completely locks up WoW. The only fix is to kill the process from Windows. No errors to provide as the game simply locks up hard. This just started happening, I'm pretty sure I ran a scan yesterday (in WoW 11.0.2) with no issues. 

I thought the issue was Journalator but disabling it did not help. Running the latest versions of everything, Auctionator 11.0.5. 

Edit: Confirmed, reverting to Auctionator 11.0.4 fixes the issue.

**Comment by rodalpho** [comment]
You sir are a prince amongst men!

**Comment by JayB0n3** [comment]
Here is the Swatter detailed Error message.  All 3 updates today cause a freeze or this error.  11.0.4 Classic is stable all others are causing crashes or errors.  I am rolling back for now. 
Date: 2024-08-16 12:23:03
ID: 1
Error occured in: Global
Count: 1
Message: ...terface/AddOns/Auctionator/Source/Database/Mixin.lua line 138:
   script ran too long
Debug:
   [string "@Interface/AddOns/Auctionator/Source/Database/Mixin.lua"]:138: _SetPrice()
   [string "@Interface/AddOns/Auctionator/Source/Database/Mixin.lua"]:27:
      ...terface/AddOns/Auctionator/Source/Database/Mixin.lua:18
Locals:
self = <table> {
 GetFirstPrice = <function> defined @Interface/AddOns/Auctionator/Source/Database/Mixin.lua:165
 GetMeanPrice = <function> defined @Interface/AddOns/Auctionator/Source/Database/Mixin.lua:263
 Init = <function> defined @Interface/AddOns/Auctionator/Source/Database/Mixin.lua:10
 _Get = <function> defined @Interface/AddOns/Auctionator/Source/Database/Mixin.lua:47
 GetPriceHistory = <function> defined @Interface/AddOns/Auctionator/Source/Database/Mixin.lua:213
 processor = Frame {
 }
 _Queue = <function> defined @Interface/AddOns/Auctionator/Source/Database/Mixin.lua:62
 SetPrice = <function> defined @Interface/AddOns/Auctionator/Source/Database/Mixin.lua:70
 GetPrice = <function> defined @Interface/AddOns/Auctionator/Source/Database/Mixin.lua:157
 cutoffDay = 1668
 ProcessScan = <function> defined @Interface/AddOns/Auctionator/Source/Database/Mixin.lua:177
 db = <table> {
 }
 GetPriceAge = <function> defined @Interface/AddOns/Auctionator/Source/Database/Mixin.lua:241
 _SetPrice = <function> defined @Interface/AddOns/Auctionator/Source/Database/Mixin.lua:85
 GetItemCount = <function> defined @Interface/AddOns/Auctionator/Source/Database/Mixin.lua:204
}
dbKey = "227844"
buyoutPrice = 189985
available = 42
priceData = <table> {
 a = <table> {
 }
 l = <table> {
 }
 h = <table> {
 }
 m = 189985
}
lowestLow = nil
highestLow = 189985
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1675 = 251120
 1666 = 449792
 1667 = 446364
 1668 = 399963
 1671 = 312497
 1670 = 355395
 1680 = 255078
}
(for control) = "1667"
(*temporary) = 1667
(*temporary) = 446364
(*temporary) = <table> {
 1675 = 251120
 1666 = 449792
 1667 = 446364
 1668 = 399963
 1671 = 312497
 1670 = 355395
 1680 = 255078
}
(*temporary) = "1667"
(*temporary) = "script ran too long"
LibCBOR = <table> {
 Serialize = <function> defined @Interface/AddOns/Auctionator/Libs/LibCBOR/LibCBOR.lua:545
 decode2 = <function> defined @Interface/AddOns/Auctionator/Libs/LibCBOR/LibCBOR.lua:448
 encode = <function> defined @Interface/AddOns/Auctionator/Libs/LibCBOR/LibCBOR.lua:57
 decode = <function> defined @Interface/AddOns/Auctionator/Libs/LibCBOR/LibCBOR.lua:422
 Deserialize = <function> defined @Interface/AddOns/Auctionator/Libs/LibCBOR/LibCBOR.lua:546
}
daysSinceZero = "1689"

**Comment by plusmouse** [comment]
Did you try 11.0.7?

**Comment by MrDarkflame** [comment]
On retail, with 11.0.7, still having same bug on my end.

2x Auctionator/Source/Database/Mixin.lua:131: script ran too long
[string "@Auctionator/Source/Database/Mixin.lua"]:131: in function `_SetPrice'
[string "@Auctionator/Source/Database/Mixin.lua"]:27: in function <Auctionator/Source/Database/Mixin.lua:18>

Locals:
self = <table> {
 processor = Frame {
 }
 cutoffDay = 1668
 db = <table> {
 }
}
dbKey = "24619"
buyoutPrice = 13335800
available = 1
priceData = <table> {
 a = <table> {
 }
 l = <table> {
 }
 m = 13335800
 h = <table> {
 }
}
lowestLow = nil
highestLow = 13335800
(for state) = <table> {
 1672 = 13335800
 1666 = 13335800
 1671 = 13335800
 1668 = 13335800
 1667 = 13335800
 1670 = 13335800
 1689 = 13335800
}
(for control) = "1668"
(*temporary) = 1668
(*temporary) = 13335800
(*temporary) = <table> {
 1672 = 13335800
 1666 = 13335800
 1671 = 13335800
 1668 = 13335800
 1667 = 13335800
 1670 = 13335800
 1689 = 13335800
}
(*temporary) = "1668"
(*temporary) = "script ran too long"
LibCBOR = <table> {
}
daysSinceZero = "1689"

**Comment by mootkins** [comment]
Adding onto this, here is the wow lua error i encountered with just auctionator enabled, no other addons

Message: ...terface/AddOns/Auctionator/Source/Database/Mixin.lua:132: script ran too long
Time: Fri Aug 16 11:51:48 2024
Count: 1
Stack: ...terface/AddOns/Auctionator/Source/Database/Mixin.lua:132: script ran too long
[string "@Interface/AddOns/Auctionator/Source/Database/Mixin.lua"]:132: in function `_SetPrice'
[string "@Interface/AddOns/Auctionator/Source/Database/Mixin.lua"]:27: in function <...terface/AddOns/Auctionator/Source/Database/Mixin.lua:18>

Locals: self = <table> {
 GetFirstPrice = <function> defined @Interface/AddOns/Auctionator/Source/Database/Mixin.lua:165
 GetMeanPrice = <function> defined @Interface/AddOns/Auctionator/Source/Database/Mixin.lua:263
 Init = <function> defined @Interface/AddOns/Auctionator/Source/Database/Mixin.lua:10
 _Get = <function> defined @Interface/AddOns/Auctionator/Source/Database/Mixin.lua:47
 GetPriceHistory = <function> defined @Interface/AddOns/Auctionator/Source/Database/Mixin.lua:213
 processor = Frame {
 }
 _Queue = <function> defined @Interface/AddOns/Auctionator/Source/Database/Mixin.lua:62
 SetPrice = <function> defined @Interface/AddOns/Auctionator/Source/Database/Mixin.lua:70
 GetPrice = <function> defined @Interface/AddOns/Auctionator/Source/Database/Mixin.lua:157
 cutoffDay = 1668
 ProcessScan = <function> defined @Interface/AddOns/Auctionator/Source/Database/Mixin.lua:177
 db = <table> {
 }
 GetPriceAge = <function> defined @Interface/AddOns/Auctionator/Source/Database/Mixin.lua:241
 _SetPrice = <function> defined @Interface/AddOns/Auctionator/Source/Database/Mixin.lua:85
 GetItemCount = <function> defined @Interface/AddOns/Auctionator/Source/Database/Mixin.lua:204
}
dbKey = "5634"
buyoutPrice = 4000
available = 10
priceData = <table> {
 a = <table> {
 }
 l = <table> {
 }
 m = 4000
 h = <table> {
 }
}
lowestLow = nil
highestLow = 4000
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1684 = 19000
 1665 = 8122
 1666 = 8122
 1676 = 10000
 1677 = 9400
 1682 = 10000
 1689 = 4000
 1678 = 10000
 1672 = 10000
 1675 = 10000
 1670 = 6975
 1671 = 5000
 1674 = 10000
 1673 = 10000
 1683 = 18000
}
(for control) = "1666"
day = "1666"
_ = 8122
(*temporary) = "1666"
(*temporary) = 8122
(*temporary) = "script ran too long"
LibCBOR = <table> {
 Serialize = <function> defined @Interface/AddOns/Auctionator/Libs/LibCBOR/LibCBOR.lua:545
 decode2 = <function> defined @Interface/AddOns/Auctionator/Libs/LibCBOR/LibCBOR.lua:448
 encode = <function> defined @Interface/AddOns/Auctionator/Libs/LibCBOR/LibCBOR.lua:57
 decode = <function> defined @Interface/AddOns/Auctionator/Libs/LibCBOR/LibCBOR.lua:422
 Deserialize = <function> defined @Interface/AddOns/Auctionator/Libs/LibCBOR/LibCBOR.lua:546
}
daysSinceZero = "1689"

**Comment by plusmouse** [comment]
I've finally replicated the freeze on my device and I've pushed 11.0.8 to Curseforge, but it hasn't been approved yet. 11.0.8 should completely fix the issue.
