### ISSUE TITLE
Lost entire price history and Addon refuses to save price history, i can only see the "today" price whenever i click on history.

### ISSUE THREAD

**Issue by Gramrock** [Auctionator/Auctionator#1550]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

It feels random, I suddenly lost the history for all items, i have no idea why. Whenever i click on any item it only shows me the prices for today now. I used to be able to see price history back for weeks. (I could swear that there was an option for history settings, can't find any options for it anymore though).

I noticed that History has two tabs "Realm History" and "Your History", I never had to switch to any tab, clicking on history would just show me the history for each day. If i however manually switch to "Your History" i see duplicate entries for the same day.

It used to be just clicking on "history" and see the history for each day, one entry per day (the cheapest price for that day). No duplicates. No need to click on any button such as "realm/your history.

## Steps to Reproduce

just search for an item that you searched for a lot and always checked the history for, and you suddenly only see "today"

## Loaded Addons

Blizzard_CompactRaidFrames: enabled
Questie: enabled
Leatrix_Plus: enabled
Auctionator: enabled
XPerl: enabled
ZPerl_Options: enabled
XPerl_TeamSpeak: disabled
Perl_Player_Buff: disabled
ImprovedBlizzardUI: enabled
ClassicAuraDurations: enabled
LFGBulletinBoard: disabled
PallyPower: enabled
TacoTip: enabled
TomTom: enabled
MoveAnything: disabled
Blizzard_CombatText: enabled
LayerHopper: disabled
PowerSpark: enabled
MoveAny: enabled
BasicMinimap_Options: enabled
LFG113: disabled
WeakAurasCompanion: enabled
WeakAurasArchive: enabled
BagBrother: enabled
Bagnon: enabled
Bagnon_Config: enabled
AtlasLootClassic_Options: enabled
AtlasLootClassic_Collections: enabled
AtlasLootClassic: enabled
AtlasLootClassic_Crafting: enabled
AtlasLootClassic_Data: enabled
AtlasLootClassic_DungeonsAndRaids: enabled
AtlasLootClassic_PvP: enabled
AtlasLootClassic_Factions: enabled
BuffTimers: enabled
BasicMinimap: enabled
BeanCounter: disabled
ModernTargetFrame: enabled
NugEnergy: enabled
NugRunning: enabled
NugRunningOptions: enabled
SlideBar: disabled
Disenchanter: enabled
Spy: enabled
!Swatter: enabled
Stubby: enabled
WeakAuras: enabled
WeakAurasModelPaths: enabled
WeakAurasOptions: enabled
WideQuestLogFixed: enabled
WeakAurasTemplates: enabled
ClassicClassIconPortraits: enabled
Details: enabled
Details_DataStorage: enabled
Details_Streamer: enabled
Details_TinyThreat: enabled
Enchantrix-Barker: disabled
Enchantrix: disabled
GatherMate2: enabled
GatherMate2_Data: enabled
Informant: disabled
Auc-Advanced: enabled
Auc-Filter-Basic: enabled
Auc-ScanData: enabled
Auc-Stat-Histogram: enabled
Auc-Stat-iLevel: enabled
Auc-Stat-Purchased: enabled
Auc-Stat-Simple: enabled
Auc-Stat-StdDev: enabled
Auc-Util-FixAH: enabled
Baganator: enabled
Bartender4: enabled
FloatingCombatTextFix: enabled
GlobalIgnoreList: enabled
LittleBuddha: enabled
WeaponSwingTimer: enabled
Talented_Data: disabled
Talented: disabled
DBM-Core: enabled
DBM-GUI: enabled
DBM-StatusBarTimers: enabled
DBM-VPVEM: enabled
DBM-Azeroth: enabled
DBM-Raids-Vanilla: enabled
AdvancedInterfaceOptions: enabled
BattlegroundTargets: enabled
BigDebuffs: enabled
ECDC: enabled
EquipmentSets: enabled
NovaWorldBuffs: enabled
Ranker: enabled
SSPVP: enabled
Atlas_BurningCrusade: enabled
AtlasLootClassic_Maps: enabled
Atlas_ClassicWoW: enabled
AtlasQuest: enabled
CharacterStatsClassic: enabled
Outfitter: enabled
Clique: disabled
Capping_Options: enabled
BigWigs_Core: enabled
BigWigs_Options: enabled
BigWigs_Plugins: enabled

## Back Trace (LUA Error Output)

No Lua error as far as i can tell.

**Comment by plusmouse** [comment]
The history is lost, but 11.0.7 should avoid a repeat.

**Comment by plusmouse** [comment]
The lost history will stay lost, but it should be generating a new history now.
