### ISSUE TITLE
Auction sold system message.

### ISSUE THREAD

**Issue by trebunner** [Auctionator/Auctionator#1552]
Addon no long provides amount auction sold for in system message in SoD Classic.

**Comment by plusmouse** [comment]
This is the yellow text that tells you when an auction was sold? That wasn't part of Auctionator.

**Comment by trebunner** [comment]
When I post auctions or purchase them the addon prints to my chat window. It used to also do that when an auction sold, now I only get the default blizzard message. I noticed this at the same time my price history was wiped.

**Comment by zeenk** [comment]
That print is from TSM, not Auctionator.

This is with all addons disabled except TSM
![2024-08-21_18-35-50](https://github.com/user-attachments/assets/85c8c73b-0d6f-4367-879c-d4a3db8fe18f)
