### ISSUE TITLE
Most options missing, Selling greyed-out

### ISSUE THREAD

**Issue by Zerogeist** [Auctionator/Auctionator#1554]
### What version(s) of WoW are you using?

Retail

### What version of Auctionator?

11.0.9

### What isn't working? What was supposed to happen?

Link to photo album of issue: https://imgur.com/a/jsYIPvS

Most fields are blank and can't be interacted with. Dropdowns show options but can't be selected (field remains blank after selection.)  Screenshots show Selling Tab (which does post items,) and two of the Options menus.

### Anything else?

Attempts to resolve:
Removed Auctionator from Addons, deleted all Auctionator data from WTF
Re-added Auctionator through curseforge > issue persists

**Comment by plusmouse** [comment]
Disable the ElvUI skin you are using for Auctionator.

**Comment by Zerogeist** [comment]
> Disable the ElvUI skin you are using for Auctionator.

Thank you! It was the Windtools skin.  Cheers.
