### ISSUE TITLE
Undercut scan error

### ISSUE THREAD

**Issue by madevelascom** [Auctionator/Auctionator#1555]
### What version(s) of WoW are you using?

Retail

### What version of Auctionator?

11.0.9

### What isn't working? What was supposed to happen?

Underscan shows the lua error and takes too long to do it. After it, selling items can take about 15 seconds each. 

### Are you experiencing any lua errors

Message: ...rce_Mainline/Tabs/Cancelling/Mixins/UndercutScan.lua:199: attempt to index local 'auctionInfo' (a nil value)
Time: Mon Aug 26 15:03:39 2024
Count: 1
Stack: ...rce_Mainline/Tabs/Cancelling/Mixins/UndercutScan.lua:199: attempt to index local 'auctionInfo' (a nil value)
[string "@Interface/AddOns/Auctionator/Source_Mainline/Tabs/Cancelling/Mixins/UndercutScan.lua"]:199: in function `ProcessSearchResults'
[string "@Interface/AddOns/Auctionator/Source_Mainline/Tabs/Cancelling/Mixins/UndercutScan.lua"]:171: in function `ReceiveEvent'
[string "@Interface/AddOns/Auctionator/Source/Utilities/EventBusMixin.lua"]:77: in function `Fire'
[string "@Interface/AddOns/Auctionator/Source_Mainline/AH/Mixins/SearchScan.lua"]:63: in function <...Auctionator/Source_Mainline/AH/Mixins/SearchScan.lua:36>

Locals: self = Frame {
 CancelNextButton = AuctionatorCancelUndercutButton {
 }
 undercutAuctions = <table> {
 }
 StartScanButton = Button {
 }
 scanRunning = true
 seenItemMinPrice = <table> {
 }
 seenAuctionResults = <table> {
 }
}
auctionInfo = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'auctionInfo' (a nil value)"

### Anything else?

Unrelated to this error, but making full scans can take up to 20 minutes sometimes.

**Comment by plusmouse** [comment]
Is this issue resolved now the AH has been fixed?
