### ISSUE TITLE
Incorrect Alchemy Crafting Cost

### ISSUE THREAD

**Issue by almercie** [Auctionator/Auctionator#1557]
### What version(s) of WoW are you using?

Retail

### What version of Auctionator?

11.0.9

### What isn't working? What was supposed to happen?

The formula used to calculate the crafting cost for alchemy is incorrect. Attached are screenshots of what is presented to me as well as the math broken out. 

![AH Scan](https://github.com/user-attachments/assets/d2135989-7fab-482a-be3c-a20605ecfda2)
![Phil calculation](https://github.com/user-attachments/assets/6430ffaa-c035-4102-9e1e-e636b73e2d4e)

### Are you experiencing any lua errors

No

### Anything else?

AH Sale Price  - (Crafting Cost / Min Yield) = Profit/Loss

**Comment by plusmouse** [comment]
Its using the tier 3 blessing blossom you have in your bags to calculate the crafting cost.
