### ISSUE TITLE
Searching and Scanning causes latency and crashes of WoW client.

### ISSUE THREAD

**Issue by bertiojones** [Auctionator/Auctionator#1558]
### What version(s) of WoW are you using?

Retail

### What version of Auctionator?

11.0.9 (2024-08-16)

### What isn't working? What was supposed to happen?

Scanning shouldn't lock up and crash WoW Client. Scanning for sale and scanning to buy has same effect.

### Are you experiencing any lua errors

No.

**Comment by plusmouse** [comment]
Can you try this with just Auctionator enabled?

**Comment by Smokeybear9** [comment]
I was having this same problem. I disabled all my add ons, delete and reinstalled auctionator, enabled it confirmed it was working as expected then reenabled my other add on and haven’t had complications since. Hopes this help anyone else who has run into this and the dev.

**Comment by bertiojones** [comment]
Turns out it was a bag value addon using auctionator data. Disabled addon
and profilers solved.

Please close ticket.
