### ISSUE TITLE
Level 8 battle pets are ignored by the 'Selling' tab

### ISSUE THREAD

**Issue by Actionhotdog** [Auctionator/Auctionator#1560]
### What version(s) of WoW are you using?

Retail

### What version of Auctionator?

11.0.11

### What isn't working? What was supposed to happen?

When posting items for auction using Auctionator's Selling tab, level 8 battle pets aren't found by the scan. So, if someone posts a level 8 pet at a slightly lower price, reposting auctions through the Selling tab doesn't work well.

**Comment by plusmouse** [comment]
Change your item matching settings in "Selling: All Items" to ignore pet levels.

**Comment by Actionhotdog** [comment]
Thank you! I'll try this.
