### ISSUE TITLE
Quantity multiplier for shopping lists

### ISSUE THREAD

**Issue by vicot** [Auctionator/Auctionator#1563]
### What version(s) of WoW are you using?

Retail

### What problem are you experiencing that led to you asking for this feature?

I have the temporary shopping list made through profession recipe search, and it nicely autopopulates quantity for each reagent needed by the recipe, so that when you go to buy said reagent the correct amount is filled in. However, let's say this recipe is for a potion, and I want to craft 5, 20, 100 of those, I now have to manually recalculate each amount. 

### What solution would you like?

Add a quantity multiplier to the shopping lists (regular and temporary ones) so that it will let me specify that I want each of the items inside x15 of their configured quantity

**Comment by plusmouse** [comment]
Right-click the search button to set a multiplier.

**Comment by vicot** [comment]
ooooh that's awesome, thanks! I'd never find this 😅 
I still think it'd be nice to set multipliers for the saved lists, but it is a low priority for me now that I know it's possible for recipe searches already
