### ISSUE TITLE
Black Lotus is displayed with The War Within Herbs

### ISSUE THREAD

**Issue by Rubyurek** [Auctionator/Auctionator#1565]
### What version(s) of WoW are you using?

Retail

### What version of Auctionator?

11.0.11

### What isn't working? What was supposed to happen?

![2024-09-04 20_10_22-World of Warcraft](https://github.com/user-attachments/assets/26264dc1-d831-4a3e-83ce-3179b84d85b4)
![2024-09-04 20_10_33-World of Warcraft](https://github.com/user-attachments/assets/ec3f8d0e-91f6-4dba-9730-f382f65c99f4)

### Anything else?

The "Black Lotus" is displayed, although I have set that only The War Within Herbs should be displayed. I think it could be a problem with Auctionator or with Blizzard's database. That's why I posted this to be on the safe side.

**Comment by plusmouse** [comment]
This is an issue with Blizzard's item tagging, so there's no much I can do.
