### ISSUE TITLE
Auctionator not showing up on add on list

### ISSUE THREAD

**Issue by TheTrashMan42** [Auctionator/Auctionator#1566]
### What version(s) of WoW are you using?

Classic

### What version of Auctionator?

3.4.3

### What isn't working? What was supposed to happen?

The add on does not show up in the in game add ons list. It does show up in my file directory however. I downloaded using CurseForge. I tried reinstalling, uninstalling and installing again, even clearing my cache did not work. I do not have any out of date add ons loaded. Not too sure what the issue is, any help is much appreciated.

**Comment by plusmouse** [comment]
The default build of Auctionator does not support Wotlk, not least because I'm unable to set anything against it as its inaccessible outside of China. You'll need to find an older build tagged with 3.4.3 support.
