### ISSUE TITLE
Pet price from different breed not showing up when posting

### ISSUE THREAD

**Issue by hollo6** [Auctionator/Auctionator#1567]
### What version(s) of WoW are you using?

Retail

### What version of Auctionator?

11.0.11

### What isn't working? What was supposed to happen?

When posting pets from the Selling tab, if a match is found but it is a different breed, the result is not showing up in the result window, therefore if the window is empty, I always have to make an extra, separate search (from search tab) for that item to figure out if the price that's (otherwise correctly, if a match is found) set by the addon is there because of that other breed, a remembered one, or something arbitrary.
Example:
1. Have a Corpselouse Larva H/S in player bags.
2. Have one Corpselouse Larva P/S on the AH (posted by someone else).
3. Open Selling tab, try to post own pet.
4. Price will be set to match the one that's already listed but the result window is empty.

It would be desirable to see the item that's already posted, whether or not marked as being a different breed, to at least give us a clue as to why that price was set.

### Are you experiencing any lua errors

No errors.

### Anything else?

I think this is the same thing that's happening with equippable items that have a different suffix, those won't show up in the result window either.

**Comment by plusmouse** [comment]
Try changing your item matching preferences in the settings ("Selling: All Items")

**Comment by hollo6** [comment]
Thanks for pointing this out, I never understood those options because I didn't know what "title" and "pet id" (not item id) meant or how to match them to breed and item suffix.
Turns out it wasn't the pets' breed that made them not appear in the results but their level.
