### ISSUE TITLE
Reduce spacing between tabs (Browse, Bids, Auctions, etc.) at the bottom of the Auction window moveable

### ISSUE THREAD

**Issue by aristoblis** [Auctionator/Auctionator#1570]
### What version(s) of WoW are you using?

Classic

### What problem are you experiencing that led to you asking for this feature?

Not experiencing a problem, just curious if it is possible to reduce the spacing between the tabs at the bottom of the auction window.

### What solution would you like?

I don't know if it is even possible, but I'd love to see added functionality to be able to reduce the spacing between the tabs at the bottom of the auction window.

**Comment by plusmouse** [comment]
Its technically possible, but risky from a blocked action and future breakage perspective, so it won't be done.
