### ISSUE TITLE
Inconsistent in showing tooltip price in crafting orders

### ISSUE THREAD

**Issue by wheatbread** [Auctionator/Auctionator#1572]
### What version(s) of WoW are you using?

Retail

### What version of Auctionator?

11.0.11

### What isn't working? What was supposed to happen?

When you mouse over mats in crafting orders, the price shows in the tooltip for some mats and doesn't for others.

Here is an example, with no other addon but Auctionator enabled:

![image](https://github.com/user-attachments/assets/3aedad0f-1a5f-4859-9046-478415be3db9)
![image](https://github.com/user-attachments/assets/c417e6de-c1a3-40e7-b555-c9d6ddabb666)
![image](https://github.com/user-attachments/assets/75fe3663-b1aa-4d07-b257-6cc9239f1c4f)
![image](https://github.com/user-attachments/assets/7105d3bf-9d74-4fa3-913f-c2ad502c429a)

This is after I did a fresh scan of the auction house with Auctionator. 

*Note: It's not just for unlearned recipes.  It also does it for learned recipes, as seen here:

![image](https://github.com/user-attachments/assets/b4d4e235-23c9-4c36-b291-4f28aa11fcf3)
![image](https://github.com/user-attachments/assets/208b4f5a-c870-41b2-8141-6191bdd80300)

Once I claim the work order, the price still doesn't show up.  

### Are you experiencing any lua errors

No errors

**Comment by Mazwak** [comment]
Not sure it is related, but I found that AH prices are not showed for reagents I have in my bag, bank or wb bank.

Once mailed to an alt, it showed the AH price.

**Comment by ShodanDelacroix** [comment]
It's not just crafting orders, it is the tooltip in general

Clean install of Auctionator and the only addon running.
Searching for weapons on AH
![auctionator_init_price](https://github.com/user-attachments/assets/5c559ebd-b80a-40d3-b2a1-7ba5a87d4891)

Clicking on the first item
![auctionator_actual_price](https://github.com/user-attachments/assets/b1f56979-a61e-4ed8-b858-669897f0ebf3)

**Comment by plusmouse** [comment]
This is expected behaviour as Blizzard doesn't supply enough information at the point of the tooltip showing to determine the appropriate price to show.
