### ISSUE TITLE
"Armor" section is missing  on the "Selling" tab

### ISSUE THREAD

**Issue by Dyla42** [Auctionator/Auctionator#1573]
### What version(s) of WoW are you using?

Classic

### What version of Auctionator?

11.0.11

### What isn't working? What was supposed to happen?

"Armor" section is missing on the "Selling" tab - and the items are not appearing anywhere on the selling tab, although they are in my bag.
I have several BoE items to list, yet they do not appear, nor does the "Armor" section of the selling tab appear.
I sent the items to another character and the same issue occurred.

### Are you experiencing any lua errors

I'm not getting any error notices.

**Comment by plusmouse** [comment]
Its not missing for me in classic era. Do you have the items hidden? Right-click any item in the list and click the "Unhide all" option.
