### ISSUE TITLE
Is Auctionator supposed to work the same in Cata Classic as in retail

### ISSUE THREAD

**Issue by speedweaver** [Auctionator/Auctionator#1575]
### What version(s) of WoW are you using?

Classic Era

### What version of Auctionator?

11.0.11

### What isn't working? What was supposed to happen?

Auctionator does not act the way it does in Retail on my Cata account. None of the extra tabs show up and all I get is the regular ol' auction window and options.  I loaded 11.0.11 from the Cata Classic area in Curse for Auctionator and I checked to make sure it's loaded, enabled and I even get a LUA error 

Date: 2024-09-22 18:05:16
ID: 1
Error occured in: Global
Count: 1
Message: ...ce/AddOns/Blizzard_MoneyFrame/Classic/MoneyFrame.lua line 579:
   attempt to index global 'self' (a nil value)
Debug:
   [string "@Interface/AddOns/Blizzard_MoneyFrame/Classic/MoneyFrame.lua"]:579: MoneyFrame_AccumulateAlignmentWidths()
   [string "@Interface/AddOns/Blizzard_GameTooltip/Classic/GameTooltip.lua"]:333: SetTooltipMoney()
   [string "@Interface/AddOns/Blizzard_AuctionUI/Classic/Blizzard_AuctionUI.lua"]:2070:
      ...ns/Blizzard_AuctionUI/Classic/Blizzard_AuctionUI.lua:2049
   [string "@Interface/AddOns/Blizzard_AuctionUI/Classic/Blizzard_AuctionUI.lua"]:2121:
      ...ns/Blizzard_AuctionUI/Classic/Blizzard_AuctionUI.lua:2115
Locals:
frameName = "GameTooltipMoneyFrame1"
widths = <table> {
}
frame = GameTooltipMoneyFrame1 {
 small = 1
 vadjust = 0
 trialErrorButton = GameTooltipMoneyFrame1TrialErrorButton {
 }
 CopperButton = GameTooltipMoneyFrame1CopperButton {
 }
 moneyType = "AUCTION_TOOLTIP"
 GoldButton = GameTooltipMoneyFrame1GoldButton {
 }
 info = <table> {
 }
 0 = <userdata>
 staticMoney = 148470
 SilverButton = GameTooltipMoneyFrame1SilverButton {
 }
 moneyWidth = 115.382698
}
info = <table> {
 showSmallerCoins = "Backpack"
 align = 1
 fixedWidth = 1
 UpdateFunc = <function> defined @Interface/AddOns/Blizzard_MoneyFrame/Classic/MoneyFrame.lua:51
 collapse = 1
}
prefixFrame = GameTooltipMoneyFrame1PrefixText {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = "PrefixText"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'self' (a nil value)"

AddOns:
  Swatter, v11.x.BETA.4 (TheWarWithBlizzardAPIs)
  Altoholic, v4.4.005
  Auctionator, v11.0.11
  DataStore, v2024.06.26
  DataStoreAchievements, v2024.06.27
  DataStoreAgenda, v2024.06.23
  DataStoreAuctions, v2024.06.23
  DataStoreCharacters, v2024.06.27
  DataStoreContainers, v2024.06.26
  DataStoreCrafts, v2024.06.26
  DataStoreCurrencies, v2024.06.23
  DataStoreInventory, v2024.06.23
  DataStoreMails, v2024.06.23
  DataStoreQuests, v2024.06.26
  DataStoreReputations, v2024.06.24
  DataStoreSpells, v2024.06.23
  DataStoreTalents, v2024.06.27
  DBMCore, v11.0.15
  DBMStatusBarTimers, v11.0.15
  DBMVPVEM, v68a8456
  HealBot, v4.4.0.37
  HealBotData, v
  HealBotOptions, v
  HealBotTips, v
  IncognitoResurrected, v1.0
  Informant, v11.x.BETA.4 (TheWarWithBlizzardAPIs)
  MapCoords, v0.43
  Postal, vv4.1.8
  Recount, vv4.4.0b
  SlideBar, v11.x.BETA.4 (TheWarWithBlizzardAPIs)
  Stubby, v11.x.BETA.4 (TheWarWithBlizzardAPIs)
  WeakAuras, v5.17.1
  WeakAurasArchive, v5.17.1
  BlizRuntimeLib v4.4.0.56489(US) <enUS>
  (ck=3ff)

**Comment by plusmouse** [comment]
You've filed your issue under Classic Era, but repeatedly state Cata Classic, which are you using?

**Comment by speedweaver** [comment]
Cats classic.      Sorry




Sent from my iPhone

On Sep 22, 2024, at 6:08 PM, plusmouse ***@***.***> wrote:

﻿

You've filed your issue under Classic Era, but repeatedly state Cata Classic, which are you using?

**Comment by plusmouse** [comment]
Download this file specifically. The problem _only_ happens if the website provides or the user uses the wrong file:
https://www.curseforge.com/wow/addons/auctionator/files/5680564

**Comment by speedweaver** [comment]
That kind of worked.  I now have all the tabs except the SELL tab.  Which is the coolest feature. 🙂

Is that Tab possible in Clata Classic

---------------
Mike Weaver
________________________________

**Comment by plusmouse** [comment]
Only the Selling, Shopping, Cancelling and Auctionator tabs are from Auctionator.
