### ISSUE TITLE
无法售卖，完整扫描到99%就停了

### ISSUE THREAD

**Issue by hz24645181** [Auctionator/Auctionator#1578]
### What version(s) of WoW are you using?

Retail, Classic

### What version of Auctionator?

10.2.36

### What isn't working? What was supposed to happen?

销售页面东西点上去开始拍卖按钮一直是灰色的，完整扫描到99%卡住不东了

### Are you experiencing any lua errors

无

**Comment by plusmouse** [comment]
Wait for the scan to finish.
