### ISSUE TITLE
Quantity Filter for commodities

### ISSUE THREAD

**Issue by Cenalian** [Auctionator/Auctionator#1579]
### What version(s) of WoW are you using?

Retail

### What problem are you experiencing that led to you asking for this feature?

While searching for a commodity with both a price and quantity filter, it would be nice if the search could take both into account and only show if both are met. I believe currently the quantity search is currently looking at the total number of that commodity listed, not that the amount you want is below the price you set. I'm finding commodities where if I have a price point and quantity set, and someone posts a single one cheaply, its showing up in my search results.

For instance, a filter set at 22 gold and quantity 10 shows this, which to me doesn't meet the threshold (10 of that commodity lower than 22 gold).
![image](https://github.com/user-attachments/assets/fcb3147f-8336-4c66-a752-77a6938fa69e)

### What solution would you like?

I understand that determining if a given quantity of a commodity exists below your price threshold may not be practical, having to iterate through the results set , but even allowing an option to have the quantity filter look at the stack of the lowest price and filter off that would be helpful.

**Comment by plusmouse** [comment]
There isn't a good solution to this without severely slowing down the search.
