### ISSUE TITLE
RFC - Countersniper (AKA "Bait Muncher")

### ISSUE THREAD

**Issue by Debuggernaut** [Auctionator/Auctionator#1582]
### What version(s) of WoW are you using?

Retail

### What problem are you experiencing that led to you asking for this feature?

Bots often post single stacks of items at half the market rate or less in an attempt to trick unsuspecting people into posting items for too little gold so the sniper can buy out the underpriced items and relist them

### What solution would you like?

There's a relatively straightforward solution to this: jury-rigging a script or addon to buy commodities 1 at a time, then sitting and patiently clicking the "buy one of item X" button again and again and again.  You'll snipe all of the underpriced items as they come along.

I modified my local copy of Auctionator to facilitate this by chopping out the useful safety checks, but obviously we'd need to cook up a user-friendly version that's hidden somewhere so people don't accidentally use it and bankrupt themselves.  I'm wondering if this is on the radar, and if so if you could describe the UX you'd like so I can implement it and send a pull request

![image](https://github.com/user-attachments/assets/a55d9097-acc0-4421-938a-8578945f62cf)

**Comment by plusmouse** [comment]
No plans to add any kind of sniping tools to Auctionator.
