### ISSUE TITLE
Bug buying some stuffs 

### ISSUE THREAD

**Issue by HugoBalbino** [Auctionator/Auctionator#1583]
### What version(s) of WoW are you using?

Classic

### What version of Auctionator?

11.0.12

### What isn't working? What was supposed to happen?

Buying some stuff in AH

### Are you experiencing any lua errors

9x ...Tabs/ResultsListing/Mixins/BuyAuctionsResultsRow.lua:26: attempt to index field 'rowData' (a nil value)
[string "@Auctionator/Source_Classic/Tabs/ResultsListing/Mixins/BuyAuctionsResultsRow.lua"]:26: in function <...Tabs/ResultsListing/Mixins/BuyAuctionsResultsRow.lua:25>
[string "=[C]"]: in function `Hide'
[string "@Blizzard_SharedXMLBase/Pools.lua"]:456: in function `resetFunc'
[string "@Blizzard_SharedXMLBase/Pools.lua"]:184: in function `CallReset'
[string "@Blizzard_SharedXMLBase/Pools.lua"]:88: in function `Release'
[string "@Blizzard_SharedXMLBase/Pools.lua"]:409: in function <Blizzard_SharedXMLBase/Pools.lua:406>
[string "=(tail call)"]: ?
[string "@Blizzard_SharedXMLBase/FrameFactory.lua"]:55: in function `Release'
[string "@Blizzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua"]:432: in function `Release'
[string "@Blizzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua"]:897: in function `ValidateDataRange'
[string "@Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua"]:702: in function `Update'
[string "@Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua"]:234: in function `SetScrollPercentageInternal'
...
[string "@Blizzard_SharedXMLBase/CallbackRegistry.lua"]:144: in function <...eBlizzard_SharedXMLBase/CallbackRegistry.lua:143>
[string "=[C]"]: ?
[string "@Blizzard_SharedXMLBase/CallbackRegistry.lua"]:147: in function `TriggerEvent'
[string "@Blizzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua"]:317: in function `SignalDataChangeEvent'
[string "@Blizzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua"]:297: in function `SetDataProvider'
[string "@Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua"]:637: in function `SetDataProvider'
[string "@Auctionator/Source/Components/ResultsListing/Mixins/ResultsListing.lua"]:128: in function `UpdateTable'
[string "@Auctionator/Source/Components/ResultsListing/Mixins/ResultsListing.lua"]:32: in function `onUpdate'
[string "@Auctionator/Source/Components/DataProviders/DataProvider.lua"]:207: in function `CheckForEntriesToProcess'
[string "@Auctionator/Source/Components/DataProviders/DataProvider.lua"]:26: in function <...tor/Source/Components/DataProviders/DataProvider.lua:24>

Locals:
self = Frame {
 HighlightTexture = Texture {
 }
 cells = <table> {
 }
 dataIndex = 2
 NormalTexture = Texture {
 }
 SelectedHighlight = Texture {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'rowData' (a nil value)"

**Comment by plusmouse** [comment]
This has been fixed now.
