### ISSUE TITLE
Lokal Error

### ISSUE THREAD

**Issue by Roktak** [Auctionator/Auctionator#1584]
### What version(s) of WoW are you using?

Classic

### What version of Auctionator?

11.0.12

### What isn't working? What was supposed to happen?

When i speak with the AH Man comes a LUA Error

### Are you experiencing any lua errors

16x ...eBlizzard_AuctionUI/Classic/Localization.lua:10: attempt to index global 'PriceDropdown' (a nil value)
[string "@Blizzard_AuctionUI/Classic/Localization.lua"]:10: in function `localizeFn'
[string "@Blizzard_SharedXML/Shared/LocalizationMachinery.lua"]:7: in function <.../Blizzard_SharedXML/Shared/LocalizationMachinery.lua:1>
[string "@Blizzard_SharedXML/Shared/LocalizationMachinery.lua"]:35: in function `SetupLocalization'
[string "@Blizzard_AuctionUI/Classic/Localization.lua"]:122: in main chunk
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@Blizzard_UIParent/Vanilla/UIParent.lua"]:225: in function `UIParentLoadAddOn'
[string "@Blizzard_UIParent/Vanilla/UIParent.lua"]:236: in function `AuctionFrame_LoadUI'
[string "@Blizzard_UIParent/Vanilla/UIParent.lua"]:973: in function <Blizzard_UIParent/Vanilla/UIParent.lua:494>

Locals:
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'PriceDropdown' (a nil value)"

### Anything else?

No

**Comment by plusmouse** [comment]
This isn't an Auctionator error - it comes from the Blizzard UI.
