### ISSUE TITLE
Better Tooltip Control . Shared  Popular Tradeskill Addons DB.data (API)

### ISSUE THREAD

**Issue by BodySame** [Auctionator/Auctionator#1585]
### What version(s) of WoW are you using?

Retail

### What problem are you experiencing that led to you asking for this feature?

Hi. Creating items in the game has become popular. There are a couple of wishes for development.

Many experience problems with the inability to control the information displayed in the Tooltip , not only for Auctionator. Much or little text and no control.
We need the ability to control the text displayed and the arrangement of lines in the tooltip.With custom  Auctionator Db  and / or other shared Auction based addons : Craft Sim, Skillet,TSM, Oribos
This feature was in Auctioneer and was included in the Enchantrix plugin options for reagents (setting and editing position and settings).
![Auctioneer_Tooltip_Showing_All_Active](https://github.com/user-attachments/assets/3d57d088-e215-4c28-943f-7bb9ef1de8a9)

### What solution would you like?

Hi. Creating items in the game has become popular. There are a couple of wishes for development.
1. maximum offer
1.1 Creating an API, DB.API or shared lib to obtain information or exchange between Auction based DBs (custom profit calculate based on shared addon data) CraftSim and other Auction, Crafting ,Tradeskill Addons. Look at Skillet very well made Craft UI, but with a minimum of statistics.
1.2 Create or add integration of selected information into tooltip, item tooltip, reagent tooltip.
With the ability to control position and color.
1.3 Creating simple calculated (arithmetic) variables (parameters, conditions) for using data from addonDB. As for CraftSim and Auction Addons DB. To use in Tooltip   or Filters in Main Frame You can see an example LibDogTag-3.0 a simple functional text formatting library.Coloring and Formating -without needing make not so simple realtime color formating code(functions) by user.
Optional idea use  Search filters code and new Tab for this Tooltip  or Db  feature to create Calculated Filters.

Example.
%AUCPrice / %SimPrice = %result(ColourRed, TooltipPosition)
If %AUCPrice / %SimPrice > 10 = %Result( ColourBlue,TooltipPosition)

Screenshot in PremadeGroupFilter  text field- some logic functions and and help in tooltip. Look how to.

<a href="https://ibb.co/F8dPRtk"><img src="https://i.ibb.co/F8dPRtk/2024-10-01-11-45-59.png" alt="2024-10-01-11-45-59" border="0"></a>

### Any alternatives you can think of?

2. Most simple  acceptable offer
Option 1.2 -1.3 Tooltip and simple functions or a window(filter) for displaying user-calculated values. Main frame ,tooltip. Tradeskill UI

**Comment by plusmouse** [comment]
Not going to add a more complicated tooltip UI.
