### ISSUE TITLE
Constant Moneyframe error

### ISSUE THREAD

**Issue by speedweaver** [Auctionator/Auctionator#1586]
### What version(s) of WoW are you using?

Classic Era

### What version of Auctionator?

11.0.11

### What isn't working? What was supposed to happen?

Get this pop-up error after about 3 clicks into Auctionator.  See Lua

I'm in Classic Cata.

### Are you experiencing any lua errors

Date: 2024-10-03 11:46:45
ID: 1
Error occured in: Global
Count: 1
Message: ...ce/AddOns/Blizzard_MoneyFrame/Classic/MoneyFrame.lua line 579:
   attempt to index global 'self' (a nil value)
Debug:
   [string "@Interface/AddOns/Blizzard_MoneyFrame/Classic/MoneyFrame.lua"]:579: MoneyFrame_AccumulateAlignmentWidths()
   [string "@Interface/AddOns/Blizzard_GameTooltip/Classic/GameTooltip.lua"]:333: SetTooltipMoney()
   [string "@Interface/AddOns/Blizzard_AuctionUI/Classic/Blizzard_AuctionUI.lua"]:2070:
      ...ns/Blizzard_AuctionUI/Classic/Blizzard_AuctionUI.lua:2049
   [string "@Interface/AddOns/Blizzard_AuctionUI/Classic/Blizzard_AuctionUI.lua"]:2152: AuctionFrameItem_OnEnter()
   [string "*Blizzard_AuctionUITemplates.xml:975_OnEnter"]:2:
      [string "*Blizzard_AuctionUITemplates.xml:975_OnEnte..."]:1
Locals:
frameName = "GameTooltipMoneyFrame1"
widths = <table> {
}
frame = GameTooltipMoneyFrame1 {
 GoldButton = GameTooltipMoneyFrame1GoldButton {
 }
 0 = <userdata>
 staticMoney = 19513
 trialErrorButton = GameTooltipMoneyFrame1TrialErrorButton {
 }
 moneyWidth = 106.691380
 moneyType = "AUCTION_TOOLTIP"
 info = <table> {
 }
 small = 1
 vadjust = 0
 SilverButton = GameTooltipMoneyFrame1SilverButton {
 }
 CopperButton = GameTooltipMoneyFrame1CopperButton {
 }
}
info = <table> {
 showSmallerCoins = "Backpack"
 align = 1
 fixedWidth = 1
 UpdateFunc = <function> defined @Interface/AddOns/Blizzard_MoneyFrame/Classic/MoneyFrame.lua:51
 collapse = 1
}
prefixFrame = GameTooltipMoneyFrame1PrefixText {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = "PrefixText"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'self' (a nil value)"

AddOns:
  Swatter, v11.x.BETA.4 (TheWarWithBlizzardAPIs)
  Altoholic, v4.4.005
  AnnounceInterrupts, v1.9d
  Auctionator, v11.0.11
  DataStore, v2024.06.26
  DataStoreAchievements, v2024.06.27
  DataStoreAgenda, v2024.06.23
  DataStoreAuctions, v2024.06.23
  DataStoreCharacters, v2024.06.27
  DataStoreContainers, v2024.06.26
  DataStoreCrafts, v2024.06.26
  DataStoreCurrencies, v2024.06.23
  DataStoreInventory, v2024.06.23
  DataStoreMails, v2024.06.23
  DataStoreQuests, v2024.06.26
  DataStoreReputations, v2024.06.24
  DataStoreSpells, v2024.06.23
  DataStoreTalents, v2024.06.27
  DBMCore, v11.0.15
  DBMStatusBarTimers, v11.0.15
  DBMVPVEM, v68a8456
  HealBot, v4.4.0.37
  HealBotData, v
  HealBotOptions, v
  HealBotTips, v
  IncognitoResurrected, v1.0
  Informant, v11.x.BETA.4 (TheWarWithBlizzardAPIs)
  MapCoords, v0.43
  Molinari, v110000.119-Release
  Postal, vv4.1.8
  Recount, vv4.4.0b
  SlideBar, v11.x.BETA.4 (TheWarWithBlizzardAPIs)
  Stubby, v11.x.BETA.4 (TheWarWithBlizzardAPIs)
  WeakAuras, v5.17.1
  WeakAurasArchive, v5.17.1
  BlizRuntimeLib v4.4.0.56713(US) <enUS>
  (ck=43b)

### Anything else?

No

**Comment by plusmouse** [comment]
This is a known Blizzard error in Cataclysm classic.
