### ISSUE TITLE
Feature request: default the price has increased message to the price not quantity

### ISSUE THREAD

**Issue by LanaYoobee** [Auctionator/Auctionator#1587]
### What version(s) of WoW are you using?

Retail

### What problem are you experiencing that led to you asking for this feature?

as we all know, when trying to buy mats on the auction house, occasionally, some mats are posted very cheap. you click on these and you go buy, and the error comes up saying the price has increased, asking to confirm buying at a new higher price. By the time you click cancel, and refresh, and select the remaining number of items at the cheaper price, everything's sold out. 

![image](https://github.com/user-attachments/assets/c7496c9a-9633-47ce-86c0-1a701e3385a6)

### What solution would you like?

It would be preferable that, if the selected quantity at the selected price no longer existed, that it would try to give you the remaining quantity at the selected price, rather than the selected quantity at next available price. This would mean just clicking ok to confirm with a higher chance of purchase success (rather than cancel, refresh, buy again). or have this as a toggable option.

**Comment by tobi1449** [comment]
+1
Alternatively, if this is not possible, I'd appreciate a simple option to disable this feature and let the buy fail.

**Comment by plusmouse** [comment]
This isn't possible (limitation of the Blizzard APIs)
