### ISSUE TITLE
Issues with GW2

### ISSUE THREAD

**Issue by BlastBlaster17** [Auctionator/Auctionator#1589]
Please include as much of the following information as possible to help me fix the bug:

## Are you on the retail or the classic version of WoW?
Retail
## Is this a bug or a feature request?
Bug
# Bug:
## Brief Description of Bug

I was running WoW with GW2 on the latest version, and it looked like it failed to load some pretty important stuff.

## Steps to Reproduce

Just launch the game with both addons installed and open the Auction House.

## Loaded Addons

Just GW2, BugSack/Grabber, Big/LittleWigs, and this addon.

## Back Trace (LUA Error Output)

`2x Auctionator/Source/Components/ResultsListing/Mixins/Manifest.xml:5 Error loading Auctionator/AuctionatorStringColumnHeader.lua
2x Auctionator/Source_Mainline/Tabs/ResultsListing/Mixins/Manifest.xml:3 Error loading Auctionator/SellingPostingHistoryRow.lua
2x Auctionator/Source_Mainline/Tabs/ResultsListing/Mixins/Manifest.xml:5 Error loading Auctionator/CancellingListResultsRow.lua
2x Auctionator/Source_Mainline/Tabs/ResultsListing/Templates/Manifest.xml:6 Couldn't open Auctionator/CancellingListResultsRow.xml
2x Auctionator/Source_Mainline/Tabs/ResultsListing/Templates/Manifest.xml:8 Couldn't open Auctionator/SellingPostingHistoryRow.xml
2x Button: Has bad mixin: AuctionatorStringColumnHeaderTemplateMixin
2x Auctionator/Source/Components/ResultsListing/Templates/StringHeader.xml:11 Frame Button: Unknown method OnClick in element OnClick
2x Auctionator/Source/Components/ResultsListing/Templates/StringHeader.xml:12 Frame Button: Unknown method OnMouseUp in element OnMouseUp
2x Auctionator/Source/Components/ResultsListing/Templates/StringHeader.xml:13 Frame Button: Unknown method OnEnter in element OnEnter
2x Auctionator/Source/Components/ResultsListing/Templates/StringHeader.xml:14 Frame Button: Unknown method OnLeave in element OnLeave`

**Comment by plusmouse** [comment]
Reinstall Auctionator to resolve this issue.
