### ISSUE TITLE
Issues with posting secret sauce

### ISSUE THREAD

**Issue by wheatbread** [Auctionator/Auctionator#1591]
### What version(s) of WoW are you using?

Retail

### What version of Auctionator?

11.0.12

### What isn't working? What was supposed to happen?

At the "selling" tab, when you click on Secret Sauce, the window that is supposed to show the currently listed stuff will just sit there loading forever and never load.  It seems to only  happen for Secret Sauce. 

![image](https://github.com/user-attachments/assets/d0554fe3-b035-4cf4-9b46-b990ea711671)

### Are you experiencing any lua errors

No errors

**Comment by plusmouse** [comment]
Thanks for the bug report. I've added a fix in the latest alpha (available shortly). This bug happened because Blizzard categorised the item as a profession gear item, rather than a tradeskill one.
