### ISSUE TITLE
Please add shopping list function

### ISSUE THREAD

**Issue by AsiaChampion** [Auctionator/Auctionator#1592]
**What version(s) of WoW are you using?**
Retail

**What problem are you experiencing that led to you asking for this feature?**
When doing NPC orders, you need to buy the missing materials. Why doesn't the plugin provide a shopping list to save the quantity and quality so that you can buy them easily at the auction house?

**What solution would you like?**
Provides a shopping list function that can save quantity and quality for easy purchase at the auction house

Regards

**Comment by plusmouse** [comment]
It does do that already. Track the recipe and then click the "Search" button on the objective tracker when you are at the AH.
