### ISSUE TITLE
Blacked out tabs... and more

### ISSUE THREAD

**Issue by Stankydots** [Auctionator/Auctionator#1593]
### What version(s) of WoW are you using?

Retail

### What version of Auctionator?

11.0.12

### What isn't working? What was supposed to happen?

Picture 1 - Blacked out tabs and when I click on a shopping list item there isn't anything in the search bar...
Picture 2 - Another thing I noticed on the selling tab  My items on the left in my bags are grayed out and when I click on the item, it selects it but quantity or buyout price etc... 

please help

### Are you experiencing any lua errors

No

### Anything else?

![image](https://github.com/user-attachments/assets/00a17120-8f1f-4ea4-8f43-15cf33dd4b3b)
![image](https://github.com/user-attachments/assets/5de3c76f-856d-44e5-8447-2d6cb7f07bd2)

**Comment by plusmouse** [comment]
This is due to the add-on supplying an ElvUI skin for Auctionator. Disable the skin and report the issue to the developers
