### ISSUE TITLE
Undercut Scan Not Scanning All Listings

### ISSUE THREAD

**Issue by TStevens13** [Auctionator/Auctionator#1594]
### What version(s) of WoW are you using?

Retail

### What version of Auctionator?

11.0.12

### What isn't working? What was supposed to happen?

What trying to do an undercut scan of my current listings in the 'Cancelling' tab, only 15 listings are scanned. The remaining posts continue to show as '?'. If it matters, the 'Undercut Scan' and 'Cancel Undercut' button never light up again after beginning the scan. The last item scanned was [Frostbitten Crossbow of the Feverflare] and the next is [Gem Studded Bracelets].

### Are you experiencing any lua errors

No errors display (I have disabled BugGrabber).

**Comment by plusmouse** [comment]
Do you have this option:
![image](https://github.com/user-attachments/assets/0aca7aef-1ed7-49d1-bd93-0f0771339657)
enabled?
