### ISSUE TITLE
actionator

### ISSUE THREAD

**Issue by Hose2560** [Auctionator/Auctionator#1596]
### What version(s) of WoW are you using?

Classic

### What version of Auctionator?

newest one

### What isn't working? What was supposed to happen?

** Interface\AddOns\Auctionator\AuctionatorVendor.lua:44: attempt to call method 'SetItemByID' (a nil value)
------------
VERS:3.1.5   MEM:  1031 KB   DB:532   SE:0  SL:2  DCP:<nil>  DBVERS:4
------------
REALMS: , Icecrown_Alliance (532), Blackrock [PvP only]_Horde (0), Lordaeron_Alliance (0), Icecrown_Horde (184), Onyxia_Alliance (0)
------------
STACK: SetItemByID > Atr_AddBondTypeToCache > Atr_GetBondType > Atr_STWP_AddAuctionInfo > Atr_ShowTipWithPricing > SetBagItem > ContainerFrameItemButton_OnEnter
------------
ADDONS: , AtlasLoot, Auctionator, BonusScanner, Decursive, GearScore, HealBot, QDKP2_Config, QDKP_V2, QDKP2_GUI, Skada, DBM**

**Comment by plusmouse** [comment]
This looks like its from a private server, which is unsupported.
