### ISSUE TITLE
Suggestion - Option for single stacks for small postings

### ISSUE THREAD

**Issue by Camann** [Auctionator/Auctionator#160]
## Description

This probably isn't the "correct" way to suggest a change, but I've never done much with code repositories such as GitHub. Apologies in advance.

Just started using your addon, and it is very helpful. I've been levelling a fresh character, and end up with a lot of items which are useless to me. I don't end up with many of most items, and I'd prefer to list these as single stacks. I don't want to spam, but I'm not sure how many of each item are most commonly needed by other players.

What I'm suggesting is an option to, say, default to single stacks so long as the total number of items is relatively low. I'm familiar with programming, but not WoW's Lua API, so I created a hack which just changes the default addon behavior. I'm sure someone more familiar with this WoW's API and this addon's code could make it optional easily.

So I might end up with:
5 strange dust
3 healing potions
4 mana potions
34 dark iron dust

Listing these wouldn't be really spammy to list the first three singularly, but the dark iron dust (I don't even know if anyone uses that stuff anymore, but I ended up with about that much) should default to 1 stack of 34.

## My Attempt

I tried to make as few changes as possible to create the effect I wanted. I chose 20 as my limit, but if it was tied to an option the user could change the desired cut off.

In Auctionator.lua I changed two functions:

```
function Atr_SetInitialStacking (numStacks, stackSize)
  Auctionator.Debug.Message( 'Atr_SetInitialStacking', numStacks, stackSize )
  
  if (Atr_IsTabSelected(SELL_TAB) and gSellPane.totalItems > 20) then
    gInitial_NumStacks = numStacks;
    gInitial_StackSize = stackSize;

    Atr_Batch_NumAuctions:SetText (numStacks);
    Atr_SetStackSize (stackSize);
  else
    gInitial_NumStacks = gSellPane.totalItems;
    gInitial_StackSize = 1;

    Atr_Batch_NumAuctions:SetText (gSellPane.totalItems);
    Atr_SetStackSize (1);
  end
end

function Atr_StackSize ()
  Auctionator.Debug.Message( 'Atr_StackSize' )
  
  local stackOverride;
  
  if (Atr_IsTabSelected(SELL_TAB) and gSellPane.totalItems > 20) then
    stackOverride = Atr_Batch_Stacksize:GetNumber();
  else
    stackOverride = 1;
  end
  
  return math.max(stackOverride, 1 )
end
```

**Comment by ceylina** [comment]
I am not completely sure what You are wanting to accomplish that is not already there. Take a look at the selling options in settings and how you can configure items to list per defined stacks of # of items. 

So say flasks you can set to default to 1 stack of 10 when you put them up.

I am pretty sure if I understand you correctly that is what you want but at the default instead of having to setup a selling default for specific items.

Take a look and see if it answers your request. I'll leave this open until I hear from you.

**Comment by Camann** [comment]
Yeah, I don't want to define by item type, just any old item I don't have many of. Like I said I'm levelling so I'm not getting many of any single item. By the time I get more, say, health potions, they're higher level health potions that have a different name, so defining basic health potions as single stacks is useless because I won't be listing those again.

I know potions are a defined group, but I'm not just selling potions, trade goods, whatever I find that I can't use.

**Comment by ceylina** [comment]
I will say that his may not benefit as a default addition as there is already an option to define sell characteristics and you can always base your decisions on a saved scan of current AH pricing so selling singular items automatically based on available total amounts in a player's inventory may be duplicating something that already exists to fill that need. You are always welcome to define limits based on either generic or specific item names.

That being said, I will bring this up with borjamacare and see if it something we may want to explore. We do try and avoid doubling up on features is possible.

As with any addon, you are always welcome to modify it for personal use granted you do not require assistance for modified versions of the code.

**Comment by Camann** [comment]
Yeah, sorry if it wasn't clear. I don't expect something like this to be on by default, but a selling option to default listings of any items to one. I just figure since I'm listing so few items, someone may pick up my item to fill out the number they need even if my auction isn't necessarily the lowest price.

I know if I needed 5 of something and the auctions were (prices lowest to highest) a stack of 4, a stack of 20, a stack of 1, etc. I'd probably buy the 4 stack and the single, since 24 would be way too many.

Thanks for considering it, anyway.

**Comment by ceylina** [comment]
I am going to go over to see if we can add an option to create a wildcard selling filter to basically accomplish this. No guarantee it is even possible or feasible but I will see what we can do. If it is something we would like to add, this may not be addresses until after legion is released.
