### ISSUE TITLE
Not selecting single items while buying

### ISSUE THREAD

**Issue by Silvenmyst** [Auctionator/Auctionator#1601]
### What version(s) of WoW are you using?

Retail

### What version of Auctionator?

11.0.14

### What isn't working? What was supposed to happen?

When I bring up an item after searching it displays the list of available auctions, it shows the quantity of 1 for the assumingly first cheapest item. However, two things happen if I select any other item in that list. It will automatically select the entire quantity available for that item, you choose an item further down the list and attempt to purchase ALL of the items up until the last selected item in the list. Yes, I am aware that this is not the normal route a person chooses, however, choosing the first item in the list is normal for me and I would suspect others, and having it attempt to purchase say 742 items is a bit needed lol.  I am not sure if this is intended but its not something I have noticed until this last week, to be honest. (yes, I did end up buying like 50 books of warlock glyphs that I now have to sell off...sooo...yea) Screenshot is scrubbed with ONLY Auctionator running. Would this not default to a single purchase with the the buyer having to put in a larger number in order to avoid NOT buying out whole stacks on accident? I am probably way off, but just trying to figure out if have been missing something this whole time. I have used this for years, just not sure why this has shown up now as an issue.
![multi stacks](https://github.com/user-attachments/assets/c0090c3d-725e-40d8-8b02-c4b2130a4ddb)
![Single Point](https://github.com/user-attachments/assets/606b4cd7-caad-48e8-8699-ad639c829413)

**Comment by plusmouse** [comment]
That is not the Auctionator buy UI, that's from the Blizzard part of the auction house.

Just enter 1 again in the quantity box. You don't need to click on the right to change that.
