### ISSUE TITLE
Show in Item UI Max Stack Size

### ISSUE THREAD

**Issue by HugoBalbino** [Auctionator/Auctionator#1602]
### What version(s) of WoW are you using?

Classic

### What problem are you experiencing that led to you asking for this feature?

When buying or selling or farming... show the max stack size is a good information to understand the bag slots that will be used by item.

### What solution would you like?

Show in item ui the max stack size to it.

### Any alternatives you can think of?

No

### Anything else?

N/A

**Comment by plusmouse** [comment]
No plans to add showing the max stack size in Auctionator.
