### ISSUE TITLE
SoD 1.15.5 xml errors on loading

### ISSUE THREAD

**Issue by mrbuds** [Auctionator/Auctionator#1603]
### What version(s) of WoW are you using?

Classic Era

### What version of Auctionator?

11.0.15-classic

### What isn't working? What was supposed to happen?

![image](https://github.com/user-attachments/assets/9d4d253e-98c7-45ce-89dd-6dd504b8fb08)

**Comment by plusmouse** [comment]
Thanks for the bug report. I've pushed a fix as 11.0.16 which will be available from Curseforge and Wago shortly.
