### ISSUE TITLE
Lua Warnings after 19/11/2024 update

### ISSUE THREAD

**Issue by Gokec** [Auctionator/Auctionator#1604]
### What version(s) of WoW are you using?

Classic Era

### What version of Auctionator?

11.0.15-classic

### What isn't working? What was supposed to happen?

On login, I receive the numerous Lua errors. Addons still continues to work though (haven't tested all functions).

### Are you experiencing any lua errors

1x Auctionator/Source_Classic/Components/Frames/MoneyInput.xml:15 Unrecognized XML: OnFocusGained
1x Auctionator/Source_Classic/Components/Frames/MoneyInput.xml:15 Unrecognized XML attribute: method
1x Auctionator/Source_Classic/Components/Frames/MoneyInputAlternate.xml:15 Unrecognized XML: OnFocusGained
1x Auctionator/Source_Classic/Components/Frames/MoneyInputAlternate.xml:15 Unrecognized XML attribute: method
1x Auctionator/Source_Classic/Tabs/ResultsListing/Templates/BuyAuctionsResultsRow.xml:9 Unrecognized XML: Texture
1x Auctionator/Source_Classic/Tabs/ResultsListing/Templates/BuyAuctionsResultsRow.xml:9 Unrecognized XML attribute: parentKey
1x Auctionator/Source_Classic/Tabs/ResultsListing/Templates/BuyAuctionsResultsRow.xml:9 Unrecognized XML attribute: atlas
1x Auctionator/Source_Classic/Tabs/ResultsListing/Templates/BuyAuctionsResultsRow.xml:9 Unrecognized XML attribute: alphaMode
1x Auctionator/Source_Classic/Tabs/ResultsListing/Templates/BuyAuctionsResultsRow.xml:9 Unrecognized XML attribute: hidden

**Comment by plusmouse** [comment]
Thanks for the bug report. I've pushed a fix as 11.0.16 which will be available from Curseforge and Wago shortly.
