### ISSUE TITLE
Anniversary error: attempt to index field 'rowData' (a nil value)

### ISSUE THREAD

**Issue by Bogdanov89** [Auctionator/Auctionator#1605]
### What version(s) of WoW are you using?

Classic Era

### What version of Auctionator?

11.0.16

### What isn't working? What was supposed to happen?

I was using bugsack and buggrabber to troubleshoot a different addon and i encountered the following issue when i opened the auction house on Anniversary WoW (EU PVE) to sell something.
I dont know what the error means nor what exactly broke down since Auctionator continued working properly, sorry.
Thank you for the awesome mod!

### Are you experiencing any lua errors

1x ...Tabs/ResultsListing/Mixins/BuyAuctionsResultsRow.lua:26: attempt to index field 'rowData' (a nil value)
[string "@Auctionator/Source_Classic/Tabs/ResultsListing/Mixins/BuyAuctionsResultsRow.lua"]:26: in function <...Tabs/ResultsListing/Mixins/BuyAuctionsResultsRow.lua:25>
[string "=[C]"]: in function `Hide'
[string "@Blizzard_SharedXMLBase/Pools.lua"]:456: in function `resetFunc'
[string "@Blizzard_SharedXMLBase/Pools.lua"]:184: in function `CallReset'
[string "@Blizzard_SharedXMLBase/Pools.lua"]:88: in function `Release'
[string "@Blizzard_SharedXMLBase/Pools.lua"]:409: in function <Blizzard_SharedXMLBase/Pools.lua:406>
[string "=(tail call)"]: ?
[string "@Blizzard_SharedXMLBase/FrameFactory.lua"]:55: in function `Release'
[string "@Blizzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua"]:432: in function `Release'
[string "@Blizzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua"]:897: in function `ValidateDataRange'
[string "@Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua"]:702: in function `Update'
[string "@Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua"]:234: in function `SetScrollPercentageInternal'
...
[string "@Blizzard_SharedXMLBase/CallbackRegistry.lua"]:144: in function <...eBlizzard_SharedXMLBase/CallbackRegistry.lua:143>
[string "=[C]"]: ?
[string "@Blizzard_SharedXMLBase/CallbackRegistry.lua"]:147: in function `TriggerEvent'
[string "@Blizzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua"]:317: in function `SignalDataChangeEvent'
[string "@Blizzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua"]:297: in function `SetDataProvider'
[string "@Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua"]:637: in function `SetDataProvider'
[string "@Auctionator/Source/Components/ResultsListing/Mixins/ResultsListing.lua"]:128: in function `UpdateTable'
[string "@Auctionator/Source/Components/ResultsListing/Mixins/ResultsListing.lua"]:32: in function `onUpdate'
[string "@Auctionator/Source/Components/DataProviders/DataProvider.lua"]:207: in function `CheckForEntriesToProcess'
[string "@Auctionator/Source/Components/DataProviders/DataProvider.lua"]:26: in function <...tor/Source/Components/DataProviders/DataProvider.lua:24>

Locals:
self = Frame {
 HighlightTexture = Texture {
 }
 cells = <table> {
 }
 dataIndex = 6
 NormalTexture = Texture {
 }
 SelectedHighlight = Texture {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'rowData' (a nil value)"

**Comment by Bogdanov89** [comment]
One more happened:

2x ...Tabs/ResultsListing/Mixins/BuyAuctionsResultsRow.lua:26: attempt to index field 'rowData' (a nil value)
[string "@Auctionator/Source_Classic/Tabs/ResultsListing/Mixins/BuyAuctionsResultsRow.lua"]:26: in function <...Tabs/ResultsListing/Mixins/BuyAuctionsResultsRow.lua:25>
[string "=[C]"]: in function `Hide'
[string "@Blizzard_SharedXMLBase/Pools.lua"]:456: in function `resetFunc'
[string "@Blizzard_SharedXMLBase/Pools.lua"]:184: in function `CallReset'
[string "@Blizzard_SharedXMLBase/Pools.lua"]:88: in function `Release'
[string "@Blizzard_SharedXMLBase/Pools.lua"]:409: in function <Blizzard_SharedXMLBase/Pools.lua:406>
[string "=(tail call)"]: ?
[string "@Blizzard_SharedXMLBase/FrameFactory.lua"]:55: in function `Release'
[string "@Blizzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua"]:432: in function `Release'
[string "@Blizzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua"]:897: in function `ValidateDataRange'
[string "@Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua"]:702: in function `Update'
[string "@Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua"]:234: in function `SetScrollPercentageInternal'
...
[string "@Blizzard_SharedXMLBase/CallbackRegistry.lua"]:144: in function <...eBlizzard_SharedXMLBase/CallbackRegistry.lua:143>
[string "=[C]"]: ?
[string "@Blizzard_SharedXMLBase/CallbackRegistry.lua"]:147: in function `TriggerEvent'
[string "@Blizzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua"]:317: in function `SignalDataChangeEvent'
[string "@Blizzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua"]:297: in function `SetDataProvider'
[string "@Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua"]:637: in function `SetDataProvider'
[string "@Auctionator/Source/Components/ResultsListing/Mixins/ResultsListing.lua"]:128: in function `UpdateTable'
[string "@Auctionator/Source/Components/ResultsListing/Mixins/ResultsListing.lua"]:32: in function `onUpdate'
[string "@Auctionator/Source/Components/DataProviders/DataProvider.lua"]:207: in function `CheckForEntriesToProcess'
[string "@Auctionator/Source/Components/DataProviders/DataProvider.lua"]:26: in function <...tor/Source/Components/DataProviders/DataProvider.lua:24>

Locals:
self = Frame {
 HighlightTexture = Texture {
 }
 cells = <table> {
 }
 dataIndex = 6
 NormalTexture = Texture {
 }
 SelectedHighlight = Texture {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'rowData' (a nil value)"

**Comment by Bogdanov89** [comment]
I hope some of this is useful, happened when i clicked on an item in the Selling tab:

3x ...Tabs/ResultsListing/Mixins/BuyAuctionsResultsRow.lua:26: attempt to index field 'rowData' (a nil value)
[string "@Auctionator/Source_Classic/Tabs/ResultsListing/Mixins/BuyAuctionsResultsRow.lua"]:26: in function <...Tabs/ResultsListing/Mixins/BuyAuctionsResultsRow.lua:25>
[string "=[C]"]: in function `Hide'
[string "@Blizzard_SharedXMLBase/Pools.lua"]:456: in function `resetFunc'
[string "@Blizzard_SharedXMLBase/Pools.lua"]:184: in function `CallReset'
[string "@Blizzard_SharedXMLBase/Pools.lua"]:88: in function `Release'
[string "@Blizzard_SharedXMLBase/Pools.lua"]:409: in function <Blizzard_SharedXMLBase/Pools.lua:406>
[string "=(tail call)"]: ?
[string "@Blizzard_SharedXMLBase/FrameFactory.lua"]:55: in function `Release'
[string "@Blizzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua"]:432: in function `Release'
[string "@Blizzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua"]:897: in function `ValidateDataRange'
[string "@Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua"]:702: in function `Update'
[string "@Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua"]:234: in function `SetScrollPercentageInternal'
...
[string "@Blizzard_SharedXMLBase/CallbackRegistry.lua"]:144: in function <...eBlizzard_SharedXMLBase/CallbackRegistry.lua:143>
[string "=[C]"]: ?
[string "@Blizzard_SharedXMLBase/CallbackRegistry.lua"]:147: in function `TriggerEvent'
[string "@Blizzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua"]:317: in function `SignalDataChangeEvent'
[string "@Blizzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua"]:297: in function `SetDataProvider'
[string "@Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua"]:637: in function `SetDataProvider'
[string "@Auctionator/Source/Components/ResultsListing/Mixins/ResultsListing.lua"]:128: in function `UpdateTable'
[string "@Auctionator/Source/Components/ResultsListing/Mixins/ResultsListing.lua"]:32: in function `onUpdate'
[string "@Auctionator/Source/Components/DataProviders/DataProvider.lua"]:207: in function `CheckForEntriesToProcess'
[string "@Auctionator/Source/Components/DataProviders/DataProvider.lua"]:26: in function <...tor/Source/Components/DataProviders/DataProvider.lua:24>

Locals:
self = Frame {
 HighlightTexture = Texture {
 }
 cells = <table> {
 }
 dataIndex = 6
 NormalTexture = Texture {
 }
 SelectedHighlight = Texture {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'rowData' (a nil value)"

**Comment by plusmouse** [comment]
Thanks for the bug report. I've added a fix in the latest alpha (available shortly)
