### ISSUE TITLE
Scan progress ends at 60%

### ISSUE THREAD

**Issue by AliStarr** [Auctionator/Auctionator#1606]
### What version(s) of WoW are you using?

Retail

### What version of Auctionator?

11.0.18

### What isn't working? What was supposed to happen?

When scanning the % progress label on the Auctionator tab above "Full Scan" starts at 10% then progresses to 60% and jumps to 100% instantly on scan completion.

### Are you experiencing any lua errors

None

### Anything else?

Been happening for quite a while. Since TWW launch at least.
It does seem to fully scan all items though.

**Comment by AliStarr** [comment]
[debug output.txt](https://github.com/user-attachments/files/17946050/debug.output.txt)

This is the debug output. Only could capture 100 lines

**Comment by plusmouse** [comment]
Its an artifact of trying to estimate how many items there are in the AH scan before the scan completes. The % is just a guide to indicate how many items out of those in the database have been updated and not every item is active in the AH.

**Comment by AliStarr** [comment]
Ahh OK, thank you for the explanation.
