### ISSUE TITLE
Strings untranslated

### ISSUE THREAD

**Issue by anon1231823** [Auctionator/Auctionator#1610]
### What version(s) of WoW are you using?

Classic Era

### What version of Auctionator?

11.0.18

### What isn't working? What was supposed to happen?

"Development is time consuming, consider supporting" is not translated and same with it's message 
![image](https://github.com/user-attachments/assets/61fab1fd-8c72-4ec7-a37f-c8b0943f97f7)

**Comment by plusmouse** [comment]
Added now.
