### ISSUE TITLE
full scan stoping at 99% and cant load any item via shoping tab

### ISSUE THREAD

**Issue by Orestikus** [Auctionator/Auctionator#1612]
### What version(s) of WoW are you using?

Classic Era

### What version of Auctionator?

11.0.18

### What isn't working? What was supposed to happen?

full scan stoping at 99% and cant load any item via shoping tab. Just rolling whole time, screenshot attached
![1](https://github.com/user-attachments/assets/93a05eff-b89f-4b56-97ad-6d31affc560b)

**Comment by Orestikus** [comment]
Installed BugSack and when try search some item via shoping tab it's alerted 'FATALITY'

**Comment by plusmouse** [comment]
Do you have BagAppraiser installed?

**Comment by plusmouse** [comment]
That, or disable it while doing full scans. It has a bug in its price processing code.

**Comment by Orestikus** [comment]
helped, thanks guys
