### ISSUE TITLE
Suffix removal Filter

### ISSUE THREAD

**Issue by Wyr3d** [Auctionator/Auctionator#1613]
### What version(s) of WoW are you using?

Retail, Classic Era

### What problem are you experiencing that led to you asking for this feature?

Currently Auctionator will see suffixed items as different items when posting for sale. This leads to what is virtually the same item being posted at differing values. This is fine for items that have a current ilvl value, but for old content where the priority is transmog value, this is awkward:

If the exact suffixed item does not, Auctionator acts as if there is none of the item on the Auction House. If the exact suffixed item does exist, the current value, for that item alone will show in the tab. This directly affects suggested pricing. However, if an alterative suffixed item exists, the pricing is ignored, which could be used as a suggested value in the case of the former, and may be of a much lower (or higher) value than the item on hand. 

Faced with this, one must either post each item based on it's suffixed value, or resort to switching to the default system for selling these items.

### What solution would you like?

The addition of a suffix filtering option which would merged all suffixed items into the same category would solve this problem, allowing to post the item at the best value for a quick sale. I recall some other auction addons were capable of this previously, and I assume still offer this so it should be possible to add to Auctionator without issue

### Any alternatives you can think of?

An alternative would be to allow every suffixed version of an item to show up in the selling tab. To make this simpler, the suggested price would still be taken from the direct copy version of an item as it currently works, but show alternative suffixed versions in addition, so the player can opt to adjust their pricing accordingly

### Anything else?

I believe that other auction addons I have used in the past have had such a system, so it should be able to be added as a feature for this one without too much of an issue.

**Comment by plusmouse** [comment]
There's an option in the Selling: All Items settings to ignore suffixes

**Comment by Wyr3d** [comment]
Took me a bit to figure out what you meant here, but I got it in the end. The section stating:

Choose how the item pricing is automatically selected
- same item/pet level with the same item/pet id
- same item level/pet id
- same item/pet id title and level
- same item/pet id and title (ignoring level)

The default here is the third one, so it only shows the exact item match.
The last one is basically the same, but as stated in brackets ignores the level.

The second one ignores everything.
The first is basically the same as, but will filter out ilvl. This is probably the best option for transmog, since higher ilvl stuff vends for more.

I think if the other three options had some bracketed addendum, this could help clear up any future misunderstandings. See bolded additions below as an example:

Choose how the item pricing is automatically selected
- same item/pet level with the same item/pet id **(all matching items)**
- same item level/pet id **(ignoring level)**
- same item/pet id title and level **(exact match)**
- same item/pet id and title (ignoring level)
