### ISSUE TITLE
Missing localization on a few strings

### ISSUE THREAD

**Issue by jrob8577** [Auctionator/Auctionator#164]
Some translations are not getting localized: 

``` lua
AtrL["Current"] = "Текущее" -- not working
AtrL["Default Auctionator tab"] = "Окно по умолчанию" -- not working
AtrL["Duration"] = "Время" -- not working
AtrL["History"] = "История" -- not working
AtrL["Advanced"] = "Расширенно"   -- not working
AtrL["Exact Match"] = "Точный поиск"  -- not working
```

Initially reported in https://github.com/Auctionator/Auctionator/pull/157, merging that PR to get the translations in and deferring this localization work.

**Comment by Wetxius** [comment]
You can create new global locales for text in .xml files. Example:
enUS
L_AUC_EXACT_MATCH = "Exact match"
ruRU
L_AUC_EXACT_MATCH = "Точный поиск"
And replace this line
https://github.com/Auctionator/Auctionator/blob/master/UI/Templates/Frames/Sell.xml#L150
by
<FontString inherits="GameFontNormalSmall" text="L_AUC_EXACT_MATCH">
