### ISSUE TITLE
Enhancement: Transmog sell mode (Ignore suffix)

### ISSUE THREAD

**Issue by ssateneth** [Auctionator/Auctionator#168]
Please include as much of the following information as possible to help me fix the bug:

This isn't a bug, but a request for enhancement. I'd very much like an option of a mode that acts as a sort of transmog selling mode. Basically inspect the item link of the equipment you want to sell and undercut, see if its randomly enchanted with a suffix, chop off the suffix and search for the base item (exact name for undercutting will obviously need to be turned off for this feature to work when enabled)

Right now, the current behavior is to search specifically for that item including its suffix. Often theres the same item on the auction house but with a different suffix, so it's missed from the search (if you intend to match the price with equipment of any suffix that is). Granted, The Undermine Journal addon doesn't currently store pricing per suffix and only prices the item based on its base form, so if there isnt any of that item on your local house, it falls back on the behavior intended for transmog selling.

**Comment by ceylina** [comment]
We get asked this almost daily. The answer is unfortunately not something we can or would do. Selling in auctionator involves the exact match of an item and mirrors/utilizes default functions from blizzard which do not account or allow for partial match listing of auctions.
