### ISSUE TITLE
Error on Full Scan

### ISSUE THREAD

**Issue by Comicus** [Auctionator/Auctionator#176]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug
Running a Full Scan for database

_Please include a brief description of the bug, including what you were doing, and when it occurred._

## Steps to Reproduce

_Include the steps I would need to follow to reproduce the bug._

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._

10x ...aceBlizzard_AuctionUI\Blizzard_AuctionUI.lua:733: attempt to index local 'color' (a nil value)
...aceBlizzard_AuctionUI\Blizzard_AuctionUI.lua:733: in function <...aceBlizzard_AuctionUI\Blizzard_AuctionUI.lua:669>
Altoholic\Altoholic-r167.lua:158: in function `AuctionFrameBrowse_Update'
...aceBlizzard_AuctionUI\Blizzard_AuctionUI.lua:260: in function <...aceBlizzard_AuctionUI\Blizzard_AuctionUI.lua:258>

Locals:
numBatchAuctions = 27203
totalAuctions = 27203
button = BrowseButton1 {
 0 = <userdata>
}
buttonName = "BrowseButton1"
buttonHighlight = BrowseButton1Highlight {
 0 = <userdata>
}
iconTexture = nil
itemName = BrowseButton1Name {
 0 = <userdata>
}
color = nil
itemCount = nil
moneyFrame = nil
yourBidText = nil
buyoutFrame = nil
buyoutMoney = nil
offset = 0
index = 1
isLastSlotEmpty = false
name = ""
texture = nil
count = 1
quality = -1
canUse = false
level = -1608439472
levelColHeader = nil
minBid = 4700125
minIncrement = 0
buyoutPrice = 4947500
duration = 4
bidAmount = 0
highBidder = false
bidderFullName = nil
owner = nil
ownerFullName = nil
saleStatus = 0
itemId = 2100
hasAllInfo = false
displayedPrice = nil
requiredBid = nil
(for index) = 1
(for limit) = 8
(for step) = 1
i = 1
(*temporary) = <function> defined =[C]:-1
(*temporary) = BrowseButton1Name {
 0 = <userdata>
}
(*temporary) = ""
(*temporary) = <userdata>
(*temporary) = false
(*temporary) = -1608439472
(*temporary) = nil
(*temporary) = 4700125
(*temporary) = 0
(*temporary) = 4947500
(*temporary) = 0
(*temporary) = false
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = 0
(*temporary) = 2100
(*temporary) = false
(*temporary) = "attempt to index local 'color' (a nil value)"

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by jrob8577** [comment]
This issues has been discussed on the forum and is listed in the release notes; it's a blizzard bug that they have been made aware of, and should be corrected in an upcoming patch. Your scan will proceed as normal.
