### ISSUE TITLE
Error when i log in, hover over an item, open auction house and view item on auction house

### ISSUE THREAD

**Issue by Rathaniel** [Auctionator/Auctionator#177]
[07:54:24] 23x Auc-Advanced\CoreMain.lua:280: attempt to call field 'GetModuleForName' (a nil value)
Auc-Advanced\CoreMain.lua:280: in function <Auc-Advanced\CoreMain.lua:261>
Auc-Advanced\CoreMain.lua:369: in function <Auc-Advanced\CoreMain.lua:359>
[C]: in function `LoadAddOn'
FrameXML\UIParent.lua:391: in function `UIParentLoadAddOn'
Rarity\Core.lua:3751: in function `ScanToys'
Rarity\Core.lua:3730: in function `ScanExistingItems'
Rarity\Core.lua:495: in function `DoEnable'
Rarity\Core.lua:447: in function <Rarity\Core.lua:446>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...s\AckisRecipeList\libs\AceAddon-3.0\AceAddon-3.0-12.lua:558: in function `EnableAddon'
...s\AckisRecipeList\libs\AceAddon-3.0\AceAddon-3.0-12.lua:651: in function <...s\AckisRecipeList\libs\AceAddon-3.0\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
FrameXML\UIParent.lua:391: in function `UIParentLoadAddOn'
FrameXML\UIParent.lua:482: in function `TimeManager_LoadUI'
FrameXML\UIParent.lua:993: in function <FrameXML\UIParent.lua:891>

Locals:
addon = "blizzard_collections"
auc = "blizzard_collections"
sys = nil
eng = nil
moduleLib = nil
(*temporary) = nil
(*temporary) = "blizzard_collections"
(*temporary) = "attempt to call field 'GetModuleForName' (a nil value)"
internal = <table> {
 Util = <table> {
 }
 API = <table> {
 }
}
AucAdvanced = <table> {
 Data = <table> {
 }
 selectorPriceModels = <function> defined @Auc-Advanced\CoreUtil.lua:221
 Settings = <table> {
 }
 RelVersion = "5579"
 getFrameNames = <function> defined @Auc-Advanced\CoreUtil.lua:97
 GetDistributionList = <function> defined @Auc-Advanced\CoreManifest.lua:170
 Libraries = <table> {
 }
 moduledetail = <table> {
 }
 RegisterRevision = <function> defined @Auc-Advanced\CoreManifest.lua:137
 API = <table> {
 }
 revisions = <table> {
 }
 Scan = <table> {
 }
 Config = <table> {
 }
 Buy = <table> {
 }
 GetCoreModule = <function> defined @Auc-Advanced\CoreModule.lua:53
 changeLocale = <function> defined @Auc-Advanced\CoreUtil.lua:201
 Print = <function> defined @Auc-Advanced\CoreUtil.lua:166
 Modules = <table> {
 }
 localizations = <function> defined @Auc-Advanced\CoreUtil.lua:85
 setFrame = <function> defined @Auc-Advanced\CoreUtil.lua:148
 GetCurrentRevision = <function> defined @Auc-Advanced\CoreManifest.lua:153
 Debug = <table> {
 }
 EmbeddedModules = <table> {
 }
 configFramesList = <function> defined @Auc-Advanced\CoreUtil.lua:120
 Post = <table> {
 }
 selectorAuctionLength = <function> defined @Auc-Advanced\CoreUtil.lua:244
 distribution = <table> {
 }
 ValidateInstall = <function> defined @Auc-Advanced\CoreManifest.lua:248
 MajorVersion = "5"
 Version = "5.21f.5579"
 MinorVersion = "21f"
 getFrameIndex = <function> defined @Auc-Advanced\CoreUtil.lua:131
 CoreModuleOnLoad = <function> defined @Auc-Advanced\CoreModule.lua:81
 NOPFUNCTION = <function> defined @Auc-Advanced\CoreManifest.lua:71
 GetRevisionList = <function> defined @Auc-Advanced\CoreManifest.lua:166
}
OnLoad = <function> defined @Auc-Advanced\CoreMain.lua:261

When i load auctionator addon i get spammed with: There are too many errors in your UI. As a result, your game experience may be degraded. Disable or update the failing addons if you don't want to see this message again.

**Comment by jrob8577** [comment]
@Rathaniel thanks for the report. I'm not sure what add on this is coming from, but it's not Auctionator.  The report above makes me think you have something called `Auc-Advanced` installed.  If the bug were caused by Auctionator, we would see Auctionator somewhere in the bug report (typically in one of those first lines where the files in which the bug originated are listed).

Hope this helps!

**Comment by Rathaniel** [comment]
oh sorry for that, thanks for reply tho your addon is working perfectly. I
just cant read ^^
