### ISSUE TITLE
LUA error during full scan

### ISSUE THREAD

**Issue by ddrak3** [Auctionator/Auctionator#179]
sorry for any mistakes i did here.
errors only occuring during full scan.
happens during every full scan
full scan still works, during last scan 489x the same lua error

396x ...aceBlizzard_AuctionUI\Blizzard_AuctionUI.lua:733: attempt to index local 'color' (a nil value)
...aceBlizzard_AuctionUI\Blizzard_AuctionUI.lua:733: in function `AuctionFrameBrowse_Update'
...aceBlizzard_AuctionUI\Blizzard_AuctionUI.lua:260: in function <...aceBlizzard_AuctionUI\Blizzard_AuctionUI.lua:258>

Locals:
numBatchAuctions = 114666
totalAuctions = 114666
button = BrowseButton5 {
 hover = <unnamed> {
 }
 pushed = <unnamed> {
 }
 0 = <userdata>
}
buttonName = "BrowseButton5"
buttonHighlight = <unnamed> {
 0 = <userdata>
}
iconTexture = BrowseButton4ItemIconTexture {
 0 = <userdata>
}
itemName = BrowseButton5Name {
 0 = <userdata>
}
color = nil
itemCount = BrowseButton4ItemCount {
 0 = <userdata>
}
moneyFrame = BrowseButton4MoneyFrame {
 0 = <userdata>
 vadjust = 0
 trialErrorButton = BrowseButton4MoneyFrameTrialErrorButton {
 }
 moneyType = "AUCTION"
 info = <table> {
 }
 showTooltip = true
 small = 1
 staticMoney = 980000000
 maxDisplayWidth = 146
}
yourBidText = BrowseButton4YourBidText {
 0 = <userdata>
}
buyoutFrame = BrowseButton4BuyoutFrame {
 0 = <userdata>
}
buyoutMoney = BrowseButton4BuyoutFrameMoney {
 0 = <userdata>
 vadjust = 0
 trialErrorButton = BrowseButton4BuyoutFrameMoneyTrialErrorButton {
 }
 moneyType = "AUCTION"
 info = <table> {
 }
 showTooltip = true
 small = 1
 staticMoney = 999000000
 maxDisplayWidth = 146
}
offset = 0
index = 5
isLastSlotEmpty = false
name = ""
texture = nil
count = 1
quality = -1
canUse = false
level = -1191749056
levelColHeader = nil
minBid = 645511
minIncrement = 0
buyoutPrice = 645511
duration = 1
bidAmount = 0
highBidder = false
bidderFullName = nil
owner = nil
ownerFullName = nil
saleStatus = 0
itemId = 55539
hasAllInfo = false
displayedPrice = 980000000
requiredBid = 980000000
(for index) = 5
(for limit) = 8
(for step) = 1
i = 5
(*temporary) = <function> defined =[C]:-1
(*temporary) = BrowseButton5Name {
 0 = <userdata>
}
(*temporary) = ""
(*temporary) = <userdata>
(*temporary) = false
(*temporary) = -1191749056
(*temporary) = nil
(*temporary) = 645511
(*temporary) = 0
(*temporary) = 645511
(*temporary) = 0
(*temporary) = false
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = 0
(*temporary) = 55539
(*temporary) = false
(*temporary) = "attempt to index local 'color' (a nil value)"

**Comment by ceylina** [comment]
Not an auctionator bug. Has been reported to Blizzard.
