### ISSUE TITLE
error at log in.

### ISSUE THREAD

**Issue by thefixer50** [Auctionator/Auctionator#183]
I receive the following message when logging in and when scanning the AH

The program do not seen to be effected in anyway.

Please include as much of the following information as possible to help me fix the bug:

RECEIVED AT WHEN LOGGIN IN:

##Message: Interface\AddOns\Informant\InfMain.lua:522: attempt to call global 'GetAuctionItemClasses' (a nil value)
Time: 08/19/16 14:49:07
Count: 1
Stack: Interface\AddOns\Informant\InfMain.lua:522: in main chunk
[C]: ?
[C]: in function `LoadAddOn'
[string "		local loadType = Stubby.GetConfig("Inform..."]:3: in main chunk
[C]: in function `RunScript'
Interface\AddOns\Stubby\Stubby.lua:914: in function <Interface\AddOns\Stubby\Stubby.lua:907>
Interface\AddOns\Stubby\Stubby.lua:927: in function `f'
Interface\AddOns\Stubby\Stubby.lua:738: in function `EventWatcher'
Interface\AddOns\Stubby\Stubby.lua:958: in function `Events'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

Locals: _G = <table> {
 ERR_OUT_OF_CHI = "Not enough chi"
 DH_HAVOC_CORE_ABILITY_2 = "Strong melee attack that consumes Fury. If it critical strikes, some Fury is refunded."
 MultiCastActionButton6Cooldown = MultiCastActionButton6Cooldown {
 }
 MerchantItem9ItemButtonStock = MerchantItem9ItemButtonStock {
 }
 GetTrainerServiceTypeFilter = <function> defined =[C]:-1
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Color unit names."
 Recount_MainWindow_Bar6 = Recount_MainWindow_Bar6 {
 }
 SetTrainerServiceTypeFilter = <function> defined =[C]:-1
 LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 736
 EventTraceFrameButton7HideButton = EventTraceFrameButton7HideButton {
 }
 SPELL_FAILED_CUSTOM_ERROR_71 = "This partygoer wants to dance with you."
 LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 395
 RecruitAFriendFrame = RecruitAFriendFrame {
 }
 CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture = CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture {
 }
 TutorialFrameLeft19 = TutorialFrameLeft19 {
 }
 MultiCastActionButton2Cooldown = MultiCastActionButton2Cooldown {
 }
 ERR_TRADE_EQUIPPED_BAG = "You can't trade equipped bags."
 PVP_RANK_6_1 = "Corporal"
 BOOKTYPE_PROFESSION = "professions"
 AudioOptionsVoicePanelOutputDeviceDropDownButtonHighlightTexture = AudioOptionsVoicePanelOutputDeviceDropDownButtonHighlightTexture {
 }
 VideoOptionsFrameCategoryFrameButton17ToggleHighlightTexture = VideoOptionsFrameCategoryFrameButton17ToggleHighlightTexture {
 }
 MerchantItem2AltCurrencyFrameItem1Text = MerchantItem2AltCurrencyFrameItem1Text {
 }
 OPTION_TOOLTIP_ACTION_BUTTON_USE_KEY_DOWN = "Action button keybinds will respond on key down, rather than on key up."
 BINDING_NAME_NAMEPLATES = "Show Enemy Name Plates"
 CHAT_HEADER_SUFFIX = ": "
 IsReferAFriendLinked = <function> defined =[C]:-1
 MAIL_LETTER_TOOLTIP = "Click to make a permanent
copy of this letter."
 AudioOptionsVoicePanelMicrophoneVolumeThumb = AudioOptionsVoicePanelMicrophoneVolumeThumb {
 }
 PaperDollTitlesPaneButton12BgTop = PaperDollTitlesPaneButton12BgTop {
 }
 DUNGEON_FLOOR_UPPERBLACKROCKSPIRE3 = "Hall of Blackhand"
 CHAT_CONFIG_OTHER_COMBAT = <table> {
 }
 FCFDockOverflowButton_OnClick = <function> defined @Interface\FrameXML\FloatingChatFrame.lua:2337
 TutorialFrameRight19 = TutorialFrameRight19 {
 }
 ChatFrame6EditBoxFocusMid = ChatFrame6EditBoxFocusMid {
 }
 BN_UNABLE_TO_RESOLVE_NAME = "Unable to whisper '%s'. Battle.net may be unavailable."
 LE_GAME_ERR_RECRUIT_A_FRIEND_FAILED = 941
 CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight = CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight {
 }
 LFGTeleport = <function> defined =[C]:-1
 LE_GAME_ERR_ONLY_ONE_QUIVER = 32
 SpellButton6Cooldown = SpellButton6Cooldown {
 }
 SLASH_LibQTip1 = "/qtip"
 ToggleEncounterJournal = <function> defined @Interface\FrameXML\UIParent.lua:788
 PetTrackerSwapInsetBg = PetTrackerSwapInsetBg {
 }
 LOSS_OF_CONTROL_DISPLAY_FEAR = "Feared"
 Graphics_QualityText = Graphics_QualityText {
 }
 TalentMicroButtonAlertShadowTopLeft = TalentMicroButtonAlertShadowTopLeft {
 }
 ROGUE_COMBAT_CORE_ABILITY_4 = "Melee ability with an increased range that consumes Combo Points."
 JoinSkirmish = <function> defined =[C]:-1
 Advanced_GraphicsAPIDropDownButtonHighlightTexture = Advanced_Graphics 

RECEIVED WHEN SCANNING AH: 

Message: ...ace\AddOns\Blizzard_AuctionUI\Blizzard_AuctionUI.lua:733: attempt to index local 'color' (a nil value)
Time: 08/19/16 14:58:22
Count: 104
Stack: ...ace\AddOns\Blizzard_AuctionUI\Blizzard_AuctionUI.lua:733: in function `AuctionFrameBrowse_Update'
...ace\AddOns\Blizzard_AuctionUI\Blizzard_AuctionUI.lua:260: in function <...ace\AddOns\Blizzard_AuctionUI\Blizzard_AuctionUI.lua:258>

Locals: numBatchAuctions = 52306
totalAuctions = 52306
button = BrowseButton8 {
 0 = <userdata>
 itemCount = 1
 buyoutPrice = 2237500
 bidAmount = 2125625
}
buttonName = "BrowseButton8"
buttonHighlight = BrowseButton8Highlight {
 0 = <userdata>
}
iconTexture = BrowseButton7ItemIconTexture {
 0 = <userdata>
}
itemName = BrowseButton8Name {
 0 = <userdata>
}
color = nil
itemCount = BrowseButton7ItemCount {
 0 = <userdata>
}
moneyFrame = BrowseButton7MoneyFrame {
 0 = <userdata>
 colorblind = true
 trialErrorButton = BrowseButton7MoneyFrameTrialErrorButton {
 }
 moneyType = "AUCTION"
 info = <table> {
 }
 staticMoney = 2125625
 small = 1
 vadjust = 0
 maxDisplayWidth = 146
}
yourBidText = BrowseButton7YourBidText {
 0 = <userdata>
}
buyoutFrame = BrowseButton7BuyoutFrame {
 0 = <userdata>
}
buyoutMoney = BrowseButton7BuyoutFrameMoney {
 0 = <userdata>
 colorblind = true
 trialErrorButton = BrowseButton7BuyoutFrameMoneyTrialErrorButton {
 }
 moneyType = "AUCTION"
 info = <table> {
 }
 staticMoney = 2237500
 small = 1
 vadjust = 0
 maxDisplayWidth = 146
}
offset = 0
index = 8
isLastSlotEmpty = true
name = ""
texture = nil
count = 1
quality = -1
canUse = false
level = 432429296
levelColHeader = nil
minBid = 2030625
minIncrement = 0
buyoutPrice = 2137500
duration = 1
bidAmount = 0
highBidder = false
bidderFullName = nil
owner = "Noideak"
ownerFullName = "Noideak-Daggerspine"
saleStatus = 0
itemId = 9773
hasAllInfo = false
displayedPrice = 2125625
requiredBid = 2125625
(for index) = 8
(for limit) = 8
(for step) = 1
i = 8
(*temporary) = <function> defined =[C]:-1
(*temporary) = BrowseButton8Name {
 0 = <userdata>
}
(*temporary) = ""
(*temporary) = <userdata>
(*temporary) = false
(*temporary) = 432429296
(*temporary) = nil
(*temporary) = 2030625
(*temporary) = 0
(*temporary) = 2137500
(*temporary) = 0
(*temporary) = false
(*temporary) = nil
(*temporary) = "Noideak"
(*temporary) = "Noideak-Daggerspine"
(*temporary) = 0
(*temporary) = 9773
(*temporary) = false
(*temporary) = "attempt to index local 'color' (a nil value)"

**Comment by ceylina** [comment]
Interface\AddOns\Informant\InfMain.lua:522

that is a module with Auctioneer, not Auction**ATOR**. Try posting it on their site but I do beleive you have an out of date version of aucitoneer. 

You can find the latest here

https://mods.curse.com/addons/wow/auctioneer

**Comment by thefixer50** [comment]
I do not have auctioneer installed.  It is not in the addon list in WOW and
there is know folder for it under interface/addons

**Comment by ceylina** [comment]
Interface\AddOns\**Informant**\InfMain.lua:522

that is a component of auctioneer, not auctionator.

http://wiki.norganna.org/Informant
