### ISSUE TITLE
vanity pets "recaged" for sale don't always appear.

### ISSUE THREAD

**Issue by flatlndr** [Auctionator/Auctionator#184]
Please include as much of the following information as possible to help me fix the bug:
## If you are reselling vanity pets they don't always show in the interface as multiples.

debug mode does not show them as having an ID

_Please include a brief description of the bug, including what you were doing, and when it occurred._
## Loaded Addons

AckisRecipeList
AckisRecipeList_Blacksmithing
AckisRecipeList_Cooking
AckisRecipeList_Leatherworking
Altoholic
Altoholic_Achievements
Altoholic_Agenda
Altoholic_Characters
Altoholic_Grids
Altoholic_Guild
Altoholic_Search
Altoholic_Summary
Auctionator
BittensSpellFlash_Rogue
BrokerPets
Broker_Everything
ChocolateBar
ChocolateBar_Options
DBM-AQ20
DBM-AQ40
DBM-BWL
DBM-BaradinHold
DBM-BastionTwilight
DBM-BlackTemple
DBM-BlackrockFoundry
DBM-BlackwingDescent
DBM-Brawlers
DBM-BrokenIsles
DBM-ChamberOfAspects
DBM-Coliseum
DBM-Core
DBM-DMF
DBM-DefaultSkin
DBM-Draenor
DBM-DragonSoul
DBM-EmeraldNightmare
DBM-EyeOfEternity
DBM-Firelands
DBM-GUI
DBM-GarrisonInvasions
DBM-HeartofFear
DBM-HellfireCitadel
DBM-Highmaul
DBM-Hyjal
DBM-Icecrown
DBM-Karazhan
DBM-MC
DBM-MogushanVaults
DBM-Naxx
DBM-Nighthold
DBM-Onyxia
DBM-Outlands
DBM-Pandaria
DBM-Party-BC
DBM-Party-Cataclysm
DBM-Party-Classic
DBM-Party-Legion
DBM-Party-MoP
DBM-Party-WoD
DBM-Party-WotLK
DBM-PvP
DBM-Scenario-MoP
DBM-Serpentshrine
DBM-SiegeOfOrgrimmarV2
DBM-StatusBarTimers
DBM-Sunwell
DBM-TerraceofEndlessSpring
DBM-TheEye
DBM-ThroneFourWinds
DBM-ThroneofThunder
DBM-Ulduar
DBM-VoA
DBM-WorldEvents
DataStore
DataStore_Achievements
DataStore_Agenda
DataStore_Auctions
DataStore_Characters
DataStore_Containers
DataStore_Crafts
DataStore_Currencies
DataStore_Garrisons
DataStore_Inventory
DataStore_Mails
DataStore_Pets
DataStore_Quests
DataStore_Reputations
DataStore_Spells
DataStore_Stats
DataStore_Talents
GoGoMount
GuildGreet
IceHUD
IceHUD_Options
Informant
IskarAssist
MasterPlan
MasterPlanA
MountFarmHelper
Postal
Recount
SlideBar
SpellFlash
SpellFlashCore
Storyline
Stubby
TidyPlates
TidyPlatesHub
TidyPlatesWidgets
TidyPlates_ClassicPlates
TidyPlates_Graphite
TidyPlates_Grey
TidyPlates_Neon
TidyPlates_Quatre
_Include a list of addons you were running at the time this bug occurred._
## Back Trace (LUA Error Output)

Not really a Bug, the addon does not crash.  More of a missed feature?
_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by ceylina** [comment]
This would require coding or a dedicated library to differentiate between caged pets and wild caught / non caged but BOE sellable pets. While they have the same name, the coding from Blizzard does not easily lead to differentiating the IDs between the two.

this has been a debate for a long time and may need to be something that is brought up in future builds as nothing has been usefully added in 7.0 to simplify pet identification.

Marking s enhancement request
