### ISSUE TITLE
Buy tab - buys the wrong items

### ISSUE THREAD

**Issue by Uncant** [Auctionator/Auctionator#185]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

Was searching for "Skull of War" there were multiple 640s listed at the same b/o price as the one 670.  I tried to buy the 670, yet it bought 640s, twice! (you lost about 8K worth of gold for me)  I had to go the the default interface to buy the 670.  

## Steps to Reproduce

_Include the steps I would need to follow to reproduce the bug._

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by ceylina** [comment]
Fixed with #200 fix
