### ISSUE TITLE
Same items get shown multiple times within the buy tab

### ISSUE THREAD

**Issue by Melethrion** [Auctionator/Auctionator#188]
Hey there,

whenever I use the buy tab to scan for items with a common part of their names, some of them get shown multiple times, although having the _exact_ same name in total. This is really confusing and wasn't the case pre patch at all. I'm using the german client. Here's a screenshot that shows what I mean:

http://www.bilder-upload.eu/upload/cbf1c4-1471958191.jpg

![my issue](https://cloud.githubusercontent.com/assets/21197654/17893194/14d681de-6945-11e6-8347-8f246efcc148.jpg)

As you can see there, I searched for "gabe de" to get all the enchantments shown which contain "gabe de" within their names (the greater ones...) and get some of them shown twice (here, "Ring - **Gabe de**r Meisterschaft").

As said above, this shouldn't be and I don't know why this occurs.. maybe, because of the price range? Yet, I couldn't find an option to set this behavior off; a complete reinstallation of the addon (incl. deletion of settings etc.) didn't help either.

Any help would be much appreciated! :)

Edit: here's another one that shows it maybe a bit better:

![my issue2](https://cloud.githubusercontent.com/assets/21197654/17893388/cf6f710e-6945-11e6-8a9a-ae3357a5c753.jpg)

Thanks in advance!

My AddOns:
  Swatter, v7.0.5664 (TasmanianThylacine)
  NPCScan, v7.0.3.7
  NPCScanOverlay, v7.0.3.4
  AskMrRobot, v39
  AtlasLoot, vv8.01.00
  AucAdvanced, v7.0.5664 (TasmanianThylacine)
  AucDb, v5.1.DEV.3583
  AucFilterBasic, v7.0.5664 (TasmanianThylacine)
  AucFilterOutlier, v7.0.5664.5459(7.0/embedded)
  AucMatchUndercut, v7.0.5664.5585(7.0/embedded)
  AucStatDebug, v<%version%> (<%codename%>)
  AucStatHistogram, v7.0.5664 (TasmanianThylacine)
  AucStatiLevel, v7.0.5664 (TasmanianThylacine)
  AucStatPurchased, v7.0.5664 (TasmanianThylacine)
  AucStatSales, v7.0.5664.5598(7.0/embedded)
  AucStatSimple, v7.0.5664 (TasmanianThylacine)
  AucStatStdDev, v7.0.5664 (TasmanianThylacine)
  AucStatWOWEcon, v7.0.5664.5613(7.0/embedded)
  AucUtilAHWindowControl, v7.0.5664.5575(7.0/embedded)
  AucUtilAppraiser, v7.0.5664.5653(7.0/embedded)
  AucUtilAskPrice, v7.0.5664.5599(7.0/embedded)
  AucUtilAutoMagic, v7.0.5664.5587(7.0/embedded)
  AucUtilCompactUI, v7.0.5664.5629(7.0/embedded)
  AucUtilEasyBuyout, v7.0.5664.5576(7.0/embedded)
  AucUtilFixAH, v7.0.5664 (TasmanianThylacine)
  AucUtilGlypherPost, v<%version%> (<%codename%>)
  AucUtilItemSuggest, v7.0.5664.5651(7.0/embedded)
  AucUtilPriceLevel, v7.0.5664.5633(7.0/embedded)
  AucUtilScanButton, v7.0.5664.5631(7.0/embedded)
  AucUtilScanFinish, v7.0.5664.5588(7.0/embedded)
  AucUtilScanProgress, v7.0.5664.4979(7.0/embedded)
  AucUtilScanStart, v7.0.5664.5347(7.0/embedded)
  AucUtilSearchUI, v7.0.5664.5657(7.0/embedded)
  AucUtilSimpleAuction, v7.0.5664.5654(7.0/embedded)
  AucUtilVendMarkup, v7.0.5664.4828(7.0/embedded)
  Auctionator, v4.0.9
  AutoCombatLogger, v7.0.1
  Babylonian, v5.1.DEV.332(/embedded)
  Bagnon, v7.0.4
  Bartender4, v4.7.2-1-g46f93da
  BeanCounter, v7.0.5664 (TasmanianThylacine)
  BestInSlot, vRelease 7.0.13
  BestInSlotLegion, vRelease 7.0.13
  Configator, v5.1.DEV.406(/embedded)
  DBMCore, v
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  Details, v
  DetailsCalcLeech, v
  DetailsDmgRank, v
  DetailsDpsTuning, v
  DetailsDungeonInfoWarlords, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsRaidInfoHellfireCitadel, v
  DetailsStreamer, v
  DetailsTimeAttack, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  ElkBuffBars, v2.5.1-189
  ExRT, v3750
  FlashTaskBar, v
  HandyNotes, vv1.4.8
  HandyNotesDraenorTreasures, v1.20
  HandyNotesLegionRaresTreasures, v0.7
  HealersHaveToDie, v2.4.2
  IskarAssist, v
  JSMD, vv2.3
  kgPanels, vr438
  LibExtraTip, v5.12.DEV.409(/embedded)
  LibSharedMedia30, v3.0-95
  MasterPlanA, vA
  MogIt, v3.6.3
  MoveAnything, v16.0.7
  oRA3, v1018
  Paste, v1.4.9
  Pawn, v2.0.7
  PitBull4, vv4.0.3-15-g909bf83
  PitBull4AltPowerBar, vv4.0.3-15-g909bf83
  Postal, vv3.5.8
  Prat30, v3.6.14      
  Prat30Libraries, v
  RaidBuffStatus, v6.2.4
  RCLootCouncil, v2.0.2
  SexyMap, v2.4.29
  Stubby, v7.0.5664 (TasmanianThylacine)
  teksLoot, v5.1.0.12
  TidyPlates, v6.18.Beta20
  TidyPlatesBlizzardPlates, v
  TidyPlatesGraphite, v
  TidyPlatesGrey, v
  TidyPlatesNeon, v
  TidyPlatesQuatre, v
  TidyPlatesHub, v
  TidyPlatesWidgets, v
  TipHelper, v5.12.DEV.405(/embedded)
  TipTac, v16.07.23
  TipTacItemRef, v16.07.23
  TipTacTalents, v16.07.21
  TomTom, vv70000-1.1.0
  WeakAuras, v2.2.1.1-4-g84c92bf
  BlizRuntimeLib_deDE v7.0.3.70000 <none>
  (ck=cec)

**Comment by ceylina** [comment]
due to removal of secondary stats like multistrike and spirit, many draenor enchants now have duplicates because of the way those secondary stats have been replaced. This is a known side effect and not something that can be or will be filtered out as it is a temporary issue and these enchants will no longer be relevant in a week.

**Comment by ceylina** [comment]
Also, Auctionator groups by price so you will often return same names so if the above statement does not apply, it is a price grouping
