### ISSUE TITLE
Latest version announcing new version available

### ISSUE THREAD

**Issue by ceylina** [Auctionator/Auctionator#190]
As of 4.0.10 the addon is announcing a new version is available even if a new version just was released. 

Need to clarify /remove nag code?

**Comment by d4t4king** [comment]
Confirmed.  I get a nag telling me 4.0.9 is available as a new version, while I currently have 4.0.10 installed.  Version self-check seems broken.

**Comment by jrob8577** [comment]
Thanks for the confirmation; this code is removed in the 4.0.11 build in progress.

**Comment by Stanzilla** [comment]
@jrob8577 is that committed somewhere yet?

**Comment by jrob8577** [comment]
@Stanzilla It's not, but I'm working on the 4.0.11 release now to include this fix, along with a few localization additions that have been sent my way.  Should be coming in a few hours after we make sure I didn't break anything with these trivial edits.  😄
