### ISSUE TITLE
Getting a string of text in chat from Auctionator

### ISSUE THREAD

**Issue by Jiimmothy** [Auctionator/Auctionator#198]
Keep getting a string of text when opening the game or going to change something in the basic options

such as https://i.imgur.com/qeiiYu4.png

**Comment by jrob8577** [comment]
@Jiimmothy It looks like the debug option is turned on.  Please go to Interface > Addons > Auctionator > Basic Options and ensure the "Enable Debug Mode" is not selected.  If it is unchecked, check and uncheck it (there might be a bug with this somehow getting set unintentionally).  

Please let me know if that works.

**Comment by Jiimmothy** [comment]
Thank you very much sorry for being a pain I am new to the add-on 

 

Kind regards


James

**Comment by jrob8577** [comment]
@Jiimmothy My pleasure, glad it was an easy fix! Welcome to Auctionator.  :P
