### ISSUE TITLE
Weird thing going on..... 

### ISSUE THREAD

**Issue by als30334** [Auctionator/Auctionator#199]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

_Please include a brief description of the bug, including what you were doing, and when it occurred._

## Steps to Reproduce

_Include the steps I would need to follow to reproduce the bug._

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

it's not s bug per say but I can't figure out why it's doing this. I'll attach screenshots below

 
![wowscrnshot_090116_185850](https://cloud.githubusercontent.com/assets/1158919/18188363/30d191ce-7077-11e6-9d32-14afc841c987.jpg)

![wowscrnshot_090116_190039](https://cloud.githubusercontent.com/assets/1158919/18188369/374d3508-7077-11e6-80a8-f41b84a71b37.jpg)

![wowscrnshot_090116_190146](https://cloud.githubusercontent.com/assets/1158919/18188374/3e854f5e-7077-11e6-8ba9-eeecf0211a84.jpg)

**Comment by als30334** [comment]
nvm I just realized it's https://mods.curse.com/addons/wow/auctionator-minifeatures doing that. It's not been updated in a year +

**Comment by jrob8577** [comment]
This is actually the Debug setting turned on in Auctionator.  😄 Go to Interface > Addons > Auctionator > Basic Options panel, and verify that Debug is turned off (not checked).

**Comment by als30334** [comment]
i figured it was the debug thing. i don't know how it got turned on lol

**Comment by als30334** [comment]
It's not on. I checked. Once i turned off Auctionator MiniFeatures, it stopped. Thanks for the response.

**Comment by jrob8577** [comment]
Interesting. I've seen reports of folks seeing this on occasionally, and I'm wondering if MiniFeatures is somehow conflicting.  Thanks for the additional info!

**Comment by als30334** [comment]
np I've been wondering WTF was making that text pop up and it occurred me to one day it was an AH addon I use, but I didn't figure out until a little while ago it definitely was Auctionator MiniFeatures.
