### ISSUE TITLE
Search only showing 1 item when searching prefix not all

### ISSUE THREAD

**Issue by karenlk** [Auctionator/Auctionator#200]
(I looked but could not find this bug or similar reported already, sorry if it is!)

_Please include as much of the following information as possible to help me fix the bug:_

If I search for 'Battlebound warhelm' then I am only seeing results for 'Battlebound warhelm of the feverflare', instead of all results (which I can see on the browse tab, or if I search 'Battlebound warhelm of the h' I can see there is a 'Battlebound warhelm of the Harmonious'). This is happening on both new legion items and old draenor items. I used to be able to search 'Nimble burnished cloak' and see all the variations of it. Now when I search, it only shows me one instead of all variations (tried 'supple helm' as well)

search results:
![auc1](https://cloud.githubusercontent.com/assets/6372935/18218186/339db7dc-711e-11e6-862a-f2f0c04eeacf.jpg)

but on main browse tab shows many available items that should match:
![auc2](https://cloud.githubusercontent.com/assets/6372935/18218198/5b494684-711e-11e6-83f7-16dc4f59d303.jpg)

__Please include a brief description of the bug, including what you were doing, and when it occurred.__

Searching on prefix of items with variations (such as crafted items)

_## Loaded Addons_
Arh
Auctionator
Bartender4
BattlePetBreedID
BattlePetCount
BodyGuardAway
Broker_DurabilityInfo
Broker_MoneyFu
Broker_RecountFu
!BugGrabber
BugSack
CanIMogIt
ChocolateBar
GatherMate2
Gnosis
Livestock
MapCoords
MasterPlanA
MikScrollingBattleText
MovableBags
MoveMyBuffBar
MyRareFinder
Overachiever
PetBattleTeams
Postal
Quester
Recount
SellOMatic
SexyMap
Stubby
!Swatter
TidyPlates
TidyPlatesHub
TidyPlatesWidgets
TidyPlates_Graphite
TidyPlates_Neon
TidyPlates_Quatre
TidyPlates_BlizzardPlates
ZPerl
ZPerl_ArcaneBar
ZPerl_PartyPet
ZPerl_Party
ZPerl_PlayerBuffs
ZPerl_PlayerPet
ZPerl_Player
ZPerl_RaidAdmin
ZPerl_RaidFrames
ZPerl_RaidHelper
ZPerl_RaidPets
ZPerl_TargetTarget
ZPerl_Target

_## Back Trace (LUA Error Output)_

none

**Comment by ceylina** [comment]
Can confirm. Thanks for reporting this. We'll look into the cause and work on a fix

**Comment by ceylina** [comment]
https://files.slack.com/files-pri/T1NEDJY6R-F27TG6S68/wowscrnshot_090216_170332.jpg
https://files.slack.com/files-pri/T1NEDJY6R-F27TWV2JD/wowscrnshot_090216_170923.jpg

What it should look like

https://files.slack.com/files-pri/T1NEDJY6R-F27TXES13/wowscrnshot_090216_172910.jpg
https://files.slack.com/files-pri/T1NEDJY6R-F27TMT5MJ/wowscrnshot_090216_173034.jpg
