### ISSUE TITLE
LUA error on CN game client

### ISSUE THREAD

**Issue by Nukme** [Auctionator/Auctionator#201]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

Keep having this lua error since 4.0.11.  Occurs on every fresh login.

## Steps to Reproduce

_Include the steps I would need to follow to reproduce the bug._

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

Message: Interface\AddOns\Auctionator\Auctionator.lua:316: attempt to compare number with nil
Time: 09/05/16 08:53:51
Count: 1
Stack: Interface\AddOns\Auctionator\Auctionator.lua:316: in function <Interface\AddOns\Auctionator\Auctionator.lua:299>
Interface\AddOns\Auctionator\Auctionator.lua:377: in function `Atr_OnChatMsgAddon'
Interface\AddOns\Auctionator\Auctionator.lua:178: in function `Atr_EventHandler'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

Locals: verString = "4.0.5CN"
userMajor = 4
userMinor = 0
userPatch = 11
otherMajor = 4
otherMinor = 0
otherPatch = nil
(*temporary) = "0"
(*temporary) = "attempt to compare number with nil"
checkVerString = "4.0.11"
VersionStringToInt = <function> defined @Interface\AddOns\Auctionator\Auctionator.lua:292

**Comment by ceylina** [comment]
Potential bug with nag code.

**Comment by ceylina** [comment]
Possible solution: Exclude nag code for clients with multi (double) byte characters. Cyrillic and Chinese/Korean

**Comment by jrob8577** [comment]
I don't think this is us - the verString in the output isn't one we created?  @Nukme is this the most recent version of Auctionator, downloaded from Curse?

**Comment by ceylina** [comment]
Oh good call! I somehow missed that

**Comment by Nukme** [comment]
@jrob8577  Yes, ver 4.0.11, from Curse.

## Interface: 70000
## Title: Auctionator
## Version: 4.0.11
## Author: Borjamacare, Zirco
## X-Website: http://mods.curse.com/addons/wow/auctionator
## X-Localizations: enUS, deDE, ruRU, svSE, frFR, esES, zhTW
## Notes: A lightweight addon that makes it easy and fast to buy, sell and manage auctions
## SavedVariablesPerCharacter: AUCTIONATOR_SHOW_ST_PRICE, AUCTIONATOR_ENABLE_ALT, AUCTIONATOR_OPEN_FIRST, AUCTIONATOR_OPEN_BUY, AUCTIONATOR_DEF_DURATION, AUCTIONATOR_SHOW_TIPS, AUCTIONATOR_V_TIPS, AUCTIONATOR_A_TIPS, AUCTIONATOR_D_TIPS, AUCTIONATOR_SHIFT_TIPS, AUCTIONATOR_DE_DETAILS_TIPS, AUCTIONATOR_DEFTAB
## SavedVariables: AUCTIONATOR_SAVEDVARS, AUCTIONATOR_PRICING_HISTORY, AUCTIONATOR_SHOPPING_LISTS, AUCTIONATOR_SHOPPING_LISTS_MIGRATED_V2, AUCTIONATOR_PRICE_DATABASE, AUCTIONATOR_LAST_SCAN_TIME, AUCTIONATOR_TOONS, AUCTIONATOR_STACKING_PREFS, AUCTIONATOR_SCAN_MINLEVEL, AUCTIONATOR_DB_MAXITEM_AGE, AUCTIONATOR_DB_MAXHIST_AGE, AUCTIONATOR_DB_MAXHIST_DAYS, AUCTIONATOR_FS_CHUNK, AUCTIONATOR_DE_DATA, AUCTIONATOR_DE_DATA_BAK, ITEM_ID_VERSION, AUCTIONATOR_SHOW_MAILBOX_TIPS

**Comment by jrob8577** [comment]
@Nukme Thanks for the additional info! @ceylina I think what's happening here is that someone else has a non-standard version, and when the nag code runs to do the sync reminder, this non standard version string is getting passed.  Irritating.  At any rate, let's bump this for 4.0.12, it's an easy enough fix to just ignore shit that doesn't parse to int, though this is a surprising edge case (we didn't cause it; it's someone else running a modified and outdated version of Auctionator).

**Comment by ceylina** [comment]
Putting it back as a bug
