### ISSUE TITLE
Error "You Do Not Have Enough Items" whenever trying to sell more than one item

### ISSUE THREAD

**Issue by SpartanHedgey** [Auctionator/Auctionator#202]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug
Whenever I try to post an auction with more than 1 items I get the error "You Do Not Have Enough Items". 

## Steps to Reproduce
Literally trying to post more than one item at the AH aftrer using the alt-click feature.

## Loaded Addons
NPCScan, Auctionator, BagBrother, Bagnon, Fishing Buddy, Handynotes, Master Plan, Mogit, Pawn, Postal, Skada, TellMeWhen, Titan Panel, Transmog Tokens, World Quest Tracker, Elvui. DBM
## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by ceylina** [comment]
You are going to have to be way more specific about this.

Do you mean you alt clicked a stack of items and placed them for sale then alt clicked a completely different stack of items and want to placed them for sale and you got this message?

Or did you alt click an item and placed the entire stack up for sale then tried to place more of the same item? If it is the latter that's not a bug that's a limitation of the game (you can't sell what you don't possess).

Please be more detailed in the issue. I will leave this open until I hear back.

**Comment by SpartanHedgey** [comment]
I alt clicked a piece of leatherworking gear (the ilvl 815 ones from
legion), of which I have multiple (with the "max" number of stacks I can
put up apparently being 4) however, upon increasing the number of stacks to
post to anything more than 1 I get this error message.

I'm trying to post multiple single "stacks" of items.

**Comment by SpartanHedgey** [comment]
I said I'm not trying to sell it in "stacks": I'm trying to post multiple
"stacks" of single items, i.e 6*1 Dreadleather Wraps like you suggested in
your reply. I'm still getting this error for some reason..

**Comment by ceylina** [comment]
This should be improved with 4.0.12 

Please update to the latest version

**Comment by rdforbes** [comment]
I'm having the same problem as the OP. Version 4.0.16. I sell a lot of shirts on the AH.  Say I have 6 of the same kind of shirt in my bags.  I'm on the SELL tab.  I try and create an auction for, say, 3 stacks of 1 by selecting the item in my bag (Alt Click).  Then press the big red "Create Auction" button.  The red error message pops up that I don't have enough items. But that's not true. If I didn't have enough of the item, the big red Create Auction button grays-out (by design).
