### ISSUE TITLE
Review scan after placing item to sell.

### ISSUE THREAD

**Issue by ceylina** [Auctionator/Auctionator#203]
Placing an item to sell via either alt-clicking or drag and dropping initiates a query against the server. This is extremely slow (about twice as slow as searching for an item in the buy tab).

Should sales first look at stored data from a full scan and if older than a certain date (date of last full scan) then scan the live AH? This may be a better solution to current issues with backend code from Blizzard.

**Comment by Qrokqt** [comment]
Caching results from full scan for a certain amount of time would be great.
