### ISSUE TITLE
Some items in the "buy" tab are displaying the wrong item level.

### ISSUE THREAD

**Issue by FlagrantWwolf** [Auctionator/Auctionator#204]
**Brief Description of Bug:**
Some items in the "buy" tab are displaying the wrong item level.

**Steps to Reproduce:**
For example the item "Cainen's Preeminent Chestguard." In the buy tab it shows as being Item level 835. However, after I purchased it it is actually only item level 772. The correct item levels are displayed in the "Browse" tab, but not in "Buy." Try looking for items over ilvl 800. That's where I noticed it the most.

**Loaded Addons:**
NPCScan, AutoTurnIn, Bagnon, HandyNotes, Master Plan, Postal, Scrap, The Undermine Journal, 
TomTom, WIM, ElvUI.

**Comment by jrob8577** [comment]
Thanks @FlagrantWwolf we're tracking this one under duplicates #185, but the additional info is helpful!  We should have a fix coming out once I have time to code up the correction.

**Comment by jrob8577** [comment]
duplicates #185
