### ISSUE TITLE
Item levle display on search results wrong

### ISSUE THREAD

**Issue by ceylina** [Auctionator/Auctionator#212]
I totally missed this. I have a fix for a reported issue from the curse page comments

> Did you fix the bug that shows items which are listed with different qualities but only with the price of the cheapest?
> Please check proper search results which seem buggy (e.g. proper item lvl display, all results found) with the following item:
> Sameed's Vision Ring
> On a german client, this item is listed in the standard search from ilvl 759 up to 850 but in your search results I got listet 3 rings at ilvl 810 (tooltip says ilvl 759) but when I click on it, it's always the tooltip of the 759 ring.
> Please do a change note when fixing this bug in a new version.
> Thank you for your effort. At the moment I'm afraid to use this addon to buy anthing from the AH due to this MAJOR bug!
> I tested this with your newest released version.

Setting up pull request to merge fix

**Comment by ceylina** [comment]
#213 pull request up

**Comment by jrob8577** [comment]
Merged to master; building to 4.0.13
