### ISSUE TITLE
Sniper Tool

### ISSUE THREAD

**Issue by Hohstapler** [Auctionator/Auctionator#214]
Hello everyone,

First of all I want to say sorry for posting here, but I couldn't find a place to post my idea.
Second thing is that I want to say thank you for making such an easy to use and great add-on.

My idea is to create a small Sniper tool (similar to TSM, but not that complicate to be used).
I know that idea is not unique and you probably already heard many of similar requests, but I guess it's worth to try to ask since this would be the great feature in Auctionator.

The idea is simple, create a Shopping List and set a price/percentage bellow the currently lowest price that you want to get an item and hit "RUN". System will automatically scan the last page all the time, when the requirement is met it will pop-up on the search box and you can buy it instantly (if you're fast enough, of course).

I am sure it's not easy to make, but with the great things you've already done this could be just a cherry on the cake!

Thank you in advance,
Hoh

**Comment by ceylina** [comment]
We already have the option to create shopping lists to do just this. We will never add automation to Auctionator so you can run what already exists but it will not check for you.
