### ISSUE TITLE
Slow scanning

### ISSUE THREAD

**Issue by errboe1501** [Auctionator/Auctionator#217]
Hey. I have always been using this addon and it is great for AH. However the scanning speed when i want to buy or sell something is so slow. Every page takes like 5 seconds to scan... I tried disabling all other addons and even reinstalled the addon like 3 times. I really hope you can help me out, because there is no other addon that works so well.. Thanks

**Comment by ceylina** [comment]
We are doing our best to come up with a solution but it is not easy. This is a well known issue so closing this to avoid duplicates.
