### ISSUE TITLE
Option to ignore "of" and so on in item names

### ISSUE THREAD

**Issue by moskvach** [Auctionator/Auctionator#218]
This is enhancement suggestion.
A lot of items are selling and buying for transmog. In this case there is no difference what stats are on item. But stats are included in name often. E.g. there is Hard Plate of the Eagle on AH for 50 gold. I want to sale Hard Plate of Strength. Auctionator thinks there is no such item on AH and suggests a higher price.
Please, add an option to ignore such elements in name.

**Comment by ceylina** [comment]
Sorry we will not be entertaining this option.
