### ISSUE TITLE
ILVL Bug

### ISSUE THREAD

**Issue by set1k** [Auctionator/Auctionator#220]
When I try to buy 835-840 BoE item, Auctionator buys instead of her 753-759 BoE with same price!
Week ago I bought 3 840 BoEs on my main, but one of them was 753... I thought I made a mistake, but today i bought 4 835-840 BoEs on my alt, and again 1 item was 759!! In Auction this item sold at the same price 835ilvl-15999.99.99  759ilvl-15999.99.99. Austionator decided to buy me 759 ilvl item :D

**Comment by ceylina** [comment]
We need version and the item in question or we can't help.

**Comment by set1k** [comment]
Auctionator version 4.0.13. 
Item today http://www.wowhead.com/item=141576/aethrynns-everwarm-chestplate
and item earlier http://www.wowhead.com/item=141573/shokells-grim-cinch

**Comment by ceylina** [comment]
Thank you. I'll make sure we look into this and see if we need to fine tune some settings.
