### ISSUE TITLE
Enhancement: Key Modifier for buyouts

### ISSUE THREAD

**Issue by Maleficara** [Auctionator/Auctionator#222]
As requested leaving enhancement request.

In Auctioneer there is an "Easy Buyout" feature which could potentially be replicated in Auctionator.

Selecting a modifier, Shift+ R Click, for example allows you to purchase from the Auction House so long as the item has 1. A buyout price and 2. is at or below your pre-selected max buyout price.

Especially helpful when dealing with the Auction trolls who auction 300 items singularly and you do not want to click "okay" to verify the purchase 300+ times.

**Comment by ceylina** [comment]
You want a snipe tool in aucitonator? Just trying to understand what you want. Granted the but button is rather slow at the moment but I am not sure how adding keybindings helps add to what is already there?

**Comment by Maleficara** [comment]
I was told to leave the ticket after speaking with bajorma (sp) - 

Anyways right now you click buy then OK then buy then okay

We would simply be adding the ability to buy...with one click. Bypassing the repeated need to click the confirmation.

I listed the key modifier on the off chance that someone dealing with the ticket might be familiar with the one click buyout feature as it has existed before or as it functions now in Auctioneer.

On September 22, 2016, at 10:24 PM, Stephanie <notifications@github.com> wrote:

You want a snipe tool in aucitonator? Just trying to understand what you want. Granted the but button is rather slow at the moment but I am not sure how adding keybindings helps add to what is already there?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Auctionator/Auctionator","title":"Auctionator/Auctionator","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/Auctionator/Auctionator">https://github.com/Auctionator/Auctionator</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ceylina in #222: You want a snipe tool in aucitonator? Just trying to understand what you want. Granted the but button is rather slow at the moment but I am not sure how adding keybindings helps add to what is already there?"}],"action":{"name":"View Issue","url":"<a href="https://github.com/Auctionator/Auctionator/issues/222#issuecomment-249105823">https://github.com/Auctionator/Auctionator/issues/222#issuecomment-249105823</a>"}}}

**Comment by ceylina** [comment]
I do know the scope of this addon is not to add the ability to simply buy a predefined criteria for items and have it simply scan the auction house and automatically buy the requested amount, price, etc. That's the principle behind what a sniping tool does and it is not what auctionator is about. The more complex addons are there to fill that role.

You can currently buy with one mouse click per auction using the buy button (yes, it is slow right now) and that should be the extent of how to buy items using this addon.

I will leave this open and discuss it internally and see if we want to expand buying at all.

**Comment by Maleficara** [comment]
Thank you.

I fear perhaps I was not explaining something well as I never have nor do I want to use the AH aggressively. In fact in a very old post someone had claimed that Auctionator had a "one click buyout" feature built in, which inspired my ticket on Curse as I didn't see that feature.

Personally I hate the bloated monster that Auctioneer is, and would prefer never to touch it, but I find myself running it with Auctionator just to deal with clicking "OK" forty times because of trolls on the AH.

Whatever happens. Thank you for all the hard work on Auctionator, I love it.

On September 23, 2016, at 6:43 AM, Stephanie <notifications@github.com> wrote:

I do know the scope of this addon is not to add the ability to simply buy a predefined criteria for items and have it simply scan the auction house and automatically buy the requested amount, price, etc. That's the principle behind what a sniping tool does and it is not what auctionator is about. The more complex addons are there to fill that role.

You can currently buy with one mouse click per auction using the buy button (yes, it is slow right now) and that should be the extent of how to buy items using this addon.

I will leave this open and discuss it internally and see if we want to expand buying at all.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Auctionator/Auctionator","title":"Auctionator/Auctionator","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/Auctionator/Auctionator">https://github.com/Auctionator/Auctionator</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ceylina in #222: I do know the scope of this addon is not to add the ability to simply buy a predefined criteria for items and have it simply scan the auction house and automatically buy the requested amount, price, etc. That's the principle behind what a sniping tool does and it is not what auctionator is about. The more complex addons are there to fill that role.\r\n\r\nYou can currently buy with one mouse click per auction using the buy button (yes, it is slow right now) and that should be the extent of how to buy items using this addon.\r\n\r\nI will leave this open and discuss it internally and see if we want to expand buying at all."}],"action":{"name":"View Issue","url":"<a href="https://github.com/Auctionator/Auctionator/issues/222#issuecomment-249196732">https://github.com/Auctionator/Auctionator/issues/222#issuecomment-249196732</a>"}}}
