### ISSUE TITLE
Search Filter Item Quality

### ISSUE THREAD

**Issue by kaizengamer** [Auctionator/Auctionator#223]
Legion has many mixed-quality item levels.  There is no finite barrier, for example, ilevel 820, where everything about that level is epic quality.  Epics can be as low as 759.  Are you able to include an 'item rarity' filter to searches such as Common/uncommon/rare/epic etc?

**Comment by ceylina** [comment]
Adding as potential enhancement to advanced searches as auction queries have the ability to filter by rarity.

**Comment by ceylina** [comment]
flags for this are:

qualityIndex 

    Can be one of the following values

        nil - No restriction
        1 - Common Quality (white) or better
        2 - Uncommon Quality (green) or better
        3 - Rare Quality (blue) or better
        4 - Epic Quality (purple) or better

**Comment by kaizengamer** [comment]
How do you implement the qualityIndex into a search?

**Comment by VaughanIwyze** [comment]
> 
> 
> How do you implement the qualityIndex into a search?

No response?

**Comment by jrob8577** [comment]
@VaughanIwyze I encourage you to read the available documentation for the underlying auction house query API, and submitting a pull request or response to address this issue.
