### ISSUE TITLE
Search Results do not differentiate item level

### ISSUE THREAD

**Issue by kaizengamer** [Auctionator/Auctionator#224]
Many items in legion share the same name/id/stats, but can range greatly in item level.  Searching for these items using Auctionator search is fruitless because of this, and I find myself reverting to vanilla AH searches.

**Comment by ceylina** [comment]
While there are several items that seem to still be not working in searches correctly, can you give a specific example please so we can look into this. Some items such as demonsteel armor does work correctly and shows items level.

Which part of a search is failing for you?

**Comment by jrob8577** [comment]
Closing, need more details to investigate.
