### ISSUE TITLE
Sell tab

### ISSUE THREAD

**Issue by Rymarri** [Auctionator/Auctionator#229]
I was trying to use the sell tab.... I put my crafted item on, it the current tab it showed no current auctions... I then clicked on the browse tab for wow... it then showed the 4 items that actually were on the AH.  yet the sell tabs says that there are none... I hope this can be fixed because I love this addon..

**Comment by ceylina** [comment]
We need to know the specific item you were trying to sell so we can see if there is an issue. Please reply with the item name.

**Comment by ceylina** [comment]
One more question, did you modify auctionator according to a popular reddit post? If so you made it so it will only search for items you can use. This is not supported and we recommend reinstalling auctionator for curse unmodified.
