### ISSUE TITLE
Search recipe from spellbook

### ISSUE THREAD

**Issue by Serray** [Auctionator/Auctionator#230]
Please include as much of the following information as possible to help me fix the bug:

If i try to search enchantments from my proffessions, i click the "AH" button. 
It now searches for the materials and the enchantment itself.
I can only find the materials, but the enchantment is never shown (and yes, there are existing onces)

_Please include a brief description of the bug, including what you were doing, and when it occurred._

Just try to search enchantmets via the spellbook

_Include the steps I would need to follow to reproduce the bug._

already written

_Include a list of addons you were running at the time this bug occurred._

I think this isnt necessary

**Comment by ceylina** [comment]
Enchants are sort of funny in that they require being "written" to vellum before being sellable. As such this is normal behavior and not something we really can accommodate for as the ID is not the same as what is on the tradeskill frame.
