### ISSUE TITLE
Error mssg: not enough memory to run add-on

### ISSUE THREAD

**Issue by sneekypants** [Auctionator/Auctionator#231]
Here is a copy what pops up on the screen and says send to you.

When I log into a toon, I receive an message that says that I don't have enough memory to run the program. Add on was running fine before this.  I unloaded all the other add ons, and still received the error.  I also uninstalled the newest version of auctionator, and reinstalled an older version where I know I wasn't having an issue, and still get this message.  I have not added or am not running anything different on my system than I did before this error showed up.

please note in your directions for reporting the bug that the website is incorrect. It says "See http://auctionatoraddon.com/bugs for instructions on where to send it.  This website is not a real website.

Thanks for your assistance. 
Sneeky

 Interface\AddOns\Auctionator\AuctionatorLocalize.lua:306: attempt to call global 'GetAuctionItemClasses' (a nil value)
------------
VERS:3.2.4   MEM:   884 KB   DB:0   SE:0  SL:0  FSCHUNK:<nil>  DBVERS:4
------------
REALMS: , Kilrogg_Alliance (0)
------------
STACK: GetAuctionItemClasses > Atr_GetAuctionClasses > Atr_ItemType2AuctionClass > Atr_IsWeaponType > Atr_CalcDisenchantPrice > Atr_STWP_GetPrices > Atr_ShowTipWithPricing > SetInventoryItem > UpdateTooltip
------------
ADDONS: , ACP, AskMrRobot, Auctionator, BagBrother, Bagnon, HandyNotes, IskarAssist, Mutilate, Ovale, Recount, SimpleComboPoints, SliceAdmiral, TomTom, DBM

**Comment by ceylina** [comment]
Check your hard drive space.

**Comment by sneekypants** [comment]
I did, I have enough space. It's your add on. Everything else is working fine. I even unloaded all the other addons , and it still is giving me the error message, but sometimes it will work, sometimes it won't after unloading the other addons. 

Do something fun today
