### ISSUE TITLE
AH button is offscreen

### ISSUE THREAD

**Issue by Etheriss** [Auctionator/Auctionator#233]
I can't see AH button in profession window when AH is opened.
Screen resolution is 1366x768. Auctionator Version 4.0.13.
![wowscrnshot_100416_130456](https://cloud.githubusercontent.com/assets/22614085/19071597/90c28120-8a39-11e6-8b9c-d35558dd4390.jpg)

**Comment by ceylina** [comment]
That is a design flaw on Blizzard's end. You can use one of the many addons that move frames around like moveanything or blizzmove to resolve this. There is nothing we will be adding to move default frames as there are enough addons that do the job better than we could.
