### ISSUE TITLE
More... tab button overlap

### ISSUE THREAD

**Issue by b-morgan** [Auctionator/Auctionator#234]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug
On the More... tab, Check for Undercuts button overlaps the gold amount.

I changed Auctionator\UI\Templates\Frames\Sell.xml line 69 to:

        <Anchors><Anchor point="TOPLEFT"><Offset><AbsDimension x="-28" y="-413"/></Offset></Anchor></Anchors>

**Comment by ceylina** [comment]
The more tab does not show gold amounts. This is what auctionator looks like unless modified

![wowscrnshot_103016_105052](https://cloud.githubusercontent.com/assets/9342192/19837766/d19ee580-9e8e-11e6-9361-a27f668cb538.jpg)
