### ISSUE TITLE
Profession windows freeze for a few seconds after opening them, when Auctionator is enabled in the game

### ISSUE THREAD

**Issue by Snoopza** [Auctionator/Auctionator#239]
## Brief Description of Bug

Opening Profession windows (Jewelcrafting, Blacksmithing, etc..) while Auctionator is enabled, makes the game freeze for a few seconds each time when you open a Profession window.

## Steps to Reproduce

Enable Auctionator, then open any Profession as if you were going to craft something.  This makes the game freeze for a few seconds, and then it becomes responsive again.

## Loaded Addons

Auctionator 4.0.13
Zygor Guides 6.0.14816

## Back Trace (LUA Error Output)

There was no errors on my screen.

**Comment by ceylina** [comment]
I cannot reproduce this on any character that has professions. Have you tried without zygor guids running?
