### ISSUE TITLE
Constant Scanning when buying things

### ISSUE THREAD

**Issue by yesCurtis** [Auctionator/Auctionator#240]
Please include as much of the following information as possible to help me fix the bug:
## Brief Description of Bug

Just buying new things on the auction house, wanting to bulk buy raid materials.
## Steps to Reproduce

Go to buy tab, type in anythign you want, click buy and constantly scanning, buy button never shows.
## Loaded Addons

Just Auctionator.

**Comment by Snoopza** [comment]
Try this:
Delete the addon from your interface folder.
Then in Curse, click on "Tools" and then on "Addon Settings Cleaner"
Delete the settings for Auctionator.
Use Curse to install a new copy of Auctionator and start the game.  This solved that issue for me.

**Comment by jrob8577** [comment]
This would also probably wipe out the AH history, so use at your own risk.  You may wish to back up your settings folder before trying this approach.
