### ISSUE TITLE
Auctionator should use the new scanning option in 7.1

### ISSUE THREAD

**Issue by oscheller87** [Auctionator/Auctionator#241]
Patch 7.1 added the auction house scanning capability to sort by price per unit on items, disregarding stacksize.
For this reason auctionator should not scan more than one single page before being able to determine the price when attempting to post an auction. 

I.e. There is no longer need to scan all 19 pages of Foxflower (which takes roughly 2 minutes) when all the info we need to post the auction is on page 1.

**Comment by jrob8577** [comment]
@oscheller87 I agree!  We'll be looking at this issue this weekend to determine the work involved.

**Comment by oscheller87** [comment]
@jrob8577 Are there difficulties implementing the 7.1 Ah changes?

**Comment by ceylina** [comment]
There are no changes that can be implemented. They simply changed a database field to per unit price. We can't take advantage of because there is nothing exposed to the API that allows this. It's a simple sort replacement that is only exposed to the default UI, not addons.
