### ISSUE TITLE
Auctionator stops scanning when there are a lot of listings for the item you are trying to buy

### ISSUE THREAD

**Issue by Snoopza** [Auctionator/Auctionator#242]
## Brief Description of Bug

Example:  I use Auctionator to try and buy some Leystone Ore.  When there are not a lot of listings for this, then it is no issue.  But sometimes, an idiot appears on my realm that puts 71+ pages of Leystone Ore, 1 Ore at a time for sale on the AH..  When this happens, Auctionator would for example reach "Scanning Page 35/71" and it would just sit there and not go further.
## Steps to Reproduce

Try to buy items such as Leystone Ore on the AH...
## Loaded Addons

Auctionator
## Back Trace (LUA Error Output)

None

**Comment by meltinglava** [comment]
#226 will probably fix this
