### ISSUE TITLE
Lost all auctionator saved data in 7.1

### ISSUE THREAD

**Issue by Shadowmoo** [Auctionator/Auctionator#243]
Please include as much of the following information as possible to help me fix the bug:

Lost all auctionator saved history with last update. Any way to get it back?

**Comment by ceylina** [comment]
Not unless you have a backup. These are stored as wtf files and if they are overwritten or corrupted, you can't recover them easily.

If you have something like hte curse client that makes a backup file for you (.bak in the WTF saved variable folder (World of Warcraft\WTF\Account\<account name>\SavedVariables then you might be able to do a partial recovery by renaming the .bak to .wtf but that is about it.
