### ISSUE TITLE
Autocomplete lua error on CN gameclient

### ISSUE THREAD

**Issue by Nukme** [Auctionator/Auctionator#246]
Please include as much of the following information as possible to help me fix the bug:
## Brief Description of Bug

This error occurs after 7.1 patch. 
## Steps to Reproduce

It may be a little difficult to reproduce on English client. One needs an IME to input  Chinese characters.

Error occurs on following order:
Say you have already searched and cached item "延时之力药水"(Potion of Prolonged Power)
1. Input "延时"
2. No autocomplete
3. With IME on, type in random letters, then delete all you've just typed in
4. Item name autocompletes, and lua error occurs. 
## Loaded Addons

Auctionator 4.0.14
## Back Trace (LUA Error Output)

Message: Interface\AddOns\Auctionator\Auctionator.lua:5061: bad argument #1 to 'strlen' (string expected, got nil)
Time: 10/31/16 01:14:54
Count: 10
Stack: [C]: in function `strlen'
Interface\AddOns\Auctionator\Auctionator.lua:5061: in function`Atr_Item_Autocomplete'
[string "_:OnCharComposition"]:1: in function <[string "_:OnCharComposition"]:1>

Locals: (_temporary) = nil
(_temporary) = "string expected, got nil"

**Comment by ceylina** [comment]
Auctionator has no code for autocomplete. Sounds like a blizzard error. That second lua error

 Interface\AddOns\Auctionator\Auctionator.lua:5061: bad argument #1 to 'strlen' (string expected, got nil)

This might be something we can better insulate against.
