### ISSUE TITLE
SLow scanning

### ISSUE THREAD

**Issue by peacekeeper9** [Auctionator/Auctionator#248]
Since 7.1 the scanning has gotten slower, like when I go to Buy and I click the buy option it just hangs there and then closes the buy window without letting me actually buy anything.

YOu need to make it a main feature for fast scanning.

There was an add in that made scanning instant but can not find it again but since it can be done it needs to be apart of auctionator

**Comment by jrob8577** [comment]
Adding that in changes the way that Auctionator works, and it's not a change I am going to make to the code.  It is possible that I will add it as a switch, but that has been discussed in another open issue, which makes this a duplicate.

As well, the speed is related to server bottlenecks, not code issues.  We are looking at various approaches to attempt to work around these bottlenecks, as has been documented in many other issues and on the forum.  Thanks for your comment.
