### ISSUE TITLE
No stack size information for auction value hints in tooltips for Merchant/Buyback

### ISSUE THREAD

**Issue by thecybermind** [Auctionator/Auctionator#250]
## Brief Description of Bug

If a merchant sells a stack of more than 1 item, the tooltip hints only ever show the value of 1 even if you hold SHIFT to toggle per-item/stack price.

## Steps to Reproduce

Go to Blood Trader and look at almost any item.

## Code Change

AuctionatorHints.lua

Change the GameTooltip:SetMerchantItem and GameTooltip:SetBuybackItem hooks on lines 482-492 to include a 'num' property:

```
hooksecurefunc (GameTooltip, "SetMerchantItem",
  function(tip, index)
    local _, _, _, num = GetMerchantItemInfo(index);
    Atr_ShowTipWithPricing (tip, GetMerchantItemLink(index), num);
  end
);

hooksecurefunc (GameTooltip, "SetBuybackItem",
  function(tip, index)
    local _, _, _, num = GetBuybackItemInfo(index);
    Atr_ShowTipWithPricing (tip, GetBuybackItemLink(index), num);
  end
);
```

**Comment by jrob8577** [comment]
@thecybermind thanks for the fix!  @ceylina submitted as a PR, merging it in now.  Should be deployed later this evening once we test in production.
