### ISSUE TITLE
Tooltip background disappearing 

### ISSUE THREAD

**Issue by redstars86** [Auctionator/Auctionator#253]
Please include as much of the following information as possible to help me fix the bug:

Half of the background, sometimes more disappears from items in my bags due to auctionator. 

_Please include a brief description of the bug, including what you were doing, and when it occurred._

It is constant

_Include the steps I would need to follow to reproduce the bug._

## Loaded Addons

Altoholic
datastore
clique
bgt
epgp
gladius
move anything
mr target
pet tracker
postal
power hungry
skada
tell me when
titan
watto
dvm
_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by ceylina** [comment]
As discussed by the user base in the comment section, this is generally accepted to be an issue with setting tooltips in Move Anything. Please either try setting all available move anything settings to the same location or report this with the author. This is not an auctionator issue
