### ISSUE TITLE
AH scan in professions window shows several items as "Non available" when they are available

### ISSUE THREAD

**Issue by EiniStein** [Auctionator/Auctionator#254]
## Brief Description of Bug

AH scan in professions window shows several items as "Non available" when they are available. For example, all ring bindings are shown as none available, some alchemy items (both the item itself and some of its ingredients) show as *both* "none available" and available.

## Steps to Reproduce

Open enchanting profession window, open AH. Select a ring binding and press the AH button. See outcome.

## Loaded Addons

Specifically disabled all other addons. But the addon Dugi's Workshop suffers from some interaction with this bug. That is, it lists the price of the item as 0 (as in none available), even when I manually scan the AH for the right search term.

## Back Trace (LUA Error Output)

n/a

**Comment by ceylina** [comment]
Did you modify auctionator by chance from a recent reddit post?

**Comment by EiniStein** [comment]
No modifications, and removing then reinstalling doesn't help.

But I noticed that Autioneer seems to suffer from a similar problem where it comes to the interaction with Dugi's Workshop (price for the crafted item remains at 0 in the profession window). So maybe some 7.1 search changes that Auctionator doesn't account for? It does find the crafted items once I remove the {brackets}.
