### ISSUE TITLE
Auctionator not reliable any more. 

### ISSUE THREAD

**Issue by smtips** [Auctionator/Auctionator#256]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

Please note that the same post is at curse.com along with another one. The issue is scary and I cannot use Auctionator with the present bugs as I may lose thousands from its unreliability in the sell tab.

I post an item, Enchant Ring - Gift of Mastery. For 65g. That's the lowest according to the sell window. Then I go and click on the browse window and others have them there for 45g. NO, they didn't just now undercut me.

I quit the game, I delete the cache folder completely. I relaunch the game, delete all the auctions for the item I posted. I do a full scan. I do a search for the same item, and instead of ONE entry there are TWO lines with precisely the same item. One showing the lower price of 45g, the other showing the one I had undercut a bit at 65g50s.

I quit, delete cache folder again, delete the addon and install it from a fresh download.

But as I said, in the sell window, the only ones showing were the ones at ~65g, not the ones listed at 45g.

Something is WAY screwy and this program can no longer be depended upon to post auctions at the lowest price. It was doing the same kind of stuff the other day with different enchants, as I described below.

I do not use any other auction programs. But I'm going to, because I don't want to keep second guessing myself and going to the Auction tab every time to verify that Auctionator is showing me the right price in the Sell window, because it obviously is NOT.

Please note that there are NO LUA errors and things seem to be normal otherwise. So using the bug reporting programs suggested seem fruitless to me as they are both designed to gather LUA error information.

_Please include a brief description of the bug, including what you were doing, and when it occurred._

## Steps to Reproduce

Try posting some Enchant Ring or Enchant Neck , - Gift of [whatever]. Gift of Haste was doing it the other day, and now it's not but gift of Mastery is. 

_Include the steps I would need to follow to reproduce the bug._

Try posting some Enchant Ring or Enchant Neck , - Gift of [whatever].

## Loaded Addons

Auctionator
Bagbrother
Bagnon
Bagnon_Copnfig
Coordinates
DBM
Garrison Commander
Garrison Commander-Broker
Mogit
Nomicakes
Pawn
Postal
Prat 3.0
Prat-3.0_Libraries
Recount
sellgrey
TradeSkillMaster
TradeSkillMaster_Mailing (note that I have NO other modules even installed for TSM, so please rule out TSM's AuctionDB as a possible issue as it is not present whatsoever).

_Include a list of addons you were running at the time this bug occurred._

ABOVE.

## Back Trace (LUA Error Output)
NO LUA ERRORS are present, see full description of issue above.

_You can get this through the use of !BugGrabber and BugSack addons._
NO LUA ERRORS are present.

I *hope* you will be posting about this issue at curse.com as I really don't come here at all. I'd like to see your response at curse. 

Thing is I haven't been checking every item I post, and I may have lost tons of potential gold from this unreliability and not even known it as I post a lot of auctions, not just enchants.

**Comment by nancikennedy** [comment]
Check the itemids for the ones not showing in your search. When they removed multistrike enchants, they converted the existing scrolls to mastery enchant scrolls....but the converted ones are NOT the same item as the scrolls made from true mastery enchants. They're not stackable etc., so I would bet that Auctionator isn't set to show them as the same.
