### ISSUE TITLE
Shopping List Exclusions

### ISSUE THREAD

**Issue by nathanblasdel** [Auctionator/Auctionator#262]
Hello,

Not a bug, but a question. Is there a way to exclude an item from a shopping list. Example: I search for "enchant neck: mark of the trained soldier" the search returns both items "enchant neck: mark of the trained soldier" and "formula: enchant neck: mark of the trained soldier". 

Thank you, and thank you for making such a great addon!

**Comment by jrob8577** [comment]
Hrm.  None that I can think of off the top of my head, unless I change the code to look for exact matches in the shopping list (which would probably not make a lot of people happy, lol).  I can put a feature on my list of things to do to allow folks to select "exact match" for items on a shopping list, but it will be quite some time before I can get to it.  :/

**Comment by nathanblasdel** [comment]
Ok, Thank you.

Not a big deal, just a small QOL improvement on top of an already HUGE improvement. I've used so many AH addons over the years, this is far and away the best I've ever had.
