### ISSUE TITLE
Auctionator miss identifying items

### ISSUE THREAD

**Issue by jamesrichard** [Auctionator/Auctionator#263]
Please include as much of the following information as possible to help me fix the bug:

Searching for "Chain Skullblasters of the" - there were three listed on the AH - one "of the Harmonious", one "of the Fireflash" and one "of the Aurora" . Auctionator listed both the Fireflash and Harmonious as Chain Skull blasters of the Fireflash

I have noticed the same issue with other leather crafted items "flavours" not being listed correctly.

_Please include a brief description of the bug, including what you were doing, and when it occurred._

Searched for "Chain Skullblasters of the" in the buy screen 

_Include the steps I would need to follow to reproduce the bug._

## Loaded Addons

Auctionator
AUC-Auctioneer (core)
Postal
Libraries - Swatter, SideBar, Stubby

## Back Trace (LUA Error Output)

There was no error generated

**Comment by karenlk** [comment]
I am also still seeing this issue in Version: 4.0.19
This is the very similar to issue #200 https://github.com/Auctionator/Auctionator/issues/200
That says it is fixed, but it is not completely fixed. It is fixed for the examples listed in Issue #200, but some still causing this issue.
Example as above, also try searching "Empyrial breastplate" or "Dreadleather pants"
