### ISSUE TITLE
Error - No Buy/Sell tab 

### ISSUE THREAD

**Issue by nate-wells** [Auctionator/Auctionator#267]
Here is the Error that occurs every time I log in to World of Warcraft.  I no longer have a buy/sell tab and I assume it is related.

Thank you for any feedback.

<Error Page 1>

Date: 2017-05-17 20:18:29

ID: 1
Error occured in: Global

Count: 1

Message: ..\AddOns\Auctionator\AuctionatorFilters.lua line 35:
   
	attempt to index global 'Auctionator' (a nil value)

Debug:
   Auctionator\AuctionatorFilters.lua:35: in main chunk

Locals:

ITEM_CLASS_IDS = <table> {

1 = 2
 
2 = 4
 
3 = 1
 
4 = 3
 
5 = 8
 
6 = 0
 
7 = 16
 
8 = 7
 
9 = 9
 
10 = 17
 
11 = 12
 
12 = 15

}

(*temporary) = nil

(*temporary) = <table> 
{
 classID = 0
}

(*temporary) = nil

(*temporary) = 3

(*temporary) = 8

(*temporary) = 0
(*temporary) = 16

(*temporary) = 7

(*temporary) = 9

(*temporary) = 17

(*temporary) = 12

(*temporary) = 15

(*temporary) = nil

(*temporary) = nil

(*temporary) = "attempt to index global 'Auctionator' (a nil value)"

AddOns:
  Swatter, v7.4.5714 (TasmanianThylacine)
  
AtlasLoot, vv8.03.05
  
AtlasLootBurningCrusade, vv8.03.05
  
AtlasLootCataclysm, vv8.03.05
  
AtlasLootClassic, vv8.03.05
  
AtlasLootLegion, vv8.03.05
  
AtlasLootMistsofPandaria, vv8.03.05
  
AtlasLootWarlordsofDraenor, vv8.03.05
  
AtlasLootWrathoftheLichKing, vv8.03.05
  
AucAdvanced, v7.4.5714 (TasmanianThylacine)
  
AucFilterBasic, v7.4.5714 (TasmanianThylacine)
  
AucFilterOutlier, v7.4.5714.5459(7.4/embedded)
  
AucMatchUndercut, v7.4.5714.5585(7.4/embedded)
  
AucStatHistogram, v7.4.5714 (TasmanianThylacine)
  
AucStatiLevel, v7.4.5714 (TasmanianThylacine)
  
AucStatPurchased, v7.4.5714 (TasmanianThylacine)
  
AucStatSales, v7.4.5714.5598(7.4/embedded)
  
AucStatSimple, v7.4.5714 (TasmanianThylacine)
  
AucStatStdDev, v7.4.5714 (TasmanianThylacine)
  
AucStatWOWEcon, v7.4.5714.5613(7.4/embedded)
  
AucUtilAHWindowControl, v7.4.5714.5575(7.4/embedded)
  
AucUtilAppraiser, v7.4.5714.5704(7.4/embedded)
  
AucUtilAskPrice, v7.4.5714.5599(7.4/embedded)
  
AucUtilAutoMagic, v7.4.5714.5686(7.4/embedded)
  
AucUtilCompactUI, v7.4.5714.5694(7.4/embedded)
  
AucUtilEasyBuyout, v7.4.5714.5576(7.4/embedded)
  
AucUtilFixAH, v7.4.5714 (TasmanianThylacine)
  
AucUtilItemSuggest, v7.4.5714.5651(7.4/embedded)
  
AucUtilPriceLevel, v7.4.5714.5633(7.4/embedded)
  
AucUtilScanButton, v7.4.5714.5631(7.4/embedded)
  
AucUtilScanFinish, v7.4.5714.5588(7.4/embedded)
  
AucUtilScanProgress, v7.4.5714.4979(7.4/embedded)
  
AucUtilScanStart, v7.4.5714.5347(7.4/embedded)
  
AucUtilSearchUI, v7.4.5714.5710(7.4/embedded)
  
AucUtilSimpleAuction, v7.4.5714.5705(7.4/embedded)
  
AucUtilVendMarkup, v7.4.5714.4828(7.4/embedded)
  
Auctionator, v4.0.17
  
Babylonian, v5.1.DEV.332(/embedded)
  
Configator, v5.1.DEV.406(/embedded)
  
DebugLib, v5.1.DEV.337(/embedded)
  
LibExtraTip, v5.12.DEV.423(/embedded)
  
SlideBar, v7.4.5714 (TasmanianThylacine)
  
Stubby, v7.4.5714 (TasmanianThylacine)
  
TipHelper, v5.12.DEV.405(/embedded)
  
BlizRuntimeLib_enUS v7.2.0.70200 <none>
  
(ck=7be)

<Error Page 2>

Date: 2017-05-17 21:10:58

ID: 12

Error occured in: Global
Count: 1

Message: ..\AddOns\Auctionator\Auctionator.lua line 343:
   
	attempt to index global 'Auctionator' (a nil value)

Debug:
   Auctionator\Auctionator.lua:343: Atr_SendAddon_VREQ()
   
	Auctionator\Auctionator.lua:2827: Atr_Idle()
   
	Auctionator\Auctionator.lua:2796: Atr_OnUpdate()
   
	 [string "*:OnUpdate"]:1:
      
	  [string "*:OnUpdate"]:1

Locals:

type = "GUILD"

target = nil

(*temporary) = nil

(*temporary) = nil

(*temporary) = nil

(*temporary) = nil

(*temporary) = nil
(*temporary) = "attempt to index global 'Auctionator' (a nil value)"

VREQ_sent = 0

zc = <table> {

 IsEnglishLocale = <function> defined
 @Interface\AddOns\Auctionator\AuctionatorLocalize.lua:63

 msg_red = <function> defined
 @Interface\AddOns\Auctionator\zcUtils.lua:570

 TrimBrackets = <function> defined
 @Interface\AddOns\Auctionator\zcUtils.lua:955

 tallyAdd = <function> defined
 @Interface\AddOns\Auctionator\zcUtils.lua:1108

 msg_yellow = <function> defined
 @Interface\AddOns\Auctionator\zcUtils.lua:572

 msg = <function> defined
 @Interface\AddOns\Auctionator\zcUtils.lua:699

 GetArrayElemOrFirst = <function> defined
 @Interface\AddOns\Auctionator\zcUtils.lua:136

 NumToBool = <function> defined
 @Interface\AddOns\Auctionator\zcUtils.lua:524

 printmem = <function> defined
 @Interface\AddOns\Auctionator\zcUtils.lua:1018

 ParseBattlePetLink = <function> defined
 @Interface\AddOns\Auctionator\zcUtils.lua:417

 ShowHide = <function> defined
 @Interface\AddOns\Auctionator\zcUtils.lua:33

 StringStartsWith = <function> defined
 @Interface\AddOns\Auctionator\zcUtils.lua:892

 StringEndsWith = <function> defined
 @Interface\AddOns\Auctionator\zcUtils.lua:872

 round = <function> defined
 @Interface\AddOns\Auctionator\zcUtils.lua:564

 CopyDeep = <function> defined
 @Interface\AddOns\Auctionator\zcUtils.lua:984

 ClearTable = <function> defined
 @Interface\AddOns\Auctionator\zcUtils.lua:975

 CheckDeferredCall = <function> defined
 @Interface\AddOns\Auctionator\zcUtils.lua:320

 priceToMoneyString = <function> defined
 @Interface\AddOns\Auctionator\zcUtils.lua:803

 tallyPrint = <function> defined
 @Interface\AddOns\Auctionator\zcUtils.lua:1120

 TrimQuotes = <function> defined
 @Interface\AddOns\Auctionator\zcUtils.lua:935

 GetArrayElemOrNil = <function> defined
 @Interface\AddOns\Auctionator\zcUtils.lua:151

 BoolToNum = <function> defined
 @Interface\AddOns\Auctionator\zcUtils.lua:514

 If = <function> defined
 @Interface\AddOns\Auctionator\zcUtils.lua:107

 periodic = <function> defined
 @Interface\AddOns\Auctionator\zcUtils.lua:343

 Min = <function> defined
 @Interface\AddOns\Auctionator\zcUtils.lua:77

 msg_pink = <function> defined
 @Interface\AddOns\Auctionator\zcUtils.lua:571

 SetTextIf = <function> defined
 @Interface\AddOns\Auctionator\zcUtils.lua:44

 QuoteString = <function> defined
 @Interface\AddOns\Auctionator\zcUtils.lua:923

 msg_str = <function> defined
 @Interface\AddOns\Auctionator\zcUtils.lua:589

 ItemNamefromLink = <function> defined
 @Interface\AddOns\Auctionator\zcUtils.lua:447

 enc64 = <function> defined
 @Interface\AddOns\Auctionator\zcUtils.lua:201

 Val = <function> defined
 @Interface\AddOns\Auctionator\zcUtils.lua:55

 IsBattlePetLink = <function> defined
 @Interface\AddOns\Auctionator\zcUtils.lua:409

 msg_ex = <function> defined
 @Interface\AddOns\Auctionator\zcUtils.lua:708

 printableLink = <function> defined
 @Interface\AddOns\Auctionator\zcUtils.lua:1005

 PrintTable = <function> defined
 @Interface\AddOns\Auctionator\zcUtils.lua:373

 StringContains = <function> defined
 @Interface\AddOns\Auctionator\zcUtils.lua:854

 StringSame = <function> defined
 @Interface\AddOns\Auctionator\zcUtils.lua:836

 PullItemIntoMemory = <function> defined
 @Interface\AddOns\Auctionator\zcUtils.lua:482

 priceToString = <function> defined
 @Interface\AddOns\Auctionator\zcUtils.lua:767

 PrintKeysSorted = <function> defined
 @Interface\AddOns\Auctionator\zcUtils.lua:118

 val2gsc = <function> defined
 @Interface\AddOns\Auctionator\zcUtils.lua:749

 Negate = <function> defined
 @Interface\AddOns\Auctionator\zcUtils.lua:534

 IsTextQuoted = <function> defined
 @Interface\AddOns\Auctionator\zcUtils.lua:916

 BoolToString = <function> defined
 @Interface\AddOns\Auctionator\zcUtils.lua:504

 msg_badErr = <function> defined
 @Interface\AddOns\Auctionator\zcUtils.lua:606

 msg_color = <function> defined
 @Interface\AddOns\Auctionator\zcUtils.lua:576

 HSV2RGB = <function> defined
 @Interface\AddOns\Auctionator\zcUtils.lua:614

 md = <function> defined @Interface\AddOns\Auctiona

AddOns:
  Swatter, v7.4.5714 (TasmanianThylacine)
  
AtlasLoot, vv8.03.05
  
AtlasLootBurningCrusade, vv8.03.05
  
AtlasLootCataclysm, vv8.03.05
  
AtlasLootClassic, vv8.03.05
  
AtlasLootLegion, vv8.03.05
  
AtlasLootMistsofPandaria, vv8.03.05
  
AtlasLootWarlordsofDraenor, vv8.03.05
  
AtlasLootWrathoftheLichKing, vv8.03.05
  
AucAdvanced, v7.4.5714 (TasmanianThylacine)
  
AucFilterBasic, v7.4.5714 (TasmanianThylacine)
  
AucFilterOutlier, v7.4.5714.5459(7.4/embedded)
  
AucMatchUndercut, v7.4.5714.5585(7.4/embedded)
  
AucStatHistogram, v7.4.5714 (TasmanianThylacine)
  
AucStatiLevel, v7.4.5714 (TasmanianThylacine)
  
AucStatPurchased, v7.4.5714 (TasmanianThylacine)
  
AucStatSales, v7.4.5714.5598(7.4/embedded)
  
AucStatSimple, v7.4.5714 (TasmanianThylacine)
  
AucStatStdDev, v7.4.5714 (TasmanianThylacine)
  
AucStatWOWEcon, v7.4.5714.5613(7.4/embedded)
  
AucUtilAHWindowControl, v7.4.5714.5575(7.4/embedded)
  
AucUtilAppraiser, v7.4.5714.5704(7.4/embedded)
  
AucUtilAskPrice, v7.4.5714.5599(7.4/embedded)
  
AucUtilAutoMagic, v7.4.5714.5686(7.4/embedded)
  
AucUtilCompactUI, v7.4.5714.5694(7.4/embedded)
  
AucUtilEasyBuyout, v7.4.5714.5576(7.4/embedded)
  
AucUtilFixAH, v7.4.5714 (TasmanianThylacine)
  
AucUtilItemSuggest, v7.4.5714.5651(7.4/embedded)
  
AucUtilPriceLevel, v7.4.5714.5633(7.4/embedded)
  
AucUtilScanButton, v7.4.5714.5631(7.4/embedded)
  
AucUtilScanFinish, v7.4.5714.5588(7.4/embedded)
  
AucUtilScanProgress, v7.4.5714.4979(7.4/embedded)
  
AucUtilScanStart, v7.4.5714.5347(7.4/embedded)
  
AucUtilSearchUI, v7.4.5714.5710(7.4/embedded)
  
AucUtilSimpleAuction, v7.4.5714.5705(7.4/embedded)
  
AucUtilVendMarkup, v7.4.5714.4828(7.4/embedded)
  
Auctionator, v4.0.17
  
Babylonian, v5.1.DEV.332(/embedded)
  
BagBrother, v
  
Bagnon, v7.1.1
  
BeanCounter, v7.4.5714 (TasmanianThylacine)
  
Capping, vv7.2.3
  
Configator, v5.1.DEV.406(/embedded)
  
DBMCore, v@project-version@
  
DBMDefaultSkin, v
  
DBMSpellTimers, v
  
DBMStatusBarTimers, v
  
DebugLib, v5.1.DEV.337(/embedded)
  
DraenorTreasures, v6.2.4.21343
  
GladiatorlosSA, v2.0
  
GTFO, v4.42.10
  
HealBot, v7.2.0.0
  
HealBotTips, v7.2.0.0
  
HealersHaveToDie, v2.4.3
  
IceHUD, v1.10.15
  
ItemPriceTooltip, v92
  
LibExtraTip, v5.12.DEV.423(/embedded)
  
OneBag3, vv3.8.5
  
Postal, vv3.5.8
  
RoguePowerBars, v5.0.4
  
SimpleRaidTargetIcons, v1.21
  
Skada, v1.6.6
  
SlideBar, v7.4.5714 (TasmanianThylacine)
  
Stubby, v7.4.5714 (TasmanianThylacine)
  
TellMeWhen, v8.3.3
  
TipHelper, v5.12.DEV.405(/embedded)
  
TomTom, vv70200-1.0.0
  
WeakAuras, v2.3.9
  
BlizRuntimeLib_enUS v7.2.0.70200 <none>
  
(ck=9e7)

**Comment by Mayo77** [comment]
Having same error. here it is:

Date: 2018-02-11 14:45:39
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Auctionator\Auctionator.lua line 3150:
   table index is nil
Debug:
   Auctionator\Auctionator.lua:3150: Atr_BuildActiveAuctions()
   Auctionator\Auctionator.lua:4662: Atr_BuildGlobalHistoryList()
   Auctionator\Auctionator.lua:3205: Atr_DisplayHlist()
   Auctionator\Auctionator.lua:1355: AuctionFrameTab_OnClick()
   [string "*:OnClick"]:1:
      [string "*:OnClick"]:1
Locals:
i = 11
name = ""
_ = nil
count = 1
link = nil
item_link = <table> {
}
(*temporary) = <table> {
 10314:0:0:0:0 = <table> {
 }
 116702:0:0:0:386 = <table> {
 }
 116702:0:0:0:213 = <table> {
 }
 71984:0:0:0:0 = <table> {
 }
 18365:0:0:0:0 = <table> {
 }
 116702:0:0:0:27 = <table> {
 }
 118823:0:0:0:0 = <table> {
 }
 22926:0:0:0:0 = <table> {
 }
}
(*temporary) = nil
(*temporary) = <table> {
 count = 1
 name = ""
}
(*temporary) = 0
(*temporary) = "table index is nil"
gActiveAuctions = <table> {
 10314:0:0:0:0 = <table> {
 }
 116702:0:0:0:386 = <table> {
 }
 116702:0:0:0:213 = <table> {
 }
 71984:0:0:0:0 = <table> {
 }
 18365:0:0:0:0 = <table> {
 }
 116702:0:0:0:27 = <table> {
 }
 118823:0:0:0:0 = <table> {
 }
 22926:0:0:0:0 = <table> {
 }
}

AddOns:
  Swatter, v7.5.5724 (TasmanianThylacine)
  ACP, vr250 
  Auctionator, v4.0.19
  BadBoy, vv7.3.91
  BadBoyCCleaner, vv7.3.0
  BagBrother, v
  Bagnon, v7.3.2
  BagnonConfig, v7.3.2
  BrokerAFK, v2.8.6
  DebugLib, v5.1.DEV.337(/embedded)
  DugisGuideViewerZ, v4.408
  EasyDeleteConfirm, v
  Oilvl, v6.7.34
  Postal, vv3.5.8
  Scrap, v13.6
  ScrapOptions, v13.6
  ScrapSpotlight, v13.6
  Spy, v3.4.9
  Stubby, v7.5.5724 (TasmanianThylacine)
  BlizRuntimeLib_enUS v7.3.5.70300 <none>
  (ck=1e0)
