### ISSUE TITLE
Auctionator blocking BG Access

### ISSUE THREAD

**Issue by Chris99460** [Auctionator/Auctionator#270]
Date: 2017-08-15 20:35:23
ID: 1
Error occured in: AddOn: Auctionator
Count: 1
Message: Error: AddOn Auctionator attempted to call a forbidden function (JoinBattlefield()) from a tainted execution path.
Debug:
   [C]: JoinBattlefield()
   Blizzard_PVPUI\Blizzard_PVPUI.lua:606: HonorFrame_Queue()
   [string "*:OnClick"]:2:
      [string "*:OnClick"]:1
Locals:
None
AddOns:
  Swatter, v7.0.5 (<%codename%>)
  AckisRecipeList, v7.2.5.1
  Archy, v7.2.0.1
  Auctionator, v4.0.17
  AutoLootPlus, v1.2.0
  Babylonian, v5.1.DEV.332(/embedded)
  Bagnon, v7.2.5
  Configator, v5.1.DEV.406(/embedded)
  Coordinates, v1.22
  Gatherer, v7.0.5
  Recount, vv7.2.5b
  SlideBar, v7.0.5 (<%codename%>)
  TomTom, vv70200-1.0.0
  BlizRuntimeLib_enUS v7.2.5.70200 <none>
  (ck=17a)

**Comment by AcidWeb** [comment]
Already reported (#60) once. Technically it is possible as Auctionator use vanilla DropDown code - and that **might** cause taint that block BG joining (yeah, seriously). 

I suggest to use [LibUIDropDownMenu](https://www.wowace.com/projects/libuidropdownmenu).

**Comment by Ketho** [comment]
I can reproduce this consistently with only Auctionator loaded, see #60 
https://streamable.com/uyflg
https://www.townlong-yak.com/bugs/afKy4k-HonorFrameLoadTaint

**Comment by jrob8577** [comment]
ty @AcidWeb re-ropening in reference to #315

**Comment by jrob8577** [comment]
Fixed in #317
