### ISSUE TITLE
7.3 patch whit Error

### ISSUE THREAD

**Issue by FrenchCurse** [Auctionator/Auctionator#274]
Date: 2017-08-29 15:31:01
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Auctionator\Auctionator.lua line 1301:
   Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
Debug:
   [C]: PlaySound()
   Auctionator\Auctionator.lua:1301: AuctionFrameTab_OnClick()
   [string "*:OnClick"]:1:
      [string "*:OnClick"]:1
Locals:
(*temporary) = "igCharacterInfoTab"

AddOns:
  Swatter, v7.4.5714 (TasmanianThylacine)
  AucAdvanced, v7.4.5714 (TasmanianThylacine)
  AucFilterBasic, v7.4.5714 (TasmanianThylacine)
  AucFilterOutlier, v7.4.5714.5459(7.4/embedded)
  AucMatchUndercut, v7.4.5714.5585(7.4/embedded)
  AucScanData, v7.4.5714 (TasmanianThylacine)
  AucStatHistogram, v7.4.5714 (TasmanianThylacine)
  AucStatiLevel, v7.4.5714 (TasmanianThylacine)
  AucStatPurchased, v7.4.5714 (TasmanianThylacine)
  AucStatSales, v7.4.5714.5598(7.4/embedded)
  AucStatSimple, v7.4.5714 (TasmanianThylacine)
  AucStatStdDev, v7.4.5714 (TasmanianThylacine)
  AucStatWOWEcon, v7.4.5714.5613(7.4/embedded)
  AucUtilAHWindowControl, v7.4.5714.5575(7.4/embedded)
  AucUtilAppraiser, v7.4.5714.5704(7.4/embedded)
  AucUtilAskPrice, v7.4.5714.5599(7.4/embedded)
  AucUtilAutoMagic, v7.4.5714.5686(7.4/embedded)
  AucUtilCompactUI, v7.4.5714.5694(7.4/embedded)
  AucUtilEasyBuyout, v7.4.5714.5576(7.4/embedded)
  AucUtilFixAH, v7.4.5714 (TasmanianThylacine)
  AucUtilItemSuggest, v7.4.5714.5651(7.4/embedded)
  AucUtilPriceLevel, v7.4.5714.5633(7.4/embedded)
  AucUtilScanButton, v7.4.5714.5631(7.4/embedded)
  AucUtilScanFinish, v7.4.5714.5588(7.4/embedded)
  AucUtilScanProgress, v7.4.5714.4979(7.4/embedded)
  AucUtilScanStart, v7.4.5714.5347(7.4/embedded)
  AucUtilSearchUI, v7.4.5714.5710(7.4/embedded)
  AucUtilSimpleAuction, v7.4.5714.5705(7.4/embedded)
  AucUtilVendMarkup, v7.4.5714.4828(7.4/embedded)
  Auctionator, v4.0.17
  AutoLootPlus, v1.2.2
  Babylonian, v5.1.DEV.332(/embedded)
  BeanCounter, v7.4.5714 (TasmanianThylacine)
  Configator, v5.1.DEV.406(/embedded)
  DebugLib, v5.1.DEV.337(/embedded)
  Enchantrix, v7.4.5714 (TasmanianThylacine)
  EnchantrixBarker, v7.4.5714 (TasmanianThylacine)
  Informant, v7.4.5714 (TasmanianThylacine)
  LeatrixPlus, v7.3.00
  LibExtraTip, v5.12.DEV.423(/embedded)
  Postal, vv3.5.8
  SlideBar, v7.4.5714 (TasmanianThylacine)
  Stubby, v7.4.5714 (TasmanianThylacine)
  TipHelper, v5.12.DEV.405(/embedded)
  BlizRuntimeLib_enUS v7.3.0.70300 <none>

**Comment by jrob8577** [comment]
Fix coming out, PM me with an email address for an invite to slack to get the beta to test.

**Comment by FrenchCurse** [comment]
ur awesome great work and ppl are happy thx for the fix
