### ISSUE TITLE
7.3 error

### ISSUE THREAD

**Issue by johnn4321** [Auctionator/Auctionator#275]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug
when accessint the AH I get an addon error
_Please include a brief description of the bug, including what you were doing, and when it occurred._
here is a copy of the error message

Date: 2017-08-29 17:51:21
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\Auctionator\Auctionator.lua line 1301:
   Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
Debug:
   [C]: PlaySound()
   Auctionator\Auctionator.lua:1301: AuctionFrameTab_OnClick()
   [string "*:OnClick"]:1:
      [string "*:OnClick"]:1
Locals:
(*temporary) = "igCharacterInfoTab"

AddOns:
  Swatter, v7.4.5714 (TasmanianThylacine)
  AllTheThings, v1.2.6
  AlreadyKnown, v1.14
  Archy, v7.2.0.1
  AucAdvanced, v7.4.5714 (TasmanianThylacine)
  AucFilterBasic, v7.4.5714 (TasmanianThylacine)
  AucFilterOutlier, v7.4.5714.5459(7.4/embedded)
  AucMatchUndercut, v7.4.5714.5585(7.4/embedded)
  AucScanData, v7.4.5714 (TasmanianThylacine)
  AucStatHistogram, v7.4.5714 (TasmanianThylacine)
  AucStatiLevel, v7.4.5714 (TasmanianThylacine)
  AucStatPurchased, v7.4.5714 (TasmanianThylacine)
  AucStatSales, v7.4.5714.5598(7.4/embedded)
  AucStatSimple, v7.4.5714 (TasmanianThylacine)
  AucStatStdDev, v7.4.5714 (TasmanianThylacine)
  AucStatWOWEcon, v7.4.5714.5613(7.4/embedded)
  AucUtilAHWindowControl, v7.4.5714.5575(7.4/embedded)
  AucUtilAppraiser, v7.4.5714.5704(7.4/embedded)
  AucUtilAskPrice, v7.4.5714.5599(7.4/embedded)
  AucUtilAutoMagic, v7.4.5714.5686(7.4/embedded)
  AucUtilCompactUI, v7.4.5714.5694(7.4/embedded)
  AucUtilEasyBuyout, v7.4.5714.5576(7.4/embedded)
  AucUtilFixAH, v7.4.5714 (TasmanianThylacine)
  AucUtilItemSuggest, v7.4.5714.5651(7.4/embedded)
  AucUtilPriceLevel, v7.4.5714.5633(7.4/embedded)
  AucUtilScanButton, v7.4.5714.5631(7.4/embedded)
  AucUtilScanFinish, v7.4.5714.5588(7.4/embedded)
  AucUtilScanProgress, v7.4.5714.4979(7.4/embedded)
  AucUtilScanStart, v7.4.5714.5347(7.4/embedded)
  AucUtilSearchUI, v7.4.5714.5710(7.4/embedded)
  AucUtilSimpleAuction, v7.4.5714.5705(7.4/embedded)
  AucUtilVendMarkup, v7.4.5714.4828(7.4/embedded)
  Auctionator, v4.0.17
  Babylonian, v5.1.DEV.332(/embedded)
  BadPet, vv1.0.8
  BartrubySummonPet, v1.26
  BattlePetBreedID, vr150
  BeanCounter, v7.4.5714 (TasmanianThylacine)
  BulkMail2Inbox, v7.0.0
  BuyEmAll, v3.4.3
  ClassHallButtonGarrison, v
  Configator, v5.1.DEV.406(/embedded)
  DebugLib, v5.1.DEV.337(/embedded)
  DropTheCheapestThing, vv70100
  Enchantrix, v7.4.5714 (TasmanianThylacine)
  EnchantrixBarker, v7.4.5714 (TasmanianThylacine)
  GatherMate2, v1.40.2
  HandyNotes, vv1.4.14
  HandyNotesDungeonLocations, v1.21
  HandyNotesLegionTownPortals, v0.0.1
  HandyNotesSuramarTelemancy, v1
  HandyNotesWorldMapButton, v2.6
  Informant, v7.4.5714 (TasmanianThylacine)
  iSoldMore, v
  kSellGreyNRepair, v1.2
  LibExtraTip, v5.12.DEV.423(/embedded)
  MinersCoffeeAndPick, v1.9
  OPie, vUmber 9
  PetTracker, v7.1.4
  PetTrackerBreeds, v7.1.4
  PetTrackerBroker, v
  PetTrackerConfig, v7.1.4
  PetTrackerJournal, v7.1.4
  PetTrackerSwitcher, v7.1.4
  PetTrackerUpgrades, v7.1.4
  PremadeGroupsFilter, v1.12
  Rematch, v4.7.5
  SlideBar, v7.4.5714 (TasmanianThylacine)
  Stubby, v7.4.5714 (TasmanianThylacine)
  SushiSort, v7.0.0.0
  TheUndermineJournal, v4.7.20170829
  TipHelper, v5.12.DEV.405(/embedded)
  Titan, v5.12.1.70200
  TitanBag, v5.12.1.70200
  TitanClock, v5.12.1.70200
  TitanCurrenciesMulti, v5.24
  TitanGold, v5.12.1.70200
  TitanLocation, v5.12.1.70200
  TitanLootType, v5.12.1.70200
  TitanPerformance, v5.12.1.70200
  TitanRepair, v5.12.1.70200
  TitanVolume, v5.12.1.70200
  TitanXP, v5.12.1.70200
  TomTom, vv70200-1.0.0
  WorldQuestGroupFinder, v0.26.3
  WorldQuestsList, v41
  BlizRuntimeLib_enUS v7.3.0.70300 <none>
  (ck=c40)

## Steps to Reproduce

_Include the steps I would need to follow to reproduce the bug._

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by jrob8577** [comment]
Fix coming out, PM me with an email address for an invite to slack to get the beta to test.
