### ISSUE TITLE
cant use buy or sell tab

### ISSUE THREAD

**Issue by Kindredspiritgr** [Auctionator/Auctionator#276]
Please include as much of the following information as possible to help me fix the bug:
When you click on buy or sell tab you get an error message
## Brief Description of Bug

_Please include a brief description of the bug, including what you were doing, and when it occurred._
Message: Interface\AddOns\Auctionator\Auctionator.lua:1301: Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
Time: 08/29/17 17:21:05
Count: 1
Stack: Interface\AddOns\Auctionator\Auctionator.lua:1301: Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
Interface\SharedXML\SharedBasicControls.lua:208: in function <Interface\SharedXML\SharedBasicControls.lua:207>
[C]: ?
[C]: in function `PlaySound'
Interface\AddOns\Auctionator\Auctionator.lua:1301: in function `AuctionFrameTab_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals: errorMessage = "Interface\AddOns\Auctionator\Auctionator.lua:1301: Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])"
DisplayMessageInternal = <function> defined @Interface\SharedXML\SharedBasicControls.lua:191
MESSAGE_TYPE_ERROR = 0
## Steps to Reproduce

_Include the steps I would need to follow to reproduce the bug._

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by jasonjohnson99** [comment]
Same issue

`160x Auctionator\Auctionator-4.0.17.lua:2843: attempt to index upvalue 'gCurrentPane' (a nil value)
Auctionator\Auctionator-4.0.17.lua:2843: in function `Atr_Idle'
Auctionator\Auctionator-4.0.17.lua:2796: in function `Atr_OnUpdate'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

Locals:
self = Atr_core {
 0 = <userdata>
 idle_lastUpdate = 0
 dcq_lastUpdate = 0.030000002123415
 TimeSinceLastUpdate = 0
}
elapsed = 0.010000000707805
(*temporary) = nil
(*temporary) = nil
(*temporary) = true
(*temporary) = "attempt to index upvalue 'gCurrentPane' (a nil value)"
gCurrentPane = nil
verCheckMsgState = 1
gHentryTryAgain = nil
`

**Comment by CadenceArmor** [comment]
Date: 2017-08-29 23:50:06
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Auctionator\Auctionator.lua line 1301:
   Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
Debug:
   [C]: PlaySound()
   Auctionator\Auctionator.lua:1301: AuctionFrameTab_OnClick()
   [string "*:OnClick"]:1:
      [string "*:OnClick"]:1
Locals:
(*temporary) = "igCharacterInfoTab"

AddOns:
  Swatter, v7.0.5 (<%codename%>)
  AngryKeystones, v
  Auctionator, v4.0.17
  AutoQuestTracker, vv1.2
  Babylonian, v5.1.DEV.332(/embedded)
  BagBrother, v
  Configator, v5.1.DEV.406(/embedded)
  DBMCore, v7.3.0
  DBMCountPackHoTS, v1.3
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsRaidInfoEmeraldNightmare, v
  DetailsRaidInfoNighthold, v
  DetailsRaidInfoTombOfSargeras, v
  DetailsRaidInfoTrialOfValor, v
  Gatherer, v7.0.5
  gUI4, v1.1
  gUI4ActionBars, v1.1
  gUI4Auras, v1.1
  gUI4CastBars, v1.1
  gUI4Chat, v1.1
  gUI4DevTools, v1.1
  gUI4FontChanger, v1.1
  gUI4Minimap, v1.1
  gUI4Objectives, v1.1
  gUI4Trade, v1.1
  gUI4UnitFrames, v1.1
  Mapster, v1.7.5.1-1-g6975e72
  Masque, v7.3.0
  MasqueGoldpaw, v1.0
  PitBull4, vv4.1.7
  Quester, v7.2.5.0
  QuickRoutes, v7.2-release
  Routes, vv1.5.7a
  SharedMediaGoldpaw, v1.0
  SlideBar, v7.0.5 (<%codename%>)
  StarCursor, vr2
  TomTom, vv70200-1.0.0
  WeakAuras, v2.4.18
  Wyr3dIcyVeinsStats, v
  BlizRuntimeLib_enUS v7.3.0.70300 <none>
  (ck=3f8)

**Comment by nonogarcia** [comment]
Me too.  Since patch 7.3 I can't use Auctionator.  It's my favorite add-on, so hopefully it gets fixed soon.  This also an opportunity to say kudos to the developer.  Love the add-on.  Please fix =)

**Comment by jrob8577** [comment]
I have a fix, but I need someone to test it. Send me an email address for an invite to slack for the beta release to test.

**Comment by FuRiouSOne** [comment]
Why are you requesting people to email you for slack to test? Why not release a "BETA" version so everyone can switch to beta in curse and test? This just sounds too fishy to me, plus slack is not very common to use anymore.

**Comment by jrob8577** [comment]
Don't do it if you're not interested, these are common development and communication tools <shrug>. There's a beta release up on curse now for approval, but I prefer to test before releasing *anything*.
