### ISSUE TITLE
 Brief Description of Bug

### ISSUE THREAD

**Issue by vestiges** [Auctionator/Auctionator#278]
Message: Interface\AddOns\Auctionator\Auctionator.lua:2843: attempt to index upvalue 'gCurrentPane' (a nil value)
Time: 08/30/17 08:14:30
Count: 77
Stack: Interface\AddOns\Auctionator\Auctionator.lua:2843: attempt to index upvalue 'gCurrentPane' (a nil value)
[C]: ?
Interface\AddOns\Auctionator\Auctionator.lua:2843: in function `Atr_Idle'
Interface\AddOns\Auctionator\Auctionator.lua:2796: in function `Atr_OnUpdate'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

Locals: 
after patch 7.3 world of warcraft 8/30/2017

**Comment by jrob8577** [comment]
@vestiges Can you see if this bug happens with version 4.0.19?
