### ISSUE TITLE
bugs after 7.3 

### ISSUE THREAD

**Issue by Ashley54** [Auctionator/Auctionator#279]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug
auction house screens are blank and do not display anything or allow input on the Buy Sell or More.. tabs.  
_Please include a brief description of the bug, including what you were doing, and when it occurred._
## Steps to Reproduce
click on auction guy in auction house and where normally those screens would pop up to allow you to sell or buy there is nothing on the screen
_Include the steps I would need to follow to reproduce the bug._

## Loaded Addons
TSM
[Changelog-BugSack-r300-release.txt](https://github.com/Auctionator/Auctionator/files/1264106/Changelog-BugSack-r300-release.txt)
_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by jrob8577** [comment]
Thanks for the bug report! I've fixed it, and issued the fix to curse; waiting for them to approve before it goes out. (See the comments in the auctionator thread for more info. 😄 )
