### ISSUE TITLE
Auctionator is blocking on AH wow

### ISSUE THREAD

**Issue by Trille1983** [Auctionator/Auctionator#280]
Date: 2017-08-30 17:55:24
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Auctionator\Auctionator.lua line 1301:
   Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
Debug:
   [C]: PlaySound()
   Auctionator\Auctionator.lua:1301: AuctionFrameTab_OnClick()
   [string "*:OnClick"]:1:
      [string "*:OnClick"]:1
Locals:
(*temporary) = "igCharacterInfoTab"

AddOns:
  Swatter, v7.0.5 (<%codename%>)
  NPCScanOverlay, v7.1.0.1
  NPCScanOverlayBroker, v1.2.7
  Ace3, v
  ACP, vr245 
  Altoholic, vr182
  Arh, v1.6.4
  Auctionator, v4.0.17
  Babylonian, v5.1.DEV.332(/embedded)
  BattlePetDailyTamer, v2.1.7
  BittensSpellFlashHunter, v60100.201503092107
  BittensSpellFlashLibrary, v60100.201503092107
  CollectMe, v2.9.3
  Configator, v5.1.DEV.406(/embedded)
  DataStore, vr63
  DataStoreAchievements, vr45
  DataStoreAgenda, vr25
  DataStoreAuctions, vr48
  DataStoreCharacters, vr40
  DataStoreContainers, vr56
  DataStoreCrafts, vr77
  DataStoreCurrencies, vr35
  DataStoreGarrisons, vr21
  DataStoreInventory, vr50
  DataStoreMails, vr49
  DataStorePets, vr42
  DataStoreQuests, vr42
  DataStoreReputations, vr40
  DataStoreSpells, vr30
  DataStoreStats, vr29
  DataStoreTalents, vr59
  DBMCore, v7.3.0
  DBMDefaultSkin, v
  DBMLDB, v
  DBMStatusBarTimers, v
  FishermansFriend, v
  Gatherer, v7.0.5
  GatherMate2, v1.41
  GatherMateSharing, vv1.10
  HandyNotes, vv1.4.15
  HandyNotesBrokenShore, vv1.20
  HandyNotesDraenorTreasures, v1.20a
  HandyNotesDungeonLocations, v1.21
  HandyNotesLegionInstanceWorldQuests, vv1.10
  HandyNotesLegionRaresTreasures, v1.01b
  HandyNotesLegionTreasures, v1
  HandyNotesPandariaTreasures, v1.06
  HandyNotesTreasureHunter, v1
  kSellGreyNRepair, v1.2
  MinimalArchaeology, v7.3.0 (2017-04-07)
  NPCScan, v7.2.0.2
  Ovale, v7.3.0.0
  Postal, vv3.5.8
  Recount, vv7.2.5f
  SlideBar, v7.0.5 (<%codename%>)
  SpellFlash, v7.0
  SpellFlashCore, v2.1.5
  Titan, v5.12.2.70300
  TitanBag, v5.12.2.70300
  TitanClock, v5.12.2.70300
  TitanGold, v5.12.2.70300
  TitanLocation, v5.12.2.70300
  TitanLootType, v5.12.2.70300
  TitanPerformance, v5.12.2.70300
  TitanRepair, v5.12.2.70300
  TitanVolume, v5.12.2.70300
  TitanXP, v5.12.2.70300
  TomTom, vv70200-1.0.0
  WowDings, vv1.3.2
  BlizRuntimeLib_enUS v7.3.0.70300 <none>
  (ck=763)

**Comment by jrob8577** [comment]
See all the conversation about this on curse.
