### ISSUE TITLE
7.3 Empty Panel

### ISSUE THREAD

**Issue by alexas** [Auctionator/Auctionator#281]
As soon as the 7.3 came out, I went to the auction house to sell my obliterum, sadly I couldn't have the addon to work, so I did by hands.

I included an image of what I see when I open it.

## Steps to reproduce
I can replicate by simply installing auctionator and going to the auction house. The panel is empty in all 3 windows (Buy, Sell, More...)

## Addon list
Accountant, Ask Mr.Robot, Atlas loot, **Auctionator**, BagBrother, Bagnon (default addons), Easy Obliterate, Quartz, SexyMap, Skada, WorldQuestTracker, DeadlyBossMod

## Images of bug
![30](https://user-images.githubusercontent.com/664126/29883572-c033b46c-8d7e-11e7-919c-8c0e6402231a.PNG)

**Comment by jrob8577** [comment]
The 4.0.19 release should address this. Please refer to the conversation on curse. Thanks for taking the time to raise this!
