### ISSUE TITLE
Empty windows with patch 7.3

### ISSUE THREAD

**Issue by notflorian** [Auctionator/Auctionator#282]
## Brief Description of Bug

When I click on the auctionneer, the Auctionator windows is empty

## Steps to Reproduce

_Include the steps I would need to follow to reproduce the bug._

## Loaded Addons

Auctionator 4.0.17

## Back Trace (LUA Error Output)

27x Auctionator\Auctionator-4.0.17.lua:2843: attempt to index upvalue 'gCurrentPane' (a nil value)
Auctionator\Auctionator-4.0.17.lua:2843: in function `Atr_Idle'
Auctionator\Auctionator-4.0.17.lua:2796: in function `Atr_OnUpdate'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

Locals:
self = Atr_core {
 0 = <userdata>
 idle_lastUpdate = 0
 dcq_lastUpdate = 0
 TimeSinceLastUpdate = 0
}
elapsed = 0.15500000119209
(*temporary) = nil
(*temporary) = nil
(*temporary) = true
(*temporary) = "attempt to index upvalue 'gCurrentPane' (a nil value)"
gCurrentPane = nil
verCheckMsgState = 1
gHentryTryAgain = nil

5x Auctionator\Auctionator-4.0.17.lua:1301: Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
[C]: in function `PlaySound'
Auctionator\Auctionator-4.0.17.lua:1301: in function `Atr_AuctionFrameTab_OnClick'
Auctionator\Auctionator-4.0.17.lua:1417: in function `Atr_SelectPane'
Auctionator\Auctionator-4.0.17.lua:2694: in function `Atr_OnAuctionHouseShow'
Auctionator\Auctionator-4.0.17.lua:176: in function `Atr_EventHandler'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

Locals:
(*temporary) = "igCharacterInfoTab"

**Comment by bushkanaka86** [comment]
I'm having the same issue. The Buy and Sell tabs are present on the auction window, but they are completely empty.

**Comment by Alexanderj76** [comment]
Hi.
Got the same problem with WoW 7.3

**Comment by peterbolam78** [comment]
Same problem here WoW 7.3 tabs remain but the boxes are blank, hope this gets fixed, really love this mod

**Comment by unckleb** [comment]
I am also having same issue.

**Comment by Pebbelzz** [comment]
I have the problem if I download the "updated" (it's still saying 4.0.17 on there fyi) version off of Curse, but if I take the zip from here on github and put it in the Addons mannually the Buy and Sell tabs are no longer blank and seem to be fully functional.

**Comment by unckleb** [comment]
@Pebbelzz I just tried that, to no avail, it still is showing blank.

![image](https://user-images.githubusercontent.com/31486932/29890956-0d7887e2-8d8f-11e7-91b6-129296cf96ca.png)

**Comment by jrob8577** [comment]
Folks: You need to be patient, I do not control the speed with which curseforge pushes updates to the client.  If you see 4.0.17, then *you do not have the updated version*, and no further bugs needs to be filed.  Please either manually install 4.0.19 from curseforge, or from an archive generated here in the repository, before reporting bugs.

**Comment by notflorian** [comment]
I confirm, version 4.0.19 fix this issue.

I'm very sorry for the noise, thanks again for your awesome addon! ;)
