### ISSUE TITLE
Prohibits me from collecting Horn of War

### ISSUE THREAD

**Issue by gho123** [Auctionator/Auctionator#283]
In my Warrior class hall, trying to collect the Horn of War every day -- the item that instantly lets me complete a world quest -- it won't let me do it with Auctionator enabled.  It gives me an error and I have to disable the addon in order to get the item.

Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

_Please include a brief description of the bug, including what you were doing, and when it occurred._

## Steps to Reproduce

_Include the steps I would need to follow to reproduce the bug._

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by jrob8577** [comment]
I need to get the error in order to diagnose this problem. Please provide as much of the information listed in each of the sections, above (specifically the Back Trace).

**Comment by gho123** [comment]
Thanks for the reply.  I'll I'll try to look into that buggrabber addon tomorrow when the item reproduces and I can try it again.
