### ISSUE TITLE
Constantly needs to be disabled to use unrelated Blizzard UIs

### ISSUE THREAD

**Issue by CavalierAU** [Auctionator/Auctionator#293]
## Brief Description of Bug

Have Auctionator installed...
Goto use LFG for a dungeon or BG
"Blizzard UI has blocked Auctionator... blah blah blah"

## Steps to Reproduce

Have Auctionator
Try to play the game

## Loaded Addons

Auctionator

Stop fucking up.

**Comment by jrob8577** [comment]
Not enough information to reproduce. Not enough courtesy to try.
