### ISSUE TITLE
Bug that keeps appearing

### ISSUE THREAD

**Issue by mlawhun0114** [Auctionator/Auctionator#294]
Date: 2017-12-18 14:10:05
ID: -6
Error occured in: AddOn: Auc-Advanced
Count: 3
Message: Note: AddOn Auc-Advanced attempted to call a protected function (PetActionButton9:Hide()) during combat lockdown.
Debug:
   [C]: Hide()
   ..\FrameXML\PetActionBarFrame.lua:185: PetActionBar_Update()
   ..\FrameXML\SpellBookFrame.lua:516: SpellButton_OnLeave()
   [string "*:OnLeave"]:1:
      [string "*:OnLeave"]:1
Locals:
None
AddOns:
  Swatter, v7.5.5724 (TasmanianThylacine)
  ArtifactPathFinder, v1.6.0
  AucAdvanced, v7.5.5724 (TasmanianThylacine)
  AucFilterBasic, v7.5.5724 (TasmanianThylacine)
  AucFilterOutlier, v7.5.5724.5459(7.5/embedded)
  AucMatchUndercut, v7.5.5724.5585(7.5/embedded)
  AucScanData, v7.5.5724 (TasmanianThylacine)
  AucStatHistogram, v7.5.5724 (TasmanianThylacine)
  AucStatiLevel, v7.5.5724 (TasmanianThylacine)
  AucStatPurchased, v7.5.5724 (TasmanianThylacine)
  AucStatSales, v7.5.5724.5598(7.5/embedded)
  AucStatSimple, v7.5.5724 (TasmanianThylacine)
  AucStatStdDev, v7.5.5724 (TasmanianThylacine)
  AucStatWOWEcon, v7.5.5724.5613(7.5/embedded)
  AucUtilAHWindowControl, v7.5.5724.5575(7.5/embedded)
  AucUtilAppraiser, v7.5.5724.5719(7.5/embedded)
  AucUtilAskPrice, v7.5.5724.5599(7.5/embedded)
  AucUtilAutoMagic, v7.5.5724.5686(7.5/embedded)
  AucUtilCompactUI, v7.5.5724.5715(7.5/embedded)
  AucUtilEasyBuyout, v7.5.5724.5576(7.5/embedded)
  AucUtilFixAH, v7.5.5724 (TasmanianThylacine)
  AucUtilItemSuggest, v7.5.5724.5651(7.5/embedded)
  AucUtilPriceLevel, v7.5.5724.5633(7.5/embedded)
  AucUtilScanButton, v7.5.5724.5631(7.5/embedded)
  AucUtilScanFinish, v7.5.5724.5720(7.5/embedded)
  AucUtilScanProgress, v7.5.5724.4979(7.5/embedded)
  AucUtilScanStart, v7.5.5724.5347(7.5/embedded)
  AucUtilSearchUI, v7.5.5724.5721(7.5/embedded)
  AucUtilSimpleAuction, v7.5.5724.5705(7.5/embedded)
  AucUtilVendMarkup, v7.5.5724.4828(7.5/embedded)
  Auctionator, v4.0.19
  Babylonian, v5.1.DEV.332(/embedded)
  BagBrother, v
  Bagnon, v7.3.2
  BeanCounter, v7.5.5724 (TasmanianThylacine)
  Configator, v5.1.DEV.431(/embedded)
  CrucibleWeight, v18
  DBMCore, v7.3.13
  DBMDefaultSkin, v
  DBMSpellTimers, v
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  DejaCharacterStats, v730rc108
  Enchantrix, v7.5.5724 (TasmanianThylacine)
  EnchantrixBarker, v7.5.5724 (TasmanianThylacine)
  GarrisonMissionManager, vv55
  Gatherer, v7.3.1
  GatherMate2, v1.41
  GTFO, v4.44.2
  HandyNotes, vv1.4.15
  HandyNotesArgus, v0.20.0
  HandyNotesBrokenShore, vv1.22
  HandyNotesLegionTreasures, v1
  HandyNotesSuramarLeylines, v1
  Informant, v7.5.5724 (TasmanianThylacine)
  LegionInvasionTimer, vv7.3.0
  LibExtraTip, v5.12.DEV.430(/embedded)
  Ovale, v7.3.0.3
  Pawn, v2.2.15
  PersonalLootHelper, v1.32
  PLG, v6.0.2.1
  RaiderIO, v7.3.2 (v201712180800)
  RaiderIODBUSA, v
  RaiderIODBUSH, v
  SellJunk, v3.0.15
  Simulationcraft, v1.8.4
  Skada, v1.7.2
  SlideBar, v7.5.5724 (TasmanianThylacine)
  Stubby, v7.5.5724 (TasmanianThylacine)
  TidyPlates, v6.18.11
  TidyPlatesGraphite, v
  TidyPlatesGrey, v
  TidyPlatesNeon, v
  TidyPlatesQuatre, v
  TidyPlatesHub, v
  TidyPlatesWidgets, v
  TipHelper, v5.12.DEV.405(/embedded)
  WorldQuestGroupFinder, v0.27
  WorldQuestTracker, v
  Wyr3dIcyVeinsStats, v
  BlizRuntimeLib_enUS v7.3.2.70300 <none>
  (ck=b21)

**Comment by jrob8577** [comment]
I don't think this is Auctionator?
