### ISSUE TITLE
Scan Returns 0 Results

### ISSUE THREAD

**Issue by CoyoteDancer** [Auctionator/Auctionator#296]
Please include as much of the following information as possible to help me fix the bug:

Since the 7.3.5 patch Scan immediately finishes with 0 results. Slow Scan behaves normally. Same results after reinstalling Auctionator.

Both  !BugGrabber and BugSack addons installed. They are functioning since bug report for another addon was generated before restarting game to reload UI. No error report generated for Auctionator.

**Comment by jrob8577** [comment]
I'll check it out tonight. Weird, I made sure to look at the patch notes to see if there was any API change... :/

**Comment by CoyoteDancer** [comment]
I forgot the possibility of conflicts with other addons. & I have about a dozen loaded. In a few minutes I'll turn off all the others, logout completely, reload the game, and try again. I'll report the results, even if there's no change.

**Comment by jrob8577** [comment]
That will be helpful, ty!

**Comment by aielwyn** [comment]
Having the exact same problem. I've already tried to disabled all other addons, logging out and restarting the game and I still get 0 results with full scan. Slow scan works fine.

**Comment by jrob8577** [comment]
Are you both on a high pop server, out of curiosity? I just checked on Dal, and get immediate scan results. :/ Gonna switch over to a test toon on another server and check...

**Comment by jrob8577** [comment]
Nevermind, apparently Dal is a high pop server now. Don't know when that happened. :P

**Comment by jrob8577** [comment]
OIC, I misinterpreted the original problem. Confirm that Full Scan returns immediately with nothing...

**Comment by CoyoteDancer** [comment]
Servers: Wyrmrest & ScarletCrusade

All addons off & even closed other applications not related to WoW.

Results of latest attempt on Wyrmrest. Sorry for the long code CnP but I'm not sure what you need.



`
BugGrabberDB = {
	["session"] = 6,
	["lastSanitation"] = 3,
	["errors"] = {
		{
			["message"] = "Interface\\AddOns\\LoreLibrary\\LoreLibrary-7.0.04.lua:1617: hooksecurefunc(): WorldMap_ClearTextures is not a function",
			["time"] = "2018/01/17 09:30:51",
			["locals"] = "",
			["stack"] = "[C]: in function `hooksecurefunc'\nInterface\\AddOns\\LoreLibrary\\LoreLibrary-7.0.04.lua:1617: in function `InitMap'\nInterface\\AddOns\\LoreLibrary\\LoreLibrary-7.0.04.lua:1899: in function `?'\nInterface\\AddOns\\LoreLibrary\\LoreLibrary-7.0.04.lua:1819: in function <Interface\\AddOns\\LoreLibrary\\LoreLibrary.lua:1819>",
			["session"] = 5,
			["counter"] = 5,
		}, -- [1]
		{
			["message"] = "...terface\\AddOns\\MozzFullWorldMap\\MozzFullWorldMap-7.02.00.00.lua:798: attempt to concatenate a nil value",
			["time"] = "2018/01/17 09:30:51",
			["locals"] = "self = MFWM {\n 0 = <userdata>\n errata = <table> {\n }\n Cache = <table> {\n }\n InitSettingsPanel = <function> defined @Interface\\AddOns\\MozzFullWorldMap\\InterfaceOptions.lua:254\n Continents = <table> {\n }\n Panels = <table> {\n }\n PixelFix = <table> {\n }\n MapData = <table> {\n }\n RefreshMapOverlays = <function> defined @Interface\\AddOns\\MozzFullWorldMap\\MozzFullWorldMap.lua:623\n TableCopy = <function> defined @Interface\\AddOns\\MozzFullWorldMap\\MozzFullWorldMap.lua:49\n emerald = <table> {\n }\n white = <table> {\n }\n L = <table> {\n }\n DefaultOptions = <table> {\n }\n Labels = <table> {\n }\n}\nevent = \"ADDON_LOADED\"\narg1 = \"MozzFullWorldMap\"\ncontinents = <table> {\n 1 = 13\n 2 = \"Kalimdor\"\n 3 = 14\n 4 = \"Eastern Kingdoms\"\n 5 = 466\n 6 = \"Outland\"\n 7 = 485\n 8 = \"Northrend\"\n 9 = 751\n 10 = \"The Maelstrom\"\n 11 = 862\n 12 = \"Pandaria\"\n 13 = 962\n 14 = \"Draenor\"\n 15 = 1007\n 16 = \"Broken Isles\"\n 17 = 1184\n 18 = \"Argus\"\n}\nid = nil\nname = nil\nmfwm_version = \"7.02.00.00\"\nwowBuild = <table> {\n date = \"Jan 16 2018\"\n toc = 70300\n version = \"7.3.5\"\n build = \"25864\"\n}\nversion = \"7.3.5\"\nbuild = \"25864\"\ndate = \"Jan 16 2018\"\ntoc = 70300\nformatString = \"Your copy of %s may be out of date... you have found mapping data errata. If you are running the most recent version of %s, please log out and e-mail your %s saved variables file to %s or post your saved variables file in the technical support forums at %s. Otherwise, please update your copy of %s.\"\n(*temporary) = <function> defined =[C]:-1\n(*temporary) = ChatFrame1 {\n 0 = <userdata>\n RefreshIfNecessary = <function> defined =[C]:-1\n OnPostShow = <function> defined =[C]:-1\n isInitialized = 1\n CalculateLineAlphaValueFromTimestamp = <function> defined =[C]:-1\n GetInsertMode = <function> defined =[C]:-1\n SetTimeVisible = <function> defined =[C]:-1\n hasOwnFontObject = true\n OnFontObjectUpdated = <function> defined =[C]:-1\n resizeButton = ChatFrame1ResizeButton {\n }\n GetFading = <function> defined =[C]:-1\n IsTextCopyable = <function> defined =[C]:-1\n Clear = <function> defined =[C]:-1\n shouldFadeAfterInactivity = true\n SetIndentedWordWrap = <function> defined =[C]:-1\n GetTimeVisible = <function> defined =[C]:-1\n MarkLayoutDirty = <function> defined =[C]:-1\n SetFont = <function> defined =[C]:-1\n GetMaxLines = <function> defined =[C]:-1\n BackFillMessage = <function> defined =[C]:-1\n UnpackageEntry = <function> defined =[C]:-1\n FontStringContainer = <unnamed> {\n }\n buttonSide = \"left\"\n SetShadowOffset = <function> defined =[C]:-1\n messageTypeList = <table> {\n }\n IsSelectingText = <function> defined =[C]:-1\n GetFont = <function> defined =[C]:-1\n PageDown = <function> defined =[C]:-1\n SetMaxLines = <function> defined =[C]:-1\n CalculateSelectingCharacterIndicesForVisibleLine = <function> defined =[C]:-1\n PackageEntry = <function> defined =[C]:-1\n oldAlpha = 0.15686275064945\n RefreshDisplay = <function> defined =[C]:-1\n SetFontObject = <function> defined =[C]:-1\n GatherSelectedText = <function> defined =[C]:-1\n MakeFontObjectCustom = <function> defined =[C]:-1\n isDisplayDirty = true\n SetOnScrollChangedCallback = <function> defined =[C]:-1\n CalculateNumVisibleLines = <function> defined =[C]:-1\n isDocked = 1\n fontObject = table: 000000CCF39EDF10 {\n }\n overrideFadeTimestamp = 0\n SetShadowColor = <function> defined =[C]:-1\n SetInsertMode = <function> defined =[C]:-1\n MarkDisplayDirty = <function> defined =[C]:-1\n tellTimer = 4863.998\n GetMessageInfo = <function> defined =[C]:-1\n GetOnScrollChangedCallback = <function> defined =[C]:-1\n channelList = <table> {\n }\n ScrollDown = <function> defined =[C]:-1\n AtTop = <function> defined =[C]:-1\n GetFontObject = <function> defined =[C]:-1\n zoneChannelList = <table> {\n }\n SetScrollOffset = <function> defined =[C]:-1\n flashTimer = 0\n fontStringPool = <table> {\n }\n visibleLines = <table> {\n }\n textIsCopyable = false\n CanEffectivelyFade = <function> defined =[C]:-1\n scrollOffset = 0\n fadeDurationSecs = 3\n insertMode = 2\n timeVisibleSecs = 120\n OnPreSizeChanged = <function> defined =[C]:-1\n historyBuffer = <table> {\n }\n GetScrollOffset = <function> defined =[C]:-1\n ResetSelectingText = <fun",
			["stack"] = "...terface\\AddOns\\MozzFullWorldMap\\MozzFullWorldMap-7.02.00.00.lua:798: in function <...terface\\AddOns\\MozzFullWorldMap\\MozzFullWorldMap.lua:660>",
			["session"] = 5,
			["counter"] = 5,
		}, -- [2]
		{
			["message"] = "Interface\\AddOns\\LoreLibrary\\LoreLibrary-7.0.04.lua:796: Usage: PlaySound(soundKitID, optional[\"SFX\",\"Music\",\"Ambience\", \"Dialog\" or \"Master\"], [forceNoDuplicates, runFinishCallback])",
			["time"] = "2018/01/17 09:30:58",
			["stack"] = "[C]: in function `PlaySound'\nInterface\\AddOns\\LoreLibrary\\LoreLibrary-7.0.04.lua:796: in function `UpdateBookDisplay'\nInterface\\AddOns\\LoreLibrary\\LoreLibrary-7.0.04.lua:1804: in function <Interface\\AddOns\\LoreLibrary\\LoreLibrary.lua:1783>\n(tail call): ?\n[C]: ?\n[string \"safecall Dispatcher[1]\"]:9: in function <[string \"safecall Dispatcher[1]\"]:5>\n(tail call): ?\n...face\\AddOns\\Archy\\Libs\\AceAddon-3.0\\AceAddon-3.0-12.lua:558: in function `EnableAddon'\n...face\\AddOns\\Archy\\Libs\\AceAddon-3.0\\AceAddon-3.0-12.lua:651: in function <...face\\AddOns\\Archy\\Libs\\AceAddon-3.0\\AceAddon-3.0.lua:636>\n[C]: in function `LoadAddOn'\nInterface\\FrameXML\\UIParent.lua:429: in function `UIParentLoadAddOn'\nInterface\\FrameXML\\UIParent.lua:528: in function `TimeManager_LoadUI'\nInterface\\FrameXML\\UIParent.lua:1114: in function <Interface\\FrameXML\\UIParent.lua:1011>",
			["session"] = 5,
			["counter"] = 5,
		}, -- [3]
	},
}
`

**Comment by CoyoteDancer** [comment]
hmmm - I see that it includes reports from other addons although I'm certain they were deselected when I logged into game.

**Comment by CoyoteDancer** [comment]
And yes - all fields showing in the UI return 0 as the value

**Comment by jrob8577** [comment]
Yeah I'm not seeing anything Auctionator in that dump, but yes I am seeing the bugged behavior. I am at work, so I'll dig into this tonight! It looks like the behavior of the Query function may have changed when receiving nil params, but that's a wild ass guess that I'll need to work at a little more.

**Comment by CoyoteDancer** [comment]
I'll make a few more trials and report whatever adds to the info so you have as much as possible to work with tonight.

I just installed both of the Bug addons this morning so they should be up to date. I get output to the chat window - so long that the beginning is not showing. But I'm not getting the popup window to send report, although I was the first time i tried (before turning off other addons)

**Comment by CoyoteDancer** [comment]
So I've tried three more times - twice on Wyrm with only the three addons loaded. Same results. Opened Bugsack from the minimap button -  reports no bugs found. Then after quitting game re-enabled the other addons I normally use. This time I logged on the char that is on ScarletCrusade. Same results: 0 scans. This time Bugsack reported the same addons errors as what i posted above. So the bug addons are functioning as expected, but I have no more info to add as far as troubleshooting.

**Comment by kingewee** [comment]
Suggestion let this add-on use http https scans and update in-game ui from worldofwarcraft.com auction house (if they let a phone app do it they will let a add-on as well) ;)

**Comment by jrob8577** [comment]
It's something I can consider, but it's not something that is currently implemented, so would be a large development effort. Are you referencing the blizzard app? They can give themselves preferential treatment to access their own APIs, IIRC there's a limit to how many API requests I can make. At any rate, it's an interesting idea to consider, can you take it out of this thread and put it in a Feature Request issue, with a description of how you see something like this working?

**Comment by jrob8577** [comment]
As well, addons are explicitly not allowed to make HTTP requests from within game, which is why you see the copy and paste behavior of so many addons (ask mr robot, a few different auction house addons, etc.)

**Comment by kingewee** [comment]
Just use same HTML5 window they do for "help" or ticket support is the key to your answer it will require someone with c++ but its 100% do-able  specially since 90% of users download addons via twitch that allow access to blizzard (their is me hinty) Question is will Blizzard like the new-age of HTTP mods through twitch? idk lol BUT they did let TWITCH LINK with BLIZZARD

**Comment by jrob8577** [comment]
Yes, but blizzard can do things that addon developers outside of blizzard can not. Happy to take a look at the source for an addon that does this though, if you can point me in that direction? Also, please take this conversation to another issue so that we are not obscuring comments related to the reported issue.

**Comment by kingewee** [comment]
if you can accomplish it the need for going to Stormwind or main citys in general will be 0 you can use AH from clicking on mini map ;x

**Comment by jrob8577** [comment]
@kingewee All future comments on this thread will be deleted. Please take this conversation to a new thread to discuss this feature.

**Comment by Gunnerb52** [comment]
I am on Nesingwary (which is not a high population server) and when I click scan it immediately comes back with 0 items found. I cleared out all the caches and tried again. Same thing. I uninstalled and reinstalled and still 0 items found.

**Comment by jrob8577** [comment]
A friendly user on the [forums](https://us.battle.net/forums/en/wow/topic/20760996641) provided me with a clue to check the right location - I suspect the code is not correctly checking that the user is allowed to make an AH request everywhere one is made, and this is causing some of the errors folks have been reporting.

As well, it seems as if the server is always telling me that I am not allowed to make a mass query (which is what is used for the full scan).  I'm going to keep testing to see if it ever tells me I can make a mass query...

**Comment by jrob8577** [comment]
Following this [blue post](https://us.battle.net/forums/en/wow/topic/20761046621), waiting for updates... They've only stated that "some" functionality has been disabled, and I'm pretty sure the full scan functionality was some of it...

**Comment by CoyoteDancer** [comment]
At least the slow scan still works, so it's definitely worth using Auctionator. Just need to go make sandwich while scanning. And I usually forget to eat while playing, so that's a good thing. :D

**Comment by James1o1o** [comment]
Weird, I had the same issue, but I just tried today, and the fast scan is working again. Did Blizzard maybe fix it in one of their hotfixes?

![image](https://user-images.githubusercontent.com/29644651/35182918-0eb47308-fdd5-11e7-8e0b-c3830ac6d5f3.png)

**Comment by jrob8577** [comment]
![good-news-everyone](https://user-images.githubusercontent.com/838110/35185579-e60362d4-fdbb-11e7-9490-1ac14c0a8f74.jpg)
Testing now.

**Comment by jrob8577** [comment]
Confirmed working! Thanks @James1o1o for posting it was fixed!
