### ISSUE TITLE
0 Scan hotfix

### ISSUE THREAD

**Issue by kingewee** [Auctionator/Auctionator#297]
they changed some code around for AH just minor fix if you are using https or http to scan for updates... for AH scans hence why people are getting 0 scan results if not the case then no clue just login try to scan with debug mode on. but changing https worked for me on modified version I made

Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

_Please include a brief description of the bug, including what you were doing, and when it occurred._

## Steps to Reproduce

_Include the steps I would need to follow to reproduce the bug._

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by jrob8577** [comment]
Thanks for the report! Can you provide a little more information? We're using the in-game API to query the auction house, so there's no HTTP requests sent from the addon.
