### ISSUE TITLE
Causing major lag spikes since patch.

### ISSUE THREAD

**Issue by Ekrol1** [Auctionator/Auctionator#298]
Hello,

Love the addon.

Unfortunately since yesterdays patch, this addon is causing major lag spikes when attempting to use the auction house. Opening the AH, posting, searching, etc. Sometimes it works, sometimes it freezes. I have attempted to use the AH with no other addons enabled and still have the issue, and disabling Auctionator fixes it.

Cheers

**Comment by jrob8577** [comment]
Can you give me an example of what I would need to do to reproduce this behavior?

**Comment by Ekrol1** [comment]
Just regular AH use? Sorry I don't know how to be more specific. 

Sometimes I'll click the AH NPC and nothing will happen for 10-60 seconds and then i'll receive "Internal Auction House Error". Attempting to use the AH after that will normally work, but may lag up again at any time. While searching for items (usually potions and flasks for me), the search will pause for any length of time for example at "Page 5/7". Posting auctions will also sometimes, but not always, freeze up.

While the lag is happening, it also locks me out of being able to logout or use the mailbox, but I am able to cast spells or chat just fine.

**Comment by jrob8577** [comment]
No worries, even that information helps. We have been seeing laggy requests to the server since Legion was released, and I'm wondering if this is just more of the same. I'll take a look and see if I can reproduce though!

**Comment by Ekrol1** [comment]
Thanks.

Is it possible that a change in computer / graphics settings could trigger this? I did get a new computer within the past week. I didn't notice it before the patch, but it could be the problem as well. Previously I had been on a Macbook, and am now on a Dell Gaming Laptop.

**Comment by jrob8577** [comment]
Not sure - I had some serious graphics issues a while back from one of the systems graphics settings, but I wasn't testing Auctionator at the time. You might try scaling back your graphics quality and interacting with the AH to test if those are related?
