### ISSUE TITLE
Tooltip stopped displaying auction prices

### ISSUE THREAD

**Issue by 1Kage1** [Auctionator/Auctionator#299]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

Pretty much the same thing as the title. after I rescanned for new prices using the usual scan (fast one) the prices just up and gone. Now it shows "uknown" in the place where price supposed to be

## Steps to Reproduce

First time it occured, I think i started to scan and closed the auction tab by moving away from the npc

## Loaded Addons

Advanced Interface Options, Angry Keystones, Big Wigs, Little Wigs, DGC, ElvUI, Pawn, Plater, OHC, Postal, Weakauras

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by kodewdle** [comment]
Ruling this out from being an issue related to usage with ElvUI, as i don't have this problem using Auctionator and ElvUI.
