### ISSUE TITLE
Dropdown usage cause taint

### ISSUE THREAD

**Issue by AcidWeb** [Auctionator/Auctionator#315]
Bugs #270 and #60 are still valid. 

Easy fixable by adding small snippets to your code. Read up on:
https://www.townlong-yak.com/bugs/afKy4k-HonorFrameLoadTaint
https://www.townlong-yak.com/bugs/Kjq4hm-DisplayModeCommunitiesTaint

**Comment by jrob8577** [comment]
Reopened, ty for confirming and links!!
