### ISSUE TITLE
AH Merged between factions - reduce memory footprint?

### ISSUE THREAD

**Issue by jrob8577** [Auctionator/Auctionator#32]
I've characters of both factions (horde and alliance) on the same realm, and I noticed that they don't use the same database. Now the AH's have merged I think it would use less memory and data storage if both factions on the same (and merged) realms would use one database.

Requested by http://www.curse.com/users/Altodicted on 7/11/2015
http://www.curse.com/addons/wow/auctionator?comment=5585

**Comment by josheinstein** [comment]
Came to suggest the same improvement, but I see that it's already an open issue.
