### ISSUE TITLE
Disenchanting return incorrect 

### ISSUE THREAD

**Issue by JRDavis91** [Auctionator/Auctionator#320]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

_The disenchant section when you highlight a piece of equipment shows the wrong item see example https://cdn.discordapp.com/attachments/403278800806346753/469508460677955604/unknown.png
This is misleading on whether or not to disenchant as you chaos crystals are 40+gold.._

## Steps to Reproduce

_Highlight the piece of equipment, see what it says you will get and disenchant and then see what the result is._

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by AKA-Syenite** [comment]
Here are two more examples of this error.

![image](https://user-images.githubusercontent.com/918621/43171047-47e34aae-8f76-11e8-80f2-0aba00b67c84.png)

![image](https://user-images.githubusercontent.com/918621/43171036-2a1caa4c-8f76-11e8-91e1-2c1fa5de5558.png)

**Comment by jrob8577** [comment]
Anyone know where to find up to date disenchanting probability tables? I've updated with the new mat constants, but need the relative probabilities to make this work in Auctionator.

**Comment by raysmith59** [comment]
I'm still not seeing this information out there so I sharded everything I have across toons and came up with:

Greens: 5.68 Gloom Dust (probably 6, range seems to be 4-9)
Blues: 1.5 Umbra Shard, 1.5 Gloom Dust
Purples: 1 Veiled Crystal, 0.31 Umbra Shard

iLvl didn't seem to have much if any impact.

I had a few dozen greens and blues and about 100 purples so they should be relatively reliable.

**Comment by FireAllianceNX** [comment]
I haven't been able to find any public tables out there aside from another addon's own collecting of data.
Is it possible to at least list the right disenchant mats to the right level (or ilevel of gears) and just list all mats? Obviously uncommon to uncommon only, but epic listing purple and blue prices, would be helpful to see vendor vs DE prices.

This table has at least some predictor, aside from the scaled expansions. https://www.wow-professions.com/wowguides/wow-disenchanting-guide.html

**Comment by git-Triste** [comment]
vvystari provided some great updates here if they can be incorporated: https://www.curseforge.com/wow/addons/auctionator?page=4#c7002

**Comment by mbloms** [comment]
Auctionator show disenchant value, but item isn't even disenchantable
![bild](https://user-images.githubusercontent.com/4217409/68398326-d6373d80-0174-11ea-9f2a-b578c912daf9.png)
