### ISSUE TITLE
Local (error)

### ISSUE THREAD

**Issue by Detonite** [Auctionator/Auctionator#322]
New bug picked up by Buggrabber today, hev not seen this one before

ADDON_ACTION_BLOCKED] AddOn 'Auctionator' tried to call the protected function 'CompactRaidFrame1:Show()'.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: in function `Show'
FrameXML\CompactUnitFrame.lua:350: in function `CompactUnitFrame_UpdateVisible'
FrameXML\CompactUnitFrame.lua:283: in function `CompactUnitFrame_UpdateAll'
FrameXML\CompactUnitFrame.lua:117: in function <FrameXML\CompactUnitFrame.lua:53>

Locals:
InCombatSkipped

**Comment by jrob8577** [comment]
@Detonite Have you seen this since the last update?
