### ISSUE TITLE
Auctionator will not allow me to Auction an item that has no other auctions like it

### ISSUE THREAD

**Issue by ZeroQuarter** [Auctionator/Auctionator#325]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

_Please include a brief description of the bug, including what you were doing, and when it occurred._

## Steps to Reproduce

_Include the steps I would need to follow to reproduce the bug._

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by jrob8577** [comment]
It allows me to post such an auction, but it does not supply a price since there is no data on which to base that price? Please re-open if this is not the case!
