### ISSUE TITLE
Feature Request : Add a "Post all" Checkbox for create a aution for the last partial stack

### ISSUE THREAD

**Issue by Nexxxy** [Auctionator/Auctionator#326]
This addon is awesome, i just miss one thing.

 

If i have 19 herbs and want to sell them in 5 sized stacks i only can create 3 x 5 = 15.

To sell the missing 4 herbs i have to reclick the herb .. wait again for 37 pages to be scanned and now can create a 1x4 stack.

 

It would be awesome if there would be a [ ] checkbox below the amount of stacks textbox saying : "Sell all". If checked it creates the max amount of the stacksized stacks + 1 dynamic stack.

In my example that would be 3x5 + 1x4 stacks.

 

Greetings

Nexxy

**Comment by Nexxxy** [comment]
Ok i dont get how your code recognizes when a startAuction Event is done.
My solution is to add a CheckBox into the Sell.xml
`
CheckButton name="Atr_SellallCheckBox" inherits="UICheckButtonTemplate">
`

then i edited : Atr_CreateAuction_OnClick() in Auctionator.lua

and added 
`
  -- this Block is for that last unfinished stack 
  if (Atr_SellallCheckBox:GetChecked() == true) then

	Auctionator.Debug.Message( 'Atr_SellallCheckBox Test : Checked' );
	countItems = Atr_GetNumItemInBags(gCurrentPane.activeScan.itemLink);
	countItems = countItems - (gJustPosted.StackSize * gJustPosted.NumStacks)
	Auctionator.Debug.Message( 'Atr_CreateAuction_OnClick() Items left : ',countItems);	
	-- this only works if the user rly wants to sell all! 
	if (countItems < gJustPosted.StackSize) then		
		StartAuction (stackStartingPrice, stackBuyoutPrice, duration, countItems, 1);   
		Auctionator.Debug.Message( 'Atr_CreateAuction_OnClick : ', "adding 1 last Stack of ", countItems);			
	else 
		Auctionator.Debug.Message( 'Atr_CreateAuction_OnClick() Items left : ',gJustPosted.StackSize, " - " ,countItems);	
	end	
	Atr_SellallCheckBox:SetChecked(false);
  end
`

My main Problem is that i cant archive it with 1 single click on create Auction
Greetings
Nexxy

**Comment by Nexxxy** [comment]
Ok, 
my further problem is that if i create a Action with StartAuction(), he just removes the current item from selling ... and i dont geht why. I guess thats why i cant use StartAuction() twice ?

**Comment by Nexxxy** [comment]
New day new attempt. 
I digged further into StartAuction .. this function clears my item.

My new attempt is to reget the ItemLink, find it in our bag, get it on Cursor and drop it again into Auction house.

Meanwhile the Auctionhouse StartAction still takes too long to make the next StartAuction happen .. Thus i have to click twice on Create Auction.

Get the Code here : 
https://paste.ofcode.org/9T8JLuHbWYVU7tF7qRC3UT

i also upload my Sell.xml and my Auctionator.lua file here.

**Comment by Nexxxy** [comment]
[Auctionator.lua.txt](https://github.com/Auctionator/Auctionator/files/2282581/Auctionator.lua.txt)

[Sell.xml.txt](https://github.com/Auctionator/Auctionator/files/2282579/Sell.xml.txt)

**Comment by jrob8577** [comment]
@Nexxxy 404 on that paste link. Can you submit a PR?

**Comment by meltinglava** [comment]
@Nexxxy If you need a guide on how to submit a PR(pull request),

- terminal(https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github). 
- web gui:
1. Make a Fork (button on the top right of the screen)
2. Push the edit key and change each file that you have changed. Write a title of what the changes where, and some notes if needed in the description. 
3. Follow the steps from the terminal guide starting from [creating a pull request](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github#create-pull-request)

**Comment by Nexxxy** [comment]
Here you go : https://github.com/Auctionator/Auctionator/pull/336

**Comment by jrob8577** [comment]
Closing this and the associate pull request, though your work is very appreciated!! With all of the changes in 8.3, this will probably no longer be necessary...
