### ISSUE TITLE
Sorcerous Earth causes hang

### ISSUE THREAD

**Issue by Walkerbo** [Auctionator/Auctionator#327]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug
When I search for Sorcerous Earth using the Auctionator Buy tab the search hangs at page 2/6.
If I search using the default search tab it does show Sorcerous Earth.

## Steps to Reproduce
Open Auctionator Buy tab enter Sorcerous Earth into the search field and click search
Search a saved list that has Sorcerous Earth in it.

## Loaded Addons
List is too long to type so I have uploaded an image.
https://i.imgur.com/xR9cy0U.png

## Back Trace (LUA Error Output)
Bugsack is not catching any errors.

**Comment by jrob8577** [comment]
This tends to happen on high population servers when there are a ton of auctions in the AH. Not sure what can be done to mitigate, but I'll leave this open as a bug to track.
