### ISSUE TITLE
Auctionator selling saying "No Current Auctions Found" for every item!!!

### ISSUE THREAD

**Issue by OrionGold** [Auctionator/Auctionator#328]
Any item that I Alt-Click to post with Auctionator and only posting the item based off of History Price not by Current price because it says there arent any on the AH when I specifically know there are. I have full scanned multiple times. Nothing has fixed it

Not sure if the problem has anything to do with me also using TSM or what. 
Please fix or get back to me asap, dont wanna run into this problem going into BFA. 

Thanks.

**Comment by roobrarcade** [comment]
I am also having this issue -- alt-clicking an item to sell, doesn't populate the lowest value found.
