### ISSUE TITLE
ERRORS: Hundreds of white messages in chat log

### ISSUE THREAD

**Issue by YouTubeNATE** [Auctionator/Auctionator#330]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

_When I log onto a character,,, I get a bunch of Atr_ white messages in chat.  Then when I open the AH, I get more.  And when I hover my mouse or search for items in the AH, the white errors are so continually numberous - I'm having to disable Auctionator now because there are too many errors._

## Steps to Reproduce

_I logged onto my character and off many times, and all the aforementioned errors occurred._

## Loaded Addons

_I was only running one addon at the time this bug occurred: Auctionator 5.0.4.  Then I installed BugGrabber & BugSack 8.0.5 and retested with all 3 addons to get Back Trace results.  Everything behaved the same as with only Auctionator 5.0.4. I also installed ChatLog 0.0.1 to get a copy of the errors in the chat box._

## Back Trace (LUA Error Output)

_BugStack shows no errors; however, the problem is in the chat log._

## Chat Log

-8/16 09:11:09.192  You are now queued in the Dungeon Finder.
8/16 09:12:45.212  If you don't have Spirit of Eche'ro it will be removed soon. so what some people are saying 
8/16 09:15:18.249  FRIEND_ONLINE
8/16 09:16:54.693  Donna says: I have your gorilla! Nyah nyah!
8/16 09:16:54.693  Donna says: I wonder if your Grindgear Gorilla can jump across the Park!
8/16 09:17:21.693  Roonsia-Frostmane creates Versatile Kyanite.
8/16 09:17:23.259  Roonsia-Frostmane creates Versatile Kyanite.
8/16 09:17:59.934  FRIEND_OFFLINE
-

**Comment by YouTubeNATE** [comment]
Dang... ChatLog is so out of date that it won't display the numberous white messages from Auctionator.

**Comment by YouTubeNATE** [comment]
I opened AH with Auctionator, and had to painstakingly look and try to type what was in the Chat Box because ChatLog won't copy it... 

Atr_AuctionFrameTab_OnClick table: 000001995AE1C570 nil nil
Atr_IsAuctionatorTab 1
Atr_HideAllDialogs
Atr_OnAuctionHouseShow
Atr_ResetDuration
Atr_Duration_Initialize table: 0000019927FA6E40
Atr_Dropdown_AddPick table: 0000019927FA6E40 12 Hours 1 function: 000001992962A7C8
Atr_Dropdown_addPick table: 0000019927FA6E40 24 Hours 2 function: 000001992962A7C8
Atr_Dropdown_addPick table: 0000019927FA6E40 48 Hours 3 function: 000001992962A7C8
Atr_FindScan nil nil nil
Atr_ClearAll
Atr_ClearTop
Atr_HideElems table: 0000019929451C00
Atr_ClearList
AtrSearch:Init  nil nil nil
Atr_IsCompoundSearch
Atr_IsCompoundSearch false
*************** TABLE AtrSearch:Init ***************
table: 0000019951162600 (
   [current_page] => -1
   [searchText] => ""
   [origSearchText] 


and it goes on-and-on... dungeon que ****

**Comment by YouTubeNATE** [comment]
I will be trying out another addon: Auctioneer until this problem is rectified.

**Comment by FireSiku** [comment]
It sounds like you have "Show Debug Messages" enabled in the Auctionator options.

**Comment by jrob8577** [comment]
@YouTubeNATE , @FireSiku is correct, please ensure that "Show Debug Messages" is not enabled (there *might* be a bug where you have to toggle it off and on again, but I have not been able to reproduce since I last looked at it).
