### ISSUE TITLE
Scans only the first 17 pages

### ISSUE THREAD

**Issue by Scaver** [Auctionator/Auctionator#331]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

If I scan for an item, for sell or buy, only the first 17 pages will be scanned and than stopped at 17 of XX and nothing more happens.

## Steps to Reproduce

Do a scan for "Monelite Ore".

## Loaded Addons

A lot but no others for auctions.

## Back Trace (LUA Error Output)

Na errors.

**Comment by imKLM** [comment]
I had the same about 3 days ago (same day this issue was created) also for monelite ore, stopped at page 9 of 42, happened in both the sell and buy screens
