### ISSUE TITLE
Price showing

### ISSUE THREAD

**Issue by Aramorn** [Auctionator/Auctionator#332]
I don't now if I am doing something wrong or not, but it does not show the price of recipes. I do not mean the recipes which are already in my bags, but those I wish to make through enchanting and engineering. 
If I hover the mouse over them, in the enchanting/engineering ta,b it won't show me anything, besides the price of the materials, included in the recipe.
Please solve this so I can choose what enchanting scroll/engineering product to craft in order to sell and not do a manually search on the AH for the prices. 
Thanks in advance!

**Comment by jrob8577** [comment]
@Aramorn I'm not sure I understand the request here, can you elaborate?
