### ISSUE TITLE
Can not scan auction!

### ISSUE THREAD

**Issue by Zannalyn** [Auctionator/Auctionator#338]
I am not sure if it is my computer or if this is happening to others but when i go to do a full scan it takes a long time to get going and then doesn't do anything. Now i have tried to uninstall and reinstall the mod but it had no effect. Now i have never had this issue in the past... and i run quite a few different mods.... the issue has only started since the new expansion came out....

**Comment by bonesoul** [comment]
Probably because highly stocked AH

**Comment by valentin78** [comment]
yep, same issue several days in row
