### ISSUE TITLE
Feature Request : Max Button instead of Text

### ISSUE THREAD

**Issue by Nexxxy** [Auctionator/Auctionator#339]
Hi,

while the Stacks are saved or choosed via Menu, you always have to type in the max count of stacks you want to sell.

I added a Button to MaxOut the maximal amount of stacks what you are able to sell.
Additionally (you dont have to take this one) i added (due to my laziyness) 3 Buttons with maxes the current selected item with stacksize of 1,2 and 5s stacksize.

**Comment by Tore7778** [comment]
This is a great idea!

**Comment by ToddlesTore** [comment]
I like this idea!

**Comment by Nexxxy** [comment]
After that last chances to Auction-Creation-Prices i changed the other maxbuttons : 1,2,5 into 1,5,20

**Comment by Bubalazzy** [comment]
Thumbs up for this idea. This is actually what came here for - to open a feature request for "max full stacks" option.
Some time ago I was using another AH addon that had option to sale: 
1. stack you put in the  box
2. Max full stacks
3. Max full stacks + excess
4. Specific size [    ]
- I was always using option 2. here, and I miss that a lot. (ofc if you don't have enough for a full stack it should offer what you have dropped in the box)

Feature request two: 
that dropdown menu for choosing duration is so inconvenient. It would be better to be checkbox-dot style 
like:  (*)12h  ( )24h  ( )48h


@Nexxxy : can you share how to add that MaxOut button, please? I'm not much into .lua language, but if you give me some info what to add to which .lua I can do it.
