### ISSUE TITLE
LUA error preventing posting since today's patch

### ISSUE THREAD

**Issue by raysmith59** [Auctionator/Auctionator#342]
2x Auctionator\Auctionator-5.0.4.lua:3117: attempt to perform arithmetic on a nil value
Auctionator\Auctionator-5.0.4.lua:3117: in function `Atr_SetDepositText'
Auctionator\Auctionator-5.0.4.lua:3072: in function `Atr_UpdateUI_SellPane'
Auctionator\Auctionator-5.0.4.lua:3009: in function `Atr_UpdateUI'
Auctionator\Auctionator-5.0.4.lua:2847: in function `Atr_Idle'
Auctionator\Auctionator-5.0.4.lua:2796: in function `Atr_OnUpdate'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

Locals:
duration = 1
(*temporary) = nil
(*temporary) = 1
(*temporary) = <function> defined =[C]:-1
(*temporary) = <function> defined @TellMeWhen\Lib\LibDogTag-Unit-3.0\LibDogTag-Unit-3.0.lua:55
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = "AUCTION_HOUSE_SCRIPT_DEPRECATED"
(*temporary) = "attempt to perform arithmetic on a nil value"
_ = "Mechanical Axebeak"
ZT = <function> defined @Auctionator\AuctionatorLocalize.lua:15
zc = <table> {
 IsEnglishLocale = <function> defined @Auctionator\AuctionatorLocalize.lua:63
 msg_red = <function> defined @Auctionator\zcUtils.lua:570
 TrimBrackets = <function> defined @Auctionator\zcUtils.lua:955
 tallyAdd = <function> defined @Auctionator\zcUtils.lua:1108
 msg_yellow = <function> defined @Auctionator\zcUtils.lua:572
 msg = <function> defined @Auctionator\zcUtils.lua:699
 GetArrayElemOrFirst = <function> defined @Auctionator\zcUtils.lua:136
 NumToBool = <function> defined @Auctionator\zcUtils.lua:524
 printmem = <function> defined @Auctionator\zcUtils.lua:1018
 ParseBattlePetLink = <function> defined @Auctionator\zcUtils.lua:417
 ShowHide = <function> defined @Auctionator\zcUtils.lua:33
 StringStartsWith = <function> defined @Auctionator\zcUtils.lua:892
 StringEndsWith = <function> defined @Auctionator\zcUtils.lua:872
 round = <function> defined @Auctionator\zcUtils.lua:564
 CopyDeep = <function> defined @Auctionator\zcUtils.lua:984
 ClearTable = <function> defined @Auctionator\zcUtils.lua:975
 CheckDeferredCall = <function> defined @Auctionator\zcUtils.lua:320
 priceToMoneyString = <function> defined @Auctionator\zcUtils.lua:803
 tallyPrint = <function> defined @Auctionator\zcUtils.lua:1120
 TrimQuotes = <function> defined @Auctionator\zcUtils.lua:935
 GetArrayElemOrNil = <function> defined @Auctionator\zcUtils.lua:151
 BoolToNum = <function> defined @Auctionator\zcUtils.lua:514
 If = <function> defined @Auctionator\zcUtils.lua:107
 periodic = <function> defined @Auctionator\zcUtils.lua:343
 Min = <function> defined @Auctionator\zcUtils.lua:77
 msg_pink = <function> defined @Auctionator\zcUtils.lua:571
 SetTextIf = <function> defined @Auctionator\zcUtils.lua:44
 QuoteString = <function> defined @Auctionator\zcUtils.lua:923
 msg_str = <function> defined @Auctionator\zcUtils.lua:589
 ItemNamefromLink = <function> defined @Auctionator\zcUtils.lua:447
 enc64 = <function> defined @Auctionator\zcUtils.lua:201
 Val = <function> defined @Auctionator\zcUtils.lua:55
 IsBattlePetLink = <function> defined @Auctionator\zcUtils.lua:409
 msg_ex = <function> defined @Auctionator\zcUtils.lua:708
 printableLink = <function> defined @Auctionator\zcUtils.lua:1005
 PrintTable = <function> defined @Auctionator\zcUtils.lua:373
 StringContains = <function> defined @Auctionator\zcUtils.lua:854
 StringSame = <function> defined @Auctionator\zcUtils.lua:836
 PullItemIntoMemory = <function> defined @Auctionator\zcUtils.lua:482
 priceToString = <function> defined @Auctionator\zcUtils.lua:767
 PrintKeysSorted = <function> defined @Auctionator\zcUtils.lua:118
 val2gsc = <function> defined @Auctionator\zcUtils.lua:749
 Negate = <function> defined @Auctionator\zcUtils.lua:534
 IsTextQuoted = <function> defined @Auctionator\zcUtils.lua:916
 BoolToString = <function> defined @Add

**Comment by prsauer** [comment]
Looks like blizz renamed some functions

StartAuction =>
PostAuction(stackStartingPrice, stackBuyoutPrice, duration, gJustPosted.StackSize, gJustPosted.NumStacks);

CalculateAuctionDeposit =>
local start   = MoneyInputFrame_GetCopper(Atr_StartingPrice);
local buyout  = MoneyInputFrame_GetCopper(Atr_StackPrice);
local deposit1 = GetAuctionDeposit (duration, start, buyout) / auctionCount;

can post a PR later today

**Comment by raysmith59** [comment]
I made those changes locally to test (and so I could actually list auctions, I'm a bit too dependent on Auctionator), now I'm getting this one.  It only seems to prevent showing of the deposit price, though, I'm able to list auctions.

1x Auctionator\Auctionator-5.0.4.lua:3122: Usage: GetAuctionDeposit(runTime, minBid, buyoutPrice, [itemCount, numStacks])
[C]: in function `GetAuctionDeposit'
Auctionator\Auctionator-5.0.4.lua:3122: in function `Atr_SetDepositText'
Auctionator\Auctionator-5.0.4.lua:3073: in function `Atr_UpdateUI_SellPane'
Auctionator\Auctionator-5.0.4.lua:3010: in function `Atr_UpdateUI'
Auctionator\Auctionator-5.0.4.lua:2848: in function `Atr_Idle'
Auctionator\Auctionator-5.0.4.lua:2797: in function `Atr_OnUpdate'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

Locals:
(*temporary) = 1
(*temporary) = nil
(*temporary) = nil

**Comment by prsauer** [comment]
can take a look when I get back home, I was able to list mine with no errors

**Comment by StaindRcks** [comment]
Date: 2018-08-28 10:51:28
ID: 6
Error occured in: Global
Count: 1
Message: ..\FrameXML\StaticPopup.lua line 4447:
   bad argument #1 to 'SetFormattedText' (string expected, got nil)
Debug:
   [C]: ?
   [C]: SetFormattedText()
   ..\FrameXML\StaticPopup.lua:4447: StaticPopup_Show()
   ..\FrameXML\UIParent.lua:1814:
      ..\FrameXML\UIParent.lua:1090
   [C]: CalculateAuctionDeposit()
   Auctionator\Auctionator.lua:3117: Atr_SetDepositText()
   Auctionator\Auctionator.lua:3072: Atr_UpdateUI_SellPane()
   Auctionator\Auctionator.lua:3009: Atr_UpdateUI()
   Auctionator\Auctionator.lua:2847: Atr_Idle()
   Auctionator\Auctionator.lua:2796: Atr_OnUpdate()
   [string "*:OnUpdate"]:1:
      [string "*:OnUpdate"]:1
Locals:

AddOns:
  Swatter, v7.7.6000 (SwimmingSeadragon)
  AngryKeystones, v
  AtlasLoot, vv8.07.13
  AtlasLootBurningCrusade, vv8.07.13
  AtlasLootCataclysm, vv8.07.13
  AtlasLootClassic, vv8.07.13
  AtlasLootLegion, vv8.07.13
  AtlasLootMistsofPandaria, vv8.07.13
  AtlasLootWarlordsofDraenor, vv8.07.13
  AtlasLootWrathoftheLichKing, vv8.07.13
  Auctionator, v5.0.4
  AzerothAutoPilot, v0.162
  DBMCore, v8.0.4
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Dominos, v8.0.6
  DominosCast, v
  DominosConfig, v
  DominosEncounter, v
  DominosProgress, v
  DominosRoll, v
  ExRT, v3940
  GatherMate2, v1.43.3
  GTFO, v4.46.4
  HandyNotes, vv1.5.3
  HandyNotesBattleForAzerothTreasures, v1
  Informant, v7.7.6000 (SwimmingSeadragon)
  Oilvl, v8.0.1
  OmniCC, v8.0.1
  OmniCCConfig, v
  Pawn, v2.2.27
  Postal, vv3.6.0
  RaiderIO, v8.0.1 (v201808270600)
  RaiderIODBUSA, v
  RaiderIODBUSH, v
  SimPermut, v1.15.0
  Simulationcraft, v1.10.6
  Skada, v1.7.5
  Stubby, v7.7.6000 (SwimmingSeadragon)
  TidyPlatesThreatPlates, v9.0.12
  TomTom, vv80001-1.0.2
  TradeSkillMaster, vv4.2.1
  TradeSkillMasterAppHelper, vv4.0
  WeakAuras, v2.7.3
  WorldQuestsList, v78
  BlizRuntimeLib_enUS v8.0.1.80000 <none>
  (ck=4a0)

**Comment by StaindRcks** [comment]
Sell button does not work. Nor do some other functions since the update. It's widespread.

**Comment by prsauer** [comment]
Ah. I was only posting a couple quick items before I left for the day -- if you could post all the buttons you've gotten errors on though I'll take a look once I get back.

**Comment by jrob8577** [comment]
This should be fixed in 5.0.5, please re-open if you continue to see issues!
