### ISSUE TITLE
Sell button no longer works since latest patch

### ISSUE THREAD

**Issue by Emberofdeath** [Auctionator/Auctionator#343]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

_Please include a brief description of the bug, including what you were doing, and when it occurred._

## Steps to Reproduce

_Include the steps I would need to follow to reproduce the bug._

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by prsauer** [comment]
see https://github.com/Auctionator/Auctionator/issues/342

**Comment by jrob8577** [comment]
Duplicates #342
