### ISSUE TITLE
Add on no longer allows you to sell items, gives error

### ISSUE THREAD

**Issue by StaindRcks** [Auctionator/Auctionator#345]
Date: 2018-08-28 10:57:47
ID: 6
Error occured in: Global
Count: 1
Message: ..\FrameXML\StaticPopup.lua line 4447:
   bad argument #1 to 'SetFormattedText' (string expected, got nil)
Debug:
   [C]: ?
   [C]: SetFormattedText()
   ..\FrameXML\StaticPopup.lua:4447: StaticPopup_Show()
   ..\FrameXML\UIParent.lua:1814:
      ..\FrameXML\UIParent.lua:1090
   [C]: CalculateAuctionDeposit()
   Auctionator\Auctionator.lua:3117: Atr_SetDepositText()
   Auctionator\Auctionator.lua:3072: Atr_UpdateUI_SellPane()
   Auctionator\Auctionator.lua:3009: Atr_UpdateUI()
   Auctionator\Auctionator.lua:2847: Atr_Idle()
   Auctionator\Auctionator.lua:2796: Atr_OnUpdate()
   [string "*:OnUpdate"]:1:
      [string "*:OnUpdate"]:1
Locals:

**Comment by tyrannicalduck** [comment]
Same error that I'm getting every time. Here's a picture if that helps at all, even if it just the same thing as his text. [https://lh3.googleusercontent.com/tfCsj2X2WBmUwQ9IdzmXR1I8RblAEsSKYxVcjQGMJYhXYwGDx6ilw2DMfeiOIn_i1u10PQxXsr4N-VqGJLvVwNj8PjHUP-xsZmfr_OKOQpTBpOTKWOLImi4ninb6_JwdDh1vWpQDWJY6WlJthwznVpanaAC4z9V1Rwyq2rsWh6YUzTfBJPZNoxvG1xBN5jq8_wDzj53J12uWvRw0pEjY-B_ZhD20hyTUzFclIMyJgDTSKxpanZDD-0mBvNVb94bw0Sw39dc7ndyvDePFKCmdZqQqSeo82Qmu1ERv0VldT_5GiYVrwOR8aqUEfwXWGKAupTpFM_W80H0XlYzBm9q6Zg2MRjaapoZS06yhh9jZzW6vqILJZw3lRe4zV103UrbWAFMYJWup8MeA19_L6wPdKByCC-aIGqjRMU9-6tK4I-yMh9LteCZry0xcRHT2a6q4Zo3RBU2sUW9zVKLEaNRBwD6P7gMVaXss_klShPlsv9jkS1WeFzgWT7xe28p4UaK9bJf9aobiBG3I-ZckhqFwBUxjK5exV9nQalS_MYVfqcFQV1VNfMqryp4sj0Z-aIXFvQY_M9tNhTjur0q0Vx6PxXhJBuxcSTC66v8pV3B6-tZdkqLsiYSiLS1OWRKZ6ow=w493-h300-no](url)

**Comment by JaredTS486** [comment]
I was able to sell some items just now. The only item I was unable to sell was https://www.wowhead.com/item=161948

**Comment by KyraindaKT** [comment]
I am not getting an error, but the "CREATE AUCTION" button does nothing.

**Comment by Anduviel** [comment]
not getting any error, but cannot sell anything, because ''CREATE AUCTION"" button is not working,

**Comment by bonesoul** [comment]
same here.

**Comment by spiritwolves** [comment]
Same for me. My "buy" tab is working but "sell" tab isn't.

**Comment by jrob8577** [comment]
@StaindRcks @KyraindaKT @Anduviel @bonesoul @spiritwolves Released 5.0.5 this morning, can you please let me know if this fixed the issues you identified? (Thanks again @praydog)

**Comment by Anduviel** [comment]
My post was shortly after the release was released , before everything was ok

**Comment by jrob8577** [comment]
@Anduviel Thanks I'll take a look (late) tonight.

**Comment by gemmaweirs** [comment]
These are the bugs I got when I placed an item to be sold and when I clicked on the button to sell. The button doesn't work. 

1x Auctionator\Auctionator-5.0.5.lua:1583: attempt to call global 'PostAuction' (a nil value)
Auctionator\Auctionator-5.0.5.lua:1583: in function `Atr_CreateAuction_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals:
duration = 3
stackStartingPrice = 8597500
stackBuyoutPrice = 9050000
(*temporary) = nil
(*temporary) = 8597500
(*temporary) = 9050000
(*temporary) = 3
(*temporary) = 1
(*temporary) = 1
(*temporary) = "attempt to call global 'PostAuction' (a nil value)"
gAtr_SellTriggeredByAuctionator = true
gJustPosted = <table> {
 StackSize = 1
 ItemName = "Warport Short Bow of the Peerless"
 NumStacks = 1
 BuyoutPrice = 9050000
 ItemLink = "|cff1eff00|Hitem:159491::::::::115:267:512::2:4796:1689:114:::|h[Warport Short Bow of the Peerless]|h|r"
}
gCurrentPane = <table> {
 activeSearch = <table> {
 }
 hlistScrollOffset = 0
 activeScan = <table> {
 }
 fullStackSize = 1
 totalItems = 1
 currIndex = 1
 UINeedsUpdate = false
 SS_hilite_itemName = "Warport Short Bow of the Peerless"
}
zc = <table> {
 IsEnglishLocale = <function> defined @Auctionator\AuctionatorLocalize.lua:63
 msg_red = <function> defined @Auctionator\zcUtils.lua:570
 TrimBrackets = <function> defined @Auctionator\zcUtils.lua:955
 tallyAdd = <function> defined @Auctionator\zcUtils.lua:1108
 msg_yellow = <function> defined @Auctionator\zcUtils.lua:572
 msg = <function> defined @Auctionator\zcUtils.lua:699
 GetArrayElemOrFirst = <function> defined @Auctionator\zcUtils.lua:136
 NumToBool = <function> defined @Auctionator\zcUtils.lua:524
 printmem = <function> defined @Auctionator\zcUtils.lua:1018
 ParseBattlePetLink = <function> defined @Auctionator\zcUtils.lua:417
 ShowHide = <function> defined @Auctionator\zcUtils.lua:33
 StringStartsWith = <function> defined @Auctionator\zcUtils.lua:892
 StringEndsWith = <function> defined @Auctionator\zcUtils.lua:872
 round = <function> defined @Auctionator\zcUtils.lua:564
 CopyDeep = <function> defined @Auctionator\zcUtils.lua:984
 ClearTable = <function> defined @Auctionator\zcUtils.lua:975
 CheckDeferredCall = <function> defined @Auctionator\zcUtils.lua:320
 priceToMoneyString = <function> defined @Auctionator\zcUtils.lua:803
 tallyPrint = <function> defined @Auctionator\zcUtils.lua:1120
 TrimQuotes = <function> defined @Auctionator\zcUtils.lua:935
 GetArrayElemOrNil = <function> defined @Auctionator\zcUtils.lua:151
 BoolToNum = <function> defined @Auctionator\zcUtils.lua:514
 If = <function> defined @Auctionator\zcUtils.lua:107
 periodic = <function> defined @Auctionator\zcUtils.lua:343
 Min = <function> defined @Auctionator\zcUtils.lua:77
 msg_pink = <function> defined @Auctionator\zcUtils.lua:571
 SetTextIf = <function> defined @Auctionator\zcUtils.lua:44
 QuoteString = <function> defined @Auctionator\zcUtils.lua:923
 msg_str = <function> defined @Auctionator\zcUtils.lua:589
 ItemNamefromLink = <function> defined @Auctionator\zcUtils.lua:447
 enc64 = <function> defined @Auctionator\zcUtils.lua:201
 Val = <function> defined @Auctionator\zcUtils.lua:55
 IsBattlePetLink = <function> defined @Auctionator\zcUtils.lua:409
 msg_ex = <function> defined @Auctionator\zcUtils.lua:708
 printableLink = <function> defined @Auctionator\zcUtils.lua:1005
 PrintTable = <function> defined @Auctionator\zcUtils.lua:373
 StringContains = <function> defined @Auctionator\zcUtils.lua:854
 StringSame = <function> defined @Auctionator\zcUtils.lua:836
 PullItemIntoMemory = <function> defined @Auctionator\zcUtils.lua:482
 priceToString = <function> defined @Auctionator\zcUtils.lua:767
 PrintKeysSorted = <function> defined @Auctionator\zcUtils.lua:118
 val2gsc = <function> defined

1x Auctionator\Auctionator-5.0.5.lua:3118: attempt to call global 'GetAuctionDeposit' (a nil value)
Auctionator\Auctionator-5.0.5.lua:3118: in function `Atr_SetDepositText'
Auctionator\Auctionator-5.0.5.lua:3074: in function `Atr_UpdateUI_SellPane'
Auctionator\Auctionator-5.0.5.lua:3011: in function `Atr_UpdateUI'
Auctionator\Auctionator-5.0.5.lua:2849: in function `Atr_Idle'
Auctionator\Auctionator-5.0.5.lua:2798: in function `Atr_OnUpdate'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

Locals:
duration = 3
(*temporary) = nil
(*temporary) = 3
(*temporary) = 8597500
(*temporary) = 9050000
(*temporary) = 1
(*temporary) = 1
(*temporary) = "attempt to call global 'GetAuctionDeposit' (a nil value)"
_ = "Warport Short Bow of the Peerless"
ZT = <function> defined @Auctionator\AuctionatorLocalize.lua:15
zc = <table> {
 IsEnglishLocale = <function> defined @Auctionator\AuctionatorLocalize.lua:63
 msg_red = <function> defined @Auctionator\zcUtils.lua:570
 TrimBrackets = <function> defined @Auctionator\zcUtils.lua:955
 tallyAdd = <function> defined @Auctionator\zcUtils.lua:1108
 msg_yellow = <function> defined @Auctionator\zcUtils.lua:572
 msg = <function> defined @Auctionator\zcUtils.lua:699
 GetArrayElemOrFirst = <function> defined @Auctionator\zcUtils.lua:136
 NumToBool = <function> defined @Auctionator\zcUtils.lua:524
 printmem = <function> defined @Auctionator\zcUtils.lua:1018
 ParseBattlePetLink = <function> defined @Auctionator\zcUtils.lua:417
 ShowHide = <function> defined @Auctionator\zcUtils.lua:33
 StringStartsWith = <function> defined @Auctionator\zcUtils.lua:892
 StringEndsWith = <function> defined @Auctionator\zcUtils.lua:872
 round = <function> defined @Auctionator\zcUtils.lua:564
 CopyDeep = <function> defined @Auctionator\zcUtils.lua:984
 ClearTable = <function> defined @Auctionator\zcUtils.lua:975
 CheckDeferredCall = <function> defined @Auctionator\zcUtils.lua:320
 priceToMoneyString = <function> defined @Auctionator\zcUtils.lua:803
 tallyPrint = <function> defined @Auctionator\zcUtils.lua:1120
 TrimQuotes = <function> defined @Auctionator\zcUtils.lua:935
 GetArrayElemOrNil = <function> defined @Auctionator\zcUtils.lua:151
 BoolToNum = <function> defined @Auctionator\zcUtils.lua:514
 If = <function> defined @Auctionator\zcUtils.lua:107
 periodic = <function> defined @Auctionator\zcUtils.lua:343
 Min = <function> defined @Auctionator\zcUtils.lua:77
 msg_pink = <function> defined @Auctionator\zcUtils.lua:571
 SetTextIf = <function> defined @Auctionator\zcUtils.lua:44
 QuoteString = <function> defined @Auctionator\zcUtils.lua:923
 msg_str = <function> defined @Auctionator\zcUtils.lua:589
 ItemNamefromLink = <function> defined @Auctionator\zcUtils.lua:447
 enc64 = <function> defined @Auctionator\zcUtils.lua:201
 Val = <function> defined @Auctionator\zcUtils.lua:55
 IsBattlePetLink = <function> defined @Auctionator\zcUtils.lua:409
 msg_ex = <function> defined @Auctionator\zcUtils.lua:708
 printableLink = <function> defined @Auctionator\zcUtils.lua:1005
 PrintTable = <function> defined @Auctionator\zcUtils.lua:373
 StringContains = <function> defined @Auctionator\zcUtils.lua:854
 StringSame = <function> defined @Auctionator\zcUtils.lua:836
 PullItemIntoMemory = <function> defined @Auctionator\zcUtils.lua:482
 priceToString = <function> defined @Auctionator\zcUtils.lua:767
 PrintKeysSorted = <function> defined @Auctionator\zcUtils.lua:118
 val2gsc = <function> defined @Auctionator\zcUtils.lua:749
 Negate = <function> defined @Auctionator\zcUtils.lua:534
 IsTextQuoted = <function> defined @Auctionator\zcUtils.lua:916
 BoolToString = <function> defined @Auctionator\zcUtils.lua:504
 msg_badErr = <function> defined @Auctionator\zcUtils.lua:606
 msg_color = <function> defined @Auctionator\zcUtils.lua:576
 HSV2RGB

**Comment by KyraindaKT** [comment]
it seems to be fixed now....

**Comment by doctorzoyd** [comment]
Still have the problem. No error message for me but the "create auctions" button doesen't work!

**Comment by Nevcairiel** [comment]
You'll need to wait until this weeks client patch (27481) was deployed to your region. It should happen with Weekly Maintenance.

**Comment by jrob8577** [comment]
Closing; please reopen if this issue persists.
