### ISSUE TITLE
After last update 5.0.5, the button "Create Auction" dosen't works anymore. It doesen't create any auctions after putting items in AH.

### ISSUE THREAD

**Issue by doctorzoyd** [Auctionator/Auctionator#346]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

_Please include a brief description of the bug, including what you were doing, and when it occurred._

## Steps to Reproduce

_Include the steps I would need to follow to reproduce the bug._

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by zubizaretta** [comment]
yes +++ not working ^^

**Comment by andytri** [comment]
I just enter game,then use AH,but it does not work.
I reload addons it also does not work.Here is error logs:
`3x Auctionator\Auctionator-5.0.5.lua:1583: attempt to call global 'PostAuction' (a nil value)
Auctionator\Auctionator-5.0.5.lua:1583: in function `Atr_CreateAuction_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals:
duration = 3
stackStartingPrice = 4752375
stackBuyoutPrice = 5002500
(*temporary) = nil
(*temporary) = 4752375
(*temporary) = 5002500
(*temporary) = 3
(*temporary) = 1
(*temporary) = 18
(*temporary) = "attempt to call global 'PostAuction' (a nil value)"
gAtr_SellTriggeredByAuctionator = true
gJustPosted = <table> {
 StackSize = 1
 ItemName = "合约：艾泽拉斯的勇士"
 NumStacks = 18
 BuyoutPrice = 5002500
 ItemLink = "|cffffffff|Hitem:153668::::::::120:253::::::|h[合约：艾泽拉斯的勇士]|h|r"
}
gCurrentPane = <table> {
 activeSearch = <table> {
 }
 hlistScrollOffset = 0
 activeScan = <table> {
 }
 fullStackSize = 20
 totalItems = 18
 currIndex = 1
 UINeedsUpdate = false
 SS_hilite_itemName = "合约：艾泽拉斯的勇士"
}
zc = <table> {
 IsEnglishLocale = <function> defined @Auctionator\AuctionatorLocalize.lua:63
 msg_red = <function> defined @Auctionator\zcUtils.lua:570
 TrimBrackets = <function> defined @Auctionator\zcUtils.lua:955
 tallyAdd = <function> defined @Auctionator\zcUtils.lua:1108
 msg_yellow = <function> defined @Auctionator\zcUtils.lua:572
 msg = <function> defined @Auctionator\zcUtils.lua:699
 GetArrayElemOrFirst = <function> defined @Auctionator\zcUtils.lua:136
 NumToBool = <function> defined @Auctionator\zcUtils.lua:524
 printmem = <function> defined @Auctionator\zcUtils.lua:1018
 ParseBattlePetLink = <function> defined @Auctionator\zcUtils.lua:417
 ShowHide = <function> defined @Auctionator\zcUtils.lua:33
 StringStartsWith = <function> defined @Auctionator\zcUtils.lua:892
 StringEndsWith = <function> defined @Auctionator\zcUtils.lua:872
 round = <function> defined @Auctionator\zcUtils.lua:564
 CopyDeep = <function> defined @Auctionator\zcUtils.lua:984
 ClearTable = <function> defined @Auctionator\zcUtils.lua:975
 CheckDeferredCall = <function> defined @Auctionator\zcUtils.lua:320
 priceToMoneyString = <function> defined @Auctionator\zcUtils.lua:803
 tallyPrint = <function> defined @Auctionator\zcUtils.lua:1120
 TrimQuotes = <function> defined @Auctionator\zcUtils.lua:935
 GetArrayElemOrNil = <function> defined @Auctionator\zcUtils.lua:151
 BoolToNum = <function> defined @Auctionator\zcUtils.lua:514
 If = <function> defined @Auctionator\zcUtils.lua:107
 periodic = <function> defined @Auctionator\zcUtils.lua:343
 Min = <function> defined @Auctionator\zcUtils.lua:77
 msg_pink = <function> defined @Auctionator\zcUtils.lua:571
 SetTextIf = <function> defined @Auctionator\zcUtils.lua:44
 QuoteString = <function> defined @Auctionator\zcUtils.lua:923
 msg_str = <function> defined @Auctionator\zcUtils.lua:589
 ItemNamefromLink = <function> defined @Auctionator\zcUtils.lua:447
 enc64 = <function> defined @Auctionator\zcUtils.lua:201
 Val = <function> defined @Auctionator\zcUtils.lua:55
 IsBattlePetLink = <function> defined @Auctionator\zcUtils.lua:409
 msg_ex = <function> defined @Auctionator\zcUtils.lua:708
 printableLink = <function> defined @Auctionator\zcUtils.lua:1005
 PrintTable = <function> defined @Auctionator\zcUtils.lua:373
 StringContains = <function> defined @Auctionator\zcUtils.lua:854
 StringSame = <function> defined @Auctionator\zcUtils.lua:836
 PullItemIntoMemory = <function> defined @Auctionator\zcUtils.lua:482
 priceToString = <function> defined @Auctionator\zcUtils.lua:767
 PrintKeysSorted = <function> defined @Auctionator\zcUtils.lua:118
 val2gsc = <function> defined @Auct`

**Comment by Nevcairiel** [comment]
You'll need to wait until this weeks client patch (27481) was deployed to your region. It should happen with Weekly Maintenance.

**Comment by andytri** [comment]
OK.My region is China,it will update on Thursday.

**Comment by jrob8577** [comment]
Closing; please re-open if this is not working after the update.
