### ISSUE TITLE
LUA error (integer overflow) when trying to list an expensive BoE drop

### ISSUE THREAD

**Issue by raysmith59** [Auctionator/Auctionator#352]
The most recent posted price was 225K:

1x integer overflow attempting to store 2250000000
[C]: in function `GetAuctionDeposit'
Auctionator\Auctionator-5.0.5.lua:3118: in function `Atr_SetDepositText'
Auctionator\Auctionator-5.0.5.lua:3074: in function `Atr_UpdateUI_SellPane'
Auctionator\Auctionator-5.0.5.lua:3011: in function `Atr_UpdateUI'
Auctionator\Auctionator-5.0.5.lua:2849: in function `Atr_Idle'
Auctionator\Auctionator-5.0.5.lua:2798: in function `Atr_OnUpdate'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

Locals:
(*temporary) = 1
(*temporary) = 2250000000
(*temporary) = 2250000000
(*temporary) = 1
(*temporary) = 1

**Comment by SmilingSparrow** [comment]
I am getting the basically the same error.  When posting for 280k I get the lua error:


Message: integer overflow attempting to store 2659990500
Time: Fri Aug 31 22:33:02 2018
Count: 3
Stack: integer overflow attempting to store 2659990500
[C]: in function `GetAuctionDeposit'
Interface\AddOns\Auctionator\Auctionator.lua:3118: in function `Atr_SetDepositText'
Interface\AddOns\Auctionator\Auctionator.lua:3074: in function `Atr_UpdateUI_SellPane'
Interface\AddOns\Auctionator\Auctionator.lua:3011: in function `Atr_UpdateUI'
Interface\AddOns\Auctionator\Auctionator.lua:2849: in function `Atr_Idle'
Interface\AddOns\Auctionator\Auctionator.lua:2798: in function `Atr_OnUpdate'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

Locals: (*temporary) = 1
(*temporary) = 2659990500
(*temporary) = 2799990000
(*temporary) = 1
(*temporary) = 1
