### ISSUE TITLE
Auctionator Ignoriong Default Auction Duration Setting

### ISSUE THREAD

**Issue by mbrad0529** [Auctionator/Auctionator#358]
While using Auctionator version 5.0.5 I have been having issues posting items for sale, namely that the Duration option seems to be set to Custom and is ignoring the setting in the Auctionator configuration, requiring me to manually check the option for duration to either 12h, 24h, or 48h before I can post the item.

## Steps to Reproduce

Using Auctionator v5.0.5, in the Addon Settings (Which I am accessing through Interface->Addons on the in game menu) for Auctionator, the Basic Options menu there is a set of radio buttons labeled "Default Auction Duration." Mine is currently set to 12 Hours, however when I visit the in-game Auction House and attempt to post an auction through the Sell tab the duration will instead be set to "Custom" and will prevent the auction being posted until I manually change it to either 12h, 24h, or 48h. I have also attempted to set the Auction setting default duration to "None" as well, and the issue still remains.

## Loaded Addons

!DetailedCloudsFix
_NPCScan.Overlay
ACP
AdvancedInterfaceOptions
afkquit
AHShowBid
AskMrRobot
AtlasLoot
Auctionator
AuctionPerUnit
Azeroth Auto Pilot
BagSync
BonusRollPreview
Boomerang
BOPCraftConfirm
CanIMogIt
ChatTabDockLock
!ClassColors
Classic Quest Log
CleanBossButton
CoolLine
CoolLine-ICD
DisableMapArrow
Dresser
Dying
ExtVendor
FishingBuddy
Foglight
GTFO
GuildMemberStatus
GuildNews
HandyNotes
HandyNotes_BattleForAzerothAchievments
HandyNotes_BattleForAzerothTreasures
HandyNotes_FieldPhotographer
HandyNotes_AzerothsTopTunes
HandyNotes_CamelFigurines
HandyNotes_Directions
HandyNotes_DungeonLocations
HandyNotes_LegionTreasures
HandyNotes_PandariaTreasures
HandyNotes_TimelessIsleChests
Higher HotKey
ImprovedStableFrame
InboxMailBag
InstanceLockCompare
InteractiveWormholes
LargerMacroIconSelection
LibStrataFix
LookingForGroup
LookingForGroup_Bindings
LookingForGroup_Broker
LookingForGroup_Event
LookingForGroup_Hook
LookingForGroup_Icon
LookingForGroup_SF
MailAttachmentCount
MasterPlanA
MikScrollingBattleText
ModelPique
MogIt
Molinari
ncHoverName
ncKillingBlow
NPCScan
Pawn
PersonalLootHelper
Postal
PGFinder
Skadacfi
RealmHopAssist
Routes
ZoneText
Simulationcraft
Skada
SpeedyLoad
Storyline
StrataFix
StupidBuffs2
TheUndermineJournal
TidyPlatesContinued
TidyPlatesContinuedHub
TidyPlatesContinuedWidgets
TidyPlatesContinued_Alvara
TidyPlatesContinued_Graphite
TidyPlatesContinued_Grey
TidyPlatesContinued_Neon
TidyPlatesContinued_Quatre
TidyPlatesContinued_Roth
TidyPlatesContinued_Slim_Horizontal
TidyPlatesContinued_Slim_Vertical
TidyPlatesContinued_BlizzardPlates
TidyPlatesContinued_ClassicPlates
TidyPlatesContinued_Simple
TidyPlatesContinued_Renaitre
TomTom
WeakAuras
WhoWhisperedMe
WorldFlightMap
!WorldFlightMapLoader
DejaCharacterStats
TradeSkillMaster
TradeSkillMaster_AppHelper
AddOnSkins
ElvUI_ExtraDataTexts
ElvUI_PriestAoe
ElvUI_ActionBar_Panels
ElvUI_ChannelAlerts
ElvUI_CoolLine
ElvUI_Enhanced
ElvUI_EverySecondCounts
ElvUI_DataConfig
ElvUI_LocPlus
ElvUI_PushToActionBar
ElvUI_SystemDT
ElvUI_VisualAuraTimers
ElvUI_CustomTweaks
ElvUI_TB
RETabBinder
iShadow
ElvUI
DBM-Core
DBM-Archaeology
DBM-DefaultSkin
DBM-SpellTimers
DBM-StatusBarTimers
ChatTextures

**Comment by jrob8577** [comment]
@mbrad0529 I'm unable to reproduce. This is a per character setting in Auctionator, I'm wondering if the value for this variable somehow got corrupted in your `SavedVariables`. Could you paste the contents of the following file here (this path is from a Mac, not sure of the location on a Windows machine though I imagine the filesystem is essentially the same once you get into the WoW folder)?
```
/Applications/World of Warcraft/WTF/Account/ACCOUNT-NAME/REALM-NAME/CHARACTER-NAME/SavedVariables
```

**Comment by SacredDuckwhale** [comment]
I've been encountering the same issue. ```AUCTIONATOR_DEF_DURATION``` is ```"L"``` - but the problem seems to be that the duration changes to "Custom" whenever an item is dragged into the Sell tab. Simultaneously, this Lua error is raised, twice for each time I drag the item there:

```3177x Auctionator\Auctionator-5.0.5.lua:3118: Usage: GetAuctionDeposit(runTime, minBid, buyoutPrice, [itemCount, numStacks])
[C]: in function `GetAuctionDeposit'
Auctionator\Auctionator-5.0.5.lua:3118: in function `Atr_SetDepositText'
Auctionator\Auctionator-5.0.5.lua:4490: in function `func'
FrameXML\UIDropDownMenu.lua:935: in function `UIDropDownMenuButton_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>
[C]: in function `Click'
AuctionPerUnit\AuctionPerUnit.lua:13: in function <AuctionPerUnit\AuctionPerUnit.lua:10>
[C]: in function `ClickAuctionSellItemButton'
Auctionator\Auctionator-5.0.5.lua:1456: in function `Atr_ClickAuctionSellItemButton'
Auctionator\Auctionator-5.0.5.lua:1482: in function <Auctionator\Auctionator.lua:1479>

Locals:
(*temporary) = nil
(*temporary) = 0
(*temporary) = 0
(*temporary) = 10
(*temporary) = 12
```

```UIDropDownMenu_GetSelectedValue(Atr_Duration)``` returns ```nil``` while the dropdown menu is set to "Custom". Changing it to a valid value manually is possible, and a correct value will be returned, but as soon as the next item is dragged into the sell tab (even if it's the same item), the menu resets to the invalid/Custom option.

Since I'm lazy and didn't want to spend more time troubleshooting this issue, I simply added this workaround to the bottom of the ```Atr_UpdateUI_SellPane``` function:

```
    if(not UIDropDownMenu_GetSelectedValue(_G["Atr_Duration"])) then -- Duration has somehow reset (don't ask me why)...
	Auctionator.Debug.Message( 'Duration for Sell tab dropdown is invalid -> Resetting it...' )
	Atr_ResetDuration()
  end
```

**Comment by mbrad0529** [comment]
Apologies for not responding sooner @jrob8577 

Here is my Auctionator.lua Saved Variables from the character having the issue:


AUCTIONATOR_SHOW_ST_PRICE = 0
AUCTIONATOR_ENABLE_ALT = 1
AUCTIONATOR_OPEN_FIRST = 2
AUCTIONATOR_OPEN_BUY = 0
AUCTIONATOR_DEF_DURATION = "S"
AUCTIONATOR_SHOW_TIPS = 1
AUCTIONATOR_V_TIPS = 1
AUCTIONATOR_A_TIPS = 1
AUCTIONATOR_D_TIPS = 1
AUCTIONATOR_SHIFT_TIPS = 1
AUCTIONATOR_DE_DETAILS_TIPS = 4
AUCTIONATOR_DEFTAB = 0

I will attempt the fix posted by @SacredDuckwhale later and let you know if it works.

**Comment by SacredDuckwhale** [comment]
It's not really a fix, more like a (quick-and-dirty) workaround. I still get the same Lua error message, but I can use the addon again and that's good enough for the time being. I don't have time to investigate further right now, but if someone finds the cause of the problem I'd obviously prefer a proper solution :)
