### ISSUE TITLE
fishing

### ISSUE THREAD

**Issue by qwasymotto** [Auctionator/Auctionator#360]
Please include as much of the following information as possible to help me fix the bug:blizzard has been telling people that your addon has been causing an internal bag error when people fish. i highly doubt it though. its when you catch two fish and it only gives you one and the other vanishes. just wanted to let you know if you wanted to double check. the GM was very eager to get rid of me.

## Brief Description of Bug

_Please include a brief description of the bug, including what you were doing, and when it occurred._

## Steps to Reproduce

_Include the steps I would need to follow to reproduce the bug._

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by jrob8577** [comment]
I can't find anything on this in the forums, not sure how to reproduce to test. Closing for now until more detail is available. 🤷‍♂️
