### ISSUE TITLE
Scanning for Enchants finds only the materials needed not the enchant itself

### ISSUE THREAD

**Issue by yoshimo** [Auctionator/Auctionator#365]
I was browsing through the guilds crafter recipe book and found the "scan for this at the ah" button.
When i used it it tried to lookup both the materials and the finished enchantment.
It should find Enchant Weapon - Versatile Navigation.
It found the components: Gloomdust , Umbrashards & veiled crystal, but couldn't find the final product.
Therefore comparing prices between materials needed and the final good is not possible.
This is due to the "wrong name" used. Could this addon have a bit more knowledge and instead of going for "weapon enchantment: Versatile navigation" go for the name of the item crafted by that skill?
So something like "weapon -  versatile navigation" in my case?

**Comment by jrob8577** [comment]
Duplicates #320 I do not currently have a d/e table, which I would need to finish fixing this bug.
