### ISSUE TITLE
LUA error enter an item

### ISSUE THREAD

**Issue by gewhy** [Auctionator/Auctionator#368]
Hi 

This error keeps happening when I enter an item. I need you to tell me how to solve this.

I'm always grateful. I'm using it.

 

Message: Interface\AddOns\Auctionator\Auctionator.lua:5058: bad argument #1 to 'strlen' (string expected, got nil)
Time: Thu Nov 8 23:18:08 2018
Count: 1
Stack: Interface\AddOns\Auctionator\Auctionator.lua:5058: bad argument #1 to 'strlen' (string expected, got nil)
[C]: in function `strlen'
Interface\AddOns\Auctionator\Auctionator.lua:5058: in function `Atr_Item_Autocomplete'
[string "*:OnCharComposition"]:1: in function <[string "*:OnCharComposition"]:1>

Locals: (*temporary) = nil
(*temporary) = "string expected, got nil"

**Comment by meltinglava** [comment]
What do you mean by "when i enter an item" is it when you shift click to put it into the search tab / sell tab or something different?

**Comment by gewhy** [comment]
This occurs when I type items directly in the Purchase tab. It's got to do with the automatic completion.
Sorry for my poor English.
