### ISSUE TITLE
wrong price for selling mogging items

### ISSUE THREAD

**Issue by ilreberli** [Auctionator/Auctionator#372]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

I am selling mogging items and recognized, that the suggested price does not fit to the actual actions.
As you can see on my screenshots, actionator displays just historic prices, but no actual actions. But when I search for the item i get actual auctions and the suggested price does not undercut the price.

![image](https://user-images.githubusercontent.com/37041620/50534765-d670b080-0b41-11e9-99ad-6405b89d9047.png)

![image](https://user-images.githubusercontent.com/37041620/50534773-e8eaea00-0b41-11e9-9616-1325a71c45a2.png)

![image](https://user-images.githubusercontent.com/37041620/50534775-f7d19c80-0b41-11e9-8160-f08e5d6fe990.png)

**Comment by jrob8577** [comment]
@ilreberli Auctionator treats items with different ilvl as different items in its search and comparison of prices. This was done back in Warlords of Draenor to differentiate between the warforged+ items, and their base item, as people were accidentally paying large sums for items that had weaker stats when they were treated as the same item (when really they wanted the stronger stat items).

**Comment by ilreberli** [comment]
Thank you for your explanation. Maybe I am wrong, but this is not relevant for transmog items (ilvl 48). I believe they are only traded and bought for mogging purposes. Therefore I would appreciate an option that ignores this behaviour when selling items and/or additional information about the items to explain the price difference (e.g. the ilvl when this is relevant and other remarks that explain the price).
