### ISSUE TITLE
 Interface, Atr_AuctionFrameAuctions_Update

### ISSUE THREAD

**Issue by DumBlonde** [Auctionator/Auctionator#374]
Please include as much of the following information as possible to help me fix the bug:

## I do not know if this is a bug, except when I mouse over an item to get the stats for pricing, it fills my chat log with line after line of Atr_StackSize and then when I list the item it does the same thing except different text.

_Please include a brief description of the bug, including what you were doing, and when it occurred._

## hovering over the item in the sell tab, with my mouse, I just need a way to stop all this unnecessary chat data in my chat log. It didn't start doing it until this week. I didn't add any new addon's I actually removed a few.

_Include the steps I would need to follow to reproduce the bug._

## Put an item in the Sell tab, then hover over the item with your mouse, and the data starts filling in repeatedly. It removes tells that I am currently conversing with, making me be unable to read what is told to me. I do not know this is a bug, it just bugs me.

_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by jrob8577** [comment]
Thanks for reporting, @DumBlonde. Can you please got to the configuration sheet for Auctionator, and ensure that the "Show Debug Output" is not checked? If that is the case, please check and uncheck it - I **think** there's a potential issue that shows up sometimes when this global variable isn't defined on the client yet, but I haven't been able to reproduce it recently.

In either case, please let me know if this corrects what you're seeing.
