### ISSUE TITLE
Item Bag Tooltip malfunction

### ISSUE THREAD

**Issue by Ptitauto** [Auctionator/Auctionator#378]
Hi, 
I'm writing an addon and there is a conflict with Auctionator.
In my code, i moved the GameTooltip (the tooltip which appears when you mouseover a spell or a player) to another place with this : 

`function TracerFunction:postHook()
	GameTooltip:SetOwner(UIParent, "ANCHOR_NONE");
	GameTooltip:SetPoint("BOTTOMRIGHT",QuickJoinToastButton,"TOPLEFT",0,0);
end
hooksecurefunc("GameTooltip_SetDefaultAnchor", TracerFunction.postHook);`

But, when I mouseover the first time an item in my bag, the tooltip which appears only says the price of the item and the price at the auctionhouse. There is no description of the item. When I mousever a second time the item, the tooltip is correct.

**Comment by jrob8577** [comment]
Can I get a screenshot of this behavior? I've updated tooltips for the new APIs in 8.3, but doubt that would have addressed this issue. Could I also get a link to your addon to test?
