### ISSUE TITLE
Suggestion: items without price history should start at 10x deposit

### ISSUE THREAD

**Issue by unquietwiki** [Auctionator/Auctionator#379]
I have made a similar suggestion to [Auctioneer](https://gitlab.com/norganna-wow/auctioneer/auc-advanced/issues/9); in fact, one of the reasons I use Auctionator right now, is because Auctioneer can get too aggressive with pricing. Item rarity for pre-BoA items; is no longer an effective means of conveying how easy it is to actually get; nor how useful it is, per the heavily-sped-up levelling of late.

**Comment by Andrej730** [comment]
What exactly do you mean by "repricing to 10x deposit"?

**Comment by unquietwiki** [comment]
@Andrej730 When an auction is posted, there's always a deposit given based on the item's value, plus time placed on auction for 12-48hr posting. That's the best clue I can think of the system having, as to what the recommended price of something should be. Right now the auction houses seem polluted by white & green items with 5-6 figure prices at times; which makes absolutely no sense, given you can't cross-server trade easily & whatnot. So if there's a way in the addon code to see what's being suggested for deposits; and suggest otherwise empty prices on that; it might help things.

**Comment by Andrej730** [comment]
Sounds reasonable but "10x" rate for all items is kind of debatable. It probably would be more correct if this rate would be based on item rarity or something.

**Comment by unquietwiki** [comment]
Yeah, I agree on that. I think item type will be more successful for that;
pets, mounts, etc. On gear, biggest issue are transition level items:
especially Legion & BfA hand-off.
