### ISSUE TITLE
Sell tab and lists stopped working

### ISSUE THREAD

**Issue by Pwofese** [Auctionator/Auctionator#382]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

Buy Tab: The buy tab gives me the following error every time I click on it:  "gCurrentSList bad metatable: type gCurrentSList: tableslist[1] bad metatable; type: table" It does not display recent searches anymore either.

Sell Tab: The sell tab does not work at all. I can drag pieces to it but it will not allow any other operations.

Full Scan: Will still scan but upon completion it creates a massive amount of errors that causes WoW to prompt me to shut off all addons to stop the errors. 

## Steps to Reproduce

Happens every time I click the tabs or start full scan. Tool tips do not appear to have any issues and "more" tab appears to work fine.

## Loaded Addons

I shut off all addons and was able to reproduce.

## Back Trace (LUA Error Output)

Upon logging in I get the following LUA error:

2x Auctionator\AuctionatorScan.lua:1456: bad argument #1 to 'max' (number expected, got nil)
[C]: in function `max'
Auctionator\AuctionatorScan.lua:1456: in function `Atr_PruneScanDB'
Auctionator\Auctionator-8.1.0.lua:781: in function `Atr_InitScanDB'
Auctionator\Auctionator-8.1.0.lua:813: in function `Atr_OnLoad'
Auctionator\Auctionator-8.1.0.lua:167: in function `Atr_EventHandler'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

Locals:
(*temporary) = nil
(*temporary) = -1
(*temporary) = "number expected, got nil"

The following is a typical error received when dragging an item to sell tab (Chaos Orb):

1x Auctionator\Auctionator-8.1.0.lua:1228: attempt to index global 'AtrScanningTooltip' (a nil value)
Auctionator\Auctionator-8.1.0.lua:1228: in function `Atr_GetSellItemInfo'
Auctionator\Auctionator-8.1.0.lua:2880: in function `Atr_OnNewAuctionUpdate'
Auctionator\Auctionator-8.1.0.lua:178: in function `Atr_EventHandler'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>
[C]: in function `ClickAuctionSellItemButton'
Auctionator\Auctionator-8.1.0.lua:1456: in function `Atr_ClickAuctionSellItemButton'
Auctionator\Auctionator-8.1.0.lua:1482: in function <Auctionator\Auctionator.lua:1479>

Locals:
auctionItemName = "Chaos Orb"
auctionTexture = 332402
auctionCount = 1
auctionQuality = 3
auctionItemLink = nil
hasCooldown = false
speciesID = nil
level = nil
breedQuality = nil
maxHealth = nil
power = nil
speed = nil
name = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = <function> defined @Auctionator\AuctionatorHints.lua:379
(*temporary) = GameTooltip {
 0 = <userdata>
 numMoneyFrames = 1
 SetHyperlink = <function> defined =[C]:-1
 SetRecipeReagentItem = <function> defined =[C]:-1
 SetBuybackItem = <function> defined =[C]:-1
 shoppingTooltips = <table> {
 }
 SetMerchantItem = <function> defined =[C]:-1
 SetQuestLogItem = <function> defined =[C]:-1
 SetGuildBankItem = <function> defined =[C]:-1
 SetTradeTargetItem = <function> defined =[C]:-1
 BottomOverlay = <unnamed> {
 }
 SetTradePlayerItem = <function> defined =[C]:-1
 SetInboxItem = <function> defined =[C]:-1
 SetSendMailItem = <function> defined =[C]:-1
 hasMoney = 1
 updateTooltip = 0.176000
 SetInventoryItem = <function> defined =[C]:-1
 ItemTooltip = <unnamed> {
 }
 comparing = false
 SetLootRollItem = <function> defined =[C]:-1
 TopOverlay = <unnamed> {
 }
 SetAuctionSellItem = <function> defined =[C]:-1
 SetBagItem = <function> defined =[C]:-1
 needsReset = true
 SetRecipeResultItem = <function> defined =[C]:-1
 SetLootItem = <function> defined =[C]:-1
 SetQuestItem = <function> defined =[C]:-1
 SetAuctionItem = <function> defined =[C]:-1
}
(*temporary) = "|cff0070dd|Hitem:52078::::::::21:264::::::|h[Chaos Orb]|h|r"
(*temporary) = nil
(*temporary) = "Chaos Orb"
(*temporary) = "|cff0070dd|Hitem:52078::::::::21:264::::::|h[Chaos Orb]|h|r"
(*temporary) = 3
(*temporary) = 85
(*temporary) = 0
(*temporary) = "Tradeskill"
(*temporary) = "Other"
(*temporary) = 200
(*temporary) = ""
(*temporary) = 332402
(*temporary) = 2000
(*temporary) = 7
(*temporary) = "attempt to index global 'AtrScanningTooltip' (a nil value)"

**Comment by datgrl** [comment]
I just downloaded Auctionator from Curse and installed it.  I had been using it for years but I had to rebuild all my profiles.  I cannot get the Sell Tab to display.  It's using the Blizzard AH.  Even with all addons disabled but Auctionator, I'm getting the message 'your addons are causing errors which may slow down your pc'.
