### ISSUE TITLE
Stuttering/performance decrease when hovering over an item

### ISSUE THREAD

**Issue by ashenity** [Auctionator/Auctionator#383]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

_When hovering over an item with Auctionator installed, performance drops ~15+ fps. It feels like the addon is scanning in the background every half a second whilst the tool-tip is active which causes stuttering/hang ups. There is no issue whilst using it for auction activity, nor while the tool-tip is inactive._

## Steps to Reproduce

- [ ] _Install and load Auctionator_
- [ ] _Hover over an item (scan not necessary)_

## Loaded Addons

```
ACP
AllTheThings
Auctionator
BadBoy
BadBoy_CCleaner
BadBoy_Guilded
BadBoy_Ignore
BadBoy_Levels
!BugGrabber
BugSack
Details
Details_EncounterDetails
Details_RaidCheck
Details_Streamer
Details_TinyThreat
Details_Vanguard
DialogKey
EasyScrap
EasyDeleteConfirm
FlashTaskBar
GatherMate2
GTFO
InFlight_Load
Kui_Media
Kui_Nameplates
Kui_Nameplates_Core
NameplateSCT
OmniCC
Pawn
Rarity
Rarity_Options
Simulationcraft
TransmogWishList
WeakAuras
WoWGatheringNodes
AddOnSkins
ElvUI_DTBars2
ElvUI_BagFilter
ElvUI_VisualAuraTimers
ElvUI
DBM-Core
DBM-DefaultSkin
DBM-StatusBarTimers
```

## Back Trace (LUA Error Output)

_N/A. No error output available, you can view a video [here](https://youtu.be/JptOwoPj5ec) which shows the extent of the problem with an empty BugSack window._

**Comment by jrob8577** [comment]
Iiiiinteresting. Ty for the video!!

**Comment by ashenity** [comment]
No problem! I have since uninstalled the game, I can reinstall fresh with only Auctionator and feedback?
