### ISSUE TITLE
Atr_SearchAH API function always uses exact searches for lists

### ISSUE THREAD

**Issue by CaspianRoach** [Auctionator/Auctionator#385]
Atr_SearchAH function which resides at AuctionatorAPI.lua:98 always does exact searches for lists of items. This leads to lists of, for example, world drop green armor that has suffixes on it (Jade Legplates of the Aurora and the like) to never show while queried for { "Vanguard Legplates", "Jade Legplates", ...etc } for example.

The current code checks for the first item in the list only and does substring search only on that first entry for some reason but the rest of the items in the list are always exact searches.

A good way to fix this would be to introduce an additional argument to that function that forces the exact search on/off so the addons can use whichever method of the search suits them best.

At the moment searching for lists of items that can have suffixes simply does not return any results for those items.

**Comment by plusmouse** [comment]
We have a new API which resolves this concern https://github.com/Auctionator/Auctionator/wiki/API-Documentation
