### ISSUE TITLE
New 8.2 Error

### ISSUE THREAD

**Issue by BluespiritWoW** [Auctionator/Auctionator#388]
ERROR

108x Auctionator\AuctionatorVendor.lua:45: Usage: AtrBindTypeToolTip:SetItemByID(ID)
[C]: in function `SetItemByID'
Auctionator\AuctionatorVendor.lua:45: in function `Atr_AddBondTypeToCache'
Auctionator\AuctionatorVendor.lua:73: in function `Atr_GetBondType'
Auctionator\AuctionatorHints.lua:319: in function `Atr_STWP_AddAuctionInfo'
Auctionator\AuctionatorHints.lua:449: in function `Atr_ShowTipWithPricing'
Auctionator\AuctionatorHints.lua:558: in function <Auctionator\AuctionatorHints.lua:554>
[C]: ?
[C]: ?
[C]: in function `SetRecipeResultItem'
...Blizzard_TradeSkillUI\Blizzard_TradeSkillDetails.lua:407: in function `OnResultMouseEnter'
[string "*:OnEnter"]:1: in function <[string "*:OnEnter"]:1>

Locals:
(*temporary) = AtrBindTypeToolTip {
 0 = <userdata>
 updateTooltip = 0.200000
 needsReset = true
 BottomOverlay = <unnamed> {
 }
 comparing = false
 TopOverlay = <unnamed> {
 }
}
(*temporary) = nil

**Comment by jrob8577** [comment]
This should be fixed in the 8.2.0 release.
