### ISSUE TITLE
[Suggestion] Snipe Feature Addon Merge

### ISSUE THREAD

**Issue by Drkangl32** [Auctionator/Auctionator#393]
I have been using Auction Snatch with Auctionator for years now.  Both of these addons work brilliantly together for gold making.  Auction Snatch adds a tab right next to the Auctionator Tabs for a clean interface.  It adds key "snipe" features which are extremely helpful in auto searching for bargains.  Key features include:

1.  Snipe shopping list can be created with gold filter settings for each item.  Auto search scans the list of items in AH in seconds using filter settings.  If the asking price or bid price falls below the gold setting, user is notified.  After a notice, user is prompted to buy, bid or skip ahead to the next item.

2.  Snipe list also include filters such as "Minimum Item Level", "Exact Match", "Ignore Stacks of 1", etc.

3.  Multiple lists can be created and/or used on different servers.

4.  Like Auctionator, Auction Snatch is extremely easy to use.

See direct link to this mod below:
https://www.curseforge.com/wow/addons/auctionsnatch

The reason I am bringing Auction Snatch to your attention is because the mod creator has left notice on Curse that they are no longer playing WoW and wish someone to take over their mod.  This mod could possibly be merged with Auctionator with minimal effort.  With a few added refinements it could serve as a brand new Auctionator "Snipe" feature!  Please take a few moments to look this mod over and consider it.

Note that for myself, I took out the annoying doorbell notification sound and replaced it with a cash register "ching" sound instead.  Aside from that, I currently use Auction Snatch and Auctionator together with no additional modifications.  They work perfectly together with no bugs whatsoever.

**Comment by Drkangl32** [comment]
Just a small additional comment.  A gold filter scan might be helpful in detecting opportunities in the other direction as well.  So, while the scan initially looks for items priced extremely low, a second gold filter preset might look for items priced extremely high.  This opens up the opportunity to dump horded commodities sitting in the bank at the maximum possible value.

As an example, a stock market style side scroll display might notify the user that "Ghost Iron Bar now selling excessively high @ 95G each".  Side scroll messages repeat until cancelled or a new scan is completed.  Or, keep it simple with a basic pop-up message.

**Comment by plusmouse** [comment]
This addon was written for the pre-8.3 auction house, as such it would require rewriting to work with the current AH. This means it will not be a simple feature merge.

Rewriting is unlikely to happen, so closing.
