### ISSUE TITLE
conflicts with ct_mod and bag tooltips

### ISSUE THREAD

**Issue by YammYcoding** [Auctionator/Auctionator#394]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug
_Please include a brief description of the bug, including what you were doing, and when it occurred._

1. Let only enabled two addons: Auctionator and CTMod ( Core and Library ).
2. Open bag and mouse over random items, gear or not ( probably the ones with prices already scanned by auctionator ).
3. lua error everytime

PS: addons alone does not trigger the error, only when together

## Loaded Addons
Auctionator
CT_Core
CT_Library

_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

Message: Interface\FrameXML\ContainerFrame.lua:1372: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: GameTooltip:SetPoint.
Time: Mon Jul 8 09:16:32 2019
Count: 8
Stack: Interface\FrameXML\ContainerFrame.lua:1372: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: GameTooltip:SetPoint.
[C]: in function `SetPoint'
Interface\FrameXML\ContainerFrame.lua:1372: in function `ContainerFrameItemButton_CalculateItemTooltipAnchors'
Interface\FrameXML\ContainerFrame.lua:1414: in function `ContainerFrameItemButton_OnEnter'
[string "*:OnEnter"]:1: in function <[string "*:OnEnter"]:1>

Locals: (*temporary) = GameTooltip {
0 = <userdata>
SetRecipeReagentItem = <function> defined =[C]:-1
SetBuybackItem = <function> defined =[C]:-1
shoppingTooltips = <table> {
}
SetMerchantItem = <function> defined =[C]:-1
ItemTooltip = <unnamed> {
}
SetQuestLogItem = <function> defined =[C]:-1
SetGuildBankItem = <function> defined =[C]:-1
BottomOverlay = <unnamed> {
}
SetTradeTargetItem = <function> defined =[C]:-1
SetTradePlayerItem = <function> defined =[C]:-1
SetSendMailItem = <function> defined =[C]:-1
SetHyperlink = <function> defined =[C]:-1
updateTooltip = 0.081000
SetInventoryItem = <function> defined =[C]:-1
SetInboxItem = <function> defined =[C]:-1
comparing = false
SetLootRollItem = <function> defined =[C]:-1
TopOverlay = <unnamed> {
}
SetAuctionSellItem = <function> defined =[C]:-1
SetBagItem = <function> defined =[C]:-1
needsReset = true
SetRecipeResultItem = <function> defined =[C]:-1
SetLootItem = <function> defined =[C]:-1
SetQuestItem = <function> defined =[C]:-1
SetAuctionItem = <function> defined =[C]:-1
}
(*temporary) = "BOTTOMRIGHT"
(*temporary) = ContainerFrame1Item15 {
timeSinceUpgradeCheck = 0
PostOnLoad = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:169
BattlepayItemTexture = <unnamed> {
}
IconOverlay = <unnamed> {
}
BagStaticTop = <unnamed> {
}
GetItemContextMatchResult = <function> defined @Interface\FrameXML\ContainerFrame.lua:1464
IconBorder = <unnamed> {
}
newitemglowAnim = <unnamed> {
}
icon = ContainerFrame1Item15IconTexture {
}
isExtended = false
UpdateTooltip = <function> defined @Interface\FrameXML\ContainerFrame.lua:1376
ExtendedOverlay = <unnamed> {
}
RegisterCallback = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:175
UnregisterCallback = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:182
UpdateItemContextMatching = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:211
NewItemTexture = <unnamed> {
}
SplitStack = <function> defined @Interface\FrameXML\ContainerFrame.lua:1100
BagStaticBottom = <unnamed> {
}
ItemContextOverlay = <unnamed> {
}
PostOnShow = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:189
flash = <unnamed> {
}
ExtendedSlot = <unnamed> {
}
ExtendedOverlay2 = <unnamed> {
}
hasItem = 1
JunkIcon = <unnamed> {
}
SetMatchesSearch = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:202
UpdateItemContextOverlay = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:222
matchesSearch = true
0 = <userdata>
count = 1
itemContextChangedCallbackIsSet = true
itemContextMatchResult = 3
itemContextChangedCallback = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:170
readable = false
Count = ContainerFrame1Item15Count {
}
PostOnHide = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:198
flashAnim = <unnamed> {
}
GetMatchesSearch = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:207
UpgradeIcon = <unnamed> {
}
searchOverlay = ContainerFrame1Item15SearchOverlay {
}
}
(*temporary) = "TOPLEFT"

**Comment by DDCorkum** [comment]
I will investigate from the CT side what could be causing the interference between the addons.

**Comment by DDCorkum** [comment]
CTCore hooks _GetDefaultAnchor, and repositions GameTooltip to a custom anchor somewhere on the screen.

I notice LibItemUpgradeInfo creates its own custom tooltips and then triggers this same function... but in the process of doing so,  it is probably triggering CTCore's hook and CTCore might not be checking that "self" is the actual GameTooltip.   This is spreading taint to the game tooltip, resulting in the error above.

My guess is that I just need to make a small change to CTCore for compatibility with LibItemUpgradeInfo (and any other addon instantiating their own tooltips separate from GameTooltip).  I'll give it a try tonight.

**Comment by jrob8577** [comment]
@DDCorkum I appreciate the thorough investigation! Please let me know if the error persists after your change; happy to look into this further on the Auctionator side.

**Comment by DDCorkum** [comment]
I believe the problem was 100% with my own code in CTMod, and I already pushed a new version 8.2.0.4 with a correction.

In summary, this is what I did wrong:
hooksecurefunc(GameTooltip_GetDefaultAnchor, function()  GameToolTip:DoStuff(); end);

And this is my correction:
hooksecurefunc(GameTooltip_GetDefaultAnchor, function(tooltip) tooltip:DoStuff(); end);

The error message was because I was tainting GameTooltip during the hook of non-default tooltips such as the one instantiated by LibItemUpgradeInfo.

**Comment by YammYcoding** [comment]
Tested beta version, and now the error is gone. I guess you made it man! Thanks :D
