### ISSUE TITLE
The latest 8.2 did not fix the hover issue for me

### ISSUE THREAD

**Issue by mournblade** [Auctionator/Auctionator#395]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug
When i go over items in inventory and elsewhere, hover is empty. No errors in output.

## Steps to Reproduce
open inventory, go to an item, there is no over or empty hover. Go to empty slot and back into the item, hover now appears.

Then go from that item to another item. No hover. Go back to first item, the hover appears (again). Then go to new item again, now the hover appears.

It's a bit intermittent insofar that i think that sometimes the hover appears right away, but most often not.

**Comment by jrob8577** [comment]
@mournblade Was this tested with only Auctionator installed?
