### ISSUE TITLE
OnModifiedClick Taint Spreads to Major Game Systems

### ISSUE THREAD

**Issue by MMOSimca** [Auctionator/Auctionator#397]
As of Patch 8.2.0, insecurely hooking OnModifiedClick spreads taint everywhere. It'll taint comparison tooltips (they don't work in combat), it taints Azerite trait selection windows (also don't work in combat), and it can even taint the dressing room (doesn't work in combat from bags).

There are alternatives, but I don't know your particular use case. Quite a lot of chatter has been made in #wowuidev in Freenode IRC about it.

**Comment by plusmouse** [comment]
This will likely disappear with the 8.3 UI updates currently being worked on. Closing.
