### ISSUE TITLE
Saved Variables Structure

### ISSUE THREAD

**Issue by Khazl** [Auctionator/Auctionator#406]
Hey, this is more a question than an issue.
I looked into the SavedVariables of this addon and wonder what this keys stand for:
```
    ["Item Name"] = {
        ["mr"] = 230,
        ["cc"] = 1,
        ["id"] = "4496:0:0:0:0",
        ["H3222"] = 230,
        ["sc"] = 0,
    }
```
Could you please give us a quick insight?

**Comment by plusmouse** [comment]
With the 8.3 update a lot of the database format is in flux, no this question is no longer relevant.
