### ISSUE TITLE
Auction Durations are wrong (Classic)

### ISSUE THREAD

**Issue by Mertex12** [Auctionator/Auctionator#407]
The current auction durations in the sell tab say 12, 24, and 48 hours but the correct times are actually 2, 8, and 24 hours as seen in the regular auctions tab

**Comment by Baalin** [comment]
The classic version of auctionator is unofficial, but you can find the fix you are looking for here:
https://www.wowinterface.com/downloads/info24958-AuctionatorClassicquickfix.html

**Comment by plusmouse** [comment]
Closing, this is dependant on #402 - and resolving that will resolve this.
