### ISSUE TITLE
Framedropping when i want to check equipment

### ISSUE THREAD

**Issue by Sekorhex** [Auctionator/Auctionator#408]
## Brief Description of Bug

Framedrops for checking Equipment

## Steps to Reproduce

I go with the cursor to the equipted items and when i want to check it, it starts to framedropping.

## Loaded Addons

Auctionator

**Comment by jrob8577** [comment]
@Sekorhex are any errors generated? If so, please provide an error report using an addon like [BugSack](https://www.curseforge.com/wow/addons/bugsack).
