### ISSUE TITLE
On trying to set guild rank!

### ISSUE THREAD

**Issue by NaomiErin** [Auctionator/Auctionator#409]
Trying to change guild ranks and the error occurs but a reload seems to fix the issue in question.

> 1x [ADDON_ACTION_FORBIDDEN] AddOn 'Auctionator' tried to call the protected function 'SetGuildRankOrder()'.
> !BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
> [C]: in function `SetGuildRankOrder'
> Blizzard_Communities\GuildRoster.lua:174: in function `func'
> FrameXML\UIDropDownMenu.lua:914: in function `UIDropDownMenuButton_OnClick'
> [string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

**Comment by plusmouse** [comment]
This is likely misappropriated to Auctionator when being caused by another addon. Auctionator doesn't use or interact with any functions relating to guilds.
