### ISSUE TITLE
Cannot buy the listed items

### ISSUE THREAD

**Issue by Walkerbo** [Auctionator/Auctionator#411]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug
When I search mounts, pets and toys when I click the buy all button the dress up panel opens up empty, and the panel does not change to the sell panel

## Steps to Reproduce
Click the mount search button, click the shop button, click the buy all button once the scan finishes

## Loaded Addons
![List of addons](https://user-images.githubusercontent.com/35990554/65660399-e9cd8f80-e071-11e9-91a7-58082be93d91.png)

## Back Trace (LUA Error Output)
(attached)

[CollectionShop error output .txt](https://github.com/Auctionator/Auctionator/files/3656039/CollectionShop.error.output.txt)

**Comment by Vanteil** [comment]
I have this same exact problem. The buy button does nothing and I can't even click on the listing for mounts and pets in the AH window.
