### ISSUE TITLE
History tab question

### ISSUE THREAD

**Issue by RoyBoy432** [Auctionator/Auctionator#417]
Is the "History" tab a list of:

1. Prices of auctions that went to completion because the item sold?
2. Prices of auctions that went to completion whether or not the item sold?

In short, when a price appears in the history tab, is it a guarantee that the item was successfully sold at that price in the past?

**Comment by manzarek123** [comment]
Its and average between the lowest low price and the highest low price for that day (in case of multiple scans a a day)

itemPrice   = zc.round ((highlowprice + lowlowprice) / 2);

And no it doesn't guarantee that the item was sold

**Comment by jrob8577** [comment]
Thanks for the answer @manzarek123!
