### ISSUE TITLE
8.0.2.5 Update

### ISSUE THREAD

**Issue by celticdragon56** [Auctionator/Auctionator#418]
I have been patiently waiting for the latest update - to work with the WoW update 8.0.2.5.  I'm wondering how much longer it will be... I am unable to use Auctionator because it is "out of date", & even if I load it, it won't work. I love Auctionator, it's a great add-on, & greatly improves my Auction House experience. Please let me know how much longer I should expect to wait - or, since I'm a novice at this stuff, let me know what I need to do to get Auctionator to work as it is now. 
Thank you so much!!!

**Comment by jrob8577** [comment]
@celticdragon56 I am currently working on updating Auctionator for 8.3. Alpha releases with greatly reduced functionality are getting posted in [the Auctionator Discord server](https://discord.gg/xgz75Pp). I appreciate your patience!!

**Comment by celticdragon56** [comment]
Thanks so much!! I really like Auctionator, so glad to hear it's in the
works! Kudos to all of you wizards who create such fantastic add-ons that
make our gaming everything we hope for and more!!!
