### ISSUE TITLE
Lua error when opening Classic AH

### ISSUE THREAD

**Issue by b-morgan** [Auctionator/Auctionator#420]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

Lua error when opening Classic AH

## Steps to Reproduce

Just open the AH

## Loaded Addons

(I'll switch to Swatter and include list on next error)

## Back Trace (LUA Error Output)

1x Auctionator\AuctionatorLocalize.lua:150: Wrong object type for function
[C]: in function `IsForbidden'
Auctionator\AuctionatorLocalize.lua:150: in function `Atr_FrameIsAccessible'
Auctionator\AuctionatorLocalize.lua:138: in function `Atr_IsAuctionatorFrame'
Auctionator\AuctionatorLocalize.lua:77: in function <Auctionator\AuctionatorLocalize.lua:76>
Auctionator\AuctionatorLocalize.lua:132: in function `Atr_LocalizeFrames'
Auctionator\Auctionator-8.1.0.lua:1178: in function `Atr_Init'
Auctionator\Auctionator-8.1.0.lua:917: in function `Atr_OnAddonLoaded'
Auctionator\Auctionator-8.1.0.lua:168: in function `Atr_EventHandler'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>
[C]: in function `LoadAddOn'
FrameXML\UIParent.lua:353: in function `UIParentLoadAddOn'
FrameXML\UIParent.lua:364: in function `AuctionFrame_LoadUI'
FrameXML\UIParent.lua:1124: in function <FrameXML\UIParent.lua:658>

Locals:
(*temporary) = <table> {
}
(*temporary) = nil

**Comment by plusmouse** [comment]
Closing, this is dependant on #402 - and resolving that will resolve this.
