### ISSUE TITLE
What is this....

### ISSUE THREAD

**Issue by ZForceSeattle** [Auctionator/Auctionator#421]
I had all of my WOW Classic items running perfectly. Something happened around the 20th and now I have a nightmare. I'm constantly seeing processes running in my main feed and I'm getting huge dialog boxes. 

I did a clean sweep of all addons and reinstalled them as I had them before. This is the mess I get now.

Date: 2019-12-24 17:09:38
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Auctionator\AuctionatorFilters.lua line 82:
   attempt to concatenate local 'parentKey' (a nil value)
Debug:
   Auctionator\AuctionatorFilters.lua:82: GenerateSubClasses()
   Auctionator\AuctionatorFilters.lua:98: in main chunk
Locals:
classID = 17
parentName = nil
parentKey = nil
subClassesTable = <table> {
 1 = 0
 2 = 1
 3 = 2
 4 = 3
 5 = 4
 6 = 5
 7 = 6
 8 = 7
 9 = 8
 10 = 9
}
subClasses = <table> {
}
subFilters = <table> {
}
(for index) = 1
(for limit) = 10
(for step) = 1
index = 1
subClassID = 0
name = "Humanoid"
filter = <table> {
 classID = 17
 subClassID = 0
}
(*temporary) = <function> defined @Interface\AddOns\Auctionator\AuctionatorFilters.lua:61
(*temporary) = <table> {
 __index = <table> {
 }
 key = 0
 name = "-------"
 filter = <table> {
 }
 subClasses = <table> {
 }
 Find = <function> defined @Interface\AddOns\Auctionator\AuctionatorFilters.lua:49
 classID = 0
 new = <function> defined @Interface\AddOns\Auctionator\AuctionatorFilters.lua:61
}
(*temporary) = <table> {
 name = "Humanoid"
 classID = 0
}
(*temporary) = nil
(*temporary) = "/Humanoid"
(*temporary) = "Humanoid"
(*temporary) = "attempt to concatenate local 'parentKey' (a nil value)"

AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  AccountantClassic, vv2.11.07
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  Auctionator, v8.2.0
  SlideBar, v8.2.6509 (SwimmingSeadragon)
  Stubby, v8.2.6510 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v1.13.3.11303 <none>
  (ck=257)
Date: 2019-12-24 17:09:42
ID: 3
Error occured in: Global
Count: 1
Message: ..\AddOns\Auctionator\Auctionator.lua line 276:
   attempt to call global 'GetProfessions' (a nil value)
Debug:
   [C]: GetProfessions()
   Auctionator\Auctionator.lua:276:
      Auctionator\Auctionator.lua:273
   Auctionator\Auctionator.lua:597: EnableDisableDElogging()
   Auctionator\Auctionator.lua:898: Atr_OnLoad()
   Auctionator\Auctionator.lua:167: Atr_EventHandler()
   [string "*:OnEvent"]:1:
      [string "*:OnEvent"]:1
Locals:

AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  AccountantClassic, vv2.11.07
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  Auctionator, v8.2.0
  BeanCounter, v8.2.6505 (SwimmingSeadragon)
  Enchantrix, v8.2.6506 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6507 (SwimmingSeadragon)
  Questie, v5.3.0
  Recount, vv8.2.0c
  SlideBar, v8.2.6509 (SwimmingSeadragon)
  Stubby, v8.2.6510 (SwimmingSeadragon)
  TidyPlatesThreatPlates, v1.2.6
  TitanClassic, v1.1.2.11302
  TitanClassicAmmo, v1.1.2.11302
  TitanClassicBag, v1.1.2.11302
  TitanClassicClock, v1.1.2.11302
  TitanClassicGold, v1.1.2.11302
  TitanClassicLocation, v1.1.2.11302
  TitanClassicLootType, v1.1.2.11302
  TitanClassicPerformance, v1.1.2.11302
  TitanClassicRegen, v1.1.2.11302
  TitanClassicRepair, v1.1.2.11302
  TitanClassicVolume, v1.1.2.11302
  TitanClassicXP, v1.1.2.11302
  TradeSkillMaster, vv4.8.24
  BlizRuntimeLib_enUS v1.13.3.11303 <none>
  (ck=4e0)

Now you will see I'm using Titan, Questie, Auctioneer, Auctionator, and TradeSkillsMaster. I had them all working perfectly. There were no bugs and no crashes. **Now I'm getting this mess.**

**Comment by jrob8577** [comment]
@ZForceSeattle is this in classic or retail?
