### ISSUE TITLE
Auctionator Revamp After Patch 8.3?

### ISSUE THREAD

**Issue by Drkangl32** [Auctionator/Auctionator#424]
I think there are many who wish to know the future of Auctionator after patch 8.3.  Will it be adapted to work with the new auction house UI?

While some features that are duplicated could be removed entirely, there are other features that could evolve.  For instance, the scan to check for undercuts could also check "last in, first out" status of items we post.  This would help us to maintain our posted items at the top of the buy list!

Any information you could share would be much appreciated!

**Comment by Ibglitrbug** [comment]
I just wondering if they are going to make it work with the xpac i hate this ah and really need my add on back its the only thing that kept me going on the ah lol Ty for all your great work.

**Comment by Walkerbo** [comment]
This new AH breaks Auctionator, I hope it can be updated to work as it did

**Comment by JohnTN4321** [comment]
I use auctionator a lot every day. TSM and the default AH do not do things I need like this addon dose. Please continue to update!

**Comment by teyasio** [comment]
All I want is just the shopping list.  The new AH covers everything else quite nicely

**Comment by jrob8577** [comment]
We're discussing this in [discord](https://discord.gg/xgz75Pp). I'm closing this issue as it is not actionable, though if folks on this thread are aware of any API documentation, please share it in discord.
