### ISSUE TITLE
Login Bug #2

### ISSUE THREAD

**Issue by DiscordGregory** [Auctionator/Auctionator#426]
This bug appears on login, only bugsack + bug grabber installed.

1x Auctionator\Auctionator-8.2.0.lua:146: Attempt to register unknown event "AUCTION_ITEM_LIST_UPDATE"
[string "=[C]"]: in function `RegisterEvent'
[string "@Auctionator\Auctionator-8.2.0.lua"]:146: in function `Atr_RegisterEvents'
[string "*:OnLoad"]:1: in function <[string "*:OnLoad"]:1>

Locals:
(*temporary) = Atr_core {
 0 = <userdata>
}
(*temporary) = "AUCTION_ITEM_LIST_UPDATE"

**Comment by jrob8577** [comment]
Fixed by https://github.com/Auctionator/Auctionator/pull/428
