### ISSUE TITLE
Login bug #3

### ISSUE THREAD

**Issue by DiscordGregory** [Auctionator/Auctionator#427]
This bug appears on login, only bugsack + bug grabber installed.

1x Auctionator\AuctionatorHints.lua:505: hooksecurefunc(): SetAuctionItem is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "@Auctionator\AuctionatorHints.lua"]:505: in main chunk

Locals:

**Comment by jrob8577** [comment]
Fixed by https://github.com/Auctionator/Auctionator/pull/428
