### ISSUE TITLE
Log In Error (Git)

### ISSUE THREAD

**Issue by vandiel01** [Auctionator/Auctionator#430]
1x Auctionator\AuctionatorHints.lua:505: hooksecurefunc(): SetAuctionItem is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "@Auctionator\AuctionatorHints.lua"]:505: in main chunk

Locals:

**Comment by jrob8577** [comment]
Please use the updated *alpha* version from Discord; this line is commented out in that version so should not be able to cause a bug.
