### ISSUE TITLE
Errors occurred while placing items for sale on AH. (Current Twitch alpha)

### ISSUE THREAD

**Issue by Ookami313** [Auctionator/Auctionator#448]
Using the most recent (to my knowledge) Twitch alpha update. Received the following errors while putting items up for sale on the AH. Can't specifically remember what I did when they occurred, but it could be either dropping the item in the sell slot or mousing over the UI when going back to my bags to grab another item. If it helps, I was selling profession patterns. Thanks.

Date: 2020-01-28 22:59:20
ID: 2
Error occured in: Global
Count: 1
Message: ...nterface\AddOns\Auctionator\Source\Tooltips\Main.lua line 44:
   attempt to perform arithmetic on local 'sellPrice' (a nil value)
Debug:
   [string "=(tail call)"]: ?
   [string "=[C]"]: ?
   [string "@Auctionator\Source\Tooltips\Main.lua"]:44: ShowTipWithPricing()
   [string "@Auctionator\Source\Tooltips\Hooks.lua"]:10:
      ...terface\AddOns\Auctionator\Source\Tooltips\Hooks.lua:3
   [string "=[C]"]: ?
   [string "=[C]"]: ?
   [string "=[C]"]: ?
   [string "=[C]"]: ?
   [string "@TradeSkillMaster\LibTSM\Service\ItemTooltipClasses\Wrapper.lua"]:89:
      ...Master\LibTSM\Service\ItemTooltipClasses\Wrapper.lua:87
   [string "=[C]"]: ?
   [string "=[C]"]: ?
   [string "=[C]"]: ?
   [string "=[C]"]: SetBagItem()
   [string "@..\FrameXML\ContainerFrame.lua"]:1413: ContainerFrameItemButton_OnEnter()
   [string "*:OnEnter"]:1:
      [string "*:OnEnter"]:1
Locals:
(*temporary) = true
(*temporary) = <function> defined =[C]:-1

Date: 2020-01-28 23:02:35
ID: 3
Error occured in: Global
Count: 1
Message: ...dOns\Auctionator\Source\Utilities\ItemIdFromLink.lua line 2:
   bad argument #1 to 'find' (string expected, got nil)
Debug:
   [string "=(tail call)"]: ?
   [string "=[C]"]: ?
   [string "=[C]"]: find()
   [string "@Auctionator\Source\Utilities\ItemIdFromLink.lua"]:2: ItemIdFromLink()
   [string "@Auctionator\Source\Tooltips\Hooks.lua"]:243:
      ...terface\AddOns\Auctionator\Source\Tooltips\Hooks.lua:241
   [string "=[C]"]: ?
   [string "=[C]"]: ?
   [string "=[C]"]: ?
   [string "=[C]"]: ?
   [string "@TradeSkillMaster\LibTSM\Service\ItemTooltipClasses\Wrapper.lua"]:89:
      ...Master\LibTSM\Service\ItemTooltipClasses\Wrapper.lua:87
   [string "=[C]"]: ?
   [string "=[C]"]: ?
   [string "=[C]"]: ?
   [string "=[C]"]: ?
   [string "=[C]"]: ?
   [string "=[C]"]: SetHyperlink()
   [string "@WQAchievements\WQAchievements.lua"]:1898: _OnEnter_func()
   [string "@BattlePetCount\Libs\LibQTip-1.0\LibQTip-1.0.lua"]:1321:
      ...dOns\BattlePetCount\Libs\LibQTip-1.0\LibQTip-1.0.lua:1315
Locals:
(*temporary) = true
(*temporary) = <function> defined =[C]:-1

AddOns:

**Comment by plusmouse** [comment]
This has been fixed in an alpha available on our discord #alpha-version-releases channel. Waiting for testing before pushing that to twitch.
