### ISSUE TITLE
Auctionator errors under WoW under 8.3.0

### ISSUE THREAD

**Issue by doutrnz** [Auctionator/Auctionator#449]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

Auctionator errors under WoW under 8.3.0

## Steps to Reproduce

Open up the Auction House or right click an auctioneer in-game

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

Date: 2020-01-28 21:05:01
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Auctionator\AuctionatorFilters.lua line 70:
   attempt to call global 'GetAuctionItemSubClasses' (a nil value)
Debug:
   [string "@Auctionator\AuctionatorFilters.lua"]:70: GenerateSubClasses()
   [string "@Auctionator\AuctionatorFilters.lua"]:98: in main chunk
Locals:
classID = 2
parentName = "Weapon"
parentKey = "Weapon"
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = 2
(*temporary) = "attempt to call global 'GetAuctionItemSubClasses' (a nil value)"

AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  ArkInventory, v30913
  ArkInventoryRules, v20000
  ArkInventoryRulesExample, v20000
  ArkInventorySearch, v20000
  Auctionator, v8.2.0
  BlizRuntimeLib_enUS v8.3.0.80300 <none>
  (ck=dc)

**Comment by plusmouse** [comment]
It looks like you're using an 8.2 version of Auctionator, which is known to be broken. Work is ongoing to get a version ready for 8.3, see the discord for alphas.
