### ISSUE TITLE
Subcategires

### ISSUE THREAD

**Issue by ghost** [Auctionator/Auctionator#45]
I want to request subcategories for subcategories in the Weapon and armor category. As of today, you can only search for "Armor/Cloth/....", while i want to search for "Armor/Cloth/Head/...". This would make it alot easyer to find pices that you are looking for

**Comment by jrob8577** [comment]
Thanks for the feature request! I'm going to start with bug fixes in the next week or so, but I'll be happy to consider these enhancements after I've caught up with bugs!

**Comment by jrob8577** [comment]
This should be doable in a post legion release, but will require some updates to the `QueryAuctionItems` calls to take the inventorySlot param into account.  Will need to update drop down in advanced search dialog, and add these filters.
