### ISSUE TITLE
auctionator command lines?

### ISSUE THREAD

**Issue by doutrnz** [Auctionator/Auctionator#450]
I hope this question has a simple solution. Are there command lines you can use to launch things like "Database scan" or "Scan" to update Auctionator? If so, may I have the list of command lines? Right now, most settings are being worked on but the notes say scan works. I don't see scan anywhere when I open addons or when I type "auctionator /help" in the chat window. Thanks everyone!!

**Comment by jrob8577** [comment]
In the alpha version, the scan runs anytime you open the AH, so long as you have not completed a scan in the last 15 minutes. Update scan information should show up in tooltips. We are working on additional features, but this is all we have released so far.
