### ISSUE TITLE
AH price is missing from some tooltips. (maybe a solution)

### ISSUE THREAD

**Issue by Tarkumi** [Auctionator/Auctionator#451]
Hello,

If I mouse over an item icon in the profession windows (reagent or product) the tooltip not contains the price for the item.

If you hook the GameToolTip's OnTooltipSetItem script, maybe you get more reliable results.

For example:

`GameTooltip:HookScript("OnTooltipSetItem", T_SetStuff)
ItemRefTooltip:HookScript("OnTooltipSetItem", T_SetStuff)
ItemRefShoppingTooltip1:HookScript("OnTooltipSetItem", T_SetStuff)
ItemRefShoppingTooltip2:HookScript("OnTooltipSetItem", T_SetStuff)
ShoppingTooltip1:HookScript("OnTooltipSetItem", T_SetStuff)
ShoppingTooltip2:HookScript("OnTooltipSetItem", T_SetStuff)

local function T_SetStuff(self)
	if self:IsForbidden() then return end
	local _, link = self:GetItem()
	if  link then
		local itemid = string.match(link, "|c.+|Hitem:([0-9]+):(.+)|h%[(.+)%]|h|r")
		if (itemid) then
			Set the tooltip.
		end
	end
end

`

**Comment by jrob8577** [comment]
Thanks for the recommendation @Tarkumi I'll investigate this evening!

**Comment by plusmouse** [comment]
This bug is new. The last alpha didn't have this problem - I used the tooltips to decide which potions to craft.

**Comment by plusmouse** [comment]
Tested profession windows, the tooltips still show.
