### ISSUE TITLE
Removing item from shopping list using remove button

### ISSUE THREAD

**Issue by DiscordGregory** [Auctionator/Auctionator#453]
When I open a shopping list, go to the bottom of the list and click the remove entry button I get this error. Only other addons are bugsack/grabber

2x SharedXML\ScrollList.lua:166: Scroll list has not been initialized. This should generally happen in OnShow.
[string "=[C]"]: in function `error'
[string "@SharedXML\ScrollList.lua"]:166: in function `RefreshScrollFrame'
[string "@Auctionator\Source\ShoppingLists\ShoppingListMixins.lua"]:23: in function `update'
[string "@SharedXML\HybridScrollFrame.lua"]:193: in function `HybridScrollFrame_SetOffset'
[string "@SharedXML\HybridScrollFrame.lua"]:30: in function <SharedXML\HybridScrollFrame.lua:29>
[string "=[C]"]: in function `SetMinMaxValues'
[string "@SharedXML\HybridScrollFrame.lua"]:243: in function `HybridScrollFrame_CreateButtons'
[string "@Auctionator\Source\ShoppingLists\ShoppingListMixins.lua"]:29: in function `Init'
[string "@Auctionator\Source\ShoppingLists\ShoppingListMixins.lua"]:14: in function `Reset'
[string "@Auctionator\Source\ShoppingLists\Main.lua"]:172: in function `RemoveItem'
[string "@Auctionator\Source\ShoppingLists\ShoppingListMixins.lua"]:81: in function `DeleteButtonClicked'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals:
(*temporary) = "Scroll list has not been initialized. This should generally happen in OnShow."

**Comment by jrob8577** [comment]
@DiscordGregory When you say "remove entry button" do you mean this (picture attached):
<img width="479" alt="remove entry button qq" src="https://user-images.githubusercontent.com/838110/74078907-0fd24b80-49e5-11ea-9843-bd38c1143dcb.png">

**Comment by DiscordGregory** [comment]
Yes
