### ISSUE TITLE
Issue: commit b54502e #1

### ISSUE THREAD

**Issue by vandiel01** [Auctionator/Auctionator#457]
57x ...dOns\Auctionator\Source\Utilities\ItemIdFromLink.lua:2: bad argument #1 to 'find' (string expected, got nil)
[string "=[C]"]: in function `find'
[string "@Auctionator\Source\Utilities\ItemIdFromLink.lua"]:2: in function `ItemIdFromLink'
[string "@Auctionator\Source\Tooltips\Hooks.lua"]:243: in function <Auctionator\Source\Tooltips\Hooks.lua:241>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `pcall'
[string "@AllTheThings\AllTheThings-2.0.1b.lua"]:8865: in function <AllTheThings\AllTheThings.lua:8822>

Locals:
(*temporary) = nil
(*temporary) = "^|c%x+|H(.+)|h%[.*%]"
(*temporary) = "string expected, got nil"

**Comment by plusmouse** [comment]
Duplicate of #440
