### ISSUE TITLE
Issue: commit b54502e #2

### ISSUE THREAD

**Issue by vandiel01** [Auctionator/Auctionator#458]
1x Auctionator\AuctionatorConfig.lua:998: attempt to index local 'lineEntry' (a nil value)
[string "@Auctionator\AuctionatorConfig.lua"]:998: in function `Atr_ShpLists_Display'
[string "@Auctionator\AuctionatorConfig.lua"]:972: in function `Atr_ShpList_Options_Update'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

Locals:
sllist = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
}
totalRows = 2
line = nil
dataOffset = 1
(for index) = 1
(for limit) = 18
(for step) = 1
line = 1
lineEntry = nil
(*temporary) = "Atr_ShpList1"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'lineEntry' (a nil value)"
kShpLists_NumShpLists = 3
kShpLists_LinesToDisplay = 18
zc = <table> {
 IsEnglishLocale = <function> defined @Auctionator\Source\Localization\Main.lua:67
 msg_red = <function> defined @Auctionator\zcUtils.lua:570
 TrimBrackets = <function> defined @Auctionator\zcUtils.lua:955
 tallyAdd = <function> defined @Auctionator\zcUtils.lua:1108
 msg_yellow = <function> defined @Auctionator\zcUtils.lua:572
 msg = <function> defined @Auctionator\zcUtils.lua:699
 GetArrayElemOrFirst = <function> defined @Auctionator\zcUtils.lua:136
 NumToBool = <function> defined @Auctionator\zcUtils.lua:524
 printmem = <function> defined @Auctionator\zcUtils.lua:1018
 ParseBattlePetLink = <function> defined @Auctionator\zcUtils.lua:417
 ShowHide = <function> defined @Auctionator\zcUtils.lua:33
 StringStartsWith = <function> defined @Auctionator\zcUtils.lua:892
 StringEndsWith = <function> defined @Auctionator\zcUtils.lua:872
 round = <function> defined @Auctionator\zcUtils.lua:564
 CopyDeep = <function> defined @Auctionator\zcUtils.lua:984
 ClearTable = <function> defined @Auctionator\zcUtils.lua:975
 CheckDeferredCall = <function> defined @Auctionator\zcUtils.lua:320
 priceToMoneyString = <function> defined @Auctionator\zcUtils.lua:803
 tallyPrint = <function> defined @Auctionator\zcUtils.lua:1120
 TrimQuotes = <function> defined @Auctionator\zcUtils.lua:935
 GetArrayElemOrNil = <function> defined @Auctionator\zcUtils.lua:151
 BoolToNum = <function> defined @Auctionator\zcUtils.lua:514
 If = <function> defined @Auctionator\zcUtils.lua:107
 periodic = <function> defined @Auctionator\zcUtils.lua:343
 Min = <function> defined @Auctionator\zcUtils.lua:77
 msg_pink = <function> defined @Auctionator\zcUtils.lua:571
 SetTextIf = <function> defined @Auctionator\zcUtils.lua:44
 QuoteString = <function> defined @Auctionator\zcUtils.lua:923
 msg_str = <function> defined @Auctionator\zcUtils.lua:589
 ItemNamefromLink = <function> defined @Auctionator\zcUtils.lua:447
 enc64 = <function> defined @Auctionator\zcUtils.lua:201
 Val = <function> defined @Auctionator\zcUtils.lua:55
 IsBattlePetLink = <function> defined @Auctionator\zcUtils.lua:409
 msg_ex = <function> defined @Auctionator\zcUtils.lua:708
 printableLink = <function> defined @Auctionator\zcUtils.lua:1005
 PrintTable = <function> defined @Auctionator\zcUtils.lua:373
 StringContains = <function> defined @Auctionator\zcUtils.lua:854
 StringSame = <function> defined @Auctionator\zcUtils.lua:836
 PullItemIntoMemory = <function> defined @Auctionator\zcUtils.lua:482
 priceToString = <function> defined @Auctionator\zcUtils.lua:767
 PrintKeysSorted = <function> defined @Auctionator\zcUtils.lua:118
 val2gsc = <function> defined @Auctionator\zcUtils.lua:749
 Negate = <function> defined @Auctionator\zcUtils.lua:534
 IsTextQuoted = <function> defined @Auctionator\zcUtils.lua:916
 BoolToString = <function> defined @Auctionator\zcUtils.lua:504

**Comment by plusmouse** [comment]
What were you doing when this happened?

**Comment by vandiel01** [comment]
Scanning for item from the ATT list or bag by "Shift Click" and it copy the word of the item to search window and it goes into a "circling loop" and the error would appear.   Same goes with the previous commit error, gives me both

**Comment by plusmouse** [comment]
This bug affects old code that will be replaced
