### ISSUE TITLE
Attempting to Scan too Frequently 

### ISSUE THREAD

**Issue by vandiel01** [Auctionator/Auctionator#459]
Recent Commit is attempting to scan, everytime i close/reopen the AH and may caused the error in #1 and #2 of my previous commit #457 where it cannot go to "find next"

**Comment by plusmouse** [comment]
What do you mean by "attempting to scan". Any chat messages, etc. indicating that this is the case.

**Comment by vandiel01** [comment]
Just woke up, but Yeah its telling me "Will do scan in xx minutes" or the like everytime I open the AH

**Comment by plusmouse** [comment]
That's a feature.
