### ISSUE TITLE
[8.3 Suggestion] Observations as Buyer

### ISSUE THREAD

**Issue by Drkangl32** [Auctionator/Auctionator#465]
As buyer I notice that nearly everything adheres to the "last in, first out" rule.  We are presented with merged stacks and not given the option to pick and choose.  

The only big exception I have seen is with gear and pets.  These are listed independently for the buyer (no stacks) because like items within these categories could come with different variables.  In the case of pets: breed, rarity and level.  In the case of gear: stats, level, etc.  With these specific categories we still have significant undercut competition to contend with.

Considering this, you might look at designing the undercut feature to have a toggle for undercuts on all items or undercuts only on gear and pets.  

Not entirely sure I got this all right.  Just an observation.

**Comment by plusmouse** [comment]
Linked to undercut implementation tracking issue. Closing.
