### ISSUE TITLE
Advanced search

### ISSUE THREAD

**Issue by plusmouse** [Auctionator/Auctionator#477]
Imagery from 8.2 release
![image](https://user-images.githubusercontent.com/60280559/74614721-3fcecc80-5112-11ea-97bf-1f9a09d1a9d5.png)

**Comment by rodalpho** [comment]
This is a primary feature for me, for example I have shopping lists with:

;Gem;0;0;115;120 -- To only show BFA gems and remove all the previous expansion garbage I don't want.

Will this or something similar be supported in the 8.3 release?

**Comment by plusmouse** [comment]
We're working on it. A limited version (not released yet) has everything except category selection working.

**Comment by plusmouse** [comment]
If you have more example terms you use I'd find them useful so that I can verify they get the results you want 🙂

**Comment by rodalpho** [comment]
Great to hear! I actually have a bunch of saved searches for enchants, gems, etc, but they all use the same level filter.

**Comment by plusmouse** [comment]
It would be amazing if you could post them here (or send them to me on discord plusmouse#7683 if you don't want them public)

**Comment by rodalpho** [comment]
Sure, image is here:

![Annotation 2020-02-23 105117](https://user-images.githubusercontent.com/747832/75115225-7a60c980-562a-11ea-9234-201bf96f558e.jpg)

**Comment by plusmouse** [comment]
That is useful. Just realized that I got the level parameters in the wrong place in the rewrite - the old code isn't always clear 😉.

I'll be working on this today (just so you know)

**Comment by rodalpho** [comment]
My pleasure to help, thanks for the addon-- I've been using it for like a decade!

**Comment by rodalpho** [comment]
This still isn't working as of the latest alpha, FYI.

**Comment by plusmouse** [comment]
The visual for an advanced search term has changed, but it should still work

**Comment by rodalpho** [comment]
Happy to test out whatever string you provide, how do I search for all gems with itemlvl 115-120?

**Comment by plusmouse** [comment]
This is #539 (pretty look).

Enchants and gems don't work - the blizzard API gives them as level 1 or 0

Gear and contracts do have level searches though

**Comment by rodalpho** [comment]
Ahhhhh. So it can't be done. Damn. That's basically all I use advanced searches for.

**Comment by plusmouse** [comment]
Basically it's "not our bug" we're waiting for blizzard to correct their API

**Comment by plusmouse** [comment]
I did know they didn't work and spent some time on it (I had your search terms) but there isn't a good way to do it

**Comment by rodalpho** [comment]
Gotcha. Thanks anyway.
