### ISSUE TITLE
Historical price data from scans (day-by-day)

### ISSUE THREAD

**Issue by plusmouse** [Auctionator/Auctionator#479]

**Comment by raysmith59** [comment]
This is probably the time to ask - one of the things I didn't like about Auctionator 8.2 was the way it handled situations where the only listing for an item is mine.  In that scenario I would like my listings to be handled like any other listing, including my previous listing price being the default price the next time it's listed if it doesn't sell.  I could sometimes work around this via one of the other tabs but it didn't always show every price I'd listed for.

Also, per-server storage and display of historical and personal listing prices.

**Comment by plusmouse** [comment]
Thanks for the feedback.

The way it's set at the moment it includes your auctions in the historic data, and is per realm. We just don't have the UI for showing it at the moment.
