### ISSUE TITLE
Sellling tab settings

### ISSUE THREAD

**Issue by BanditBanditBandit** [Auctionator/Auctionator#50]
It is awesome to see new blood on this addon, it has been my FAVORITE by far compared to the other AH addons. Simple and does exactly what its supposed to. The few things I could recommend for this addon is a setting to automatically post Max stacks + Leftovers or if not that, maybe a setting that will set the # of stacks to the max for all items that don't have a specific behavior. on that same topic, adding new categories of items into the selling list would be nice, instead of only being able to add in items specifically. 

The other topic of suggestion would be support for an addon called LinkWrangler. It allows you to open up sever items on your screen at one time, it is very useful for going to the AH with things you need to pick up, or comparing a whole set of armor on the screen at one time. Its great, I love it. But I cannot use it. I cannot use the addon because it doesnt work with this one, and I absolutely NEED this addon. The author of the addon has the instructions on his page on how to support the multiple tooltips that will be on the screen. I tried to inquire about this a year ago, but it was never pursued.

**Comment by jrob8577** [comment]
Thanks for the suggestion!  I'm including some links for myself here for when I can get around to doing some feature additions:

LinkWrangler core
http://www.curse.com/addons/wow/link-wrangler-1-7

It appears that Auctioneer has implemented this via an additional addon:
http://www.curse.com/addons/wow/linkwrangler_auctioneer

In the addon source:
Developer.htm : documentation of the LinkWrangler callback API, and all other exports, for AddOn authors
