### ISSUE TITLE
multiple LUA errors at character login

### ISSUE THREAD

**Issue by PsiloCA** [Auctionator/Auctionator#510]
Please include as much of the following information as possible to help me fix the bug:
Lua Errors at startup

Message: Interface\AddOns\Auctionator\AuctionatorFilters.lua:70: attempt to call global 'GetAuctionItemSubClasses' (a nil value)
Time: Sat Feb 22 20:17:40 2020
Count: 1
Stack: Interface\AddOns\Auctionator\AuctionatorFilters.lua:70: attempt to call global 'GetAuctionItemSubClasses' (a nil value)
[string "@Interface\AddOns\Auctionator\AuctionatorFilters.lua"]:70: in function `GenerateSubClasses'
[string "@Interface\AddOns\Auctionator\AuctionatorFilters.lua"]:98: in main chunk

Locals: classID = 2
parentName = "Weapon"
parentKey = "Weapon"
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = 2
(*temporary) = "attempt to call global 'GetAuctionItemSubClasses' (a nil value)"

#2

Message: Interface\AddOns\Auctionator\Auctionator.lua:146: Attempt to register unknown event "AUCTION_ITEM_LIST_UPDATE"
Time: Sat Feb 22 20:17:40 2020
Count: 1
Stack: Interface\AddOns\Auctionator\Auctionator.lua:146: Attempt to register unknown event "AUCTION_ITEM_LIST_UPDATE"
[string "=[C]"]: in function `RegisterEvent'
[string "@Interface\AddOns\Auctionator\Auctionator.lua"]:146: in function `Atr_RegisterEvents'
[string "*:OnLoad"]:1: in function <[string "*:OnLoad"]:1>

Locals: (*temporary) = Atr_core {
0 = <userdata>
}
(*temporary) = "AUCTION_ITEM_LIST_UPDATE

#3

Message: Interface\AddOns\Auctionator\AuctionatorHints.lua:505: hooksecurefunc(): SetAuctionItem is not a function
Time: Sat Feb 22 20:17:40 2020
Count: 1
Stack: Interface\AddOns\Auctionator\AuctionatorHints.lua:505: hooksecurefunc(): SetAuctionItem is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "@Interface\AddOns\Auctionator\AuctionatorHints.lua"]:505: in main chunk

Locals:

1 more when i click on Shopping Lists

Message: Interface\AddOns\Auctionator\AuctionatorConfig.lua:998: attempt to index local 'lineEntry' (a nil value)
Time: Sat Feb 22 20:21:02 2020
Count: 1
Stack: Interface\AddOns\Auctionator\AuctionatorConfig.lua:998: attempt to index local 'lineEntry' (a nil value)
[string "@Interface\AddOns\Auctionator\AuctionatorConfig.lua"]:998: in function `Atr_ShpLists_Display'
[string "@Interface\AddOns\Auctionator\AuctionatorConfig.lua"]:972: in function `Atr_ShpList_Options_Update'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

Locals: sllist = <table> {
1 = <table> {
}
}
totalRows = 0
line = nil
dataOffset = 1
(for index) = 1
(for limit) = 18
(for step) = 1
line = 1
lineEntry = nil
(*temporary) = "Atr_ShpList1"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'lineEntry' (a nil value)"
kShpLists_NumShpLists = 1
kShpLists_LinesToDisplay = 18
zc = <table> {
IsEnglishLocale = <function> defined @Interface\AddOns\Auctionator\AuctionatorLocalize.lua:63
msg_red = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:570
TrimBrackets = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:955
tallyAdd = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:1108
msg_yellow = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:572
msg = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:699
GetArrayElemOrFirst = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:136
NumToBool = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:524
printmem = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:1018
ParseBattlePetLink = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:417
ShowHide = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:33
StringStartsWith = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:892
StringEndsWith = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:872
round = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:564
CopyDeep = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:984
ClearTable = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:975
CheckDeferredCall = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:320
priceToMoneyString = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:803
tallyPrint = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:1120
TrimQuotes = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:935
GetArrayElemOrNil = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:151
BoolToNum = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:514
If = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:107
periodic = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:343
Min = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:77
msg_pink = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:571
SetTextIf = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:44
QuoteString = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:923
msg_str = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:589
ItemNamefromLink = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:447
enc64 = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:201
Val = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:55
IsBattlePetLink = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:409
msg_ex = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:708
printableLink = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:1005
PrintTable = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:373
StringContains = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:854
StringSame = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:836
PullItemIntoMemory = <function

_Please include a brief description of the bug, including what you were doing, and when it occurred._

Logging in. nothing shows up on AH page but Auctionator does appear to allow access to settings.

_Include the steps I would need to follow to reproduce the bug._

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._
I tried with some loaded and none loaded. tried deleteing and reloading 

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by jrob8577** [comment]
Please install the alpha

**Comment by PsiloCA** [comment]
can i reply to this email?

**Comment by jrob8577** [comment]
@PsiloCA I prefer you join [Discord](https://discord.gg/xgz75Pp) and we can have a conversation there.

**Comment by PsiloCA** [comment]
ya i cant verify my cellphone right now cuz i cant find the damn thing or i
would :P
