### ISSUE TITLE
Shopping Lists configuration feedback

### ISSUE THREAD

**Issue by jrob8577** [Auctionator/Auctionator#519]
Need help documenting all of the settings that were previously on this configuration page. Add what your remember in the comments!
<img width="809" alt="Shopping Lists" src="https://user-images.githubusercontent.com/838110/75118089-b5173180-562b-11ea-9cbc-35390b483736.png">

**Comment by zalidthebur** [comment]
Delete = Delete a shopping list.
Edit = Choose shopping list and edit the contents in a wordpad type environment.
Rename = Rename shopping list.
New = Create a new shopping list.
Import/Export = Never used so not too sure. But I guess it was a way to import/export a shopping list ?
