### ISSUE TITLE
New Call to Arms quests in 8.3 not being tracked

### ISSUE THREAD

**Issue by DeeRez** [Auctionator/Auctionator#521]
Patch 8.3 added new Call to Arms quests which aren't currently tracked

Call to Arms : Vale of Eternal Blossoms - Horde: https://www.wowhead.com/quest=59017
Call to Arms : Vale of Eternal Blossoms - Alliance: https://www.wowhead.com/quest=59018
Call to Arms: Uldum - Horde: https://www.wowhead.com/quest=59016
Call to Arms: Uldum - Alliance: https://www.wowhead.com/quest=59019

**Comment by plusmouse** [comment]
This has nothing to do with Auctionator. Closing
