### ISSUE TITLE
Remove copper price in tooltip

### ISSUE THREAD

**Issue by flow0284** [Auctionator/Auctionator#527]
It would be nice, if it was possible to remove the copper priceinformation in the tooltip from auctionprice. since the new auctionhouse dont support copper ;)

**Comment by plusmouse** [comment]
That would make a lot of sense

**Comment by jrob8577** [comment]
Its possible, but the alignment looks terrible with the vendor price. Gonna close this; we can revisit later if we come up with a good idea that doesn't look bad.
