### ISSUE TITLE
Open bags obscure shopping lists

### ISSUE THREAD

**Issue by Tarkumi** [Auctionator/Auctionator#533]
When I open the AH and open bags, the bags are overlapping the AuctionHouse frame, including the shopping list.

When I click on the AH frame, it comes to foreground, but the shopping list doesn't when clicked, remaining obscured.

I included two screenshots to show the problem.
![Bag in foreground](https://user-images.githubusercontent.com/455295/75607693-1f334900-5afa-11ea-8fb4-26c1395f3cf9.jpg)
![Bag should be in background](https://user-images.githubusercontent.com/455295/75607695-24909380-5afa-11ea-9505-f533288e866f.jpg)

**Comment by jrob8577** [comment]
@Tarkumi What bag addon is this? Want to be able to test with it.

**Comment by Tarkumi** [comment]
It's BaudBag, also the bug present with Skillet too.

**Comment by b-morgan** [comment]
I can confirm that the bug is present with [Skillet](https://www.wowace.com/projects/skillet). I just finished converting Skillet's Auctionator plugin to work with the new API (Skillet-r809-alpha, Auctionator-alpha-0.0.50)

**Comment by plusmouse** [comment]
We're reworking the Auctionatator UI (again), and the sidebar is being removed (making this a non-issue).
