### ISSUE TITLE
Shopping list doesn't always display all items searched

### ISSUE THREAD

**Issue by zalidthebur** [Auctionator/Auctionator#534]
When I click a shopping list, auctionator goes through the process of checking for each item as it always has done. But in the past it used to display all the items in one list. I thought this functionality had disappeared and was patiently waiting to see if would return when I accidentally found that it is actually there now but not working correctly. If you have a window other than “Buy” open when you click the shopping list and then open the “Buy” window, the list is there in all its glory. If you have the “Buy” window open when you do this, then only the last item is displayed.
Any chance this can work in the "Buy" window ?
See screenshots below :
<a href="https://imgur.com/D6V0gxo"><img src="https://i.imgur.com/D6V0gxo.jpg" title="source: imgur.com" /></a>
<a href="https://imgur.com/YEZ6qe4"><img src="https://i.imgur.com/YEZ6qe4.jpg" title="source: imgur.com" /></a>

**Comment by plusmouse** [comment]
What alpha are you using?

**Comment by zalidthebur** [comment]
Altoholic-8.3-002

**Comment by plusmouse** [comment]
OK. Can you try with the latest release from #alpha-version-releases on [discord ](https://discord.gg/z7hWDSk)

**Comment by zalidthebur** [comment]
Just tried with alpha-0.0.25 adn still the same.

**Comment by plusmouse** [comment]
Have you tested with no other addons enabled? And installed BugSack (and report any errors it gives)

**Comment by zalidthebur** [comment]
I'll try tomorrow and let you know. Off to bed now :-)

**Comment by zalidthebur** [comment]
It's Auctioneer Core.

**Comment by plusmouse** [comment]
As this is a result of another ah add-on it is outside our current scope to make the alpha compatible. Will keep this under review. Closing.

**Comment by zalidthebur** [comment]
Seems to now be working with Auctioneer running. No idea why :D
