### ISSUE TITLE
Failed to work

### ISSUE THREAD

**Issue by Ixidor52** [Auctionator/Auctionator#538]
## Brief Description of Bug

enter game and go to auctioneer in game and the auctionator is not working.

## Steps to Reproduce

enable auctionator and all addons that came with it.  also enable buggrabber and bugsack.
enter game and you will have 3 errors occur.  i have had the issue occur when just auctionator is enabled or in any combo with other listed addons.

## Loaded Addons

i have !BugGrabber-v8.2.1, BugSack-v8.2.0, Rematch_4_10_1, Recount-v8.3.0b, Peddler-6.1, Gatherer-7.3.1, CanIMogIt-8.3.0v1.25, and Auctionator+8.2.0

## Back Trace (LUA Error Output)

[17:20:46][Junnantasa] says: 0
[17:21:27]7x Auctionator\AuctionatorFilters.lua:70: attempt to call global 'GetAuctionItemSubClasses' (a nil value)
[string "@Auctionator\AuctionatorFilters.lua"]:70: in function `GenerateSubClasses'
[string "@Auctionator\AuctionatorFilters.lua"]:98: in main chunk

Locals:
classID = 2
parentName = "Weapon"
parentKey = "Weapon"
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = 2
(*temporary) = "attempt to call global 'GetAuctionItemSubClasses' (a nil value)"

[17:21:28]7x Auctionator\Auctionator-8.2.0.lua:146: Attempt to register unknown event "AUCTION_ITEM_LIST_UPDATE"
[string "=[C]"]: in function `RegisterEvent'
[string "@Auctionator\Auctionator-8.2.0.lua"]:146: in function `Atr_RegisterEvents'
[string "*:OnLoad"]:1: in function <[string "*:OnLoad"]:1>

Locals:
(*temporary) = Atr_core {
 0 = <userdata>
}
(*temporary) = "AUCTION_ITEM_LIST_UPDATE"
[17:21:29]7x Auctionator\AuctionatorHints.lua:505: hooksecurefunc(): SetAuctionItem is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "@Auctionator\AuctionatorHints.lua"]:505: in main chunk

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by plusmouse** [comment]
[See here](https://github.com/Auctionator/Auctionator/wiki/The-8.3-Release)
