### ISSUE TITLE
Random disconnect after manual fullscan (Thrall-EU)

### ISSUE THREAD

**Issue by flow0284** [Auctionator/Auctionator#541]

**Comment by Neurotoxin001** [comment]
Same

**Comment by flow0284** [comment]
Since a couple of alpha builds the random disconnect while/after a manual scan was solved for me.

**Comment by Neurotoxin001** [comment]
So if I just scroll all items on AH manually without pressing scan button addon will get all new prices? Because it's simpler and faster and without disconnects then pressing the button.

**Comment by plusmouse** [comment]
That does work. Although, fingers crossed, the latest alpha on discord fixes the issue.

**Comment by plusmouse** [comment]
As the original poster no longer has the issue, closing

**Comment by Neurotoxin001** [comment]
8.3.0.7 still disconnects

**Comment by plusmouse** [comment]
Can you try Shift+Clicking the scan button - it does the scan in a slower way that's less likely to disconnect

**Comment by Neurotoxin001** [comment]
It's ok, but it's super slow, I can scroll all items manually faster

**Comment by plusmouse** [comment]
You could try reducing the full scan step size in advanced settings - lower values can help with disconnects

**Comment by Neurotoxin001** [comment]
It's disconnects even with 200 (250 was default)

**Comment by plusmouse** [comment]
Beyond "use the slow scan mode" we don't have any good solutions at the moment. We did speak to a dev about making the "fast scan" work, but making the changes they suggested to our code would have resulted in a 8 hour (not a typo) scan in some cases.
