### ISSUE TITLE
In the auction hause should be 3 more tabs because of the addon but I didn´t find any option to turn them on. I tried older versions and turned every other addon off but that didn´t help. 

### ISSUE THREAD

**Issue by KayKa13** [Auctionator/Auctionator#545]
Please include as much of the following information as possible to help me fix the bug:

The 3 extra auction house tabs weren´t there

_Please include a brief description of the bug, including what you were doing, and when it occurred._

## Steps to Reproduce

_Include the steps I would need to follow to reproduce the bug._

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by plusmouse** [comment]
https://github.com/Auctionator/Auctionator/wiki/The-8.3-Release
