### ISSUE TITLE
Auctionator isn't loading for me

### ISSUE THREAD

**Issue by lorddev** [Auctionator/Auctionator#548]
Please include as much of the following information as possible to help me fix the bug:

![image](https://user-images.githubusercontent.com/2220085/75940088-e7513c00-5e40-11ea-8d54-586e5e69c879.png)

## Brief Description of Bug

When I talk to an auctioneer, Auctionator doesn't load.

## Steps to Reproduce

When I talk to an auctioneer

## Loaded Addons

![image](https://user-images.githubusercontent.com/2220085/75940191-36976c80-5e41-11ea-9cff-d581e2d2d242.png)

![image](https://user-images.githubusercontent.com/2220085/75940207-3dbe7a80-5e41-11ea-8a69-7462fb9eab9c.png)

![image](https://user-images.githubusercontent.com/2220085/75940222-4b740000-5e41-11ea-82e1-179366da8d53.png)

![image](https://user-images.githubusercontent.com/2220085/75940234-54fd6800-5e41-11ea-92e3-7e25f709667f.png)

I know, that's a lot of addons. I disabled most and tried to load again but couldn't.

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

Three errors can be seen in this screenshot:

![image](https://user-images.githubusercontent.com/2220085/75940300-80805280-5e41-11ea-812c-66bc0b796650.png)

P.S. Thanks for all your hard work over the years!

**Comment by lorddev** [comment]
```
2x Auctionator\AuctionatorFilters.lua:70: attempt to call global 'GetAuctionItemSubClasses' (a nil value)
[string "@Auctionator\AuctionatorFilters.lua"]:70: in function `GenerateSubClasses'
[string "@Auctionator\AuctionatorFilters.lua"]:98: in main chunk

Locals:
classID = 2
parentName = "Weapon"
parentKey = "Weapon"
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = 2
(*temporary) = "attempt to call global 'GetAuctionItemSubClasses' (a nil value)"
```
---
```
2x Auctionator\Auctionator-8.2.0.lua:146: Attempt to register unknown event "AUCTION_ITEM_LIST_UPDATE"
[string "=[C]"]: in function `RegisterEvent'
[string "@Auctionator\Auctionator-8.2.0.lua"]:146: in function `Atr_RegisterEvents'
[string "*:OnLoad"]:1: in function <[string "*:OnLoad"]:1>

Locals:
(*temporary) = Atr_core {
 0 = <userdata>
}
(*temporary) = "AUCTION_ITEM_LIST_UPDATE"
```
---
```
2x Auctionator\AuctionatorHints.lua:505: hooksecurefunc(): SetAuctionItem is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "@Auctionator\AuctionatorHints.lua"]:505: in main chunk

Locals:

```

**Comment by jrob8577** [comment]
Please visit us in [the Discord server](https://discord.gg/xgz75Pp); you must use the alpha release for 8.3, and the alpha does not have the same UI as the previous version.
