### ISSUE TITLE
"fatality" lUa errors on Load In (8 individual Errors) 

### ISSUE THREAD

**Issue by rottenheals** [Auctionator/Auctionator#553]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

Fatality Lua Error sound upon load-in to wow with latest ALPHA  0.0.26

_Please include a brief description of the bug, including what you were doing, and when it occurred._

## Steps to Reproduce

Happens upon Load in to Game World

_Include the steps I would need to follow to reproduce the bug._

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._

ELvUI
ElvUI Add On Skins 
WEak Auras (latest)
Paste
BugSack / !Bug Grabber
Skada
Altaholic
Exorsus Raid Tools
DBM installed BUT deactivated
BigWigs & Little Wigs
Azurite Tool Tips
Clique
Auctionator (did not get same errors under previous ALPHA 0-0-12
Add On Control Panel
LIbSharedMEdia-3.0
Postal

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._
1x Error loading Auctionator\Source\Utilities\Slice.lua

1x Error loading Auctionator\Source\Utilities\Table.lua

1x Error loading Auctionator\Source\Utilities\StringContains.lua

1x Error loading Auctionator\Source\Search\Mixins\AdvancedSearchProviderMixin.lua

1x Error loading Auctionator\Source\Search\Main.lua

1x Error loading Auctionator\Source\Search\Filters-Filters.lua

2x SharedXML\Mixin.lua:28: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: in function `pairs'
[string "@SharedXML\Mixin.lua"]:28: in function <SharedXML\Mixin.lua:25>
[string "=(tail call)"]: ?
[string "@Auctionator\Source\ShoppingLists\Mixins\ScrollListLine.lua"]:1: in main chunk

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

**Comment by plusmouse** [comment]
Have you attempted to update the addon w/out restarting WoW?

**Comment by plusmouse** [comment]
This appears to be issue with how the alpha was installed. Closing.
