### ISSUE TITLE
Undercutting doesn't work for me.

### ISSUE THREAD

**Issue by lorddev** [Auctionator/Auctionator#556]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

Items aren't being undercut. See settings screen at 5%:

![image](https://user-images.githubusercontent.com/2220085/76171008-6b0e6f80-6144-11ea-8507-cd0ae09f29a2.png)

Now see auction screen which defaults prices to _the same as_ other auctions instead of cheaper.

## Steps to Reproduce

See screen shots above

## Loaded Addons

![image](https://user-images.githubusercontent.com/2220085/76171053-ad37b100-6144-11ea-809c-91ada0c31890.png)

![image](https://user-images.githubusercontent.com/2220085/76171056-b1fc6500-6144-11ea-9ad0-2b1cc5e943a6.png)

## Back Trace (LUA Error Output)

No bug caught by BugSack

**Comment by jrob8577** [comment]
Sine undercutting has not been implemented for 8.3 yet, this is not a bug. Please ask in Discord channel, or refer to list of completed 8.3 features (https://github.com/Auctionator/Auctionator/wiki/The-8.3-Release)
