### ISSUE TITLE
Wrong vendor price for some gear

### ISSUE THREAD

**Issue by clancyby** [Auctionator/Auctionator#557]
![vendor price 2020-03-09 025613](https://user-images.githubusercontent.com/61461975/76173583-a98e4380-61b1-11ea-8f32-e7048ee4bd39.png)
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

_Please include a brief description of the bug, including what you were doing, and when it occurred._

## Steps to Reproduce

_Include the steps I would need to follow to reproduce the bug._

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by jrob8577** [comment]
I'm going to need english translations of that tooltip to investigate.

**Comment by plusmouse** [comment]
This will be fixed in an upcoming release
