### ISSUE TITLE
Undercutting does not work in certain situations

### ISSUE THREAD

**Issue by Nillx** [Auctionator/Auctionator#565]
Undercutting does not actually undercut competitors if they listed an auction that have the same price as mine, even if i set a custom undercut amount (tried setting it at 5%, 1%, 1S). 

Example here:

Two people "undercut" me by posting items after mine
![2](https://user-images.githubusercontent.com/34476875/76310009-a345b780-62d6-11ea-8b87-d598330a9cc6.JPG)
Addon sets the same gold amount as my previous post
![1](https://user-images.githubusercontent.com/34476875/76310008-a2148a80-62d6-11ea-8abe-8b43714fd624.JPG)

Undercut value is set to 1s.

**Comment by plusmouse** [comment]
We'll look into it.
