### ISSUE TITLE
Shopping List not returning to Front Pane of AH

### ISSUE THREAD

**Issue by vandiel01** [Auctionator/Auctionator#570]
Not a bug maybe but... hard to explain..
1. Press on item in shopping list, will bring you to another pane to acquire said item...
2. (do not press back), press on other item and the previous pane will remain, hence pressing on shopping list will be useless if cannot see what's behind the pane...

Suggestion: return to main pane after pressing shopping list fires then return with result

**Comment by plusmouse** [comment]
In summary, when you search from the shopping list, it should change to the "Buy" tab.

**Comment by plusmouse** [comment]
As shopping list are in a tab now, this is no longer relevant
