### ISSUE TITLE
Alpha - LUA error when hovering over mail containing multiple items

### ISSUE THREAD

**Issue by raysmith59** [Auctionator/Auctionator#573]
My auction alt has a handful of stacks of different types of meat in one mail item that another alt sent to him, when I hover over that mail item I get this error:

47x Auctionator\Source\Tooltips\Main.lua:82: attempt to call field 'UtilitiesItemKeyFromLink' (a nil value)
[string "@Auctionator\Source\Tooltips\Main.lua"]:82: in function `ShowTipWithMultiplePricing'
[string "@Auctionator\Source\Tooltips\Hooks.lua"]:185: in function <Auctionator\Source\Tooltips\Hooks.lua:158>
[string "=[C]"]: in function `InboxFrameItem_OnEnter'
[string "@Postal\Modules\Express.lua"]:42: in function <Postal\Modules\Express.lua:41>
[string "=(tail call)"]: ?
[string "*:OnEnter"]:1: in function <[string "*:OnEnter"]:1>

Locals:
tooltipFrame = GameTooltip {
 0 = <userdata>
 SetCurrencyByID = <function> defined @AllTheThings\AllTheThings.lua:3988
 ItemTooltip = <unnamed> {
 }
 SetHyperlink = <function> defined =[C]:-1
 SetGuildBankItem = <function> defined =[C]:-1
 hasMoney = 1
 Hide = <function> defined =[C]:-1
 comparing = false
 TopOverlay = <unnamed> {
 }
 SetHeirloomByItemID = <function> defined =[C]:-1
 SetLFGDungeonReward = <function> defined @AllTheThings\AllTheThings.lua:4025
 SetQuestItem = <function> defined =[C]:-1
 AllTheThingsProcessing = true
 SetToyByItemID = <function> defined =[C]:-1
 numMoneyFrames = 1
 SetRecipeReagentItem = <function> defined @Altoholic\Tooltip.lua:706
 SetInboxItem = <function> defined =[C]:-1
 SetBuybackItem = <function> defined =[C]:-1
 TMW_SetSpellByIDWithClassIcon = <function> defined @TellMeWhen\Components\Core\Spells\ClassSpellCache.lua:212
 SetLootItem = <function> defined =[C]:-1
 SetMerchantItem = <function> defined =[C]:-1
 SetQuestLogItem = <function> defined =[C]:-1
 TMW_SetDogTag = <function> defined @TellMeWhen\Components\Core\Common\DogTags\config.lua:398
 SetTradeTargetItem = <function> defined =[C]:-1
 TMW_SetEquiv = <function> defined @TellMeWhen\Options\TellMeWhen_Options.lua:165
 SetTradePlayerItem = <function> defined =[C]:-1
 SetTrainerService = <function> defined =[C]:-1
 SetSendMailItem = <function> defined =[C]:-1
 SetItemByID = <function> defined =[C]:-1
 updateTooltip = 0.033000
 SetInventoryItem = <function> defined =[C]:-1
 SetExistingSocketGem = <function> defined =[C]:-1
 SetItemKey = <function> defined =[C]:-1
 SetLootRollItem = <function> defined =[C]:-1
 shoppingTooltips = <table> {
 }
 SetLFGDungeonShortageReward = <function> defined @AllTheThings\AllTheThings.lua:4042
 SetBagItem = <function> defined =[C]:-1
 needsReset = true
 SetCurrencyToken = <function> defined @Altoholic\Tooltip.lua:706
 BottomOverlay = <unnamed> {
 }
 TMW_SetFrameHighlight = <function> defined @TellMeWhen\Components\GroupModules\GroupModule_GroupPosition\Config.lua:193
 SetRecipeResultItem = <function> defined @Altoholic\Tooltip.lua:706
}
itemKeys = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
 12 = <table> {
 }
}
auctionPrice = nil
total = 0
itemCount = 0
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
 12 = <table> {
 }
}
(for control) = 1
_ = 1
itemEntry = <table> {
 name = "Moist Fillet"
 count = 200
 link = "|cffffffff|Hitem:168645::::::::120:259::::::|h[Moist Fillet]|h|r"
}
(*temporary) = <function> defined @Auctionator\Source\Database\Main.lua:81
(*temporary) = nil
(*temporary) = "|cffffffff|Hitem:168645::::::::120:259::::::|h[Moist Fillet]|h|r"
(*temporary) = "attempt to call field 'UtilitiesItemKeyFromLink' (a nil value)"
zc = <table> {
 IsEnglishLocale = <function> defined @Auctionator\Source\Localization\Main.lua:67
 msg_red = <function> defined @Auctionator\zcUtils.lua:570
 TrimBrackets = <function> defined @Auctionator\zcUtils.lua:955
 tallyAdd = <function> defined @Auctionator\zcUtils.lua:1108
 msg_yellow = <function> defined @Auctionator\zcUtils.lua:572
 msg = <function> defined @Auctionator\zcUtils.lua:699
 GetArrayElemOrFirst = <function> defined @Auctionator\zcUtils.lua:136
 NumToBool = <function> defined @Auctionator\zcUtils.lua:524
 printmem = <function> defined @Auctionator\zcUtils.lua:1018
 ParseBattlePetLink = <function> defined @Auctionator\zcUtil

**Comment by plusmouse** [comment]
Fixed in 1e2ee37ae38ffe7f9278d8355626df07f93e7b25
