### ISSUE TITLE
Enhancement: Reset search button in auction house

### ISSUE THREAD

**Issue by flow0284** [Auctionator/Auctionator#574]
The old auctionhouse had a resetbutton to reset the select category, filter and searchtextbox. 
Is it possible to add such a button again into the auctionhouseframe near the searchfield?

**Comment by plusmouse** [comment]
There's a button to reset the filter
![image](https://user-images.githubusercontent.com/60280559/76520459-d87b1280-645a-11ea-95b2-b99a6bfc3b09.png)

**Comment by flow0284** [comment]
I know, I mean a button to reset everything.
Close and unselect categories, clear searchfield und remove filter

**Comment by plusmouse** [comment]
I'm not sure why we need a button to do that?

**Comment by flow0284** [comment]
Less clicks. If i would know how to do that, i would do.

**Comment by plusmouse** [comment]
As we avoid changing the default UI where possible this feature isn't likely to be implemented.
