### ISSUE TITLE
Unable to add Item with adv searchterm into shoppinglist

### ISSUE THREAD

**Issue by flow0284** [Auctionator/Auctionator#575]
With version 52 i am unable to add a item to a shoppinglist with a advanced search term.
The term i try to use is ;Rüstung/Kette;;;110;115 

There is no lua error or debug message. After trying to add the search term the Add Item button is disabled. After switching between different shoppinglists the button is enabled again but the new search term isn't there.

**Comment by plusmouse** [comment]
I'm not sure what's happening. I've tried to add the term and it works for me.

**Comment by flow0284** [comment]
Buggrabber and Bugsack are installed. Now with v53 there is no problem.

**Comment by plusmouse** [comment]
No issue, closing
