### ISSUE TITLE
[Suggestion] Undercut X% Redefine Commondities and Items

### ISSUE THREAD

**Issue by Drkangl32** [Auctionator/Auctionator#581]
Thank you for doing such a great job in rewriting this entire mod.  I know this is a massive undertaking.

I noticed undercut X% has a section for undercuts applied to "items" and "commodities" groupings.  However, it might be more useful to have undercut settings applied to groupings of "stackable items" and "non-stackable items".  The reason for this is because we will probably always want to apply undercuts non-stackables (gear and pets) while we may or may not wish to apply undercuts to stackables (all else) since these are always merged under the "last in, first out" rule.  Personally, I feel that the need to undercut any stacked items would be extremely rare.  Stacked items usually just get re-posted at the matched price to make sure "first out" status is maintained.

Note that items such as toys, recipes, consumables, and even mounts are classified as stackable and always merged if matching a selling price without bidding enabled.  The only stack exception I have found is with gear and pets since like items in these categories can come with variations (level, stats, gem slots, breed, etc).  These alone are left unstacked for the buyer to select from all the possible variations.  This is where the undercut function still plays a major role.

Right now, selling on AH is a confusing mess with people not really understanding the stack systems.  Having a mod that could automatically determine stacked and unstacked items and act accordingly would be a very powerful tool that nobody has considered yet.

**Comment by plusmouse** [comment]
I had assumed that all items weren't LIFO (my mistake). Splitting the undercut settings by LIFO on/off makes sense.

**Comment by Drkangl32** [comment]
I should add that uncaged pets DO stack since they are all the same.  Only caged pets with viewable stats and breed are left unstacked for the buyer's benefit.  

That might present a problem since they are all under the same "Battle Pets" AH tab.

**Comment by rodalpho** [comment]
This would be a great enhancement. I only want to undercut non-commodities, typically very expensive items. 

Note that assuming people _won't_ want to undercut commodities is definitely wrong. Many people are simply not capable of understanding that LIFO means that is pointless and ultimately hurts their income, so I expect you to get pushback on not including it. Not from me, though!

**Comment by plusmouse** [comment]
My perspective it's a UI thing to do this, as detecting gear or caged pets is easy.

At the moment we have the settings split by "item" or "commodity" - which isn't the same as LIFO on or LIFO off
