### ISSUE TITLE
Suggestion: Per character/realm duration settings

### ISSUE THREAD

**Issue by Voxxel** [Auctionator/Auctionator#582]
Please include as much of the following information as possible to help me fix the bug:
## Brief Description of Bug

You initialized the set of duration times of auctions but I use different durations on different servers. The stock 8.3 AH remembers the lastly used duration for each items which is now unavailable with Auctionator (at least I can't figure out how to turn off this set duration function).

**Comment by plusmouse** [comment]
There isn't a way to turn it "off" currently. We are looking at optional per-character configuration in the future though.
