### ISSUE TITLE
Suggestion: Shows current auctions for an item after posting

### ISSUE THREAD

**Issue by Voxxel** [Auctionator/Auctionator#583]
Please include as much of the following information as possible to help me fix the bug:
## Brief Description of Bug

The best way to check if the price you set for an auction is correct is to see the AH window for the item right after you press the "Create Auction" button.
In other words: Whenever you make an auction by pressing the "Create Auction" button the stock AH automatically returns to the item's page where you can see your auctioned item compared to others. In this window you can unmistakably realize if you set your price incorrect (eg. forgot to put a zero to the end of price), because it differs from other competitors' prices.

In Auctionator 8.3 alpha this window is missing, it gives a blank page after you create an auction instead of listing the item. I was able to sell a Land Shark pet for 4900 gold instead of 49000.

**Comment by plusmouse** [comment]
We have messages in the chat showing what you set the auction (at least until we can create a UI that is more useful).
