### ISSUE TITLE
Suggestion: Let me sort shopping list results by more than name

### ISSUE THREAD

**Issue by Voxxel** [Auctionator/Auctionator#584]
Please include as much of the following information as possible to help me fix the bug:
## Brief Description of Bug

Another suggestion to make the result window of shopping list searches sort-able.  Now if I try to sort the search result window for name / price / whatever it just changes to sort the stock AH's Favorites.

Once it's done, It would also be good if we could save the sorting method so we don't have to set the sorting over and over.

**Comment by plusmouse** [comment]
I know about this issue. There isn't a good solution to the problem atm.
