### ISSUE TITLE
Nothing appears on the HV window

### ISSUE THREAD

**Issue by Steatch** [Auctionator/Auctionator#585]
Hey, guys,
I just installed the addon and nothing appears on the HV window. No buttons or scan list.
I searched in the options but I can't find anything to change this, did I forget something or is it a bug?
I have uninstalled and reinstalled but the problem is still there.
I can't create lists either.
The addon is installed because it appears in the options and it displays a price on the items.

## Brief Description of Bug
Nothing appears on the HV window. No buttons or scan list.

**Comment by plusmouse** [comment]
You need to install an alpha build, see https://github.com/Auctionator/Auctionator/wiki/The-8.3-Release
