### ISSUE TITLE
Welcome dialog on first load

### ISSUE THREAD

**Issue by plusmouse** [Auctionator/Auctionator#587]
With the Auction House revamp it was necessary to revamp Auctionator as well. It has been overhauled to work in 8.3

This means that things may not be where they were in 8.2 and features (most notably undercut scanning and price histories) missing.

You _do_ have all your old shopping lists and can edit them. All the old search functionality for shopping lists is back, just press "Search"

**Comment by jrob8577** [comment]
Let's finalize the messaging we want in the description, above.
