### ISSUE TITLE
LUA error when right-clicking on a weapon enchant to list

### ISSUE THREAD

**Issue by raysmith59** [Auctionator/Auctionator#588]
Previous 3 enchants I listed were fine, 4th caused the error.  Haven't had issues previously either, first instance of this error.  It *may* have to do with a conflict with the background scan, the error came up 2 seconds before the scan finished processing.

1x ...rd_AuctionHouseUI\Blizzard_AuctionHouseSellFrame.lua:483: attempt to compare nil with number
[string "@Blizzard_AuctionHouseUI\Blizzard_AuctionHouseSellFrame.lua"]:483: in function `CanPostItem'
[string "@Blizzard_AuctionHouseUI\Blizzard_AuctionHouseCommoditiesSellFrame.lua"]:89: in function `CanPostItem'
[string "@Auctionator\Source\Selling\Mixins\Commodity.lua"]:33: in function `UpdateCommoditySellButton'
[string "@Auctionator\Source\Selling\Mixins\Frame.lua"]:71: in function <...eAuctionator\Source\Selling\Mixins\Frame.lua:46>

Locals:
self = <unnamed> {
 0 = <userdata>
 SetItem = <function> defined @Blizzard_AuctionHouseUI\Blizzard_AuctionHouseCommoditiesSellFrame.lua:118
 isInitialized = true
 itemLocation = <table> {
 }
 UpdatePriceSelection = <function> defined @Blizzard_AuctionHouseUI\Blizzard_AuctionHouseCommoditiesSellFrame.lua:48
 RegisterHeader = <function> defined @Blizzard_AuctionHouseUI\Blizzard_AuctionHouseUtil.lua:84
 OnCleaned = <function> defined @SharedXML\LayoutFrame.lua:102
 GetMaxQuantity = <function> defined @Blizzard_AuctionHouseUI\Blizzard_AuctionHouseSellFrame.lua:379
 OnOverlayClick = <function> defined @Blizzard_AuctionHouseUI\Blizzard_AuctionHouseSellFrame.lua:460
 GetSearchResultPrice = <function> defined @Blizzard_AuctionHouseUI\Blizzard_AuctionHouseSellFrame.lua:344
 OnOverlayLeave = <function> defined @Blizzard_AuctionHouseUI\Blizzard_AuctionHouseSellFrame.lua:456
 SetSortOrder = <function> defined @Blizzard_AuctionHouseUI\Blizzard_AuctionHouseUtil.lua:67
 OnShow = <function> defined @Blizzard_AuctionHouseUI\Blizzard_AuctionHouseCommoditiesSellFrame.lua:23
 searchResultPrice = 8423900
 LayoutChildren = <function> defined @SharedXML\LayoutFrame.lua:165
 GetCommoditiesSellList = <function> defined @Blizzard_AuctionHouseUI\Blizzard_AuctionHouseCommoditiesSellFrame.lua:149
 GetAuctionHouseFrame = <function> defined @Blizzard_AuctionHouseUI\Blizzard_AuctionHouseUtil.lua:47
 ClearSearchResultPrice = <function> defined @Blizzard_AuctionHouseUI\Blizzard_AuctionHouseSellFrame.lua:340
 QuantityInput = <unnamed> {
 }
 GetSearchContext = <function> defined @Blizzard_AuctionHouseUI\Blizzard_AuctionHouseUtil.lua:92
 CreateAuctionTabRight = <unnamed> {
 }
 isLayoutFrame = true
 CreateAuctionTabLeft = <unnamed> {
 }
 SetSearchContext = <function> defined @Blizzard_AuctionHouseUI\Blizzard_AuctionHouseUtil.lua:88
 OnDurationUpdated = <function> defined @Blizzard_AuctionHouseUI\Blizzard_AuctionHouseSellFrame.lua:370
 CalculateFrameSize = <function> defined @SharedXML\LayoutFrame.lua:121
 MarkClean = <function> defined @SharedXML\LayoutFrame.lua:93
 GetQuantity = <function> defined @Blizzard_AuctionHouseUI\Blizzard_AuctionHouseSellFrame.lua:445
 GetSortOrderState = <function> defined @Blizzard_AuctionHouseUI\Blizzard_AuctionHouseUtil.lua:58
 spacing = 15
 GetLayoutChildren = <function> defined @SharedXML\LayoutFrame.lua:52
 searchContext = 17
 OnOverlayEnter = <function> defined @Blizzard_AuctionHouseUI\Blizzard_AuctionHouseSellFrame.lua:449
 IsDirty = <function> defined @SharedXML\LayoutFrame.lua:98
 OnLoad = <function> defined @Blizzard_AuctionHouseUI\Blizzard_AuctionHouseSellFrame.lua:276
 UpdateTotalPrice = <function> defined @Blizzard_AuctionHouseUI\Blizzard_AuctionHouseSellFrame.lua:502
 ShowHelpTip = <function> defined @Blizzard_AuctionHouseUI\Blizzard_AuctionHouseSellFrame.lua:506
 fixedWidth = 362.999969
 headers = <table> {
 }
 UpdateFocusTabbing = <function> defined @Blizzard_AuctionHouseUI\Blizzard_AuctionHouseSellFrame.lua:365
 GetPadding = <function> defined @SharedXML\LayoutFrame.lua:112
 UpdatePostButtonState = <function> defined =[C]:-1
 MarkDirty = <function> defined @SharedXML\LayoutFrame.lua:78
 GetDuration = <function> defined @Blizzard_AuctionHouseUI\Blizzard_AuctionHouseSellFrame.lua:441
 OnUpdate = <function> defined @SharedXML\LayoutFrame.lua:72
 OnOverlayReceiveDrag = <function> defined @Blizzard_AuctionHouseUI\Blizzard_AuctionHouseSellFrame.lua:467
 PostButton = <unnamed> {
 }
 CreateAuctionLabel = <unnamed> {
 }
 dirty = false
 fixedHeight = 442.000031
 CreateAuctionTabMiddle = <unnamed> {
 }
 HideHelpTip = <function> define

**Comment by plusmouse** [comment]
I think the issue is related to the server throttling requests, and somehow (see #589) causes the error.
