### ISSUE TITLE
attempt to call global 'GetAuctionItemSubClasses' (a nil value)

### ISSUE THREAD

**Issue by LupeChristoph** [Auctionator/Auctionator#599]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug
During addon loading, I got three LUA errors from Auctionator.

1x Auctionator\AuctionatorFilters.lua:70: attempt to call global 'GetAuctionItemSubClasses' (a nil value)
[string "@Auctionator\AuctionatorFilters.lua"]:70: in function `GenerateSubClasses'
[string "@Auctionator\AuctionatorFilters.lua"]:98: in main chunk

Locals:
classID = 2
parentName = "Waffe"
parentKey = "Waffe"
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = 2
(*temporary) = "attempt to call global 'GetAuctionItemSubClasses' (a nil value)"
---------------------------------------------------------------------------------------------------
1x Auctionator\Auctionator-8.2.0.lua:146: Attempt to register unknown event "AUCTION_ITEM_LIST_UPDATE"
[string "=[C]"]: in function `RegisterEvent'
[string "@Auctionator\Auctionator-8.2.0.lua"]:146: in function `Atr_RegisterEvents'
[string "*:OnLoad"]:1: in function <[string "*:OnLoad"]:1>

Locals:
(*temporary) = Atr_core {
 0 = <userdata>
}
(*temporary) = "AUCTION_ITEM_LIST_UPDATE"
---------------------------------------------------------------------------------------------------
1x Auctionator\AuctionatorHints.lua:505: hooksecurefunc(): SetAuctionItem is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "@Auctionator\AuctionatorHints.lua"]:505: in main chunk

Locals:
---------------------------------------------------------------------------------------------------
## Steps to Reproduce

Just install Auctionator and activate it for some character.

## Loaded Addons
Auctionator
BugGrabber
BugSack
TooManyAddons
Swatter

## Back Trace (LUA Error Output)

See above.

**Comment by plusmouse** [comment]
See https://github.com/Auctionator/Auctionator/wiki/The-8.3-Release
