### ISSUE TITLE
Auctionator bug

### ISSUE THREAD

**Issue by badimus** [Auctionator/Auctionator#60]
Occasionally I get a conflict when using the default UI to queue for bgs

Date: 2016-01-30 21:32:58
ID: 1
Error occured in: AddOn: Auctionator
Count: 1
Message: Error: AddOn Auctionator attempted to call a forbidden function (JoinBattlefield()) from a tainted execution path.
Debug:

   Blizzard_PVPUI\Blizzard_PVPUI.lua:524: HonorFrame_Queue()

```
  [string "*:OnClick"]:1
```

Locals:
None
AddOns:
  Swatter, v5.0.0 (<%codename%>)
  NPCScan, v6.2.3.6
  NPCScanOverlay, v6.2.3.1
  AtlasLoot, vv8.00.60
  Auctionator, v3.2.6
  AutoRepair, v
  Babylonian, v5.1.DEV.332(/embedded)
  Bartender4, v4.6.12
  Capping, v6.2.01
  Configator, v5.1.DEV.376(/embedded)
  Coordinates, v1.19
  CrapAway, v
  Gatherer, v5.0.0
  HandyNotes, vv1.4.6
  HandyNotesDraenorTreasures, v1.16
  HealersHaveToDie, v2.3.7
  PetTracker, v6.2.5
  PetTrackerBreeds, v
  PetTrackerConfig, v
  PetTrackerSwitcher, v
  PetTrackerUpgrades, v
  Postal, v3.5.4
  Recount, vv6.2.3e release
  SlideBar, v5.0.0 (<%codename%>)
  TomTom, vv60200-2.1.0
  BlizRuntimeLib_enUS v6.2.3.60200 <none>
  (ck=28f)

**Comment by ceylina** [comment]
Not an auctionator bug. We don't hook any Bg or queue functions. this is caused by taint form another addon and is caught by auctionator. May want to look at addons specific to battlegrounds like capping.

**Comment by jrob8577** [comment]
ty @AcidWeb reopening in reference to #315

**Comment by jrob8577** [comment]
@Ketho I can't reproduce with current version of Auctionator following the steps in your stream, can you still repro with 5.0.1?

**Comment by AcidWeb** [comment]
Use reproduction steps from foxlit research. Also fix might be already injected by other addon.

**Comment by jrob8577** [comment]
I disabled all but Auctionator. Foxlit research?

I was going to load the patch suggested by [the link above](https://www.townlong-yak.com/bugs/afKy4k-HonorFrameLoadTaint) first, but wanted to verify nothing goes wrong if I do... Not being able to reproduce it, though, I'm not sure how to verify I haven't broken something else. 😄 

@AcidWeb Is this reproducable for you? If so, I can give you a zip with the updated code to test?

**Comment by AcidWeb** [comment]
Many big players like ElvUI already include that snippet so it is 100% safe. I also use it in my addons.

No need for ZIP - I know it is a valid fix.

**Comment by jrob8577** [comment]
👍 My next question, and desire for testing, is if both fixes are needed?

**Comment by AcidWeb** [comment]
Yes. New CommunityUI is affected by other dropdown taint.
