### ISSUE TITLE
Consistent keyboard/mouse shortcuts to post current auction in the "Sell" tab

### ISSUE THREAD

**Issue by plusmouse** [Auctionator/Auctionator#612]
* Commands for use in macros `/atr post`.
* Using the same mouse button for selecting an item to post as to click the post button

**Comment by MirreNL** [comment]
I encountered a problem with my macro bound to the "H" key by using:
/run SetBindingMacro("H", "Auction")
/run SaveBindings(1)

The first two days after creating this it worked like a charm. Servers are more busy now and every time I put something up for auction using my "H" key I can't put up another item for auction after I did that. The "Create Auction" button is greyed out and when I point at the button  with my mouse it says "Throttled. Waiting for the server.

**Comment by plusmouse** [comment]
The message "Throttled. Waiting for the server." should disappear within 30s. If isn't disappearing, that's a bug and I'll need to fix it

**Comment by MirreNL** [comment]
It does not disapear at all but the same dalay is there when auctionator is disabled. Maybe Blizzard changed something since wednesday? Some hotfix or so that messes with this. I can't explain it.

**Comment by plusmouse** [comment]
As this issue occurs whether auctionator is enabled or disabled, it's not something I can fix. Sorry.

**Comment by MirreNL** [comment]
I only mentioned it here because the way I found to do this (sort of) does not work anymore. We have to find another way realizing this issue (use [enter] po make an auction) in the future.

**Comment by plusmouse** [comment]
There's other ways to post rather than faking a click, don't worry about that.

**Comment by MirreNL** [comment]
Oki :)

**Comment by plusmouse** [comment]
This issue is resolved by the new selling tab in the latest alpha. The new post macro is `/auctionator post`
