### ISSUE TITLE
auctionator several error message i am lost

### ISSUE THREAD

**Issue by papafredo** [Auctionator/Auctionator#616]
hi , auctionatr is not working anymore on my computer, i tried to unsitall and reinstall via the twitch client but it is not working. 

i have several error message on auctionator here they are:

**message 1 avertissement LUA:**

Message: Interface\AddOns\Auctionator\AuctionatorFilters.lua:70: attempt to call global 'GetAuctionItemSubClasses' (a nil value)
Time: Thu Mar 26 01:12:25 2020
Count: 1
Stack: Interface\AddOns\Auctionator\AuctionatorFilters.lua:70: attempt to call global 'GetAuctionItemSubClasses' (a nil value)
[string "@Interface\AddOns\Auctionator\AuctionatorFilters.lua"]:70: in function `GenerateSubClasses'
[string "@Interface\AddOns\Auctionator\AuctionatorFilters.lua"]:98: in main chunk

Locals: classID = 2
parentName = "Arme"
parentKey = "Arme"
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = 2
(*temporary) = "attempt to call global 'GetAuctionItemSubClasses' (a nil value)"

**Message 2 LUA:**

Message: Interface\AddOns\Auctionator\Auctionator.lua:146: Attempt to register unknown event "AUCTION_ITEM_LIST_UPDATE"
Time: Thu Mar 26 01:12:25 2020
Count: 1
Stack: Interface\AddOns\Auctionator\Auctionator.lua:146: Attempt to register unknown event "AUCTION_ITEM_LIST_UPDATE"
[string "=[C]"]: in function `RegisterEvent'
[string "@Interface\AddOns\Auctionator\Auctionator.lua"]:146: in function `Atr_RegisterEvents'
[string "*:OnLoad"]:1: in function <[string "*:OnLoad"]:1>

Locals: (*temporary) = Atr_core {
 0 = <userdata>
}
(*temporary) = "AUCTION_ITEM_LIST_UPDATE"

**Message 3 LUA:** 

Message: Interface\AddOns\Auctionator\AuctionatorHints.lua:505: hooksecurefunc(): SetAuctionItem is not a function
Time: Thu Mar 26 01:12:25 2020
Count: 1
Stack: Interface\AddOns\Auctionator\AuctionatorHints.lua:505: hooksecurefunc(): SetAuctionItem is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "@Interface\AddOns\Auctionator\AuctionatorHints.lua"]:505: in main chunk

Locals: 

**Message 4 LUA:**

Message: Interface\AddOns\Auctionator\AuctionatorConfig.lua:998: attempt to index local 'lineEntry' (a nil value)
Time: Thu Mar 26 01:19:26 2020
Count: 1
Stack: Interface\AddOns\Auctionator\AuctionatorConfig.lua:998: attempt to index local 'lineEntry' (a nil value)
[string "@Interface\AddOns\Auctionator\AuctionatorConfig.lua"]:998: in function `Atr_ShpLists_Display'
[string "@Interface\AddOns\Auctionator\AuctionatorConfig.lua"]:972: in function `Atr_ShpList_Options_Update'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

Locals: sllist = <table> {
 1 = <table> {
 }
}
totalRows = 0
line = nil
dataOffset = 1
(for index) = 1
(for limit) = 18
(for step) = 1
line = 1
lineEntry = nil
(*temporary) = "Atr_ShpList1"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'lineEntry' (a nil value)"
kShpLists_NumShpLists = 1
kShpLists_LinesToDisplay = 18
zc = <table> {
 IsEnglishLocale = <function> defined @Interface\AddOns\Auctionator\AuctionatorLocalize.lua:63
 msg_red = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:570
 TrimBrackets = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:955
 tallyAdd = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:1108
 msg_yellow = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:572
 msg = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:699
 GetArrayElemOrFirst = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:136
 NumToBool = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:524
 printmem = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:1018
 ParseBattlePetLink = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:417
 ShowHide = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:33
 StringStartsWith = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:892
 StringEndsWith = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:872
 round = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:564
 CopyDeep = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:984
 ClearTable = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:975
 CheckDeferredCall = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:320
 priceToMoneyString = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:803
 tallyPrint = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:1120
 TrimQuotes = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:935
 GetArrayElemOrNil = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:151
 BoolToNum = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:514
 If = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:107
 periodic = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:343
 Min = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:77
 msg_pink = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:571
 SetTextIf = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:44
 QuoteString = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:923
 msg_str = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:589
 ItemNamefromLink = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:447
 enc64 = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:201
 Val = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:55
 IsBattlePetLink = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:409
 msg_ex = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:708
 printableLink = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:1005
 PrintTable = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:373
 StringContains = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:854
 StringSame = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:836
 PullItemIntoMemory = <function

can you help ?

thank you in advance

**Comment by jrob8577** [comment]
Use the alpha. Go to discord if you have any questions.

**Comment by papafredo** [comment]
Problem solved woth alpha thank you. Envoyé depuis mon smartphone Samsung Galaxy.
-------- Message d'origine --------De : John Roberts <notifications@github.com> Date : 26/03/2020  01:21  (GMT+01:00) À : Auctionator/Auctionator <Auctionator@noreply.github.com> Cc : papafredo <fred.bigarani@gmail.com>, Author <author@noreply.github.com> Objet : Re: [Auctionator/Auctionator] auctionator several error message i am lost (#616) 
Use the alpha. Go to discord if you have any questions.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Auctionator/Auctionator/issues/616#issuecomment-604157685",
"url": "https://github.com/Auctionator/Auctionator/issues/616#issuecomment-604157685",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
