### ISSUE TITLE
Clicking entry of shopping list while searching breaks multisearch

### ISSUE THREAD

**Issue by plusmouse** [Auctionator/Auctionator#625]
Small item, clicking an item in the list while the multisearch runs seems to break the multisearch (I think they're not getting disabled).

Clicking on (any) item gets:
![image](https://user-images.githubusercontent.com/60280559/78592469-0aef1400-783d-11ea-895c-d908b993deab.png)

Correct results:
![image](https://user-images.githubusercontent.com/60280559/78592508-1b9f8a00-783d-11ea-9f13-97ef096900b0.png)

**Comment by jrob8577** [comment]
@plusmouse can you test this one with the updated implementation in #634 ? I couldn't reproduce but I'm not sure I understood from the pictures if I was trying to break it correctly. 😄

**Comment by plusmouse** [comment]
Duplicate of #636
