### ISSUE TITLE
Search for gems and enchants by usable level

### ISSUE THREAD

**Issue by plusmouse** [Auctionator/Auctionator#626]
@rodalpho

Upon investigation (of something else entirely) it appears that it was an undocumented quirk of the old advanced searches that made it work.

**TODO:** Integrate the result of https://www.townlong-yak.com/framexml/live/Blizzard_APIDocumentation#C_AuctionHouse.GetExtraBrowseInfo into the advanced search syntax.

**Comment by rodalpho** [comment]
Fantastic news!

**Comment by plusmouse** [comment]
Working on it
![image](https://user-images.githubusercontent.com/60280559/79016937-13f72280-7b68-11ea-8a82-41a44811456a.png)

At the moment if a non-gem or non-enchant result is returned it can cause the search hang. Looking for a way around it.
