### ISSUE TITLE
wow 8.3.0 error

### ISSUE THREAD

**Issue by Feldar666** [Auctionator/Auctionator#631]
Message: Interface\AddOns\Auctionator\AuctionatorFilters.lua:70: attempt to call global 'GetAuctionItemSubClasses' (a nil value)
Time: Tue Apr  7 11:21:42 2020
Count: 1
Stack: Interface\AddOns\Auctionator\AuctionatorFilters.lua:70: attempt to call global 'GetAuctionItemSubClasses' (a nil value)
[string "@Interface\AddOns\Auctionator\AuctionatorFilters.lua"]:70: in function `GenerateSubClasses'
[string "@Interface\AddOns\Auctionator\AuctionatorFilters.lua"]:98: in main chunk

Locals: classID = 2
parentName = "Weapon"
parentKey = "Weapon"
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = 2
(*temporary) = "attempt to call global 'GetAuctionItemSubClasses' (a nil value)"

**Comment by plusmouse** [comment]
See https://github.com/Auctionator/Auctionator/wiki/The-8.3-Release
