### ISSUE TITLE
auctionator not working at all

### ISSUE THREAD

**Issue by Domo709** [Auctionator/Auctionator#632]
Please include as much of the following information as possible to help me fix the bug:

## addon not working at all. tried uninstalling and reinstalling. worked before but havent played in months and now it is not loading at all. get an error as soon as i login to a character. 

_Please include a brief description of the bug, including what you were doing, and when it occurred._

## just log in to any character with addon enabled. error pops up

_Include the steps I would need to follow to reproduce the bug._

## Loaded Addons
-auctionator
-azeroth auto pilot
-bagbrother
-bagnon
-basicminimap
-can i mog it
-dominos
-gathermate2
-holy power indicator
-mount journal enhanced
-omnicc
-rarescanner
-slidebar
-speedygonzales
-swatter
-tomtom
-wow-pro
-wow-pro leveling

_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output).
**PAGE 1**
1x Auctionator\AuctionatorFilters.lua:70: attempt to call global 'GetAuctionItemSubClasses' (a nil value)
[string "@Auctionator\AuctionatorFilters.lua"]:70: in function `GenerateSubClasses'
[string "@Auctionator\AuctionatorFilters.lua"]:98: in main chunk

Locals:
classID = 2
parentName = "Weapon"
parentKey = "Weapon"
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = 2
(*temporary) = "attempt to call global 'GetAuctionItemSubClasses' (a nil value)"

**PAGE 2**
1x Auctionator\AuctionatorFilters.lua:70: attempt to call global 'GetAuctionItemSubClasses' (a nil value)
[string "@Auctionator\AuctionatorFilters.lua"]:70: in function `GenerateSubClasses'
[string "@Auctionator\AuctionatorFilters.lua"]:98: in main chunk

Locals:
classID = 2
parentName = "Weapon"
parentKey = "Weapon"
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = 2
(*temporary) = "attempt to call global 'GetAuctionItemSubClasses' (a nil value)"

**PAGE 3**
1x Auctionator\AuctionatorHints.lua:505: hooksecurefunc(): SetAuctionItem is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "@Auctionator\AuctionatorHints.lua"]:505: in main chunk

Locals:

**PAGE 4**
6x (null)

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by jrob8577** [comment]
Read the comments on curse, visit the Discord server and (you would have learned by doing either of those things) install the alpha.

**Comment by Domo709** [comment]
> Read the comments on curse, visit the Discord server and (you would have learned by doing either of those things) install the alpha.

thank you sorry should have done that first

**Comment by jrob8577** [comment]
We're getting close to a production release, just not quite there yet.
