### ISSUE TITLE
Buttons overflow from the frame in deDE locale

### ISSUE THREAD

**Issue by plusmouse** [Auctionator/Auctionator#638]
![image](https://user-images.githubusercontent.com/60280559/79010114-2c137580-7b59-11ea-94f7-37a2bfe2f6c2.png)

Resolution: Move the buttons to the right of the shopping list dropdown

**Comment by flow0284** [comment]
I was unable to see this issue because i am using elvui.
I changed my translation for "Erstellen" to "New" and also "Gegenstand hinzufügen" into "Hinzufügen".

Maybe borj will add me as translator to the curseproject. so i can change it.

**Comment by plusmouse** [comment]
Give borj a private message on curse, and he should give you edit permissions

**Comment by jrob8577** [comment]
@flow0284 Just added you

**Comment by plusmouse** [comment]
Resolved with new translations. Closing (thanks @flow0284 )
