### ISSUE TITLE
Saved Variables Redundancy

### ISSUE THREAD

**Issue by sparklicorn** [Auctionator/Auctionator#64]
AUCTIONATOR_PRICE_DATABASE table in saved variables is currently in a "Realm_Faction" format.
The data is not being stored in one centralized table, or even shared, among characters on the same connected realm group.
Since the auction house now operates cross-faction, would you please consider merging connected realms / faction data?

Thanks!
P.S. I also have a suggestion - The pricing data on tooltips could be colored according to how recent the price was recorded. For example, Green for most recent / recorded in past 24 hrs, Yellow for 24-48 hrs, Red 48+ hrs.

**Comment by jrob8577** [comment]
Great point! I'll look into this when I've completed Legion testing, this sounds like a great enhancement!
