### ISSUE TITLE
 [Suggestion] Undercut X% Redefine Commondities and Items #2

### ISSUE THREAD

**Issue by Drkangl32** [Auctionator/Auctionator#644]
Had a close look at the most recent iteration Auctionator.  Interface is now cleaner and easier to navigate.  Really coming along nicely!

However, the recent "Undercut" idea that was intended, while very close, is backwards.  Currently everything that can merge now undercuts while caged pets and gear do not. 

The idea is to post items that merge with cheapest item posted without an undercut.  If it can merge, normally there is no real need to undercut!

However, gear and caged pets do not merge.  They are always listed individually and would normally require a small undercut to make sure buyers will always select the item.  It also assures top slot on the list.

To accommodate all, you might consider adding a "Undercut all Items" or "Undercut Gear and Caged Pets" toggle.  While I have closely examined the inner workings of the new AH to determine that only undercutting gear and caged pets is necessary, there may be others who have a different philosophy.

**Comment by plusmouse** [comment]
We have exactly that. There's a + next to undercut that expands for pet/gear options.

**Comment by Drkangl32** [comment]
Sorry.  Did not see that.  

This is a great feature if people understand its usefulness.  It can really help simplify posting which is what Auctionator has always been about.  Thank you for your wonderful work!
