### ISSUE TITLE
Make the addon's tab buttons more dynamic please

### ISSUE THREAD

**Issue by Voxxel** [Auctionator/Auctionator#645]
Using the latest Alpha, it seems the Shopping tab button falls behind any other custom tabs instead of aligns to the right dynamically. This makes the Shopping List inaccessible. I believe this problem goes for the Auctionator tab button too.

The /run AuctionatorTabs_ShoppingLists:Click() command works but it would be much-much easier and clear to users if we wouldn't have to set up macros in order to use this addon.

I understand if you blame other addons for this bug and you may be right about it, but after all it just seems that Auctionator doesn't work correctly -- and the majority of new users won't dig through github to get an answer why is it not working or if there's any workaround, they rather just delete the seemingly bugged addon and move on.

**Comment by plusmouse** [comment]
Is this due to tsm again?

The argument for our tabs looking out for other add-ons also applies to tsm to avoid rendering on top of other add-ons tabs.

We're aware of the problem, at the moment the only way to fix this is to test for tsm being loaded - if a better way appears we'll likely do it.

**Comment by jrob8577** [comment]
I might also be able to dynamically determine the last tab in the AH. It is annoying that we are getting blamed for TSM code, but we can probably fix it (especially since it seems like the TSM authors aren't very open to customer support or working nicely with other addons...)

**Comment by jrob8577** [comment]
Fixed by #690
