### ISSUE TITLE
bad argument #1 to '?' (Usage: local depositCost

### ISSUE THREAD

**Issue by Phzzt** [Auctionator/Auctionator#647]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug
I get errors when posting some items, mostly pets.

## Steps to Reproduce
Sell an item on the AH, like a pet.

## Back Trace (LUA Error Output)
283x bad argument #1 to '?' (Usage: local depositCost = C_AuctionHouse.CalculateItemDeposit(item, duration, quantity))
[string "=[C]"]: in function `CalculateItemDeposit'
[string "@Blizzard_AuctionHouseUI\Blizzard_AuctionHouseItemSellFrame.lua"]:302: in function `GetDepositAmount'
[string "@Blizzard_AuctionHouseUI\Blizzard_AuctionHouseSellFrame.lua"]:483: in function `CanPostItem'
[string "@Blizzard_AuctionHouseUI\Blizzard_AuctionHouseItemSellFrame.lua"]:327: in function `CanPostItem'
[string "@Auctionator\Source\Selling\Mixins\Item.lua"]:33: in function `UpdateItemSellButton'
[string "@Auctionator\Source\Selling\Mixins\Frame.lua"]:62: in function <...eAuctionator\Source\Selling\Mixins\Frame.lua:46>

Locals:
(*temporary) = "bad argument #1 to '?' (Usage: local depositCost = C_AuctionHouse.CalculateItemDeposit(item, duration, quantity))"

**Comment by plusmouse** [comment]
What version of the alpha are you using (`/auctionator version` will print it)?

We're looking to replace all the posting code with a new tab, so this probably won't get fixed. You can avoid the error by turning the posting code (default duration 12/24/48 and undercutting) off with `/auctionator config feature_selling_1` and a `/reload` (latest discord alpha only)

**Comment by Phzzt** [comment]
Auctionator: Version: 0.0.56 (pre-release)

I have enabled the setting you mentioned. I'm raiding now but I'm sure it will work when I next visit the auction house.

Thank you for helping me :)

**Comment by plusmouse** [comment]
The discord alpha releases are at 79 - we're working on a new Shopping tab for the shopping lists, which is the main change. It's not 100% done, or we'd have released it on twitch.
