### ISSUE TITLE
Buttons in buy tab are too wide in German

### ISSUE THREAD

**Issue by Mythos** [Auctionator/Auctionator#648]
In the new buy tab the buttons are a bit too wide in german language so that they go out of the auction window:

![image](https://user-images.githubusercontent.com/416568/79491993-9deb3380-801f-11ea-89d2-4c1bb97a031f.png)

(also happens when ElvUI skinning is disabled)

**Comment by plusmouse** [comment]
Fixed in alpha 80

**Comment by plusmouse** [comment]
Not fixed. The buttons need to be moved to the RHS of the shopping list dropdown

**Comment by plusmouse** [comment]
Fixed
