### ISSUE TITLE
ich habe den addon runtergeldane aber funtionert nicht

### ISSUE THREAD

**Issue by ShJigar** [Auctionator/Auctionator#656]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

_Please include a brief description of the bug, including what you were doing, and when it occurred._

## Steps to Reproduce

_Include the steps I would need to follow to reproduce the bug._

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by plusmouse** [comment]
https://github.com/Auctionator/Auctionator/wiki/The-8.3-Release

**Comment by ShJigar** [comment]
ich habe Addon erst vor ein stunde runtergeladen, und weitre Addon habe nicht runtergeladen.
ich ich brauche gerne Hilfe

**Comment by jrob8577** [comment]
Sie müssen die Alpha-Version herunterladen.

**Comment by ShJigar** [comment]
ich habe auch Alpha-Version runtergeladen aber funktioniert immer noch nicht

**Comment by flow0284** [comment]
Hi, bitte lade die letzte Alpha Version (https://github.com/Auctionator/Auctionator/releases/tag/83) herunter. 
Speichere die ZIP Datei auf deinem Desktop. 
Entpacke die ZIP Datei. 
Den Ordner "Auctionator" **verschiebst** Du bitte in das Addons Verzeichnis Deiner WoW Installation. Bspw. C:\Games\World of Warcraft\_retail_\Interface\Addons\

Starte World of Warcraft (retail) in der Characterauswahl bitte untern links auf die Schaltfläche Addons klicken. In der Addonsliste zum Eintrag Auctionator scrollen. Davor muss ein Häkchen sein, wenn nicht bitte das Häkchen selbst setzen und die Addon-Liste mit OK schließen.

Nun in einen Charackter einloggen und zum Auktionshaus gehen. Sobald das AH geöffnet ist, erhälst du die eine Meldung von Auctionator mit einigen Informationen zum aktuellen Entwicklungsstand. Diese Meldung kannst Du schließen. 

Jetzt musst du am unteren Rand des Auktionshauses zwei neue Reiter sehen. "Einkaufen" und "Auctionator".
