### ISSUE TITLE
i can't get the addon to work at all

### ISSUE THREAD

**Issue by P1xzM4** [Auctionator/Auctionator#663]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

immediately when i open the game i get Lua Error. and everytime my UI reloads, like going through portals and such.

## Steps to Reproduce

immediately when i open the game i get Lua Error. and everytime my UI reloads, like going through portals and such.

## Loaded Addons
i have tried uninstall them all and installing them all again.
These are the addons i use:
MikScrollingBattleText
Deadly Boss Mod (DBM)
BugSack
Bagnon
Titan [Reputation]
BugGrabber
Auctionator
Skada Damage Meter
Titan Panel [Currencies] Multi
Titan Panel
Selljunk
ChampionCommander
Molinari

## Back Trace (LUA Error Output)
These is what Bug grapper comes up with:

1x Auctionator\AuctionatorFilters.lua:70: attempt to call global 'GetAuctionItemSubClasses' (a nil value)
[string "@Auctionator\AuctionatorFilters.lua"]:70: in function `GenerateSubClasses'
[string "@Auctionator\AuctionatorFilters.lua"]:98: in main chunk

Locals:
classID = 2
parentName = "Weapon"
parentKey = "Weapon"
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = 2
(*temporary) = "attempt to call global 'GetAuctionItemSubClasses' (a nil value)"

And:
1x Auctionator\Auctionator-8.2.0.lua:146: Attempt to register unknown event "AUCTION_ITEM_LIST_UPDATE"
[string "=[C]"]: in function `RegisterEvent'
[string "@Auctionator\Auctionator-8.2.0.lua"]:146: in function `Atr_RegisterEvents'
[string "*:OnLoad"]:1: in function <[string "*:OnLoad"]:1>

Locals:
(*temporary) = Atr_core {
 0 = <userdata>
}
(*temporary) = "AUCTION_ITEM_LIST_UPDATE"

And:
1x Auctionator\AuctionatorHints.lua:505: hooksecurefunc(): SetAuctionItem is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "@Auctionator\AuctionatorHints.lua"]:505: in main chunk

Locals:

And:

6x (null)

**Comment by jrob8577** [comment]
Join Discord or read the comments on curseforge. Install the alpha.
