### ISSUE TITLE
I can’t set the decimal price from 1 gold coin - commas and periods are not put.

### ISSUE THREAD

**Issue by elislavkat** [Auctionator/Auctionator#669]
in shopping list window,  can’t set the decimal price from 1 gold coin - commas and periods are not put.
![image](https://user-images.githubusercontent.com/64079137/79862811-dd8b9400-8400-11ea-821b-4bc3b4cb0eaa.png)

**Comment by plusmouse** [comment]
What price are you trying to put in? I had assumed that people wouldn't need to specify the silvers in the price - most prices are in gold  (with silvers as a minor detail)

**Comment by elislavkat** [comment]
I'm trying as example - 0g 50s  for you it one string of code, and for us, new players - great help21 апр. 2020 г. 7:19 PM пользователь plusmouse <notifications@github.com> написал:
What price are you trying to put in? I had assumed that people wouldn't need to specify the silvers in the price - most prices are in gold  (with silvers as a minor detail)

**Comment by plusmouse** [comment]
Thanks for the feature suggestion, we'll look at it if we have time.
