### ISSUE TITLE
Skillet sends shopping list and results are unexpected.

### ISSUE THREAD

**Issue by b-morgan** [Auctionator/Auctionator#672]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

Skillet sends a shopping list to Auctionator and the results are unexpected. This may be caused because the search is not exact.

## Steps to Reproduce

With Skillet and the Auction House open, click on a recipe in Skillet and then click on the Auctionator button in the Skillet frame. If Skillet debugging is on (/skillet debugshow on), the shopping list sent to Auctionator will be displayed in chat.

![Skillet-Auctionator](https://user-images.githubusercontent.com/1547854/79914366-621aea00-83e2-11ea-8125-5e4ef34c1ac0.png)

## Loaded Addons

Skillet, Auctionator, and god knows what else.

## Back Trace (LUA Error Output)

There is no error, just unexpected results

**Comment by plusmouse** [comment]
```lua
-- Searches for an array of search terms and displays ONLY the
-- results with names that exactly match a search terms
-- Search terms MUST NOT include " or ; in them
-- The auction house MUST be open.
--    callerID: string
--    terms   : string[]
Auctionator.API.v1.MultiSearchExact(callerID, terms)
```

**Comment by b-morgan** [comment]
Skillet-r817-alpha contains the code to use this new API. There is an Auctionator plugin option, SearchExact, that will turn it on.
