### ISSUE TITLE
Russian version. Word length.

### ISSUE THREAD

**Issue by Hubbotu** [Auctionator/Auctionator#673]
Hi. [I am](url=https://www.curseforge.com/members/hubbotu/projects) the localizer of the Russian version. In the Russian version, the words are superimposed on each other. The list of words is presented as links.
https://www.curseforge.com/wow/addons/auctionator/localization/languages/98/phrases#293664
https://www.curseforge.com/wow/addons/auctionator/localization/languages/98/phrases#293667
https://www.curseforge.com/wow/addons/auctionator/localization/languages/98/phrases#293630
https://i.imgur.com/ZEeHrHK.png
In translation, these words are very long.

**Comment by plusmouse** [comment]
Can you provide a screenshot so we can see how much we need to rearrange things to make the translations fit?

**Comment by Hubbotu** [comment]
You just need to set the margin between the translation languages a little more in Russian localization. And the links to the discord and so on should be moved even further to the right.

**Comment by plusmouse** [comment]
![image](https://user-images.githubusercontent.com/60280559/79998431-9b228f80-84b2-11ea-8904-2f1848afc536.png)
