### ISSUE TITLE
Throttling when selling

### ISSUE THREAD

**Issue by Shauren** [Auctionator/Auctionator#675]
## Brief Description of Bug

Having Auctionator enabled causes sell button to be disabled for ~3 seconds after setting item inside  CommoditiesSellFrame or ItemSellFrame

## Steps to Reproduce

1. Enable Auctionator
2. Put item in sell frame
3. Observe button disabled for ~3 seconds (tested on Kazzak-EU)

Without Auctionator `AUCTION_HOUSE_THROTTLED_SYSTEM_READY` is fired after ~250ms instead

## Loaded Addons

None, disabled all but Auctionator version 8.3.0 from curseforge

## Extra

This is caused by taint on execution path that finally ends up calling `C_AuctionHouse.SendSellSearchQuery` in Blizzard_AuctionHouseUI.
Commenting out both `hooksecurefunc(AuctionHouseFrame.ItemSellFrame.ItemDisplay, "SetItemInternal"` calls that set auction duration in `AuctionatorItemSellingMixin:Initialize` and `AuctionatorCommoditySellingMixin:Initialize` results in no throttling at all, just like with Auctionator disabled

This is the most user-visible effect but ALL C_AuctionHouse functions that query remote server on a tainted path are throttled

**Comment by jrob8577** [comment]
Thanks for the report! This is a known issue and will be addressed in our next major release with a custom sell tab, instead of hooking the existing tab. Please track #646 for progress.
