### ISSUE TITLE
Macro /auctionator post for the post button

### ISSUE THREAD

**Issue by plusmouse** [Auctionator/Auctionator#682]
Users like to macro this stuff to get it done quickly. I can implement this, just need the button 😄

**Comment by scotepi** [comment]
For now, this seems to work for me.

`/run a=AuctionHouseFrame;c=a.CommoditiesSellFrame;i=a.ItemSellFrame;if c:CanPostItem() then c.QuantityInput.MaxButton:Click(); c.PostButton:Click() elseif i:CanPostItem() then i.QuantityInput.MaxButton:Click(); i.PostButton:Click() end`

**Comment by plusmouse** [comment]
This issue is resolved by #753
