### ISSUE TITLE
Guild & Communities Opens and gives me.....

### ISSUE THREAD

**Issue by vandiel01** [Auctionator/Auctionator#683]
1x [ADDON_ACTION_FORBIDDEN] AddOn 'Auctionator' tried to call the protected function 'GuildControlSetRank()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `GuildControlSetRank'
[string "@Blizzard_GuildControlUI\Blizzard_GuildControlUI.lua"]:24: in function <...\Blizzard_GuildControlUI\Blizzard_GuildControlUI.lua:7>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML\UIParent.lua"]:457: in function `UIParentLoadAddOn'
[string "@FrameXML\UIParent.lua"]:707: in function `Communities_LoadUI'
[string "@FrameXML\UIParent.lua"]:973: in function `ToggleCommunitiesFrame'
[string "@FrameXML\UIParent.lua"]:828: in function `ToggleGuildFrame'
[string "TOGGLEGUILDTAB"]:1: in function <[string "TOGGLEGUILDTAB"]:1>

**Comment by plusmouse** [comment]
As the issue hasn't reappeared in the interim, viewing this as fixed and closing
