### ISSUE TITLE
Tried to call protected function JoinBattleground()

### ISSUE THREAD

**Issue by DiscordGregory** [Auctionator/Auctionator#685]
## Brief Description of Bug

Went to tank Q for a battleground and could not, bugsack threw an error saying Auctionator attempted to access a protected function.

## Steps to Reproduce

Just queue for battleground

## Back Trace (LUA Error Output)

1x [ADDON_ACTION_FORBIDDEN] AddOn 'Auctionator' tried to call the protected function 'JoinBattlefield()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `JoinBattlefield'
[string "@Blizzard_PVPUI\Blizzard_PVPUI-1.0.lua"]:657: in function `HonorFrame_Queue'
[string "*:OnClick"]:2: in function <[string "*:OnClick"]:1>

**Comment by plusmouse** [comment]
As the issue hasn't reappeared in the interim, viewing this as fixed and closing
