### ISSUE TITLE
Where are the Buy/Sell Tabs?

### ISSUE THREAD

**Issue by OMGizmo** [Auctionator/Auctionator#691]
how can i fix the buy/sell tabs not being here?
https://gyazo.com/93a307d7d5b7e6f4321b4a6a888a8bc1

**Comment by igorrebolj** [comment]
Same here, iam using TSM also (not sure if its connected)

**Comment by OMGizmo** [comment]
> Same here, iam using TSM also (not sure if its connected)

I'm not using tsm, I'm solely using auctionator

**Comment by plusmouse** [comment]
For tsm see #643 

There aren't new buy/sell tabs, there is a shopping tab though

**Comment by igorrebolj** [comment]
Well something broke, this is my ah window, i dont see shopping lists 

https://imgur.com/g4kK8cg

**Comment by plusmouse** [comment]
Use the latest alpha from discord. And _see_ #643
