### ISSUE TITLE
Center text in search spinner

### ISSUE THREAD

**Issue by flow0284** [Auctionator/Auctionator#695]
I changed a bit the german translations to fit the german text into the search spinner.
While searching for some shoppinglistitems the text in the left circle is no centered to the circle.
![WoWScrnShot_042820_102921](https://user-images.githubusercontent.com/27314841/80465992-32b53180-893c-11ea-89ea-fc38d7dbdbd0.jpg)

**Comment by plusmouse** [comment]
I'll release a build with the new translations in later (on my phone at the moment)
