### ISSUE TITLE
Sort by lowest bid, not only buyout

### ISSUE THREAD

**Issue by fagitomania** [Auctionator/Auctionator#698]
Pretty much the title, if you can sort by lowest bid i can't seem to find the option.
Also can i just download the files and use with classic?

**Comment by plusmouse** [comment]
We don't currently support classic, you can always download an old version auctionator (unsupported) https://www.curseforge.com/wow/addons/auctionator/files/2737148

Given the 8.3 AH redesign its unlikely we'll implement this. Closing.
