### ISSUE TITLE
Price tooltip on pets

### ISSUE THREAD

**Issue by AchaiusEstalius** [Auctionator/Auctionator#703]
Turning off all tooltips on auctionator still does not turn off the tooltip price for pets. 

This is annoying cause PetTracker conflicts with the price tooltip, with it's own location tooltip, they are basically on top of eachother and i'd like to disable Auctionator price for pets cause i prefer to show the location and i'm using underminejournal for most pets.

**Comment by plusmouse** [comment]
Ok. I'll look at fixing it so the tooltips turn off. It's a bug that the setting didn't work.

**Comment by plusmouse** [comment]
This will be put on curseforge in the next alpha release. If you want the fix now its on the auctionator #alpha-version-releases discord channel (no phone needed to read messages). A curseforge alpha release with the fix will go out in the few days.
