### ISSUE TITLE
Option to buy from sell tab

### ISSUE THREAD

**Issue by stingray66** [Auctionator/Auctionator#706]
**Is your feature request related to a problem? Please describe.**
Cannot buy from sell tab items that are under priced
**Describe the solution you'd like**
Under the sell tab, to able to right click on auction item to buy it when you see it's under priced.
**Describe alternatives you've considered**
only alternative i have is to go back to buy tab, type in item and click buy then run to mail box and come back.

**Comment by plusmouse** [comment]
This has been fixed in #791 (download the latest alpha to get the feature)
