### ISSUE TITLE
Lua error when opening AH

### ISSUE THREAD

**Issue by spewage** [Auctionator/Auctionator#713]
Message: bad argument #1 to '?' (outside of expected range 0 to 4294967295 - Usage: local name, texture, count, qualityID, usable, level, levelType, minBid, minIncrement, buyoutPrice, bidAmount, highBidder, b
Time: Thu May  7 09:11:36 2020
Count: 1
Stack: bad argument #1 to '?' (outside of expected range 0 to 4294967295 - Usage: local name, texture, count, qualityID, usable, level, levelType, minBid, minIncrement, buyoutPrice, bidAmount, highBidder, b
[string "=[C]"]: in function `GetReplicateItemInfo'
[string "@Interface\AddOns\DataStore_Auctions\DataStore_Auctions.lua"]:248: in function <...ace\AddOns\DataStore_Auctions\DataStore_Auctions.lua:228>
[string "=[C]"]: ?
[string "@Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

**Comment by plusmouse** [comment]
This isn't Auctionator, or Auctionator code. Closing.
