### ISSUE TITLE
Shopping lists fails to display correctly if the UI Scale is set to 1

### ISSUE THREAD

**Issue by jxytb** [Auctionator/Auctionator#714]
When I set the "UI Scale" to 1.0 and reload the shopping list can not show any item or results after searching finished.
If I uncheck the "UI Scale" in "System -> Advanced" shopping list is working well.

**Comment by plusmouse** [comment]
I'm not sure what's happening here, but I use "UI Scale" all the time without an issue. Try only activating auctionator.

**Comment by jxytb** [comment]
It is very strange.when I set "UI Scale" to other settings(except 1.0) the shopping list also works well.I have tested with 3 computers((2k display)) and they all only activating auctionator after deleteing WTF folder.

**Comment by plusmouse** [comment]
Can you install https://www.curseforge.com/wow/addons/bugsack and report any errors it gives?

**Comment by jxytb** [comment]
I have installed bugsack and !BugGrabber.There is no error.
I change uiScale to 0.99 or 0.999 by AdvancedInterfaceOptions and the shopping list still works well.
I change uiScale to 1 by AdvancedInterfaceOptions and there is no item and result in shopping list.
I only create one shopping list and there are 5 items in this list.I print some value from the function RefreshScrollFrame in ScrollList.lua
When the uiscale is 0.99 after I click the name of list:
buttonCount:19
numResults:5
populateCount:5
When the uiscale is 1.0 after I click the name of list:
buttonCount:1
numResults:5
populateCount:1

**Comment by plusmouse** [comment]
Update, can replicate the effect:
![image](https://user-images.githubusercontent.com/60280559/81333485-9954f080-909c-11ea-885c-d74a9663c62c.png)

**Comment by plusmouse** [comment]
Checked, we don't have any code that handles UI scale, it "just works" for every value except for 1.

**Comment by plusmouse** [comment]
Fixed in the latest alpha (278)
