### ISSUE TITLE
[Suggestion] Undercut X% Redefine Commondities and Items 3

### ISSUE THREAD

**Issue by Drkangl32** [Auctionator/Auctionator#719]
Your split undercut feature has been working excellently!  This has made my posting process much faster and simpler.  Thank you so much for the implementation!  I have two minor suggestions:

1.  A more detailed description might better explain the critical differences between pets/gear and all other.  I amended the descriptions a bit in case you think it would be helpful to the user.  I am sure my wording could be improved upon:

**Options to set undercutting percent or values and duration of most items.  Without an undercut, these item categories merge into stacks which follow the LIFO rule.  Undercutting may not be necessary. 

Options to set undercutting percent or values and duration of gear and caged pets.  These item categories are listed individually and do not merge into stacks.  Undercutting is recommended.**

2. I notice that the undercut feature does not  seem to apply to bids (if active).  Would this be added in later?  Not really a big deal either way.

**Comment by plusmouse** [comment]
Options to set undercutting percent or values and duration of most items. Without an undercut, these item categories group up with the last item added being the first to sell. Undercutting may not be necessary.

Options to set undercutting percent or values and duration of gear and caged pets. These item categories are listed individually and a buyer can choose which one they want. Undercutting may be useful.

**Comment by Drkangl32** [comment]
Simplified language for the novice to better understand.  Hopefully, it adds enough clarity to explain the usefulness of this feature.
