### ISSUE TITLE
AuctionHouseFrameCollectionShopTab:SetPoint() Error occurring in the TabContainer.lua file.

### ISSUE THREAD

**Issue by Ookami313** [Auctionator/Auctionator#724]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug
When talking to the AH NPC (Tortollan) received the following error. Using 128 alpha release.

## Steps to Reproduce
Accessed the AH from a Brutosaur mount. Unsure if the issue occurs with the regular AH NPCs.

## Loaded Addons
See below in the error dump.

## Back Trace (LUA Error Output)
Date: 2020-05-12 20:42:52
ID: 15
Error occured in: Global
Count: 1
Message: ...dOns\Auctionator\Source\Tabs\Mixins\TabContainer.lua line 60:
   AuctionHouseFrameCollectionShopTab:SetPoint(): trying to anchor to itself
Debug:
   [string "=(tail call)"]: ?
   [string "=[C]"]: ?
   [string "=[C]"]: SetPoint()
   [string "@Auctionator\Source\Tabs\Mixins\TabContainer.lua"]:60: PositionTabs()
   [string "@Auctionator\Source\Tabs\Mixins\TabContainer.lua"]:15:
      ...dOns\Auctionator\Source\Tabs\Mixins\TabContainer.lua:3
   [string "=[C]"]: ?
   [string "=[C]"]: ?
   [string "=[C]"]: ?
   [string "=[C]"]: CreateFrame()
   [string "@Auctionator\Source\Core\Mixin.lua"]:67:
      Auctionator\Source\Core\Mixin.lua:65
   [string "@Auctionator\Source\Core\Mixin.lua"]:122:
      Auctionator\Source\Core\Mixin.lua:113
   [string "=[C]"]: ?
   [string "=[C]"]: ?
   [string "=[C]"]: ?
   [string "=[C]"]: CreateFrame()
   [string "@Auctionator\Source\Events\OnAuctionHouseShow.lua"]:5: OnAuctionHouseShow()
   [string "@Auctionator\Source\Events\Handler.lua"]:10: Handler()
   [string "*:OnEvent"]:1:
      [string "*:OnEvent"]:1
Locals:
(*temporary) = <function> defined =[C]:-1

AddOns:
  MoncaiCompare, v7.2.0
  Swatter, v8.2.6511 (SwimmingSeadragon)
  WorldFlightMapLoader, v8.1.0.0
  WowheadLooter, v80300
  AchieveIt, v8.3.0.01
  ACP, v3.5.7 
  AllTheThings, v2.0.3
  Altoholic, v8.3-007
  AltoholicSummary, vr192
  AraBrokerGuildFriends, vr81
  AraBrokerReputations, vr35
  AraBrokerReputationsAlts, vr2
  AraBrokerXP, vr7
  Arh, v2.0
  AskMrRobot, v86
  AtlasLoot, vv8.12.00
  AtlasLootBattleforAzeroth, vv8.12.00
  AtlasLootBurningCrusade, vv8.12.00
  AtlasLootCataclysm, vv8.12.00
  AtlasLootClassic, vv8.12.00
  AtlasLootLegion, vv8.12.00
  AtlasLootMistsofPandaria, vv8.12.00
  AtlasLootWarlordsofDraenor, vv8.12.00
  AtlasLootWrathoftheLichKing, vv8.12.00
  Auctionator, v8.3.128 (alpha)
  Auditor3, v6.1.4
  AutoLootToggle, v50200.15
  AzeriteButton, v3.0
  AzeritePowerWeights, v8.3.11
  AzeriteTooltip, v2.0.8
  BarrelsOEasy, v1.1.15
  BattlePetDailyTamer, v3.0.6
  BattleNetFriendAlert, v3.5
  BattlePetCount, v1.8.16
  Bazooka, vv2.9.5
  BFAInvasionTimer, vv8.3.0
  BiggerBagChecker, vv1.4.1-release
  BonusRollFilter, v8.3.0.2-release
  BonusRollPreview, v80100.47-Release
  BookClub, v3.2.0.7
  BrokerAllXP, v1.6.6-release
  BrokerAuditor, v6.1.4
  BrokerBags, vv5.3-release
  BrokerCurrency, v8.1.0.1
  BrokerCurrencyflow, vv1.7.5
  BrokerLocation, vv1.23
  BrokerProfessionsMenu, v8.3.0.0
  BrokeruClock, vv3.3.11
  BtWQuests, v1.64
  BtWQuestsBattleForAzeroth, v48
  BtWQuestsBattleForAzerothPrologue, v14
  BuyEmAll, v3.5.4
  CalendarHUD, v8.02
  CamelSpotter, v1.4.9
  CanIMogIt, v8.3.0v1.25
  ChampionCommander, v1.2.4 80300
  ClassHallsAccountReporter, v1.6
  ClassicQuestLog, v1.4.7
  ClassOrderHallsComplete, v1.35
  CloudyTradeSkill, v3.1
  Collectinator, v8.2.5.2
  CollectionShop, v4.02
  ConRO, v8.3.4
  ConROMonk, v8.3.1
  ConvertRatings, v1.15
  CorruptionTooltips, v1.8.2
  CritterHelper, v1.0
  Cromulent, v80205-2
  CurrencySorter, v8.2.5
  DataStore, vr67
  DataStoreAchievements, vr49
  DataStoreAgenda, vr31
  DataStoreAuctions, vr52
  DataStoreCharacters, vr45
  DataStoreContainers, vr61
  DataStoreCrafts, vr84
  DataStoreCurrencies, vr40
  DataStoreGarrisons, vr26
  DataStoreInventory, vr55
  DataStoreMails, vr54
  DataStorePets, vr46
  DataStoreQuests, vr48
  DataStoreReputations, vr45
  DataStoreSpells, vr34
  DataStoreStats, vr33
  DataStoreTalents, vr63
  DBMArchaeology, v
  DBMCore, v8.3.21
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DejaCharacterStats, v830r304
  Details, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  DoesMyAltKnowThat, vv4-5-g4cde5d5
  DrashQuestCompleteSound, v6.0.3
  DressingRoomFunctions, vv2.0.0
  EasyDestroy, vv201210250036
  EasyMail, v4.3.1
  EasyScrap, v24
  EmoteLDB, v8.3.0-1.1
  ExtVendor, v1.8.7
  FBOutfitDisplayFrame, v1.10.2
  FBTrackingFrame, v1.10.1
  FishingBuddy, v1.10.8.9
  FleecingTip, v830.1848(050320)
  FlyoutButtonCustom, v2.86
  FollowerLocationInfo, v1.5.5-release
  GarrisonCommander, v3.2.4 70200
  GarrisonOrderHallReport, v2.2.1
  GatherMate2, v1.45.5
  GearManagerMoreIcons, v1.17
  Grail, v110
  GrailAchievements, v011
  GrailNPCsretail, v27178
  GrailNPCsretailenUS, v27178
  GrailQuestsretail, v31478
  GrailQuestsretailenUS, v31478
  GrailReputationsretail, v007
  GraphPaper, v1.4.11
  GTFO, v4.55.2
  HandyNotes, vv1.5.10
  HandyNotesArgus, vv0.15
  HandyNotesAzerothsTopTunes, vv1.2.2
  HandyNotesBattleForAzerothTreasures, v1
  HandyNotesBFAHFTracker, v8.0.5
  HandyNotesBrokenShore, vv1.33
  HandyNotesCamelFigurines, v1.3
  HandyNotesDirections, v1
  HandyNotesDraenorTreasures, v1.21
  HandyNotesDungeonLocations, v1.50
  HandyNotesEverShiftingMirror, v1.0.3
  HandyNotesFieldPhotographer, v8.0.0.0
  HandyNotesGuild, v1.10
  HandyNotesHigherDimensionalLearning, v1
  HandyNotesHigherLearning, v8.0.0.0
  HandyNotesKosumoth, v1
  HandyNotesLegionClassOrderHalls, vv1.34
  HandyNotesLegionInstanceWorldQuests, vv1.20
  HandyNotesLegionMagePortals, v1.3
  HandyNotesLegionRaresTreasures, v1.1
  HandyNotesLegionTownPortals, v0.0.1
  HandyNotesLegionTreasures, v1
  HandyNotesLimitedSupplyVendors, vv1.0.1
  HandyNotesLorewalkers, v1
  HandyNotesLostAndFound, v1
  HandyNotesMechagonAndNazjatar, v13
  HandynotesPandaria, v1.4.1
  HandyNotesSuramarLeylines, v1
  HandyNotesSuramarLocations, v0.0.1
  HandyNotesSuramarShalAranTelemancy, vv1.23
  HandyNotesTimelessIsle, v1.2
  HandyNotesToolsOfTheTrade, v5.0.0
  HandyNotesTravelGuide, vv2.1.3
  HandyNotesTreasureHunter, v1
  HandyNotesVisionsOfNZoth, v38
  HandyNotesWarfrontRares, v0.5.0
  HandyNotesWellRead, v8.0.0.0
  HandyNotesWitheredArmyTraining, v1
  HandyNotesWitheredChests, v1.2
  HiddenArtifactTracker, v
  HideCleanUpBagsButton, v2.2
  HideOrderHallBar, vv1.4
  HigherLearning, v1.02
  IcyVeinsStatPriority, v2019-3-13
  Identity2, v4.2.0
  ILDBlizzard, v2.1.6 70200
  Immersion, v1.2.3
  ImmersionExtraFade, v1.5
  InFlight, v8.3.001
  InFlightLoad, v8.3.001
  InspectEquip3, v3.0.14
  InstanceAchievementTracker, v2.77.0
  InterruptAnnouncer, v1.0
  ItemLevelDisplay, v2.1.6 70200
  KethoInstanceTimer, vv3.1.1
  KibQuestMobs, v1.15
  KnowYourLootSpec, v60000.1.0
  LegionInvasionTimer, vv8.3.0
  LFGStatusIcon, v5.4.001
  LightHeaded, vv80200-1.0.0-2020-05-01
  LightHeadedDataE, vwowi:revision
  LightHeadedDataQIDNames, vwowi:revision
  LinkWrangler, v2.02
  LinkWranglerCompanion, v1.82
  LiteMount, v8.3.7
  LOIHCal, v8.3.1
  LoosePebble, v2.02
  LootSpecSwapper, v8.3.0.01
  LostTreasureCheck, v2.1
  MacroToolkit, vv7.3.0.2
  MacroToolkitIcons, v7.2.0.0
  MailNotifier, v8.3.0
  Mapster, v1.8.5
  MBB, v4.0.1
  MikScrollingBattleText, v5.7.150
  MinimalArchaeology, v8.3.0.1
  MissionReportMenu, v
  Molinari, v80300.66-Release
  mOnArsWardrobeHelper, v1.18.6
  MoveAnything, v17.1.0
  MuffinArchaeologyUI, v8.0.0.01
  MuffinFactionizer, v8.1.0.00
  Narcissus, v1.0.9a
  NetherwingEggs, v3.05
  NomiCakes, v8.3.0.1
  NoTaintGlow, v1.02
  numQuests, v7
  OgriLazy, v1.4
  OmniCC, v8.3.5
  OmniCCConfig, v
  OPie, vWalnut 6
  OrderHallCommander, v1.7.6 80300
  Outfitter, v5.22.1
  Overachiever, v1.0.9
  OverachieverCache, v1.0.9
  OverachieverTabs, v1.0.9
  OverachieverTrade, v1.0.9
  ParagonReputation, v1.27
  Paste, v1.4.10
  Pawn, v2.3.25
  PetJournalEnhanced, v2.9.30
  PetTracker, v8.3.6
  PetTrackerConfig, v
  PetTrackerJournal, v
  phisFactionSwitcher, v1.1.2
  Prat30, v3.7.55
  Prat30Libraries, v
  PreciseWorldQuestTimers, v
  PremadeGroupsFilter, v1.36
  PremadeSort, v1.1.5
  QBar, v18.07.29
  Quartz, v3.5.2
  QuestCompletist, v109.27
  RaidAchievement, v
  RaidAchievementOldModules, v
  RaidBrowserInDungeonFinder, v0.3
  RareLove, v1.10
  RareScanner, v8.2
  RareTrackerCore, v1.0.8
  RareTrackerMechagon, v6.0.6
  RareTrackerNazjatar, v6.0.4
  RareTrackerUldum, v6.0.5
  RareTrackerVale, v6.0.4
  Rarity, v1.0 (r697-release-2)
  RarityOptions, v
  Rematch, v4.10.3
  Routes, vv1.6.3
  SetCollector, v3.0.7
  ShadowedUFIndicators, vv2.3.4
  ShadowedUFSmoothBars, vv1.2.2
  ShadowedUnitFrames, vv4.2.9
  SharedMedia, v3.1.0-191
  SharedMediaClassicalFonts, v8.3-release1
  SharedMediaNoAsianFonts, v7.3.5.0
  SharedMediaAdditionalFonts, v8.3.0
  SharedMediaAdditionalSounds, v7.0
  shPerformance, v
  SignOn, vv2.4.2
  SimpleStats, v1.7.5
  SkillUp, v3.6
  SkillUpDing, v1.2
  SkillUpMaxLineColor, v1.1f
  SkillUpUCase, v1.0g
  StealYourCarbon, v
  TabardAddict, v2.47
  tdBattlePetScript, v80100.01
  tdBattlePetScriptRematch, v80100.01
  TinyExtraBarsMacroTextHelpers, v1.00
  TipTop, v3.1.1
  TokenSplainer, vr04
  TomTom, vv80300-1.1.2
  TradeSkillMaster, vv4.9.34
  TradeSkillMasterAppHelper, vv4.0.8
  TrainAll, v1.3
  TransmogTokens, v1.4.9
  TransmogWishList, v8.2.03
  tullaRange, v8.3.2
  tullaRangeConfig, v
  Vendor, v3.5.7
  VendorPawn, v1.1.0
  VendorRulePack, v3.5.7
  Volumizer, v8.0.1.1
  WarCampaignsComplete, v1.05
  WarfrontRareTracker, v1.1.3-1
  WeakAuras, v2.17.5
  WeakAurasCompanion, v1.1.0
  Wholly, v079
  WIM, v3.8.8
  Wisent, v1.0.0 (r7-release)
  WorldBossStatus, vv6.0.6
  WorldFlightMap, v8.3.0.1
  WorldMapTrackingEnhanced, vv4.00
  WorldQuestsList, v92
  WorldQuestTab, v8.3.03.2
  WorldQuestTabUtilities, v8.3.01.2
  WoWDBProfiler, v
  WoWPro, v8.3.0-B0
  WoWProAchievements, v8.3.0-B0
  WoWProDailies, v8.3.0-B0
  WoWProLeveling, v8.3.0-B0
  WoWProProfession, v8.3.0-B0
  WoWProWorldEvents, v8.3.0-B0
  WQAchievements, vv8.3.0-4release
  XLoot, v8.2-1
  XLootFrame, v8.2-1
  XLootGroup, v8.2-1
  XLootMaster, v8.2-1
  XLootMonitor, v8.2-1
  BlizRuntimeLib_enUS v8.3.0.80300 <none>
  (ck=2143)

**Comment by plusmouse** [comment]
This appears to be a result of CollectionShop being enabled and interacting with our tab placement. Can't replicate the error with a normal AH NPC though.

**Comment by Ookami313** [comment]
Interesting. I just received the same error when interacting with an AH NPC in Stormwind (have updated to 130alpha). But you are correct, when I disabled CollectionShop no error occurred. Is this a CollectionShop issue and should I bring it up with it's author, or something that can be fixed on Auctionator's side?

CollectionShop enabled (tabs shifted past edge of the UI frame):
![WoWScrnShot_051320_082543_cropped](https://user-images.githubusercontent.com/26803942/81812298-ef3df400-94f3-11ea-8135-cfbf938ea486.jpg)

CollectionShop disabled:
![WoWScrnShot_051320_082712_cropped](https://user-images.githubusercontent.com/26803942/81812496-34fabc80-94f4-11ea-8929-335f7a8323b9.jpg)

It's interesting how TSM's tab moves from outside to inside between CollectionShop being enabled or disabled.

Thanks.

**Comment by plusmouse** [comment]
It looks like this error only happens when TSM _and_  CollectionShop are enabled (I've tried just collection shop and auctionator and that works fine)
