### ISSUE TITLE
Scrolling behavior in Cancel frame

### ISSUE THREAD

**Issue by tflo** [Auctionator/Auctionator#725]
First of all, congrats for the way the Cancel frame has been implemented. It is exceptionally great that we can cancel an auction with a single, confirmation-free click on an item. (One step closer to being able to get rid of TSM!)

One minor complaint/suggestion: It would be nice if the list wouldn’t auto-scroll to the top after clicking an item.

Thanks for considering, if it is not already in work.

**Comment by Drkangl32** [comment]
I was just about to leave the same comment on this subject!  =)

Scroll position resets to the top of the list after a cancellation.  If we have a really long list this can be inconvenient.
