### ISSUE TITLE
Sort search results by iLevel

### ISSUE THREAD

**Issue by designadrug** [Auctionator/Auctionator#733]
Would like to be able to sort search results by iLevel. Would be particularly useful for enchantments and cut gems.

**Comment by plusmouse** [comment]
You can filter (instead of sorting) by the level of gems and enchants, its the "Crafted Level" option in the search parameters window:
![image](https://user-images.githubusercontent.com/60280559/82302490-92d64b00-99b1-11ea-854d-d9ddd827c8b0.png)

**Comment by jrob8577** [comment]
@plusmouse Do we get the ilvl from our searches? Can't remember what comes back from the API. If we do, we can add a column to the results listing...

**Comment by plusmouse** [comment]
We do get an ilvl back for gear only

**Comment by plusmouse** [comment]
However levels for gems and enchants is something we've added, and isn't normally part of the results

**Comment by designadrug** [comment]
OMG sorry - I forgot I activated the alpha stream a while back to get some feature or other. Seriously; hard to tell.

Just some context - say you've got a page of results for Haste Gems, you can sort on name, you can sort on price... seeing that iLevel column really helped me figure out which gems (and ring enchantments) were appropriate for characters of a certain level. Being able to sort on that column would really allow me to zero-in much faster. And the same would be true of other gear too.

I know I can do it by filtering ranges. But I don't. Sometimes I'm shopping for multiple characters at a time. Mostly it's because I like to look.

**Comment by plusmouse** [comment]
The Blizzard 9.0.1 PTR AH has the desired feature (it lets you sort by usable item level on both gems and enchants):
![image](https://user-images.githubusercontent.com/60280559/90421417-42a27e00-e0b1-11ea-8638-a4f45ea448ff.png)

If that doesn't meet your requirements comment here (and I'll reopen the issue) or in a new feature request.
