### ISSUE TITLE
[Suggestion] Auctionator Undercut Highlight Scan

### ISSUE THREAD

**Issue by Drkangl32** [Auctionator/Auctionator#734]
Auctionator Undercut Highlight Scan

As one of the key features to the old Auctionator, it would be helpful to work in an undercut scan feature on the 8.3 version.

1. From "auctions" page, a "scan for undercuts" button might be added at top of the page (space is available).

2.  When pressed a scan commences.  Scan checks all posted items to be sure they are at the top of the list.  This is done from Blizzards list on the left side of the Auction tab.  This applies to LIFO stacks and solitary items.

3.  If items are not at the top of the list, they are highlighted in a similar way (but different color) to Blizzards highlight.  Highlight remains until we close the page, check the item or press the button for a new scan.

4.  The highlights might be applied to Blizzard's left side Auction list from the Auctions tab.  It would be up to the user to check and retrieve the information from Blizzards interface based on Auctionator highlights.

The idea is to simply apply a subtle, clean looking colored highlight to items Blizzard's auctions page rather than recreating an entirely new "scan" tab.  

I know this feature would be easier said than done.  But, doing this way might be easier to implement while sharing a familiar interface for users to understand.  It would also be less clutter to worry about such as Magic Button posing the details in chat.

Just a thought.  Hope ideas like this might help contribute to your project!

**Comment by plusmouse** [comment]
We already have a new "Cancelling" tab in the latest release. Please update :)
