### ISSUE TITLE
Auctionator causes the addon to exit wow 

### ISSUE THREAD

**Issue by Cryptoconnect2019** [Auctionator/Auctionator#736]
Auctionator causes WOW to Exit , 

happen wen you put some items to sell tab

**Comment by plusmouse** [comment]
Can you check whether this happens when only auctionator is enabled?

**Comment by rushtothesun** [comment]
Auctionator was probably autoscanning at the same time. Doing anything while autoscan is in progress will just DC you.

**Comment by plusmouse** [comment]
You can disable the auto scan in the settings which might help.
