### ISSUE TITLE
Full Scan Doesn't Complete

### ISSUE THREAD

**Issue by Ketrel** [Auctionator/Auctionator#737]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug
Full scan just goes on indefinitely

## Steps to Reproduce
1. Have the auto scan off 
2. Go to AH  
3. Got to auctionator tab and click full scan

## Loaded Addons
Tried with just Auctionator

I downgraded back to Alpha 149 and the full scan works there.  It's something that changed between Alpha 149 and Release 8.3.1.2  

(I have to wait until the time limit is up but then I'll try the release between those and see if it works in that and will report back)

**Comment by Ketrel** [comment]
Update: 8.3.1.1 does not have this issue

**Comment by plusmouse** [comment]
I've just tested 8.3.1.2 and it worked for me.

Can you try Alpha 152?

**Comment by Ketrel** [comment]
Alpha 152 works.  It completes at the same speed as 149 and 8.3.1.1

**Comment by plusmouse** [comment]
Closing, there was a change in 151 that probably resolved the issue.
