### ISSUE TITLE
Shared AH price data on connected realms?

### ISSUE THREAD

**Issue by Yanngo** [Auctionator/Auctionator#738]
The Auctionator shows me in tooltips what an item costs on AH according to the latest scan.
On **connected realms** the auction house is one and the same on two or more realms.
Right now in order to see correct and up-to-date information about prices I have to scan the AH after switching to another connected realm. **Can this data be shared?** It is same per one set of connected realms, for instance, Wildhammer-Thunderhorn EU. I don't want to scan the AH two times every day. 

I am using Auctionator Version: 8.3.1.2

Thank you for the time spent developing and improving the addon.

**Comment by plusmouse** [comment]
We can share the data. The awkward part is keeping an up-to-date list of the connected realms, and detecting it automatically.
