### ISSUE TITLE
Full Scan = DC

### ISSUE THREAD

**Issue by nicholasforneris** [Auctionator/Auctionator#744]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

_Please include a brief description of the bug, including what you were doing, and when it occurred._

## Steps to Reproduce

_Include the steps I would need to follow to reproduce the bug._

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by plusmouse** [comment]
Please use the alternate scan mode - it exists for the case when the normal scan fails.

![image](https://user-images.githubusercontent.com/60280559/84772292-a5549c00-afd2-11ea-80da-6e6b0ec7b450.png)
