### ISSUE TITLE
Items often aren't listed when Create Auction is clicked

### ISSUE THREAD

**Issue by raysmith59** [Auctionator/Auctionator#745]
I don't see any commonality of items that have this issue but once it starts it usually continues until I get out of the auction UI completely and go back in.  It looks like the items will list but they don't.

**Comment by plusmouse** [comment]
(from the discord)
:fearful: Blizzard have modified the AH in this week's realm restart to cause mass posting/searches to fail or take forever. This was an intentional change. See https://us.forums.blizzard.com/en/wow/t/auction-house-much-slower-today/556722/13

**Comment by raysmith59** [comment]
This isn't new, it's been going on for a week or two but I was waiting for this reset to see if it improved things, if anything it's worse now but the issue was happening before today.  Also, in many cases I'm just listing a single item (say, a boxed pet), not anything in bulk.

**Comment by plusmouse** [comment]
Try running `/auctionator config feature_selling_1` to disable our undercut %s and duration setting code, that usually resolves the issue

**Comment by plusmouse** [comment]
As of the latest alphas we no longer modify the "Sell" tab, and encourage users to use the "Selling" tab; so this bug no longer applies to auctionator. If this issue pops up again with the "Selling" tab please report it in a new issue.
