### ISSUE TITLE
To Many Searches on Post

### ISSUE THREAD

**Issue by scotepi** [Auctionator/Auctionator#746]
When posting an item, a search is done when the item is dropped in the AH frame and event is triggered `COMMODITY_SEARCH_RESULTS_UPDATED ####`.

Once the item post posted a search is done again and another event `COMMODITY_SEARCH_RESULTS_UPDATED #### `

Can there be an option to turn off the excessive searching for items? I understand it is for the UI, but if a recent scan was done, why does it need to search for the item before posting it? Why does it need to search again after posting when event `AUCTION_HOUSE_AUCTION_CREATED` is returned? You know what item I had in the frame, you know what I posted it for, don't search again just to tell me what the addon can already know.

**Comment by plusmouse** [comment]
Run `/atr c feature_selling_1` to switch off any auctionator stuff in the sell tab

**Comment by plusmouse** [comment]
Just reviewed the events, the same events are triggered whether Auctionator is active or not. Closing.
