### ISSUE TITLE
Opening Guild & Communities gives an access violation error

### ISSUE THREAD

**Issue by Coreston** [Auctionator/Auctionator#749]
Date: 2020-06-20 12:42:02
ID: 2
Error occured in: AddOn: Auctionator
Count: 1
Message: Error: AddOn Auctionator attempted to call a forbidden function (GuildControlSetRank()) from a tainted execution path.
Debug:
   [string "=[C]"]: GuildControlSetRank()
   [string "@Blizzard_GuildControlUI\Blizzard_GuildControlUI.lua"]:24:
      ...\Blizzard_GuildControlUI\Blizzard_GuildControlUI.lua:7
   [string "=[C]"]: LoadAddOn()
   [string "@..\FrameXML\UIParent.lua"]:457: UIParentLoadAddOn()
   [string "@..\FrameXML\UIParent.lua"]:707:
      ..\FrameXML\UIParent.lua:706
   [string "=[C]"]: Communities_LoadUI()
   [string "@..\FrameXML\UIParent.lua"]:973: ToggleCommunitiesFrame()
   [string "@..\FrameXML\UIParent.lua"]:828: ToggleGuildFrame()
   [string "TOGGLEGUILDTAB"]:1:
      [string "TOGGLEGUILDTAB"]:1
Locals:
None
AddOns:
  Swatter, v5.0.0 (<%codename%>)
  Altoholic, v8.3-006
  AskMrRobot, v86
  Auctionator, v8.3.1.4
  Bartender4, v4.9.0
  CTBuffMod, v8.3.0.9
  CTCore, v8.3.0.9
  CTLibrary, v8.3.0.9
  CTMailMod, v8.3.0.7
  CTMapMod, v8.3.0.8
  DataStore, vr67
  DataStoreAchievements, vr49
  DataStoreAgenda, vr31
  DataStoreAuctions, vr52
  DataStoreCharacters, vr45
  DataStoreContainers, vr61
  DataStoreCrafts, vr84
  DataStoreCurrencies, vr40
  DataStoreGarrisons, vr26
  DataStoreInventory, vr55
  DataStoreQuests, vr48
  DataStoreReputations, vr45
  DataStoreSpells, vr34
  DataStoreStats, vr33
  DataStoreTalents, vr63
  DBMCore, v8.3.26
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  Decursive, v2.7.7
  DejaCharacterStats, v830r305
  GatherMate2, v1.45.5
  HealBot, v8.3.0.20
  HealBotData, v8.3.0.20
  HealBoten, v8.3.0.20
  HealBotOptions, v8.3.0.20
  HealBotTips, v8.3.0.20
  MasterPlanA, vA
  Molinari, v80300.66-Release
  Recount, vv8.3.0d
  Rematch, v4.10.4
  SlideBar, v5.0.0 (<%codename%>)
  SpartanUI, v5.3.2
  SpartanUIArtwork, v5.3.2
  SpartanUIFilmEffects, v5.3.2
  SpartanUIStyleFel, v5.3.2
  SpartanUIStyleMinimal, v5.3.2
  SpartanUIStyleTransparent, v5.3.2
  SpartanUIStyleWar, v5.3.2
  Stubby, v5.21e.5566 (SanctimoniousSwamprat)
  WorldQuestTracker, v
  ZPerl, v5.9.5
  ZPerlArcaneBar, v
  ZPerlParty, v
  ZPerlPartyPet, v
  ZPerlPlayer, v
  ZPerlPlayerBuffs, v
  ZPerlPlayerPet, v
  ZPerlRaidFrames, v
  ZPerlTarget, v
  ZPerlTargetTarget, v
  BlizRuntimeLib_enUS v8.3.0.80300 <none>
  (ck=5f9)

**Comment by plusmouse** [comment]
WoW often blames the wrong add-on for access violations. See #683 and #641 

Had hoped this bug was gone.

**Comment by plusmouse** [comment]
Possibly related https://www.townlong-yak.com/bugs/Kjq4hm-DisplayModeCommunitiesTaint
