### ISSUE TITLE
Make a dropdown field for Default tab instead of multiple single lines

### ISSUE THREAD

**Issue by flow0284** [Auctionator/Auctionator#762]

**Comment by plusmouse** [comment]
The classic version of this is:
![image](https://user-images.githubusercontent.com/60280559/87251952-5da52100-c467-11ea-8680-d046d156d873.png)

The dropdown should be reusable so it can be used to configure keyboard shortcuts:
![image](https://user-images.githubusercontent.com/60280559/87251962-76153b80-c467-11ea-9abb-083544316a26.png)
