### ISSUE TITLE
Disconnected every Time I start Scan

### ISSUE THREAD

**Issue by DreamOfHero** [Auctionator/Auctionator#775]
1 minute after I start the scan (complete or fast is same) on Wow Retail, server disconnect

**Comment by plusmouse** [comment]
Have you used the alternate scan mode?
![image](https://user-images.githubusercontent.com/60280559/87415870-b2f74480-c5c5-11ea-94fa-8dc6ed72ef93.png)

**Comment by DreamOfHero** [comment]
Hi,

These days I dig into the problem.
The problem is not on your addon, but on an add-on called Re:Crystalize.
I uninstalled it and the game work as expected.

*Andrea*

Il giorno mar 14 lug 2020 alle ore 12:32 plusmouse <notifications@github.com>
ha scritto:
