### ISSUE TITLE
Hide empty bagslots in selling tab (as option)

### ISSUE THREAD

**Issue by flow0284** [Auctionator/Auctionator#779]

**Comment by plusmouse** [comment]
I'm not sure what advantage seeing the empty item categories provides?

**Comment by flow0284** [comment]
In my opinion, there is no benefit in showing the empty bag slots.

![grafik](https://user-images.githubusercontent.com/27314841/86948929-2d4f4100-c14e-11ea-9176-c3f6b96dba4f.png)

**Comment by plusmouse** [comment]
Its designed to look like a bag view, and bag views have empty slots. Removing the empty slots is a trivial change however.

**Comment by flow0284** [comment]
Make it as option, please 😍
