### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Hubbotu** [Auctionator/Auctionator#782]
Message: bad argument #1 to '?' (Usage: local depositCost = C_AuctionHouse.CalculateItemDeposit(item, duration, quantity))
Time: Tue Jul  7 07:46:29 2020
Count: 4
Stack: bad argument #1 to '?' (Usage: local depositCost = C_AuctionHouse.CalculateItemDeposit(item, duration, quantity))
[string "=[C]"]: in function `CalculateItemDeposit'
[string "@Interface\AddOns\Blizzard_AuctionHouseUI\Blizzard_AuctionHouseItemSellFrame.lua"]:302: in function `GetDepositAmount'
[string "@Interface\AddOns\Blizzard_AuctionHouseUI\Blizzard_AuctionHouseSellFrame.lua"]:487: in function `CanPostItem'
[string "@Interface\AddOns\Blizzard_AuctionHouseUI\Blizzard_AuctionHouseItemSellFrame.lua"]:327: in function `CanPostItem'
[string "@Interface\AddOns\Blizzard_AuctionHouseUI\Blizzard_AuctionHouseSellFrame.lua"]:476: in function <...rd_AuctionHouseUI\Blizzard_AuctionHouseSellFrame.lua:475>
[string "=[C]"]: in function `UpdatePostButtonState'
[string "@Interface\AddOns\Blizzard_AuctionHouseUI\Blizzard_AuctionHouseSellFrame.lua"]:336: in function `OnEvent'
[string "@Interface\AddOns\Blizzard_AuctionHouseUI\Blizzard_AuctionHouseItemSellFrame.lua"]:85: in function <...uctionHouseUI\Blizzard_AuctionHouseItemSellFrame.lua:84>

Locals: (*temporary) = "bad argument #1 to '?' (Usage: local depositCost = C_AuctionHouse.CalculateItemDeposit(item, duration, quantity))"

**Comment by plusmouse** [comment]
This appears to be part of the Sell tab functionality, which has been removed and replaced in the latest alphas. As such this bug will be "fixed" as soon as the new Selling tab leaves alpha.
