### ISSUE TITLE
Undercut stopped working

### ISSUE THREAD

**Issue by AlexL1118** [Auctionator/Auctionator#783]
Undercut stopped working, starting from Alpha 166.
Reproducing:
- Let's try to sell something that almost always exist in AH, and also easy to get. For example, [Bright Baubles].
- Today on my realm it sells for 19g93s (the real price is not important).
- My undercut setting is 1s.
- Attempt to sell this item leads to the same price as the current price (19g93s). This is incorrect, should be 19g92s - according to my undercut setting (like it was in release v8.3.1.5).
- That's why I have to check each alpha update, and every time return back to v8.3.1.5.

**Comment by plusmouse** [comment]
The selling functionality has been migrated to the new "Selling" tab. The new shortcut to put an item up for sale is to Alt+Left Click it from your bag, or select it inside the selling tab..
