### ISSUE TITLE
Do not clear item & settings from selling tab on Post if more of that item remains in inventory

### ISSUE THREAD

**Issue by dmlary** [Auctionator/Auctionator#784]
**Is your feature request related to a problem? Please describe.**
I frequently split my raw materials into multiple listing when posting auctions.  Previously, and with the new selling tab, after each post, I have to re-select the item, and change the quantity before posting again.

**Describe the solution you'd like**
I would like it if there are more of the posted item present in my bag, that the item remain ready for post, and all the other settings also remain unchanged.

**Describe alternatives you've considered**
Generally anything that would make it easier to sell piles of ore in lots of 100, 50, 20, 10, and 5 with as few clicks as possible would make me happy.

**Additional context**

**Comment by plusmouse** [comment]
1. Why are you selling commodities in stacks (the new LIFO system makes stack sizes irrelevant)?
2. Would providing default stack amounts help? ie Potions are always posted in 50s no matter how many you possess, Ores are posted in 100s, etc.

**Comment by dmlary** [comment]
1. I haven't seen the AH ever split a listing of trade goods (ore or herbs) that I've posted.  I've also not seen any clear answer (reddit,wowhead) of whether the AH will split a listing.  I've seen reference on reddit to splitting stacks to make them easier to sell since the AH changes.  It would make my life easier if they did, so if you have a reference for them doing this, I will be happy.
2. That wouldn't help for my specific scenario, I post in multiple stack sizes for a given item.

**Comment by dmlary** [comment]
Just verified that they do split auction lots!  This is not needed.  Thank you.
