### ISSUE TITLE
SourceID Search

### ISSUE THREAD

**Issue by vandiel01** [Auctionator/Auctionator#785]
![image](https://user-images.githubusercontent.com/52209920/87342267-977e3200-c510-11ea-8c0c-e27dd5a7512a.png)

**Comment by plusmouse** [comment]
This will be a multisearch based on the results of an item ID search.
![image](https://user-images.githubusercontent.com/60280559/87342524-49365680-c543-11ea-9a96-56f73140b670.png)
![image](https://user-images.githubusercontent.com/60280559/87342545-594e3600-c543-11ea-9b8c-7bbeea38ff68.png)

Doing a `C_AuctionHouse.SendSearchQuery` or a `C_AuctionHouse.SendSellSearchQuery` for _each_ result should get us the results we want.
