### ISSUE TITLE
Error ver Auctionator 8.3.1.6-2

### ISSUE THREAD

**Issue by Hubbotu** [Auctionator/Auctionator#786]
Message: bad argument #1 to '?' (Usage: local depositCost = C_AuctionHouse.CalculateItemDeposit(item, duration, quantity))
Time: Tue Jul 14 06:32:07 2020
Count: 1
Stack: bad argument #1 to '?' (Usage: local depositCost = C_AuctionHouse.CalculateItemDeposit(item, duration, quantity))
[string "=[C]"]: in function `CalculateItemDeposit'
[string "@Interface\AddOns\Blizzard_AuctionHouseUI\Blizzard_AuctionHouseItemSellFrame.lua"]:302: in function `GetDepositAmount'
[string "@Interface\AddOns\Blizzard_AuctionHouseUI\Blizzard_AuctionHouseSellFrame.lua"]:487: in function `CanPostItem'
[string "@Interface\AddOns\Blizzard_AuctionHouseUI\Blizzard_AuctionHouseItemSellFrame.lua"]:327: in function `CanPostItem'
[string "@Interface\AddOns\Blizzard_AuctionHouseUI\Blizzard_AuctionHouseSellFrame.lua"]:476: in function <...rd_AuctionHouseUI\Blizzard_AuctionHouseSellFrame.lua:475>
[string "=[C]"]: in function `UpdatePostButtonState'
[string "@Interface\AddOns\Blizzard_AuctionHouseUI\Blizzard_AuctionHouseSellFrame.lua"]:336: in function `OnEvent'
[string "@Interface\AddOns\Blizzard_AuctionHouseUI\Blizzard_AuctionHouseItemSellFrame.lua"]:85: in function <...uctionHouseUI\Blizzard_AuctionHouseItemSellFrame.lua:84>

Locals: (*temporary) = "bad argument #1 to '?' (Usage: local depositCost = C_AuctionHouse.CalculateItemDeposit(item, duration, quantity))"

**Comment by plusmouse** [comment]
This error will be fixed in the [next major release](https://github.com/Auctionator/Auctionator/wiki/8.3.2-Release) of Auctionator, which removes the code that this is related to.
