### ISSUE TITLE
Lua error after using Hearthstone on action bar

### ISSUE THREAD

**Issue by Mushey** [Auctionator/Auctionator#793]
## Brief Description of Bug

I was standing in the middle of Ramkahen in Uldum (current/assault time).
I just finished the assault, opened the cache.
Used my Hearthstone from my action bar to get back to Boralus.
Error popped up. (see stack trace)
The only thing I could think of was I may have attempted to hearth while the loot from my assault cache was on the middle of my screen. I may have mouse-overed one of the loot items which caused Auctionator to look up the value of it?
That's the only thing I could think of. The error only actually came up after clicking on the Hearthstone.
There were no other errors reported in BugSack apart from this one Auctionator one, so I don't think it's caused by another addon but anything is possible.

## Steps to Reproduce

Honestly not sure. I was unable to reproduce it.
Everything I had done is listed in the description.

## Loaded Addons

AdiBags
Angry Keystones
Astral Keys
Auctionator
BugGrabber
BugSack
Can I Mog It?
Details!
Elitism Helper
HandyNotes
Method Dungeon Tools (DB Stub)
MogIt
Mythic Dungeon Tools
O Item Level
Paste
Personal Loot Helper
Postal
Raider.IO
RareScanner
Rarity
SellJunk
Titan Panel
TomCat's Tours
TomTom
WeakAuras 2
World Quest Tracker
Deadly Boss Mods

## Back Trace (LUA Error Output)

![image](https://user-images.githubusercontent.com/68464607/87850569-8bd9a380-c934-11ea-8d61-cb80c3c623f2.png)

**Comment by plusmouse** [comment]
Known bug, and should be fixed with the next major Auctionator release.
