### ISSUE TITLE
Custom default item quantity in the Selling tab

### ISSUE THREAD

**Issue by flow0284** [Auctionator/Auctionator#797]
## Change the default item quantity in the Selling tab to 1 (instead of the maximum)
![grafik](https://user-images.githubusercontent.com/27314841/87886083-7e96e480-ca1a-11ea-9657-6ba168632402.png)

**Comment by plusmouse** [comment]
We could add that as an option. We can't remove the current behaviour as multiple users have requested the automatically selecting everything.

**Comment by flow0284** [comment]
Ah ok
