### ISSUE TITLE
Exclude selected items from the selling bag view

### ISSUE THREAD

**Issue by Galthariel** [Auctionator/Auctionator#799]
## Selling Tab with Bag View is Great but can be even better

Not a problem but I consider very important since it will speed up people that uses the AH very often and in a daily basis.

**Describe the solution you'd like**
An option to ignore items (right click with a ignore option or any other keybind) to be used in the new "Bag View inside the Selling Tab) so we easy see what items we should be posting in the AH.

**Describe alternatives you've considered**
There is no alternative right now but to eye search for the items you want to post in the AH

**Additional context**
Not Applicable

**Comment by plusmouse** [comment]
Comment by "Viking Sven"
Is it possible to get an exclusion list added to it somehow so you can mark items as not to show up in the bag view in the pane? Like my AH char is also an enchanter, so I'd like to be able to not have enchanting mats show up in the bag contents so I don't accidentally list them

**Comment by rodalpho** [comment]
Just came here to request this exact enhancement!

I would also prefer a list view rather than icons, personally.

**Comment by plusmouse** [comment]
![image](https://user-images.githubusercontent.com/60280559/89102199-b0d31980-d3fe-11ea-89fb-9fa073a87700.png)
