### ISSUE TITLE
Background Worker for Fullscan Data

### ISSUE THREAD

**Issue by RShadowhand** [Auctionator/Auctionator#801]
**Is your feature request related to a problem? Please describe.**
Fullscan getting interrupted when closing Auction frame, and you can't fullscan again for 15 minutes, essentially wasting a fullscan.

**Describe the solution you'd like**
Background worker for fullscan data parsing. i.e. fullscan data is cached, and parsed even after auction frame is closed.

**Comment by plusmouse** [comment]
We would like to do that, but the WoW API removes access to the fullscan data the moment the AH closes.

Reading the data can't be done instantly as that causes the WoW client to freeze, so we read it over time (at a rate of 250 entries per frame).

**Comment by RShadowhand** [comment]
Maybe I should try to bring this up to WoW devs then? I haven't done anything of the sort before, do you have any suggestions or pointers? Do I blindly tweet at Ion?

**Comment by plusmouse** [comment]
I don't know. Usually we just take the WoW API as-is and try to work around any issues.

**Comment by plusmouse** [comment]
Closing as there isn't currently a way for us to do this.
