### ISSUE TITLE
No Auctionator Tabs Showing Up on AH

### ISSUE THREAD

**Issue by Taqito** [Auctionator/Auctionator#802]
Just wanted to see if there is a fix because I can't seem to find anything on it.  In WoW Classic the addon seems to load because it shows up in my interface addons but when I go to the AH none of the Auctionator tabs are there. I tried deleting saved variables and reinstalling the addon on together but nothing seems to bring up the tabs... is there a command Im suppose to be using now?

**Comment by plusmouse** [comment]
We don't officially support classic, but there are modified versions of Auctionator that work (mostly).

Downloading an old version of Auctionator (8.2) will work too https://www.curseforge.com/wow/addons/auctionator/files/2737148 - the changes made in 8.3 are the reason that the tabs don't show on the latest retail release of Auctionator when used with classic.
