### ISSUE TITLE
Default Auction Duration

### ISSUE THREAD

**Issue by sauljaffe** [Auctionator/Auctionator#803]
I have the default auction duration set to 48 hours in the Auctionator options.  However, the auction duration when I try to auction something in the auction house defaults to 24 hours.  Auctionator does not appear to be setting the default auction duration.  This is in the version downloaded on 7/26/20 via Twitch.

This seemed to have broken about 2 or 3 updates ago.  I have not added/changed other addons in that time so I don't believe any of them could be the problem.  

No errors appear in Bugsack/grabber directly related to Auctionator as far as i can see although there are warnings of "46x (null)" that appear without any indication of the addon causing it.

**Comment by plusmouse** [comment]
All the duration/undercut features were transitioned to the new "Selling" tab because hijacking the Blizzard "Sell" tab caused throttling issues.
