### ISSUE TITLE
Support posting auctions in the Selling tab

### ISSUE THREAD

**Issue by sauljaffe** [Auctionator/Auctionator#805]
**Is your feature request related to a problem? Please describe.**
There doesn't seem to be a way to actually start an auction through the new Selling tab.  It appears to only assume that everything is posted in Buyout mode.

**Describe the solution you'd like**
I'd like a way to put up items up for auction through the selling tab.  That is to say, actual auctions rather than things in buyout mode.  This is after all "AUCTIONator" and not "SELLinator". :-) :-)

**Describe alternatives you've considered**
I can switch to the normal Auction tab but it doesn't seem to have all the historical data that Auctionator keeps from the scan.  For example, I just put up for auction a Darkmoon Eye.  In the "Selling" tab, auctionator correctly showed that there were previous auctions at high price for the item - I think it was over 100K.  But, when I switched to the "Auction" tab, it showed as a default price only 95gold which is nowhere near accurate.  Undermine Journal was reporting an average of somewhere around 120K gold in my realm.

**Comment by Alinnia** [comment]
Hi, currently the Selling tab only displays "Price" which is the buyout price. It does not show bid prices. Can you please add bid prices information to the Selling Tab. E.g. the prices displayed can be the item's "Current Bid" and "Buyout Price". 

P.S. Let me know if you want me to raise a separate ticket for this..

**Comment by plusmouse** [comment]
This ticket is fine. We're looking into adding posting auctions to the selling tab. When we add the auction functionality the bid price will be added as part of that.

**Comment by plusmouse** [comment]
Is something like this what you envisioned?
![image](https://user-images.githubusercontent.com/60280559/89286463-28e14f80-d64a-11ea-8b4f-28c10b898637.png)

**Comment by sauljaffe** [comment]
I think that would work for me... although, honestly, I don't particularly like the "Selling" tab at all.  I dislike having another tab that duplicates a standard tab with no real additional functionality.  Other than setting the duration, I don't see what functionality the "Selling" tab adds that's not available on the "Sell" tab.

**Comment by Alinnia** [comment]
One extra functionality that the addon provides is ability to automatically undercut by a percentage or set value. I use this for when selling pets.

@plusmouse When selling a pet, I currently have to mouseover each listed pet in order to find out what levels the pets are so that I can price mine accordingly. Is it possible to display the pet level in the Selling tab? Perhaps can just use the existing "Item Level" column to display this information as pets don't have an item level?

**Comment by plusmouse** [comment]
@Alinnia That feature request needs its own issue, but its doable 👍

**Comment by plusmouse** [comment]
@Alinnia Do you need the capability to post items for bidding, or is it only necessary to see other people's bids?

**Comment by Alinnia** [comment]
@plusmouse I personally don't need to post items for bidding, only need to see items' listed bid prices. Reason being that I like to adjust my buyout price if there's an item with a much lower bidding price.

**Comment by sauljaffe** [comment]
@plusmouse  I do need to be able to post items for bidding which is why I raised the issue in the first place.  I do not post everything only with a buyout price.  Sometimes, I put things up for bidding.

**Comment by plusmouse** [comment]
The previous version of Auctionator for 8.2 did not include bidding support (beyond 5% below starting price), and prioritised buyouts?

**Comment by sauljaffe** [comment]
Previous versions of Auctionator did support putting things up for bid.  You were able to specify in the options what undercutting you wanted to do and could put anything there, IIRC.  All you had to do when putting thing in the auction house was to click the box/button that specified "Buyout" so that, like now, if the "Buyout" button is checked the thing went up for the one buyout price and if the button was not checked, it went up for auction.  I cannot remember if you had to set the minimum bid or if Auctionator did that for you.

**Comment by plusmouse** [comment]
Upon review this feature adds too much complexity to the selling tab to make it worth adding, as such, closing this issue.
