### ISSUE TITLE
Sell Tab No Longer Uses Stored Option Data

### ISSUE THREAD

**Issue by JoshAveni** [Auctionator/Auctionator#806]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

The "Sell" tab used to instantly apply my Auctionator settings (5% undercut/48 hour time scale) on items. Now it's as if I don't have the addon at all. It uses the default time of auction (24 hours, instead of 48 hours) and lowest price (instead of undercutting by 5%). My set options seem to only apply to the "Selling" tab and not the "Sell" tab. The selling tab also doesn't have a "Bid" mode, so that's why I'm submitting the bug. I want my options back on the "Sell" tab, please, if at all possible.

## Steps to Reproduce

If you use version 8.3.1.4, you should have no problem seeing the options working on the "Sell" tab. It's only when I updated to the most recent version that my options don't register.

## Loaded Addons

• AppearanceTooltip
• Auctionator
• AzeritePowerWeights
• Can I Mog It?
• Garrison Mission Manager

**Comment by plusmouse** [comment]
Duplicates #805
