### ISSUE TITLE
Clicking an item that isn't found on scan.

### ISSUE THREAD

**Issue by strickland** [Auctionator/Auctionator#807]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

_Please include a brief description of the bug, including what you were doing, and when it occurred._

Not a bug, but I think its major issue.  I dont know if you can attest to this, but when an item isn't found in research, it will automatically put it at the price of the previous item and if you are a fast clicker you might click post in the same price as previous item, it should leave it blank empty in price place if the item wasnt scanned.

## Steps to Reproduce

_Include the steps I would need to follow to reproduce the bug._

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by plusmouse** [comment]
Fixed in the latest alpha 🙂

**Comment by strickland** [comment]
Hello I don't know how to re-open this, you fixed it to make the sell out to be 1copper, however this isnt a fix, I may still click sell by mistake, I suggest making it empty! that way I cannot sell it.

Or put a dash "-"

**Comment by plusmouse** [comment]
I've modified the fix, it should work now (available in alpha 241)
