### ISSUE TITLE
Multiple selection, then click posts

### ISSUE THREAD

**Issue by strickland** [Auctionator/Auctionator#808]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when I try to select so many items on so many characters 👍 
**Describe the solution you'd like** 

An idea is to multiple select with a border around my selection on the left tab, i.e. I can select all items that I want to post, then just click post even if I need to click post multiple times, we can create a macro to spam-press it.

**Describe alternatives you've considered**

**Additional context**

**Comment by plusmouse** [comment]
Have you tried the post macro `/auctionator post` - it posts the currently selected item?

**Comment by strickland** [comment]
No I haven't, it wouldnt allow me to multi-select items, I can only select one item at the time? maybe I'm missing something, wait let me play around until I figure it out.

**Comment by plusmouse** [comment]
It does only do one item at a time, sorry.

**Comment by strickland** [comment]
oh yes, my idea is to multiple select all items that I wish to sell, then use a macro to sell all in one click, thats the feature that I think will be neat.

**Comment by plusmouse** [comment]
The solution to #845 should help. Let me know how it goes.
