### ISSUE TITLE
Gather data from other realms.

### ISSUE THREAD

**Issue by strickland** [Auctionator/Auctionator#809]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex.

 I'm always frustrated when many items on my dead realms come up empty, and cannot get a price for it, then I go to the browser to try and find the price, all I need is an average price to sell the items.

**Describe the solution you'd like**

I think we can pull data from other realms either from other players by using a 3rd party small lightweight application that runs in the systry, or maybe use my alts to save data which then I can use on my realm, at least it will find approx prices for stuff.

Another solution is if i'm on dead realm, I go to a big realm like ravencrest, then scan their AH as level 1 character, then go on my dead realm and I still retain all the prices, that way I never get stuck with no prices on my realm.

**Describe alternatives you've considered**

**Additional context**

**Comment by plusmouse** [comment]
The issue of dead realms will be fixed by Blizzard with realm connections. See the US/EU forum post [here](https://us.forums.blizzard.com/en/wow/t/new-realm-connections-are-underway/572562)/[here](https://eu.forums.blizzard.com/en/wow/t/new-realm-connections-are-underway/162877).
