### ISSUE TITLE
Buyout price issue

### ISSUE THREAD

**Issue by Drizli** [Auctionator/Auctionator#812]
Hi, issue is:
Buyout price entry window in selling tab seems to take data from chat report, in this case it was auction sold price in chat that was pasted to my buyout price.

Screenshot:
https://imgur.com/a/XjmWDaY
Not sure if that's only source (sold auction) of this bug, happened to me at least 4 times in last 3 days.

**Comment by plusmouse** [comment]
What add-on are you using for the sold chat report?

**Comment by plusmouse** [comment]
Made a fix that will be in the latest alpha (239), if you don't respond I'll assume that the fix worked.
