### ISSUE TITLE
Tooltip of bet battle price overlap with other addons

### ISSUE THREAD

**Issue by strickland** [Auctionator/Auctionator#814]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

 I think all the things and other addons like battlepet something, I forgot its name. which show tooltip information

Check screenshot! 

_Please include a brief description of the bug, including what you were doing, and when it occurred._

## Steps to Reproduce

Run any other tooltip addon, like all the things.

_Include the steps I would need to follow to reproduce the bug._

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

no error in buggrabber or bugsack! Its just an appearance of tooltip overlapping.

**Comment by plusmouse** [comment]
Can't really fix this without more information, but I know that ATT at leasts does't overlap - I just tested
![image](https://user-images.githubusercontent.com/60280559/89104508-bab24800-d411-11ea-88d5-78120f87086a.png)
![image](https://user-images.githubusercontent.com/60280559/89104550-01a03d80-d412-11ea-952d-364389a8735b.png)

**Comment by strickland** [comment]
The pet battle addons that I have are.

Battle Pet BreedID
PetTracker
Rematch

Here's what I'll do, ill disable one by one to see which one is interfering with the text in there, hold on.

**Comment by plusmouse** [comment]
It's probably PetTracker. The auctionator battle pet auction price tooltip can be turned off, or PetTracker can be edited to fix the issue (in PetTracker/addons/main/features/tooltips.lua at line 43 add `BattlePetTooltip:AddLine(" ")`)
![image](https://user-images.githubusercontent.com/60280559/89104675-fd285480-d412-11ea-8877-ce90c94900c0.png)

**Comment by strickland** [comment]
I found it, it is in fact PetTracker.

**Comment by strickland** [comment]
do i need to add this line everytime I update pettracker addon? why not the author adds it of pettracker?

**Comment by plusmouse** [comment]
You will need to add it each time. Disabling the Auctionator pet tooltip is the easier option.

I don't have a better solution at the moment unfortunately - the pet tooltip is extra awkward to add stuff to.

**Comment by strickland** [comment]
But I like to check prices of the pets man, so I dont want to disable it, anyway I posted an issue in the pettracker page, lets see if pettracker author decides to fix it from his end.

**Comment by plusmouse** [comment]
Adding this from discord:

Another option is to edit line 35 of PetTracker/addons/main/features/tooltips.lua  changing the `-2` to `-30`
![image](https://user-images.githubusercontent.com/60280559/89200365-d2233980-d5a7-11ea-94af-0e9002449c6d.png)
