### ISSUE TITLE
Add pet level information to the Selling tab

### ISSUE THREAD

**Issue by Alinnia** [Auctionator/Auctionator#818]
**Is your feature request related to a problem? Please describe.**
When selling a pet, I currently need to mouseover each listed pet in order to find out what levels the pets are so that I can price mine accordingly. 

**Describe the solution you'd like**
The Selling tab to display pet level information. Perhaps can just use the existing "Item Level" column to display this information as pets don't have an item level.

**Describe alternatives you've considered**
In the Selling tab mouseover each listed pet to view the pet level, which is what I'm doing now. Other alternative is to use the default Buy tab to search for the pet and view listed pets' pet levels, but that requires switching back and forth between the Buy and Selling tabs.

**Comment by plusmouse** [comment]
Find it in the latest alpha (247)
