### ISSUE TITLE
Selling tab is not always undercutting the cheapest price

### ISSUE THREAD

**Issue by Alinnia** [Auctionator/Auctionator#822]
## Brief Description of Bug
When using the Selling tab to sell items, it undercuts the first price on the list however that price is not always the cheapest.  I suspect this issue occurs only when there are listings with bid prices on the AH. If the listed item on the AH has the cheapest bid price, that item will be at the top of the list in the Selling tab and the addon will undercut the buyout of that particular listing instead of the cheapest buyout price. 

Sometimes I'm able to catch a flicker of movement on my Selling tab where the cheapest buyout price is at the top but then it gets moved/sorted down the list. This flicker happens in like a millisecond so hard for me to confirm the details. 

Issue occurs in the current release 8.3.2.2 and alpha 250. Below are examples of when the issue occurred.

Example 1: The lowest price is 84658g (highlighted) but it's not the price the addon is using for undercutting.
![Land Shark 1](https://user-images.githubusercontent.com/65435667/89703702-6d455600-d990-11ea-8de4-3bccb62921f0.jpg)
![Land Shark 2](https://user-images.githubusercontent.com/65435667/89703663-18094480-d990-11ea-8677-7af31ffb2020.png)

Example 2: The lowest price is 19045g96s (highlighted) but it's not the price the addon is using for undercutting.
![Snobold Runt 1](https://user-images.githubusercontent.com/65435667/89703667-1ccdf880-d990-11ea-9e55-2e1b07cfc8ec.jpg)
![Snobold Runt 2](https://user-images.githubusercontent.com/65435667/89703668-1dff2580-d990-11ea-87da-036674f86ba7.png)

## Steps to Reproduce
Try selecting a number of items in the Selling tab. The issue occurring or not is dependent on if the items listed on the AH having a bid price.
Or create a listing with a higher buyout price, but lower bidding price. That listing will appear at the top of the list in the Selling tab despite not having the lowest buyout price. 

## Loaded Addons
Issue occurs even with only just Auctionator turned on.

Update 1: I just tested listing an armor piece and was able to reproduce the issue. So it's not happening with just pets (just that I sell and buy pets mainly). Have updated my ticket title and description to reflect this.

Update 2: When I use the shortcut to list the item from my bag (instead of clicking on the item's icon in the Selling tab), even though the Selling tab's list is not showing the cheapest buyout price at the top, the addon will undercut the correct price.

**Comment by plusmouse** [comment]
Please try the fix in the latest alpha (251)
