### ISSUE TITLE
Causes Disconnect from game

### ISSUE THREAD

**Issue by rsvirus** [Auctionator/Auctionator#828]
When searching the auction house for an item the first time will cause the game to disconnect to the log in screen. This will dissapear after you login but will happen again when you access the auction on another character or a character not played for a short period.

## Loaded Addons
WeakAuras: enabled
WeakAurasModelPaths: enabled
WeakAurasOptions: enabled
ChocolateBar_Options: enabled
!MoncaiCompare: enabled
NoDuel: enabled
ElvUI: enabled
ElvUI_Config: disabled
ElvUI_SLE: enabled
BagBrother: enabled
Dominos: enabled
Dominos_Cast: enabled
Dominos_Config: enabled
Dominos_Encounter: enabled
Dominos_Progress: enabled
Dominos_Roll: enabled
Kui_Nameplates_Core: enabled
Kui_Nameplates_Core_Config: enabled
Kui_Nameplates: enabled
Kui_Media: enabled
AutoVendor: enabled
AdvancedInterfaceOptions: enabled
AtlasLoot_BattleforAzeroth: enabled
AtlasLoot_BurningCrusade: enabled
AtlasLoot_Cataclysm: enabled
AtlasLoot_Classic: enabled
AtlasLoot_Collections: enabled
AtlasLoot_Crafting: enabled
AtlasLoot_Factions: enabled
AtlasLoot_Legion: enabled
AtlasLoot_MistsofPandaria: enabled
AtlasLoot_Options: enabled
AtlasLoot_PvP: enabled
AtlasLoot_WarlordsofDraenor: enabled
AtlasLoot_WorldEvents: enabled
AtlasLoot_WrathoftheLichKing: enabled
AtlasLoot: enabled
Auctionator: enabled
AutoTurnIn: enabled
AzeritePowerWeights: enabled
Bagnon: enabled
Bagnon_Config: enabled
Broker_Currency: enabled
ChocolateBar: enabled
Coordinates: enabled
Details: enabled
Details_EncounterDetails: enabled
Details_RaidCheck: enabled
Details_DataStorage: enabled
Details_Streamer: enabled
Details_TinyThreat: enabled
Details_Vanguard: enabled
HandyNotes: enabled
HandyNotes_BattleForAzerothTreasures: enabled
LibTTScan-1.0: enabled
MaxDps: enabled
MaxDps_DeathKnight: enabled
MoveAnything: enabled
NugRunning: enabled
NugRunningOptions: enabled
Omen: enabled
Overachiever: enabled
Overachiever_Cache: enabled
Overachiever_Tabs: enabled
Overachiever_Trade: enabled
Postal: enabled
RareScanner: enabled
Spy: enabled
TipTac: enabled
TipTacItemRef: enabled
TipTacOptions: enabled
TipTacTalents: enabled
TomCats: enabled
TomTom: enabled
WeakAurasArchive: enabled
WeakAurasTemplates: enabled
WorldQuestsList: enabled
DBM-Core: enabled
DBM-DefaultSkin: enabled
DBM-GUI: enabled
DBM-SpellTimers: enabled
DBM-StatusBarTimers: enabled
DBM-AntorusBurningThrone: enabled
DBM-Argus: enabled
DBM-Azeroth-BfA: enabled
DBM-Azeroth: enabled
DBM-BaradinHold: enabled
DBM-BastionTwilight: enabled
DBM-ZuldazarRaid: enabled
DBM-BlackTemple: enabled
DBM-BlackrockFoundry: enabled
DBM-BlackwingDescent: enabled
DBM-BWL: enabled
DBM-Brawlers: enabled
DBM-BrokenIsles: enabled
DBM-CastleNathria: enabled
DBM-ChamberOfAspects: enabled
DBM-CrucibleofStorms: enabled
DBM-Coliseum: enabled
DBM-DMF: enabled
DBM-Draenor: enabled
DBM-DragonSoul: enabled
DBM-Party-BfA: enabled
DBM-Party-Shadowlands: enabled
DBM-EmeraldNightmare: enabled
DBM-EyeOfEternity: enabled
DBM-Firelands: enabled
DBM-GarrisonInvasions: enabled
DBM-HeartofFear: enabled
DBM-HellfireCitadel: enabled
DBM-Highmaul: enabled
DBM-Icecrown: enabled
DBM-Karazhan: enabled
DBM-MogushanVaults: enabled
DBM-MC: enabled
DBM-Hyjal: enabled
DBM-Naxx: enabled
DBM-Nyalotha: enabled
DBM-Onyxia: enabled
DBM-Outlands: enabled
DBM-Pandaria: enabled
DBM-PvP: enabled
DBM-AQ20: enabled
DBM-Scenario-MoP: enabled
DBM-Serpentshrine: enabled
DBM-SiegeOfOrgrimmarV2: enabled
DBM-Sunwell: enabled
DBM-AQ40: enabled
DBM-TerraceofEndlessSpring: enabled
DBM-EternalPalace: enabled
DBM-TheEye: enabled
DBM-Nighthold: enabled
DBM-ThroneFourWinds: enabled
DBM-ThroneofThunder: enabled
DBM-TombofSargeras: enabled
DBM-TrialofValor: enabled
DBM-Uldir: enabled
DBM-Ulduar: enabled
DBM-VoA: enabled
DBM-WorldEvents: enabled
WeakAurasCompanion: enabled
ElvUI_VisualAuraTimers: disabled
ElvUI_ExtraActionBars: disabled
ElvUI_CastBarOverlay: disabled
ElvUI_EverySecondCounts: disabled
ElvUI_AuraBarsMovers: disabled
ElvUI_CustomTweaks: disabled
ElvUI_DTBars2: disabled
ElvUI_OptionsUI: enabled

**Comment by plusmouse** [comment]
Can you try turning the autoscan setting off?
![image](https://user-images.githubusercontent.com/60280559/90125076-4a80bc00-dd59-11ea-8bb9-ccb823d07226.png)

**Comment by licountrynerd** [comment]
Was having same issue with similar addons less ELVUI. Turning off the "autoscan" option you suggested 10/10 loads with no disconnect.
