### ISSUE TITLE
Errors when posting via Selling tab

### ISSUE THREAD

**Issue by Alinnia** [Auctionator/Auctionator#830]
## Brief Description of Bug
When I click on the item icon in the Selling tab and hit my "/auctionator post" macro to post my pets for sale, randomly got these 3 error messages at once.

**Error 1:**
Message: bad argument #1 to '?' (Usage: local depositCost = C_AuctionHouse.CalculateItemDeposit(item, duration, quantity))
Time: Sat Aug 15 12:23:12 2020
Count: 173
Stack: bad argument #1 to '?' (Usage: local depositCost = C_AuctionHouse.CalculateItemDeposit(item, duration, quantity))
[string "=[C]"]: ?
[string "=[C]"]: in function `CalculateItemDeposit'
[string "@Interface\AddOns\Auctionator\Source\Tabs\Selling\Mixins\SaleItem.lua"]:99: in function `GetDeposit'
[string "@Interface\AddOns\Auctionator\Source\Tabs\Selling\Mixins\SaleItem.lua"]:80: in function <...\Auctionator\Source\Tabs\Selling\Mixins\SaleItem.lua:63>

Locals: 

**Error 2:**
Message: bad argument #1 to '?' (Usage: local depositCost = C_AuctionHouse.CalculateItemDeposit(item, duration, quantity))
Time: Sat Aug 15 12:23:10 2020
Count: 1
Stack: bad argument #1 to '?' (Usage: local depositCost = C_AuctionHouse.CalculateItemDeposit(item, duration, quantity))
[string "=[C]"]: ?
[string "=[C]"]: in function `CalculateItemDeposit'
[string "@Interface\AddOns\Auctionator\Source\Tabs\Selling\Mixins\SaleItem.lua"]:99: in function `GetDeposit'
[string "@Interface\AddOns\Auctionator\Source\Tabs\Selling\Mixins\SaleItem.lua"]:415: in function `GetPostButtonState'
[string "@Interface\AddOns\Auctionator\Source\Tabs\Selling\Mixins\SaleItem.lua"]:429: in function `UpdatePostButtonState'
[string "@Interface\AddOns\Auctionator\Source\Tabs\Selling\Mixins\SaleItem.lua"]:117: in function `ReceiveEvent'
[string "@Interface\AddOns\Auctionator\Source\Utilities\EventBusMixin.lua"]:86: in function `Fire'
[string "@Interface\AddOns\Auctionator\Source\AH\Mixins\Throttling.lua"]:44: in function <...e\AddOns\Auctionator\Source\AH\Mixins\Throttling.lua:24>

Locals: 

**Error 3:**
Message: ...\Auctionator\Source\Tabs\Selling\Mixins\SaleItem.lua:54: bad argument #1 to 'UnlockItem' (Usage: C_Item.UnlockItem(itemLocation))
Time: Sat Aug 15 12:23:12 2020
Count: 1
Stack: ...\Auctionator\Source\Tabs\Selling\Mixins\SaleItem.lua:54: bad argument #1 to 'UnlockItem' (Usage: C_Item.UnlockItem(itemLocation))
[string "=[C]"]: ?
[string "=[C]"]: in function `UnlockItem'
[string "@Interface\AddOns\Auctionator\Source\Tabs\Selling\Mixins\SaleItem.lua"]:54: in function `UnlockItem'
[string "@Interface\AddOns\Auctionator\Source\Tabs\Selling\Mixins\SaleItem.lua"]:49: in function <...\Auctionator\Source\Tabs\Selling\Mixins\SaleItem.lua:40>
[string "=[C]"]: in function `Hide'
[string "@Interface\FrameXML\UIParent.lua"]:2728: in function `SetUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2755: in function `MoveUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2779: in function `HideUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2457: in function <Interface\FrameXML\UIParent.lua:2449>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface\FrameXML\UIParent.lua"]:3327: in function `HideUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:3483: in function `CloseWindows'
[string "@Interface\FrameXML\UIParent.lua"]:3525: in function <Interface\FrameXML\UIParent.lua:3515>
[string "=[C]"]: in function `securecall'
[string "@Interface\FrameXML\UIParent.lua"]:4153: in function `ToggleGameMenu'
[string "TOGGLEGAMEMENU"]:1: in function <[string "TOGGLEGAMEMENU"]:1>

Locals: 

## Loaded Addons
Accountant 8.0
Auctionator
BadBoy
Battle Pet BreedID
Postal
Rematch
SavedInstances
The Undermine Journal
ElvUI
ElvUI OptionsUI

**Comment by plusmouse** [comment]
Have these errors happened again (I haven't been able to replicate them, so can't fix them)?

**Comment by Alinnia** [comment]
Every now and then when I click on an item icon then press the macro to post, I do occasionally get an error where the Count just keeps increasing on its own like in a loop and I have to /reloadui to get rid of the error message. I'll copy and paste the error here the next time it happens, incase it's not the same error message but related.

**Comment by Alinnia** [comment]
Just got the error. In this error message the Count keeps going up and I have to reload my UI to get rid of it:
![image](https://user-images.githubusercontent.com/65435667/92548660-f656f200-f29a-11ea-8c68-047d92dc8a0e.png)

**Comment by Alinnia** [comment]
Got the errors again. I think it has something to do with how quickly I'm trying to post my items - I might be doing it too quickly. Because I could replicate the issue if I spam click on an item's icon in the Selling tab and spam press the posting macro at the same time.

![image](https://user-images.githubusercontent.com/65435667/92618234-7dd84b80-f303-11ea-97ec-5726f9de8b96.png)
![image](https://user-images.githubusercontent.com/65435667/92618251-816bd280-f303-11ea-80c0-4a130f25e04f.png)

**Comment by plusmouse** [comment]
That should help me fix it. Even if you are pressing the buttons fast it shouldn't give an error. Thanks for narrowing it down.

**Comment by plusmouse** [comment]
I was able to replicate the bug, a fix in the latest alpha (288)
