### ISSUE TITLE
Full scans that include items that only I have up for auction still don't store my sell prices

### ISSUE THREAD

**Issue by raysmith59** [Auctionator/Auctionator#832]
Prior to the 8.3 changes I requested that all full scans include my own auctions when I'm the only one with an item listed, it sounded like that was being addressed but it's still not happening as far as I can tell.  I list a tmog item, it defaults to vendor sell price, I change it to my preferred sell price, it doesn't sell, I re-list it and it again defaults to vendor list price and there's no history in terms of what I tried selling it for previously.  Not having history or reasonable recommendations continues to be an issue.

**Comment by plusmouse** [comment]
Are you using the new "Selling" tab?

**Comment by raysmith59** [comment]
Nay, didn't realize the functionality was tied to the tab.  Does seem to work from Selling, thanks.
