### ISSUE TITLE
Configurable default item for shopping list tab

### ISSUE THREAD

**Issue by comiluv** [Auctionator/Auctionator#835]
**Is your feature request related to a problem? Please describe.**
I most of the time go to the auction house to shop for herbs and ores that I set up as a shopping list item in Auctionator addon, but I have to go through a drop-down menu every time and I feel like it's wasted clicks I made when the menu can be set as default.

**Describe the solution you'd like**
I'd like the shopping list tab can have an item set to be default so Auctionator would open and search for items in the default shopping list whenever Shopping List tab is opened or Auction House is opened and Shopping List is the default tab

**Comment by plusmouse** [comment]
Available in alpha 291
