### ISSUE TITLE
Error happens each time I scan for auctions, apart from that awesome addon! 

### ISSUE THREAD

**Issue by KirbyV2** [Auctionator/Auctionator#839]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug
Opened ah to scan and got this error. Has been happening ever since the recode of the addon.

Locals: <none>
_Please include a brief description of the bug, including what you were doing, and when it occurred._

## Steps to Reproduce
Opened ah to scan and got this error
_Include the steps I would need to follow to reproduce the bug._

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)
Message: bad argument #1 to '?' (outside of expected range 0 to 4294967295 - Usage: local name, texture, count, qualityID, usable, level, levelType, minBid, minIncrement, buyoutPrice, bidAmount, highBidder, b
Time: Fri Aug 28 06:14:51 2020
Count: 1
Stack: bad argument #1 to '?' (outside of expected range 0 to 4294967295 - Usage: local name, texture, count, qualityID, usable, level, levelType, minBid, minIncrement, buyoutPrice, bidAmount, highBidder, b
[string "=[C]"]: in function `GetReplicateItemInfo'
[string "@Interface\AddOns\DataStore_Auctions\DataStore_Auctions.lua"]:209: in function <...ace\AddOns\DataStore_Auctions\DataStore_Auctions.lua:189>
[string "=[C]"]: ?
[string "@Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119>
_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by plusmouse** [comment]
I think this is a bug in Altaholic; the code that gives the error isn't in Auctionator.

**Comment by plusmouse** [comment]
Do you still get the errors, and have you tried making sure all your addons are up to date?

**Comment by KirbyV2** [comment]
I make a habit of keeping all my addons up to date and I use very few addons. I uninstalled altoholic and the error when I open the ah has stopped so thankyou for that fix, however I am still getting this error when i click create auction in the sell frame. 

```
Message: ...rd_AuctionHouseUI\Blizzard_AuctionHouseSellFrame.lua:487: attempt to compare nil with number
Time: Fri Sep 11 16:56:45 2020
Count: 1
Stack: ...rd_AuctionHouseUI\Blizzard_AuctionHouseSellFrame.lua:487: attempt to compare nil with number
[string "@Interface\AddOns\Blizzard_AuctionHouseUI\Blizzard_AuctionHouseSellFrame.lua"]:487: in function `CanPostItem'
[string "@Interface\AddOns\Blizzard_AuctionHouseUI\Blizzard_AuctionHouseCommoditiesSellFrame.lua"]:89: in function `CanPostItem'
[string "@Interface\AddOns\Blizzard_AuctionHouseUI\Blizzard_AuctionHouseCommoditiesSellFrame.lua"]:103: in function `PostItem'
[string "@Interface\AddOns\Blizzard_AuctionHouseUI\Blizzard_AuctionHouseSellFrame.lua"]:220: in function <...rd_AuctionHouseUI\Blizzard_AuctionHouseSellFrame.lua:219>

Locals: self = <unnamed> {
 0 = <userdata>
 SetItem = <function> defined @Interface\AddOns\Blizzard_AuctionHouseUI\Blizzard_AuctionHouseCommoditiesSellFrame.lua:118
 isInitialized = true
 itemLocation = <table> {
 }
 UpdatePriceSelection = <function> defined @Interface\AddOns\Blizzard_AuctionHouseUI\Blizzard_AuctionHouseCommoditiesSellFrame.lua:48
 RegisterHeader = <function> defined @Interface\AddOns\Blizzard_AuctionHouseUI\Blizzard_AuctionHouseUtil.lua:84
 OnCleaned = <function> defined @Interface\SharedXML\LayoutFrame.lua:102
 GetMaxQuantity = <function> defined @Interface\AddOns\Blizzard_AuctionHouseUI\Blizzard_AuctionHouseSellFrame.lua:383
 OnOverlayClick = <function> defined @Interface\AddOns\Blizzard_AuctionHouseUI\Blizzard_AuctionHouseSellFrame.lua:464
 GetSearchResultPrice = <function> defined @Interface\AddOns\Blizzard_AuctionHouseUI\Blizzard_AuctionHouseSellFrame.lua:348
 OnOverlayLeave = <function> defined @Interface\AddOns\Blizzard_AuctionHouseUI\Blizzard_AuctionHouseSellFrame.lua:460
 SetSortOrder = <function> defined @Interface\AddOns\Blizzard_AuctionHouseUI\Blizzard_AuctionHouseUtil.lua:67
 OnShow = <function> defined @Interface\AddOns\Blizzard_AuctionHouseUI\Blizzard_AuctionHouseCommoditiesSellFrame.lua:23
 LayoutChildren = <function> defined @Interface\SharedXML\LayoutFrame.lua:165
 GetCommoditiesSellList = <function> defined @Interface\AddOns\Blizzard_AuctionHouseUI\Blizzard_AuctionHouseCommoditiesSellFrame.lua:149
 GetAuctionHouseFrame = <function> defined @Interface\AddOns\Blizzard_AuctionHouseUI\Blizzard_AuctionHouseUtil.lua:47
 ClearSearchResultPrice = <function> defined @Interface\AddOns\Blizzard_AuctionHouseUI\Blizzard_AuctionHouseSellFrame.lua:344
 QuantityInput = <unnamed> {
 }
 GetSearchContext = <function> defined @Interface\AddOns\Blizzard_AuctionHouseUI\Blizzard_AuctionHouseUtil.lua:92
 CreateAuctionTabRight = <unnamed> {
 }
 isLayoutFrame = true
 CreateAuctionTabLeft = <unnamed> {
 }
 SetSearchContext = <function> defined @Interface\AddOns\Blizzard_AuctionHouseUI\Blizzard_AuctionHouseUtil.lua:88
 OnDurationUpdated = <function> defined @Interface\AddOns\Blizzard_AuctionHouseUI\Blizzard_AuctionHouseSellFrame.lua:374
 CalculateFrameSize = <function> defined @Interface\SharedXML\LayoutFrame.lua:121
 MarkClean = <function> defined @Interface\SharedXML\LayoutFrame.lua:93
 GetQuantity = <function> defined @Interface\AddOns\Blizzard_AuctionHouseUI\Blizzard_AuctionHouseSellFrame.lua:449
 GetSortOrderState = <function> defined @Interface\AddOns\Blizzard_AuctionHouseUI\Blizzard_AuctionHouseUtil.lua:58
 spacing = 15
 GetLayoutChildren = <function> defined @Interface\SharedXML\LayoutFrame.lua:52
 searchContext = 17
 OnOverlayEnter = <function> defined @Interface\AddOns\Blizzard_AuctionHouseUI\Blizzard_AuctionHouseSellFrame.lua:453
 IsDirty = <function> defined @Interface\SharedXML\LayoutFrame.lua:98
 OnLoad = <function> defined @Interface\AddOns\Blizzard_AuctionHouseUI\Blizzard_AuctionHouseSellFrame.lua:278
 UpdateTotalPrice = <function> defined @Interface\AddOns\Blizzard_AuctionHouseUI\Blizzard_AuctionHouseSellFrame.lua:510
 ShowHelpTip = <function> defined @Interface\AddOns\Blizzard_AuctionHouseUI\Blizzard_AuctionHouseSellFrame.lua
```

**Comment by plusmouse** [comment]
We don't modify the "Sell" tab any more - so that error isn't from Auctionator. Have you tried using the "Selling" tab - which we do support?

**Comment by KirbyV2** [comment]
Ok i think the issue is resolved now. Thankyou for the help.
