### ISSUE TITLE
Toggle quantity with a macro

### ISSUE THREAD

**Issue by ThatWOWGuy** [Auctionator/Auctionator#841]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to sell Max or 1 using a macro like /auctionator post 1 or /auctionator post Max

**Describe alternatives you've considered**
I've posted all of my single items, then switched quantity to Max to post my stacks

**Additional context**
Would be an amazing feature

**Comment by plusmouse** [comment]
What type of items do you post as max and what type of items do you sell as 1?

**Comment by plusmouse** [comment]
Not exactly the fix you were after, but the setting can be flipped by running

`/auctionator config lifo_default_quantity 0` (set to max)
`/auctionator config lifo_default_quantity 1` (set to 1)

The next item selected will use the new setting.

**Comment by plusmouse** [comment]
The alpha has been updated to offer separate quantity settings for most items and gear/pets. Does that cover your use case?

This issue will be closed as "fixed" if there aren't any further responses.

**Comment by ThatWOWGuy** [comment]
Sorry for the delay. Yeah that should help with posting. If not I'll use
the toggles you gave me.

**Comment by plusmouse** [comment]
That's great.
