### ISSUE TITLE
Wanting the "post" button to proceed to the next item in inventory

### ISSUE THREAD

**Issue by penguinsane** [Auctionator/Auctionator#845]
**Is your feature request related to a problem? Please describe.**

I get frustrated having to click each item in the selling tab, then click to post.

**Describe the solution you'd like**

I would like for the selling tab to proceed to the next item on the list, if possible, when I hit post. That way I can just click post over and over, would make things faster.

**Describe alternatives you've considered**

I have not considered other alternatives. There is an addon called AuctionFaster which has this functionality, but it is nowhere near as polished as Auctionator, and it breaks often. I am okay with it being an option that I would need to toggle.

**Additional context**

None. I apologize if this is already an option somewhere and I've missed it.

**Comment by penguinsane** [comment]
This does speed up the process significantly, thank you! I would still love to see the functionality I suggested, but barring that, this is a decent enough alternative. Thanks again!

**Comment by plusmouse** [comment]
This is fixed in alpha 321
