### ISSUE TITLE
Export search results as plain text or excel file

### ISSUE THREAD

**Issue by Kelrok** [Auctionator/Auctionator#852]
**Is your feature request related to a problem? Please describe.**
A: My problem is I'm having to do a lot of work between several different programs to find the best item to sell during a market trend. It's also hard to manually type in values on my excel sheet for items I'm trying to price out since most of my money is made from flipping mats.

**Describe the solution you'd like**
A: I would like to be able to Export and Save the search results from Auctionator as either a plain text or an excel file so I can post it into my excel sheets. The files would list the name of the item in the AH, how much buyout, how much auctioned, how many available at the time, and a timestamp of when the search was made.

**Describe alternatives you've considered**
A: An alternative to the excel export would be a plain text export.

**Additional context**

**Comment by plusmouse** [comment]
There's been progress, this version of Auctionator will do a plain text export, with an "Export CSV" button on the shopping tab.

Can you let me know if this does what you want it to?

[Auctionator-CSV-Export.zip](https://github.com/Auctionator/Auctionator/files/5627657/Auctionator-CSV-Export.zip)
![image](https://user-images.githubusercontent.com/60280559/100843277-06cdd180-3472-11eb-97d4-e7fe7fa1e2bd.png)

**Comment by Magistermomo** [comment]
Hello,

it's a great idea to use csv.
But I've got a problem with the prices.
There are no ',' in the prices so it is not possible to make a between 1300 or 13.00 gold for instance.
I don't know if it's related to interface language (french for me) or something else but the list is not really usable without manual intervention. 

thank you very much

**Comment by plusmouse** [comment]
The prices are in coppers. You can use formulas in a spreadsheet to automatically convert the prices into the format you want
[In Sheet 1 of this spreadsheet](https://github.com/Auctionator/Auctionator/files/7452368/csv.formulas.xlsx) there is an example of converting the prices into gold (you paste the CSV into the first few columns and the later columns update automatically
.

**Comment by Magistermomo** [comment]
shame on me ... thank you very much !
