### ISSUE TITLE
Auctionator Ignoriong Default Duration

### ISSUE THREAD

**Issue by woofpup** [Auctionator/Auctionator#855]
Please include as much of the following information as possible to help me fix the bug:
I set the duration to 24 under the options. I exit auction to make sure settings apply (it doesn't matter if I do or don't though), open selling, click item, note it still says 48, change to 24. Next item, sometimes is 24 but most often is 48.

## Brief Description of Bug

_Please include a brief description of the bug, including what you were doing, and when it occurred._

## Steps to Reproduce

_Include the steps I would need to follow to reproduce the bug._

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by plusmouse** [comment]
Are you using the new "Selling" tab?

**Comment by plusmouse** [comment]
Oh, I think I know what's happening here. There are _two_ duration settings, one for most items, and the other for gear/pets. The gear/pets one defaults to 48 hours, you'll need to change that to 24 too:
![image](https://user-images.githubusercontent.com/60280559/93379479-cc32a080-f855-11ea-97ae-d1af5d21ffe8.png)

**Comment by woofpup** [comment]
Yes, the Auctionator selling tab.

**Comment by woofpup** [comment]
Sorry, didn't see your 2nd email. That would likely be the issue because
it's mog gear I'm selling. Thanks so much!

**Comment by plusmouse** [comment]
No problem.

**Comment by Neurotoxin001** [comment]
It's still not fixed in 8.3.4

**Comment by plusmouse** [comment]
There are TWO duration settings, one for most items and another one for gear/pets. Make sure you have set both of them. The default for gear/pets is 48.

**Comment by Neurotoxin001** [comment]
Yes, I set both of them. I updated my comment.

**Comment by plusmouse** [comment]
It's possible your saved variables file for auctionator is corrupted. It is in [WoW Directory]\_retail_\WTF\Account\[Some numbers]\SavedVariables and it's the Auctionator.lua file. You will need to delete it. If you have any shopping lists to save use the export shopping lists feature to back them up first.

**Comment by Neurotoxin001** [comment]
I removed them now and it's still showing 24 hours after I set 48.

**Comment by plusmouse** [comment]
Are you using the "Selling" tab?

**Comment by Neurotoxin001** [comment]
I use default blizzard's selling tab – I just press right click on item and it's appearing there

**Comment by plusmouse** [comment]
You need to change your settings so that right-click puts it in the Auctionator selling tab.

![image](https://user-images.githubusercontent.com/60280559/95026957-d85b9200-068c-11eb-8a77-28f7100eb05e.png)

We have tried modifying the blizzard tab, but it caused throttling issues, so we had to make our own tab to do the settings with.

**Comment by Neurotoxin001** [comment]
Ah ok, I already found it now.

But there is no info that these timers is only work for auctionator selling tab :(

**Comment by plusmouse** [comment]
That's something we need to fix.

**Comment by tflo** [comment]
Thanks for the info here. In fact, I was also wondering how it is possible that this setting is broken for so long, lol.
