### ISSUE TITLE
Disenchant or Vendor Price fallback

### ISSUE THREAD

**Issue by mikfhan** [Auctionator/Auctionator#858]
**Is your feature request related to a problem? Please describe.**
Sometimes you just want to spam-sell items on AH without too much worry of lost profit, but there are no recent auctions to inform your default sales price. Typing in a price yourself for each item is a bit slow, you just want to head back to the dungeons.

**Describe the solution you'd like**
Perhaps disenchant probability and materials AH value could be the item's suggested buyout price fallback, and lacking or exceeding that, some predefined vendor price percent adjusted from within AddOn options (adding AH deposit on top of both).

**Describe alternatives you've considered**
Not really an alternative, just another thought if not implemented already, that item starting price after discount should minimum be 100% vendor price and have AH deposit added on top, so a slow auction won't be sold for less than vendor price.

**Additional context**
I got something like this working myself in a custom Auctionator tweak I did, but that was for old version 5.0.3 in early BFA days. From link below, search for "mikfhan begin" in the files Auctionator.lua + AuctionatorConfig.lua + AuctionatorHints.lua:

https://www.dropbox.com/sh/3azg37vwikrau3k/AABu6_H88Ma4GbSsm2AnKccKa?dl=0

**Comment by plusmouse** [comment]
If you modify `Source/Tabs/Selling/Mixin/SaleItem.lua` to add
```diff
diff --git a/Source/Tabs/Selling/Mixins/SaleItem.lua b/Source/Tabs/Selling/Mixins/SaleItem.lua
index 368f6c3..3a17d70 100644
--- a/Source/Tabs/Selling/Mixins/SaleItem.lua
+++ b/Source/Tabs/Selling/Mixins/SaleItem.lua
@@ -412,6 +412,12 @@ function AuctionatorSaleItemMixin:ProcessItemResults(itemKey)

   -- Didn't find anything currently posted, and nothing in DB
   if postingPrice == nil then
+    local item = Item:CreateFromItemLink(self.itemInfo.itemLink)
+    item:ContinueOnItemLoad(function()
+      self:UpdateSalesPrice(
+        select(11, GetItemInfo(self.itemInfo.itemLink))*10 + self:GetDeposit()
+      )
+    end)
     Auctionator.Debug.Message("Lowest price not found.")
     return
   end
```

That will make the default price 10 &times; vendor price (+ the deposit). Change the 10 to something else to change that.

[I've put the change in the relevant file here](https://github.com/Auctionator/Auctionator/files/5251429/modified.SaleItem.zip)

**Comment by plusmouse** [comment]
Added in alpha 354
![image](https://user-images.githubusercontent.com/60280559/95242575-44fa9c00-0807-11eb-8548-23e805667d7d.png)

**Comment by mikfhan** [comment]
NOICE!
