### ISSUE TITLE
Display inventory's item level or pet level information in the icons

### ISSUE THREAD

**Issue by Alinnia** [Auctionator/Auctionator#863]
**Is your feature request related to a problem? Please describe.**
Currently the level of the items and pets in my inventory is not displayed in the Selling tab. I can't easily tell what level my item or pet is. Also, I could have multiple icons that look the same because it's for the same item/pet but they represent different ilvl/pet level.

**Describe the solution you'd like**
The icons to display the item level or pet level. 
1. The icons in the left menu shows the quantity in the bottom right corner, so either top left or top right of the icon can display the level. 
2. It would be good if the big icon at the top that shows the currently selected item also displayed the level so that I know what level the item is that I'm going to list on the AH.

**Describe alternatives you've considered**
Can mouseover the icon to view the level information in the tooltip. However, the tooltip covers up part of the Selling tab screen and makes it very hard to see the information behind the tooltip, so would prefer not using this method if possible.

**Comment by plusmouse** [comment]
I don't think there's a simple solution, as sometimes the stats on gear matter too, so at some point checking the tooltip is necessary. Its been so long since this was filed its unlikely I'm going to do it (as it would have happened by now)
