### ISSUE TITLE
Auctionator Ledger

### ISSUE THREAD

**Issue by cindynico** [Auctionator/Auctionator#866]
Hi,

I prefere Auctionator to for example TSM. The only reason I still use TSM is for the ledger. A lot of my family and friends have the same problem. Both Addons are heavy and we only want to use one. We all prefere to use Auctionator so I was wondering if it would be possible to implement a Ledger?

Now I go in TSM and I can see verything I sold, vendored, bought from the past months and I can keep track who bought my stuff on AH and when. I can also keep track what I vendored.

This is e massive usefull part of the adoon and if Auctionator would have that I didnt have to use TSM anymore and didnt have to chose which addon to keep.

Hope you can implement this :)

Ty for all the super work on your great addon!

**Comment by plusmouse** [comment]
A new work in progress journal monitoring auction mails and posting is available at https://www.curseforge.com/wow/addons/journalator 

![image](https://user-images.githubusercontent.com/60280559/110475801-388dae80-80d9-11eb-81b3-c30c4a5a6320.png)

**Comment by cindynico** [comment]
Hi 🙂

Well done! tyvm 🙂
________________________________
Van: plusmouse <notifications@github.com>
Verzonden: dinsdag 9 maart 2021 14:14
Aan: Auctionator/Auctionator <Auctionator@noreply.github.com>
CC: cindynico <cindyke27@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [Auctionator/Auctionator] Auctionator Ledger (#866)


A new work in progress journal monitoring auction mails and posting is available at https://www.curseforge.com/wow/addons/journalator

[image]<https://user-images.githubusercontent.com/60280559/110475801-388dae80-80d9-11eb-81b3-c30c4a5a6320.png>

**Comment by plusmouse** [comment]
This is being tracked in https://github.com/Auctionator/Journalator - so I'm going to close this issue.
