### ISSUE TITLE
Bug Export srolling list

### ISSUE THREAD

**Issue by Adrenaline-E-Sports** [Auctionator/Auctionator#872]
If more than 8 lists are saved, not all of them will be seen in the Shopping Export function.

**Comment by plusmouse** [comment]
There should be a scroll bar
![image](https://user-images.githubusercontent.com/60280559/94776804-4caae280-03ba-11eb-8e2d-39cbb807f1e5.png)

Let me know if that helps.

**Comment by Adrenaline-E-Sports** [comment]
Exactly this button wasn't there. It works again after rebooting the game.
