### ISSUE TITLE
Auctionator v8.3.4 Release with Skillet

### ISSUE THREAD

**Issue by Galthariel** [Auctionator/Auctionator#875]
Just got the following error after using Skillet.

4x Skillet\Plugins\Auctionator-8.3.4.lua:251: bad argument #3 to 'format' (string expected, got nil)
[string "=[C]"]: in function `format'
[string "@Skillet\Plugins\Auctionator-8.3.4.lua"]:251: in function `GetExtraText'
[string "@Skillet\SkilletPlugin.lua"]:149: in function `GetExtraText'
[string "@Skillet\UI\MainFrame.lua"]:1761: in function `UpdateDetailsWindow'
[string "@Skillet\UI\MainFrame.lua"]:862: in function `UpdateTradeSkillWindow'
[string "@Skillet\Skillet-4.18.lua"]:827: in function `?'
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@Ace3\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by plusmouse** [comment]
I'm unable to replicate the error. Have you reported it to Skillet too?

**Comment by Galthariel** [comment]
Now I did :-)

**Comment by Galthariel** [comment]
Weird thing  is that the previous Alpha version wasn't giving me any errors

**Comment by plusmouse** [comment]
I had tested it against Skillet because I thought it might give errors, it didn't back then for me either.

**Comment by plusmouse** [comment]
Is this bug still a problem?

**Comment by plusmouse** [comment]
Closing due to lack of responses, and inability to replicate the bug.
