### ISSUE TITLE
New release is only offering to sell one duplicate pet at a time

### ISSUE THREAD

**Issue by raysmith59** [Auctionator/Auctionator#876]
I have 6 identical pets that I'm selling, until today I could just right-click and Post and all 6 would be up for sale, as of today's new version it's only putting up 1 at a time when I post.  I prefer the previous behaviour and since this wasn't addressed in the version notes I assume it wasn't an intentional change.

**Comment by plusmouse** [comment]
The quantities for most items (LIFO) and gear/pets (not LIFO) have separate settings now.

![image](https://user-images.githubusercontent.com/60280559/95089742-62067080-071c-11eb-9ba6-25993c9c0869.png)

You will need to change the quantity in your settings.
