### ISSUE TITLE
Post chat output msg for sales, plus total gold gathered.

### ISSUE THREAD

**Issue by strickland** [Auctionator/Auctionator#877]
**Is your feature request related to a problem? Please describe.**
Not related to a problem

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Usually I go to the ingame mail then click "Open All Mail", then it starts collecting cancelled items + gold for sold items.

But then I can't know what was sold, basically I used to use TSM and it shows in chat a text about what was sold + total amount gathered from this mail opening.

I just miss this feature, its just an output msg in chat, nothing fancy, I'm not sure if it is easy to develop, if so then that would be really nice.

**Comment by Alinnia** [comment]
Hi, I actually use a separate addon called Postal that does exactly that - it shows in chat a text line for per mail collected and the total gold collected. It's a also very lightweight addon, especially compared to TSM, so I definitely recommend you give Postal a go as it does exactly what you're looking for. Hope that helps.

**Comment by strickland** [comment]
ill get postal, thanks.

**Comment by strickland** [comment]
i've tested it, exactly what I was looking for, thank you for the suggestion <3

**Comment by plusmouse** [comment]
As the feature request has been solved by another addon, closing this issue. If you want the issue to remain open add a message and I can reopen it.
