### ISSUE TITLE
Disappearing Items from Cancelling Tab

### ISSUE THREAD

**Issue by cmorse318** [Auctionator/Auctionator#878]
## Brief Description of Bug

When you have multiple of a stackable item listed on the Auction House and somebody purchases only part of that inventory you have listed, the entire item is removed from the Cancelling tab of Auctionator even though you still have stock remaining. The only way to refresh the display is by running the reload UI command and it catches itself back up to present. I'm not sure if it happens 100% of the time, but it does happen to me frequently enough that I decided to look up the GitHub page and write a report for this issue. I also understand it may be a tricky fix due to how the AH works now.

## Steps to Reproduce

List multiple quantities of something stackable on the auction house, such as 50 Abyssal Healing Potions. When somebody purchases only part of that stack of 50, such as 5, 10, or 20 potions, the entire Abyssal Healing Potion row will be removed from the Cancelling tab. It seems to happen whether or not you currently have the Auction House open. I encounter this issue multiple times per day, so you should have no trouble reproducing the glitch.

## Loaded Addons

Standard raiding stuff + Auctionator and TSM.

## Conclusion

Thanks for your time and hard work on this add-on!

**Comment by plusmouse** [comment]
Do the purchased auctions show up correctly in TSM or the default UI view?

**Comment by cmorse318** [comment]
I usually don't use the TSM portion of the Auction House so I'm not sure about that one, but everything is correct on the default UI "Auctions" tab when this occurs. For example, if I had 50 healing potions listed and 20 sold, I'll see on the default auctions tab that 20 are sold and 30 are still listed. But on the Auctionator Cancelling tab I wouldn't see any healing potions at all without a relog or reloading UI. Hope that helps!

**Comment by plusmouse** [comment]
The latest alpha (355) should have this fixed. If it isn't, post on this issue and I'll reopen it.
