### ISSUE TITLE
LUA Error

### ISSUE THREAD

**Issue by RobSaab** [Auctionator/Auctionator#880]
Soon as I log in this is reported to BugGrabber.

2x Overachiever\Overachiever-1.0.9.lua:1461: Usage: GameTooltip:HookScript("frameScriptTypeName", function[, bindingType])
[string "=[C]"]: in function `HookScript'
[string "@Overachiever\Overachiever-1.0.9.lua"]:1461: in function <Overachiever\Overachiever.lua:1377>

Locals:
(*temporary) = GameTooltip {
 0 = <userdata>
 OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:205
 ItemTooltip = <unnamed> {
 }
 SetHyperlink = <function> defined =[C]:-1
 RightEdge = <unnamed> {
 }
 ClearBackdrop = <function> defined @SharedXML\Backdrop.lua:335
 SetLFGDungeonReward = <function> defined @AllTheThings\AllTheThings.lua:4666
 numMoneyFrames = 2
 SetRecipeReagentItem = <function> defined @Altoholic\Tooltip.lua:702
 SetBuybackItem = <function> defined =[C]:-1
 SetMerchantItem = <function> defined =[C]:-1
 SetupTextureCoordinates = <function> defined @SharedXML\Backdrop.lua:267
 TopRightCorner = <unnamed> {
 }
 GetEdgeSize = <function> defined @SharedXML\Backdrop.lua:241
 updateTooltip = 0.200000
 SetInventoryItem = <function> defined =[C]:-1
 TopEdge = <unnamed> {
 }
 SetLootRollItem = <function> defined =[C]:-1
 SetBagItem = <function> defined =[C]:-1
 BottomRightCorner = <unnamed> {
 }
 SetBackdropColor = <function> defined @SharedXML\Backdrop.lua:452
 LeftEdge = <unnamed> {
 }
 SetCurrencyByID = <function> defined @AllTheThings\AllTheThings.lua:4628
 textLeft1Font = "GameTooltipHeaderText"
 customBackdropAlpha = 0.800000
 SetTrainerService = <function> defined =[C]:-1
 SetCurrencyToken = <function> defined =[C]:-1
 SetGuildBankItem = <function> defined =[C]:-1
 hasMoney = 1
 TopLeftCorner = <unnamed> {
 }
 SetItemByID = <function> defined =[C]:-1
 Hide = <function> defined =[C]:-1
 SetExistingSocketGem = <function> defined =[C]:-1
 SetLootItem = <function> defined =[C]:-1
 template = "Transparent"
 TextRight1 = GameTooltipTextRight1 {
 }
 ApplyBackdrop = <function> defined @SharedXML\Backdrop.lua:347
 SetBackdrop = <function> defined @SharedXML\Backdrop.lua:382
 TopOverlay = <unnamed> {
 }
 GetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:462
 GetBackdrop = <function> defined @SharedXML\Backdrop.lua:400
 SetUnitDebuff = <function> defined =[C]:-1
 SetHeirloomByItemID = <function> defined =[C]:-1
 SetUnitBuff = <function> defined =[C]:-1
 SetQuestItem = <function> defined =[C]:-1
 BottomEdge = <unnamed> {
 }
 SetBorderBlendMode = <function> defined @SharedXML\Backdrop.lua:319
 SetToyByItemID = <function> defined =[C]:-1
 SetBackpackToken = <function> defined =[C]:-1
 SetCurrencyTokenByID = <function> defined =[C]:-1
 BottomLeftCorner = <unnamed> {
 }
 SetInboxItem = <function> defined =[C]:-1
 TextLeft1 = GameTooltipTextLeft1 {
 }
 shoppingTooltips = <table> {
 }
 SetLFGDungeonShortageReward = <function> defined @AllTheThings\AllTheThings.lua:4683
 Center = <unnamed> {
 }
 OnBackdropSizeChanged = <function> defined @SharedXML\Backdrop.lua:235
 SetTradeTargetItem = <function> defined =[C]:-1
 StatusBar = GameTooltipStatusBar {
 }
 SetTradePlayerItem = <function> defined =[C]:-1
 textRight1Font = "GameTooltipHeaderText"
 SetSendMailItem = <function> defined =[C]:-1
 GetBackdropColor = <function> defined @SharedXML\Backdrop.lua:443
 HasBackdropInfo = <function> defined @SharedXML\Backdrop.lua:331
 textLeft2Font = "GameTooltipText"
 SetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:475
 TextRight2 = GameTooltipTextRight2 {
 }
 TextLeft2 = GameTooltipTextLeft2 {
 }
 SetUnitAura = <function> defined =[C]:-1
 SetQuestLogItem = <function> defined =[C]:-1
 textRight2Font = "GameTooltipText"
 SetItemKey = <function> defined =[C]:-1
 needsReset = true
 SetupPieceVisuals = <function> defined @SharedXML\Backdrop.lua:299
 backdropInfo = <table> {
 }
 BottomOverlay = <unnamed> {
 }
 SetRecipeResultItem = <function> defined @Altoholic\Tooltip.lua:702
}
(*temporary) = "OnTooltipSetUnit"
(*temporary) = nil

**Comment by plusmouse** [comment]
This isn't an Auctionator error - you'll need to enable/disable addons one by one until you can determine which one is causing the error.

**Comment by RobSaab** [comment]
Sorry, I posted the wrong bug but seems an update fixed whatever was happening.  No idea as so many addons are going bonkers.  Sorry to have wasted your time.

Robert
