### ISSUE TITLE
Stop hiding item?

### ISSUE THREAD

**Issue by gitsocko** [Auctionator/Auctionator#881]
Description: cannot unhide item on Selling tab
Steps: hide an item and try to unhide it

**Comment by gitsocko** [comment]
Description: cannot unhide item on Selling tab
Steps: hide an item and try to unhide it

**Comment by plusmouse** [comment]
Right click any other item, and click "Restore All"
![image](https://user-images.githubusercontent.com/60280559/96072133-80e2d080-0e9b-11eb-835d-4c8de854fa00.png)

**Comment by gitsocko** [comment]
Got it; thanks @plusmouse!
