### ISSUE TITLE
Include Craft Cost Information in Tooltip

### ISSUE THREAD

**Issue by Drkangl32** [Auctionator/Auctionator#884]
My thought was to include crafting cost information in the mouse over dialogue box.  So, as we mouse over potential items to sell or craft we might also see the 1:1 total crafting cost based on the most current auction scan.  This feature might be toggled on/off via a check box in your option menu.

With massive numbers of crafted items currently in game, I imagine a feature like this to be difficult to implement and maintain as new crafted items are usually added with each patch.  Some additional math may also be required since many consumables are crafted as stacks.  However, it would be extremely useful and save a tremendous amount of time for players.  Please consider it!

**Comment by plusmouse** [comment]
This is out of scope for Auctionator.

The Auctionator core focusses exclusively on UIs to do with managing auctions, and leaves accountancy and statistics generation to other addons.

The [API ](https://github.com/Auctionator/Auctionator/wiki/API-Documentation) will let another addon implement this feature and use Auctionator's prices.
