### ISSUE TITLE
Add Bidding Option to Selling Tab

### ISSUE THREAD

**Issue by Drkangl32** [Auctionator/Auctionator#885]
First, I want to complement you on your creativity in putting together the "Selling" tab.  A very innovative design.  As I get used to the more efficient operation, I see its potential.  

I may be using the Selling tab incorrectly as I do not see a way to implement a bid option.  If this is the case, please explain and disregard my request below.

I wanted to request that you consider adding a bidding option to your Selling tab.  While I am not a big fan of bidding, it seems that more players are now including a bid price when they post high value items (especially gear, pets and mounts).  If I am to remain competitive , I must also include a bid price.  In fact, not long ago I sold a Wooly White Rhino for over a million gold only because I provided a bid option.

If you are unable to designate space for a bid price in the Selling tab, perhaps you might reactivate your undercut feature in Blizzard's Sell tab (since bidding is included) so we can use this tab as an alternative.

Either way, I appreciate all your efforts to improve Auctionator with fresh ideas.

**Comment by plusmouse** [comment]
There isn't a bid option in the Selling tab. Adding the option to the Selling tab means adding another option to an already busy tab, and we'd like to avoid that.

The undercut feature was disabled on the "Sell" tab as it caused unavoidable throttling issues - to the point that individuals who used the Sell tab a lot disabled the undercut feature to save time.

**Comment by tflo** [comment]
The lack of the possibility to enter a bid price is really an issue for some auctions. For most auctions I can live without bid (though, via TSM, I always set a bit if available), but for some auctions a bid is still a must.

> Adding the option to the Selling tab means adding another option to an already busy tab, and we'd like to avoid that.

Well, with a little rearrangement in the upper part of the frame, I think it can fit well – _without making it too busy_. Here a little mock-up:

![auctionator-test-fs8](https://user-images.githubusercontent.com/1410282/109476545-56bf3300-7a77-11eb-83f4-8c96d2ecf02b.png)

Thanks for considering.

And many thanks for all the great work you put into Auctionator!

– Tom

**Comment by Drkangl32** [comment]
Nice mock-up Tom.

I also notice that the "post" button could be reduced in width to make a bit more space.  Perhaps that might make just enough space to add silver to bids.

I would be happy with any bid functionality on the selling tab, even if the undercut feature did not work for it.  Currently I am having to alternate between sell and selling tabs just to do basic posting (with and without bids) which is somewhat counter productive.

Again, I am not into adding in bids when I post.  However, it almost always becomes necessary as I compete with others who post with a low-ball bid option.   The way I see it, a lower bid is just another form of an undercut.  

I know adapting to the new auction house layout has been a challenge and issues like these will be ironed out with time.  Meanwhile, I still appreciate the creative efforts made by Plusmouse and others who make this mod stand out.

**Comment by plusmouse** [comment]
Some updates:
![image](https://user-images.githubusercontent.com/60280559/109608685-254f7180-7b22-11eb-9c50-9a4236608133.png)
* It will be an option that you have to enable, the bid price will be hidden by default
* I still need to make the field work and handle faulty inputs (more than buyout price, 0, permit bid price only etc.)
* For undercutting I was thinking of doing it the way from pre 8.3 Auctionator. The only option would be to set a % (defaults 5%) below the chosen buyout price.

When disabled the Selling view will look like it always does:
![image](https://user-images.githubusercontent.com/60280559/109609230-f5ed3480-7b22-11eb-96af-c9eee9fe228b.png)

**Comment by Drkangl32** [comment]
This is amazing!  Super clean layout and offers everything we need to get posting done at maximum efficiency.  There is even a bit of extra space in case you want to add more features later.  Perfect!

Would the toggle be a manual switch that would maintain our interface until we change it?  Or, would it be like the Blizzard bid check box that automatically reverts back to buy-out only default when we exit the AH (or uncheck the box)?  I wonder what would work the best for most users?  Either way, an "enable bidding" check box toggle of some kind might need to be added to the selling tab.

With regard to undercuts, I only apply them to gear and pets.  Pricing for these items average 10 - 20K.  However, I am usually only interested in a "set price" undercut of 1G, 10S to avoid driving the price down too much.  As an example, if undercutting 1% on a 20K item, the price drops around 200G per undercut which is more than I wish to give away.  Especially if there is an undercut war going on.

In any case, I would be happy with any way you are able to implement the bidding options.  This includes price match only, percentage undercut, set price undercut or anything else you can manage.  It can always be enhanced later.  For the time being, we can go in and make manual price alterations as needed.  What is key is that everything we need for posting is laid out on the same page for easy access and simplicity!

Hopefully, buy out undercut features would remain as they are.

**Comment by plusmouse** [comment]
Auctionator pre-8.3 hid the bid prices by default (you had to enable them in the settings), this will be no different in that respect:
![image](https://user-images.githubusercontent.com/60280559/109630248-9c91ff00-7b3c-11eb-8174-c9bf10a508ac.png)

I'm not planning to change the buyout undercut features - the change here is just adding a bid option

Still not got a working version, only the UI so far 😄

**Comment by plusmouse** [comment]
Find this in alpha 541 (available on discord, and in a minute or 2, curseforge)
# Updates
Now got a config option:
![image](https://user-images.githubusercontent.com/60280559/109644648-a4a66a80-7b4d-11eb-941d-ef4d8553daef.png)

And a functioning bid box:
![image](https://user-images.githubusercontent.com/60280559/109644722-c56ec000-7b4d-11eb-808d-ca13bb4ca3a8.png)

**Comment by Drkangl32** [comment]
From what I see, the selling tab layout looks excellent.  Having posting features all on the same tab will save users a tremendous amount of time.

If you are considering a future bid undercut feature, perhaps the easiest way to do it might be to share all settings with the buy-out undercut interface.  Simply check or uncheck a box: "apply same undercut settings to bidding if enabled".  Leaving the box unchecked might default to price match only (like the Blizzard AH interface).  Just an idea that might simplify any potential implementation. 

It will be very important to make sure that bidding is automatically cancelled if bid cells only have a zero entry.  Like the Blizzard interface, the system should default to buy-out only (no bids) when such post is made.

Looking forward to trying out your revisions!

**Comment by plusmouse** [comment]
At the moment the bid price automatically matches the buyout price, and bidding is only turned on if the prices differ.

I'm unclear on which price you wanted the bid price to undercut (did you intend it to undercut 1 or 2 - from the screenshot):
![image](https://user-images.githubusercontent.com/60280559/109760064-fdc1dd00-7be5-11eb-8c2a-4c9976f6c8cd.png)

Its unlikely I'll be adding a full selection of undercut settings for bidding.

**Comment by Drkangl32** [comment]
An undercut for number 2 would be ideal.   The main reason to offer a bid option is usually to undercut a rival that already has a bid offering up.  We want to steal a potential sale away from them with an undercut to anything they can offer (including bidding).

Undercut bid price can always be added in later.  A price match would be fine for now (number 2).  

In the future, I agree about not going to the trouble to adding in a bunch of separate undercut settings for bidding.  My thinking was to try to share settings from the "buy-out" undercut section.  Just check a box to share buy-out settings with bidding :  "apply same undercut settings to bidding if enabled".  So, if buy-out is set for 1% undercut, bidding would also undercut 1%.  Or, if buy-out is set to undercut 1G, bidding would also undercut 1G.  Unchecking the box reverts to bid price match default.
