### ISSUE TITLE
dropdown for shopping-lists: sortable, scrollable ?

### ISSUE THREAD

**Issue by Ahfau77** [Auctionator/Auctionator#886]
I just switched from Auctioneer after years to your addon and i really like your feature of the shopping-lists.

After creating nearly 30 lists regarding the professions-materials for the several wow-extensions, i would love to have the ability to sort the list in the dropdown located at the top-left. It would be sufficient for me if the shopping-lists listed in the dropdown would be sorted by name as default.

Additionally if the list is pretty long, it would be helpful if the dropdown has a maximum height and if this specific height is reached, the list gets scrollable and won't grow further in height.

**Comment by plusmouse** [comment]
Implemented sorting shopping lists, find it in the latest alpha (398).

Making the list scrollable isn't going to be done for now.
