### ISSUE TITLE
Auctionator\Source\FullScan\Mixins\Frame.lua:107: Usage: NonEmptyItem:ContinueOnLoad(callbackFunction)

### ISSUE THREAD

**Issue by Galthariel** [Auctionator/Auctionator#887]
Getting the error bellow after latest release v9.0.0.1

1x Auctionator\Source\FullScan\Mixins\Frame.lua:107: Usage: NonEmptyItem:ContinueOnLoad(callbackFunction)
[string "=[C]"]: in function `error'
[string "@FrameXML\ObjectAPI\Item.lua"]:233: in function `ContinueOnItemLoad'
[string "@Auctionator\Source\FullScan\Mixins\Frame.lua"]:107: in function `ProcessBatch'
[string "@Auctionator\Source\FullScan\Mixins\Frame.lua"]:135: in function <Auctionator\Source\FullScan\Mixins\Frame.lua:134>

Locals:
(*temporary) = "Usage: NonEmptyItem:ContinueOnLoad(callbackFunction)"

No errors in the previous version

**Comment by plusmouse** [comment]
Not 100% sure that what I've done will fix the problem, so keep an eye out for any future errors, or the scan getting frozen.

**Comment by Galthariel** [comment]
👍
