### ISSUE TITLE
Make the auctionhouse-window moveable

### ISSUE THREAD

**Issue by Ahfau77** [Auctionator/Auctionator#889]
Is it possible that you make the frame for the auctionhouse moveable like in auctioneer, so you can drag and drop it freely on the screen?

**Comment by plusmouse** [comment]
Have you tried an addon like https://www.curseforge.com/wow/addons/blizzmove

**Comment by Ahfau77** [comment]
[BlizzMove](https://www.curseforge.com/wow/addons/blizzmove) works like a charm, thx :)
