### ISSUE TITLE
LUA error when closing auction interface in latest version

### ISSUE THREAD

**Issue by raysmith59** [Auctionator/Auctionator#891]
1x Auctionator\Source\FullScan\Mixins\Frame.lua:107: Usage: NonEmptyItem:ContinueOnLoad(callbackFunction)
[string "=[C]"]: in function `error'
[string "@FrameXML\ObjectAPI\Item.lua"]:233: in function `ContinueOnItemLoad'
[string "@Auctionator\Source\FullScan\Mixins\Frame.lua"]:107: in function `ProcessBatch'
[string "@Auctionator\Source\FullScan\Mixins\Frame.lua"]:135: in function <Auctionator\Source\FullScan\Mixins\Frame.lua:134>

Locals:
(*temporary) = "Usage: NonEmptyItem:ContinueOnLoad(callbackFunction)"

**Comment by plusmouse** [comment]
A fix has been put in the latest release, 9.0.0.3.
