### ISSUE TITLE
View Item Price History in Buying Tab

### ISSUE THREAD

**Issue by Gotlyfe** [Auctionator/Auctionator#892]
When buying items, it would be very helpful to be able to check the price history for the items.

I am unaware of any way to do this without owning one of the items that I can put in the Sell tab.

**Comment by iomect** [comment]
We need this feature

**Comment by plusmouse** [comment]
A solution is available in alpha 448, does the below solve this issue?

Right-click any result in the "Shopping" tab to view a price history
![image](https://user-images.githubusercontent.com/60280559/103127677-98ec8280-468a-11eb-9d90-f1ed51ffe230.png)

**Comment by iomect** [comment]
Just updated and tested, great!

**Comment by Gotlyfe** [comment]
💰💛💰💛💰💛💰💛

**Comment by c1v1d** [comment]
> A solution is available in alpha 448, does the below solve this issue?
> 
> Right-click any result in the "Shopping" tab to view a price history
> ![image](https://user-images.githubusercontent.com/60280559/103127677-98ec8280-468a-11eb-9d90-f1ed51ffe230.png)

I'm not sure if you are aware of this issue or not, but the price history isn't always accurate. Someone can post an item for 1 copper and auctionator will automatically default the price history to the lowest listing of the day. 
![AH](https://user-images.githubusercontent.com/76636269/103162487-dc440f80-47b6-11eb-88d3-e4928fc934f1.jpg)
