### ISSUE TITLE
Feature not available for Free Trial accounts.

### ISSUE THREAD

**Issue by mikfhan** [Auctionator/Auctionator#896]
## Brief Description of Bug

Opening auction house on a Free Trial account causes Lua Error with Auctionator.Tooltip.LateHooks() hooksecurefunc.

## Steps to Reproduce

Log into WoW retail 9.0.1 with Auctionator 9.0.0.3 and talk to any auction house NPC, the Lua Error pops up when the "Feature not available for Free Trial accounts." error message pops up.

## Loaded Addons

Auctionator 9.0.0.3 only.

## Back Trace (LUA Error Output)

Message: ...terface\AddOns\Auctionator\Source\Tooltips\Hooks.lua:232: Usage: hooksecurefunc([table,] "function", hookfunc)
Time: Thu Oct 22 19:20:48 2020
Count: 1
Stack: ...terface\AddOns\Auctionator\Source\Tooltips\Hooks.lua:232: Usage: hooksecurefunc([table,] "function", hookfunc)
[string "=[C]"]: in function `hooksecurefunc'
[string "@Interface\AddOns\Auctionator\Source\Tooltips\Hooks.lua"]:232: in function `LateHooks'
[string "@Interface\AddOns\Auctionator\Source\Core\Mixin.lua"]:107: in function <Interface\AddOns\Auctionator\Source\Core\Mixin.lua:102>
[string "@Interface\AddOns\Auctionator\Source\Core\Mixin.lua"]:130: in function <Interface\AddOns\Auctionator\Source\Core\Mixin.lua:122>
[string "=[C]"]: in function `CreateFrame'
[string "@Interface\AddOns\Auctionator\Source\Events\OnAuctionHouseShow.lua"]:7: in function `OnAuctionHouseShow'
[string "@Interface\AddOns\Auctionator\Source\Events\Handler.lua"]:10: in function `Handler'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

Locals: (*temporary) = <table> {
 UpdateOnBarHighlightMarksBySpell = <function> defined @Interface\FrameXML\ActionButton.lua:78
 ERR_OUT_OF_CHI = "Not enough chi"
 DH_HAVOC_CORE_ABILITY_2 = "Strong melee attack that consumes Fury. If it critical strikes, some Fury is refunded."
 MultiCastActionButton6Cooldown = MultiCastActionButton6Cooldown {
 }
 MerchantItem9ItemButtonStock = MerchantItem9ItemButtonStock {
 }
 GetTrainerServiceTypeFilter = <function> defined =[C]:-1
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Color unit names."
 SetTrainerServiceTypeFilter = <function> defined =[C]:-1
 LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 741
 SPELL_FAILED_CUSTOM_ERROR_71 = "This partygoer wants to dance with you."
 LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 400
 ERROR_CLUB_TICKET_COUNT_AT_MAX_COMMUNITY = "Can't create any more invite links for this community."
 RecruitAFriendFrame = RecruitAFriendFrame {
 }
 CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture = CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture {
 }
 TutorialFrameLeft19 = TutorialFrameLeft19 {
 }
 MultiCastActionButton2Cooldown = MultiCastActionButton2Cooldown {
 }
 ERR_TRADE_EQUIPPED_BAG = "You can't trade equipped bags."
 PVP_RANK_6_1 = "Corporal"
 MultiBarLeftButton7 = MultiBarLeftButton7 {
 }
 AudioOptionsVoicePanelOutputDeviceDropdownButtonHighlightTexture = AudioOptionsVoicePanelOutputDeviceDropdownButtonHighlightTexture {
 }
 VideoOptionsFrameDefaults = VideoOptionsFrameDefaults {
 }
 MerchantItem1AltCurrencyFrameItem1Text = MerchantItem1AltCurrencyFrameItem1Text {
 }
 OPTION_TOOLTIP_ACTION_BUTTON_USE_KEY_DOWN = "Action button keybinds will respond on key down, rather than on key up."
 BINDING_NAME_NAMEPLATES = "Show Enemy Name Plates"
 CHAT_HEADER_SUFFIX = ": "
 MultiBarBottomRightButton8Shine5 = MultiBarBottomRightButton8Shine5 {
 }
 COVENANT_MISSIONS_HEALTH = "Health"
 MAIL_LETTER_TOOLTIP = "Click to make a permanent
copy of this letter."
 UnitFrameManaBar_UnregisterDefaultEvents = <function> defined @Interface\FrameXML\UnitFrame.lua:782
 PaperDollTitlesPaneButton10BgTop = PaperDollTitlesPaneButton10BgTop {
 }
 DUNGEON_FLOOR_UPPERBLACKROCKSPIRE3 = "Hall of Blackhand"
 CHAT_CONFIG_OTHER_COMBAT = <table> {
 }
 FCFDockOverflowButton_OnClick = <function> defined @Interface\FrameXML\FloatingChatFrame.lua:2379
 TutorialFrameRight19 = TutorialFrameRight19 {
 }
 ChatFrame6EditBoxFocusMid = ChatFrame6EditBoxFocusMid {
 }
 BN_UNABLE_TO_RESOLVE_NAME = "Unable to whisper '%s'. Blizzard services may be unavailable."
 AutoCompleteEditBox_OnKeyDown = <function> defined @Interface\FrameXML\AutoComplete.lua:366
 CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight = CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight {
 }
 LFGTeleport = <function> defined =[C]:-1
 LE_GAME_ERR_ONLY_ONE_QUIVER = 32
 INT_SPELL_DURATION_HOURS = "%d |4hour:hrs;"
 ToggleEncounterJournal = <function> defined @Interface\FrameXML\UIParent.lua:1035
 LOSS

**Comment by plusmouse** [comment]
A fix is in the latest alpha (377) and will go out in the next release of Auctionator.
