### ISSUE TITLE
Selling

### ISSUE THREAD

**Issue by vandiel01** [Auctionator/Auctionator#897]
Using '/atr post' macro, was selling xmog from my bag.  In Selling tab, when selling xmogs and it comes to last item, the item on the Selling tab "still there" but my bags are empty then it gives me error and does not refresh when I close/open AH

`1x ...\Auctionator\Source\Tabs\Selling\Mixins\SaleItem.lua:64: bad argument #1 to 'LockItem' (Usage: C_Item.LockItem(itemLocation))
[string "=[C]"]: in function `LockItem'
[string "@Auctionator\Source\Tabs\Selling\Mixins\SaleItem.lua"]:64: in function `LockItem'
[string "@Auctionator\Source\Tabs\Selling\Mixins\SaleItem.lua"]:127: in function `ReceiveEvent'
[string "@Auctionator\Source\Utilities\EventBusMixin.lua"]:86: in function `Fire'
[string "@Auctionator\Source\Tabs\Selling\Mixins\BagItem.lua"]:47: in function <...s\Auctionator\Source\Tabs\Selling\Mixins\BagItem.lua:41>

Locals:
(*temporary) = <table> {
 Clear = <function> defined @FrameXML\ObjectAPI\ItemLocation.lua:21
 IsEquipmentSlot = <function> defined @FrameXML\ObjectAPI\ItemLocation.lua:48
 IsEqualToBagAndSlot = <function> defined @FrameXML\ObjectAPI\ItemLocation.lua:64
 SetBagAndSlot = <function> defined @FrameXML\ObjectAPI\ItemLocation.lua:27
 IsBagAndSlot = <function> defined @FrameXML\ObjectAPI\ItemLocation.lua:52
 SetEquipmentSlot = <function> defined @FrameXML\ObjectAPI\ItemLocation.lua:38
 slotIndex = 16
 HasAnyLocation = <function> defined @FrameXML\ObjectAPI\ItemLocation.lua:56
 bagID = 4
 GetEquipmentSlot = <function> defined @FrameXML\ObjectAPI\ItemLocation.lua:44
 IsEqualToEquipmentSlot = <function> defined @FrameXML\ObjectAPI\ItemLocation.lua:72
 GetBagAndSlot = <function> defined @FrameXML\ObjectAPI\ItemLocation.lua:34
 IsValid = <function> defined @FrameXML\ObjectAPI\ItemLocation.lua:60
 IsEqualTo = <function> defined @FrameXML\ObjectAPI\ItemLocation.lua:80
}`

**Comment by plusmouse** [comment]
Tested posting the last item in my bag and didn't have an issue. Not sure what triggered it, but if it happens again can you take a screenshot?

**Comment by vandiel01** [comment]
will do

**Comment by plusmouse** [comment]
This issue hasn't reoccurred for more than a month. Closing.
