### ISSUE TITLE
Enchanting: Search does not find enchantment

### ISSUE THREAD

**Issue by StanoRiga** [Auctionator/Auctionator#899]
## Brief Description of Bug

When using the "search" button in the enchantment profession, the search does find the materials, but not the enchantment (see video file here: https://streamable.com/1tgewb).
If you want to search via auctionator tab for an enchantment with the exact name (eg. "Ring - Pakt der Meisterschaft" nothing is found with Auctionator, but with standard AH search. Now it becomes weird: When using the profession "search" button Auctionator searches (in my example) for "Pakt der Meisterschaft" and does not find anything (as shown in the video). But if I manually add a search for "Pakt der Meisterschaft" in Auctionator, the enchantment is found.
This does not happen with cooking or tailoring.
(german client)

## Steps to Reproduce
1) open auction house
2) open professions book
3) select a recipe you are sure that materials and enchantments are available in AH
4) click the search button (mats are found, enchantment not
5) add an item to the auctionator temporary search list with the same search phrase as the enchantment
6) enchantment now is found.

## Loaded Addons
all other temporary deactivated

## Back Trace (LUA Error Output)
No Buggrabber output

**Comment by plusmouse** [comment]
Tested and can confirm this happens on the English client too.

**Comment by Rhyzco** [comment]
This has to do with "exact search" parameter that can be found if you edit the shopping list item that it's being searched. When you open your enchanting profession window, the reagents the name is the same when in you search the auction house, but enchantments are different. For example "Eternal Agility" is in auction house "Enchant boots - Eternal Agility", if you edit the search item and remove the "exact search" the enchantment is listed again.
Maybe add an option to search with Exact Search on or off?

**Comment by Weissrolf** [comment]
Either turn Exact search off by default or make it search for the full name like "Enchant boot -".

**Comment by plusmouse** [comment]
Modified the search to turn exact search off when searching for an enchantment

**Comment by plusmouse** [comment]
Find the fix in alpha 503 - this will be included in the next normal release.
