### ISSUE TITLE
Item price visual comparison on "Selling" tab

### ISSUE THREAD

**Issue by addonaddict** [Auctionator/Auctionator#900]
**Is your feature request related to a problem? Please describe.**
Not necessarily a problem, but I tend to have a character with a ton of transmog items in the bags. Some of the pieces I want to sell, and some that are not worth selling i want to use for my own transmog unlock or sell to vendor. This is a hassle when I have all of my bags full with gear pieces as I have no visual indication what is worth more than the rest and i have to hover or click on each item 1 by 1 and decide then if it is worth selling.

**Describe the solution you'd like**
If possible to implement - i would like to see some kind of colored indicator (example: dot/line over the item icon that changes color gradually - perhaps red to green spectrum?). this indicator would compare the prices of all items currently in the bag/"selling" tab between each other and be colored accordingly. This would be based on single items, ignoring the quantities.
Of course this could also be a toggle in the options for users who do not want to see this or need this option.

This would also give you a better visualization on what is worth farming more compared to other things (possibly extend outside the selling tab to your bags with a toggle?)

Im not sure if this is a good idea or is feasible but i just wanted to leave my feedback here as this is one of the only gripes I have when posting a million transmogs / different types of herbs ores etc. to AH

Thank you so much for the great addon, I will be using it always even if this is not implement <3

![image](https://user-images.githubusercontent.com/73442541/97808525-6cd9f580-1c35-11eb-9906-10fad663b4c8.png)

**Comment by plusmouse** [comment]
Closing as this feature request is unlikely to happen.
