### ISSUE TITLE
Tooltip dont show Auctionator Info

### ISSUE THREAD

**Issue by Avabehe** [Auctionator/Auctionator#901]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug
I am using Auctionator 9.0.0.3

The Issue is @the chat Links of items and in skillet @ reagents tooltip, the Auction Price Info isnt shown

## Steps to Reproduce

Hover an Itemlink in the chat or hover an reagent in skillet 
![WoWScrnShot_110220_174434](https://user-images.githubusercontent.com/46047858/97966585-501bfa00-1dbc-11eb-9828-fff1e54b11d7.jpg)

## Loaded Addons

Skillet
ElvUI
ElvUI BenikUI
ProejctAzilroka
Auctionator

## Back Trace (LUA Error Output)

no LUA Error message

Maybe the Creator from Skillet could help to find it, it tooks him hours to find the issue(In the beginning I thought its an Skillet Error)

https://www.curseforge.com/wow/addons/skillet/issues/608

**Comment by b-morgan** [comment]
Skillet does not use LibExtraTip so the following code (in ...\Tooltips\Hooks.lua) doesn't get called.

```
-- This is called when mousing over a reagant item on a recipe page in the tradeskill window
hooksecurefunc( GameTooltip, 'SetRecipeReagentItem',
  function( tip, reagentId, index )
    local itemLink = C_TradeSkillUI.GetRecipeReagentItemLink(reagentId, index)

    local itemCount = select(3, C_TradeSkillUI.GetRecipeReagentInfo(reagentId, index))

    Auctionator.Tooltip.ShowTipWithPricing(tip, itemLink, itemCount)
  end
);
```

**Comment by vsaR1SK** [comment]
Still no fix for chat?

**Comment by Avabehe** [comment]
No, it isnt fixed :(

**Comment by plusmouse** [comment]
Tested with Skillet enabled, the auction prices do appear on chat links:
![image](https://user-images.githubusercontent.com/60280559/100577581-71e3a080-32d8-11eb-8909-7273d725fe7b.png)

We assume that tooltips for prices are from `GameTooltip`, I'm guessing Skillet doesn't use `GameTooltip` for the reagents - which is why we don't attach a price.

**Comment by plusmouse** [comment]
Had a look at hooking `SetHyperlink` to show the price, we can't because hooking to `SetHyperlink` causes issues with tooltips inside the auction house.

**Comment by plusmouse** [comment]
@b-morgan Got a solution, if you use `GameTooltip:SetItemByID` instead of `GameTooltip:SetHyperlink` the auction price shows up correctly:
![image](https://user-images.githubusercontent.com/60280559/100580753-6eebae80-32de-11eb-86e7-b6acf3f96bf5.png)

```diff
diff --git a/UI/MainFrame.lua b/UI/MainFrame.lua
index 847f4bc..47e827f 100644
--- a/UI/MainFrame.lua
+++ b/UI/MainFrame.lua
@@ -1481,7 +1481,7 @@ function Skillet:SetTradeSkillToolTip(skillIndex)
                if recipe.itemID ~= 0 then
                        if self.currentTrade == 7411 then               -- Enchanting
                                --DA.DEBUG(2,"Using SetHyperlink (itemID)")
-                               GameTooltip:SetHyperlink("item:"..recipe.itemID)
+                               GameTooltip:SetItemByID(recipe.itemID)
                        else
                                --DA.DEBUG(2,"Using SetRecipeResultItem")
                                GameTooltip:SetRecipeResultItem(recipeID)
@@ -1512,7 +1512,7 @@ end
 function Skillet:SetReagentToolTip(reagentID, numNeeded, numCraftable)
        --DA.DEBUG(0,"SetReagentToolTip("..tostring(reagentID)..", "..tostring(numNeeded)..", "..tostring(numCraftable)..")")
        GameTooltip:ClearLines()
-       GameTooltip:SetHyperlink("item:"..reagentID)
+       GameTooltip:SetItemByID(reagentID)
        if self:VendorSellsReagent(reagentID) then
                GameTooltip:AppendText(GRAY_FONT_COLOR_CODE .. " (" .. L["buyable"] .. ")" .. FONT_COLOR_CODE_CLOSE)
        end
```

**Comment by plusmouse** [comment]
Upon review, I've made it so SetHyperlink is hooked again so you won't need to make any changes for Skillet to work in the latest alpha.

**Comment by teelolws** [comment]
> Upon review, I've made it so SetHyperlink is hooked again so you won't need to make any changes for Skillet to work in the latest alpha.

Oh, good. I can change Altoholic back to using SetHyperlink again. I noticed issues with it not showing all the item details when using SetItemByID.
