### ISSUE TITLE
Auctionator and Altoholic guild bank tooltips

### ISSUE THREAD

**Issue by addonaddict** [Auctionator/Auctionator#902]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

Tooltips within Altoholic addon do not show auctionator data such as auction house price for an item
![image](https://user-images.githubusercontent.com/73442541/98046657-9b53fe00-1df8-11eb-83e7-244fa0ff7cd8.png)

## Steps to Reproduce

Install auctionator and Altoholic-Retail (Teelo's Fork), open guild bank (or any other altoholic frame), then hover over any item. Auctionator does not work with altoholic tooltips.

## Loaded Addons

Altoholic-Retail (Teelo's Fork) + Auctionator

## Back Trace (LUA Error Output)

(Not a UI error)

Is this something that will be fixed/added?

Thank you

**Comment by teelolws** [comment]
I've changed Altoholic to use GameTooltip:SetItemByID instead of GameTooltip:SetHyperlink and submitted a PR to have Auctionator hook SetItemByID: https://github.com/Auctionator/Auctionator/pull/905
