### ISSUE TITLE
Make it easier to post the same stack several times

### ISSUE THREAD

**Issue by chbiel** [Auctionator/Auctionator#903]
**Is your feature request related to a problem? Please describe.**
Normally I want to post x stacks with a size of y of item z.
E.g. I have 100 items and I want to sell them in stacks of 10 but all after each other.

At the moment, everytime I click "Create auction", the selected items is deselected, the "Duration" selection is resetted and so on, so I have to click it again, maybe adjust the stacksize, click the durtion again, and post.
I for the above example I have to do it 10 times.

**Describe the solution you'd like**
I can imagine two possible solutions:

1. don't reset (or at least make it configurable) the form, when there are items of the selected item left. so that i could click 10 times on "Create auction" without having to click something else

2. I remember this feature from Auctioneer, that you can set those values in the selling UI, that means an extra text field for giving the number of stacks like this:

![image](https://user-images.githubusercontent.com/1297702/98290549-1d375900-1faa-11eb-8d2a-d35990cf4616.png)

I don't know what fits better in to the current concepts, but one option that makes that kind of tasks easier would be cool.

**Describe alternatives you've considered**
See above

**Additional context**

I actually tried to implement it and PR it (as seen in the image), but I need some help with the information flow within the plugin. So if someone would like to explain the code a little I look forward to help^^

**Comment by plusmouse** [comment]
The new AH makes selling in multiple stacks irrelevant. Even if you post 1 stack of 100, a player can buy just 5 items from the stack, and the AH leaves the remaining 95 on sale, for players to purchase chunks of.

**Comment by chbiel** [comment]
Oh I did not know that! (I am coming back after some years of a break), so never mind..i close it :)
