### ISSUE TITLE
Old version banned

### ISSUE THREAD

**Issue by Debuggernaut** [Auctionator/Auctionator#904]
This isn't really a bug, so feel free to close it immediately, just thought it was interesting and wanted to share

I currently have:
    ## Version: 8.3.1.5

and in my addon list, I'm seeing "Banned" next to Auctionator.  Looks like that's coming from this line of code:

https://github.com/StygianTheBest/AzerothCore-Content/blob/0c531ef9b1e1d42200a28c332d4af312056d26ca/WoWClient/RandomLoginScreen/Interface/GlueXML/AddonList.lua#L132

Very strange.  (the issue went away with a newer version of Auctionator)

**Comment by plusmouse** [comment]
Its a known issue, old versions of Auctionator could make 9.0.1 crash, so they were banned.
