### ISSUE TITLE
WoW crashes when I tab out of game during a scan

### ISSUE THREAD

**Issue by johnnydangerjt** [Auctionator/Auctionator#907]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

I have the latest version installed, and am in 9.0.2 ... Whenever I try scanning, on ANY character, it instantly DCs me if I tab out of WoW. If I stay in game, it works fine, but leaving the game to let it works crashes it

## Steps to Reproduce

For me, all I need to do is click the auction person, have it start the scan, tab out, and it instantly DCs me

## Loaded Addons

Auctionator, AutoRepair, BadBoy, Bagnon, Bagbrother, DBM, Dominos, HandyNotes, NeatPlates, Postal, Recount, Sexy Map, Shadow Unit Frames, TipTac. Those are the ones I have enabled right now

## Back Trace (LUA Error Output)
Here ya go. This showed up in game

1x Auctionator\Source\Config\Mixins\Shopping.lua:15: bad argument #1 to 'ipairs' (table expected, got nil)
[string "=[C]"]: in function ipairs' [string "@Auctionator\Source\Config\Mixins\Shopping.lua"]:15: in function <Auctionator\Source\Config\Mixins\Shopping.lua:12> [string "@Auctionator\Source\Config\Mixins\Shopping.lua"]:25: in function <Auctionator\Source\Config\Mixins\Shopping.lua:22> [string "=[C]"]: in function Show'
[string "@FrameXML\UIParent.lua"]:2910: in function SetUIPanel' [string "@FrameXML\UIParent.lua"]:2716: in function ShowUIPanel'
[string "@FrameXML\UIParent.lua"]:2623: in function <FrameXML\UIParent.lua:2619>
[string "=[C]"]: in function SetAttribute' [string "@FrameXML\UIParent.lua"]:3468: in function ShowUIPanel'
[string "@Oilvl\Oilvl-v8.3 BFA.lua"]:5912: in function `?'
[string "@Oilvl\Oilvl-v8.3 BFA.lua"]:6059: in function <Oilvl\Oilvl.lua:6058>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"
= defined =[C]:-1

**Comment by johnnydangerjt** [comment]
Here ya go. This showed up in game

1x Auctionator\Source\Config\Mixins\Shopping.lua:15: bad argument #1 to 'ipairs' (table expected, got nil)
[string "=[C]"]: in function `ipairs'
[string "@Auctionator\Source\Config\Mixins\Shopping.lua"]:15: in function <Auctionator\Source\Config\Mixins\Shopping.lua:12>
[string "@Auctionator\Source\Config\Mixins\Shopping.lua"]:25: in function <Auctionator\Source\Config\Mixins\Shopping.lua:22>
[string "=[C]"]: in function `Show'
[string "@FrameXML\UIParent.lua"]:2910: in function `SetUIPanel'
[string "@FrameXML\UIParent.lua"]:2716: in function `ShowUIPanel'
[string "@FrameXML\UIParent.lua"]:2623: in function <FrameXML\UIParent.lua:2619>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML\UIParent.lua"]:3468: in function `ShowUIPanel'
[string "@Oilvl\Oilvl-v8.3 BFA.lua"]:5912: in function `?'
[string "@Oilvl\Oilvl-v8.3 BFA.lua"]:6059: in function <Oilvl\Oilvl.lua:6058>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

**Comment by johnnydangerjt** [comment]
Want to add this a day later

Now, even when I stay in game, the game crashes out. It scan for about 90 seconds, freezes the entire games, then it crashes. On ALL my characters. I deleted the cache/WTF/interface folders (just to be "sure" it wasn't them), and reinstalled the addon, and it still does this

So I'll wait for you folks to figure it out. Just wanted to give you a heads up

**Comment by plusmouse** [comment]
1. I can verify that tabbing out causes a DC, when only Auctionator is enabled, don't have a fix for that at the moment
2. The Lua error is the result of another addon doing something (O Item Level), and is unrelated to the disconnect.

Are these disconnects new with the latest patch, or have they been happening back in 8.3?

**Comment by RainbowTea** [comment]
I can add that i am getting disconnected from the game when doing a scan, it stops at 60%, the game freezes then i am booted to the disconnect screen. No errors though.

**Comment by plusmouse** [comment]
Thanks for the feedback.

We don't have a fix for the disconnects, but are looking into it.

While waiting for a fix doing an "slow scan" by [Shift]+Clicking the scan button or flipping this setting to on:
![image](https://user-images.githubusercontent.com/60280559/100456527-6d40a180-30b8-11eb-99b4-6747f0769ca2.png)

will let you get updated prices - its not as a nice as a normal scan, but it doesn't have any disconnection issues at the time of writing.
