### ISSUE TITLE
Elvui support for button/interface skins

### ISSUE THREAD

**Issue by addonaddict** [Auctionator/Auctionator#910]
Is there any possibility of supporting Elvui?
Currently the tabs and AH interface itself is not being skinned when using Elvui
Not sure who would be responsible for this work so i will leave this inquiry on both addons

Thanks :)

![image](https://user-images.githubusercontent.com/73442541/100400852-d62b0980-3025-11eb-890d-8a7a15164548.png)

**Comment by plusmouse** [comment]
A pre-release version of ElvUI AddonSkins has a skin for Auctionator (https://git.tukui.org/Azilroka/AddOnSkins).

I don't know when it will be formally released though.
