### ISSUE TITLE
A list of suggested enhancements

### ISSUE THREAD

**Issue by MarshallBuhl** [Auctionator/Auctionator#911]
Thanks so much for the effort you've put into Auctionator.  After using it for a little while, I've noticed a few things that
could be better; auctions take up way too much of my time.  Here is my list of possible enhancements that would make
selling gear much more efficient:

*  ~~Gear ilevel should be displayed without having to hover over the icon. The standard AH lists it in the item name.~~
*  ~~Suggested price should be based on other auctions of the same ilevel.  Don't compare an ilevel 57 item to a 33 item if
      there are other higher ilevel items already for auction.~~  If the exact same ilevel isn't already for auction, consider the highest
      ilevel less than your item for a suggested price.
*  Suggested price should never be more than the vendor price times the vendor price multiplier even if other people are asking
      more. So many people ask thousands for items that vender for less than 1g.
*  Allow for a minimum profit based upon whatever is greater: a set amount of gold or a percentage of the vendor price.
       Never suggest an auction amount less than the vendor price.
*  Replace the total amount field with the total profit or display both.
*  ~~It would be really nice if Auctionator recorded all my auction prices so that it displayed how much I asked for it the last time. I generally drop the price until it sells or it's easier to just vendor it.~~ (now available in the latest alpha 433)

Thanks for listening!

**Comment by plusmouse** [comment]
Adding the gear level to the name is now done in the latest alpha:
![image](https://user-images.githubusercontent.com/60280559/100478288-9b3adb80-30e2-11eb-8efb-098a03a37989.png)

**Comment by plusmouse** [comment]
The second point has been done, there's a new option to toggle to get the wanted effect:
![image](https://user-images.githubusercontent.com/60280559/101401259-f9797280-38c9-11eb-9c07-4b39b1768209.png)

**Comment by plusmouse** [comment]
I'm going to close this issue, as the remaining suggestions are unlikely to be implemented.

> * Suggested price should never be more than the vendor price times the vendor price multiplier even if other people are asking
> more. So many people ask thousands for items that vender for less than 1g.
> * Allow for a minimum profit based upon whatever is greater: a set amount of gold or a percentage of the vendor price.
> * Never suggest an auction amount less than the vendor price.
> * Replace the total amount field with the total profit or display both.
