### ISSUE TITLE
Hiden item problem

### ISSUE THREAD

**Issue by Leucosia1978** [Auctionator/Auctionator#913]
is it possible to add some kind of feature that makes it easy to unhide a item

**Comment by plusmouse** [comment]
To restore all hidden items, right click any other item and then click "Restore All"
![image](https://user-images.githubusercontent.com/60280559/100494499-0c59ad80-313a-11eb-998c-6828618784bc.png)

Does that help?

**Comment by Leucosia1978** [comment]
ty Sent from Mail for Windows 10 From: plusmouseSent: Friday, November 27, 2020 10:25 PMTo: Auctionator/AuctionatorCc: Leucosia1978; AuthorSubject: Re: [Auctionator/Auctionator] Hiden item problem (#913) To restore all hidden items, right click any other item and then click "Restore All"Does that help?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by sauljaffe** [comment]
The problem with "Restore All" is that it unhides EVERY ITEM including items on ALL characters.
