### ISSUE TITLE
Disconnecting wow when full scan started

### ISSUE THREAD

**Issue by klepp0906** [Auctionator/Auctionator#914]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

Each time I open the AH and it begins its full scan i disconnect from wow.  When i reconnect its fine until the timeout on full scans expires and the issue begins anew. 

## Steps to Reproduce

Simply visit the AH (for 1:1 im using the engineer ah in oribos) and I do have "optimize network for speed" as well as "use ipv6" enabled if relevant.  (and advanced logging but i dont imagine that plays a part) 

## Loaded Addons

[list.txt](https://github.com/Auctionator/Auctionator/files/5610733/list.txt)

## Back Trace (LUA Error Output)

no lua errors

**Comment by plusmouse** [comment]
A solution now exists, its just being tested and then it will be put on curseforge ASAP

**Comment by plusmouse** [comment]
Sorry about this, we are working on a fix to be released as soon as possible.

**Comment by plusmouse** [comment]
Switching to the alternate scan mode will let you get a scan done. Not a fix, but it is a workaround:
![image](https://user-images.githubusercontent.com/60280559/100524522-c986ec80-31b0-11eb-9866-12b1344ca011.png)

**Comment by klepp0906** [comment]
got it, will switch to that mode for the time being.  thanks for getting on this so quickly, very appreciated! :)

**Comment by speedweaver** [comment]
Just wanted to point out that this happens to me also.

**Comment by plusmouse** [comment]
I've spent a lot of time on this issue, and written a lot of code to try and work around it. Unfortunately I haven't had much luck. There are 2 options users can use if they're on a busy server:

* Enable the "Use alternate slower scan mode by default" option found in the "Basic Options" section.
* If you use Collectionator (or want to keep using the default scan), try reducing the number for the "Full scan step size" option found in the "Advanced" section. Suggested alternate values are 150 and 50; the default is 250.

**Comment by speedweaver** [comment]
Ok thanks!

Sent from my iPhone

On Dec 3, 2020, at 10:09 AM, plusmouse <notifications@github.com> wrote:

﻿

I've spent a lot of time on this issue, and written a lot of code to try and work around it. Unfortunately I haven't had much luck. There are 2 options users can use if they're on a busy server:

  *   Enable the "Use alternate slower scan mode by default" option found in the "Basic Options" section.
  *   If you use Collectionator (or want to keep using the default scan), try reducing the number for the "Full scan step size" option found in the "Advanced" section. Suggested alternate values are 150 and 50; the default is 250.

**Comment by nunyabiznes** [comment]
ok, as I see after I created my initial issue track, that there is an existing one. Closing the one I opened  I can kind of accept, however your posted work around  (as a reason to close my ticket), is invalid. While it's no longer causing disconnect / crash - scan still fails to complete. everytime I log an AH toon on and open the AH interface, I get the text scan failed - imitate another in 15m.
again this is not specific to a server as I get the same message no matter which of my three AH toons I'm on.

**Comment by SanUI** [comment]
Note: My auctionator config also has an "Advanced" section where I can set the "Full scan step size". Turns out roughly 85 is good for me... not sure what influences that, but I know 100 does not work. Going to try to get it up further, but it's certainly acceptable this way, although the scan IS slower than before.

**Comment by speedweaver** [comment]
Just want to mention that the work around does work for me. It’s just slower

Sent from my iPhone

On Dec 4, 2020, at 3:48 PM, SanUI <notifications@github.com> wrote:

﻿

Note: My auctionator config also has an "Advanced" section where I can set the "Full scan step size". Turns out roughly 85 is good for me... not sure what influences that, but I know 100 does not work. Going to try to get it up further, but it's certainly acceptable this way, although the scan IS slower than before.

**Comment by plusmouse** [comment]
> 
> 
> ok, as I see after I created my initial issue track, that there is an existing one. Closing the one I opened I can kind of accept, however your posted work around (as a reason to close my ticket), is invalid. While it's no longer causing disconnect / crash - scan still fails to complete. everytime I log an AH toon on and open the AH interface, I get the text scan failed - imitate another in 15m.
> again this is not specific to a server as I get the same message no matter which of my three AH toons I'm on.
Have you tried the alternate scan mode - that doesn't have a 15 minute timer?

**Comment by nunyabiznes** [comment]
I did  the alternative scan....was slow, but worked. after the update today (and lowering step size) full scan completes with out issues.

**Comment by speedweaver** [comment]
Ty for the information.  This helps

Sent from my iPhone

On Dec 6, 2020, at 4:28 PM, nunyabiznes <notifications@github.com> wrote:

﻿

I did the alternative scan....was slow, but worked. after the update today (and lowering step size) full scan completes with out issues.
