### ISSUE TITLE
Enchanted Elethium Bar missing at selling tab.

### ISSUE THREAD

**Issue by Tarkumi** [Auctionator/Auctionator#915]
[Enchanted Elethium Bar](https://www.wowhead.com/item=172437/enchanted-elethium-bar) does not shows in the selling tab. All other tradeskill materials made with enchanting (Enchanted Heavy Callous Hide and Enchanted Lightless Silk) shows without problems.
There is no lua error.

**Comment by plusmouse** [comment]
Fixed in the latest release
