### ISSUE TITLE
Shopping List not finding anything

### ISSUE THREAD

**Issue by teyasio** [Auctionator/Auctionator#916]
I create an item for the shopping list.  But it never finds the item. If I search for it. It finds it.

Can reproduce everytime

**Comment by flow0284** [comment]
Screenshot and/or itemname please

**Comment by teyasio** [comment]
![image](https://user-images.githubusercontent.com/15948301/100944039-68228e80-34cc-11eb-8b3a-71432b083c69.png)

**Comment by plusmouse** [comment]
I've put a fix into the latest alpha (400)
