### ISSUE TITLE
Time till full scan not displayed correctly

### ISSUE THREAD

**Issue by bartuszekj** [Auctionator/Auctionator#917]
It looks like the number of minutes is not calculated correctly when the number of seconds is zero. See below what happens when I keep spamming "Full scan" when it's on cooldown:

![Screenshot](https://user-images.githubusercontent.com/4855870/100775850-6d4ae500-33c9-11eb-9421-d1e37dfae28e.png)

You can see that the number of minutes changes from "11" to "10" one second too early.

**Comment by plusmouse** [comment]
Fixed in the latest alpha (397)
