### ISSUE TITLE
Way to "Unhide" an item

### ISSUE THREAD

**Issue by sauljaffe** [Auctionator/Auctionator#921]
**Is your feature request related to a problem? Please describe.**
Recently, I discovered that some items in my inventory where not showing up in the Selling tab when open up the Auction page on one of my characters.  They were 3 pets and I've had put them up for auction in the past.  But, after Shadowlands dropped, they were no longer appearing in the inventory list to sell on the "Selling" page.  I can only think that they must have been hidden somehow although I don't remember hiding them.  It might be a bug.  But, in any case, this brings up the issue that there doesn't seem to be a way to "Unhide" an item once it's been hidden.

**Describe the solution you'd like**
I know there's a way to put the item up for auction via the selling tab from the inventory.  I think it's something like alt-click but I might have that wrong.  Anyway, I think there should be a key stroke to "Unhide" a previously hidden item because, well, mistakes happen, people's minds change, etc.  Or, maybe, the key click to put the item up for sale should also "Unhide" the item?

**Comment by plusmouse** [comment]
See https://github.com/Auctionator/Auctionator/issues/913#issuecomment-735042081
