### ISSUE TITLE
Show itemStackCount from GetItemInfo in item-tooltip

### ISSUE THREAD

**Issue by Ahfau77** [Auctionator/Auctionator#922]
You already display several item-infos in the item's tooltip like vendor-price or auction-price...

Can you please extend the item's tooltip by "itemStackCount" retrieved from GetItemInfo() which should show the max. stack-size an item can have ?

**Comment by plusmouse** [comment]
The current entries in the tooltips are prices relevant to using the auction house. I don't see how putting the stack size in would help using the auction house, especially as stack sizes are no longer relevant in sales?

**Comment by Ahfau77** [comment]
For me it would be pretty helpful when i buy 1000 pieces of anything to see if i need 5 (stack-size 200) or 50 (stack-size 20) bag-slots to receive it later...

**Comment by plusmouse** [comment]
Have you tried something like https://www.curseforge.com/wow/addons/stack-size ?

**Comment by Ahfau77** [comment]
thanks for the suggestion about "Max Stack Size"  - i tried it.
Unfortunately it is last updated on Apr 16, 2017 and it is so simple that it doesn't differs if the tooltip really belongs to an item,  f.e. if you visit a profession-trainer and hover over a recipe, it throws errors in my setup.

I had a quick look at your Source\Tooltips\Main.lua and thought it would be just a tiny snippet that you have to extend your code to display the stack-size additionally ?
