### ISSUE TITLE
Constant crashes on fullscan - 

### ISSUE THREAD

**Issue by nunyabiznes** [Auctionator/Auctionator#923]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug
crash/dc when trying to do a full scan - happens on all three AH toons, rexxar, scarlet, and proudmoore.

_Please include a brief description of the bug, including what you were doing, and when it occurred._

Happens if fresh log in, or have been playing a main - hit full scan on my AH toon, hangs at 10% for 5s then causes the game to crash. Have tried renaming cache/wtf folders to see if another addon is causing this. even with only auctionator running it happens.

## Steps to Reproduce

_Include the steps I would need to follow to reproduce the bug._

see above

## Loaded Addons

Auctionator, altoholic, atlasloot, buggrabber/sack, rare scan, details dbm, (healbot - but AH toons dont load that one).
 - happens even with fresh cache/wtf folder

_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._
none showing as game crashes to log in screen. on logging back in there is nothing recorded from previous session
not showing

**Comment by plusmouse** [comment]
See https://github.com/Auctionator/Auctionator/issues/914#issuecomment-735281075
