### ISSUE TITLE
Selling legendary base items of different rank

### ISSUE THREAD

**Issue by SanUI** [Auctionator/Auctionator#924]
**Is your feature request related to a problem? Please describe.**
 When selling a legendary base item (e.g. https://www.wowhead.com/item=172327/boneshatter-pauldrons) of rank 2, auctionator tries to undercut  even those of rank 1, which makes it much too cheap, and I need to manually interfere. As far as I can tell, the "Undercut Scan" does already take rank into account (i.e. it only considers the rank 2 item to be undercut when there's a cheaper item of rank 2 and ignores those of rank 1 for it). I suspect the same happens for rank 3 and 4, but I have not tested.

**Describe the solution you'd like**
Auctionator should consider items of different itemlevel different, even if the names are the same (or internal IDs or whatnot). As far as I can tell, there's nothing else that distinguishes crafted legendary items of different ranks. The main idea would be to be able to simply put up such an item for auction, have auctionator figure out the price due to the settings and then just click "post" and not have a too low price (just as I do with every other item as well).

**Describe alternatives you've considered**
Maybe I could worm through tradeskillmaster to find if it can do that. I could also always manually interfere, which somewhat goes against the purpose of using auctionator.

**Additional context**
I did ask in gitter if there are other workarounds, but none was forthcoming.

Thanks for considering :) And thanks for the awesome auctionator!

**Comment by plusmouse** [comment]
Thanks for the feedback.

We can add an option that will have the undercut scan version of undercutting apply to the Selling tab. It would hide other bits of gear that are of different ilvls from the view though (although with extra effort we could keep the other ilvls on display). Is that what you're after?

Trying to pick a default method that "just works" is hard with gear, we've had few different suggestions.

**Comment by SanUI** [comment]
> It would hide other bits of gear that are of different ilvls from the view though (although with extra effort we could keep the other ilvls on display).

It would hide it from the item view in the selling tab? That's certainly fine.

> Edit: Most of the issues stem from the fact that for tmog the ilvl doesn't affect the sale value, while for current xpac gear the ilvl matters a lot.

Ah yeah. Maybe a config option that lets one enable this for certain classes of gear? Or just enable this for a whitelisted set, where you just put in all the legendary crafted base gear? Or err on the side of "too expensive" and show some sort of warning? Bring up a popup where the user _must_ make a choice? Just some brainstorming :)

**Comment by plusmouse** [comment]
A config option to enable it is the option I'd prefer - that way nobody will be surprised by the behaviour changing.
