### ISSUE TITLE
Disconnected when opening the auction house from the NPC

### ISSUE THREAD

**Issue by JotaJotaMz** [Auctionator/Auctionator#925]
Please include as much of the following information as possible to help me fix the bug:

## Cuando le hablo al NPC de la subasta el autioner trata de hacer el escaneo pero no puede y me cierra el juego.

_Please include a brief description of the bug, including what you were doing, and when it occurred._

## Steps to Reproduce

_Include the steps I would need to follow to reproduce the bug._

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by plusmouse** [comment]
Please turn this option on:
![image](https://user-images.githubusercontent.com/60280559/101261780-9d7be600-3731-11eb-9451-3f0430398deb.png)
