### ISSUE TITLE
Pause AH scanning when pressing modifier key right before interacting with AH NPC

### ISSUE THREAD

**Issue by addonaddict** [Auctionator/Auctionator#929]
**Is your feature request related to a problem? Please describe.**
Not a problem really, more of a QoL annoyance
AllTheThings AH module scans the AH similar like Auctionator does to give you a list of items on AH that you didnt collect yet
Problem is if you have AH auto scan enabled in auctionator, that will be done first. After scanning you have to wait 15m, that means youre locked out of scanning AH for ATT addon for 15m
This is fixable if you simply disable auto scanning but that would be very annoying to do all the time

**Describe the solution you'd like**
Implement a modifier key that will allow u to not scan AH automatically so other addons have a chance to do it instead

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by plusmouse** [comment]
We recently changed the scanning method to one that doesn't involve the 15 minute timeout - making turning off the autoscan to make ATT work unnecessary. Do you still need the shift down no scan?

**Comment by addonaddict** [comment]
oh i was unaware of that - will test it out!
if that is the case and it will not interfere with ATT scanning then that is all i care about :)
thank you!!
