### ISSUE TITLE
Price history - Not requiring to have the item

### ISSUE THREAD

**Issue by skules** [Auctionator/Auctionator#930]
**Is your feature request related to a problem? Please describe.**
You can't see the price history of an item in the sell tab unless you have the item in your bags. Why?

**Describe the solution you'd like**
Should be able to see item history of an item even when it isn't in your bags. For example if you've added it to the favorites selection.

**Describe alternatives you've considered**
Always having said item in inventory, which isn't exactly a great alternative if I end up selling them all.

**Comment by MyDevil94** [comment]
I don't know if it is possible.. but a "Historic Price" frame when you are in the "Buy Tab" (Red square) or a second window with the "History from selected item" (Green square) could help.
![Auction](https://user-images.githubusercontent.com/75698657/101537569-04043c80-399c-11eb-8a37-7ccbb5978827.jpg)

Then you can browse the auction house and you see if the price is high or low.

**Comment by plusmouse** [comment]
Available in alpha 448, right-click any result in the "Shopping" tab to view a price history
![image](https://user-images.githubusercontent.com/60280559/103127677-98ec8280-468a-11eb-9d90-f1ed51ffe230.png)
