### ISSUE TITLE
Auctionator\Source\Database\Main.lua:112: bad argument #1 to 'pairs' (table expected, got nil)

### ISSUE THREAD

**Issue by MajorXRA** [Auctionator/Auctionator#931]
Message: ...nterface\AddOns\Auctionator\Source\Database\Main.lua:112: bad argument #1 to 'pairs' (table expected, got nil)
Time: Tue Dec  8 00:20:04 2020
Count: 1
Stack: ...nterface\AddOns\Auctionator\Source\Database\Main.lua:112: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: in function `pairs'
[string "@Interface\AddOns\Auctionator\Source\Database\Main.lua"]:112: in function `Prune'
[string "@Interface\AddOns\Auctionator\Source\Variables\Main.lua"]:95: in function `InitializeDatabase'
[string "@Interface\AddOns\Auctionator\Source\Variables\Main.lua"]:10: in function `Initialize'
[string "@Interface\AddOns\Auctionator\Source\Events\VariablesLoaded.lua"]:4: in function `VariablesLoaded'
[string "@Interface\AddOns\Auctionator\Source\Events\Handler.lua"]:8: in function `Handler'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

Locals: (*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

**Comment by plusmouse** [comment]
Can you upload your Auctionator.lua file?

[WoW Directory]\_retail_\WTF\Account\[Some numbers]\SavedVariables and it's the Auctionator.lua file, paste the file into the text box.

**Comment by plusmouse** [comment]
And is this the first time you've used Auctionator, or have you been using it for a while? And what version of Auctionator are you on?

**Comment by MajorXRA** [comment]
1.few months ago(8.3) nothing wrong, but this time (reinstall the game for 9.0) something wrong.
2.I have tried 9.0.1.1-9.0.0 ,all the same error.
delete all the other interface still unchanged.

[Auctionator.zip](https://github.com/Auctionator/Auctionator/files/5653936/Auctionator.zip)

**Comment by plusmouse** [comment]
I'm sorry about that.

You attached the wrong file, I need the one at `[WoW Directory]_retail_\WTF\Account[Some numbers]\SavedVariables` and it's the `Auctionator.lua` file.

**Comment by plusmouse** [comment]
Deleting that file should resolve the problem, however I'd still like to see it so I can make sure this problem doesn't happen again.

**Comment by MajorXRA** [comment]
hope that'll be helpful :)

[Auctionator.zip](https://github.com/Auctionator/Auctionator/files/5654001/Auctionator.zip)

**Comment by plusmouse** [comment]
Had a look. It looks like you used a newer version of Auctionator and then swapped back to a really old one (back in February or March), and that caused the database to get corrupted. Deleting the file will get you working again, and I'll put a fix in Auctionator to make sure this doesn't happen again 😃

**Comment by MajorXRA** [comment]
The problem is solved, Thanks.

**Comment by plusmouse** [comment]
That's great. I'll close the issue now.
