### ISSUE TITLE
"Cancelling" tab does not retain sort order upon cancelling an auction

### ISSUE THREAD

**Issue by digitalnexus** [Auctionator/Auctionator#932]
Attempting to cancel an auction, while having selected a specific column order sorting, seems to revert that column order to default sorting.

- Let's say I want to clear out all "1 hour remaining" auctions to repost them.
- The easiest way to do this is to Sort By "Time Left" in the Cancelling tab, which now shows my soon-to-end auctions on top.
- Left clicking on an auction it is properly cancelled, as expected, but the column order is not retained - so I have to re-sort by Time Left, and proceed to click on the next auction.

**Comment by plusmouse** [comment]
Find a fix in alpha 425
