### ISSUE TITLE
Unit Price history - Incorrect pricing saved ?

### ISSUE THREAD

**Issue by skules** [Auctionator/Auctionator#933]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

The pricing history in the selling tab seems to record incorrectly or saves the wrong value? Doesn't seem to update if you re-scan?

Think this occurs when people are trying to scam/setup snipe prices and the scan occurs? 

Would be good to be able to modify or if it re-scans then it updates the price.

![image](https://user-images.githubusercontent.com/8022147/101474557-3f265180-3943-11eb-9545-013b57fdd90e.png)

![image](https://user-images.githubusercontent.com/8022147/101474587-4baaaa00-3943-11eb-8b60-e512a9a2a9be.png)

**Comment by plusmouse** [comment]
The scan saves the lowest price on a given day. We can show another column which shows the highest low price we saw?

So if a scan sees 5 as the lowest once, 10 as the lowest another time, the "highest low price" column would show 10, and the normal column would show 5.

Would that work for you?

**Comment by skules** [comment]
Yeah, that would be good. 

 or taking the 2nd to 5th lowest value instead of the lowest value. So in the example screenshot if it was the 5th lowest, instead of 154.85g it'd be 154.99g

**Comment by plusmouse** [comment]
Choosing which value to pick is very subjective. This is what I had in mind:
![image](https://user-images.githubusercontent.com/60280559/101531379-145feb80-398b-11eb-98c0-73459878de9b.png)

**Comment by skules** [comment]
That sounds great.

**Comment by plusmouse** [comment]
Find it in the latest alpha (423), right-click the "Unit Price" header to find the "Upper Unit Price column to enable:
![image](https://user-images.githubusercontent.com/60280559/101590820-0dfd5e00-39e3-11eb-8750-927f37a65356.png)
