### ISSUE TITLE
Endless "Fetching item info...." loop in the Scanning tab

### ISSUE THREAD

**Issue by Tiiara** [Auctionator/Auctionator#934]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

Scanning endlessly for current prices when opening the Selling Tab

## Steps to Reproduce

Open Auction House, go to Selling Tab, select any item.

## Loaded Addons

a lot, but none AH related

## Back Trace (LUA Error Output)

`Message: ...ionator\Source\Tabs\DataProviders\SearchProvider.lua:145: attempt to call field 'RoundTime' (a nil value)
Time: Tue Dec  8 13:43:10 2020
Count: 3
Stack: ...ionator\Source\Tabs\DataProviders\SearchProvider.lua:145: attempt to call field 'RoundTime' (a nil value)
[string "@Interface\AddOns\Auctionator\Source\Tabs\DataProviders\SearchProvider.lua"]:145: in function `ProcessCommodityResults'
[string "@Interface\AddOns\Auctionator\Source\Tabs\DataProviders\SearchProvider.lua"]:117: in function <...ionator\Source\Tabs\DataProviders\SearchProvider.lua:114>

Locals: self = <unnamed> {
 0 = <userdata>
 GetEntryAt = <function> defined @Interface\AddOns\Auctionator\Source\Tabs\DataProviders\DataProvider.lua:74
 Sort = <function> defined @Interface\AddOns\Auctionator\Source\Tabs\DataProviders\SearchProvider.lua:104
 onPreserveScroll = <function> defined @Interface\AddOns\Auctionator\Source\Tabs\ResultsListing\Mixins\ResultsListing.lua:63
 searchCompleted = false
 OnUpdate = <function> defined @Interface\AddOns\Auctionator\Source\Tabs\DataProviders\DataProvider.lua:21
 OnShow = <function> defined @Interface\AddOns\Auctionator\Source\Tabs\DataProviders\SearchProvider.lua:60
 insertedKeys = <table> {
 }
 GetColumnHideStates = <function> defined @Interface\AddOns\Auctionator\Source\Tabs\DataProviders\SearchProvider.lua:87
 SetOnEntryProcessedCallback = <function> defined @Interface\AddOns\Auctionator\Source\Tabs\DataProviders\DataProvider.lua:84
 onSearchEnded = <function> defined @Interface\AddOns\Auctionator\Source\Tabs\ResultsListing\Mixins\ResultsListing.lua:57
 results = <table> {
 }
 onSearchStarted = <function> defined @Interface\AddOns\Auctionator\Source\Tabs\ResultsListing\Mixins\ResultsListing.lua:50
 entriesToProcess = <table> {
 }
 ProcessCommodityResults = <function> defined @Interface\AddOns\Auctionator\Source\Tabs\DataProviders\SearchProvider.lua:133
 ProcessItemResults = <function> defined @Interface\AddOns\Auctionator\Source\Tabs\DataProviders\SearchProvider.lua:199
 announcedCompletion = true
 ReceiveEvent = <function> defined @Interface\AddOns\Auctionator\Source\Tabs\DataProviders\SearchProvider.lua:76
 onUpdate = <function> defined @Interface\AddOns\Auctionator\Source\Tabs\ResultsListing\Mixins\ResultsListing.lua:46
 onEntryProcessed = <function> defined @Interface\AddOns\Auctionator\Source\Tabs\DataProviders\DataProvider.lua:14
 processCountPerUpdate = 10
 GetRowTemplate = <function> defined @Interface\AddOns\Auctionator\Source\Tabs\DataProviders\SearchProvider.lua:249
 OnLoad = <function> defined @Interface\AddOns\Auctionator\Source\Tabs\DataProviders\DataProvider.lua:5
 OnHide = <function> defined @Interface\AddOns\Auctionator\Source\Tabs\DataProviders\SearchProvider.lua:69
 CheckForEntriesToProcess = <function> defined @Interface\AddOns\Auctionator\Source\Tabs\DataProviders\DataProvider.lua:117
 GetCount = <function> defined @Interface\AddOns\Auctionator\Source\Tabs\DataProviders\DataProvider.lua:80
 UniqueKey = <function> defined @Interface\AddOns\Auctionator\Source\Tabs\DataProviders\SearchProvider.lua:100
 SetOnUpdateCallback = <function> defined @Interface\AddOns\Auctionator\Source\Tabs\DataProviders\DataProvider.lua:88
 OnEvent = <function> defined @Interface\AddOns\Auctionator\Source\Tabs\DataProviders\SearchProvider.lua:114
 GetTableLayout = <function> defined @Interface\AddOns\Auctionator\Source\Tabs\DataProviders\SearchProvider.lua:83
 SetOnPreserveScrollCallback = <function> defined @Interface\AddOns\Auctionator\Source\Tabs\DataProviders\DataProvider.lua:100
 SetOnSearchEndedCallback = <function> defined @Interface\AddOns\Auctionator\Source\Tabs\DataProviders\DataProvider.lua:96
 AppendEntries = <function> defined @Interface\AddOns\Auctionator\Source\Tabs\DataProviders\DataProvider.lua:104
 SetOnSearchStartedCallback = <function> defined @Interface\AddOns\Auctionator\Source\Tabs\DataProviders\DataProvider.lua:92
 Reset = <function> defined @Interface\AddOns\Auctionator\Source\Tabs\DataProviders\Da
`

**Comment by plusmouse** [comment]
I've just uploaded alpha 421 to curseforge - it includes a fix for this bug.
