### ISSUE TITLE
Auctionator constantly scanning AH

### ISSUE THREAD

**Issue by addonaddict** [Auctionator/Auctionator#936]
With the recent change to AH scanning, if you enable option to auto-scan AH when opening it it will scan it as usual, except now the user is pretty much forced to not have the auto-scan option enabled
If you enable it like I do - each single time I open AH it auto scans it for me, not allowing me to put up any items through selling tab

Is there any possibility to add a 10 minute or so throttle to scanning after a 100% successful scan was completed?
I and probably many others tend to open AH multiple times when putting things up on AH while running between mailbox, bank, or just crafting things and this really slows it down to the point of where i have to turn the option off

thanks

**Comment by plusmouse** [comment]
Find the fix in the latest alpha (423)
