### ISSUE TITLE
Price history showing 0silver entry for some items.

### ISSUE THREAD

**Issue by lunamoonraker** [Auctionator/Auctionator#938]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

Updated Auctionator 1-2 days ago and after running Full Scan or automated scan on opening, Any item in my inventory not already listed when using Selling is showing a 0s price at the top with previous normal prices in the history below.

Running subsequent scans after cancelling show additional item count but still 0s.

If 0s entry clicked it is added as sell price, as 0s (not tried actually listing). I had to be v careful when relisting high value items as it auto enters 0s value though Post was greyed until unit price selected.

![Screenshot 2020-12-09 185240](https://user-images.githubusercontent.com/20485957/101668498-e7760c00-3a50-11eb-8f25-bd7fb57726c0.jpg)
![Screenshot 2020-12-09 184507](https://user-images.githubusercontent.com/20485957/101668506-e9d86600-3a50-11eb-92ec-c2d85e10863d.jpg)
![Screenshot 2020-12-09 183823](https://user-images.githubusercontent.com/20485957/101668518-eba22980-3a50-11eb-9735-83ea816f6e50.jpg)

## Steps to Reproduce

Tried Cancelling item, rerunning scan (both auto scan at open AH and manual) then Selling with same result. Updated to latest version (9.0.1.2) just now and the same result. Closed game and restarted, the same. Disabled all other addons, the same. Appears to add item listed count in history window in Selling after cancel and retry also. See screenshots.

Displays 0s even when previous price added and posted, then cancelled and resell. Just to confirm, no items were actually listed to AH at 0s value only at previously used values.

Repeatable each time.

## Loaded Addons
Same with all other addons disabled, only Auctionator running.

## Back Trace (LUA Error Output)

No error in Bugsack with Buggrabber running.

**Comment by plusmouse** [comment]
Can you attach your Auctionator.lua file `[WoW Directory]_retail_\WTF\Account[Some numbers]\SavedVariables` and it's the `Auctionator.lua` file.

I haven't been able to replicate the bug, but hopefully this file will tell me more.

**Comment by plusmouse** [comment]
I've had a look at the code, something went wrong in one scan, which has left a 0 as the price for today. I'm unsure what caused the scan to fail. If another addon interfered it would have happened then (so disabling them would have made so difference).

I think the new price is updating correctly - the price shown is the least price it saw today, so a higher price won't bump it up.

**Comment by lunamoonraker** [comment]
Thanks for looking into this. Here is the .lua as requested

[Auc-Advanced.zip](https://github.com/Auctionator/Auctionator/files/5668435/Auc-Advanced.zip)

**Comment by lunamoonraker** [comment]
Thanks for looking into this. here is the .lua as requested.

Is there a quick way to copy/ paste a list of addons? otherwise Ill need to type them all. I do not use another auction addon fyi.
[Auctionator.zip](https://github.com/Auctionator/Auctionator/files/5668456/Auctionator.zip)

**Comment by plusmouse** [comment]
From your file I can establish that 0 prices started showing at least 17 days ago.

Comparing it to my own file it seems there are 0 prices in there too (though not as far back as I reset my database a lot) - so its likely not an add-on. I've setup my Auctionator build to alert me if a 0 price shows up again.

Having the prices and availability persist is by design - it keeps the lowest price for the day and the greatest quantity.

**Comment by plusmouse** [comment]
I'm glad that the code that blocked posting with a 0 price was effective, even though the 0 shouldn't have appeared in the first place.

What version were you on _before_ you updated?

**Comment by plusmouse** [comment]
**Update:** Found a way to replicate the bug. Progress 😄

**Comment by plusmouse** [comment]
I've found a fix for it. It should go out in the next release (currently in alpha 430).

**Comment by lunamoonraker** [comment]
Thanks a lot for your prompt attention and fix. Appreciated as with all the work done on the addon.
