### ISSUE TITLE
Available amounts

### ISSUE THREAD

**Issue by RadsWa** [Auctionator/Auctionator#939]
Since the last update 9.0.1.3, on the selling tab Auctionator has stopped showing the amounts sellers have listed (item amounts), I just now noticed this includes your own auctions.
![image](https://user-images.githubusercontent.com/73009320/101852305-4db97680-3b98-11eb-9dc0-d2be5d83aaef.png)

**Comment by plusmouse** [comment]
A fix is in 9.0.1.4
