### ISSUE TITLE
Pet/Gear sale

### ISSUE THREAD

**Issue by Gonnno** [Auctionator/Auctionator#940]
Hello,

Is the last price of my auction scheduled to be recorded?

Let me explain, currently the last price of an item is recorded per day, but it is the lowest price and not my sale.
Some items like pets and gear sell in more than 48 hours and knowing what price I put them on before will make it easier to put them back on sale in AH.

Thank you for your reply.

**Comment by plusmouse** [comment]
The price of your last auction is recorded in the latest alpha https://github.com/Auctionator/Auctionator/releases/tag/436-alpha - and will be put into a normal release in the next week or so.
