### ISSUE TITLE
Create multiple auctions of a single stack

### ISSUE THREAD

**Issue by narcolepticsnowman** [Auctionator/Auctionator#941]
**Is your feature request related to a problem? Please describe.**
Auctioneer (which currently does not function) has a feature to create multiple auctions of any stack size. I.e., 5 auctions of 2 stacks each etc. This feature is a huge time saver when you have a bunch of things that only sell as a stack of 1.

**Describe the solution you'd like**
I would like to be able to specify a stack size and the total amount I want to post per auction instead of only quantity.

**Describe alternatives you've considered**
I tried to use auctioneer, but it's broken. I tried using Tradeskillmaster and auction faster, but neither have this feature.

**Additional context**
This is a really handy way to sell for enchanters and the like, because people typically only want 1 of an enchanting scroll at a time versus a stack of them.

**Comment by plusmouse** [comment]
The new AH makes selling in multiple stacks irrelevant. Even if you post 1 stack of 100, a player can buy just 5 items from the stack, and the AH leaves the remaining 95 on sale, for players to purchase chunks of.

You can set the default amount to sell in the settings.

**Comment by narcolepticsnowman** [comment]
😮 coooooool! Thanks for teaching me, this addon is legit!
