### ISSUE TITLE
Feature Request: In Selling tab, add option to make favorite items always visible

### ISSUE THREAD

**Issue by DenL** [Auctionator/Auctionator#942]
**Is your feature request related to a problem? Please describe.**
When watching certain items you are selling (e.g. for undercuts), it's quite troublesome to have to set up a shopping list and and look at current posted that way, or that having to keep one copy of the item in bag so you can easily click it to search.

**Describe the solution you'd like**
If all the favorited items are always visible regardless of whether the item is in the bag or not, it would be a lot easier to search for the item and look at current posted auctions

**Describe alternatives you've considered**
Setting up shopping list for the favorited items. But the shopping list search result does not clearly say whether your item is the lowest posted or not so you have to click into it and back out to click another and rinse and repeat.

**Additional context**
It would be even better if cancelling can be done right in the selling tab.

**Comment by plusmouse** [comment]
You can set up your shopping lists to show if yours is top or not, just enable the "Top?" column in the "Shopping" tab:
![image](https://user-images.githubusercontent.com/60280559/102159195-f9a1e100-3e7a-11eb-9f86-8f30201d6607.png)


In the "Selling" tab you can right-click your listings to cancel them:
![image](https://user-images.githubusercontent.com/60280559/102159333-3d94e600-3e7b-11eb-8005-3f60a4a93027.png)


Does that help?

**Comment by DenL** [comment]
Yes this is what I'm looking for, thanks! Didn't know about this feature.

"Top?" doesn't seem to be working tho:
![image](https://user-images.githubusercontent.com/5632219/102159781-31486300-3e52-11eb-8b79-ef11137ddab7.png)
And when clicking into the third one:
![image](https://user-images.githubusercontent.com/5632219/102159811-41f8d900-3e52-11eb-8b94-30697d5830cd.png)

**Comment by DenL** [comment]
Just another thought, while cancelling in selling tab and "Top?" in shopping list is great, problem remains when you want to check your auctions without the item in bag. Once you see the shopping list that you are not top, you'd have to locate your auction in cancel tab and manually cancel them.

Is it possible to: 1) add right click cancel in shopping tab, or 2) allow quick search similar to shopping tab for selling tab?
So that you can easily cancel undercut auctions.

A lot of times you just want to cancel that few items instead of doing a whole cancel scan.

**Comment by plusmouse** [comment]
We get the "Top?" value from the default AH (its the green tick there), so its unlikely we can fix it for gear in the Shopping tab
![image](https://user-images.githubusercontent.com/60280559/102161499-5ef7d100-3e7f-11eb-9e2a-ba2ef39a17ec.png)

1. Right-click cancel in the shopping tab; possible, but would take an extra click to view the item listings before being able to cancel.
2. A quick search in the selling tab; this is probably the better idea.

**Comment by plusmouse** [comment]
I didn't mean the close the issue, sorry for any confusion.

**Comment by DenL** [comment]
Thank you. I thought the green tick in default UI just means you have something for sale in there. It had never worked as indicating that your item is the top. Or maybe I wasn't selling the stuff that it's intended for.

**Comment by plusmouse** [comment]
Added this feature in alpha 444.
![image](https://user-images.githubusercontent.com/60280559/102759874-a04f1b80-436c-11eb-9b23-1f2e87d4e18d.png)
