### ISSUE TITLE
bad argument #1 to 'LockItem'

### ISSUE THREAD

**Issue by Quartzfire** [Auctionator/Auctionator#943]
Please include as much of the following information as possible to help me fix the bug:

When I sell items, the last item I sell doesn't disappear from the area on the right that shows the icons for the items. When I then click on the icon, that is when I get the LUA.

_Please include a brief description of the bug, including what you were doing, and when it occurred._

Sell some items.
Last item icon doesn't disappear from the panel.
Click on the item.
Experience LUA error.

Hope this link to imgur works [here](https://imgur.com/a/cntq2Cs)

## Loaded Addons

Is there a way to somehow generate this?

## Back Trace (LUA Error Output)

3x ...\Auctionator\Source\Tabs\Selling\Mixins\SaleItem.lua:64: bad argument #1 to 'LockItem' (Usage: C_Item.LockItem(itemLocation))
[string "=[C]"]: in function `LockItem'
[string "@Auctionator\Source\Tabs\Selling\Mixins\SaleItem.lua"]:64: in function `LockItem'
[string "@Auctionator\Source\Tabs\Selling\Mixins\SaleItem.lua"]:127: in function `ReceiveEvent'
[string "@Auctionator\Source\Utilities\EventBusMixin.lua"]:86: in function `Fire'
[string "@Auctionator\Source\Tabs\Selling\Mixins\BagItem.lua"]:47: in function <...s\Auctionator\Source\Tabs\Selling\Mixins\BagItem.lua:41>

Locals:
(*temporary) = <table> {
 Clear = <function> defined @FrameXML\ObjectAPI\ItemLocation.lua:21
 IsEquipmentSlot = <function> defined @FrameXML\ObjectAPI\ItemLocation.lua:48
 IsEqualToBagAndSlot = <function> defined @FrameXML\ObjectAPI\ItemLocation.lua:64
 SetBagAndSlot = <function> defined @FrameXML\ObjectAPI\ItemLocation.lua:27
 IsBagAndSlot = <function> defined @FrameXML\ObjectAPI\ItemLocation.lua:52
 SetEquipmentSlot = <function> defined @FrameXML\ObjectAPI\ItemLocation.lua:38
 slotIndex = 11
 HasAnyLocation = <function> defined @FrameXML\ObjectAPI\ItemLocation.lua:56
 bagID = 0
 GetEquipmentSlot = <function> defined @FrameXML\ObjectAPI\ItemLocation.lua:44
 IsEqualToEquipmentSlot = <function> defined @FrameXML\ObjectAPI\ItemLocation.lua:72
 GetBagAndSlot = <function> defined @FrameXML\ObjectAPI\ItemLocation.lua:34
 IsValid = <function> defined @FrameXML\ObjectAPI\ItemLocation.lua:60
 IsEqualTo = <function> defined @FrameXML\ObjectAPI\ItemLocation.lua:80
}

**Comment by plusmouse** [comment]
Just tried posting the last item in my bag, it disappears correctly. What version of Auctionator are you on? And can I get a screenshot of your "Selling" settings?
![image](https://user-images.githubusercontent.com/60280559/102262314-d32b8680-3f0a-11eb-92a0-bac40fb9ed56.png)

**Comment by Quartzfire** [comment]
Hi PlusMouse,

Wow, thanks for the super quick response.

Screenshot of "selling" tab should be attached.

I'm using "Auctionator-9.0.2.zip".

![Screenshot 2020-12-15 204143](https://user-images.githubusercontent.com/76067897/102270520-ff98d000-3f15-11eb-94e3-b87e501a3188.png)

I do have a *lot* of addons, could well be a conflict somewhere. In terms of things that interact with the AH, I have TSM and also have Collectionator - I can try disable everything other than Auctionator if that may help?

Regards,
Quartz

**Comment by Quartzfire** [comment]
Hi PlusMouse,

Quick update - I have disabled almost all addons.

I have Auctionator and Bugtracker & Bugsack loaded.

Problem still occurs (also happened without bugtracker & bugsack loaded, but I got no lua).

Updated screenshot attached.

As you can see - the selling post does happen, so I no longer actually have the item, I assume perhaps that is why the lua is generated when I click on it's icon on the left?

Please do let me know if there's anything else I can test / trace / screenshot / log etc.

Regards,
Quartz
![auctionator](https://user-images.githubusercontent.com/76067897/102272583-e2b1cc00-3f18-11eb-9743-bd70d133d578.png)

**Comment by plusmouse** [comment]
A fix will go out in the with the next release. Find it in an alpha build (442) in the interim.
