### ISSUE TITLE
İtems price bug

### ISSUE THREAD

**Issue by byacaba** [Auctionator/Auctionator#944]
hi,
Ardent Sunstar Signet, items have the same name but different prices. it causes a big mistake!

ty

![resim](https://user-images.githubusercontent.com/76185859/102549759-b8553f80-40cd-11eb-9624-39ce40de9d09.png)

![resim](https://user-images.githubusercontent.com/76185859/102551483-9c9f6880-40d0-11eb-95a5-da7aa58a93e2.png)

![resim](https://user-images.githubusercontent.com/76185859/102551509-a9bc5780-40d0-11eb-9d0e-650804ea1037.png)

_____________________________________________________________________

and another items problem

![resim](https://user-images.githubusercontent.com/76185859/102554578-27369680-40d6-11eb-8a04-1554ba606a44.png)

**Comment by plusmouse** [comment]
The item level is shown just to the right of the item name. This is an issue with the default Blizzard UI, not Auctionator, so closing this issue.
