### ISSUE TITLE
Add a keybind for "cancel undercut" button similar to TSM

### ISSUE THREAD

**Issue by addonaddict** [Auctionator/Auctionator#945]
**Is your feature request related to a problem? Please describe.**
TSM allows user to select a key to use to quickly cancel undercut auctions
With recent changes, cancelling hundreds of auctions is a chore, being able to bind the button to a scroll wheel would make the task much easier on (mine at least) fingers :D

to expand on this, you could also add a key for "post" button in selling tab, so you can just click an item and instantly scroll down to post

Thank you

**Comment by plusmouse** [comment]
We already have macros for this.

### Selling Post Button Macro
`/auctionator post`
### Undercut scan cancel button macro
`/auctionator cancelundercut`

**Comment by addonaddict** [comment]
For a macro you need to have it placed on the action bars. This is a lazy work-around that TSM handles differently. Instead of having to put a macro on each and every toon that I do auction house with, wouldnt it make more sense to be a addon-assigned hotkey that is enabled when in these specific windows? This is how TSM does it and it works great...
