### ISSUE TITLE
Atrvalue now only updates on full scan

### ISSUE THREAD

**Issue by snaily1111** [Auctionator/Auctionator#948]
Hello there, 
I am using tsm + auctinator for figuring out a crafting cost of items, I configured tsm to use atrvalue(price from auctinator scan), and it use to update prices in tsm's crafting window after every auctinator's shopping list scan, and it looks like some of your latest changes broke something, at first it was completely broken, now after auctinator update full scan updates prices, but shopping list scan does not.

**Comment by plusmouse** [comment]
Can you try this version:
[ModifiedEvents.zip](https://github.com/Auctionator/Auctionator/files/5725319/ModifiedEvents.zip)

**Comment by snaily1111** [comment]
Yep, it works fine now.
p.s. just in case its unrelated bug, although its probably some technical details of the build - localization was not working for me

**Comment by plusmouse** [comment]
I'll push a full release shortly which will have the fixed localisation.
