### ISSUE TITLE
Export auction scan data to excel

### ISSUE THREAD

**Issue by addonaddict** [Auctionator/Auctionator#949]
**Is your feature request related to a problem? Please describe.**
I would like to have the ability to export the data from auction house scan to excel spreadsheet
TSM has a handy option where you can open the profession window and it will instantly tell you what to craft to get profit, and what is not profitable
I would like to do this without having TSM installed (i hate everything else about it) by exporting the data to a premade excel sheet that reads the auctionator scan

**Describe the solution you'd like**
The data extracted would be something simple like:
Item_full_name           |          lowest_price_listed       |             any extra information that would be useful to have               

I understand if this is not something you'd be interested in but im sure some folks would enjoy this seeing as you're starting to implement other extract to excel  tools like with shopping list

Thank you :)

**Comment by plusmouse** [comment]
The shopping lists can be used to simulate exporting a full scan data, using a generic search term like [lvl <= 60] (which takes a while to load all the item names), or using [Tradeskill] (which is a bit faster) to get all the reagent prices.
