### ISSUE TITLE
Export results

### ISSUE THREAD

**Issue by 8150565** [Auctionator/Auctionator#951]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

_Please include a brief description of the bug, including what you were doing, and when it occurred._

## Steps to Reproduce

_Include the steps I would need to follow to reproduce the bug._

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by 8150565** [comment]
During data export, the item price is not comma separated. example (at the auction the price is 1000g15s20b) it would be nice to make 1000.15 during export (excluding bronze) Suggestion, not a bug

**Comment by plusmouse** [comment]
The data is just what Auctionator is using internally. You can use formulas in a spreadsheet editor to extract the gold and silver though.
[example of data usage.xlsx](https://github.com/Auctionator/Auctionator/files/5729801/example.of.data.usage.xlsx)

Sheet1 is the raw data, and Sheet2 is the processed data with the formulas.

**Comment by 8150565** [comment]
> You can use formulas in a spreadsheet editor to extract the gold and silver.
> [example of data usage.xlsx](https://github.com/Auctionator/Auctionator/files/5729801/example.of.data.usage.xlsx)
> 
> Sheet1 is the raw data, and Sheet2 is the processed data with the formulas.
> 
> Does that help?

Yes, its help, nice solution!
