### ISSUE TITLE
Cancelling auctions / undercut scan

### ISSUE THREAD

**Issue by clawwd** [Auctionator/Auctionator#953]
Hi,

Not 100% sure if this is a bug or maybe something with an addon causing issues.

I post a ton of auctions which are usually in the $30k+ range and several times a day I run undercut and cancel and repost them. I can get through like may 10 of them before the auctionator starts slowing down to a crawl saying "retrieving item info" or something like that. Once this happens, I can only click the "Cancel Undercut" button every 5 or more seconds for the remainder of the time so it probably takes me 15 mins total. Is this being seen by everyone or is there a workaround?

**Comment by plusmouse** [comment]
It's a known problem. To reduce the load on the auction house servers blizzard limited how many cancellations can be done in a minute. There is no fix.

**Comment by clawwd** [comment]
Got it. Thanks for the reply!
