### ISSUE TITLE
Tooltip for selling tab items should not block listing

### ISSUE THREAD

**Issue by DenL** [Auctionator/Auctionator#955]
**Is your feature request related to a problem? Please describe.**
Currently, mouseover an item in the selling tab would show tooltip as such blocking the listings:
![image](https://user-images.githubusercontent.com/5632219/103123611-ee0ca200-4652-11eb-99c9-a7cd1f7744c1.png)

**Describe the solution you'd like**
Tooltip should preferably be to the side of the AH frame like in the default UI
![image](https://user-images.githubusercontent.com/5632219/103123565-c289b780-4652-11eb-8bde-e2315ab160d5.png)

**Describe alternatives you've considered**
I think the above solution is the best.

**Additional context**
N/A

**Comment by plusmouse** [comment]
I've tested having the tooltip to the side, it doesn't appear to help, and feels odd as the tooltip is no longer directly linked to the icon it was related to:
![image](https://user-images.githubusercontent.com/60280559/128249680-f5b65e4a-ea73-4099-a309-a68dbc5624cf.png)

Closing as "won't fix".
