### ISSUE TITLE
Auctionator disrupts Guild Notes

### ISSUE THREAD

**Issue by Danny953** [Auctionator/Auctionator#956]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

When I try to change a Guild Member's Note or Officer Note, Auctionator bugs out and prevents me from making the change.

## Steps to Reproduce

Sign in, attempt to change a guild note.

## Loaded Addons

Altoholic
AtlasLoot
Bugsack & Buggrabber
Bartender 4
Bagnon
Neatplates
Omen3
OmniCC
Scrap
Titan Panel
TomTom
Weakauras
DBM 

## Back Trace (LUA Error Output)

1x [ADDON_ACTION_FORBIDDEN] AddOn 'Auctionator' tried to call the protected function 'SetNote()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `SetNote'
[string "@FrameXML\StaticPopup.lua"]:2691: in function `EditBoxOnEnterPressed'
[string "@FrameXML\StaticPopup.lua"]:4919: in function `StaticPopup_EditBoxOnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

**Comment by plusmouse** [comment]
This kind of issue is tricky as the error message sometimes specifies the wrong addon to blame, or references the wrong code, there is a way to get more accurate information though:

Could you please run this command in-game directly after loading your character:
```
/console taintLog 1
```
And then play until you get these errors again? Once you do, please log out immediately and then upload the contents of `World of Warcraft\_retail_\Logs\taint.log` to [pastebin ](https://pastebin.com) and paste the link here.

The file will tell me what in Auctionator is causing the problem.

**Comment by Danny953** [comment]
https://pastebin.com/1zEaLamY

Looks like it may be Bagnon messing with it.

**Comment by plusmouse** [comment]
Is this issue still affecting you?

**Comment by plusmouse** [comment]
Fixed in alpha 512
