### ISSUE TITLE
Cancel and Post item refresh

### ISSUE THREAD

**Issue by clawwd** [Auctionator/Auctionator#958]
Hi,

I see a lot of answers to concerns over the time it takes to  cancel items as some Blizzard new rule but I dont think the problem with this addon is that. I believe the problem is that the addon tries to refresh each time which is causing the issues. Example: you cancel an item via the "cancel undercut"... the addon seems to scan again for the validity of the item being undercut currently before allowing a cancel.

Can you duplicate this or try and cancel this quivery to see if it stops the issue? I can totally  help you edit this out if you are good with it.

**Comment by plusmouse** [comment]
Removing the query is a one line change, if you want to try it:
```diff
diff --git a/Source/Tabs/DataProviders/Cancelling.lua b/Source/Tabs/DataProviders/Cancelling.lua
index 6c223b6..5c39f82 100755
--- a/Source/Tabs/DataProviders/Cancelling.lua
+++ b/Source/Tabs/DataProviders/Cancelling.lua
@@ -126,7 +126,7 @@ function AuctionatorCancellingDataProviderMixin:OnEvent(eventName, auctionID, ..
     if tIndexOf(self.waitingforCancellation, auctionID) ~= nil then
       table.insert(self.beenCancelled, auctionID)
     end
-    self:QueryAuctions()
+    self:PopulateAuctions()

   elseif eventName == "OWNED_AUCTIONS_UPDATED" then
     self:PopulateAuctions()
```

**Comment by plusmouse** [comment]
I've had a look. The cancelling takes place immediately (you can see the yellow message appear in chat). The delay is waiting for an updated list of auctions _after_ cancelling. I've checked the Blizzard code for the vanilla AH, it also refreshes the list of auctions after a cancellation, and has the same delay, it just doesn't show a loading spinner.

**Comment by clawwd** [comment]
Hi Plusmouse,

Sorry for the late reply but TY for looking into this.

**Comment by plusmouse** [comment]
I've spent more time on the issue, and made it so there is less refreshing in alpha 454

**Comment by clawwd** [comment]
Happy New Year Plusmouse.

Nice and thank you for your hard work. It is truly nice to see someone
taking pride in their work
