### ISSUE TITLE
Auction price in tooltip doesn't take legendary rank into account

### ISSUE THREAD

**Issue by flow0284** [Auctionator/Auctionator#959]
In my bag i have one Umbrahide Armguards with itemlevel 235 (rank 4) the tooltip shows me the auctionprice for the one with itemlevel 190 (rank 1)

![WoWScrnShot_122720_150329](https://user-images.githubusercontent.com/27314841/103172584-c38a3700-4854-11eb-9f01-c36eb76825b0.jpg)

**Comment by mlopezv86** [comment]
I would also extend the range of this request adding item level to count filtering, I guess the fix approach would be really close to miss the chance to insta-reuse the fix code.
ATM when highlighting an item like flow0284 is doing you get that item count based only on item ID. If I have for example 2 shadowghast necklaces 225 and 2 shadowghast necklaces 235 on my inventory, the tooltip will show a count of 4 regardless the variant.

PS: Sorry if this deserves a new issue posting. Hopefully I'm right and the fix could be reused for both.

**Comment by plusmouse** [comment]
I don't think Auctionator counts how many of an item you have in your bag. You'll need to report the issue to your bag addon developer.

**Comment by plusmouse** [comment]
Fixed in alpha 514
