### ISSUE TITLE
Auction cancel scan / cancelling items causes screen to jump up and down

### ISSUE THREAD

**Issue by addonaddict** [Auctionator/Auctionator#961]
Hi,

Is there any way to make it like TSM? The list keeps scrolling up and down like crazy each time item is cancelled or continuously while doing undercut scanning
This makes cancelling many items a total pain
TSM does it very quick without any wait time, is there something that can be done to mirror same funcitonality?
I love Auctionator and really dont want to have to make the switch..
Thank you :)

**Comment by plusmouse** [comment]
This should be fixed in alpha 454.

**Comment by addonaddict** [comment]
Test alpha 454 and it is not fixed, made it worse in fact
Now when scanning for undercats, each item hangs the whole game for the same amount of time that it took before to make the screen jump up and down
If you sort auctions by price, the "jumping up and down" still remains
When cancelling, the whole game again hangs for the same amount of time that it was jumping up and down before
Opening an issue again just in case this is the wrong place to comment - not sure why issues are being closed before they're even tested.

Thanks
