### ISSUE TITLE
Feature Request: Do not undercut own auctions

### ISSUE THREAD

**Issue by addonaddict** [Auctionator/Auctionator#962]
Self explanatory, I constantly undercut my own auctions because I didnt post the whole quantity right away
This causes the addon to spit out warning that item is undercut when doing undercut scan
Default behavior (or with toggle in options) should be to match price of owned auctions
Thanks

**Comment by plusmouse** [comment]
Not an issue. Tested and it doesn't report as undercut.
![image](https://user-images.githubusercontent.com/60280559/103477895-fd11f380-4dba-11eb-9c97-8e60dc6ff85a.png)
