### ISSUE TITLE
Lag/freezing when cancelling tab updates

### ISSUE THREAD

**Issue by addonaddict** [Auctionator/Auctionator#963]
Test alpha 454 and it is not fixed, the jumping is (somewhat) fixed but lag appeared
Now when scanning for undercuts, each item hangs the whole game for roughly 1-2 seconds
Sometimes the screen freezing does not stop even after the undercut scan is complete, goes away maybe after 30 sec or so
_If you sort auctions by price, the "jumping up and down" still remains_

Is there any way to make it like TSM, where you can cancel without any lag whatsoever?
I dont think on TSM you can pick and choose what to cancel first, but they have a skip button instead so the user is following a list from top down. Dont know if that is relevant at all

Thanks

**Comment by plusmouse** [comment]
Can you try alpha 456?

**Comment by addonaddict** [comment]
Working good so far
Cancel scan still lags out the game, although slightly less lag per item (not sure if it's because I have less addons turned on this time around)
Cancelling each item 1 by 1 also lags out the screen, the jumping is gone though after some minor testing

The way I see it - if you are able to get rid of the screen freezing and add option to use a macro on button mouseover, a lot more people will use auctionator over TSM
I know you declined my previous feature request for the macro and explained that you already have a "macro" that can do this, but it is not enough to warrant the users to actually use it, besides  the fact that i didnt even know of it's existence until I asked

Hoping you would reconsider..
If you need anything else tested out let me know
Thank you!

**Comment by plusmouse** [comment]
It shouldn't be causing the screen to lag out - I'd suspect another addon is interfering, can you please try cancel scanning with just Auctionator enabled?

**Comment by addonaddict** [comment]
Alpha458:
Minor lag is present on each item scan, both for undercut scan and during undercutting the items (lags for same amounts)
Tested with and without addons on 2 separate PC's
I was also in silvermoon (0 people around) with 24ms home/world if that helps at all. Although the lag is graphical, not internet
It is not really game breaking so if theres no way out of this, then it's not too much of a big deal. Just not sure how TSM manages to do it without any lag whatsoever

Let me know if you want me to test anything else, thx

**Comment by plusmouse** [comment]
Just checking, does the entire WoW client freeze, not just the cancelling view? I've tested repeatedly on my computer, the wow client doesn't freeze.

A slight lag between cancellations and the view updating is normal though - we wait for the WoW API to report the item as cancelled before removing it from the view. The faded out auction is used to indicate that we're waiting.

I can change it so that the auction disappears the instant you click on it, but it won't be cancelled for another split-second?

**Comment by plusmouse** [comment]
As the client isn't freezing, I'm closing this issue (comment here if it is and I'll reopen it).

**Comment by addonaddict** [comment]
Yes the lag is present although somewhat minor. You notice it when moving your camera around while scanning
If you say it doesnt happen for you then maybe it's an isolated issue. Although as i said, TSM manages to do it without any issues whatsoever (but then again i dont know code so pardon if theres some specific reason for it)
Lets see if other players report it, thx

**Comment by plusmouse** [comment]
Can you try this version and see if the lag is still present?

[Auctionator-AuctionCache.zip](https://github.com/Auctionator/Auctionator/files/5774377/Auctionator-AuctionCache.zip)

**Comment by addonaddict** [comment]
Yes that works! Lag is gone when canceling items
Same lag is present when scanning for undercuts, though (which is not an issue if there is no easy solution)

**Comment by addonaddict** [comment]
**update**
After about 10 minutes it is back to normal behaviour with (somehat less) lag each time you cancel undercut item
No idea what is going on... :/

**Comment by addonaddict** [comment]
Tested for about 6 hours on and off
Lag amount seems to vary, sometimes a lot, sometimes almost not noticable
I use auctionator together with TSM, i do not notice any lag whatsoever when doing anything with TSM, auctionator I do
Hope this helps, no idea what could be causing this

**Comment by plusmouse** [comment]
Its possible TSM is interfering, I've just tested and found that when TSM is enabled cancelling an auction makes the list of items in the "Cancelling" tab change order, this doesn't happen when TSM is disabled.

**Comment by plusmouse** [comment]
Just tested with TSM enabled, I get the freeze. This issue won't be fixed as it's likely an interaction between 2 add-ons that is causing this issue. If something else comes up that suggests it can happen when _only_ Auctionator is enabled I'll look at the issue again.

**Comment by plusmouse** [comment]
I've made another modified version of Auctionator which might fix the problem.

[Auctionator-QueryChecking.zip](https://github.com/Auctionator/Auctionator/files/5781151/Auctionator-QueryChecking.zip)

**Comment by addonaddict** [comment]
This is strange because I disabled all my addons EXCEPT auctionator, turned off TSM desktop app, relocated WTF and Interface folders so the game can make brand new ones + I added your auctionator-querychecking verison to test. The lag is still there with a fresh UI and is quite a bit heavier (about .5-.7 seconds PER item undercut scan) this slows down the scanning quite a bit
Same heavy lag is present during item cancelling
I also ran /console cvar_default just in case during the resetting to make sure everything is 100% clean

My internet connection is perfectly stable 21ms with gtx1070 and i7 6770k + SSD, + 16gb ddr4 ram (300fps in silvermoon) 
 just in case PC performance is a possibility

i uploaded a vid example in case it helps
https://filebin.net/nnav7wo3l1l4a7uy

**Comment by plusmouse** [comment]
OK. There's definitely an issue there. I'm not sure what's causing it, I'll keep looking for a solution though.

**Comment by plusmouse** [comment]
Please can you try this version, fingers crossed it solves the problem 😃 

[Auctionator-UpdateDecrease.zip](https://github.com/Auctionator/Auctionator/files/5782616/Auctionator-UpdateDecrease.zip)

**Comment by addonaddict** [comment]
The error below happens when inside shopping, selling, and cancelling tabs created by auctionator:
This error is being output constantly if window is open, 326 errors in about 30 sec or so
BUT on the other hand, the lag has completely vanished!!! :D
Almost there haha
Let me know if you want anything else tested

301x ...Source\Tabs\ResultsListing\Mixins\ResultsListing.lua:118: attempt to index field 'DataProvider' (a nil value)
[string "@Auctionator\Source\Tabs\ResultsListing\Mixins\ResultsListing.lua"]:118: in function <...Source\Tabs\ResultsListing\Mixins\ResultsListing.lua:113>

Locals:
self = <unnamed> {
 0 = <userdata>
 tableBuilder = <table> {
 }
 InitializeDataProvider = <function> defined @Auctionator\Source\Tabs\ResultsListing\Mixins\ResultsListing.lua:43
 CustomiseColumns = <function> defined @Auctionator\Source\Tabs\ResultsListing\Mixins\ResultsListing.lua:189
 ClearColumnSorts = <function> defined @Auctionator\Source\Tabs\ResultsListing\Mixins\ResultsListing.lua:183
 OnUpdate = <function> defined @Auctionator\Source\Tabs\ResultsListing\Mixins\ResultsListing.lua:113
 ScrollFrame = <unnamed> {
 }
 columnSpecification = <table> {
 }
 OnShow = <function> defined @Auctionator\Source\Tabs\ResultsListing\Mixins\ResultsListing.lua:102
 Init = <function> defined @Auctionator\Source\Tabs\ResultsListing\Mixins\ResultsListing.lua:3
 dataProvider = <unnamed> {
 }
 EnableSpinner = <function> defined @Auctionator\Source\Tabs\ResultsListing\Mixins\ResultsListing.lua:254
 DisableSpinner = <function> defined @Auctionator\Source\Tabs\ResultsListing\Mixins\ResultsListing.lua:260
 HeaderContainer = <unnamed> {
 }
 RestoreScrollPosition = <function> defined @Auctionator\Source\Tabs\ResultsListing\Mixins\ResultsListing.lua:63
 UpdateForHiding = <function> defined @Auctionator\Source\Tabs\ResultsListing\Mixins\ResultsListing.lua:207
 isInitialized = true
 CustomiseDropDown = <unnamed> {
 }
 InitializeTable = <function> defined @Auctionator\Source\Tabs\ResultsListing\Mixins\ResultsListing.lua:121
 ReceiveEvent = <function> defined @Auctionator\Source\Tabs\ResultsListing\Mixins\ResultsListing.lua:36
 UpdateTable = <function> defined @Auctionator\Source\Tabs\ResultsListing\Mixins\ResultsListing.lua:158
 PopulateOverride = <function> defined @Auctionator\Source\Tabs\ResultsListing\Mixins\ResultsListing.lua:73
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'DataProvider' (a nil value)"

**Comment by plusmouse** [comment]
Awesome. The latest alpha (459) has the fix in it. Closing this issue now, hopefully for the last time 😄

**Comment by addonaddict** [comment]
Great! Thank you so much for this, its smooth as butter now

**Comment by addonaddict** [comment]
Not sure if this happened due to the changes you made or not but when in "selling" tab:
When cancelling own undercut auctions, addon does a "refresh" after every single item that takes 1-3 seconds . Before i was able to cancel few at a time without any wait or refreshes.
Just bringing it up in case there was some issue that arose
Sorry haha :D

![image](https://user-images.githubusercontent.com/73442541/103966359-b5c69280-512d-11eb-8715-b19e352c2973.png)

**Comment by plusmouse** [comment]
The refresh is normal, getting it without a noticeable refresh before was just a fluke.

**Comment by addonaddict** [comment]
thank you
