### ISSUE TITLE
Eternal Crystal - bug when posting /w favourites in Sell tab

### ISSUE THREAD

**Issue by addonaddict** [Auctionator/Auctionator#965]
Error reproduced each time when posting Eternal Crystal (purple enchanting material) while having it in favourites
Does not happen to any other item

13x ...\Auctionator\Source\Tabs\Selling\Mixins\SaleItem.lua:522: Usage: local itemExists = C_Item.DoesItemExist(emptiableItemLocation)
[string "=[C]"]: in function `DoesItemExist'
[string "@Auctionator\Source\Tabs\Selling\Mixins\SaleItem.lua"]:522: in function `PostItem'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals:
(*temporary) = nil

**Comment by plusmouse** [comment]
Fixed in alpha 458
