### ISSUE TITLE
Feature Request: additional item types for "default quantity"

### ISSUE THREAD

**Issue by addonaddict** [Auctionator/Auctionator#966]
**Is your feature request related to a problem? Please describe.**
I want to be able to set a default posting quantity per item type, which is available in Auctionator, but is very limited (essentially to gear/pets and EVERYTHING else. So if I want to post lets say 5 enchants max, 20 potions max, 200 herbs max - the user is forced to either enter it 1 by 1 manually or set the setting to 0 to default to maximum. This is the big benefit to TSM, which I would love if you could incorporate to Auctionator :)

Example of types of items to be configurable in terms of max quantity:
1. Gear/Pets (existing)
2. Potions/Flasks
3. Enchants/similar consumables
4. Herbs/Ores/Skins

There might be more categories but this is all I could come up with quickly, hope you can consider this
Thanks :)

**Comment by addonaddict** [comment]
Is there any poossibility for this to be implemented in the future? It would be a MASSIVE quality of life improvement for this addon
Flasks usually should be put at about 20 pcs per due to their high demand, while potions in SL should go at about 10 pcs max. due to all the undercutters (this is for my serfver at least)
Hope you can consider this, and allow broader customization for different item types (not just potions, but pots AND flasks for example)
thx

**Comment by plusmouse** [comment]
Doesn't have pot vs flask customisation, but the feature is available in alpha 555 https://github.com/Auctionator/Auctionator/releases/tag/555-alpha
