### ISSUE TITLE
Post with return key

### ISSUE THREAD

**Issue by NKatic** [Auctionator/Auctionator#967]
Hello, 
first of all, great addon, thank you all for your effort.

Would it be possible to confirm actions with return key?
For example,
in the selling tab, you enter a quantity, say 2, and while the caret is in the quantity box, you press a button on your keyboard and the item is posted to the ah. The same logic is implemented when adding an item to a shopping list, return key confirms, the item is added to the list and the small window is closed.

Happy new year!

**Comment by plusmouse** [comment]
Pressing [ENTER] already works for adding shopping list items.

**Comment by NKatic** [comment]
> Pressing [ENTER] already works for adding shopping list items.

Yes, I've used that as an example. I've said the logic is implemented for the shopping list items and it would be great if it would be implemented in the selling tab.

**Comment by plusmouse** [comment]
Find this in alpha 527
