### ISSUE TITLE
Skip button

### ISSUE THREAD

**Issue by Anatharias** [Auctionator/Auctionator#969]
**Is your feature request related to a problem? Please describe.**
No problem in particular, just that when I want only 2 auctions posted, for instance, and that I still have the same item in my bag, auctionator doesn't skip it based on the amount specified in the option panel (Which is related to number of items to post).
So I need to manually click on the next item, but first I need to check the icons to see which one I'm reviewing.

Same apply if I don't want to post an item for any reason

**Describe the solution you'd like**
A skip button, just next to post, to skip the posting of a given item

**Describe alternatives you've considered**
The skip could be automatic if:
- the "Default quantity" is reached
and
- I'm the current best seller for a given item

Bonus request: 
Keybinds to:
1. Post
2. Skip

**Comment by addonaddict** [comment]
I second this - very tedious to try and find which item you stopped at (especially in favourites)
A skip button would help a lot, and a keybind too if possible
Auctionator is close to being perfect but there are these little things that could make it much more efficient

Thank you :)
