### ISSUE TITLE
Feature Request: ignore item at undercut scan

### ISSUE THREAD

**Issue by addonaddict** [Auctionator/Auctionator#970]
**Is your feature request related to a problem? Please describe.**
There are items you post that have been massively undercut by someone. If I post above them, i dont want that to show up on the undercut scan together with everything else. When spamming the cancel macro/button, I accidentally cancel the item that is 
"undercut" but not really undercut.

**Describe the solution you'd like**
2 solutions:
1. easy - add ignore item checkbox or something in undercut scan window + a button to reset filter.
2. harder, maybe? - add an option in auctionator settings to ignore items that were set to lower price at time of posting. This way undercut scan ignores them.

**Comment by plusmouse** [comment]
This is unlikely to be implemented, as it would complicate the UI to cope with an edge case.
