### ISSUE TITLE
Bug when cancelling items quickly via direct click VS button/macro

### ISSUE THREAD

**Issue by addonaddict** [Auctionator/Auctionator#972]
When clicking an item directly to cancel - it cancels it quickly. You may also click on many items at once, and the addon will cancel all of the items you clicked (after a short delay). This is a quick method
Using a button/button macro works differently - it will let you cancel items if you click it slowly 1 item at a time, but as soon as you start spamming it at same speed as you're clicking items directly - then some items (majority of them) will turn grey and will skip being cancelled. For these items the button/macro will no longer work. You would have to cancel them manually by clicking on them.

Note that this is not due to blizzard throttle, it happens even before throttle kicks in every time.
You can recreate by having lots of items that are undercut-then try spam clicking on items, then try again but spam the button/macro to do the same thing. Both act differently. 

Both ways (should) have the same speed in ideal world

![image](https://user-images.githubusercontent.com/73442541/104406166-b051b980-552c-11eb-8cb4-9784e7579983.png)

**Comment by plusmouse** [comment]
Modified the button code so it should perform better

**Comment by addonaddict** [comment]
great will test it out appreciate the willingness to improve things
