### ISSUE TITLE
Scroll bar disappears in cancelling mode during scan, list sorts itself after click-cancelling 1 item after scan

### ISSUE THREAD

**Issue by addonaddict** [Auctionator/Auctionator#973]
As described in title - scroll wheel sometimes disappears during cancel scan for whatever reason until you click in scroll area and start scrolling, then it reappears
Also, each time after cancel-scanning... after you click on first item to cancel it, list re-sorts itself, so you have to go and try to find the item again, which is painfully annoying if you';re cancelling specific item

Happens with no other addons involved, alpha 460

thank you

**Comment by plusmouse** [comment]
The scroll wheel is fixed.
