### ISSUE TITLE
Cancel scan stops whenever auctions sell (and maybe when they expire too?)

### ISSUE THREAD

**Issue by addonaddict** [Auctionator/Auctionator#974]
As described in title - cancel scan stops completely whenever something sells and you get noficaition in chat. Youre forced to re-scan from start. Recreate by scanning while someone (2nd acc?) buys out one of your items. Happened many many times now. Alpha 460

**Comment by addonaddict** [comment]
happens on latest alpha build - currently selling a lot of high movement goods like power flasks, and my undercut scans constantly stop 1/4 way 1/2 way through etc
Pretty annoying x_x

**Comment by plusmouse** [comment]
Fix in alpha 469

**Comment by addonaddict** [comment]
thanks
