### ISSUE TITLE
Feature Request: Progress bar at undercut scan window

### ISSUE THREAD

**Issue by addonaddict** [Auctionator/Auctionator#975]
A lot of the time I find myself start cancelling auctions before the cancel scan actually finishes as I tend to sort by "undercut?" so I cannot tell if it completes until I actually scroll all the way down
Any chance a progress bar can be added or something so we can tell how many items left to scan before it's completed? Would be a massive QoL improvement for an AH goblin like myself :)

quick example:
![image](https://user-images.githubusercontent.com/73442541/104665780-3cd0b900-56a0-11eb-9fa6-b71080ac7399.png)

thanks! :)

**Comment by plusmouse** [comment]
The "Undercut Scan" button reactivates when the scan is finished

**Comment by addonaddict** [comment]
tbh never noticed this, sorry to waste ur time then, thank you. ill pay attention to the button ( i started using the macro instead so i wasnt even looking at button before hehe)
