### ISSUE TITLE
Auctionator & Guild Management

### ISSUE THREAD

**Issue by Hope810** [Auctionator/Auctionator#980]
With Auctionator installed I sometimes have trouble ranking my guild members. I am the GM. I get a message that states "Auctionator has been blocked from an action only available to the Blizzard UI. You can disable this addon and reload the UI." I am given two buttons {Disable} and {Ignore}.

**Comment by plusmouse** [comment]
This appears to be similar to #956 . I've tried sorting the guild I'm in by rank (I'm not a GM though) and can't get the bug to replicate. I'll leave this bug open though until we can find a resolution.

**Comment by Hope810** [comment]
Yes, this is happening as well. Love your addon by the way. 😊

Heather Monceaux-Cooley
Maintenance & Reliability Analyst I

Equistar Chemicals, LP
Lake Charles Polymers Plant
4101 Hwy 108 South
Westlake, Louisiana 70669
Office: +1 337.430.6753
Cell: +1 337.526.9949
Fax: +1 337.439.7397

Heather.Monceaux-Cooley@lyondellbasell.com<mailto:Heather.Monceaux-Cooley@lyondellbasell.com>
Heather.Monceaux-Cooley@lyb.com<mailto:Heather.Monceaux-Cooley@lyb.com>
www.lyondellbasell.com<http://www.lyondellbasell.com/>


[LYB_signature_logo]

**Comment by plusmouse** [comment]
Is this issue still affecting you?

**Comment by Hope810** [comment]
Yes it is still happening. This is the message I get ..... if it helps.

[cid:b1260a20-b9ea-48f3-8820-e5c4ac0f3d93]

Heather Monceaux-Cooley
Maintenance & Reliability Analyst


Equistar Chemicals, LP
Lake Charles Polymers Plant
4101 Hwy 108 South
Westlake, Louisiana 70669
Office: +1 337.430.6753
Cell: +1 337.526.9949
Fax: +1 337.439.7312

Heather.Monceaux@lyondellbasell.com<https://webmail.lyondellbasell.com/owa/redir.aspx?C=e7b0ef1b032d42748bedf8bbac246aed&URL=mailto%3aHeather.Monceaux%40lyondellbasell.com>
www.lyondellbasell.com<https://webmail.lyondellbasell.com/owa/redir.aspx?C=e7b0ef1b032d42748bedf8bbac246aed&URL=http%3a%2f%2fwww.lyondellbasell.com%2f>

[Description: LyondellBasell]<https://webmail.lyondellbasell.com/owa/redir.aspx?C=e7b0ef1b032d42748bedf8bbac246aed&URL=http%3a%2f%2fwww.lyondellbasell.com%2f>

[Description: Goal Zero]


________________________________

**Comment by plusmouse** [comment]
Does this error happen when only Auctionator is enabled?

**Comment by plusmouse** [comment]
Actually, I can verify the issue (managed to replicate it). Working on solution :)

**Comment by Hope810** [comment]
Ah! Thank you soooooooooo much!!

Heather Monceaux-Cooley
Maintenance & Reliability Analyst I

Equistar Chemicals, LP
Lake Charles Polymers Plant
4101 Hwy 108 South
Westlake, Louisiana 70669
Office: +1 337.430.6753
Cell: +1 337.526.9949
Fax: +1 337.439.7397

Heather.Monceaux-Cooley@lyondellbasell.com<mailto:Heather.Monceaux-Cooley@lyondellbasell.com>
Heather.Monceaux-Cooley@lyb.com<mailto:Heather.Monceaux-Cooley@lyb.com>
www.lyondellbasell.com<http://www.lyondellbasell.com/>


[LYB_signature_logo]

**Comment by plusmouse** [comment]
Fixed in alpha 512 (message back if you're not sure how to get it).

**Comment by Hope810** [comment]
Got it! Much appreciated.  😊



Heather Monceaux-Cooley
Maintenance & Reliability Analyst I

Equistar Chemicals, LP
Lake Charles Polymers Plant
4101 Hwy 108 South
Westlake, Louisiana 70669
Office: +1 337.430.6753
Cell: +1 337.526.9949
Fax: +1 337.439.7397

Heather.Monceaux-Cooley@lyondellbasell.com<mailto:Heather.Monceaux-Cooley@lyondellbasell.com>
Heather.Monceaux-Cooley@lyb.com<mailto:Heather.Monceaux-Cooley@lyb.com>
www.lyondellbasell.com<http://www.lyondellbasell.com/>


[LYB_signature_logo]
