### ISSUE TITLE
Feature Request / Bug Report: Sorting items

### ISSUE THREAD

**Issue by addonaddict** [Auctionator/Auctionator#981]
Favourite items are not being properly sorted, makes quickly checking undercuts of specific sets like one in the photo a bit annoying with many favourites
Ideally it should be sorted by type of items - in this case all gear should be together, preferably first sorted by item, then my name, so that the whole set is together, potions are all together, flasks are together, etc.

Thanks

![image](https://user-images.githubusercontent.com/73442541/105355314-f4ddf480-5bbf-11eb-84b8-2a96ac1146fe.png)

**Comment by addonaddict** [comment]
Update: sorting seems off even in the normal list, not just favourites
example:
![image](https://user-images.githubusercontent.com/73442541/105432994-c0e9ea00-5c26-11eb-9316-7dfff47f701e.png)

3 legendary pieces in a row, then random items, then last item is another legendary piece of the same kind
all 4 should be together in my opinion

**Comment by plusmouse** [comment]
The items in the selling tab use the same ordering the items have in your bags, so long as your bags remain sorted, they should appear grouped how you want them too.
