### ISSUE TITLE
Request: remove chat spam when using Auctionator cancel item macro

### ISSUE THREAD

**Issue by addonaddict** [Auctionator/Auctionator#983]
![image](https://user-images.githubusercontent.com/73442541/105642226-78b10e80-5e56-11eb-990a-3c9c0170123d.png)

The whole point of a macro is to simplify the process of cancelling mass auctions, it works (not nearly as good as TSM) but it does spam your chat when you use it
I tend to watch chat for deals / post items on trade chat so its kind of annoying to have to scroll
I know you can probably divert the spam to another tab but i find it completely unnecessary

If possible please remove it all together or put a "notification" alert inside Auctionator window itself that appears for 2-3 seconds to say that macro was used, if telling the user that they pressed a button is actually needed..

thank you

**Comment by plusmouse** [comment]
Won't fix.

**Comment by addonaddict** [comment]
unfortunate.
is there a way to edit your code to remove this obnoxious feature?
thx
