### ISSUE TITLE
Sellers Names Column

### ISSUE THREAD

**Issue by Galthariel** [Auctionator/Auctionator#984]
Maybe it's there but I couldn't find where but Seller names is important, at least for me. Thanks :-)

**Comment by addonaddict** [comment]
Yes please... right now you can see names by hovering over each item. TSM manages to scan it during post and show you who owns the auction right in the window, even for materials and such

perhaps narrow down the left items column and add another  tab for sellers? i think other tabs can be shrunk too to accomodate
would be great QoL feature
![image](https://user-images.githubusercontent.com/73442541/105996767-c4430280-6078-11eb-8651-b8f62156def6.png)

**Comment by plusmouse** [comment]
Find it in alpha 484 (right-click the column headers and enable the "Seller(s)" column):
![image](https://user-images.githubusercontent.com/60280559/107365741-25d18b00-6ad5-11eb-9400-739ccee00859.png)
