### ISSUE TITLE
Request: more precise time left

### ISSUE THREAD

**Issue by addonaddict** [Auctionator/Auctionator#985]
Self-explanatory, would be great to see exactly how much time is left instead of it being rounded to 1 hour. I like to cancel auctions that are about to be gone and repost if i log on to do AH. currently have to switch to blizz UI and do it slowly there.

Also color-coding of time like in blizz UI would be a neat addition

Auctionator:
![image](https://user-images.githubusercontent.com/73442541/106000878-4e8d6580-607d-11eb-9add-cf17e08aaed4.png)

BlizzardUI:
![image](https://user-images.githubusercontent.com/73442541/106000910-56e5a080-607d-11eb-896e-39a834b60131.png)

**Comment by plusmouse** [comment]
Would showing the time as decimals below 1 help?
![image](https://user-images.githubusercontent.com/60280559/107157668-353dc080-697d-11eb-8081-b201a77b0d62.png)

**Comment by addonaddict** [comment]
Yes this works if replicating blizzard style is too time consuming or difficult
I wouldnt mind seeing it as 0.07 for 7 minutes for example, and 0.2 for 20 minutes and higher, if possible
Would also love it if anything below 1 hour could be color-coded in red like blizzard does it so the user doesnt have to sort everything by time to decide what to cancel

thank you

**Comment by plusmouse** [comment]
Only auctions below 1 hour are listed as "1" in the time left field currently - so you can cancel your almost finished auctions just by selecting those with the 1 in them?
