### ISSUE TITLE
Improve compatibility when using together with TSM

### ISSUE THREAD

**Issue by addonaddict** [Auctionator/Auctionator#986]
These days TSM is extremely helpful to have even if you dont use the auction module. The ledger module itself is extremely helpful. There are many times when TSM cant handle some crafting/posting methods like crafted ranked gear, at which the user is forced to either use blizz auction or other addon like Auctionator/Auctioneer.
When using TSM together with Auctionator few major problems occur:

1. as you know from before, cancel scan jumps up and down when cancelling items. does not happen with TSM disabled. Extremely frustrating!! Normal behaviour should be to disable TSM from refreshing anything while inside auctionator's undercut or selling windows.

2. When auctions expire or sold, you get notification in chat and your auctionator window completely refreshes along with any settings you picked for the item you're posting. This is very annoying when you are trying to post items to sell. I have already posted 10 pieces of 225 legendary gear for 3g each because auctionator window was spazzing out when few items were expiring and lost over 100k in 10 seconds because of it. Normal behaviour should disable any refreshing when items expire (both in undercut and sell windows)

3. may not be TSM issue but I will leave it here - time left: part of the tooltip when hovering over an item in auctionator sell window simply does not work, never have. not sure what the issue is here. 
![image](https://user-images.githubusercontent.com/73442541/106390554-ec9f6980-63b6-11eb-9717-17b19a336b98.png)
another example:
![image](https://user-images.githubusercontent.com/73442541/106391091-91bb4180-63b9-11eb-99bf-3088eb3389e8.png)

Please consider doing this. Auctionator and TSM are both some of the most used addons out there, they should play well together. Both do things that the other cannot do properly/lacks features in.

Thank you..

**Comment by plusmouse** [comment]
1. Is awkward to fix - disabling a TSM query is out of scope for this addon, possibly modifying our sorting code could resolve the glitch though.
2. Was unaware of. Depending on what query is triggering the reset this could be simple to fix. Testing the case when an auction expires isn't practical.
3. Is now fixed.

**Comment by addonaddict** [comment]
thanks! perhaps coordinating with TSM team would resolve the #1 on their end?
seems to be on their end afterall, and its heavily affecting auctionator in a negative way (for me at least)

**Comment by plusmouse** [comment]
1. Should now be fixed.
2. Is a different issue, can you open a separate issue, including what items you were selling and what items were purchased while you were posting?

**Comment by addonaddict** [comment]
All types of items, addon doesnt discriminate on that
Not 100% sure whther it happens every time, but every time that ive noticed a sale while posting items the window refreshes itself, either because of TSM or auctionator itself, no idea

**Comment by plusmouse** [comment]
I need to know a specific (low cost) item so I can test with it?

**Comment by addonaddict** [comment]
There is no specific item and I dont remember now as i havent played for a while
You can buy a bunch of random mats that have high chance to sell quickly and post them at 1 silver, then start posting something with the sell value entered in and wait for a refresh

All i know is i was selling mainly 168 blue cloth gear + power flasks from Shadowlands + legendary gear + random shadowlands materials when I first noticed it happening if its any help
