### ISSUE TITLE
Scroll resets when cancelling own items - need to scroll all the way down each time

### ISSUE THREAD

**Issue by addonaddict** [Auctionator/Auctionator#987]
As title suggests - when user cancels own auction in selling tab, window will refresh and put you back on top. If you have 10 items to cancel at bottom, this is a pain to deal with.
Please get rid of refresh (not sure why so many things trigger a refresh to be honest, there is a button for that afterall)

![image](https://user-images.githubusercontent.com/73442541/106463603-a48b5000-6465-11eb-9345-8d8e6cd24069.png)

thanks

**Comment by plusmouse** [comment]
The refresh won't be removed.

**Comment by addonaddict** [comment]
Thats unfortunate that you do not view it as amateur-level coding bugs.
Im glad you are still considering/fixing other problems though. Most users do not bother to go make account on github to announce every issue they have with the addon, they just boot up WoWup and replace it with auctioneer or TSM.
Either way, addon is great for casual users who wont notice these obnoxious design decisions unless they post in larger quantities like me

**Comment by plusmouse** [comment]
Leaving outdated information on the screen (which is what the simplest version of removing the refresh would do) is undesirable.

The UI was designed with low quantities (just stacks of potions, actually) in mind - which explains why the large quantities hit issues.

The display will need to be updated somewhat after a cancellation, and a refresh is the simplest way of doing that.

**Comment by addonaddict** [comment]
That can easily be solved by refreshing and then moving back to the position of the slider prior to the refresh, thats what other similar addons do
pushing the user back up after a cancel feels completely unnecessary (refresh isnt the issue, even though noone sits at that screen for 10 minutes straight for the old information to actually make a difference)

**Comment by plusmouse** [comment]
You can try it with that if you want. Additional work is needed to prevent the scroll from being preserved between different items though - which is why I haven't merged it in.

```diff
--- a/Source/Tabs/DataProviders/SearchProvider.lua
+++ b/Source/Tabs/DataProviders/SearchProvider.lua
@@ -132,6 +132,7 @@ function AuctionatorSearchDataProviderMixin:OnEvent(eventName, itemRef, auctionI
     self:AppendEntries(self:ProcessItemResults(itemRef), true)

   elseif eventName == "AUCTION_CANCELED" then
+    self.onPreserveScroll()
     Auctionator.EventBus
       :RegisterSource(self, "AuctionatorSearchDataProviderMixin")
       :Fire(self, Auctionator.Selling.Events.RefreshSearch)
