### ISSUE TITLE
add minimal minimal price 

### ISSUE THREAD

**Issue by xhajnal** [Auctionator/Auctionator#988]
**Is your feature request related to a problem? Please describe.**
add information of minimal price of an item

**Describe the solution you'd like**
When mouse-over an item in inventory, the minimal buyout price (minimal of all sellers, minimal for all queries) for the item.
Either for the whole period or last X-days.

**Comment by plusmouse** [comment]
This would be a historical price, which doesn't reflect the current price - Auctionator deliberately focusses on the latest price only. See [here](https://github.com/Auctionator/Auctionator/wiki/In-item-tooltips,-why-does-Auctionator-display-the-most-recently-scanned-price-rather-than-an-average-of-some-sort)
