### ISSUE TITLE
Auctions that expire or sell cause the Selling tab to refresh

### ISSUE THREAD

**Issue by plusmouse** [Auctionator/Auctionator#993]
All types of items, addon doesnt discriminate on that
Not 100% sure whther it happens every time, but every time that ive noticed a sale while posting items the window refreshes itself, either because of TSM or auctionator itself, no idea

_Originally posted by @addonaddict in https://github.com/Auctionator/Auctionator/issues/986#issuecomment-778199641_

**Comment by plusmouse** [comment]
I need to know at least some specific (low cost) items so I can effectively test the problem.

**Comment by plusmouse** [comment]
@addonaddict There's a fix for this in the latest alpha (498). If it comes up again open a _new_ issue.

**Comment by addonaddict** [comment]
ok thank you will test it out
