### ISSUE TITLE
Feature Request: quick buy keybind in Selling tab - show total gold price on confirmation window

### ISSUE THREAD

**Issue by addonaddict** [Auctionator/Auctionator#994]
Currently when buying items quickly via keybind like Shift+Click in Selling tab you dont get any idea of total gold spent, you have to use quick math in your head to get an idea. A quick total gold amount would help with that + help realize a bad purchase in those few unlucky cases...
![image](https://user-images.githubusercontent.com/73442541/107817616-5f5bfd80-6d44-11eb-853c-280a11190f9f.png)

Perhaps revising the confirm window to include:
total price in gold, silver, copper with coin graphics (to match blizz UI)
total quantity (not needed but i added this for sake of being thorough.. i know you can see the quantity on the normal window behind the confirmation tab)
maybe even add some additional options like who you are buying it from like name1, name2, name3, etc. OR 1 name or Multiple sellers if more than 1 seller

Just a QoL improvement for me, no biggy if you dont agree that it's needed :)
thanks

**Comment by plusmouse** [comment]
Something like:
![image](https://user-images.githubusercontent.com/60280559/107821404-48350400-6d74-11eb-89b3-ebfb10a1e418.png)

?

**Comment by addonaddict** [comment]
Yes thats perfect
