### ISSUE TITLE
Minor feature request: copy seller name under new tab option "Seller(s)" in Selling Menu

### ISSUE THREAD

**Issue by addonaddict** [Auctionator/Auctionator#997]
Love the new option to see the sellers, thank you SO much!!!
I would like to take it a step forward and be able to copy the seller's name (if possible) so user can quickly whisper the seller in hopes of getting a better discount
Would be immensely helpful as for example my server has a ton of ALT codes in peoples names... so annoying!

![image](https://user-images.githubusercontent.com/73442541/107862900-209a7600-6e1e-11eb-99b6-04528acf30fd.png)

thanks!

**Comment by plusmouse** [comment]
It isn't possible to add it, as it has the potential to break other click based shortcuts, and explaining why clicking on the sellers name would do something different to the rest of the row is unwanted complexity.
