### ISSUE TITLE
Tradeskill UI error while not visiting auction house.

### ISSUE THREAD

**Issue by dle0105** [Auctionator/Auctionator#999]
**Please include as much of the following information as possible to help me fix the bug:**

Receive an LUA error when minimizing parent categories in the tradeskill UI

**_Please include a brief description of the bug, including what you were doing, and when it occurred._**

I usually use an addon that will minimize all parent categories in the tradeskill UI with one click. Upon doing so, the error gets thrown. I even disabled all addons except Auctionator and bugsack/bug grabber.

**_Include the steps I would need to follow to reproduce the bug._**

(I tested mining, cooking and enchanting)

What seems to trigger it:

1. Open a tradeskill away from the auction house.
2. Start collapsing parent categories while leaving the child categories within them expanded.
3. Once you get to the last one and collapse it, the error gets thrown.

**## Loaded Addons**

**_Include a list of addons you were running at the time this bug occurred._**

Auctionator 9.0.6
BugSack
!BugGrabber

**## Back Trace (LUA Error Output)**

**_You can get this through the use of !BugGrabber and BugSack addons._**

> 114x Usage: local numReagents = C_TradeSkillUI.GetRecipeNumReagents(recipeSpellID [, recipeLevel])
[string "=[C]"]: in function `GetRecipeNumReagents'
[string "@Auctionator\Source\ReagentSearch\Main.lua"]:22: in function `GetSkillReagentsTotal'
[string "@Auctionator\Source\ReagentSearch\Mixins\Button.lua"]:31: in function `UpdateTotal'
[string "@Auctionator\Source\ReagentSearch\Mixins\Button.lua"]:15: in function <...s\Auctionator\Source\ReagentSearch\Mixins\Button.lua:14>
[string "=[C]"]: in function `SetSelectedRecipeLevel'
[string "@Blizzard_TradeSkillUI\Blizzard_TradeSkillDetails.lua"]:90: in function `SetSelectedRecipeID'
[string "@Blizzard_TradeSkillUI\Blizzard_TradeSkillUI.lua"]:157: in function <...dOns\Blizzard_TradeSkillUI\Blizzard_TradeSkillUI.lua:156>
[string "=[C]"]: in function `OnRecipeChanged'
[string "@Blizzard_TradeSkillUI\Blizzard_TradeSkillUI.lua"]:24: in function `recipeChangedCallback'
[string "@Blizzard_TradeSkillUI\Blizzard_TradeSkillRecipeList.lua"]:494: in function `SetSelectedRecipeID'
[string "@Blizzard_TradeSkillUI\Blizzard_TradeSkillRecipeList.lua"]:316: in function `VerifySelection'
[string "@Blizzard_TradeSkillUI\Blizzard_TradeSkillRecipeList.lua"]:69: in function <...zzard_TradeSkillUI\Blizzard_TradeSkillRecipeList.lua:50>
[string "=[C]"]: ?

> Locals:
(*temporary) = "Usage: local numReagents = C_TradeSkillUI.GetRecipeNumReagents(recipeSpellID [, recipeLevel])"

**Comment by plusmouse** [comment]
Can you try the latest alpha? - there's a fix in it that might solve your problem. Otherwise can you link the add-on so that I can test it and create a solution.

**Comment by dle0105** [comment]
> 
> 
> Can you try the latest alpha? - there's a fix in it that might solve your problem. Otherwise can you link the add-on so that I can test it and create a solution.

All works fine in the latest Alpha, apologies for not trying that before making an issue.

Thanks.
